import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCm2CorpsExercises: ScienceExercise[] = [
  {
    id: 'sc-cm2-com-004',
    subject: 'sciences',
    title: 'Compréhension : rôle du cœur',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Le cœur est un muscle qui bat environ 70 fois par minute. Il envoie le sang dans tout le corps. » — Quelle est la fonction principale du cœur ?',
    options: [
      { id: 'a', text: 'Digérer les aliments', isCorrect: false },
      { id: 'b', text: 'Faire circuler le sang dans le corps', isCorrect: true },
      { id: 'c', text: 'Filtrer l\'air respiré', isCorrect: false },
    ],
    correctAnswer: 'Faire circuler le sang dans le corps',
    explanation: 'Le cœur pompe le sang et le fait circuler dans tout le corps pour apporter de l\'oxygène aux organes.',
    hint: 'Le texte dit qu\'il envoie le sang dans tout le corps.',
    tags: ['cm2', 'sciences', 'corps', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm2-com-005',
    subject: 'sciences',
    title: 'Compréhension : digestion',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Quand on mange, les aliments passent dans la bouche, puis l\'estomac, puis les intestins. Ce trajet s\'appelle la digestion. » — Quel organe vient juste après l\'estomac ?',
    options: [
      { id: 'a', text: 'Le cœur', isCorrect: false },
      { id: 'b', text: 'Les intestins', isCorrect: true },
      { id: 'c', text: 'Les poumons', isCorrect: false },
    ],
    correctAnswer: 'Les intestins',
    explanation: 'Le trajet des aliments est : bouche → estomac → intestins.',
    hint: 'Le texte liste les organes dans l\'ordre.',
    tags: ['cm2', 'sciences', 'corps', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm2-com-006',
    subject: 'sciences',
    title: 'Compréhension : squelette',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Le squelette protège les organes du corps. Le crâne, par exemple, protège le cerveau. » — Que protège le crâne ?',
    options: [
      { id: 'a', text: 'Le cœur', isCorrect: false },
      { id: 'b', text: 'Le cerveau', isCorrect: true },
      { id: 'c', text: 'Les poumons', isCorrect: false },
    ],
    correctAnswer: 'Le cerveau',
    explanation: 'Le crâne est l\'os de la tête. Il protège le cerveau des chocs.',
    hint: 'Le texte le dit directement.',
    tags: ['cm2', 'sciences', 'corps', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-024',
    subject: 'sciences',
    title: 'ADN : information génétique',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'cellules',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où se trouve l\'ADN dans une cellule humaine ?',
    options: [
      { id: 'a', text: 'Dans les mitochondries uniquement', isCorrect: false },
      { id: 'b', text: 'Principalement dans le noyau de la cellule', isCorrect: true },
      { id: 'c', text: 'À la surface de la cellule', isCorrect: false },
    ],
    correctAnswer: 'Principalement dans le noyau de la cellule',
    explanation: 'L\'ADN (molécule de l\'hérédité) est principalement contenu dans le noyau de chaque cellule, enroulé en chromosomes.',
    hint: 'Le noyau est la « bibliothèque » de la cellule.',
    tags: ['cm2', 'sciences', 'corps', 'cellules', 'adn', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-025',
    subject: 'sciences',
    title: 'Système immunitaire : anticorps',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'immunite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les anticorps sont... ?',
    options: [
      { id: 'a', text: 'Des cellules musculaires spécialisées', isCorrect: false },
      { id: 'b', text: 'Des protéines produites par le système immunitaire pour neutraliser les agents pathogènes', isCorrect: true },
      { id: 'c', text: 'Des hormones régulant la croissance', isCorrect: false },
    ],
    correctAnswer: 'Des protéines produites par le système immunitaire pour neutraliser les agents pathogènes',
    explanation: 'Les anticorps reconnaissent et se fixent sur les agents pathogènes (virus, bactéries) pour les neutraliser ou les marquer pour destruction.',
    hint: 'La vaccination stimule la production d\'anticorps.',
    tags: ['cm2', 'sciences', 'corps', 'immunite', 'anticorps', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-026',
    subject: 'sciences',
    title: 'Neurones : transmission de l\'information',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'systeme-nerveux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les neurones transmettent-ils l\'information ?',
    options: [
      { id: 'a', text: 'Par circulation du sang', isCorrect: false },
      { id: 'b', text: 'Par des signaux électriques et chimiques', isCorrect: true },
      { id: 'c', text: 'Par vibrations mécaniques', isCorrect: false },
    ],
    correctAnswer: 'Par des signaux électriques et chimiques',
    explanation: 'Les neurones transmettent des influx nerveux sous forme de signaux électriques (dans le neurone) et chimiques (entre les neurones, via les synapses).',
    hint: 'C\'est comme un réseau électrique très complexe.',
    tags: ['cm2', 'sciences', 'corps', 'systeme-nerveux', 'neurones', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-027',
    subject: 'sciences',
    title: 'Hormones : insuline',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'hormones',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle de l\'insuline ?',
    options: [
      { id: 'a', text: 'Accélérer la respiration', isCorrect: false },
      { id: 'b', text: 'Réguler le taux de sucre dans le sang', isCorrect: true },
      { id: 'c', text: 'Contrôler la pression artérielle', isCorrect: false },
    ],
    correctAnswer: 'Réguler le taux de sucre dans le sang',
    explanation: 'L\'insuline est une hormone produite par le pancréas. Elle fait entrer le glucose dans les cellules pour réguler la glycémie (taux de sucre sanguin).',
    hint: 'Son absence cause le diabète de type 1.',
    tags: ['cm2', 'sciences', 'corps', 'hormones', 'insuline', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-028',
    subject: 'sciences',
    title: 'Reproduction : fécondation',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'reproduction',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La fécondation est... ?',
    options: [
      { id: 'a', text: 'La naissance d\'un bébé', isCorrect: false },
      { id: 'b', text: 'L\'union d\'un spermatozoïde et d\'un ovule', isCorrect: true },
      { id: 'c', text: 'La puberté', isCorrect: false },
    ],
    correctAnswer: 'L\'union d\'un spermatozoïde et d\'un ovule',
    explanation: 'La fécondation est la fusion du spermatozoïde (cellule reproductrice mâle) et de l\'ovule (cellule reproductrice femelle) pour former un œuf.',
    hint: 'C\'est le début d\'un nouvel être vivant.',
    tags: ['cm2', 'sciences', 'corps', 'reproduction', 'fecondation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-029',
    subject: 'sciences',
    title: 'Organes : poumon vs. cœur',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'organes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le lien entre les poumons et le cœur ?',
    options: [
      { id: 'a', text: 'Ils n\'ont aucune relation', isCorrect: false },
      { id: 'b', text: 'Le cœur envoie le sang vers les poumons pour qu\'il récupère de l\'oxygène', isCorrect: true },
      { id: 'c', text: 'Les poumons pompent le sang dans tout le corps', isCorrect: false },
    ],
    correctAnswer: 'Le cœur envoie le sang vers les poumons pour qu\'il récupère de l\'oxygène',
    explanation: 'La petite circulation : le cœur envoie le sang pauvre en O₂ vers les poumons, où il récupère l\'oxygène, puis revient au cœur pour repartir dans le corps.',
    hint: 'Le sang fait deux trajets : poumons et corps.',
    tags: ['cm2', 'sciences', 'corps', 'organes', 'coeur', 'poumons', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-030',
    subject: 'sciences',
    title: 'Addictions : tabac',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi la cigarette est-elle dangereuse pour les poumons ?',
    options: [
      { id: 'a', text: 'Elle refroidit les poumons', isCorrect: false },
      { id: 'b', text: 'Elle contient des substances toxiques qui endommagent les tissus pulmonaires', isCorrect: true },
      { id: 'c', text: 'Elle rétrécit la cage thoracique', isCorrect: false },
    ],
    correctAnswer: 'Elle contient des substances toxiques qui endommagent les tissus pulmonaires',
    explanation: 'La fumée de cigarette contient plus de 4000 substances chimiques dont le goudron et le monoxyde de carbone, qui endommagent les cils et les alvéoles pulmonaires.',
    hint: 'Les poumons d\'un fumeur noircissent avec le temps.',
    tags: ['cm2', 'sciences', 'corps', 'hygiene', 'tabac', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-031',
    subject: 'sciences',
    title: 'Nutrition : lipides',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'nutrition',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle des lipides (graisses) dans le corps ?',
    options: [
      { id: 'a', text: 'Construire les muscles uniquement', isCorrect: false },
      { id: 'b', text: 'Stocker de l\'énergie, isoler le corps et constituer les membranes cellulaires', isCorrect: true },
      { id: 'c', text: 'Transporter l\'oxygène dans le sang', isCorrect: false },
    ],
    correctAnswer: 'Stocker de l\'énergie, isoler le corps et constituer les membranes cellulaires',
    explanation: 'Les lipides ont plusieurs rôles : réserve d\'énergie (tissu adipeux), isolation thermique, et composant essentiel des membranes de toutes les cellules.',
    hint: 'La graisse protège aussi nos organes des chocs.',
    tags: ['cm2', 'sciences', 'corps', 'nutrition', 'lipides', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-032',
    subject: 'sciences',
    title: 'Maladies infectieuses : mode de transmission',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'sante',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La grippe se transmet principalement par... ?',
    options: [
      { id: 'a', text: 'L\'eau du robinet', isCorrect: false },
      { id: 'b', text: 'Les gouttelettes projetées lors de la toux et des éternuements', isCorrect: true },
      { id: 'c', text: 'Le contact avec des plantes', isCorrect: false },
    ],
    correctAnswer: 'Les gouttelettes projetées lors de la toux et des éternuements',
    explanation: 'Le virus de la grippe se transmet principalement par voie respiratoire : les gouttelettes infectieuses projetées dans l\'air lors d\'une toux ou d\'un éternuement.',
    hint: 'Se couvrir la bouche quand on tousse aide à protéger les autres.',
    tags: ['cm2', 'sciences', 'corps', 'sante', 'grippe', 'transmission', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-033',
    subject: 'sciences',
    title: 'Cerveau : mémoire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'systeme-nerveux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la mémoire à long terme ?',
    options: [
      { id: 'a', text: 'Une mémoire qui dure seulement quelques secondes', isCorrect: false },
      { id: 'b', text: 'La capacité à stocker et récupérer des informations sur une longue période', isCorrect: true },
      { id: 'c', text: 'La mémoire musculaire uniquement', isCorrect: false },
    ],
    correctAnswer: 'La capacité à stocker et récupérer des informations sur une longue période',
    explanation: 'La mémoire à long terme stocke des informations de manière durable (jours, années, toute une vie). Le sommeil joue un rôle crucial dans la consolidation de la mémoire.',
    hint: 'Tu te souviens de ta première journée d\'école grâce à ta mémoire à long terme.',
    tags: ['cm2', 'sciences', 'corps', 'cerveau', 'memoire', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-068',
    subject: 'sciences',
    title: 'Épigénétique : gènes et environnement',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'genetique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'épigénétique montre que l\'environnement peut influencer l\'expression des gènes sans changer l\'ADN. Quel exemple illustre ce phénomène ?',
    options: [
      { id: 'a', text: 'Les vrais jumeaux ont exactement les mêmes gènes et sont identiques en tout point toute leur vie', isCorrect: false },
      { id: 'b', text: 'Les vrais jumeaux ont le même ADN mais peuvent développer des maladies différentes selon leur mode de vie', isCorrect: true },
      { id: 'c', text: 'L\'alimentation modifie directement la séquence ADN des individus', isCorrect: false },
    ],
    correctAnswer: 'Les vrais jumeaux ont le même ADN mais peuvent développer des maladies différentes selon leur mode de vie',
    explanation: 'Les jumeaux ont un ADN identique mais l\'épigénétique (méthylation de l\'ADN…) diffère selon leur mode de vie, alimentation, stress. C\'est la nature + la culture en interaction.',
    hint: 'L\'épigénétique = "au-dessus des gènes".',
    tags: ['cm2', 'sciences', 'corps', 'genetique', 'epigenetique', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-069',
    subject: 'sciences',
    title: 'Cerveau : plasticité cérébrale',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'cerveau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la plasticité cérébrale ?',
    options: [
      { id: 'a', text: 'La capacité du cerveau à se déformer physiquement sous pression', isCorrect: false },
      { id: 'b', text: 'La capacité du cerveau à se réorganiser en formant de nouvelles connexions neuronales', isCorrect: true },
      { id: 'c', text: 'La résistance du crâne aux chocs', isCorrect: false },
    ],
    correctAnswer: 'La capacité du cerveau à se réorganiser en formant de nouvelles connexions neuronales',
    explanation: 'Le cerveau peut créer et renforcer des connexions neuronales en réponse aux apprentissages et aux expériences. Cette plasticité est maximale dans l\'enfance mais persiste toute la vie.',
    hint: 'Apprendre une nouvelle compétence crée de nouvelles connexions neuronales.',
    tags: ['cm2', 'sciences', 'corps', 'cerveau', 'plasticite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-070',
    subject: 'sciences',
    title: 'Corps : maladies auto-immunes',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'immunite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans une maladie auto-immune (comme le diabète de type 1), que se passe-t-il ?',
    options: [
      { id: 'a', text: 'Le système immunitaire est trop faible et ne combat pas les microbes', isCorrect: false },
      { id: 'b', text: 'Le système immunitaire attaque par erreur les cellules saines du propre corps', isCorrect: true },
      { id: 'c', text: 'Un virus bloque totalement le système immunitaire', isCorrect: false },
    ],
    correctAnswer: 'Le système immunitaire attaque par erreur les cellules saines du propre corps',
    explanation: 'Dans le diabète de type 1, le système immunitaire détruit les cellules bêta du pancréas qui produisent l\'insuline. Il confond ses propres cellules avec des envahisseurs.',
    hint: 'Auto = soi-même. Le corps se combat lui-même.',
    tags: ['cm2', 'sciences', 'corps', 'immunite', 'maladies-auto-immunes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-071',
    subject: 'sciences',
    title: 'Nutrition : micronutriments',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'nutrition',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la différence entre un macronutriment et un micronutriment ?',
    options: [
      { id: 'a', text: 'Les macronutriments sont dans les grandes portions, les micronutriments dans les petites', isCorrect: false },
      { id: 'b', text: 'Les macronutriments fournissent de l\'énergie ; les micronutriments (vitamines, minéraux) assurent le bon fonctionnement de l\'organisme', isCorrect: true },
      { id: 'c', text: 'Ce sont exactement la même chose', isCorrect: false },
    ],
    correctAnswer: 'Les macronutriments fournissent de l\'énergie ; les micronutriments (vitamines, minéraux) assurent le bon fonctionnement de l\'organisme',
    explanation: 'Macronutriments : glucides, lipides, protéines → énergie (calories). Micronutriments : vitamines, minéraux (fer, calcium…) → régulation des fonctions vitales sans fournir d\'énergie directe.',
    hint: 'Macro = grand (fournit l\'énergie). Micro = petit (régule).',
    tags: ['cm2', 'sciences', 'corps', 'nutrition', 'micronutriments', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-072',
    subject: 'sciences',
    title: 'Corps : reins et filtration',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'organes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle quantité de sang les reins filtrent-ils approximativement chaque jour ?',
    options: [
      { id: 'a', text: '1 litre par jour', isCorrect: false },
      { id: 'b', text: '180 litres par jour', isCorrect: true },
      { id: 'c', text: '5 litres par jour (le volume total du sang)', isCorrect: false },
    ],
    correctAnswer: '180 litres par jour',
    explanation: 'Les reins filtrent environ 180 L de sang par jour. Ils retiennent ce qui est utile (eau, glucose, minéraux) et éliminent les déchets dans ~1,5 L d\'urine par jour.',
    hint: 'L\'urine finale ne représente qu\'1 % du filtrat initial !',
    tags: ['cm2', 'sciences', 'corps', 'reins', 'filtration', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-073',
    subject: 'sciences',
    title: 'Corps : stress oxydatif',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'biochimie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les antioxydants (présents dans les fruits et légumes) sont-ils bénéfiques pour la santé ?',
    options: [
      { id: 'a', text: 'Ils empêchent les cellules de respirer trop vite', isCorrect: false },
      { id: 'b', text: 'Ils neutralisent les radicaux libres qui endommagent les cellules', isCorrect: true },
      { id: 'c', text: 'Ils augmentent directement la production d\'énergie cellulaire', isCorrect: false },
    ],
    correctAnswer: 'Ils neutralisent les radicaux libres qui endommagent les cellules',
    explanation: 'Les radicaux libres (produits par le métabolisme et le stress) endommagent l\'ADN et les cellules (stress oxydatif). Les antioxydants (vitamines C, E, polyphénols) les neutralisent.',
    hint: 'Les fruits et légumes colorés sont souvent riches en antioxydants.',
    tags: ['cm2', 'sciences', 'corps', 'biochimie', 'antioxydants', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-074',
    subject: 'sciences',
    title: 'Corps : thermorégulation en altitude',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'regulation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les alpinistes en haute altitude ont-ils plus de globules rouges que les personnes vivant en plaine ?',
    options: [
      { id: 'a', text: 'Parce qu\'ils mangent davantage de viande rouge', isCorrect: false },
      { id: 'b', text: 'Le manque d\'O₂ stimule la production de globules rouges pour compenser', isCorrect: true },
      { id: 'c', text: 'Le froid en altitude détruit les globules blancs', isCorrect: false },
    ],
    correctAnswer: 'Le manque d\'O₂ stimule la production de globules rouges pour compenser',
    explanation: 'En altitude, la pression en O₂ diminue. L\'organisme réagit en produisant plus de globules rouges (polyglobulie) pour transporter davantage d\'O₂ avec le sang disponible.',
    hint: 'C\'est pour ça que certains sportifs s\'entraînent en altitude.',
    tags: ['cm2', 'sciences', 'corps', 'regulation', 'altitude', 'globules-rouges', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-075',
    subject: 'sciences',
    title: 'Corps : système lymphatique',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'immunite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle du système lymphatique ?',
    options: [
      { id: 'a', text: 'Transporter le sang dans tout le corps', isCorrect: false },
      { id: 'b', text: 'Drainer les liquides des tissus, transporter les graisses intestinales et jouer un rôle immunitaire', isCorrect: true },
      { id: 'c', text: 'Produire les hormones de croissance', isCorrect: false },
    ],
    correctAnswer: 'Drainer les liquides des tissus, transporter les graisses intestinales et jouer un rôle immunitaire',
    explanation: 'Le système lymphatique circule en parallèle du sang. Il collecte les liquides des tissus (lymphe), transporte les graisses de l\'intestin et abrite les lymphocytes (cellules immunitaires).',
    hint: 'Les ganglions lymphatiques (ganglions enflés quand on est malade) font partie de ce système.',
    tags: ['cm2', 'sciences', 'corps', 'immunite', 'lymphatique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-076',
    subject: 'sciences',
    title: 'Corps : neurones et synapse',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'systeme-nerveux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment l\'information se transmet-elle d\'un neurone à l\'autre au niveau d\'une synapse ?',
    options: [
      { id: 'a', text: 'Par contact direct : les neurones se touchent et l\'électricité passe', isCorrect: false },
      { id: 'b', text: 'Par des molécules chimiques (neurotransmetteurs) libérées dans l\'espace synaptique', isCorrect: true },
      { id: 'c', text: 'Par des ondes sonores produites par la cellule', isCorrect: false },
    ],
    correctAnswer: 'Par des molécules chimiques (neurotransmetteurs) libérées dans l\'espace synaptique',
    explanation: 'À la synapse, les neurones ne se touchent pas. L\'un libère des neurotransmetteurs (ex : dopamine, sérotonine) dans un espace (fente synaptique). Le neurone suivant les capte et transmet le signal.',
    hint: 'La dopamine est un neurotransmetteur impliqué dans le plaisir et la motivation.',
    tags: ['cm2', 'sciences', 'corps', 'systeme-nerveux', 'synapse', 'neurotransmetteurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-077',
    subject: 'sciences',
    title: 'Corps : cycles circadiens',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'regulation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le rythme circadien ?',
    options: [
      { id: 'a', text: 'Le rythme du cœur en battements par minute', isCorrect: false },
      { id: 'b', text: 'L\'horloge biologique interne de ~24h qui régule veille/sommeil, température, hormones…', isCorrect: true },
      { id: 'c', text: 'La cadence des repas recommandée par les médecins', isCorrect: false },
    ],
    correctAnswer: 'L\'horloge biologique interne de ~24h qui régule veille/sommeil, température, température, hormones…',
    explanation: 'Le rythme circadien (circa = environ, dies = jour) est une horloge interne de 24h. Il régule l\'éveil, le sommeil, la température corporelle, les hormones. La lumière bleue des écrans le perturbe.',
    hint: 'Circadien : circo = autour, dies = jour. Environ 24 heures.',
    tags: ['cm2', 'sciences', 'corps', 'regulation', 'rythme-circadien', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
