import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCm2VivantExercises: ScienceExercise[] = [
  {
    id: 'sc-cm2-com-001',
    subject: 'sciences',
    title: 'Compréhension : métamorphose',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« La chenille se transforme en papillon. Ce processus s\'appelle une métamorphose. » — Que devient une chenille ?',
    options: [
      { id: 'a', text: 'Un ver', isCorrect: false },
      { id: 'b', text: 'Un papillon', isCorrect: true },
      { id: 'c', text: 'Une abeille', isCorrect: false },
    ],
    correctAnswer: 'Un papillon',
    explanation: 'La chenille se transforme en papillon : c\'est ce qu\'on appelle une métamorphose.',
    hint: '« Métamorphose » veut dire transformation.',
    tags: ['cm2', 'sciences', 'animaux', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Lis la 1ʳᵉ phrase.', extraHint: 'La chenille devient un papillon.' },
    }),
  },

    {
    id: 'sc-cm2-com-002',
    subject: 'sciences',
    title: 'Compréhension : abeilles pollinisatrices',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Les abeilles récoltent le nectar des fleurs. En volant de fleur en fleur, elles transportent du pollen, ce qui aide les plantes à se reproduire. » — Quel service les abeilles rendent-elles aux plantes ?',
    options: [
      { id: 'a', text: 'Elles arrosent les plantes', isCorrect: false },
      { id: 'b', text: 'Elles aident les plantes à se reproduire', isCorrect: true },
      { id: 'c', text: 'Elles protègent les plantes des insectes', isCorrect: false },
    ],
    correctAnswer: 'Elles aident les plantes à se reproduire',
    explanation: 'En transportant le pollen, les abeilles permettent aux fleurs d\'être fécondées et de donner des fruits.',
    hint: 'Elles transportent du pollen d\'une fleur à l\'autre.',
    tags: ['cm2', 'sciences', 'animaux', 'plantes', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis la 2ᵉ phrase.', 'Que transportent les abeilles ?', 'À quoi cela sert-il ?'] },
    }),
  },

    {
    id: 'sc-cm2-com-003',
    subject: 'sciences',
    title: 'Compréhension : insectivore',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Un animal insectivore se nourrit d\'insectes. La hirondelle, par exemple, attrape des insectes en vol. » — Comment appelle-t-on un animal qui mange des insectes ?',
    options: [
      { id: 'a', text: 'Un herbivore', isCorrect: false },
      { id: 'b', text: 'Un carnivore', isCorrect: false },
      { id: 'c', text: 'Un insectivore', isCorrect: true },
    ],
    correctAnswer: 'Un insectivore',
    explanation: 'Le mot « insectivore » désigne un animal qui se nourrit d\'insectes.',
    hint: 'Le mot est directement dans le texte.',
    tags: ['cm2', 'sciences', 'besoins', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm2-com-012',
    subject: 'sciences',
    title: 'Compréhension : animal omnivore',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« La mouette mange des poissons. Le lapin mange de l\'herbe. Le renard mange à la fois des lapins, des fruits et des baies. » — Quel animal est omnivore ?',
    options: [
      { id: 'a', text: 'La mouette', isCorrect: false },
      { id: 'b', text: 'Le lapin', isCorrect: false },
      { id: 'c', text: 'Le renard', isCorrect: true },
    ],
    correctAnswer: 'Le renard',
    explanation: 'Le renard est omnivore car il mange à la fois des animaux (lapins) et des végétaux (fruits, baies).',
    hint: 'L\'omnivore mange des animaux ET des plantes.',
    tags: ['cm2', 'sciences', 'animaux', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Lis la dernière phrase.', extraHint: 'Le renard mange des lapins ET des fruits.' },
    }),
  },

    {
    id: 'sc-cm2-com-013',
    subject: 'sciences',
    title: 'Compréhension : cactus et désert',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Les cactus vivent dans le désert. Leurs tiges épaisses stockent de l\'eau. Ils ont peu de feuilles pour limiter l\'évaporation. » — Pourquoi les cactus ont-ils peu de feuilles ?',
    options: [
      { id: 'a', text: 'Pour être plus beaux', isCorrect: false },
      { id: 'b', text: 'Pour grandir plus vite', isCorrect: false },
      { id: 'c', text: 'Pour limiter l\'évaporation de l\'eau', isCorrect: true },
    ],
    correctAnswer: 'Pour limiter l\'évaporation de l\'eau',
    explanation: 'Dans le désert, l\'eau est rare. Le cactus limite ses feuilles pour perdre le moins d\'eau possible.',
    hint: 'La réponse est dans la dernière phrase du texte.',
    tags: ['cm2', 'sciences', 'plantes', 'habitats', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-014',
    subject: 'sciences',
    title: 'Biodiversité : définition scientifique',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La biodiversité comprend... ?',
    options: [
      { id: 'a', text: 'Uniquement les animaux sauvages', isCorrect: false },
      { id: 'b', text: 'La diversité des espèces, des gènes et des écosystèmes', isCorrect: true },
      { id: 'c', text: 'Uniquement les espèces marines', isCorrect: false },
    ],
    correctAnswer: 'La diversité des espèces, des gènes et des écosystèmes',
    explanation: 'La biodiversité englobe trois niveaux : diversité des espèces (animaux, plantes…), diversité génétique, et diversité des écosystèmes.',
    hint: 'C\'est beaucoup plus large que juste les animaux.',
    tags: ['cm2', 'sciences', 'ecosysteme', 'biodiversite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-015',
    subject: 'sciences',
    title: 'Évolution : sélection naturelle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'evolution',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que signifie la « sélection naturelle » selon Darwin ?',
    options: [
      { id: 'a', text: 'Les hommes choisissent les animaux les plus forts', isCorrect: false },
      { id: 'b', text: 'Les individus les mieux adaptés à leur environnement survivent et se reproduisent davantage', isCorrect: true },
      { id: 'c', text: 'La nature élimine aléatoirement des animaux', isCorrect: false },
    ],
    correctAnswer: 'Les individus les mieux adaptés à leur environnement survivent et se reproduisent davantage',
    explanation: 'Darwin a montré que les individus les mieux adaptés ont plus de chances de survivre et de transmettre leurs caractères à leurs descendants.',
    hint: 'Les girafes à long cou atteignent les feuilles hautes et survivent mieux.',
    tags: ['cm2', 'sciences', 'vivant', 'evolution', 'darwin', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-016',
    subject: 'sciences',
    title: 'Génétique : hérédité',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'reproduction',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que l\'hérédité ?',
    options: [
      { id: 'a', text: 'Le fait de recevoir de l\'argent de ses parents', isCorrect: false },
      { id: 'b', text: 'La transmission de caractères des parents aux enfants via les gènes', isCorrect: true },
      { id: 'c', text: 'L\'apprentissage par imitation des parents', isCorrect: false },
    ],
    correctAnswer: 'La transmission de caractères des parents aux enfants via les gènes',
    explanation: 'L\'hérédité, c\'est la transmission de caractères (couleur des yeux, groupe sanguin…) des parents à leurs enfants par les gènes.',
    hint: 'Les enfants ressemblent à leurs parents grâce à l\'hérédité.',
    tags: ['cm2', 'sciences', 'vivant', 'heredite', 'genes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-017',
    subject: 'sciences',
    title: 'Écosystème : équilibre',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans une forêt, des loups sont réintroduits et mangent des cerfs. Que se passe-t-il pour la végétation ?',
    options: [
      { id: 'a', text: 'Elle diminue car les loups mangent les arbres', isCorrect: false },
      { id: 'b', text: 'Elle se régénère car les cerfs, moins nombreux, la broutent moins', isCorrect: true },
      { id: 'c', text: 'Elle ne change pas', isCorrect: false },
    ],
    correctAnswer: 'Elle se régénère car les cerfs, moins nombreux, la broutent moins',
    explanation: 'Le retour des loups régule la population de cerfs, ce qui laisse la végétation se régénérer. C\'est un effet en cascade dans l\'écosystème.',
    hint: 'Moins de cerfs = moins de broutage des plantes.',
    tags: ['cm2', 'sciences', 'ecosysteme', 'equilibre', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-018',
    subject: 'sciences',
    title: 'Classification : domaines du vivant',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Parmi les grands groupes du vivant, lequel correspond aux êtres vivants unicellulaires sans noyau ?',
    options: [
      { id: 'a', text: 'Les animaux', isCorrect: false },
      { id: 'b', text: 'Les bactéries (procaryotes)', isCorrect: true },
      { id: 'c', text: 'Les champignons', isCorrect: false },
    ],
    correctAnswer: 'Les bactéries (procaryotes)',
    explanation: 'Les bactéries sont des procaryotes : des cellules sans noyau véritable. Les animaux, plantes et champignons ont des cellules avec noyau (eucaryotes).',
    hint: 'Pro-caryote = avant le noyau (sans noyau).',
    tags: ['cm2', 'sciences', 'vivant', 'classification', 'bacteries', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-019',
    subject: 'sciences',
    title: 'Comportement animal : communication',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les abeilles informent-elles leurs congénères sur la direction d\'une source de nectar ?',
    options: [
      { id: 'a', text: 'Par des sons ultrasoniques', isCorrect: false },
      { id: 'b', text: 'Par une danse (danse des abeilles)', isCorrect: true },
      { id: 'c', text: 'Par des phéromones uniquement', isCorrect: false },
    ],
    correctAnswer: 'Par une danse (danse des abeilles)',
    explanation: 'Karl von Frisch a découvert que les abeilles effectuent une danse en 8 pour indiquer la direction et la distance des fleurs.',
    hint: 'Cette découverte a valu le prix Nobel à son auteur.',
    tags: ['cm2', 'sciences', 'vivant', 'animaux', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-020',
    subject: 'sciences',
    title: 'Photosynthèse : bilan',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le produit rejeté par les plantes lors de la photosynthèse ?',
    options: [
      { id: 'a', text: 'Du CO₂', isCorrect: false },
      { id: 'b', text: 'De l\'oxygène (O₂)', isCorrect: true },
      { id: 'c', text: 'De la vapeur d\'eau uniquement', isCorrect: false },
    ],
    correctAnswer: 'De l\'oxygène (O₂)',
    explanation: 'La photosynthèse : CO₂ + H₂O + lumière → glucose + O₂. Les plantes absorbent du CO₂ et rejettent de l\'O₂ que nous respirons.',
    hint: 'C\'est ce que nous respirons.',
    tags: ['cm2', 'sciences', 'vivant', 'plantes', 'photosynthese', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-021',
    subject: 'sciences',
    title: 'Symbiose : exemple lichen',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La symbiose est une relation où... ?',
    options: [
      { id: 'a', text: 'Un être vivant profite d\'un autre sans lui nuire', isCorrect: false },
      { id: 'b', text: 'Deux êtres vivants profitent mutuellement l\'un de l\'autre', isCorrect: true },
      { id: 'c', text: 'Un être vivant nuit à un autre', isCorrect: false },
    ],
    correctAnswer: 'Deux êtres vivants profitent mutuellement l\'un de l\'autre',
    explanation: 'La symbiose est une relation mutuellement bénéfique. Les lichens associent un champignon et une algue : l\'algue fait la photosynthèse, le champignon fournit l\'eau.',
    hint: 'Les deux partenaires gagnent quelque chose.',
    tags: ['cm2', 'sciences', 'vivant', 'ecosysteme', 'symbiose', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-022',
    subject: 'sciences',
    title: 'Extinction de masse : dinosaures',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'evolution',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la cause principale de l\'extinction des dinosaures il y a 66 millions d\'années ?',
    options: [
      { id: 'a', text: 'Une épidémie mondiale', isCorrect: false },
      { id: 'b', text: 'L\'impact d\'une météorite et ses conséquences climatiques', isCorrect: true },
      { id: 'c', text: 'La chasse des premiers humains', isCorrect: false },
    ],
    correctAnswer: 'L\'impact d\'une météorite et ses conséquences climatiques',
    explanation: 'Une météorite géante a percuté la Terre, provoquant incendies, un nuage de poussière bloquant le soleil et un refroidissement climatique massif.',
    hint: 'Les humains sont apparus bien après les dinosaures.',
    tags: ['cm2', 'sciences', 'vivant', 'evolution', 'extinction', 'dinosaures', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-023',
    subject: 'sciences',
    title: 'Clonage : définition',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'reproduction',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le clonage produit... ?',
    options: [
      { id: 'a', text: 'Un individu différent de l\'original', isCorrect: false },
      { id: 'b', text: 'Un individu génétiquement identique à l\'original', isCorrect: true },
      { id: 'c', text: 'Un hybride entre deux espèces', isCorrect: false },
    ],
    correctAnswer: 'Un individu génétiquement identique à l\'original',
    explanation: 'Le clonage crée une copie génétiquement identique d\'un organisme. Les vrais jumeaux sont des clones naturels.',
    hint: 'Les vrais jumeaux sont un exemple naturel.',
    tags: ['cm2', 'sciences', 'vivant', 'reproduction', 'clonage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-058',
    subject: 'sciences',
    title: 'Évolution convergente',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'evolution',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le dauphin (mammifère) et le requin (poisson) ont une forme corporelle similaire. Comment appelle-t-on ce phénomène ?',
    options: [
      { id: 'a', text: 'L\'homologie', isCorrect: false },
      { id: 'b', text: 'L\'évolution convergente', isCorrect: true },
      { id: 'c', text: 'Le mimétisme', isCorrect: false },
    ],
    correctAnswer: 'L\'évolution convergente',
    explanation: 'L\'évolution convergente : des espèces non apparentées développent des formes similaires car elles s\'adaptent aux mêmes contraintes environnementales (ici, nager vite dans l\'eau).',
    hint: 'Même environnement → mêmes solutions, indépendamment de l\'ancêtre.',
    tags: ['cm2', 'sciences', 'vivant', 'evolution', 'convergence', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-059',
    subject: 'sciences',
    title: 'Microbiome intestinal',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'microorganismes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le microbiome intestinal humain contient des milliards de bactéries. Quel est leur rôle principal ?',
    options: [
      { id: 'a', text: 'Elles envahissent l\'intestin et causent des maladies', isCorrect: false },
      { id: 'b', text: 'Elles aident à la digestion, renforcent l\'immunité et produisent des vitamines', isCorrect: true },
      { id: 'c', text: 'Elles ne jouent aucun rôle, leur présence est accidentelle', isCorrect: false },
    ],
    correctAnswer: 'Elles aident à la digestion, renforcent l\'immunité et produisent des vitamines',
    explanation: 'Le microbiome est un écosystème de bactéries symbiotiques vivant dans l\'intestin. Elles digèrent des fibres, produisent des vitamines (B12, K) et entraînent le système immunitaire.',
    hint: 'Les probiotiques (yaourts) apportent de "bonnes" bactéries au microbiome.',
    tags: ['cm2', 'sciences', 'vivant', 'microorganismes', 'microbiome', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-060',
    subject: 'sciences',
    title: 'Espèces invasives : impact',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La perche du Nil, introduite dans le lac Victoria en Afrique, a provoqué l\'extinction de centaines d\'espèces de poissons. Pourquoi les espèces invasives sont-elles si destructrices ?',
    options: [
      { id: 'a', text: 'Elles apportent des maladies inconnues dans les écosystèmes', isCorrect: false },
      { id: 'b', text: 'Elles n\'ont pas de prédateurs naturels dans leur nouvel environnement et perturbent l\'équilibre existant', isCorrect: true },
      { id: 'c', text: 'Elles mangent uniquement les plantes, privant les animaux herbivores', isCorrect: false },
    ],
    correctAnswer: 'Elles n\'ont pas de prédateurs naturels dans leur nouvel environnement et perturbent l\'équilibre existant',
    explanation: 'Introduites hors de leur milieu d\'origine, les espèces invasives prolifèrent sans contrôle (pas de prédateurs), mangent les espèces locales et modifient tout l\'écosystème.',
    hint: 'Le frelon asiatique en France est un autre exemple d\'espèce invasive.',
    tags: ['cm2', 'sciences', 'vivant', 'ecosysteme', 'especes-invasives', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-061',
    subject: 'sciences',
    title: 'ADN : information génétique',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'genetique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où se trouve l\'ADN dans une cellule humaine ?',
    options: [
      { id: 'a', text: 'Dans la membrane cellulaire', isCorrect: false },
      { id: 'b', text: 'Principalement dans le noyau de la cellule', isCorrect: true },
      { id: 'c', text: 'Dans le liquide cytoplasmatique entourant le noyau', isCorrect: false },
    ],
    correctAnswer: 'Principalement dans le noyau de la cellule',
    explanation: 'L\'ADN est contenu dans le noyau sous forme de chromosomes. Chaque cellule humaine (sauf les globules rouges) contient 46 chromosomes avec l\'ensemble du génome humain.',
    hint: '46 chromosomes = 23 paires héritées de chaque parent.',
    tags: ['cm2', 'sciences', 'vivant', 'genetique', 'adn', 'noyau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-062',
    subject: 'sciences',
    title: 'Photosynthèse : équation bilan',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lors de la photosynthèse, les plantes absorbent du CO₂ et de l\'H₂O et libèrent... ?',
    options: [
      { id: 'a', text: 'Du CO₂ et de l\'azote', isCorrect: false },
      { id: 'b', text: 'Du glucose (sucre) et de l\'O₂ (oxygène)', isCorrect: true },
      { id: 'c', text: 'De la vapeur d\'eau et du méthane', isCorrect: false },
    ],
    correctAnswer: 'Du glucose (sucre) et de l\'O₂ (oxygène)',
    explanation: 'Équation simplifiée : 6 CO₂ + 6 H₂O + lumière → C₆H₁₂O₆ (glucose) + 6 O₂. Les plantes fabriquent leur nourriture et libèrent l\'oxygène que nous respirons.',
    hint: 'La photosynthèse produit le glucose qui nourrit la plante ET l\'O₂ qui nous permet de respirer.',
    tags: ['cm2', 'sciences', 'vivant', 'plantes', 'photosynthese', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-063',
    subject: 'sciences',
    title: 'Sixième extinction de masse',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'biodiversite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les scientifiques parlent d\'une "sixième extinction de masse" en cours. Quelle en est la principale cause ?',
    options: [
      { id: 'a', text: 'Les éruptions volcaniques répétées', isCorrect: false },
      { id: 'b', text: 'Les activités humaines : destruction des habitats, pollution, changement climatique', isCorrect: true },
      { id: 'c', text: 'Un astéroïde qui approche de la Terre', isCorrect: false },
    ],
    correctAnswer: 'Les activités humaines : destruction des habitats, pollution, changement climatique',
    explanation: 'Les 5 extinctions de masse précédentes avaient des causes naturelles. La 6ème, en cours, est due à l\'humanité : déforestation, agriculture intensive, pollution et réchauffement climatique.',
    hint: 'La 5ème extinction a tué les dinosaures (météorite, -66 Ma).',
    tags: ['cm2', 'sciences', 'vivant', 'biodiversite', 'extinction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-064',
    subject: 'sciences',
    title: 'Cellules souches',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'cellule',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui rend les cellules souches particulières par rapport aux autres cellules ?',
    options: [
      { id: 'a', text: 'Elles sont plus grosses que les autres cellules', isCorrect: false },
      { id: 'b', text: 'Elles peuvent se différencier en différents types de cellules spécialisées', isCorrect: true },
      { id: 'c', text: 'Elles ne contiennent pas d\'ADN', isCorrect: false },
    ],
    correctAnswer: 'Elles peuvent se différencier en différents types de cellules spécialisées',
    explanation: 'Les cellules souches sont non spécialisées. Elles peuvent se transformer en cellules musculaires, neurones, cellules sanguines… C\'est leur plasticité qui intéresse la médecine régénérative.',
    hint: 'Elles sont comme des cellules "vierges" qui peuvent devenir n\'importe quel type.',
    tags: ['cm2', 'sciences', 'vivant', 'cellule', 'cellules-souches', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-065',
    subject: 'sciences',
    title: 'Symbiose : coraux et zooxanthelles',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les coraux hébergent des algues microscopiques (zooxanthelles) qui leur fournissent 90 % de leur nourriture par photosynthèse. Que peut-il se passer quand la mer se réchauffe ?',
    options: [
      { id: 'a', text: 'Les coraux grandissent plus vite grâce à la chaleur', isCorrect: false },
      { id: 'b', text: 'Le stress thermique expulse les algues, le corail blanchit et peut mourir', isCorrect: true },
      { id: 'c', text: 'Les algues se reproduisent davantage et envahissent le récif', isCorrect: false },
    ],
    correctAnswer: 'Le stress thermique expulse les algues, le corail blanchit et peut mourir',
    explanation: 'Le blanchissement des coraux : sous l\'effet du réchauffement, les coraux expulsent leurs algues symbiotiques. Sans elles, ils perdent leur couleur et leur source de nourriture. Ils meurent si le stress dure.',
    hint: 'La Grande Barrière de Corail a subi des épisodes massifs de blanchissement.',
    tags: ['cm2', 'sciences', 'vivant', 'ecosysteme', 'coraux', 'symbiose', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-066',
    subject: 'sciences',
    title: 'Organisme : respiration cellulaire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'cellule',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La respiration cellulaire est différente de la respiration pulmonaire. Qu\'est-ce que c\'est ?',
    options: [
      { id: 'a', text: 'La façon dont les cellules expirent le CO₂ dans les poumons', isCorrect: false },
      { id: 'b', text: 'La réaction chimique par laquelle les cellules brûlent le glucose avec O₂ pour produire de l\'énergie', isCorrect: true },
      { id: 'c', text: 'Le mouvement de l\'air dans les bronches', isCorrect: false },
    ],
    correctAnswer: 'La réaction chimique par laquelle les cellules brûlent le glucose avec O₂ pour produire de l\'énergie',
    explanation: 'Équation : C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O + énergie (ATP). C\'est l\'inverse de la photosynthèse. Toutes les cellules vivantes font cette respiration 24h/24.',
    hint: 'La respiration cellulaire se passe dans les mitochondries.',
    tags: ['cm2', 'sciences', 'vivant', 'cellule', 'respiration-cellulaire', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-067',
    subject: 'sciences',
    title: 'Écologie : empreinte écologique',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'ecologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'empreinte écologique d\'un pays mesure... ?',
    options: [
      { id: 'a', text: 'La surface de forêt restante dans ce pays', isCorrect: false },
      { id: 'b', text: 'La surface de biosphère nécessaire pour produire les ressources consommées et absorber les déchets générés', isCorrect: true },
      { id: 'c', text: 'La quantité de CO₂ émise par l\'industrie uniquement', isCorrect: false },
    ],
    correctAnswer: 'La surface de biosphère nécessaire pour produire les ressources consommées et absorber les déchets générés',
    explanation: 'L\'empreinte écologique convertit toute consommation humaine en surface de Terre nécessaire. Si tout le monde vivait comme un Français moyen, il faudrait 2,9 planètes.',
    hint: 'Le "Jour du dépassement" est la date où l\'humanité a consommé ce que la Terre peut régénérer en un an.',
    tags: ['cm2', 'sciences', 'vivant', 'ecologie', 'empreinte-ecologique', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
];
