import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCm2MatiereExercises: ScienceExercise[] = [
  {
    id: 'sc-cm2-com-044',
    subject: 'sciences',
    title: 'Atome : structure',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'structure',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la structure simplifiée d\'un atome ?',
    options: [
      { id: 'a', text: 'Un noyau d\'électrons entouré de protons', isCorrect: false },
      { id: 'b', text: 'Un noyau (protons + neutrons) entouré d\'électrons', isCorrect: true },
      { id: 'c', text: 'Un nuage de protons sans noyau', isCorrect: false },
    ],
    correctAnswer: 'Un noyau (protons + neutrons) entouré d\'électrons',
    explanation: 'Un atome est composé d\'un noyau central (protons chargés + et neutrons neutres) autour duquel gravitent des électrons chargés -.',
    hint: 'Le noyau est au centre, les électrons tournent autour.',
    tags: ['cm2', 'sciences', 'matiere', 'atome', 'structure', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-045',
    subject: 'sciences',
    title: 'Réaction chimique : combustion',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'reactions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La combustion du bois produit... ?',
    options: [
      { id: 'a', text: 'De l\'eau pure uniquement', isCorrect: false },
      { id: 'b', text: 'De la chaleur, de la lumière, du CO₂ et de la vapeur d\'eau', isCorrect: true },
      { id: 'c', text: 'De l\'oxygène pur', isCorrect: false },
    ],
    correctAnswer: 'De la chaleur, de la lumière, du CO₂ et de la vapeur d\'eau',
    explanation: 'La combustion est une réaction chimique entre un combustible (bois) et l\'oxygène. Elle produit de l\'énergie (chaleur + lumière), du CO₂ et H₂O.',
    hint: 'Un feu de bois éclaire et réchauffe : c\'est l\'énergie libérée.',
    tags: ['cm2', 'sciences', 'matiere', 'combustion', 'reaction', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-046',
    subject: 'sciences',
    title: 'Lumière : spectre visible',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'lumiere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'obtient-on quand on décompose la lumière blanche avec un prisme ?',
    options: [
      { id: 'a', text: 'Une lumière noire', isCorrect: false },
      { id: 'b', text: 'Toutes les couleurs de l\'arc-en-ciel (spectre visible)', isCorrect: true },
      { id: 'c', text: 'Des rayons infrarouges uniquement', isCorrect: false },
    ],
    correctAnswer: 'Toutes les couleurs de l\'arc-en-ciel (spectre visible)',
    explanation: 'La lumière blanche est un mélange de toutes les couleurs. Un prisme les sépare par réfraction, révélant le spectre : rouge, orange, jaune, vert, bleu, indigo, violet.',
    hint: 'L\'arc-en-ciel est un prisme naturel formé par les gouttes de pluie.',
    tags: ['cm2', 'sciences', 'matiere', 'lumiere', 'spectre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-047',
    subject: 'sciences',
    title: 'Électricité : tension et intensité',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'electricite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quoi la tension électrique (en volts) est-elle différente de l\'intensité (en ampères) ?',
    options: [
      { id: 'a', text: 'Ce sont deux noms pour la même chose', isCorrect: false },
      { id: 'b', text: 'La tension est la « pression » qui pousse le courant ; l\'intensité est la quantité de courant qui circule', isCorrect: true },
      { id: 'c', text: 'L\'intensité mesure la chaleur, la tension la vitesse', isCorrect: false },
    ],
    correctAnswer: 'La tension est la « pression » qui pousse le courant ; l\'intensité est la quantité de courant qui circule',
    explanation: 'La tension (V) est comme la pression d\'eau dans un tuyau. L\'intensité (A) est comme le débit d\'eau qui coule. Les deux caractérisent le courant.',
    hint: 'Le réseau domestique est à 230 V ; une pile AA est à 1,5 V.',
    tags: ['cm2', 'sciences', 'matiere', 'electricite', 'tension', 'intensite', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-048',
    subject: 'sciences',
    title: 'Chaleur : rayonnement',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'thermique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment la chaleur du soleil nous parvient-elle à travers le vide de l\'espace ?',
    options: [
      { id: 'a', text: 'Par conduction à travers l\'espace', isCorrect: false },
      { id: 'b', text: 'Par rayonnement électromagnétique (infrarouge)', isCorrect: true },
      { id: 'c', text: 'Par convection de l\'air de l\'espace', isCorrect: false },
    ],
    correctAnswer: 'Par rayonnement électromagnétique (infrarouge)',
    explanation: 'La chaleur du Soleil se propage par rayonnement électromagnétique, notamment les infrarouges. Ce mode ne nécessite aucun milieu matériel (d\'où le vide de l\'espace).',
    hint: 'On se réchauffe au soleil même en altitude où l\'air est froid.',
    tags: ['cm2', 'sciences', 'matiere', 'thermique', 'rayonnement', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-049',
    subject: 'sciences',
    title: 'Matériaux : polymères',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le plastique est un polymère. Qu\'est-ce qu\'un polymère ?',
    options: [
      { id: 'a', text: 'Un métal léger', isCorrect: false },
      { id: 'b', text: 'Une longue chaîne de molécules répétées', isCorrect: true },
      { id: 'c', text: 'Un gaz comprimé dans un solide', isCorrect: false },
    ],
    correctAnswer: 'Une longue chaîne de molécules répétées',
    explanation: 'Un polymère est formé de milliers de petites molécules (monomères) assemblées en longues chaînes. Le caoutchouc, les fibres textiles et le plastique sont des polymères.',
    hint: 'Poly = beaucoup, mère = partie. Beaucoup de parties répétées.',
    tags: ['cm2', 'sciences', 'matiere', 'materiaux', 'polymeres', 'plastique', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-050',
    subject: 'sciences',
    title: 'Nanotechnologie : échelle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un nanomètre (nm) correspond à... ?',
    options: [
      { id: 'a', text: 'Un millième de mètre (mm)', isCorrect: false },
      { id: 'b', text: 'Un milliardième de mètre (10⁻⁹ m)', isCorrect: true },
      { id: 'c', text: 'Un millionième de mètre (μm)', isCorrect: false },
    ],
    correctAnswer: 'Un milliardième de mètre (10⁻⁹ m)',
    explanation: '1 nm = 10⁻⁹ m. Un cheveu fait environ 80 000 nm de diamètre. Les nanotechnologies travaillent à cette échelle atomique.',
    hint: 'Nano = milliardième.',
    tags: ['cm2', 'sciences', 'matiere', 'nanometres', 'echelle', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-051',
    subject: 'sciences',
    title: 'Énergie : conservation',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'energie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que dit la loi de conservation de l\'énergie ?',
    options: [
      { id: 'a', text: 'L\'énergie peut être créée à partir de rien', isCorrect: false },
      { id: 'b', text: 'L\'énergie ne se crée ni ne se détruit, elle se transforme', isCorrect: true },
      { id: 'c', text: 'L\'énergie s\'accumule au fil du temps', isCorrect: false },
    ],
    correctAnswer: 'L\'énergie ne se crée ni ne se détruit, elle se transforme',
    explanation: 'La loi de conservation de l\'énergie stipule que l\'énergie totale d\'un système isolé reste constante. Elle change de forme (mécanique → thermique → électrique…).',
    hint: 'Un ballon qui tombe transforme l\'énergie potentielle en énergie cinétique.',
    tags: ['cm2', 'sciences', 'matiere', 'energie', 'conservation', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-052',
    subject: 'sciences',
    title: 'Son : décibels',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'son',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À partir de quelle intensité sonore le son devient-il dangereux pour l\'oreille ?',
    options: [
      { id: 'a', text: 'Dès 50 décibels (conversation normale)', isCorrect: false },
      { id: 'b', text: 'À partir d\'environ 85 décibels', isCorrect: true },
      { id: 'c', text: 'Seulement à 200 décibels', isCorrect: false },
    ],
    correctAnswer: 'À partir d\'environ 85 décibels',
    explanation: 'L\'exposition prolongée à des sons dépassant 85 dB (aspiration, musique forte) peut endommager les cellules ciliées de l\'oreille interne, causant une surdité.',
    hint: 'Un concert de rock dépasse souvent 100 dB.',
    tags: ['cm2', 'sciences', 'matiere', 'son', 'decibels', 'sante', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-053',
    subject: 'sciences',
    title: 'Objets techniques : capteur',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un capteur de température est... ?',
    options: [
      { id: 'a', text: 'Un appareil qui produit de la chaleur', isCorrect: false },
      { id: 'b', text: 'Un dispositif qui mesure la température et transmet l\'information', isCorrect: true },
      { id: 'c', text: 'Un afficheur de données', isCorrect: false },
    ],
    correctAnswer: 'Un dispositif qui mesure la température et transmet l\'information',
    explanation: 'Un capteur est un transducteur : il convertit une grandeur physique (température, lumière, pression) en signal électrique exploitable par un système informatique.',
    hint: 'Le thermomètre de ta maison connectée est un capteur.',
    tags: ['cm2', 'sciences', 'matiere', 'objets-techniques', 'capteur', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-054',
    subject: 'sciences',
    title: 'Radioactivité : définition',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'radioactivite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La radioactivité naturelle est... ?',
    options: [
      { id: 'a', text: 'Un phénomène uniquement créé par l\'homme', isCorrect: false },
      { id: 'b', text: 'L\'émission spontanée de rayonnements par des atomes instables', isCorrect: true },
      { id: 'c', text: 'La diffusion de la lumière dans les roches', isCorrect: false },
    ],
    correctAnswer: 'L\'émission spontanée de rayonnements par des atomes instables',
    explanation: 'Certains atomes (uranium, radium…) ont un noyau instable qui se désintègre en émettant des rayonnements. La radioactivité naturelle existe depuis la formation de la Terre.',
    hint: 'Le granit des Vosges est naturellement radioactif.',
    tags: ['cm2', 'sciences', 'matiere', 'radioactivite', 'atome', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-055',
    subject: 'sciences',
    title: 'Mélange : chromatographie',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'melanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que permet de faire la chromatographie sur papier ?',
    options: [
      { id: 'a', text: 'Mesurer la masse des molécules', isCorrect: false },
      { id: 'b', text: 'Séparer et identifier les constituants d\'un mélange coloré', isCorrect: true },
      { id: 'c', text: 'Produire de l\'électricité à partir de solutions', isCorrect: false },
    ],
    correctAnswer: 'Séparer et identifier les constituants d\'un mélange coloré',
    explanation: 'La chromatographie utilise un solvant qui migre dans le papier en entraînant les molécules à des vitesses différentes, les séparant selon leurs propriétés.',
    hint: 'On peut séparer les couleurs d\'un feutre noir avec de l\'eau et du papier filtre.',
    tags: ['cm2', 'sciences', 'matiere', 'melanges', 'chromatographie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-056',
    subject: 'sciences',
    title: 'Intelligence artificielle : machine learning',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que l\'apprentissage automatique (machine learning) ?',
    options: [
      { id: 'a', text: 'Un robot qui copie les gestes humains', isCorrect: false },
      { id: 'b', text: 'Des algorithmes qui s\'améliorent en analysant de grandes quantités de données', isCorrect: true },
      { id: 'c', text: 'Un programme qui suit des instructions fixes sans s\'adapter', isCorrect: false },
    ],
    correctAnswer: 'Des algorithmes qui s\'améliorent en analysant de grandes quantités de données',
    explanation: 'Le machine learning est une branche de l\'IA : au lieu d\'être programmés explicitement, les algorithmes apprennent de données pour améliorer leurs prédictions.',
    hint: 'Les recommandations de films sur Netflix utilisent le machine learning.',
    tags: ['cm2', 'sciences', 'matiere', 'objets-techniques', 'ia', 'machine-learning', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-057',
    subject: 'sciences',
    title: 'Force : gravitation universelle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'forces',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la loi de la gravitation universelle de Newton ?',
    options: [
      { id: 'a', text: 'Tous les corps tombent à la même vitesse dans le vide', isCorrect: false },
      { id: 'b', text: 'Tout corps ayant une masse attire tout autre corps ayant une masse', isCorrect: true },
      { id: 'c', text: 'La Terre est le seul corps qui exerce une attraction gravitationnelle', isCorrect: false },
    ],
    correctAnswer: 'Tout corps ayant une masse attire tout autre corps ayant une masse',
    explanation: 'Newton a montré que toute masse attire toute autre masse. La Lune et la Terre s\'attirent mutuellement : c\'est ce qui crée les marées.',
    hint: 'La Lune tombe en permanence vers la Terre… mais rate toujours !',
    tags: ['cm2', 'sciences', 'matiere', 'forces', 'gravitation', 'newton', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-078',
    subject: 'sciences',
    title: 'Matière : antimatière',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'physique-fondamentale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que l\'antimatière ?',
    options: [
      { id: 'a', text: 'De la matière très compacte comme dans les étoiles à neutrons', isCorrect: false },
      { id: 'b', text: 'De la matière dont les particules ont des charges opposées à celles de la matière ordinaire', isCorrect: true },
      { id: 'c', text: 'De la matière invisible comme la matière noire', isCorrect: false },
    ],
    correctAnswer: 'De la matière dont les particules ont des charges opposées à celles de la matière ordinaire',
    explanation: 'L\'antimatière est composée d\'antiparticules (antiélectrons = positrons, antiprotons…). Quand matière et antimatière se rencontrent, elles s\'annihilent en énergie pure.',
    hint: 'Le Big Bang a produit autant de matière que d\'antimatière, mais l\'univers est fait de matière : encore un mystère !',
    tags: ['cm2', 'sciences', 'matiere', 'antimatiere', 'physique', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-079',
    subject: 'sciences',
    title: 'Matière : semiconducteurs',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'electricite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le silicium est un semiconducteur. Pourquoi est-il au cœur de l\'électronique moderne ?',
    options: [
      { id: 'a', text: 'Il est très bon conducteur comme le cuivre', isCorrect: false },
      { id: 'b', text: 'Sa conductivité électrique peut être contrôlée précisément, ce qui permet de créer des transistors', isCorrect: true },
      { id: 'c', text: 'Il est complètement isolant et protège les circuits', isCorrect: false },
    ],
    correctAnswer: 'Sa conductivité électrique peut être contrôlée précisément, ce qui permet de créer des transistors',
    explanation: 'Un semiconducteur est ni conducteur ni isolant. En ajoutant des impuretés (dopage), on contrôle sa conductivité. Les transistors (milliards dans les puces) sont des interrupteurs électroniques en silicium.',
    hint: 'Un smartphone contient des milliards de transistors en silicium.',
    tags: ['cm2', 'sciences', 'matiere', 'semiconducteurs', 'electronique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-080',
    subject: 'sciences',
    title: 'Matière : énergie nucléaire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'energie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La fission nucléaire utilisée dans les centrales produit de l\'énergie comment ?',
    options: [
      { id: 'a', text: 'En brûlant de l\'uranium avec de l\'oxygène', isCorrect: false },
      { id: 'b', text: 'En cassant des noyaux atomiques lourds, libérant une énorme énergie selon E=mc²', isCorrect: true },
      { id: 'c', text: 'En assemblant deux atomes d\'hydrogène en hélium', isCorrect: false },
    ],
    correctAnswer: 'En cassant des noyaux atomiques lourds, libérant une énorme énergie selon E=mc²',
    explanation: 'La fission : on bombarde des noyaux d\'uranium avec des neutrons. Le noyau se casse, libérant de l\'énergie (E=mc²). Cette chaleur produit de la vapeur qui fait tourner des turbines.',
    hint: 'E=mc² : une petite masse libère une énergie colossale (c = vitesse de la lumière).',
    tags: ['cm2', 'sciences', 'matiere', 'energie-nucleaire', 'fission', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-081',
    subject: 'sciences',
    title: 'Matière : supraconductivité',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'electricite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un matériau supraconducteur présente une résistance électrique nulle. Quel est l\'obstacle à son usage généralisé ?',
    options: [
      { id: 'a', text: 'Il ne conduit que les courants alternatifs', isCorrect: false },
      { id: 'b', text: 'La supraconductivité nécessite des températures proches du zéro absolu (-273°C)', isCorrect: true },
      { id: 'c', text: 'Il est trop lourd pour être utilisé dans les appareils portables', isCorrect: false },
    ],
    correctAnswer: 'La supraconductivité nécessite des températures proches du zéro absolu (-273°C)',
    explanation: 'Les supraconducteurs conductent l\'électricité sans perte (résistance = 0), mais seulement à des températures très basses. Les refroidir est coûteux. Des applications existent dans les IRM et les accélérateurs de particules.',
    hint: 'Le zéro absolu (-273,15°C) est la température la plus basse possible.',
    tags: ['cm2', 'sciences', 'matiere', 'supraconductivite', 'electricite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-082',
    subject: 'sciences',
    title: 'Matière : matériaux composites',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La fibre de carbone est un matériau composite. Qu\'est-ce qu\'un composite ?',
    options: [
      { id: 'a', text: 'Un alliage de deux métaux fondus ensemble', isCorrect: false },
      { id: 'b', text: 'Un matériau formé de deux composants ou plus aux propriétés complémentaires', isCorrect: true },
      { id: 'c', text: 'Un matériau produit uniquement par synthèse chimique', isCorrect: false },
    ],
    correctAnswer: 'Un matériau formé de deux composants ou plus aux propriétés complémentaires',
    explanation: 'La fibre de carbone = fibres très rigides dans une résine polymère. Le béton armé = béton (compression) + acier (traction). Chaque composant apporte une propriété que l\'autre n\'a pas.',
    hint: 'Le béton armé est le composite le plus utilisé au monde.',
    tags: ['cm2', 'sciences', 'matiere', 'composites', 'materiaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-083',
    subject: 'sciences',
    title: 'Matière : lumière et photons',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'optique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La lumière a une double nature. Laquelle ?',
    options: [
      { id: 'a', text: 'Elle est à la fois chaude et froide selon sa couleur', isCorrect: false },
      { id: 'b', text: 'Elle se comporte à la fois comme une onde et comme des particules (photons)', isCorrect: true },
      { id: 'c', text: 'Elle se déplace à des vitesses différentes selon la couleur dans le vide', isCorrect: false },
    ],
    correctAnswer: 'Elle se comporte à la fois comme une onde et comme des particules (photons)',
    explanation: 'La dualité onde-corpuscule : en physique quantique, la lumière est à la fois une onde (interférence) et un flux de particules (photons). Einstein a découvert les photons en étudiant l\'effet photoélectrique.',
    hint: 'Einstein a reçu le prix Nobel pour la découverte de l\'effet photoélectrique (pas pour la relativité).',
    tags: ['cm2', 'sciences', 'matiere', 'lumiere', 'photons', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-084',
    subject: 'sciences',
    title: 'Matière : plasma, 4ème état',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'etats-matiere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le plasma est souvent appelé le "quatrième état de la matière". Où le trouve-t-on ?',
    options: [
      { id: 'a', text: 'Dans les glaçons congelés à très basse pression', isCorrect: false },
      { id: 'b', text: 'Dans les étoiles, les éclairs et certains écrans de télévision', isCorrect: true },
      { id: 'c', text: 'Dans les liquides très denses comme le mercure', isCorrect: false },
    ],
    correctAnswer: 'Dans les étoiles, les éclairs et certains écrans de télévision',
    explanation: 'Le plasma est un gaz très chaud dont les électrons sont arrachés des atomes. C\'est l\'état le plus répandu dans l\'univers (étoiles). Sur Terre : les éclairs, les tubes néon, les écrans plasma.',
    hint: '99% de la matière visible dans l\'univers est sous forme de plasma (les étoiles).',
    tags: ['cm2', 'sciences', 'matiere', 'plasma', 'etats-matiere', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-085',
    subject: 'sciences',
    title: 'Matière : entropie',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'thermodynamique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi un verre cassé ne se reconstitue-t-il jamais spontanément ?',
    options: [
      { id: 'a', text: 'Parce que le verre est trop fragile pour se recoller', isCorrect: false },
      { id: 'b', text: 'Parce que l\'entropie (désordre) augmente naturellement — les systèmes évoluent vers plus de désordre', isCorrect: true },
      { id: 'c', text: 'Parce que l\'énergie du choc a détruit les molécules de verre', isCorrect: false },
    ],
    correctAnswer: 'Parce que l\'entropie (désordre) augmente naturellement — les systèmes évoluent vers plus de désordre',
    explanation: 'Le 2ème principe de la thermodynamique : l\'entropie (désordre) d\'un système isolé ne peut qu\'augmenter. Un verre en mille morceaux a plus d\'entropie qu\'un verre intact.',
    hint: 'L\'entropie explique pourquoi le temps semble s\'écouler dans un sens unique.',
    tags: ['cm2', 'sciences', 'matiere', 'entropie', 'thermodynamique', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-086',
    subject: 'sciences',
    title: 'Matière : spectroscopie',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'optique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les astronomes savent-ils de quoi sont faites des étoiles à des millions d\'années-lumière ?',
    options: [
      { id: 'a', text: 'En envoyant des sondes spatiales qui y prélevèrent des échantillons', isCorrect: false },
      { id: 'b', text: 'En analysant la lumière émise : chaque élément chimique produit un spectre unique (spectroscopie)', isCorrect: true },
      { id: 'c', text: 'En calculant la masse de l\'étoile à distance', isCorrect: false },
    ],
    correctAnswer: 'En analysant la lumière émise : chaque élément chimique produit un spectre unique (spectroscopie)',
    explanation: 'Chaque atome absorbe et émet la lumière à des longueurs d\'onde précises (comme une empreinte digitale). En décomposant la lumière stellaire, on lit quels éléments sont présents.',
    hint: 'L\'hélium a été découvert dans le Soleil avant de l\'être sur Terre (helios = soleil).',
    tags: ['cm2', 'sciences', 'matiere', 'spectroscopie', 'astronomie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-087',
    subject: 'sciences',
    title: 'Matière : polymérisation',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'reactions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment fabrique-t-on du plastique polyéthylène (PE) à partir du pétrole ?',
    options: [
      { id: 'a', text: 'En chauffant directement le pétrole brut jusqu\'à ébullition', isCorrect: false },
      { id: 'b', text: 'En liant chimiquement des milliers de molécules d\'éthylène (réaction de polymérisation)', isCorrect: true },
      { id: 'c', text: 'En moulant le pétrole dans un moule à haute pression', isCorrect: false },
    ],
    correctAnswer: 'En liant chimiquement des milliers de molécules d\'éthylène (réaction de polymérisation)',
    explanation: 'La polymérisation enchaîne des milliers de monomères (éthylène = CH₂=CH₂) pour former une longue chaîne : le polyéthylène. C\'est le plastique le plus produit au monde (sacs, bouteilles).',
    hint: 'Éthylène (monomer) → polyéthylène (polymère) = sac plastique.',
    tags: ['cm2', 'sciences', 'matiere', 'polymerisation', 'plastique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-121',
    subject: 'sciences',
    title: 'Mesures : convertir kg en grammes (décimal)',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un échantillon minéral pèse 2,4 kg. Quelle est sa masse en grammes ?',
    options: [
      { id: 'a', text: '240 g', isCorrect: false },
      { id: 'b', text: '2 400 g', isCorrect: true },
      { id: 'c', text: '24 000 g', isCorrect: false },
    ],
    correctAnswer: '2 400 g',
    explanation: '1 kg = 1 000 g. Donc 2,4 kg = 2 400 g.',
    hint: '1 kilogramme = 1 000 grammes.',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'masse', 'conversion', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'medium' },
  },
  {
    id: 'sc-cm2-com-122',
    subject: 'sciences',
    title: 'Mesures : calculer une masse à partir de la densité',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La densité du fer est 7,9 g/cm³. Quelle est la masse d\'un morceau de fer de 5 cm³ ?',
    options: [
      { id: 'a', text: '5 g', isCorrect: false },
      { id: 'b', text: '39,5 g', isCorrect: true },
      { id: 'c', text: '79 g', isCorrect: false },
    ],
    correctAnswer: '39,5 g',
    explanation: 'Masse = densité × volume = 7,9 × 5 = 39,5 g.',
    hint: 'Densité (g/cm³) × volume (cm³) = masse (g).',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'densite', 'masse', 'calcul', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'high' },
  },
  {
    id: 'sc-cm2-com-123',
    subject: 'sciences',
    title: 'Mesures : amplitude thermique avec températures négatives',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un thermomètre indique −5°C le matin et 12°C l\'après-midi. Quelle est l\'amplitude thermique de la journée ?',
    options: [
      { id: 'a', text: '7°C', isCorrect: false },
      { id: 'b', text: '17°C', isCorrect: true },
      { id: 'c', text: '60°C', isCorrect: false },
    ],
    correctAnswer: '17°C',
    explanation: '12 − (−5) = 12 + 5 = 17°C. L\'amplitude thermique est la différence entre la température max et la température min.',
    hint: 'Soustraire un nombre négatif revient à l\'additionner.',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'temperature', 'amplitude', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'medium' },
  },
  {
    id: 'sc-cm2-com-124',
    subject: 'sciences',
    title: 'Mesures : comparer deux volumes en unités différentes',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une fiole contient 3,5 L de solution. Une autre en contient 3 450 mL. Quelle est la différence entre les deux ?',
    options: [
      { id: 'a', text: '5 mL', isCorrect: false },
      { id: 'b', text: '50 mL', isCorrect: true },
      { id: 'c', text: '500 mL', isCorrect: false },
    ],
    correctAnswer: '50 mL',
    explanation: '3,5 L = 3 500 mL. Différence : 3 500 − 3 450 = 50 mL.',
    hint: 'Convertis 3,5 L en mL, puis calcule la différence.',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'volume', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'medium' },
  },
  {
    id: 'sc-cm2-com-125',
    subject: 'sciences',
    title: 'Mesures : rapport entre deux masses',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un os fossile pèse 280 g. Un os actuel équivalent pèse 70 g. Combien de fois l\'os fossile est-il plus lourd ?',
    options: [
      { id: 'a', text: '2 fois', isCorrect: false },
      { id: 'b', text: '4 fois', isCorrect: true },
      { id: 'c', text: '8 fois', isCorrect: false },
    ],
    correctAnswer: '4 fois',
    explanation: '280 ÷ 70 = 4. L\'os fossile est 4 fois plus lourd que l\'os actuel.',
    hint: 'Pour trouver le rapport, on divise la grande valeur par la petite.',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'masse', 'rapport', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'medium' },
  },
  {
    id: 'sc-cm2-com-126',
    subject: 'sciences',
    title: 'Mesures : calculer une température moyenne',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Températures relevées sur 4 jours : −2°C, 1°C, 7°C, 2°C. Quelle est la température moyenne ?',
    options: [
      { id: 'a', text: '2°C', isCorrect: true },
      { id: 'b', text: '4°C', isCorrect: false },
      { id: 'c', text: '8°C', isCorrect: false },
    ],
    correctAnswer: '2°C',
    explanation: 'Somme : −2 + 1 + 7 + 2 = 8. Moyenne : 8 ÷ 4 = 2°C.',
    hint: 'Additionne toutes les valeurs, puis divise par le nombre de relevés.',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'temperature', 'moyenne', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'high' },
  },
  {
    id: 'sc-cm2-com-127',
    subject: 'sciences',
    title: 'Mesures : diviser une longueur',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un câble électrique de 2,5 m est coupé en 5 parts égales. Quelle est la longueur de chaque part ?',
    options: [
      { id: 'a', text: '0,25 m', isCorrect: false },
      { id: 'b', text: '0,5 m', isCorrect: true },
      { id: 'c', text: '5 m', isCorrect: false },
    ],
    correctAnswer: '0,5 m',
    explanation: '2,5 ÷ 5 = 0,5. Chaque part mesure 0,5 m, soit 50 cm.',
    hint: 'Divise la longueur totale par le nombre de parts.',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'longueur', 'division', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'medium' },
  },
  {
    id: 'sc-cm2-com-128',
    subject: 'sciences',
    title: 'Mesures : convertir cm³ en litres',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'mesures',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une boîte a un volume de 5 000 cm³. Sachant que 1 litre = 1 000 cm³, combien de litres peut-elle contenir ?',
    options: [
      { id: 'a', text: '0,5 L', isCorrect: false },
      { id: 'b', text: '5 L', isCorrect: true },
      { id: 'c', text: '50 L', isCorrect: false },
    ],
    correctAnswer: '5 L',
    explanation: '5 000 ÷ 1 000 = 5. La boîte peut contenir 5 litres.',
    hint: 'Divise le volume en cm³ par 1 000 pour obtenir des litres.',
    tags: ['cm2', 'sciences', 'matiere', 'mesures', 'volume', 'conversion', 'cm3', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    meta: { numericLoad: 'medium' },
  },
];
