import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCpEspaceExercises: DecouverteExercise[] = [

  // CP · espace · maison_ecole
  {
    id: 'ddm-cp-esp-001',
    subject: 'decouverte_du_monde',
    title: 'La chambre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis la bonne pièce.',
    prompt: 'Dans quelle pièce dort-on à la maison ?',
    options: [
      { id: 'a', text: 'la cuisine', isCorrect: false },
      { id: 'b', text: 'la chambre', isCorrect: true },
      { id: 'c', text: 'le salon', isCorrect: false },
      { id: 'd', text: 'le couloir', isCorrect: false },
    ],
    correctAnswer: 'la chambre',
    explanation: 'On dort dans la chambre, où se trouve le lit.',
    hint: 'C\'est là où tu te réveilles le matin.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-002',
    subject: 'decouverte_du_monde',
    title: 'La cantine',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis le bon endroit.',
    prompt: 'Où mange-t-on à l\'école le midi ?',
    options: [
      { id: 'a', text: 'dans la cour', isCorrect: false },
      { id: 'b', text: 'en classe', isCorrect: false },
      { id: 'c', text: 'à la cantine', isCorrect: true },
      { id: 'd', text: 'dans les couloirs', isCorrect: false },
    ],
    correctAnswer: 'à la cantine',
    explanation: 'La cantine est la grande salle de l\'école où les élèves déjeunent.',
    hint: 'C\'est là où il y a des plateaux repas.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-003',
    subject: 'decouverte_du_monde',
    title: 'La cour de récréation',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on l\'endroit où les enfants jouent à l\'école ?',
    options: [
      { id: 'a', text: 'la salle de classe', isCorrect: false },
      { id: 'b', text: 'la cantine', isCorrect: false },
      { id: 'c', text: 'la cour de récréation', isCorrect: true },
      { id: 'd', text: 'la bibliothèque', isCorrect: false },
    ],
    correctAnswer: 'la cour de récréation',
    explanation: 'La cour de récréation est l\'espace extérieur de l\'école pour jouer.',
    hint: 'On y va pendant la récré.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-006',
    subject: 'decouverte_du_monde',
    title: 'Se laver à la maison',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis la bonne pièce.',
    prompt: 'Dans quelle pièce se lave-t-on à la maison ?',
    options: [
      { id: 'a', text: 'le salon', isCorrect: false },
      { id: 'b', text: 'la chambre', isCorrect: false },
      { id: 'c', text: 'la salle de bains', isCorrect: true },
      { id: 'd', text: 'le couloir', isCorrect: false },
    ],
    correctAnswer: 'la salle de bains',
    explanation: 'Dans la salle de bains, il y a le lavabo, la douche ou la baignoire.',
    hint: 'On y brosse aussi les dents.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CP · espace · quartier
  {
    id: 'ddm-cp-esp-004',
    subject: 'decouverte_du_monde',
    title: 'Où achète-t-on du pain ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'quartier',
    format: 'qcm',
    instructions: 'Choisis le bon magasin.',
    prompt: 'Où va-t-on pour acheter du pain dans le quartier ?',
    options: [
      { id: 'a', text: 'à la pharmacie', isCorrect: false },
      { id: 'b', text: 'à la boulangerie', isCorrect: true },
      { id: 'c', text: 'à la bibliothèque', isCorrect: false },
      { id: 'd', text: 'à la piscine', isCorrect: false },
    ],
    correctAnswer: 'à la boulangerie',
    explanation: 'La boulangerie est le magasin où le boulanger fabrique et vend le pain.',
    hint: 'Ça sent bon le pain chaud !',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-005',
    subject: 'decouverte_du_monde',
    title: 'Quand tu sors de chez toi',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'quartier',
    format: 'qcm',
    instructions: 'Choisis le bon endroit.',
    prompt: 'Quand tu sors de ta maison, tu te retrouves dans…',
    options: [
      { id: 'a', text: 'la forêt', isCorrect: false },
      { id: 'b', text: 'la mer', isCorrect: false },
      { id: 'c', text: 'la rue ou le quartier', isCorrect: true },
      { id: 'd', text: 'la montagne', isCorrect: false },
    ],
    correctAnswer: 'la rue ou le quartier',
    explanation: 'Autour de ta maison, il y a les rues, les voisins, les magasins : c\'est ton quartier.',
    hint: 'C\'est l\'endroit proche de chez toi.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
