import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCpEspaceHabitatExercises: DecouverteExercise[] = [

  // CP · espace · habitat
  {
    id: 'ddm-cp-esp-007',
    subject: 'decouverte_du_monde',
    title: 'Maison ou appartement',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un appartement se trouve généralement dans…',
    options: [
      { id: 'a', text: 'un champ', isCorrect: false },
      { id: 'b', text: 'un immeuble', isCorrect: true },
      { id: 'c', text: 'une forêt', isCorrect: false },
      { id: 'd', text: 'une ferme', isCorrect: false },
    ],
    correctAnswer: 'un immeuble',
    explanation: 'Un appartement est un logement dans un immeuble. Plusieurs familles habitent dans le même bâtiment.',
    hint: 'Un immeuble a plusieurs étages et plusieurs logements.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-008',
    subject: 'decouverte_du_monde',
    title: 'La maison individuelle',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une maison individuelle se distingue d\'un appartement parce qu\'elle a souvent…',
    options: [
      { id: 'a', text: 'des voisins juste au-dessus', isCorrect: false },
      { id: 'b', text: 'un jardin autour', isCorrect: true },
      { id: 'c', text: 'un ascenseur', isCorrect: false },
      { id: 'd', text: 'une cave commune', isCorrect: false },
    ],
    correctAnswer: 'un jardin autour',
    explanation: 'La maison individuelle est entourée de son propre jardin. C\'est différent de l\'appartement en immeuble.',
    hint: 'On peut jouer dehors dans son propre jardin.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-009',
    subject: 'decouverte_du_monde',
    title: 'Le salon',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis ce qu\'on fait dans le salon.',
    prompt: 'Dans quelle pièce regarde-t-on souvent la télévision et reçoit-on les invités ?',
    options: [
      { id: 'a', text: 'la cuisine', isCorrect: false },
      { id: 'b', text: 'la salle de bains', isCorrect: false },
      { id: 'c', text: 'le salon', isCorrect: true },
      { id: 'd', text: 'les toilettes', isCorrect: false },
    ],
    correctAnswer: 'le salon',
    explanation: 'Le salon est la pièce principale où l\'on se réunit pour regarder la télé, discuter et recevoir des invités.',
    hint: 'Il y a souvent un canapé et une télé.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-010',
    subject: 'decouverte_du_monde',
    title: 'La cuisine',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis ce qu\'on fait dans la cuisine.',
    prompt: 'Dans quelle pièce prépare-t-on les repas ?',
    options: [
      { id: 'a', text: 'le salon', isCorrect: false },
      { id: 'b', text: 'la cuisine', isCorrect: true },
      { id: 'c', text: 'la chambre', isCorrect: false },
      { id: 'd', text: 'le couloir', isCorrect: false },
    ],
    correctAnswer: 'la cuisine',
    explanation: 'Dans la cuisine, il y a une cuisinière, un réfrigérateur et un évier. On y prépare à manger.',
    hint: 'Ça sent bon quand maman ou papa cuisinent.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-011',
    subject: 'decouverte_du_monde',
    title: 'Les toilettes (WC)',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans quelle pièce va-t-on pour faire ses besoins ?',
    options: [
      { id: 'a', text: 'la cuisine', isCorrect: false },
      { id: 'b', text: 'les toilettes (WC)', isCorrect: true },
      { id: 'c', text: 'la chambre', isCorrect: false },
      { id: 'd', text: 'l\'entrée', isCorrect: false },
    ],
    correctAnswer: 'les toilettes (WC)',
    explanation: 'Les toilettes (aussi appelées WC) sont la pièce où l\'on fait ses besoins. Il faut bien se laver les mains après.',
    hint: 'On les appelle aussi les WC.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-012',
    subject: 'decouverte_du_monde',
    title: 'Le couloir',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert le couloir dans une maison ?',
    options: [
      { id: 'a', text: 'À dormir', isCorrect: false },
      { id: 'b', text: 'À cuisiner', isCorrect: false },
      { id: 'c', text: 'À circuler entre les pièces', isCorrect: true },
      { id: 'd', text: 'À se laver', isCorrect: false },
    ],
    correctAnswer: 'À circuler entre les pièces',
    explanation: 'Le couloir est un passage qui permet de passer d\'une pièce à une autre.',
    hint: 'C\'est un passage, pas une pièce où l\'on vit.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-013',
    subject: 'decouverte_du_monde',
    title: 'Dedans ou dehors',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où se trouve le jardin d\'une maison ?',
    options: [
      { id: 'a', text: 'À l\'intérieur de la maison', isCorrect: false },
      { id: 'b', text: 'À l\'extérieur de la maison', isCorrect: true },
      { id: 'c', text: 'Dans le garage', isCorrect: false },
      { id: 'd', text: 'Dans la cuisine', isCorrect: false },
    ],
    correctAnswer: 'À l\'extérieur de la maison',
    explanation: 'Le jardin se trouve à l\'extérieur (dehors) de la maison. On y joue quand il fait beau.',
    hint: 'Dehors = à l\'extérieur. Dedans = à l\'intérieur.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-014',
    subject: 'decouverte_du_monde',
    title: 'Le garage',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert le garage dans une maison ?',
    options: [
      { id: 'a', text: 'À dormir', isCorrect: false },
      { id: 'b', text: 'À garer la voiture et ranger des outils', isCorrect: true },
      { id: 'c', text: 'À cuisiner', isCorrect: false },
      { id: 'd', text: 'À se laver', isCorrect: false },
    ],
    correctAnswer: 'À garer la voiture et ranger des outils',
    explanation: 'Le garage est un espace pour garer la voiture et parfois ranger des vélos, des outils ou d\'autres objets.',
    hint: 'C\'est là où on met la voiture quand il pleut.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-015',
    subject: 'decouverte_du_monde',
    title: 'La cave',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La cave se trouve généralement…',
    options: [
      { id: 'a', text: 'au dernier étage', isCorrect: false },
      { id: 'b', text: 'sous la maison, en dessous du sol', isCorrect: true },
      { id: 'c', text: 'dans le jardin', isCorrect: false },
      { id: 'd', text: 'sur le toit', isCorrect: false },
    ],
    correctAnswer: 'sous la maison, en dessous du sol',
    explanation: 'La cave est un espace en dessous de la maison, sous le niveau du sol. On y range souvent des affaires.',
    hint: 'Elle est en dessous de tout, dans la terre.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-016',
    subject: 'decouverte_du_monde',
    title: 'Le grenier',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le grenier se trouve généralement…',
    options: [
      { id: 'a', text: 'sous la maison', isCorrect: false },
      { id: 'b', text: 'dans le jardin', isCorrect: false },
      { id: 'c', text: 'tout en haut de la maison, sous le toit', isCorrect: true },
      { id: 'd', text: 'dans la cuisine', isCorrect: false },
    ],
    correctAnswer: 'tout en haut de la maison, sous le toit',
    explanation: 'Le grenier est l\'espace sous le toit, tout en haut de la maison. On y range les vieilles affaires.',
    hint: 'Il est en haut, juste sous les tuiles.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-017',
    subject: 'decouverte_du_monde',
    title: 'Habitat à la campagne',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on un endroit où l\'on élève des animaux et cultive la terre ?',
    options: [
      { id: 'a', text: 'un immeuble', isCorrect: false },
      { id: 'b', text: 'une ferme', isCorrect: true },
      { id: 'c', text: 'un château', isCorrect: false },
      { id: 'd', text: 'une villa', isCorrect: false },
    ],
    correctAnswer: 'une ferme',
    explanation: 'Une ferme est un lieu à la campagne où l\'on cultive des plantes et élève des animaux.',
    hint: 'Il y a des vaches, des poules et des tracteurs.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-018',
    subject: 'decouverte_du_monde',
    title: 'Types de logements',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces logements se trouve en ville dans un immeuble ?',
    options: [
      { id: 'a', text: 'une ferme', isCorrect: false },
      { id: 'b', text: 'un appartement', isCorrect: true },
      { id: 'c', text: 'un igloo', isCorrect: false },
      { id: 'd', text: 'une cabane dans les bois', isCorrect: false },
    ],
    correctAnswer: 'un appartement',
    explanation: 'Un appartement est un logement dans un immeuble, souvent en ville.',
    hint: 'On prend l\'ascenseur ou les escaliers pour y accéder.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-019',
    subject: 'decouverte_du_monde',
    title: 'Mon adresse',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'adresse de ta maison ou de ton appartement sert à…',
    options: [
      { id: 'a', text: 'trouver où tu habites', isCorrect: true },
      { id: 'b', text: 'connaître ton âge', isCorrect: false },
      { id: 'c', text: 'savoir quelle école tu fréquentes', isCorrect: false },
      { id: 'd', text: 'mesurer la taille de ta maison', isCorrect: false },
    ],
    correctAnswer: 'trouver où tu habites',
    explanation: 'L\'adresse (numéro de rue + ville) permet au facteur ou à tes amis de savoir où tu habites.',
    hint: 'Sans adresse, le facteur ne pourrait pas livrer ton courrier.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-020',
    subject: 'decouverte_du_monde',
    title: 'Les voisins',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on les personnes qui habitent près de chez toi ?',
    options: [
      { id: 'a', text: 'les cousins', isCorrect: false },
      { id: 'b', text: 'les voisins', isCorrect: true },
      { id: 'c', text: 'les amis de classe', isCorrect: false },
      { id: 'd', text: 'les inconnus', isCorrect: false },
    ],
    correctAnswer: 'les voisins',
    explanation: 'Les voisins sont les personnes qui habitent à côté de chez toi, dans la même rue ou le même immeuble.',
    hint: 'Ce sont les gens qui habitent juste à côté.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-021',
    subject: 'decouverte_du_monde',
    title: 'Salle de bains',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans la salle de bains, on trouve…',
    options: [
      { id: 'a', text: 'un lit et une armoire', isCorrect: false },
      { id: 'b', text: 'un lavabo, une douche ou baignoire', isCorrect: true },
      { id: 'c', text: 'une cuisinière et un réfrigérateur', isCorrect: false },
      { id: 'd', text: 'un canapé et une télé', isCorrect: false },
    ],
    correctAnswer: 'un lavabo, une douche ou baignoire',
    explanation: 'La salle de bains contient un lavabo pour se laver les mains, une douche ou une baignoire et un miroir.',
    hint: 'C\'est là où on se brosse les dents.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-022',
    subject: 'decouverte_du_monde',
    title: 'La chambre des enfants',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans la chambre, on trouve principalement…',
    options: [
      { id: 'a', text: 'une cuisinière et un micro-ondes', isCorrect: false },
      { id: 'b', text: 'un lit, une armoire et des jouets', isCorrect: true },
      { id: 'c', text: 'un canapé et une télé', isCorrect: false },
      { id: 'd', text: 'un lavabo et une baignoire', isCorrect: false },
    ],
    correctAnswer: 'un lit, une armoire et des jouets',
    explanation: 'Dans la chambre d\'enfant, il y a le lit pour dormir, une armoire pour les vêtements et parfois des jouets.',
    hint: 'C\'est ta pièce personnelle où tu dors.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-023',
    subject: 'decouverte_du_monde',
    title: 'L\'entrée de la maison',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la première pièce que l\'on traverse en entrant dans une maison ?',
    options: [
      { id: 'a', text: 'la cuisine', isCorrect: false },
      { id: 'b', text: 'la chambre', isCorrect: false },
      { id: 'c', text: 'l\'entrée', isCorrect: true },
      { id: 'd', text: 'la salle de bains', isCorrect: false },
    ],
    correctAnswer: 'l\'entrée',
    explanation: 'L\'entrée est la pièce ou l\'espace juste derrière la porte d\'entrée. On y enlève ses chaussures et on y accroche son manteau.',
    hint: 'On y enlève ses chaussures en arrivant.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-024',
    subject: 'decouverte_du_monde',
    title: 'La salle à manger',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans quelle pièce mange-t-on souvent en famille ?',
    options: [
      { id: 'a', text: 'le couloir', isCorrect: false },
      { id: 'b', text: 'la cave', isCorrect: false },
      { id: 'c', text: 'la salle à manger', isCorrect: true },
      { id: 'd', text: 'le grenier', isCorrect: false },
    ],
    correctAnswer: 'la salle à manger',
    explanation: 'La salle à manger est la pièce avec une table et des chaises, où la famille se réunit pour manger.',
    hint: 'Il y a une grande table pour toute la famille.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-025',
    subject: 'decouverte_du_monde',
    title: 'Porte et fenêtre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La fenêtre sert à…',
    options: [
      { id: 'a', text: 'entrer et sortir de la maison', isCorrect: false },
      { id: 'b', text: 'laisser entrer la lumière et l\'air', isCorrect: true },
      { id: 'c', text: 'cuisiner', isCorrect: false },
      { id: 'd', text: 'rangement des affaires', isCorrect: false },
    ],
    correctAnswer: 'laisser entrer la lumière et l\'air',
    explanation: 'La fenêtre laisse entrer la lumière du soleil et peut s\'ouvrir pour aérer la pièce.',
    hint: 'On regarde dehors à travers elle.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-esp-026',
    subject: 'decouverte_du_monde',
    title: 'Le toit',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'habitat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert le toit d\'une maison ?',
    options: [
      { id: 'a', text: 'À cuisiner', isCorrect: false },
      { id: 'b', text: 'À protéger de la pluie et du froid', isCorrect: true },
      { id: 'c', text: 'À stocker les voitures', isCorrect: false },
      { id: 'd', text: 'À décorer la maison', isCorrect: false },
    ],
    correctAnswer: 'À protéger de la pluie et du froid',
    explanation: 'Le toit couvre la maison et protège l\'intérieur de la pluie, du vent et du froid.',
    hint: 'Grâce à lui, on est au sec quand il pleut.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
