import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCpReperesExercises: DecouverteExercise[] = [

  // CP · reperes · famille
  {
    id: 'ddm-cp-rep-001',
    subject: 'decouverte_du_monde',
    title: 'Les membres de la famille',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le papa de ta maman ?',
    options: [
      { id: 'a', text: 'mon oncle', isCorrect: false },
      { id: 'b', text: 'mon grand-père', isCorrect: true },
      { id: 'c', text: 'mon cousin', isCorrect: false },
      { id: 'd', text: 'mon parrain', isCorrect: false },
    ],
    correctAnswer: 'mon grand-père',
    explanation: 'Le papa de ta maman est ton grand-père. La maman de ta maman est ta grand-mère.',
    hint: 'Les parents de tes parents sont tes grands-parents.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-002',
    subject: 'decouverte_du_monde',
    title: 'Frère ou sœur',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on un enfant de la même famille qui est une fille ?',
    options: [
      { id: 'a', text: 'un frère', isCorrect: false },
      { id: 'b', text: 'un cousin', isCorrect: false },
      { id: 'c', text: 'une sœur', isCorrect: true },
      { id: 'd', text: 'une amie', isCorrect: false },
    ],
    correctAnswer: 'une sœur',
    explanation: 'Les enfants d\'un même père et d\'une même mère sont des frères et sœurs.',
    hint: 'C\'est une fille qui partage les mêmes parents que toi.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-003',
    subject: 'decouverte_du_monde',
    title: 'Les parents',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans une famille, les parents sont…',
    options: [
      { id: 'a', text: 'le frère et la sœur', isCorrect: false },
      { id: 'b', text: 'le papa et la maman', isCorrect: true },
      { id: 'c', text: 'le grand-père et la grand-mère', isCorrect: false },
      { id: 'd', text: 'l\'oncle et la tante', isCorrect: false },
    ],
    correctAnswer: 'le papa et la maman',
    explanation: 'Les parents sont le père et la mère. Ils s\'occupent de leurs enfants.',
    hint: 'Ce sont les adultes les plus proches dans ta famille.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-004',
    subject: 'decouverte_du_monde',
    title: 'L\'oncle et la tante',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le frère ou la sœur de ton papa, c\'est ton…',
    options: [
      { id: 'a', text: 'cousin ou cousine', isCorrect: false },
      { id: 'b', text: 'oncle ou tante', isCorrect: true },
      { id: 'c', text: 'grand-père ou grand-mère', isCorrect: false },
      { id: 'd', text: 'parrain ou marraine', isCorrect: false },
    ],
    correctAnswer: 'oncle ou tante',
    explanation: 'Le frère de ton papa ou de ta maman est ton oncle. La sœur est ta tante.',
    hint: 'Un oncle est le frère de l\'un de tes parents.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-005',
    subject: 'decouverte_du_monde',
    title: 'Rôle des parents',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que font les parents pour leurs enfants ?',
    options: [
      { id: 'a', text: 'Ils les laissent seuls toute la journée.', isCorrect: false },
      { id: 'b', text: 'Ils s\'en occupent, les nourrissent et les protègent.', isCorrect: true },
      { id: 'c', text: 'Ils les envoient travailler.', isCorrect: false },
      { id: 'd', text: 'Ils ne font rien de spécial.', isCorrect: false },
    ],
    correctAnswer: 'Ils s\'en occupent, les nourrissent et les protègent.',
    explanation: 'Les parents ont le rôle de s\'occuper de leurs enfants : les nourrir, les soigner, les aimer, les aider à grandir.',
    hint: 'Pense à tout ce que tes parents font pour toi chaque jour.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CP · reperes · regles_vie
  {
    id: 'ddm-cp-rep-006',
    subject: 'decouverte_du_monde',
    title: 'Lever la main en classe',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pour prendre la parole en classe, que doit-on faire ?',
    options: [
      { id: 'a', text: 'Crier fort pour être entendu', isCorrect: false },
      { id: 'b', text: 'Lever la main et attendre d\'être interrogé', isCorrect: true },
      { id: 'c', text: 'Se lever et s\'en aller', isCorrect: false },
      { id: 'd', text: 'Chuchoter avec son voisin', isCorrect: false },
    ],
    correctAnswer: 'Lever la main et attendre d\'être interrogé',
    explanation: 'En classe, on lève la main pour demander la parole. Cela permet à tout le monde de s\'exprimer dans l\'ordre.',
    hint: 'C\'est une règle pour que tout le monde puisse s\'exprimer.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-007',
    subject: 'decouverte_du_monde',
    title: 'Ranger sa place',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi range-t-on sa place à la fin de la journée ?',
    options: [
      { id: 'a', text: 'Pour que la salle soit propre et agréable pour tout le monde.', isCorrect: true },
      { id: 'b', text: 'Parce que c\'est puni de ne pas le faire.', isCorrect: false },
      { id: 'c', text: 'Pour cacher ses affaires.', isCorrect: false },
      { id: 'd', text: 'Ce n\'est pas nécessaire de ranger.', isCorrect: false },
    ],
    correctAnswer: 'Pour que la salle soit propre et agréable pour tout le monde.',
    explanation: 'Ranger sa place est un geste de respect pour les autres. Une classe bien rangée est plus agréable à vivre.',
    hint: 'Pense aux autres élèves qui utilisent aussi la salle.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-008',
    subject: 'decouverte_du_monde',
    title: 'Être poli',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand quelqu\'un te donne quelque chose, tu dis…',
    options: [
      { id: 'a', text: 'Rien du tout', isCorrect: false },
      { id: 'b', text: 'Merci !', isCorrect: true },
      { id: 'c', text: 'Encore !', isCorrect: false },
      { id: 'd', text: 'C\'est à moi !', isCorrect: false },
    ],
    correctAnswer: 'Merci !',
    explanation: 'Dire « merci » est une marque de politesse et de respect envers la personne qui a fait quelque chose pour toi.',
    hint: 'C\'est un mot magique de politesse.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-009',
    subject: 'decouverte_du_monde',
    title: 'Aider un camarade',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un camarade est triste et tout seul dans la cour. Que fais-tu ?',
    options: [
      { id: 'a', text: 'Je l\'ignore et je continue à jouer.', isCorrect: false },
      { id: 'b', text: 'Je m\'approche et je lui demande si ça va.', isCorrect: true },
      { id: 'c', text: 'Je me moque de lui.', isCorrect: false },
      { id: 'd', text: 'Je lui prends ses jouets.', isCorrect: false },
    ],
    correctAnswer: 'Je m\'approche et je lui demande si ça va.',
    explanation: 'Aider un camarade en difficulté, c\'est faire preuve d\'empathie et de solidarité.',
    hint: 'Pense à comment tu voudrais être traité si tu étais triste.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-010',
    subject: 'decouverte_du_monde',
    title: 'Ne pas se battre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un camarade te prend ton stylo. Que dois-tu faire ?',
    options: [
      { id: 'a', text: 'Le frapper pour récupérer mon stylo.', isCorrect: false },
      { id: 'b', text: 'Lui demander de me le rendre calmement ou prévenir un adulte.', isCorrect: true },
      { id: 'c', text: 'Pleurer sans rien dire.', isCorrect: false },
      { id: 'd', text: 'Prendre quelque chose à lui en échange.', isCorrect: false },
    ],
    correctAnswer: 'Lui demander de me le rendre calmement ou prévenir un adulte.',
    explanation: 'On résout les conflits avec les mots, pas avec les coups. On peut aussi demander l\'aide d\'un adulte.',
    hint: 'Les mots sont plus efficaces que les gestes.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CP · reperes · metiers
  {
    id: 'ddm-cp-rep-011',
    subject: 'decouverte_du_monde',
    title: 'Le métier de maîtresse',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le métier de la maîtresse ou du maître ?',
    options: [
      { id: 'a', text: 'médecin', isCorrect: false },
      { id: 'b', text: 'enseignant(e)', isCorrect: true },
      { id: 'c', text: 'pompier', isCorrect: false },
      { id: 'd', text: 'cuisinier', isCorrect: false },
    ],
    correctAnswer: 'enseignant(e)',
    explanation: 'La maîtresse ou le maître est un enseignant(e). Son travail est d\'apprendre à lire, écrire et compter aux élèves.',
    hint: 'C\'est la personne qui t\'apprend des choses à l\'école.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-012',
    subject: 'decouverte_du_monde',
    title: 'Le docteur',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui soigne les malades et prescrit des médicaments ?',
    options: [
      { id: 'a', text: 'le boulanger', isCorrect: false },
      { id: 'b', text: 'le facteur', isCorrect: false },
      { id: 'c', text: 'le médecin (docteur)', isCorrect: true },
      { id: 'd', text: 'le pompier', isCorrect: false },
    ],
    correctAnswer: 'le médecin (docteur)',
    explanation: 'Le médecin (ou docteur) examine les malades et prescrit les médicaments nécessaires pour guérir.',
    hint: 'C\'est lui qui t\'examine quand tu as de la fièvre.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-013',
    subject: 'decouverte_du_monde',
    title: 'Le pompier',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le métier de la personne qui éteint les incendies ?',
    options: [
      { id: 'a', text: 'le policier', isCorrect: false },
      { id: 'b', text: 'le pompier', isCorrect: true },
      { id: 'c', text: 'le jardinier', isCorrect: false },
      { id: 'd', text: 'le cuisinier', isCorrect: false },
    ],
    correctAnswer: 'le pompier',
    explanation: 'Le pompier intervient pour éteindre les incendies, mais aussi pour porter secours aux personnes en danger.',
    hint: 'Il utilise des grandes échelles et des lances à eau.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-014',
    subject: 'decouverte_du_monde',
    title: 'Le boulanger',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui fabrique et vend le pain et les croissants ?',
    options: [
      { id: 'a', text: 'le pharmacien', isCorrect: false },
      { id: 'b', text: 'le boulanger', isCorrect: true },
      { id: 'c', text: 'le facteur', isCorrect: false },
      { id: 'd', text: 'le coiffeur', isCorrect: false },
    ],
    correctAnswer: 'le boulanger',
    explanation: 'Le boulanger prépare le pain, les croissants et les viennoiseries très tôt le matin.',
    hint: 'Sa boulangerie sent bon le pain chaud.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-015',
    subject: 'decouverte_du_monde',
    title: 'Le facteur',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui distribue le courrier et les colis dans les maisons ?',
    options: [
      { id: 'a', text: 'le jardinier', isCorrect: false },
      { id: 'b', text: 'le facteur', isCorrect: true },
      { id: 'c', text: 'le pompier', isCorrect: false },
      { id: 'd', text: 'le maçon', isCorrect: false },
    ],
    correctAnswer: 'le facteur',
    explanation: 'Le facteur (ou factrice) livre le courrier, les lettres et les colis à domicile.',
    hint: 'Il passe souvent le matin avec son vélo ou sa camionnette jaune.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-016',
    subject: 'decouverte_du_monde',
    title: 'Le jardinier',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui s\'occupe de l\'entretien des jardins et des espaces verts ?',
    options: [
      { id: 'a', text: 'le jardinier', isCorrect: true },
      { id: 'b', text: 'le boulanger', isCorrect: false },
      { id: 'c', text: 'l\'épicier', isCorrect: false },
      { id: 'd', text: 'le coiffeur', isCorrect: false },
    ],
    correctAnswer: 'le jardinier',
    explanation: 'Le jardinier taille les haies, tond la pelouse et plante des fleurs pour entretenir les jardins.',
    hint: 'Il utilise une tondeuse, un râteau et des cisailles.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-017',
    subject: 'decouverte_du_monde',
    title: 'Le cuisinier de la cantine',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui prépare les repas à la cantine de l\'école ?',
    options: [
      { id: 'a', text: 'le directeur', isCorrect: false },
      { id: 'b', text: 'la maîtresse', isCorrect: false },
      { id: 'c', text: 'le cuisinier ou la cuisinière', isCorrect: true },
      { id: 'd', text: 'le facteur', isCorrect: false },
    ],
    correctAnswer: 'le cuisinier ou la cuisinière',
    explanation: 'Le cuisinier de la cantine prépare les repas pour tous les élèves de l\'école chaque jour.',
    hint: 'C\'est grâce à lui que tu manges chaud à la cantine.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-018',
    subject: 'decouverte_du_monde',
    title: 'Un métier utile',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les métiers sont-ils importants dans la société ?',
    options: [
      { id: 'a', text: 'Pour que les adultes s\'ennuient moins.', isCorrect: false },
      { id: 'b', text: 'Pour rendre des services utiles à tout le monde.', isCorrect: true },
      { id: 'c', text: 'Pour que les enfants restent seuls à la maison.', isCorrect: false },
      { id: 'd', text: 'Ils ne sont pas vraiment importants.', isCorrect: false },
    ],
    correctAnswer: 'Pour rendre des services utiles à tout le monde.',
    explanation: 'Chaque métier a un rôle important dans la société : nourrir, soigner, enseigner, protéger, construire…',
    hint: 'Imagine ta vie sans boulanger, sans médecin, sans pompier…',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-019',
    subject: 'decouverte_du_monde',
    title: 'Le policier',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle du policier ?',
    options: [
      { id: 'a', text: 'Il vend des fruits et des légumes.', isCorrect: false },
      { id: 'b', text: 'Il fait respecter les lois et protège les habitants.', isCorrect: true },
      { id: 'c', text: 'Il répare les voitures.', isCorrect: false },
      { id: 'd', text: 'Il construit les maisons.', isCorrect: false },
    ],
    correctAnswer: 'Il fait respecter les lois et protège les habitants.',
    explanation: 'Le policier assure la sécurité des personnes et fait respecter les règles de la société.',
    hint: 'Il porte un uniforme bleu et intervient en cas de danger.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-rep-020',
    subject: 'decouverte_du_monde',
    title: 'Travailler ensemble',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans un groupe, pourquoi est-il important d\'écouter les autres ?',
    options: [
      { id: 'a', text: 'Pour faire ce qu\'on veut sans tenir compte des autres.', isCorrect: false },
      { id: 'b', text: 'Pour travailler ensemble et que chacun puisse s\'exprimer.', isCorrect: true },
      { id: 'c', text: 'Ce n\'est pas important d\'écouter les autres.', isCorrect: false },
      { id: 'd', text: 'Pour savoir qui a tort.', isCorrect: false },
    ],
    correctAnswer: 'Pour travailler ensemble et que chacun puisse s\'exprimer.',
    explanation: 'Écouter les autres permet de partager les idées et de mieux travailler ensemble. C\'est le respect mutuel.',
    hint: 'Pense au travail en groupe en classe.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
