import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCpTempsMoisExercises: DecouverteExercise[] = [

  // CP · temps · mois
  {
    id: 'ddm-cp-tem-013',
    subject: 'decouverte_du_monde',
    title: 'Mois de Noël',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis le bon mois.',
    prompt: 'En quel mois fête-t-on Noël ?',
    options: [
      { id: 'a', text: 'novembre', isCorrect: false },
      { id: 'b', text: 'décembre', isCorrect: true },
      { id: 'c', text: 'janvier', isCorrect: false },
      { id: 'd', text: 'octobre', isCorrect: false },
    ],
    correctAnswer: 'décembre',
    explanation: 'Noël se fête le 25 décembre. C\'est le dernier mois de l\'année.',
    hint: 'C\'est en hiver, tout à la fin de l\'année.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-014',
    subject: 'decouverte_du_monde',
    title: 'Mois de la rentrée',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis le bon mois.',
    prompt: 'En quel mois a lieu la rentrée scolaire en France ?',
    options: [
      { id: 'a', text: 'juillet', isCorrect: false },
      { id: 'b', text: 'août', isCorrect: false },
      { id: 'c', text: 'septembre', isCorrect: true },
      { id: 'd', text: 'octobre', isCorrect: false },
    ],
    correctAnswer: 'septembre',
    explanation: 'La rentrée scolaire a lieu en septembre, au début de l\'automne.',
    hint: 'C\'est juste après les grandes vacances d\'été.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-015',
    subject: 'decouverte_du_monde',
    title: 'Combien y a-t-il de mois ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien y a-t-il de mois dans une année ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '11', isCorrect: false },
      { id: 'c', text: '12', isCorrect: true },
      { id: 'd', text: '13', isCorrect: false },
    ],
    correctAnswer: '12',
    explanation: 'L\'année a 12 mois : janvier, février, mars, avril, mai, juin, juillet, août, septembre, octobre, novembre, décembre.',
    hint: 'Compte les mois en les nommant.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-016',
    subject: 'decouverte_du_monde',
    title: 'Premier mois de l\'année',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis le premier mois.',
    prompt: 'Quel est le premier mois de l\'année ?',
    options: [
      { id: 'a', text: 'mars', isCorrect: false },
      { id: 'b', text: 'juin', isCorrect: false },
      { id: 'c', text: 'janvier', isCorrect: true },
      { id: 'd', text: 'décembre', isCorrect: false },
    ],
    correctAnswer: 'janvier',
    explanation: 'L\'année commence le 1er janvier. On souhaite alors « Bonne Année ! ».',
    hint: 'C\'est le mois du Nouvel An.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-017',
    subject: 'decouverte_du_monde',
    title: 'Dernier mois de l\'année',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis le dernier mois.',
    prompt: 'Quel est le dernier mois de l\'année ?',
    options: [
      { id: 'a', text: 'novembre', isCorrect: false },
      { id: 'b', text: 'octobre', isCorrect: false },
      { id: 'c', text: 'décembre', isCorrect: true },
      { id: 'd', text: 'janvier', isCorrect: false },
    ],
    correctAnswer: 'décembre',
    explanation: 'Décembre est le douzième et dernier mois de l\'année. C\'est le mois de Noël.',
    hint: 'C\'est le mois de Noël et du Nouvel An.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CP · temps · fetes
  {
    id: 'ddm-cp-tem-018',
    subject: 'decouverte_du_monde',
    title: 'La fête de Pâques',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'fetes',
    format: 'qcm',
    instructions: 'Choisis la bonne saison.',
    prompt: 'En quelle saison fête-t-on Pâques ?',
    options: [
      { id: 'a', text: 'en hiver', isCorrect: false },
      { id: 'b', text: 'au printemps', isCorrect: true },
      { id: 'c', text: 'en été', isCorrect: false },
      { id: 'd', text: 'en automne', isCorrect: false },
    ],
    correctAnswer: 'au printemps',
    explanation: 'Pâques est une fête célébrée au printemps. Les enfants cherchent des œufs en chocolat dans le jardin.',
    hint: 'C\'est quand les fleurs commencent à pousser.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-019',
    subject: 'decouverte_du_monde',
    title: 'Halloween',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'fetes',
    format: 'qcm',
    instructions: 'Choisis le bon mois.',
    prompt: 'En quel mois fête-t-on Halloween ?',
    options: [
      { id: 'a', text: 'août', isCorrect: false },
      { id: 'b', text: 'septembre', isCorrect: false },
      { id: 'c', text: 'octobre', isCorrect: true },
      { id: 'd', text: 'novembre', isCorrect: false },
    ],
    correctAnswer: 'octobre',
    explanation: 'Halloween se fête le 31 octobre. Les enfants se déguisent en fantômes et en sorcières.',
    hint: 'C\'est la veille de la Toussaint.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-020',
    subject: 'decouverte_du_monde',
    title: 'Les grandes vacances',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'fetes',
    format: 'qcm',
    instructions: 'Choisis la bonne saison.',
    prompt: 'En quelle saison ont lieu les grandes vacances scolaires ?',
    options: [
      { id: 'a', text: 'au printemps', isCorrect: false },
      { id: 'b', text: 'en automne', isCorrect: false },
      { id: 'c', text: 'en été', isCorrect: true },
      { id: 'd', text: 'en hiver', isCorrect: false },
    ],
    correctAnswer: 'en été',
    explanation: 'Les grandes vacances ont lieu en été, en juillet et août. C\'est la plus longue période de vacances scolaires.',
    hint: 'C\'est la plus longue période de vacances.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-021',
    subject: 'decouverte_du_monde',
    title: 'Vacances de Noël',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'fetes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les vacances de Noël ont lieu en quelle saison ?',
    options: [
      { id: 'a', text: 'en automne', isCorrect: false },
      { id: 'b', text: 'en été', isCorrect: false },
      { id: 'c', text: 'en hiver', isCorrect: true },
      { id: 'd', text: 'au printemps', isCorrect: false },
    ],
    correctAnswer: 'en hiver',
    explanation: 'Les vacances de Noël (fin décembre-début janvier) ont lieu en hiver.',
    hint: 'C\'est quand il fait froid et qu\'il peut neiger.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CP · temps · calendrier
  {
    id: 'ddm-cp-tem-022',
    subject: 'decouverte_du_monde',
    title: 'Lire le calendrier',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert un calendrier ?',
    options: [
      { id: 'a', text: 'À dessiner', isCorrect: false },
      { id: 'b', text: 'À connaître les jours, les semaines et les mois de l\'année', isCorrect: true },
      { id: 'c', text: 'À peser les aliments', isCorrect: false },
      { id: 'd', text: 'À mesurer la température', isCorrect: false },
    ],
    correctAnswer: 'À connaître les jours, les semaines et les mois de l\'année',
    explanation: 'Un calendrier montre tous les jours de l\'année, organisés en semaines et en mois.',
    hint: 'C\'est ce qu\'on regarde pour savoir quelle date on est.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-023',
    subject: 'decouverte_du_monde',
    title: 'Jours dans un mois',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En général, combien y a-t-il de jours dans un mois ?',
    options: [
      { id: 'a', text: 'environ 7 jours', isCorrect: false },
      { id: 'b', text: 'environ 15 jours', isCorrect: false },
      { id: 'c', text: 'environ 30 jours', isCorrect: true },
      { id: 'd', text: 'environ 50 jours', isCorrect: false },
    ],
    correctAnswer: 'environ 30 jours',
    explanation: 'La plupart des mois ont 30 ou 31 jours. Février en a 28 (ou 29 les années bissextiles).',
    hint: 'Un peu moins d\'un mois = 4 semaines.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-024',
    subject: 'decouverte_du_monde',
    title: 'Jours dans une semaine',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien y a-t-il de semaines dans un an environ ?',
    options: [
      { id: 'a', text: 'environ 12', isCorrect: false },
      { id: 'b', text: 'environ 52', isCorrect: true },
      { id: 'c', text: 'environ 100', isCorrect: false },
      { id: 'd', text: 'environ 365', isCorrect: false },
    ],
    correctAnswer: 'environ 52',
    explanation: 'Il y a environ 52 semaines dans une année (365 jours ÷ 7 jours = 52 semaines).',
    hint: 'Une année a 365 jours. Chaque semaine a 7 jours.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-025',
    subject: 'decouverte_du_monde',
    title: 'Mois de la Toussaint',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis le bon mois.',
    prompt: 'La Toussaint (1er novembre) a lieu en quel mois ?',
    options: [
      { id: 'a', text: 'octobre', isCorrect: false },
      { id: 'b', text: 'novembre', isCorrect: true },
      { id: 'c', text: 'décembre', isCorrect: false },
      { id: 'd', text: 'septembre', isCorrect: false },
    ],
    correctAnswer: 'novembre',
    explanation: 'La Toussaint est célébrée le 1er novembre. C\'est une fête qui honore les défunts.',
    hint: 'C\'est le mois qui suit octobre.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-026',
    subject: 'decouverte_du_monde',
    title: 'Ordre des mois (début)',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis le bon mois.',
    prompt: 'Quel mois vient après janvier ?',
    options: [
      { id: 'a', text: 'mars', isCorrect: false },
      { id: 'b', text: 'décembre', isCorrect: false },
      { id: 'c', text: 'février', isCorrect: true },
      { id: 'd', text: 'juin', isCorrect: false },
    ],
    correctAnswer: 'février',
    explanation: 'Après janvier vient février. Janvier (1) → Février (2) → Mars (3)…',
    hint: 'C\'est le mois le plus court de l\'année.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-027',
    subject: 'decouverte_du_monde',
    title: 'Mois d\'été',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis un mois d\'été.',
    prompt: 'Lequel de ces mois est un mois d\'été ?',
    options: [
      { id: 'a', text: 'décembre', isCorrect: false },
      { id: 'b', text: 'mars', isCorrect: false },
      { id: 'c', text: 'juillet', isCorrect: true },
      { id: 'd', text: 'novembre', isCorrect: false },
    ],
    correctAnswer: 'juillet',
    explanation: 'Juillet est un mois d\'été. Les mois d\'été en France sont juin, juillet et août.',
    hint: 'C\'est le mois des grandes vacances au soleil.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-028',
    subject: 'decouverte_du_monde',
    title: 'Mois d\'hiver',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis un mois d\'hiver.',
    prompt: 'Lequel de ces mois est un mois d\'hiver ?',
    options: [
      { id: 'a', text: 'août', isCorrect: false },
      { id: 'b', text: 'mai', isCorrect: false },
      { id: 'c', text: 'janvier', isCorrect: true },
      { id: 'd', text: 'septembre', isCorrect: false },
    ],
    correctAnswer: 'janvier',
    explanation: 'Janvier est un mois d\'hiver. Les mois d\'hiver sont décembre, janvier et février.',
    hint: 'C\'est quand il fait froid et qu\'il peut neiger.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-029',
    subject: 'decouverte_du_monde',
    title: 'Mois de printemps',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis un mois de printemps.',
    prompt: 'Lequel de ces mois est un mois de printemps ?',
    options: [
      { id: 'a', text: 'décembre', isCorrect: false },
      { id: 'b', text: 'avril', isCorrect: true },
      { id: 'c', text: 'août', isCorrect: false },
      { id: 'd', text: 'octobre', isCorrect: false },
    ],
    correctAnswer: 'avril',
    explanation: 'Avril est un mois de printemps. Les mois de printemps sont mars, avril et mai.',
    hint: 'C\'est le mois du poisson d\'avril !',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-030',
    subject: 'decouverte_du_monde',
    title: 'Mois d\'automne',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'mois',
    format: 'qcm',
    instructions: 'Choisis un mois d\'automne.',
    prompt: 'Lequel de ces mois est un mois d\'automne ?',
    options: [
      { id: 'a', text: 'juillet', isCorrect: false },
      { id: 'b', text: 'mars', isCorrect: false },
      { id: 'c', text: 'octobre', isCorrect: true },
      { id: 'd', text: 'janvier', isCorrect: false },
    ],
    correctAnswer: 'octobre',
    explanation: 'Octobre est un mois d\'automne. Les mois d\'automne sont septembre, octobre et novembre.',
    hint: 'C\'est quand les feuilles tombent des arbres.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-031',
    subject: 'decouverte_du_monde',
    title: 'Saisons de l\'année (ordre)',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis le bon ordre.',
    prompt: 'Quel est l\'ordre des saisons en commençant par le printemps ?',
    options: [
      { id: 'a', text: 'printemps → hiver → été → automne', isCorrect: false },
      { id: 'b', text: 'printemps → été → automne → hiver', isCorrect: true },
      { id: 'c', text: 'printemps → automne → hiver → été', isCorrect: false },
      { id: 'd', text: 'printemps → été → hiver → automne', isCorrect: false },
    ],
    correctAnswer: 'printemps → été → automne → hiver',
    explanation: 'L\'ordre des saisons est toujours : printemps → été → automne → hiver, puis ça recommence.',
    hint: 'Pense aux changements de la nature au fil de l\'année.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cp-tem-032',
    subject: 'decouverte_du_monde',
    title: 'Saison après l\'hiver',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne saison.',
    prompt: 'Quelle saison vient juste après l\'hiver ?',
    options: [
      { id: 'a', text: 'l\'automne', isCorrect: false },
      { id: 'b', text: 'l\'été', isCorrect: false },
      { id: 'c', text: 'le printemps', isCorrect: true },
      { id: 'd', text: 'un autre hiver', isCorrect: false },
    ],
    correctAnswer: 'le printemps',
    explanation: 'Après l\'hiver vient le printemps : il fait plus doux, les oiseaux reviennent et les fleurs poussent.',
    hint: 'C\'est la saison où tout revient à la vie.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
