import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCe2GeoPaysagesExercises: HgExercise[] = [

  {
    id: 'hg-ce2-geo-pay-001',
    subject: 'histoire_geo',
    title: "Paysage urbain",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un paysage avec de grands immeubles, des rues animées, des magasins et beaucoup de gens est un paysage…",
    options: [
      { id: 'a', text: "de montagne", isCorrect: false },
      { id: 'b', text: "urbain (de ville)", isCorrect: true },
      { id: 'c', text: "littoral", isCorrect: false },
      { id: 'd', text: "rural", isCorrect: false },
    ],
    correctAnswer: "urbain (de ville)",
    explanation: "Un paysage urbain est caractérisé par des bâtiments élevés, des routes nombreuses, des commerces et une forte densité de population. Paris, Lyon, Marseille sont des paysages urbains.",
    hint: "Urbain vient du latin « urbs » = ville.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-002',
    subject: 'histoire_geo',
    title: "Paysage rural",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un paysage avec des champs, des fermes, quelques maisons et peu d'habitants est un paysage…",
    options: [
      { id: 'a', text: "industriel", isCorrect: false },
      { id: 'b', text: "rural (de campagne)", isCorrect: true },
      { id: 'c', text: "urbain", isCorrect: false },
      { id: 'd', text: "polaire", isCorrect: false },
    ],
    correctAnswer: "rural (de campagne)",
    explanation: "Un paysage rural est dominé par l'agriculture, les forêts et les espaces verts. Les villages et les fermes y sont dispersés. La densité de population y est faible.",
    hint: "Rural = campagne, agriculture, peu d'habitants.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-003',
    subject: 'histoire_geo',
    title: "Paysage de montagne",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le signe qui caractérise le mieux un paysage de montagne ?",
    options: [
      { id: 'a', text: "Des plages de sable et des vagues", isCorrect: false },
      { id: 'b', text: "Des sommets enneigés et des pentes raides", isCorrect: true },
      { id: 'c', text: "Des champs à perte de vue", isCorrect: false },
      { id: 'd', text: "Des usines et des entrepôts", isCorrect: false },
    ],
    correctAnswer: "Des sommets enneigés et des pentes raides",
    explanation: "Un paysage de montagne se caractérise par une altitude élevée, des pentes raides, souvent de la neige en hiver. On y pratique la randonnée, le ski, l'alpinisme.",
    hint: "Les Alpes, les Pyrénées → neige, altitude, ski.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-004',
    subject: 'histoire_geo',
    title: "Paysage littoral",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un paysage littoral est un paysage situé…",
    options: [
      { id: 'a', text: "en haute montagne", isCorrect: false },
      { id: 'b', text: "au bord de la mer ou de l'océan", isCorrect: true },
      { id: 'c', text: "au centre d'une grande ville", isCorrect: false },
      { id: 'd', text: "dans une grande forêt", isCorrect: false },
    ],
    correctAnswer: "au bord de la mer ou de l'océan",
    explanation: "Un paysage littoral est en bord de mer. On y trouve des plages, des falaises, des ports et des stations balnéaires. La Bretagne, la Côte d'Azur sont des littoraux célèbres.",
    hint: "Littoral = côte = bord de mer.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-005',
    subject: 'histoire_geo',
    title: "Paysage de plaine",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Dans un paysage de plaine, l'horizon est…",
    options: [
      { id: 'a', text: "caché par des montagnes", isCorrect: false },
      { id: 'b', text: "loin et bien visible car le terrain est plat", isCorrect: true },
      { id: 'c', text: "caché par des immeubles", isCorrect: false },
      { id: 'd', text: "caché par des forêts épaisses", isCorrect: false },
    ],
    correctAnswer: "loin et bien visible car le terrain est plat",
    explanation: "Une plaine est une région au relief peu marqué. On peut voir loin car rien ne bloque la vue. La Beauce (au sud de Paris) est une grande plaine céréalière.",
    hint: "Plaine = terrain plat, horizon dégagé.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-006',
    subject: 'histoire_geo',
    title: "Les activités en montagne",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle activité est typique des paysages de montagne en hiver ?",
    options: [
      { id: 'a', text: "La pêche en mer", isCorrect: false },
      { id: 'b', text: "Le ski et les sports de glisse", isCorrect: true },
      { id: 'c', text: "La culture du blé", isCorrect: false },
      { id: 'd', text: "La navigation fluviale", isCorrect: false },
    ],
    correctAnswer: "Le ski et les sports de glisse",
    explanation: "Les paysages de montagne enneigée accueillent des stations de ski. Les Alpes et les Pyrénées sont des destinations touristiques importantes pour les sports d'hiver.",
    hint: "Neige + pentes + montagne = activité hivernale.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-007',
    subject: 'histoire_geo',
    title: "Paysage méditerranéen",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le paysage méditerranéen (comme en Provence) se reconnaît à ses…",
    options: [
      { id: 'a', text: "bocages et pommiers", isCorrect: false },
      { id: 'b', text: "oliviers, cyprès, garrigue et soleil intense", isCorrect: true },
      { id: 'c', text: "glaciers et alpages", isCorrect: false },
      { id: 'd', text: "marais et canaux", isCorrect: false },
    ],
    correctAnswer: "oliviers, cyprès, garrigue et soleil intense",
    explanation: "Le paysage méditerranéen se caractérise par un climat chaud et sec en été, des oliviers, des lavandes, des cyprès et une végétation basse appelée garrigue ou maquis.",
    hint: "Provence, Languedoc, Côte d'Azur → oliviers, soleil, garrigue.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-008',
    subject: 'histoire_geo',
    title: "Paysage normand",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le paysage normand est connu pour ses champs entourés de haies, ses vaches et ses…",
    options: [
      { id: 'a', text: "vignes", isCorrect: false },
      { id: 'b', text: "pommiers et vergers (paysage de bocage)", isCorrect: true },
      { id: 'c', text: "champs de lavande", isCorrect: false },
      { id: 'd', text: "palmiers", isCorrect: false },
    ],
    correctAnswer: "pommiers et vergers (paysage de bocage)",
    explanation: "La Normandie est célèbre pour ses bocages (champs fermés par des haies), ses vaches laitières, ses pommiers pour le cidre et le calvados, et ses falaises de craie.",
    hint: "Normandie = vaches, pommiers, cidre, bocage.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-009',
    subject: 'histoire_geo',
    title: "Activités à la mer",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelles sont les deux activités principales dans un paysage littoral ?",
    options: [
      { id: 'a', text: "L'élevage de bovins et la culture du maïs", isCorrect: false },
      { id: 'b', text: "La pêche et le tourisme balnéaire", isCorrect: true },
      { id: 'c', text: "L'exploitation minière et l'industrie lourde", isCorrect: false },
      { id: 'd', text: "La sylviculture et la chasse", isCorrect: false },
    ],
    correctAnswer: "La pêche et le tourisme balnéaire",
    explanation: "Les zones littorales accueillent la pêche (ports de pêche, filets) et le tourisme (plages, voile, plongée). Certains littoraux accueillent aussi des ports commerciaux.",
    hint: "Mer = pêcheurs + vacanciers.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-010',
    subject: 'histoire_geo',
    title: "Activités à la campagne",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'activité principale dans un paysage rural de plaine est…",
    options: [
      { id: 'a', text: "Le tourisme balnéaire", isCorrect: false },
      { id: 'b', text: "L'agriculture (cultures céréalières, élevage)", isCorrect: true },
      { id: 'c', text: "La finance et les services numériques", isCorrect: false },
      { id: 'd', text: "La pêche en haute mer", isCorrect: false },
    ],
    correctAnswer: "L'agriculture (cultures céréalières, élevage)",
    explanation: "La campagne est le domaine de l'agriculture : on y cultive du blé, du maïs, des betteraves, et on y élève des vaches, des moutons, des poulets.",
    hint: "Champs + fermes = agriculture.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-011',
    subject: 'histoire_geo',
    title: "L'homme transforme le paysage",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quand les hommes construisent de nouvelles maisons et routes là où il y avait des champs, on appelle cela…",
    options: [
      { id: 'a', text: "la déforestation", isCorrect: false },
      { id: 'b', text: "l'urbanisation", isCorrect: true },
      { id: 'c', text: "la reforestation", isCorrect: false },
      { id: 'd', text: "la désertification", isCorrect: false },
    ],
    correctAnswer: "l'urbanisation",
    explanation: "L'urbanisation désigne la transformation de terres agricoles ou naturelles en zones construites (lotissements, zones commerciales, routes). Cela fait grandir les villes.",
    hint: "Urbain = ville → urbanisation = la ville qui s'étend.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-012',
    subject: 'histoire_geo',
    title: "Les paysages changent",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En quelle saison un paysage de montagne alpine ressemble-t-il le plus à une station de ski ?",
    options: [
      { id: 'a', text: "En été", isCorrect: false },
      { id: 'b', text: "En hiver", isCorrect: true },
      { id: 'c', text: "Au printemps", isCorrect: false },
      { id: 'd', text: "En automne", isCorrect: false },
    ],
    correctAnswer: "En hiver",
    explanation: "En hiver, les sommets alpins sont couverts de neige, les remontées mécaniques sont en marche et les stations de ski sont animées. En été, le même paysage est vert et accueille randonneurs et VTT.",
    hint: "Ski → neige → hiver.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-013',
    subject: 'histoire_geo',
    title: "Paysage forestier",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La forêt des Landes, dans le sud-ouest de la France, est principalement composée de…",
    options: [
      { id: 'a', text: "Palmiers", isCorrect: false },
      { id: 'b', text: "Pins maritimes", isCorrect: true },
      { id: 'c', text: "Chênes et hêtres", isCorrect: false },
      { id: 'd', text: "Sapins enneigés", isCorrect: false },
    ],
    correctAnswer: "Pins maritimes",
    explanation: "La forêt des Landes (Gironde, Landes) est l'une des plus grandes forêts artificielles d'Europe, plantée au XIXe siècle de pins maritimes pour assainir les marécages.",
    hint: "Les Landes → forêt de pins → littoral atlantique.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-014',
    subject: 'histoire_geo',
    title: "Milieu urbain vs rural",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle affirmation est VRAIE concernant la différence entre le milieu urbain et le milieu rural ?",
    options: [
      { id: 'a', text: "Il y a plus d'habitants au km² à la campagne qu'en ville", isCorrect: false },
      { id: 'b', text: "Il y a plus d'habitants au km² en ville qu'à la campagne", isCorrect: true },
      { id: 'c', text: "Les transports en commun sont plus développés à la campagne", isCorrect: false },
      { id: 'd', text: "Les services (hôpitaux, écoles) sont plus nombreux à la campagne", isCorrect: false },
    ],
    correctAnswer: "Il y a plus d'habitants au km² en ville qu'à la campagne",
    explanation: "La densité de population (nb d'habitants par km²) est beaucoup plus élevée en ville (ex: Paris = 20 000 hab/km²) qu'à la campagne. Les services sont aussi plus concentrés en ville.",
    hint: "Densité = nombre d'habitants dans un espace donné. Ville = très dense.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-pay-015',
    subject: 'histoire_geo',
    title: "Reconnaître un paysage",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Sur une photo, on voit une falaise blanche au bord de la mer avec une plage au pied. Quel type de paysage est-ce ?",
    options: [
      { id: 'a', text: "Paysage de montagne", isCorrect: false },
      { id: 'b', text: "Paysage littoral", isCorrect: true },
      { id: 'c', text: "Paysage de plaine", isCorrect: false },
      { id: 'd', text: "Paysage urbain", isCorrect: false },
    ],
    correctAnswer: "Paysage littoral",
    explanation: "Une falaise en bord de mer avec une plage est typique d'un paysage littoral. Les falaises normandes sont un exemple célèbre (falaises d'Étretat).",
    hint: "Mer + falaise + plage → littoral.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
