import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCe2GeoCarteFranceExercises: HgExercise[] = [

  {
    id: 'hg-ce2-geo-fra-001',
    subject: 'histoire_geo',
    title: "La forme de la France",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France métropolitaine a une forme particulière qui lui vaut un surnom. Quel est ce surnom ?",
    options: [
      { id: 'a', text: "Le triangle", isCorrect: false },
      { id: 'b', text: "L'hexagone", isCorrect: true },
      { id: 'c', text: "Le carré", isCorrect: false },
      { id: 'd', text: "L'étoile", isCorrect: false },
    ],
    correctAnswer: "L'hexagone",
    explanation: "La France est souvent appelée « l'Hexagone » car sa forme ressemble à un hexagone (figure à 6 côtés). Sur une carte, on reconnaît cette forme caractéristique.",
    hint: "Un hexagone a 6 côtés — comme les frontières de la France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-002',
    subject: 'histoire_geo',
    title: "La capitale de la France",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale de la France, où se trouvent l'Élysée, l'Assemblée nationale et le Louvre ?",
    options: [
      { id: 'a', text: "Lyon", isCorrect: false },
      { id: 'b', text: "Paris", isCorrect: true },
      { id: 'c', text: "Marseille", isCorrect: false },
      { id: 'd', text: "Toulouse", isCorrect: false },
    ],
    correctAnswer: "Paris",
    explanation: "Paris est la capitale de la France. C'est la ville la plus peuplée du pays, avec la tour Eiffel, le Louvre, Notre-Dame et les grandes institutions politiques.",
    hint: "La tour Eiffel est dans cette ville.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-003',
    subject: 'histoire_geo',
    title: "Les pays voisins de la France",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France partage des frontières terrestres avec plusieurs pays. Lequel n'est PAS voisin de la France ?",
    options: [
      { id: 'a', text: "L'Espagne", isCorrect: false },
      { id: 'b', text: "La Pologne", isCorrect: true },
      { id: 'c', text: "L'Allemagne", isCorrect: false },
      { id: 'd', text: "L'Italie", isCorrect: false },
    ],
    correctAnswer: "La Pologne",
    explanation: "La France a 8 voisins terrestres : Belgique, Luxembourg, Allemagne, Suisse, Italie, Monaco, Espagne et Andorre. La Pologne est bien trop à l'est.",
    hint: "La Pologne est à l'est de l'Allemagne, loin de la France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-004',
    subject: 'histoire_geo',
    title: "La Loire",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le plus long fleuve de France ?",
    options: [
      { id: 'a', text: "La Seine", isCorrect: false },
      { id: 'b', text: "La Loire", isCorrect: true },
      { id: 'c', text: "Le Rhône", isCorrect: false },
      { id: 'd', text: "La Garonne", isCorrect: false },
    ],
    correctAnswer: "La Loire",
    explanation: "La Loire (1 013 km) est le plus long fleuve de France. Elle traverse notamment Orléans et Nantes, et se jette dans l'Atlantique à Saint-Nazaire.",
    hint: "Ce fleuve passe par Orléans, la ville de Jeanne d'Arc.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-005',
    subject: 'histoire_geo',
    title: "La Seine",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Seine est le fleuve qui traverse Paris. Dans quel espace maritime se jette-t-elle ?",
    options: [
      { id: 'a', text: "La mer Méditerranée", isCorrect: false },
      { id: 'b', text: "La Manche", isCorrect: true },
      { id: 'c', text: "L'océan Atlantique", isCorrect: false },
      { id: 'd', text: "La mer du Nord", isCorrect: false },
    ],
    correctAnswer: "La Manche",
    explanation: "La Seine traverse Paris et se jette dans la Manche à l'estuaire de la Seine (près de Rouen et du Havre).",
    hint: "Le Havre, grand port normand, est à l'embouchure de la Seine.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-006',
    subject: 'histoire_geo',
    title: "Le Rhône",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Rhône traverse Lyon puis se dirige vers le sud. Dans quelle mer se jette-t-il ?",
    options: [
      { id: 'a', text: "L'océan Atlantique", isCorrect: false },
      { id: 'b', text: "La mer Méditerranée", isCorrect: true },
      { id: 'c', text: "La Manche", isCorrect: false },
      { id: 'd', text: "La mer du Nord", isCorrect: false },
    ],
    correctAnswer: "La mer Méditerranée",
    explanation: "Le Rhône naît en Suisse, traverse le lac Léman et Lyon, puis se jette dans la Méditerranée dans le delta de Camargue (Bouches-du-Rhône).",
    hint: "Le Rhône coule du nord au sud et atteint la mer au sud de la France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-007',
    subject: 'histoire_geo',
    title: "Les Alpes",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le point culminant de la France, situé dans les Alpes à la frontière franco-italienne ?",
    options: [
      { id: 'a', text: "Le Puy de Dôme", isCorrect: false },
      { id: 'b', text: "Le Mont Blanc (4 810 m)", isCorrect: true },
      { id: 'c', text: "Le Mont Ventoux", isCorrect: false },
      { id: 'd', text: "Le Vignemale", isCorrect: false },
    ],
    correctAnswer: "Le Mont Blanc (4 810 m)",
    explanation: "Le Mont Blanc (4 808-4 810 m) est le plus haut sommet des Alpes et d'Europe occidentale. Il est situé à la frontière entre la France, l'Italie et la Suisse.",
    hint: "« Blanc » car il est recouvert de neige toute l'année.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-008',
    subject: 'histoire_geo',
    title: "Les Pyrénées",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Pyrénées sont une chaîne de montagnes qui sépare la France de l'Espagne. Dans quelle partie de la France les trouve-t-on ?",
    options: [
      { id: 'a', text: "Au nord-est", isCorrect: false },
      { id: 'b', text: "Au sud-ouest", isCorrect: true },
      { id: 'c', text: "À l'est", isCorrect: false },
      { id: 'd', text: "Au nord", isCorrect: false },
    ],
    correctAnswer: "Au sud-ouest",
    explanation: "Les Pyrénées s'étendent d'est en ouest au sud de la France, entre l'Atlantique (côté basque) et la Méditerranée (côté catalan). Elles forment la frontière avec l'Espagne.",
    hint: "L'Espagne est au sud de la France, donc les Pyrénées sont au sud.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-009',
    subject: 'histoire_geo',
    title: "La mer Méditerranée",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La mer Méditerranée borde la France au…",
    options: [
      { id: 'a', text: "nord", isCorrect: false },
      { id: 'b', text: "sud", isCorrect: true },
      { id: 'c', text: "ouest", isCorrect: false },
      { id: 'd', text: "est", isCorrect: false },
    ],
    correctAnswer: "sud",
    explanation: "La mer Méditerranée borde la France au sud, de la frontière espagnole (Pyrénées-Orientales) à la frontière italienne. Marseille, Nice, Montpellier sont sur ce littoral.",
    hint: "Marseille, Nice, Cannes → bord de la mer au sud.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-010',
    subject: 'histoire_geo',
    title: "La Manche",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Manche est un bras de mer qui sépare la France du Royaume-Uni. Dans quelle partie de la France la trouve-t-on ?",
    options: [
      { id: 'a', text: "Au sud", isCorrect: false },
      { id: 'b', text: "Au nord", isCorrect: true },
      { id: 'c', text: "À l'est", isCorrect: false },
      { id: 'd', text: "À l'ouest", isCorrect: false },
    ],
    correctAnswer: "Au nord",
    explanation: "La Manche est au nord de la France, entre Normandie, Picardie et les côtes anglaises. Le port de Calais est le plus proche de l'Angleterre (33 km).",
    hint: "Calais, Dunkerque, le débarquement de 1944 → nord de la France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-011',
    subject: 'histoire_geo',
    title: "Grandes villes françaises",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la 2e ville de France par le nombre d'habitants ?",
    options: [
      { id: 'a', text: "Lyon", isCorrect: false },
      { id: 'b', text: "Marseille", isCorrect: true },
      { id: 'c', text: "Toulouse", isCorrect: false },
      { id: 'd', text: "Nice", isCorrect: false },
    ],
    correctAnswer: "Marseille",
    explanation: "Après Paris, Marseille est la 2e ville de France. C'est un grand port méditerranéen dans les Bouches-du-Rhône. Lyon est la 3e ville.",
    hint: "Paris, puis Marseille (bord de mer au sud), puis Lyon (confluence Rhône+Saône).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-012',
    subject: 'histoire_geo',
    title: "Le Massif Central",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Massif Central est un massif montagneux situé dans le centre de la France. Il est connu pour ses…",
    options: [
      { id: 'a', text: "plages et stations balnéaires", isCorrect: false },
      { id: 'b', text: "volcans éteints (comme le Puy de Dôme)", isCorrect: true },
      { id: 'c', text: "fjords et glaciers", isCorrect: false },
      { id: 'd', text: "déserts de sable", isCorrect: false },
    ],
    correctAnswer: "volcans éteints (comme le Puy de Dôme)",
    explanation: "Le Massif Central (Auvergne) est une région de volcans éteints depuis des millions d'années. Le Puy de Dôme (1 465 m) est le plus célèbre.",
    hint: "Auvergne, Puy de Dôme, volcans → Massif Central.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-013',
    subject: 'histoire_geo',
    title: "Les DOM",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France possède des territoires hors d'Europe appelés DROM. Lequel est situé dans l'océan Indien ?",
    options: [
      { id: 'a', text: "La Martinique", isCorrect: false },
      { id: 'b', text: "La Réunion", isCorrect: true },
      { id: 'c', text: "La Guadeloupe", isCorrect: false },
      { id: 'd', text: "La Guyane", isCorrect: false },
    ],
    correctAnswer: "La Réunion",
    explanation: "La Réunion est un département français d'outre-mer situé dans l'océan Indien, près de Madagascar. La Martinique et la Guadeloupe sont dans les Caraïbes, la Guyane en Amérique du Sud.",
    hint: "La Réunion → océan Indien, à l'est de Madagascar.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-014',
    subject: 'histoire_geo',
    title: "La Garonne",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Garonne traverse Toulouse et Bordeaux. Dans quel espace maritime se jette-t-elle ?",
    options: [
      { id: 'a', text: "La mer Méditerranée", isCorrect: false },
      { id: 'b', text: "L'océan Atlantique (via l'estuaire de la Gironde)", isCorrect: true },
      { id: 'c', text: "La mer du Nord", isCorrect: false },
      { id: 'd', text: "La Manche", isCorrect: false },
    ],
    correctAnswer: "L'océan Atlantique (via l'estuaire de la Gironde)",
    explanation: "La Garonne traverse Toulouse et Bordeaux avant de se jeter dans l'Atlantique via l'estuaire de la Gironde. Cet estuaire est l'un des plus larges d'Europe.",
    hint: "Bordeaux est sur la Garonne, et Bordeaux est proche de l'Atlantique.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-fra-015',
    subject: 'histoire_geo',
    title: "La France et ses régions",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'carte_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Depuis 2016, la France métropolitaine est divisée en combien de régions ?",
    options: [
      { id: 'a', text: "22", isCorrect: false },
      { id: 'b', text: "13", isCorrect: true },
      { id: 'c', text: "96", isCorrect: false },
      { id: 'd', text: "5", isCorrect: false },
    ],
    correctAnswer: "13",
    explanation: "Depuis la réforme territoriale de 2016, la France métropolitaine est divisée en 13 régions (contre 22 auparavant). Les 5 régions d'outre-mer s'ajoutent pour un total de 18 régions.",
    hint: "La réforme de 2016 a fusionné certaines régions : de 22 → 13.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
