import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCe2GeoContinentsOceansExercises: HgExercise[] = [

  {
    id: 'hg-ce2-geo-cto-001',
    subject: 'histoire_geo',
    title: "Combien y a-t-il de continents ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Combien y a-t-il de continents sur la Terre ?",
    options: [
      { id: 'a', text: "4", isCorrect: false },
      { id: 'b', text: "6", isCorrect: false },
      { id: 'c', text: "5", isCorrect: true },
      { id: 'd', text: "7", isCorrect: false },
    ],
    correctAnswer: "5",
    explanation: "On enseigne généralement 5 continents en France : Europe, Afrique, Amériques, Asie, Océanie (et parfois l'Antarctique en plus). Certains pays en comptent 6 ou 7 selon les découpages.",
    hint: "Les 5 continents sont représentés par les 5 anneaux olympiques.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-002',
    subject: 'histoire_geo',
    title: "Sur quel continent est la France ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Sur quel continent se trouve la France métropolitaine ?",
    options: [
      { id: 'a', text: "L'Afrique", isCorrect: false },
      { id: 'b', text: "L'Europe", isCorrect: true },
      { id: 'c', text: "L'Asie", isCorrect: false },
      { id: 'd', text: "L'Amérique", isCorrect: false },
    ],
    correctAnswer: "L'Europe",
    explanation: "La France métropolitaine est située en Europe occidentale. Elle fait partie de l'Union européenne. Elle a aussi des territoires outre-mer sur d'autres continents (Guyane en Amérique du Sud, Réunion en Afrique…).",
    hint: "La France est en Europe de l'Ouest.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-003',
    subject: 'histoire_geo',
    title: "Le plus grand continent",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le plus grand continent du monde ?",
    options: [
      { id: 'a', text: "L'Afrique", isCorrect: false },
      { id: 'b', text: "L'Asie", isCorrect: true },
      { id: 'c', text: "L'Amérique", isCorrect: false },
      { id: 'd', text: "L'Europe", isCorrect: false },
    ],
    correctAnswer: "L'Asie",
    explanation: "L'Asie est le plus grand continent : environ 44 millions de km². C'est aussi le plus peuplé avec environ 4,7 milliards d'habitants. La Chine et l'Inde sont les pays les plus peuplés du monde.",
    hint: "L'Asie est le plus grand ET le plus peuplé des continents.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-004',
    subject: 'histoire_geo',
    title: "Combien d'océans ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Combien y a-t-il d'océans sur la Terre ?",
    options: [
      { id: 'a', text: "3", isCorrect: false },
      { id: 'b', text: "5", isCorrect: true },
      { id: 'c', text: "7", isCorrect: false },
      { id: 'd', text: "10", isCorrect: false },
    ],
    correctAnswer: "5",
    explanation: "On compte 5 océans : l'Atlantique, le Pacifique, l'Indien, l'Arctique et l'Antarctique (ou Austral). Le Pacifique est le plus grand.",
    hint: "5 océans : Atlantique, Pacifique, Indien, Arctique, Antarctique.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-005',
    subject: 'histoire_geo',
    title: "L'océan le plus grand",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le plus grand océan du monde ?",
    options: [
      { id: 'a', text: "L'océan Atlantique", isCorrect: false },
      { id: 'b', text: "L'océan Pacifique", isCorrect: true },
      { id: 'c', text: "L'océan Indien", isCorrect: false },
      { id: 'd', text: "La mer Méditerranée", isCorrect: false },
    ],
    correctAnswer: "L'océan Pacifique",
    explanation: "L'océan Pacifique est le plus grand : il couvre environ un tiers de la surface de la Terre. Il est bordé par l'Asie, l'Océanie et les Amériques.",
    hint: "Pacifique = le plus grand océan = un tiers de la surface terrestre.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-006',
    subject: 'histoire_geo',
    title: "L'Afrique",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Afrique est le 2e plus grand continent. Quel désert très célèbre se trouve au nord de l'Afrique ?",
    options: [
      { id: 'a', text: "Le désert de Gobi", isCorrect: false },
      { id: 'b', text: "Le Sahara", isCorrect: true },
      { id: 'c', text: "L'Atacama", isCorrect: false },
      { id: 'd', text: "Le Grand Désert de Victoria", isCorrect: false },
    ],
    correctAnswer: "Le Sahara",
    explanation: "Le Sahara est le plus grand désert chaud du monde. Il couvre environ 9 millions de km² dans le nord de l'Afrique. Le désert de Gobi est en Asie.",
    hint: "Sahara = grand désert chaud au nord de l'Afrique.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-007',
    subject: 'histoire_geo',
    title: "L'Amérique",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Amérique est divisée en deux grandes parties. Lesquelles ?",
    options: [
      { id: 'a', text: "L'Amérique du Nord et l'Amérique du Pacifique", isCorrect: false },
      { id: 'b', text: "L'Amérique du Nord et l'Amérique du Sud", isCorrect: true },
      { id: 'c', text: "L'Amérique de l'Est et l'Amérique de l'Ouest", isCorrect: false },
      { id: 'd', text: "L'Amérique chaude et l'Amérique froide", isCorrect: false },
    ],
    correctAnswer: "L'Amérique du Nord et l'Amérique du Sud",
    explanation: "L'Amérique comprend l'Amérique du Nord (États-Unis, Canada, Mexique) et l'Amérique du Sud (Brésil, Argentine…), reliées par l'Amérique centrale.",
    hint: "Amérique du Nord = USA/Canada. Amérique du Sud = Brésil/Argentine.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-008',
    subject: 'histoire_geo',
    title: "L'Antarctique",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Où se trouve le pôle Sud ?",
    options: [
      { id: 'a', text: "En Australie", isCorrect: false },
      { id: 'b', text: "En Antarctique", isCorrect: true },
      { id: 'c', text: "En Afrique du Sud", isCorrect: false },
      { id: 'd', text: "Dans l'océan Atlantique", isCorrect: false },
    ],
    correctAnswer: "En Antarctique",
    explanation: "Le pôle Sud se trouve en Antarctique, le continent le plus au sud. Il est recouvert d'une épaisse calotte glaciaire. Aucun être humain n'y vit en permanence.",
    hint: "Pôle Sud = Antarctique = continent recouvert de glace.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-009',
    subject: 'histoire_geo',
    title: "L'hémisphère Nord et Sud",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'planisphere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'équateur partage la Terre en deux. Comment appelle-t-on la moitié nord ?",
    options: [
      { id: 'a', text: "L'hémisphère Sud", isCorrect: false },
      { id: 'b', text: "L'hémisphère Nord", isCorrect: true },
      { id: 'c', text: "L'hémisphère Est", isCorrect: false },
      { id: 'd', text: "Le tropique", isCorrect: false },
    ],
    correctAnswer: "L'hémisphère Nord",
    explanation: "L'équateur est une ligne imaginaire qui divise la Terre en hémisphère Nord (au-dessus) et hémisphère Sud (en dessous). La France est dans l'hémisphère Nord.",
    hint: "Hémisphère = demi-sphère. Nord = au-dessus de l'équateur.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-010',
    subject: 'histoire_geo',
    title: "Planisphère ou globe ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'planisphere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un planisphère est une représentation de la Terre. Quelle est sa forme ?",
    options: [
      { id: 'a', text: "Une sphère (boule)", isCorrect: false },
      { id: 'b', text: "Une carte plate (à plat)", isCorrect: true },
      { id: 'c', text: "Un cylindre", isCorrect: false },
      { id: 'd', text: "Un cône", isCorrect: false },
    ],
    correctAnswer: "Une carte plate (à plat)",
    explanation: "Un planisphère est une carte plate qui représente toute la surface de la Terre. Un globe est une boule qui représente la Terre en 3D. La carte plate déforme légèrement les formes et surfaces.",
    hint: "Planisphère = carte à plat. Globe = boule = plus précis.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-011',
    subject: 'histoire_geo',
    title: "Eau et terres",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'planisphere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Environ quelle proportion de la surface de la Terre est couverte par les océans ?",
    options: [
      { id: 'a', text: "Environ un quart (25 %)", isCorrect: false },
      { id: 'b', text: "Environ les deux tiers (70 %)", isCorrect: true },
      { id: 'c', text: "Exactement la moitié (50 %)", isCorrect: false },
      { id: 'd', text: "Presque tout (95 %)", isCorrect: false },
    ],
    correctAnswer: "Environ les deux tiers (70 %)",
    explanation: "Les océans et mers couvrent environ 70 % de la surface de la Terre. Les continents et îles ne représentent que 30 % de la surface totale. La Terre est surtout une planète d'eau !",
    hint: "Terre bleue = 70 % d'eau. Les continents = seulement 30 %.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-012',
    subject: 'histoire_geo',
    title: "L'Asie et ses pays",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Lequel de ces pays est en Asie ?",
    options: [
      { id: 'a', text: "Le Brésil", isCorrect: false },
      { id: 'b', text: "Le Japon", isCorrect: true },
      { id: 'c', text: "L'Australie", isCorrect: false },
      { id: 'd', text: "Le Nigeria", isCorrect: false },
    ],
    correctAnswer: "Le Japon",
    explanation: "Le Japon est un archipel d'îles en Asie de l'Est, dans l'océan Pacifique. Le Brésil est en Amérique du Sud, l'Australie en Océanie, le Nigeria en Afrique.",
    hint: "Japon = îles en Asie de l'Est, dans le Pacifique.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-013',
    subject: 'histoire_geo',
    title: "L'Océanie",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Australie est le pays le plus grand d'Océanie. Dans quel océan est-elle située ?",
    options: [
      { id: 'a', text: "L'Atlantique", isCorrect: false },
      { id: 'b', text: "Le Pacifique et l'Indien", isCorrect: true },
      { id: 'c', text: "L'Arctique", isCorrect: false },
      { id: 'd', text: "La Méditerranée", isCorrect: false },
    ],
    correctAnswer: "Le Pacifique et l'Indien",
    explanation: "L'Australie est entourée par l'océan Pacifique à l'est et l'océan Indien à l'ouest. C'est à la fois un pays et un continent (le 6e ou 7e selon les classements).",
    hint: "Australie = entourée du Pacifique (est) et de l'Indien (ouest).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-014',
    subject: 'histoire_geo',
    title: "Mers et océans : la différence",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la différence entre une mer et un océan ?",
    options: [
      { id: 'a', text: "La mer est plus profonde que l'océan", isCorrect: false },
      { id: 'b', text: "La mer est une étendue d'eau plus petite, souvent entourée de terres ; l'océan est immense", isCorrect: true },
      { id: 'c', text: "Il n'y a aucune différence", isCorrect: false },
      { id: 'd', text: "L'océan est d'eau douce", isCorrect: false },
    ],
    correctAnswer: "La mer est une étendue d'eau plus petite, souvent entourée de terres ; l'océan est immense",
    explanation: "Les mers sont des étendues d'eau salée plus petites (mer Méditerranée, mer du Nord). Les océans sont de vastes étendues (Pacifique, Atlantique). Les mers sont souvent reliées aux océans.",
    hint: "Mer = plus petite, souvent entourée de terres. Océan = immense.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-cto-015',
    subject: 'histoire_geo',
    title: "La Réunion : quel continent ?",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'continents_oceans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'île de la Réunion est un département français. Dans quel océan se trouve-t-elle ?",
    options: [
      { id: 'a', text: "L'Atlantique", isCorrect: false },
      { id: 'b', text: "L'océan Indien", isCorrect: true },
      { id: 'c', text: "Le Pacifique", isCorrect: false },
      { id: 'd', text: "La Méditerranée", isCorrect: false },
    ],
    correctAnswer: "L'océan Indien",
    explanation: "L'île de la Réunion est un département et région d'outre-mer (DROM) français, situé dans l'océan Indien, à l'est de Madagascar. Bien qu'elle soit française, elle est géographiquement proche de l'Afrique.",
    hint: "La Réunion = île française dans l'océan Indien, près de Madagascar.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
