import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCe2HistoireVieQuotidienneExercises: HgExercise[] = [

  {
    id: 'hg-ce2-hist-vq-001',
    subject: 'histoire_geo',
    title: "Les Gaulois : ce qu'ils mangeaient",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_gauloises',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Gaulois vivaient dans des villages et cultivaient la terre. Quelle céréale cultivaient-ils surtout ?",
    options: [
      { id: 'a', text: "Le riz", isCorrect: false },
      { id: 'b', text: "Le blé et l'orge", isCorrect: true },
      { id: 'c', text: "Le maïs", isCorrect: false },
      { id: 'd', text: "La pomme de terre", isCorrect: false },
    ],
    correctAnswer: "Le blé et l'orge",
    explanation: "Les Gaulois cultivaient principalement le blé et l'orge pour faire du pain et de la bouillie. Le maïs et la pomme de terre viennent d'Amérique et n'existaient pas encore en Europe à cette époque.",
    hint: "Le maïs et la pomme de terre n'existaient pas encore en Europe à l'époque des Gaulois.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-002',
    subject: 'histoire_geo',
    title: "Les Gaulois : leurs maisons",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_gauloises',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Dans quel type de maison vivaient les Gaulois ?",
    options: [
      { id: 'a', text: "Des maisons en pierre avec des fenêtres en verre", isCorrect: false },
      { id: 'b', text: "Des huttes rondes en bois et en chaume", isCorrect: true },
      { id: 'c', text: "Des appartements dans de grands immeubles", isCorrect: false },
      { id: 'd', text: "Des châteaux forts avec des tours", isCorrect: false },
    ],
    correctAnswer: "Des huttes rondes en bois et en chaume",
    explanation: "Les Gaulois construisaient des maisons rondes avec des murs en bois et des toits en chaume (paille). Elles abritaient souvent toute la famille, y compris les animaux en hiver.",
    hint: "Les maisons gauloises étaient construites avec les matériaux de la nature : bois et paille.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-003',
    subject: 'histoire_geo',
    title: "L'école au Moyen Âge",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au Moyen Âge, qui apprenait à lire et à écrire ?",
    options: [
      { id: 'a', text: "Tous les enfants, comme aujourd'hui", isCorrect: false },
      { id: 'b', text: "Principalement les futurs prêtres et moines, dans les monastères", isCorrect: true },
      { id: 'c', text: "Uniquement les filles des nobles", isCorrect: false },
      { id: 'd', text: "Les paysans en priorité", isCorrect: false },
    ],
    correctAnswer: "Principalement les futurs prêtres et moines, dans les monastères",
    explanation: "Au Moyen Âge, la plupart des enfants ne savaient pas lire. C'est dans les monastères que l'on apprenait à lire, écrire et recopier des livres. Charlemagne avait essayé d'ouvrir des écoles, mais elles restaient rares.",
    hint: "Au Moyen Âge, les livres étaient copiés à la main dans les monastères.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-004',
    subject: 'histoire_geo',
    title: "La nourriture au Moyen Âge",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au Moyen Âge, quelle était la nourriture principale des paysans ?",
    options: [
      { id: 'a', text: "Les frites et les poulets rôtis", isCorrect: false },
      { id: 'b', text: "Le pain, les légumes et la bouillie de céréales", isCorrect: true },
      { id: 'c', text: "Les pizzas et les pâtes", isCorrect: false },
      { id: 'd', text: "Le chocolat et les bonbons", isCorrect: false },
    ],
    correctAnswer: "Le pain, les légumes et la bouillie de céréales",
    explanation: "Les paysans du Moyen Âge mangeaient surtout du pain de seigle ou d'orge, des légumes (navets, choux, poireaux) et une bouillie de céréales. La viande était rare et réservée aux jours de fête.",
    hint: "Les paysans du Moyen Âge mangeaient surtout ce qu'ils cultivaient.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-005',
    subject: 'histoire_geo',
    title: "Les chevaliers au Moyen Âge",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Que portait un chevalier pour se protéger au combat au Moyen Âge ?",
    options: [
      { id: 'a', text: "Un uniforme en coton et un casque de vélo", isCorrect: false },
      { id: 'b', text: "Une armure en métal et un bouclier", isCorrect: true },
      { id: 'c', text: "Une toge blanche comme les Romains", isCorrect: false },
      { id: 'd', text: "Des habits de paysan pour se cacher", isCorrect: false },
    ],
    correctAnswer: "Une armure en métal et un bouclier",
    explanation: "Les chevaliers portaient une armure en métal (d'abord des cottes de mailles en anneaux de fer, puis des plaques d'acier), un bouclier et un casque. Ils combattaient à cheval avec une lance ou une épée.",
    hint: "Les chevaliers étaient des guerriers bien protégés pour combattre.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-006',
    subject: 'histoire_geo',
    title: "Les châteaux forts",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "À quoi servait le château fort au Moyen Âge ?",
    options: [
      { id: 'a', text: "C'était uniquement une prison", isCorrect: false },
      { id: 'b', text: "C'était la résidence du seigneur et un lieu de protection pour les habitants", isCorrect: true },
      { id: 'c', text: "C'était uniquement un lieu de prière", isCorrect: false },
      { id: 'd', text: "C'était un marché où l'on vendait des produits", isCorrect: false },
    ],
    correctAnswer: "C'était la résidence du seigneur et un lieu de protection pour les habitants",
    explanation: "Le château fort était la maison du seigneur. En cas d'attaque, les habitants du village pouvaient s'y réfugier. Ses hauts murs, ses tours et ses fossés le rendaient difficile à prendre.",
    hint: "Le château fort servait à se défendre en cas d'attaque.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-007',
    subject: 'histoire_geo',
    title: "Les paysans au Moyen Âge",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au Moyen Âge, la plupart des gens étaient des paysans. Que devaient-ils payer au seigneur ?",
    options: [
      { id: 'a', text: "Un abonnement à Internet", isCorrect: false },
      { id: 'b', text: "Des impôts en argent ou en nourriture (blé, poules…)", isCorrect: true },
      { id: 'c', text: "Un loyer en bonbons", isCorrect: false },
      { id: 'd', text: "Rien, c'était gratuit", isCorrect: false },
    ],
    correctAnswer: "Des impôts en argent ou en nourriture (blé, poules…)",
    explanation: "Les paysans devaient payer des redevances au seigneur : une part de leur récolte, quelques jours de travail gratuit sur ses terres (corvées) et diverses taxes. En échange, le seigneur les protégeait.",
    hint: "Les paysans payaient leur seigneur avec ce qu'ils produisaient.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-008',
    subject: 'histoire_geo',
    title: "Les vêtements au Moyen Âge",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "De quoi étaient faits les vêtements des paysans au Moyen Âge ?",
    options: [
      { id: 'a', text: "De nylon et de polyester", isCorrect: false },
      { id: 'b', text: "De laine et de lin tissés à la main", isCorrect: true },
      { id: 'c', text: "De soie et d'or", isCorrect: false },
      { id: 'd', text: "De cuir d'animaux comme au Paléolithique", isCorrect: false },
    ],
    correctAnswer: "De laine et de lin tissés à la main",
    explanation: "Les paysans portaient des vêtements simples en laine (mouton) ou en lin (plante), tissés à la main chez eux. Les nobles pouvaient se permettre des tissus plus fins ou colorés comme la soie, importée d'Orient.",
    hint: "Les paysans fabriquaient leurs vêtements avec ce qu'ils produisaient.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-009',
    subject: 'histoire_geo',
    title: "L'école au XIXe siècle",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_xixe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Jules Ferry rend l'école gratuite et obligatoire en 1882. Jusqu'à quel âge les enfants devaient-ils aller à l'école ?",
    options: [
      { id: 'a', text: "Jusqu'à 8 ans", isCorrect: false },
      { id: 'b', text: "Jusqu'à 13 ans", isCorrect: true },
      { id: 'c', text: "Jusqu'à 18 ans", isCorrect: false },
      { id: 'd', text: "Jusqu'à 5 ans seulement", isCorrect: false },
    ],
    correctAnswer: "Jusqu'à 13 ans",
    explanation: "La loi Jules Ferry de 1882 rend l'école obligatoire pour les enfants de 6 à 13 ans. Avant cette loi, beaucoup d'enfants travaillaient dès leur jeune âge sans jamais apprendre à lire.",
    hint: "Jules Ferry 1882 = école obligatoire de 6 à 13 ans.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-010',
    subject: 'histoire_geo',
    title: "Le travail des enfants au XIXe siècle",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_xixe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au XIXe siècle, avant les lois protégeant les enfants, beaucoup d'entre eux travaillaient. Où ?",
    options: [
      { id: 'a', text: "Dans les écoles comme professeurs", isCorrect: false },
      { id: 'b', text: "Dans les usines, les mines et les champs dès 6 ou 7 ans", isCorrect: true },
      { id: 'c', text: "Dans les hôpitaux comme médecins", isCorrect: false },
      { id: 'd', text: "Dans les châteaux forts", isCorrect: false },
    ],
    correctAnswer: "Dans les usines, les mines et les champs dès 6 ou 7 ans",
    explanation: "Au XIXe siècle, des enfants très jeunes travaillaient dans les mines, les usines textiles ou les champs. C'est pour lutter contre cela que les premières lois sur le travail des enfants ont été votées.",
    hint: "Avant les lois, les enfants pauvres travaillaient comme des adultes.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-011',
    subject: 'histoire_geo',
    title: "Les transports au XIXe siècle",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_xixe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au début du XIXe siècle (avant le train), comment les gens voyageaient-ils d'une ville à l'autre ?",
    options: [
      { id: 'a', text: "En avion", isCorrect: false },
      { id: 'b', text: "En diligence (voiture tirée par des chevaux)", isCorrect: true },
      { id: 'c', text: "En voiture à moteur", isCorrect: false },
      { id: 'd', text: "En tramway électrique", isCorrect: false },
    ],
    correctAnswer: "En diligence (voiture tirée par des chevaux)",
    explanation: "Avant l'invention du train, les gens voyageaient en diligence : une grande voiture en bois tirée par des chevaux. Le voyage pouvait durer plusieurs jours pour parcourir quelques centaines de kilomètres.",
    hint: "Avant le train, les déplacements dépendaient des chevaux.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-012',
    subject: 'histoire_geo',
    title: "L'éclairage dans le passé",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_xixe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Avant l'électricité, comment les gens s'éclairaient-ils le soir ?",
    options: [
      { id: 'a', text: "Avec des lampes LED", isCorrect: false },
      { id: 'b', text: "Avec des bougies, des lampes à huile ou à pétrole", isCorrect: true },
      { id: 'c', text: "Avec des néons fluorescents", isCorrect: false },
      { id: 'd', text: "Avec des tablettes lumineuses", isCorrect: false },
    ],
    correctAnswer: "Avec des bougies, des lampes à huile ou à pétrole",
    explanation: "Avant l'électricité (fin XIXe s.), on s'éclairait avec des bougies ou des lampes à huile, puis à pétrole. L'électricité a révolutionné la vie quotidienne en apportant un éclairage sûr et abondant.",
    hint: "L'électricité domestique n'existait pas avant la fin du XIXe siècle.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-013',
    subject: 'histoire_geo',
    title: "La médecine dans le passé",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_xixe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Avant les découvertes de Pasteur au XIXe siècle, pourquoi tant de gens mouraient-ils d'infections ?",
    options: [
      { id: 'a', text: "Parce qu'il n'y avait pas assez à manger", isCorrect: false },
      { id: 'b', text: "Parce qu'on ne savait pas encore que les microbes causaient les maladies", isCorrect: true },
      { id: 'c', text: "Parce qu'il y avait trop de soleil", isCorrect: false },
      { id: 'd', text: "Parce que les gens ne se lavaient jamais", isCorrect: false },
    ],
    correctAnswer: "Parce qu'on ne savait pas encore que les microbes causaient les maladies",
    explanation: "Avant Pasteur, on ne connaissait pas les microbes. Les médecins ne désinfectaient pas leurs outils. Beaucoup de patients mouraient d'infections après une opération. Pasteur a montré que les germes causent les maladies.",
    hint: "Pasteur a découvert que les microbes causent les maladies.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-014',
    subject: 'histoire_geo',
    title: "La vie à l'époque de Louis XIV",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'vie_quotidienne_ancien_regime',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "À l'époque de Louis XIV (XVIIe siècle), comment les nobles passaient-ils leur temps à Versailles ?",
    options: [
      { id: 'a', text: "En travaillant dans les champs", isCorrect: false },
      { id: 'b', text: "En assistant aux cérémonies royales, en dansant et en chassant", isCorrect: true },
      { id: 'c', text: "En fabriquant des voitures à moteur", isCorrect: false },
      { id: 'd', text: "En allant à l'école obligatoire", isCorrect: false },
    ],
    correctAnswer: "En assistant aux cérémonies royales, en dansant et en chassant",
    explanation: "À Versailles, les nobles vivaient près du roi. Leur journée était rythmée par les cérémonies (lever du roi, repas en public), les bals, la chasse et les spectacles. Cette vie brillante cachait une réalité très inégalitaire.",
    hint: "La noblesse de Versailles vivait près du roi pour lui plaire.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-hist-vq-015',
    subject: 'histoire_geo',
    title: "Comparer les époque : les maisons",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'comparaison_epoques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Laquelle de ces inventions a le plus changé la maison depuis le Moyen Âge ?",
    options: [
      { id: 'a', text: "La cheminée", isCorrect: false },
      { id: 'b', text: "L'électricité, l'eau courante et le chauffage central", isCorrect: true },
      { id: 'c', text: "Les rideaux aux fenêtres", isCorrect: false },
      { id: 'd', text: "Les portes en bois", isCorrect: false },
    ],
    correctAnswer: "L'électricité, l'eau courante et le chauffage central",
    explanation: "L'électricité (lumière, appareils), l'eau courante (robinets, toilettes) et le chauffage central ont transformé radicalement le confort de la maison depuis le XIXe siècle. Au Moyen Âge, rien de tout cela n'existait.",
    hint: "Ces inventions du XIXe et XXe siècles ont changé le confort de vie pour tous.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
