import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCe2GeocommuneRegionExercises: HgExercise[] = [

  {
    id: 'hg-ce2-geo-ori-001',
    subject: 'histoire_geo',
    title: "Les 4 points cardinaux",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'orientation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les 4 points cardinaux sont le Nord, le Sud, l'Est et l'Ouest. Sur une carte, le Nord se trouve…",
    options: [
      { id: 'a', text: "en bas", isCorrect: false },
      { id: 'b', text: "en haut", isCorrect: true },
      { id: 'c', text: "à droite", isCorrect: false },
      { id: 'd', text: "à gauche", isCorrect: false },
    ],
    correctAnswer: "en haut",
    explanation: "Par convention, sur la plupart des cartes, le Nord est en haut, le Sud en bas, l'Est à droite et l'Ouest à gauche. La rose des vents confirme cette orientation.",
    hint: "Sur une carte, regarde la flèche Nord : elle pointe vers le haut.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-002',
    subject: 'histoire_geo',
    title: "Est et Ouest",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'orientation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Si tu regardes une carte en ayant le Nord devant toi (en haut), l'Est est à…",
    options: [
      { id: 'a', text: "gauche", isCorrect: false },
      { id: 'b', text: "droite", isCorrect: true },
      { id: 'c', text: "en bas", isCorrect: false },
      { id: 'd', text: "en haut", isCorrect: false },
    ],
    correctAnswer: "droite",
    explanation: "N=haut, S=bas, E=droite, O=gauche. Le soleil se lève à l'Est (à droite sur la carte) et se couche à l'Ouest (à gauche).",
    hint: "Le soleil se LÈVE à l'Est → à droite sur une carte orientée Nord en haut.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-003',
    subject: 'histoire_geo',
    title: "La rose des vents",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'orientation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La rose des vents indique les directions sur une carte. Quelle direction est entre le Nord et l'Est ?",
    options: [
      { id: 'a', text: "Le Sud-Ouest", isCorrect: false },
      { id: 'b', text: "Le Nord-Est", isCorrect: true },
      { id: 'c', text: "Le Sud-Est", isCorrect: false },
      { id: 'd', text: "Le Nord-Ouest", isCorrect: false },
    ],
    correctAnswer: "Le Nord-Est",
    explanation: "Entre le Nord et l'Est, on trouve le Nord-Est (NE). La rose des vents a 8 directions : N, NE, E, SE, S, SO, O, NO.",
    hint: "Nord + Est = Nord-Est.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-004',
    subject: 'histoire_geo',
    title: "Qu'est-ce qu'une commune ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Une commune est la plus petite unité administrative de France. Qui dirige une commune ?",
    options: [
      { id: 'a', text: "Le préfet", isCorrect: false },
      { id: 'b', text: "Le maire", isCorrect: true },
      { id: 'c', text: "Le président de la République", isCorrect: false },
      { id: 'd', text: "Le président de région", isCorrect: false },
    ],
    correctAnswer: "Le maire",
    explanation: "Chaque commune (ville ou village) est dirigée par un maire, élu par les habitants. La France compte environ 35 000 communes, des plus petites (quelques habitants) aux plus grandes (Paris).",
    hint: "Le maire est le chef d'une commune, élu par les habitants.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-005',
    subject: 'histoire_geo',
    title: "Le département",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France est divisée en départements. Combien y en a-t-il en France métropolitaine ?",
    options: [
      { id: 'a', text: "13", isCorrect: false },
      { id: 'b', text: "96", isCorrect: true },
      { id: 'c', text: "35 000", isCorrect: false },
      { id: 'd', text: "18", isCorrect: false },
    ],
    correctAnswer: "96",
    explanation: "La France métropolitaine est divisée en 96 départements, chacun avec un numéro (ex : 75 = Paris, 69 = Rhône). En ajoutant les 5 départements d'outre-mer, on en compte 101.",
    hint: "96 départements en métropole, chacun a un numéro.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-006',
    subject: 'histoire_geo',
    title: "Qu'est-ce qu'une région ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Une région regroupe plusieurs départements. Qui dirige une région ?",
    options: [
      { id: 'a', text: "Le maire", isCorrect: false },
      { id: 'b', text: "Le président du conseil régional", isCorrect: true },
      { id: 'c', text: "Le préfet de département", isCorrect: false },
      { id: 'd', text: "Le Premier ministre", isCorrect: false },
    ],
    correctAnswer: "Le président du conseil régional",
    explanation: "La région est dirigée par un président de conseil régional, élu par les habitants. La région gère des domaines comme les lycées, la formation professionnelle et les transports.",
    hint: "Commune → maire. Département → préfet. Région → président de conseil régional.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-007',
    subject: 'histoire_geo',
    title: "Les emboîtements territoriaux",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Dans quel ordre, du plus petit au plus grand, classe-t-on ces territoires ?",
    options: [
      { id: 'a', text: "Pays → région → département → commune", isCorrect: false },
      { id: 'b', text: "Commune → département → région → pays", isCorrect: true },
      { id: 'c', text: "Région → commune → pays → département", isCorrect: false },
      { id: 'd', text: "Département → commune → région → pays", isCorrect: false },
    ],
    correctAnswer: "Commune → département → région → pays",
    explanation: "L'ordre du plus petit au plus grand est : commune (ex: Nantes) → département (Loire-Atlantique) → région (Pays de la Loire) → pays (France). Ces territoires s'emboîtent comme des poupées russes.",
    hint: "Du village au pays : commune → département → région → France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-008',
    subject: 'histoire_geo',
    title: "La France en Europe",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France est un pays membre de l'Union européenne. Dans quel continent se situe l'Europe ?",
    options: [
      { id: 'a', text: "En Asie", isCorrect: false },
      { id: 'b', text: "En Europe (qui est un continent)", isCorrect: true },
      { id: 'c', text: "En Amérique", isCorrect: false },
      { id: 'd', text: "En Afrique", isCorrect: false },
    ],
    correctAnswer: "En Europe (qui est un continent)",
    explanation: "L'Europe est l'un des 7 continents de la Terre. La France y est l'un des plus grands pays. Elle fait partie de l'Union européenne (UE), qui regroupe 27 pays.",
    hint: "Europe = continent. France = pays d'Europe.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-009',
    subject: 'histoire_geo',
    title: "Lire une légende",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lecture_carte',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Sur une carte, la légende sert à…",
    options: [
      { id: 'a', text: "Indiquer la date de création de la carte", isCorrect: false },
      { id: 'b', text: "Expliquer la signification des couleurs et des symboles utilisés", isCorrect: true },
      { id: 'c', text: "Donner le nom de l'auteur de la carte", isCorrect: false },
      { id: 'd', text: "Mesurer les distances", isCorrect: false },
    ],
    correctAnswer: "Expliquer la signification des couleurs et des symboles utilisés",
    explanation: "La légende d'une carte explique ce que représentent les couleurs, les symboles et les hachures. Sans légende, une carte est difficile à lire.",
    hint: "Légende = dictionnaire de la carte.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-010',
    subject: 'histoire_geo',
    title: "L'échelle d'une carte",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lecture_carte',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Sur une carte, l'échelle indique…",
    options: [
      { id: 'a', text: "La température du lieu représenté", isCorrect: false },
      { id: 'b', text: "Le rapport entre les distances sur la carte et les distances réelles", isCorrect: true },
      { id: 'c', text: "Le nombre d'habitants de chaque ville", isCorrect: false },
      { id: 'd', text: "L'orientation de la carte (nord, sud)", isCorrect: false },
    ],
    correctAnswer: "Le rapport entre les distances sur la carte et les distances réelles",
    explanation: "L'échelle indique combien de kilomètres réels correspond à 1 cm sur la carte. Par exemple, 1 cm = 100 km signifie que la carte est très réduite par rapport à la réalité.",
    hint: "Échelle = rapport entre la carte et la réalité.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-011',
    subject: 'histoire_geo',
    title: "Numéro de département",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le numéro 75 sur une plaque d'immatriculation indique que le véhicule a été immatriculé à…",
    options: [
      { id: 'a', text: "Lyon", isCorrect: false },
      { id: 'b', text: "Paris", isCorrect: true },
      { id: 'c', text: "Marseille", isCorrect: false },
      { id: 'd', text: "Toulouse", isCorrect: false },
    ],
    correctAnswer: "Paris",
    explanation: "Le 75 est le numéro du département de Paris. Les codes postaux parisiens commencent par 75. Chaque département a son propre numéro (de 01 à 95 + 2A/2B pour la Corse).",
    hint: "75 = Paris. 69 = Rhône (Lyon). 13 = Bouches-du-Rhône (Marseille).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-012',
    subject: 'histoire_geo',
    title: "Qu'est-ce qu'une frontière ?",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Une frontière est une ligne qui…",
    options: [
      { id: 'a', text: "divise une ville en quartiers", isCorrect: false },
      { id: 'b', text: "sépare deux pays (ou deux territoires)", isCorrect: true },
      { id: 'c', text: "marque le milieu d'une autoroute", isCorrect: false },
      { id: 'd', text: "indique l'altitude sur une carte", isCorrect: false },
    ],
    correctAnswer: "sépare deux pays (ou deux territoires)",
    explanation: "Une frontière délimite le territoire d'un pays. Traverser une frontière signifie entrer dans un autre pays. En Europe, les frontières Schengen peuvent être traversées librement.",
    hint: "Passer la frontière = changer de pays.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-013',
    subject: 'histoire_geo',
    title: "S'orienter avec le soleil",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'orientation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le soleil se couche toujours à l'Ouest. Si tu regardes le soleil se coucher, de quel côté est le Nord ?",
    options: [
      { id: 'a', text: "Derrière toi", isCorrect: false },
      { id: 'b', text: "À ta droite", isCorrect: true },
      { id: 'c', text: "À ta gauche", isCorrect: false },
      { id: 'd', text: "Devant toi", isCorrect: false },
    ],
    correctAnswer: "À ta droite",
    explanation: "Si tu regardes l'Ouest (soleil couchant), le Nord est à ta droite. La règle : face au nord → est à droite, ouest à gauche, sud derrière.",
    hint: "Soleil couchant = Ouest. Ouest = gauche si Nord en haut. Donc Nord = droite quand on regarde l'Ouest.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-014',
    subject: 'histoire_geo',
    title: "Région et chef-lieu",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le chef-lieu de la région Île-de-France (la ville la plus importante) est…",
    options: [
      { id: 'a', text: "Versailles", isCorrect: false },
      { id: 'b', text: "Paris", isCorrect: true },
      { id: 'c', text: "Évry", isCorrect: false },
      { id: 'd', text: "Melun", isCorrect: false },
    ],
    correctAnswer: "Paris",
    explanation: "Paris est la capitale de la France ET le chef-lieu de la région Île-de-France. L'Île-de-France est la région la plus peuplée de France (environ 12 millions d'habitants).",
    hint: "Paris = capitale de la France = chef-lieu de l'Île-de-France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-ori-015',
    subject: 'histoire_geo',
    title: "De la commune au monde",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'organisation_territoriale',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est l'ordre correct, du plus petit au plus grand territoire ?",
    options: [
      { id: 'a', text: "Continent → pays → région → département → commune", isCorrect: false },
      { id: 'b', text: "Commune → département → région → pays → continent → Terre", isCorrect: true },
      { id: 'c', text: "Département → commune → pays → région → Terre", isCorrect: false },
      { id: 'd', text: "Région → commune → continent → pays → département", isCorrect: false },
    ],
    correctAnswer: "Commune → département → région → pays → continent → Terre",
    explanation: "L'emboîtement complet : commune (ex: Lyon) → département (Rhône) → région (Auvergne-Rhône-Alpes) → pays (France) → continent (Europe) → Terre.",
    hint: "Du village à la planète : commune, département, région, pays, continent, Terre.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
