import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCe2GeoEuropeIntroExercises: HgExercise[] = [

  {
    id: 'hg-ce2-geo-eur-001',
    subject: 'histoire_geo',
    title: "L'Europe : combien de pays ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Europe est composée de nombreux pays. Environ combien y en a-t-il ?",
    options: [
      { id: 'a', text: "Environ 10", isCorrect: false },
      { id: 'b', text: "Environ 50", isCorrect: true },
      { id: 'c', text: "Environ 100", isCorrect: false },
      { id: 'd', text: "Environ 5", isCorrect: false },
    ],
    correctAnswer: "Environ 50",
    explanation: "L'Europe compte environ 50 pays souverains selon les différents critères géographiques. L'Union européenne en regroupe 27 (en 2024).",
    hint: "L'Europe a environ 50 pays, dont 27 dans l'UE.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-002',
    subject: 'histoire_geo',
    title: "Les voisins immédiats de la France",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France partage ses frontières avec plusieurs pays européens. Lequel N'est PAS un voisin de la France ?",
    options: [
      { id: 'a', text: "L'Allemagne", isCorrect: false },
      { id: 'b', text: "La Suède", isCorrect: true },
      { id: 'c', text: "L'Italie", isCorrect: false },
      { id: 'd', text: "La Belgique", isCorrect: false },
    ],
    correctAnswer: "La Suède",
    explanation: "La France est voisine de la Belgique, du Luxembourg, de l'Allemagne, de la Suisse, de l'Italie, de Monaco, de l'Espagne et d'Andorre. La Suède est un pays scandinave, très loin de la France.",
    hint: "La Suède est en Scandinavie, au nord de l'Europe — pas du tout voisine de la France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-003',
    subject: 'histoire_geo',
    title: "Les capitales européennes",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale de l'Allemagne ?",
    options: [
      { id: 'a', text: "Munich", isCorrect: false },
      { id: 'b', text: "Berlin", isCorrect: true },
      { id: 'c', text: "Hambourg", isCorrect: false },
      { id: 'd', text: "Francfort", isCorrect: false },
    ],
    correctAnswer: "Berlin",
    explanation: "Berlin est la capitale de l'Allemagne depuis la réunification en 1990. C'est aussi la plus grande ville d'Allemagne avec environ 3,7 millions d'habitants.",
    hint: "Berlin = capitale de l'Allemagne depuis 1990.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-004',
    subject: 'histoire_geo',
    title: "La capitale de l'Espagne",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale de l'Espagne, voisine du sud de la France ?",
    options: [
      { id: 'a', text: "Barcelone", isCorrect: false },
      { id: 'b', text: "Madrid", isCorrect: true },
      { id: 'c', text: "Séville", isCorrect: false },
      { id: 'd', text: "Valence", isCorrect: false },
    ],
    correctAnswer: "Madrid",
    explanation: "Madrid est la capitale de l'Espagne. Elle est située au centre du pays. Barcelone est la 2e ville mais n'est pas la capitale.",
    hint: "Madrid = capitale de l'Espagne. Barcelone = 2e ville mais pas la capitale.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-005',
    subject: 'histoire_geo',
    title: "La mer Méditerranée",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Combien de continents bordent la mer Méditerranée ?",
    options: [
      { id: 'a', text: "Un seul", isCorrect: false },
      { id: 'b', text: "Trois (Europe, Afrique, Asie)", isCorrect: true },
      { id: 'c', text: "Deux", isCorrect: false },
      { id: 'd', text: "Cinq", isCorrect: false },
    ],
    correctAnswer: "Trois (Europe, Afrique, Asie)",
    explanation: "La mer Méditerranée est bordée par trois continents : l'Europe au nord (France, Espagne, Italie, Grèce…), l'Afrique au sud (Maroc, Algérie, Tunisie…) et l'Asie à l'est (Turquie, Liban, Israël…).",
    hint: "Méditerranée = entre Europe (nord), Afrique (sud) et Asie (est).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-006',
    subject: 'histoire_geo',
    title: "La capitale du Royaume-Uni",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Royaume-Uni est une île au nord de la France. Quelle est sa capitale ?",
    options: [
      { id: 'a', text: "Édimbourg", isCorrect: false },
      { id: 'b', text: "Londres", isCorrect: true },
      { id: 'c', text: "Manchester", isCorrect: false },
      { id: 'd', text: "Dublin", isCorrect: false },
    ],
    correctAnswer: "Londres",
    explanation: "Londres est la capitale du Royaume-Uni. C'est l'une des plus grandes villes d'Europe. Édimbourg est la capitale de l'Écosse (partie du Royaume-Uni). Dublin est la capitale de l'Irlande, pays différent.",
    hint: "Londres = capitale du Royaume-Uni. Séparée de la France par la Manche.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-007',
    subject: 'histoire_geo',
    title: "La Suisse : un voisin particulier",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Suisse est voisine de la France à l'est. Quelle est sa particularité par rapport à la plupart des pays d'Europe ?",
    options: [
      { id: 'a', text: "Elle n'a pas de montagnes", isCorrect: false },
      { id: 'b', text: "Elle n'est pas membre de l'Union européenne", isCorrect: true },
      { id: 'c', text: "Elle n'a pas de frontière avec la France", isCorrect: false },
      { id: 'd', text: "Sa capitale est Zurich", isCorrect: false },
    ],
    correctAnswer: "Elle n'est pas membre de l'Union européenne",
    explanation: "La Suisse est un pays indépendant qui n'est pas membre de l'Union européenne. Sa capitale est Berne (et non Zurich qui est la plus grande ville). Elle a 4 langues officielles : français, allemand, italien et romanche.",
    hint: "Suisse = voisine de la France, mais pas dans l'UE. Capitale = Berne.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-008',
    subject: 'histoire_geo',
    title: "L'Italie",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Italie est voisine de la France au sud-est. Quelle forme particulière a-t-elle sur la carte ?",
    options: [
      { id: 'a', text: "La forme d'une étoile", isCorrect: false },
      { id: 'b', text: "La forme d'une botte", isCorrect: true },
      { id: 'c', text: "La forme d'un carré", isCorrect: false },
      { id: 'd', text: "La forme d'un hexagone", isCorrect: false },
    ],
    correctAnswer: "La forme d'une botte",
    explanation: "L'Italie est célèbre pour sa forme de botte sur la carte. Elle s'étend dans la mer Méditerranée vers le sud. Sa capitale est Rome.",
    hint: "Italie = péninsule en forme de botte dans la Méditerranée.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-009',
    subject: 'histoire_geo',
    title: "La capitale de la Belgique",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Belgique est voisine du nord de la France. Quelle est sa capitale, qui accueille aussi des institutions européennes ?",
    options: [
      { id: 'a', text: "Liège", isCorrect: false },
      { id: 'b', text: "Bruxelles", isCorrect: true },
      { id: 'c', text: "Anvers", isCorrect: false },
      { id: 'd', text: "Gand", isCorrect: false },
    ],
    correctAnswer: "Bruxelles",
    explanation: "Bruxelles est la capitale de la Belgique. Elle est aussi le siège de nombreuses institutions de l'Union européenne, notamment la Commission européenne et le Parlement européen (avec Strasbourg).",
    hint: "Bruxelles = capitale belge + siège de l'UE.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-010',
    subject: 'histoire_geo',
    title: "Les pays du nord de l'Europe",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Suède, la Norvège et le Danemark sont des pays du nord de l'Europe. Comment appelle-t-on cette région ?",
    options: [
      { id: 'a', text: "Les pays méditerranéens", isCorrect: false },
      { id: 'b', text: "La Scandinavie", isCorrect: true },
      { id: 'c', text: "Les pays de l'Est", isCorrect: false },
      { id: 'd', text: "Les pays du Bénélux", isCorrect: false },
    ],
    correctAnswer: "La Scandinavie",
    explanation: "La Scandinavie désigne les pays du nord de l'Europe : Suède, Norvège, Danemark (et parfois la Finlande et l'Islande). Ces pays sont connus pour leur qualité de vie élevée et leurs fjords.",
    hint: "Scandinavie = nord de l'Europe = Suède, Norvège, Danemark.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-011',
    subject: 'histoire_geo',
    title: "L'Union européenne",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Union européenne (UE) est une organisation de pays européens. Quel symbole reconnaît-on immédiatement comme celui de l'UE ?",
    options: [
      { id: 'a', text: "Un drapeau rouge avec une étoile jaune", isCorrect: false },
      { id: 'b', text: "Un drapeau bleu avec un cercle d'étoiles jaunes", isCorrect: true },
      { id: 'c', text: "Un drapeau vert avec une croix blanche", isCorrect: false },
      { id: 'd', text: "Un drapeau tricolore bleu-blanc-rouge", isCorrect: false },
    ],
    correctAnswer: "Un drapeau bleu avec un cercle d'étoiles jaunes",
    explanation: "Le drapeau de l'Union européenne est bleu avec 12 étoiles dorées disposées en cercle. Les 12 étoiles symbolisent l'unité et la solidarité entre les peuples européens.",
    hint: "Drapeau UE = fond bleu + 12 étoiles dorées en cercle.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-012',
    subject: 'histoire_geo',
    title: "Les Alpes et plusieurs pays",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Alpes sont une chaîne de montagnes partagée par plusieurs pays. Lesquels ?",
    options: [
      { id: 'a', text: "La France, l'Espagne et le Portugal", isCorrect: false },
      { id: 'b', text: "La France, la Suisse, l'Italie, l'Autriche et l'Allemagne", isCorrect: true },
      { id: 'c', text: "La Norvège, la Suède et la Finlande", isCorrect: false },
      { id: 'd', text: "La Pologne, la Hongrie et la Roumanie", isCorrect: false },
    ],
    correctAnswer: "La France, la Suisse, l'Italie, l'Autriche et l'Allemagne",
    explanation: "Les Alpes traversent plusieurs pays : France (Savoie, Dauphiné), Suisse, Italie (nord), Autriche et Allemagne (Bavière). C'est la plus grande chaîne de montagnes d'Europe occidentale.",
    hint: "Les Alpes = chaîne partagée par France, Suisse, Italie, Autriche, Allemagne.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-013',
    subject: 'histoire_geo',
    title: "La Manche",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Manche est une mer qui sépare la France du Royaume-Uni. Quelle est sa largeur minimale ?",
    options: [
      { id: 'a', text: "Environ 34 km au détroit du Pas-de-Calais", isCorrect: true },
      { id: 'b', text: "Environ 500 km", isCorrect: false },
      { id: 'c', text: "Environ 5 km seulement", isCorrect: false },
      { id: 'd', text: "Environ 200 km", isCorrect: false },
    ],
    correctAnswer: "Environ 34 km au détroit du Pas-de-Calais",
    explanation: "Au point le plus étroit — le détroit du Pas-de-Calais entre Calais et Douvres — la Manche ne fait que 34 km de large. C'est là que passe le tunnel sous la Manche.",
    hint: "Calais-Douvres = 34 km = le tunnel sous la Manche passe là.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-014',
    subject: 'histoire_geo',
    title: "L'Europe : au nord ou au sud ?",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Grèce est un pays du sud de l'Europe. Dans quelle mer ses nombreuses îles sont-elles situées ?",
    options: [
      { id: 'a', text: "La mer du Nord", isCorrect: false },
      { id: 'b', text: "La mer Égée et la Méditerranée", isCorrect: true },
      { id: 'c', text: "L'océan Atlantique", isCorrect: false },
      { id: 'd', text: "La mer Baltique", isCorrect: false },
    ],
    correctAnswer: "La mer Égée et la Méditerranée",
    explanation: "La Grèce est un pays méditerranéen avec des milliers d'îles dispersées dans la mer Égée (entre la Grèce et la Turquie) et en Méditerranée. Sa capitale est Athènes.",
    hint: "Grèce = îles en mer Égée + Méditerranée. Capitale = Athènes.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-eur-015',
    subject: 'histoire_geo',
    title: "La capitale de la Russie",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe_intro',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Russie est le plus grand pays du monde, s'étendant sur l'Europe ET l'Asie. Quelle est sa capitale ?",
    options: [
      { id: 'a', text: "Saint-Pétersbourg", isCorrect: false },
      { id: 'b', text: "Moscou", isCorrect: true },
      { id: 'c', text: "Kiev", isCorrect: false },
      { id: 'd', text: "Vladivostok", isCorrect: false },
    ],
    correctAnswer: "Moscou",
    explanation: "Moscou est la capitale de la Russie et sa plus grande ville. La Russie s'étend sur deux continents (Europe et Asie) et représente environ 11 % des terres émergées du globe.",
    hint: "Moscou = capitale de la Russie, plus grand pays du monde.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
