import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCe2GeoDeplacementsExercises: HgExercise[] = [

  {
    id: 'hg-ce2-geo-dep-001',
    subject: 'histoire_geo',
    title: "Les moyens de transport",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Parmi ces moyens de transport, lequel ne circule PAS sur une route ?",
    options: [
      { id: 'a', text: "La voiture", isCorrect: false },
      { id: 'b', text: "Le train", isCorrect: true },
      { id: 'c', text: "Le bus", isCorrect: false },
      { id: 'd', text: "Le camion", isCorrect: false },
    ],
    correctAnswer: "Le train",
    explanation: "Le train circule sur des rails (voies ferrées), pas sur des routes. La voiture, le bus et le camion circulent tous sur des routes.",
    hint: "Le train a besoin de rails, pas de routes.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-002',
    subject: 'histoire_geo',
    title: "Les transports en commun",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les transports en commun sont des transports utilisés par beaucoup de personnes en même temps. Lequel de ces transports n'est PAS un transport en commun ?",
    options: [
      { id: 'a', text: "Le métro", isCorrect: false },
      { id: 'b', text: "La voiture personnelle", isCorrect: true },
      { id: 'c', text: "Le bus", isCorrect: false },
      { id: 'd', text: "Le tramway", isCorrect: false },
    ],
    correctAnswer: "La voiture personnelle",
    explanation: "La voiture personnelle transporte en général une seule famille. Le métro, le bus et le tramway sont des transports en commun car ils emportent de nombreux passagers à la fois.",
    hint: "Transport en commun = tout le monde partage le même véhicule.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-003',
    subject: 'histoire_geo',
    title: "L'avion",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'avion est utilisé pour les voyages très longs. D'où décolle et atterrit un avion ?",
    options: [
      { id: 'a', text: "Une gare", isCorrect: false },
      { id: 'b', text: "Un aéroport", isCorrect: true },
      { id: 'c', text: "Un port", isCorrect: false },
      { id: 'd', text: "Une station-service", isCorrect: false },
    ],
    correctAnswer: "Un aéroport",
    explanation: "Les avions décollent et atterrissent dans des aéroports. En France, les plus grands sont Roissy-Charles-de-Gaulle et Orly, près de Paris.",
    hint: "Avion → aéroport. Bateau → port. Train → gare.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-004',
    subject: 'histoire_geo',
    title: "Le bateau",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les bateaux sont utilisés pour traverser des mers ou des océans. Depuis où les bateaux partent-ils ?",
    options: [
      { id: 'a', text: "Un aéroport", isCorrect: false },
      { id: 'b', text: "Un port", isCorrect: true },
      { id: 'c', text: "Une gare routière", isCorrect: false },
      { id: 'd', text: "Une halte ferroviaire", isCorrect: false },
    ],
    correctAnswer: "Un port",
    explanation: "Les bateaux partent des ports. En France, les grands ports sont Marseille, Le Havre, Bordeaux et Dunkerque. Les ferries traversent la Manche entre Calais et Douvres.",
    hint: "Le bateau a besoin d'eau → port = là où l'eau et la terre se rejoignent.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-005',
    subject: 'histoire_geo',
    title: "Le vélo",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le vélo est un mode de transport qu'on appelle « doux ». Pourquoi ?",
    options: [
      { id: 'a', text: "Parce qu'il est confortable et silencieux uniquement", isCorrect: false },
      { id: 'b', text: "Parce qu'il ne pollue pas et ne consomme pas de carburant fossile", isCorrect: true },
      { id: 'c', text: "Parce qu'il est plus rapide que la voiture", isCorrect: false },
      { id: 'd', text: "Parce qu'il peut transporter beaucoup de personnes", isCorrect: false },
    ],
    correctAnswer: "Parce qu'il ne pollue pas et ne consomme pas de carburant fossile",
    explanation: "On appelle « transports doux » le vélo, la trottinette et la marche : ils ne brûlent pas de pétrole, ne produisent pas de CO₂ et n'émettent pas de bruit de moteur.",
    hint: "Doux = sans moteur polluant.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-006',
    subject: 'histoire_geo',
    title: "Le métro",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le métro est un transport en commun que l'on trouve principalement…",
    options: [
      { id: 'a', text: "Dans les villages à la campagne", isCorrect: false },
      { id: 'b', text: "Dans les grandes villes", isCorrect: true },
      { id: 'c', text: "Sur les autoroutes", isCorrect: false },
      { id: 'd', text: "En mer", isCorrect: false },
    ],
    correctAnswer: "Dans les grandes villes",
    explanation: "Le métro circule sous terre dans les grandes villes. Paris possède l'un des plus vieux et des plus denses réseaux de métro au monde (16 lignes, 300+ stations).",
    hint: "Métro = sous la ville = grande ville uniquement.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-007',
    subject: 'histoire_geo',
    title: "Le train et la gare",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les trains s'arrêtent dans des gares. Quelle est la gare parisienne d'où partent les TGV vers Lyon et le sud de la France ?",
    options: [
      { id: 'a', text: "Gare du Nord", isCorrect: false },
      { id: 'b', text: "Gare de Lyon", isCorrect: true },
      { id: 'c', text: "Gare de l'Est", isCorrect: false },
      { id: 'd', text: "Gare Montparnasse", isCorrect: false },
    ],
    correctAnswer: "Gare de Lyon",
    explanation: "La Gare de Lyon (Paris) dessert le sud-est : Lyon, Marseille, Nice. La Gare du Nord dessert le nord et l'Angleterre (Eurostar), Montparnasse dessert l'ouest et Bordeaux.",
    hint: "Gare de Lyon → on part vers Lyon et le Sud-Est.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-008',
    subject: 'histoire_geo',
    title: "Distances et transports",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Pour aller de Paris à New York (à 5 800 km), quel est le moyen de transport le plus adapté ?",
    options: [
      { id: 'a', text: "Le train", isCorrect: false },
      { id: 'b', text: "L'avion", isCorrect: true },
      { id: 'c', text: "Le vélo", isCorrect: false },
      { id: 'd', text: "La voiture", isCorrect: false },
    ],
    correctAnswer: "L'avion",
    explanation: "New York est de l'autre côté de l'océan Atlantique. Seul l'avion permet de traverser l'océan en quelques heures (environ 8h de vol Paris-New York).",
    hint: "Pour traverser un océan, aucun train ni voiture n'est possible.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-009',
    subject: 'histoire_geo',
    title: "Les autoroutes",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Sur les autoroutes françaises, on doit souvent payer un droit de passage. Comment s'appelle ce paiement ?",
    options: [
      { id: 'a', text: "L'amende", isCorrect: false },
      { id: 'b', text: "Le péage", isCorrect: true },
      { id: 'c', text: "Le ticket", isCorrect: false },
      { id: 'd', text: "La taxe de route", isCorrect: false },
    ],
    correctAnswer: "Le péage",
    explanation: "Les autoroutes françaises sont en grande partie payantes. On paie un péage (à des bornes) pour les emprunter. L'argent sert à entretenir et construire les routes.",
    hint: "Péage → barrière → tu paies pour passer.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-010',
    subject: 'histoire_geo',
    title: "Transport et environnement",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel mode de transport pollue le moins pour faire un long trajet entre deux villes ?",
    options: [
      { id: 'a', text: "L'avion", isCorrect: false },
      { id: 'b', text: "Le train", isCorrect: true },
      { id: 'c', text: "La voiture individuelle", isCorrect: false },
      { id: 'd', text: "Le bus diesel", isCorrect: false },
    ],
    correctAnswer: "Le train",
    explanation: "Le train électrique émet beaucoup moins de CO₂ par passager que l'avion ou la voiture. En France, le TGV est le mode de transport longue distance le moins polluant.",
    hint: "Train électrique → peu de CO₂ → meilleur pour l'environnement.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-011',
    subject: 'histoire_geo',
    title: "Le bus scolaire",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le bus scolaire est un transport en commun. En l'utilisant plutôt que d'aller en voiture, on…",
    options: [
      { id: 'a', text: "pollue davantage", isCorrect: false },
      { id: 'b', text: "réduit le nombre de voitures et la pollution", isCorrect: true },
      { id: 'c', text: "augmente les embouteillages", isCorrect: false },
      { id: 'd', text: "perd du temps inutilement", isCorrect: false },
    ],
    correctAnswer: "réduit le nombre de voitures et la pollution",
    explanation: "Un bus peut transporter 50 à 80 élèves à la fois, remplaçant autant de voitures. Moins de voitures = moins de pollution, moins d'embouteillages et moins d'émissions de CO₂.",
    hint: "1 bus = 50 voitures en moins → moins de pollution.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-012',
    subject: 'histoire_geo',
    title: "Les marchandises",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les produits vendus dans les supermarchés viennent parfois de pays lointains. Quel moyen de transport est surtout utilisé pour transporter de très grandes quantités de marchandises entre continents ?",
    options: [
      { id: 'a', text: "L'avion", isCorrect: false },
      { id: 'b', text: "Le bateau porte-conteneurs", isCorrect: true },
      { id: 'c', text: "Le camion", isCorrect: false },
      { id: 'd', text: "Le train", isCorrect: false },
    ],
    correctAnswer: "Le bateau porte-conteneurs",
    explanation: "La grande majorité des marchandises mondiales (vêtements, électronique, jouets…) est transportée par bateaux porte-conteneurs. Ils sont lents mais transportent des milliers de conteneurs à la fois.",
    hint: "Le bateau est lent mais transporte des milliers de boîtes = conteneurs.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-013',
    subject: 'histoire_geo',
    title: "Voyager à l'étranger",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Pour voyager hors d'Europe (dans un pays très lointain), quel document d'identité est généralement nécessaire ?",
    options: [
      { id: 'a', text: "La carte d'électeur", isCorrect: false },
      { id: 'b', text: "Le passeport", isCorrect: true },
      { id: 'c', text: "La carte de bibliothèque", isCorrect: false },
      { id: 'd', text: "Le livret de famille", isCorrect: false },
    ],
    correctAnswer: "Le passeport",
    explanation: "Le passeport est un document officiel qui permet de prouver son identité et sa nationalité à l'étranger. Pour certains pays, un visa est aussi nécessaire.",
    hint: "Passeport = document pour voyager hors de son pays.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-014',
    subject: 'histoire_geo',
    title: "Le tramway",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le tramway est un transport en commun qui circule en ville. Sur quoi roule-t-il ?",
    options: [
      { id: 'a', text: "Sur l'eau", isCorrect: false },
      { id: 'b', text: "Sur des rails intégrés dans la rue", isCorrect: true },
      { id: 'c', text: "Sur une route normale comme un bus", isCorrect: false },
      { id: 'd', text: "Dans un tunnel sous la ville", isCorrect: false },
    ],
    correctAnswer: "Sur des rails intégrés dans la rue",
    explanation: "Le tramway circule sur des rails posés à même le sol des rues. Il est électrique (donc moins polluant qu'un bus diesel) et peut transporter beaucoup de passagers.",
    hint: "Tramway = train électrique dans la rue, sur des rails.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-ce2-geo-dep-015',
    subject: 'histoire_geo',
    title: "Le vélo en ville",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'deplacements',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "De nombreuses villes aménagent des pistes cyclables. Quel est l'avantage d'une piste cyclable ?",
    options: [
      { id: 'a', text: "Elle est réservée aux voitures électriques", isCorrect: false },
      { id: 'b', text: "Elle sécurise les déplacements à vélo en séparant vélos et voitures", isCorrect: true },
      { id: 'c', text: "Elle permet aux piétons de marcher plus vite", isCorrect: false },
      { id: 'd', text: "Elle est réservée aux livraisons de colis", isCorrect: false },
    ],
    correctAnswer: "Elle sécurise les déplacements à vélo en séparant vélos et voitures",
    explanation: "Les pistes cyclables (bandes ou voies séparées) permettent aux cyclistes de circuler en sécurité, sans risquer de se faire heurter par des voitures. Cela encourage l'usage du vélo.",
    hint: "Piste cyclable = espace protégé pour les vélos.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
