import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe2ConjugaisonExercises: FrenchExercise[] = [
  {
    id: 'fr-ce2-conjugaison-101',
    subject: 'francais',
    title: 'Présent du 1er groupe',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ dans la cour.',
    options: [
      { id: 'a', text: 'jouons', isCorrect: true },
      { id: 'b', text: 'joue', isCorrect: false },
      { id: 'c', text: 'jouez', isCorrect: false }
    ],
    correctAnswer: 'jouons',
    explanation: 'Avec nous, on écrit jouons.',
    hint: 'Pense à : nous jouons.',
    tags: ['ce2','conjugaison','present','1er-groupe','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-102',
    subject: 'francais',
    title: 'Être au présent',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Après une longue course, Lucas dit : « Je ___ épuisé mais fier. »',
    options: [
      { id: 'a', text: 'suis', isCorrect: true },
      { id: 'b', text: 'es', isCorrect: false },
      { id: 'c', text: 'est', isCorrect: false }
    ],
    correctAnswer: 'suis',
    explanation: 'Avec je, on dit je suis.',
    hint: 'Pense à : je suis.',
    tags: ['ce2','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-103',
    subject: 'francais',
    title: 'Avoir au présent',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'verbe avoir au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Tu ___ toujours de bonnes idées pour les jeux.',
    options: [
      { id: 'a', text: 'as', isCorrect: true },
      { id: 'b', text: 'a', isCorrect: false },
      { id: 'c', text: 'ai', isCorrect: false }
    ],
    correctAnswer: 'as',
    explanation: 'Avec "tu", le verbe avoir s’écrit "as". "a" s’utilise avec "il/elle", "ai" avec "je".',
    hint: 'Avec "tu", quelle terminaison prend le verbe avoir ?',
    tags: ['ce2','conjugaison','avoir','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-104',
    subject: 'francais',
    title: 'Aller au présent',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe aller au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Ils ___ à l’école.',
    options: [
      { id: 'a', text: 'vont', isCorrect: true },
      { id: 'b', text: 'vais', isCorrect: false },
      { id: 'c', text: 'allez', isCorrect: false }
    ],
    correctAnswer: 'vont',
    explanation: 'Avec ils, on dit ils vont.',
    hint: 'Pense à : ils vont.',
    tags: ['ce2','conjugaison','aller','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-105',
    subject: 'francais',
    title: 'Présent 1er groupe 2',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Vous ___ rapidement.',
    options: [
      { id: 'a', text: 'avancez', isCorrect: true },
      { id: 'b', text: 'avance', isCorrect: false },
      { id: 'c', text: 'avançons', isCorrect: false }
    ],
    correctAnswer: 'avancez',
    explanation: 'Avec vous, on dit vous avancez.',
    hint: 'Pense à : vous avancez.',
    tags: ['ce2','conjugaison','present','1er-groupe','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-106',
    subject: 'francais',
    title: 'Être avec nous',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ en avance.',
    options: [
      { id: 'a', text: 'sommes', isCorrect: true },
      { id: 'b', text: 'êtes', isCorrect: false },
      { id: 'c', text: 'sont', isCorrect: false }
    ],
    correctAnswer: 'sommes',
    explanation: 'Avec nous, on dit nous sommes.',
    hint: 'Pense à : nous sommes.',
    tags: ['ce2','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-107',
    subject: 'francais',
    title: 'Avoir avec ils',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe avoir au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Après leur longue randonnée, les deux amis ___ très faim et soif.',
    options: [
      { id: 'a', text: 'ont', isCorrect: true },
      { id: 'b', text: 'avons', isCorrect: false },
      { id: 'c', text: 'avez', isCorrect: false }
    ],
    correctAnswer: 'ont',
    explanation: '"Les deux amis" = ils. Avec ils, le verbe avoir s’écrit "ont". "avons" s’utilise avec "nous", "avez" avec "vous".',
    hint: 'Quel pronom peut remplacer "les deux amis" ?',
    tags: ['ce2','conjugaison','avoir','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-108',
    subject: 'francais',
    title: 'Aller avec nous',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe aller au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ au musée.',
    options: [
      { id: 'a', text: 'allons', isCorrect: true },
      { id: 'b', text: 'allez', isCorrect: false },
      { id: 'c', text: 'va', isCorrect: false }
    ],
    correctAnswer: 'allons',
    explanation: 'Avec nous, on dit nous allons.',
    hint: 'Pense à : nous allons.',
    tags: ['ce2','conjugaison','aller','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-109',
    subject: 'francais',
    title: 'Imparfait simple',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'conjugaison',
    subskill: 'imparfait',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Hier, nous ___ dans le jardin.',
    options: [
      { id: 'a', text: 'jouions', isCorrect: true },
      { id: 'b', text: 'jouons', isCorrect: false },
      { id: 'c', text: 'jouerez', isCorrect: false }
    ],
    correctAnswer: 'jouions',
    explanation: 'À l’imparfait avec nous, on écrit jouions.',
    hint: 'Regarde le mot hier.',
    tags: ['ce2','conjugaison','imparfait','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-110',
    subject: 'francais',
    title: 'Futur simple',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'conjugaison',
    subskill: 'futur simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Demain, ils ___ au parc.',
    options: [
      { id: 'a', text: 'iront', isCorrect: true },
      { id: 'b', text: 'vont', isCorrect: false },
      { id: 'c', text: 'allaient', isCorrect: false }
    ],
    correctAnswer: 'iront',
    explanation: 'Au futur simple, avec ils, on écrit iront.',
    hint: 'Regarde le mot demain.',
    tags: ['ce2','conjugaison','futur','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-111',
    subject: 'francais',
    title: 'Présent 1er groupe 3',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Tu ___ un dessin.',
    options: [
      { id: 'a', text: 'termines', isCorrect: true },
      { id: 'b', text: 'termine', isCorrect: false },
      { id: 'c', text: 'terminons', isCorrect: false }
    ],
    correctAnswer: 'termines',
    explanation: 'Avec tu, on dit tu termines.',
    hint: 'Pense à : tu termines.',
    tags: ['ce2','conjugaison','present','1er-groupe','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-112',
    subject: 'francais',
    title: 'Être avec vous',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Vous ___ prêts.',
    options: [
      { id: 'a', text: 'êtes', isCorrect: true },
      { id: 'b', text: 'sommes', isCorrect: false },
      { id: 'c', text: 'sont', isCorrect: false }
    ],
    correctAnswer: 'êtes',
    explanation: 'Avec vous, on dit vous êtes.',
    hint: 'Pense à : vous êtes.',
    tags: ['ce2','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-113',
    subject: 'francais',
    title: 'Avoir avec nous',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe avoir au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ une nouvelle règle.',
    options: [
      { id: 'a', text: 'avons', isCorrect: true },
      { id: 'b', text: 'avez', isCorrect: false },
      { id: 'c', text: 'ont', isCorrect: false }
    ],
    correctAnswer: 'avons',
    explanation: 'Avec nous, on dit nous avons.',
    hint: 'Pense à : nous avons.',
    tags: ['ce2','conjugaison','avoir','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-114',
    subject: 'francais',
    title: 'Aller avec je',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe aller au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Je ___ chez mamie.',
    options: [
      { id: 'a', text: 'vais', isCorrect: true },
      { id: 'b', text: 'va', isCorrect: false },
      { id: 'c', text: 'allons', isCorrect: false }
    ],
    correctAnswer: 'vais',
    explanation: 'Avec je, on dit je vais.',
    hint: 'Pense à : je vais.',
    tags: ['ce2','conjugaison','aller','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-115',
    subject: 'francais',
    title: 'Imparfait 2',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'conjugaison',
    subskill: 'imparfait',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Avant, il ___ plus lentement.',
    options: [
      { id: 'a', text: 'courait', isCorrect: true },
      { id: 'b', text: 'court', isCorrect: false },
      { id: 'c', text: 'courra', isCorrect: false }
    ],
    correctAnswer: 'courait',
    explanation: 'À l’imparfait, on écrit courait.',
    hint: 'Le mot avant aide.',
    tags: ['ce2','conjugaison','imparfait','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce2-conjugaison-116',
    subject: 'francais',
    title: 'Futur 2',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'conjugaison',
    subskill: 'futur simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Bientôt, nous ___ en vacances.',
    options: [
      { id: 'a', text: 'serons', isCorrect: true },
      { id: 'b', text: 'sommes', isCorrect: false },
      { id: 'c', text: 'étions', isCorrect: false }
    ],
    correctAnswer: 'serons',
    explanation: 'Au futur simple, avec nous, on écrit serons.',
    hint: 'Le mot bientôt indique le futur.',
    tags: ['ce2','conjugaison','futur','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:conjugaison',
  },
];
