import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe2LectureExercises: FrenchExercise[] = [
  {
    id: 'fr-ce2-lecture-101',
    subject: 'francais',
    title: 'Combiner deux informations',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Avant de partir à l’école, Léa glisse ses cahiers et sa trousse dans son sac. Elle n’oublie rien. Que met Léa dans son sac ?',
    options: [
      { id: 'a', text: 'Ses cahiers et son goûter', isCorrect: false },
      { id: 'b', text: 'Ses cahiers et sa trousse', isCorrect: true },
      { id: 'c', text: 'Sa trousse et son manteau', isCorrect: false }
    ],
    correctAnswer: 'Ses cahiers et sa trousse',
    explanation: 'La phrase mentionne les cahiers ET la trousse. Les deux éléments sont nécessaires pour répondre correctement.',
    hint: 'Combien d’objets sont cités dans la phrase ?',
    tags: ['ce2','lecture','comprehension','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-102',
    subject: 'francais',
    title: 'Repérer le lieu parmi plusieurs',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Dans sa chambre, Milo a une table, un canapé et un tapis. Il cherche une bonne cachette pour sa bille préférée et la glisse sous un objet. Où l’a-t-il cachée ?',
    options: [
      { id: 'a', text: 'Sous la table', isCorrect: false },
      { id: 'b', text: 'Sous le canapé', isCorrect: true },
      { id: 'c', text: 'Sous le tapis', isCorrect: false }
    ],
    correctAnswer: 'Sous le canapé',
    explanation: 'Milo cache sa bille sous le canapé, pas sous la table ni sous le tapis, même si les deux sont présents dans la chambre.',
    hint: 'Plusieurs cachettes sont mentionnées : lis attentivement.',
    tags: ['ce2','lecture','lieu','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-103',
    subject: 'francais',
    title: 'Comprendre une cause par indice',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Avant de sortir, Nina jette un coup d’œil au thermomètre accroché près de la porte. Elle attrape aussitôt son manteau. Pourquoi prend-elle son manteau ?',
    options: [
      { id: 'a', text: 'Parce qu’il pleut', isCorrect: false },
      { id: 'b', text: 'Parce qu’il fait froid', isCorrect: true },
      { id: 'c', text: 'Parce qu’il y a du vent', isCorrect: false }
    ],
    correctAnswer: 'Parce qu’il fait froid',
    explanation: 'Un thermomètre indique la température. Nina voit qu’il fait froid et prend son manteau.',
    hint: 'À quoi sert un thermomètre ?',
    tags: ['ce2','lecture','cause','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-104',
    subject: 'francais',
    title: 'Petite inférence',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'inference simple',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Paul prend un parapluie avant de sortir. Quel temps fait-il sûrement ?',
    options: [
      { id: 'a', text: 'Il pleut', isCorrect: true },
      { id: 'b', text: 'Il neige dans la cuisine', isCorrect: false },
      { id: 'c', text: 'Il fait très chaud', isCorrect: false }
    ],
    correctAnswer: 'Il pleut',
    explanation: 'On prend souvent un parapluie quand il pleut.',
    hint: 'Pense à l’objet.',
    tags: ['ce2','lecture','inference','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-105',
    subject: 'francais',
    title: 'Identifier le bon personnage',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du sujet',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Dans le jardin, le jardinier taille les branches basses pendant que son fils ramasse les feuilles tombées. Qui coupe les branches ?',
    options: [
      { id: 'a', text: 'Son fils', isCorrect: false },
      { id: 'b', text: 'Le jardinier', isCorrect: true },
      { id: 'c', text: 'La voisine', isCorrect: false }
    ],
    correctAnswer: 'Le jardinier',
    explanation: 'C’est le jardinier qui taille les branches. Son fils, lui, ramasse les feuilles.',
    hint: 'Deux personnes agissent : que fait chacun ?',
    tags: ['ce2','lecture','sujet','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-106',
    subject: 'francais',
    title: 'Comprendre un enchaînement',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Inès rentre de l’école, mange vite son goûter, puis sort ses cahiers. Que fait-elle juste après le goûter ?',
    options: [
      { id: 'a', text: 'Elle va jouer dehors', isCorrect: false },
      { id: 'b', text: 'Elle sort ses cahiers', isCorrect: true },
      { id: 'c', text: 'Elle prend le bus', isCorrect: false }
    ],
    correctAnswer: 'Elle sort ses cahiers',
    explanation: 'Après avoir mangé son goûter, Inès sort ses cahiers pour faire ses devoirs.',
    hint: 'Lis les trois actions dans l’ordre : que vient juste après le goûter ?',
    tags: ['ce2','lecture','ordre','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-107',
    subject: 'francais',
    title: 'Reformuler une phrase',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'association de sens',
    format: 'qcm',
    instructions: 'Choisis la phrase qui dit la même chose.',
    prompt: 'Le chat s’endort lentement près de la fenêtre chauffée par le soleil.',
    options: [
      { id: 'a', text: 'Le chat joue près de la fenêtre', isCorrect: false },
      { id: 'b', text: 'Le chat se repose dans un endroit chaud', isCorrect: true },
      { id: 'c', text: 'Le soleil réchauffe la fenêtre pour le chat', isCorrect: false }
    ],
    correctAnswer: 'Le chat se repose dans un endroit chaud',
    explanation: '"S’endort" = se repose. "Fenêtre chauffée par le soleil" = endroit chaud. Il faut reformuler, pas recopier.',
    hint: 'Cherche un autre mot pour "s’endort" et pour "chauffée par le soleil".',
    tags: ['ce2','lecture','association','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-108',
    subject: 'francais',
    title: 'Comprendre un petit texte',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Zoé a perdu sa clé. Elle cherche partout dans sa chambre. Que cherche Zoé ?',
    options: [
      { id: 'a', text: 'Son cartable', isCorrect: false },
      { id: 'b', text: 'Sa clé', isCorrect: true },
      { id: 'c', text: 'Son portable', isCorrect: false }
    ],
    correctAnswer: 'Sa clé',
    explanation: 'Zoé cherche ce qu’elle a perdu : sa clé. Son cartable et son portable ne sont pas mentionnés.',
    hint: 'Qu’a-t-elle perdu au tout début du texte ?',
    tags: ['ce2','lecture','petit-texte','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-109',
    subject: 'francais',
    title: 'Petite inférence 2',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'inference simple',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le four sonne et papa met des gants épais. Que va-t-il sortir ?',
    options: [
      { id: 'a', text: 'Un plat chaud', isCorrect: true },
      { id: 'b', text: 'Un ballon mouillé', isCorrect: false },
      { id: 'c', text: 'Un manteau propre', isCorrect: false }
    ],
    correctAnswer: 'Un plat chaud',
    explanation: 'Les gants servent à sortir quelque chose de chaud du four.',
    hint: 'Observe les indices.',
    tags: ['ce2','lecture','inference','maison','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-110',
    subject: 'francais',
    title: 'Comprendre une action par ses effets',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Emma s’approche du tableau avec son éponge mouillée. Quelques secondes plus tard, toutes les lettres ont disparu. Qu’a fait Emma ?',
    options: [
      { id: 'a', text: 'Elle a dessiné sur le tableau', isCorrect: false },
      { id: 'b', text: 'Elle a effacé le tableau', isCorrect: true },
      { id: 'c', text: 'Elle a lavé l’éponge', isCorrect: false }
    ],
    correctAnswer: 'Elle a effacé le tableau',
    explanation: 'Avec son éponge, Emma a effacé les lettres. Le résultat : les lettres ont disparu.',
    hint: 'Qu’arrive-t-il aux lettres ? Quel outil utilise Emma ?',
    tags: ['ce2','lecture','action','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-111',
    subject: 'francais',
    title: 'Identifier un objet par sa description',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Dans le jardin, Noé essaie de gonfler quelque chose de rouge et tout rond. Quand c’est prêt, il va pouvoir jouer. Que gonfle Noé ?',
    options: [
      { id: 'a', text: 'Un matelas gonflable', isCorrect: false },
      { id: 'b', text: 'Un ballon', isCorrect: true },
      { id: 'c', text: 'Un pneu de vélo', isCorrect: false }
    ],
    correctAnswer: 'Un ballon',
    explanation: 'Un objet rouge, tout rond, que l’on gonfle pour jouer dans le jardin : c’est un ballon.',
    hint: 'Quelle forme est décrite ? À quoi sert cet objet ?',
    tags: ['ce2','lecture','objet','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-112',
    subject: 'francais',
    title: 'Comprendre une intention',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Après le dîner, Lila ouvre un livre pour lire. Elle allume la lampe de son bureau avant de commencer. Pourquoi allume-t-elle la lampe ?',
    options: [
      { id: 'a', text: 'Pour avoir suffisamment de lumière pour lire', isCorrect: true },
      { id: 'b', text: 'Pour appeler sa maman', isCorrect: false },
      { id: 'c', text: 'Pour voir s’il pleut dehors', isCorrect: false }
    ],
    correctAnswer: 'Pour avoir suffisamment de lumière pour lire',
    explanation: 'Lila veut lire, donc elle allume la lampe pour avoir assez de lumière.',
    hint: 'Que va-t-elle faire juste après avoir allumé la lampe ?',
    tags: ['ce2','lecture','cause','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-113',
    subject: 'francais',
    title: 'Inférer un lieu',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'inference simple',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Les élèves de CE2 préparent le spectacle de fin d’année. Ce matin, ils répètent leur chant avec leur maîtresse de musique. Où sont-ils probablement ?',
    options: [
      { id: 'a', text: 'Dans la cantine', isCorrect: false },
      { id: 'b', text: 'Dans la cour de récréation', isCorrect: false },
      { id: 'c', text: 'Dans la salle de musique', isCorrect: true }
    ],
    correctAnswer: 'Dans la salle de musique',
    explanation: 'Pour répéter un chant avec une maîtresse de musique, on va dans la salle de musique. C’est logique même si ce n’est pas dit directement.',
    hint: 'Quel endroit à l’école est fait pour la musique ?',
    tags: ['ce2','lecture','inference','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-114',
    subject: 'francais',
    title: 'Petit raisonnement logique',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'inference simple',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Maman ouvre grand les fenêtres après avoir cuisiné du poisson. Pourquoi les ouvre-t-elle sûrement ?',
    options: [
      { id: 'a', text: 'Pour faire partir l’odeur', isCorrect: true },
      { id: 'b', text: 'Pour ranger ses chaussures', isCorrect: false },
      { id: 'c', text: 'Pour écrire au tableau', isCorrect: false }
    ],
    correctAnswer: 'Pour faire partir l’odeur',
    explanation: 'On ouvre souvent les fenêtres pour aérer.',
    hint: 'Pense à ce que l’on fait après avoir cuisiné.',
    tags: ['ce2','lecture','inference','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-115',
    subject: 'francais',
    title: 'Associer phrase équivalente',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'association de sens',
    format: 'qcm',
    instructions: 'Choisis la phrase équivalente.',
    prompt: 'Le facteur dépose le courrier dans la boîte.',
    options: [
      { id: 'a', text: 'Le facteur met le courrier dans la boîte', isCorrect: true },
      { id: 'b', text: 'Le facteur lit le courrier dans le salon', isCorrect: false },
      { id: 'c', text: 'Le facteur emporte le courrier avec lui', isCorrect: false }
    ],
    correctAnswer: 'Le facteur met le courrier dans la boîte',
    explanation: '"Déposer dans la boîte" veut dire y mettre quelque chose. Les deux autres phrases changent complètement l’action.',
    hint: 'Cherche un synonyme du verbe "déposer".',
    tags: ['ce2','lecture','association','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-116',
    subject: 'francais',
    title: 'Comprendre un déroulement',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Avant d’aller dormir, Hugo brosse ses dents puis lit une histoire. Que fait-il juste après avoir brossé ses dents ?',
    options: [
      { id: 'a', text: 'Il lit une histoire', isCorrect: true },
      { id: 'b', text: 'Il prend le bus', isCorrect: false },
      { id: 'c', text: 'Il fait du vélo', isCorrect: false }
    ],
    correctAnswer: 'Il lit une histoire',
    explanation: 'L’ordre des actions est donné dans la phrase.',
    hint: 'Observe ce qui vient après puis.',
    tags: ['ce2','lecture','ordre','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-117',
    subject: 'francais',
    title: 'Comprendre une indication de temps indirecte',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Les voisins ont sorti leurs guirlandes et commencé à décorer leur jardin dès que le soleil s’est couché. À quel moment décorent-ils leur jardin ?',
    options: [
      { id: 'a', text: 'Le matin', isCorrect: false },
      { id: 'b', text: 'L’après-midi', isCorrect: false },
      { id: 'c', text: 'Le soir', isCorrect: true }
    ],
    correctAnswer: 'Le soir',
    explanation: '"Le soleil s’est couché" signifie que la nuit tombe, donc c’est le soir.',
    hint: 'Que se passe-t-il quand le soleil se couche ?',
    tags: ['ce2','lecture','temps','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-118',
    subject: 'francais',
    title: 'Comprendre un comportement',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le chat est devant la porte fermée. Il miaule sans s’arrêter en regardant vers l’intérieur. Que veut-il probablement ?',
    options: [
      { id: 'a', text: 'Manger sa gamelle', isCorrect: false },
      { id: 'b', text: 'Rentrer dans la maison', isCorrect: true },
      { id: 'c', text: 'Jouer avec une balle', isCorrect: false }
    ],
    correctAnswer: 'Rentrer dans la maison',
    explanation: 'Le chat regarde vers l’intérieur et miaule devant la porte fermée : il veut entrer dans la maison.',
    hint: 'Vers quoi regarde le chat ? Qu’est-ce qui est fermé ?',
    tags: ['ce2','lecture','petit-texte','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-119',
    subject: 'francais',
    title: 'Inférence école',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'inference simple',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'La cloche sonne et les élèves rangent vite leurs affaires. Que va-t-il se passer ?',
    options: [
      { id: 'a', text: 'La classe va se terminer', isCorrect: true },
      { id: 'b', text: 'Le repas va cuire', isCorrect: false },
      { id: 'c', text: 'La nuit va tomber', isCorrect: false }
    ],
    correctAnswer: 'La classe va se terminer',
    explanation: 'La cloche et le rangement annoncent souvent la fin de la classe.',
    hint: 'Observe les indices.',
    tags: ['ce2','lecture','inference','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce2-lecture-120',
    subject: 'francais',
    title: 'Inférer un lieu depuis une intention',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'inference simple',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Sami est fier de son dessin. Il veut que tous ses camarades puissent le voir. Il prend du scotch et le colle en hauteur. Où Sami a-t-il collé son dessin ?',
    options: [
      { id: 'a', text: 'Dans son cahier', isCorrect: false },
      { id: 'b', text: 'Sur son bureau', isCorrect: false },
      { id: 'c', text: 'Sur le mur de la classe', isCorrect: true }
    ],
    correctAnswer: 'Sur le mur de la classe',
    explanation: 'Pour que tous les camarades voient le dessin, il faut le coller en hauteur dans la classe, sur le mur.',
    hint: 'Où faut-il mettre quelque chose pour que tout le monde le voie en classe ?',
    tags: ['ce2','lecture','lieu','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },
];
