import { cloneDefaultAdaptations } from '../../core/exercise-core.adaptations';
import type { ScienceExercise } from './science.types';

export const scienceExercises: ScienceExercise[] = [

  // ══════════════════════════════════════════════════════════════════
  // CP — 12 exercices
  // vivant : animaux (3) + vivant_non_vivant (3)
  // corps : reconnaissance simple (3)
  // environnement : météo (3)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'sc-cp-viv-001',
    subject: 'sciences',
    title: 'Animal aquatique',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Parmi ces animaux, lequel vit dans l\'eau ?',
    options: [
      { id: 'a', text: 'Le chien', isCorrect: false },
      { id: 'b', text: 'Le poisson', isCorrect: true },
      { id: 'c', text: 'Le lapin', isCorrect: false },
    ],
    correctAnswer: 'Le poisson',
    explanation: 'Le poisson vit dans l\'eau. Le chien et le lapin vivent sur la terre.',
    hint: 'Pense à l\'animal qu\'on trouve dans un aquarium.',
    tags: ['cp', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-002',
    subject: 'sciences',
    title: 'Animal qui pond des œufs',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal pond des œufs ?',
    options: [
      { id: 'a', text: 'La vache', isCorrect: false },
      { id: 'b', text: 'La poule', isCorrect: true },
      { id: 'c', text: 'La chatte', isCorrect: false },
    ],
    correctAnswer: 'La poule',
    explanation: 'La poule pond des œufs. La vache et la chatte donnent naissance à des petits vivants.',
    hint: 'On trouve ses œufs dans les rayons du supermarché.',
    tags: ['cp', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-003',
    subject: 'sciences',
    title: 'Animal avec des ailes',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal a des ailes et peut voler ?',
    options: [
      { id: 'a', text: 'Le cochon', isCorrect: false },
      { id: 'b', text: 'L\'oiseau', isCorrect: true },
      { id: 'c', text: 'La vache', isCorrect: false },
    ],
    correctAnswer: 'L\'oiseau',
    explanation: 'L\'oiseau a des ailes et peut voler. Les autres animaux cités n\'ont pas d\'ailes.',
    hint: 'Cet animal chante dans les arbres.',
    tags: ['cp', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-004',
    subject: 'sciences',
    title: 'Vivant : arbre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces objets est vivant ?',
    options: [
      { id: 'a', text: 'Une pierre', isCorrect: false },
      { id: 'b', text: 'Un arbre', isCorrect: true },
      { id: 'c', text: 'Une chaise', isCorrect: false },
    ],
    correctAnswer: 'Un arbre',
    explanation: 'Un arbre est vivant : il grandit, se nourrit et se reproduit. Une pierre et une chaise ne sont pas vivantes.',
    hint: 'Cet être pousse, a des feuilles et peut donner des fruits.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-005',
    subject: 'sciences',
    title: 'Non vivant : table',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel n\'est PAS vivant ?',
    options: [
      { id: 'a', text: 'Un chien', isCorrect: false },
      { id: 'b', text: 'Une fleur', isCorrect: false },
      { id: 'c', text: 'Une table', isCorrect: true },
    ],
    correctAnswer: 'Une table',
    explanation: 'Une table n\'est pas vivante : elle ne grandit pas, ne mange pas, ne respire pas.',
    hint: 'Cet objet a été fabriqué par l\'homme.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-006',
    subject: 'sciences',
    title: 'Vivant : chien',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui est vivant ?',
    options: [
      { id: 'a', text: 'Un caillou', isCorrect: false },
      { id: 'b', text: 'Une voiture', isCorrect: false },
      { id: 'c', text: 'Un chien', isCorrect: true },
    ],
    correctAnswer: 'Un chien',
    explanation: 'Un chien est vivant : il respire, mange, bouge et grandit.',
    hint: 'Cet être a besoin de manger et de boire pour vivre.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-001',
    subject: 'sciences',
    title: 'Corps : yeux',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps sert à voir ?',
    options: [
      { id: 'a', text: 'Le nez', isCorrect: false },
      { id: 'b', text: 'Les yeux', isCorrect: true },
      { id: 'c', text: 'Les oreilles', isCorrect: false },
    ],
    correctAnswer: 'Les yeux',
    explanation: 'On utilise les yeux pour voir. Le nez sert à sentir et les oreilles à entendre.',
    hint: 'On les ferme pour dormir.',
    tags: ['cp', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-002',
    subject: 'sciences',
    title: 'Corps : oreilles',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps sert à entendre ?',
    options: [
      { id: 'a', text: 'Les yeux', isCorrect: false },
      { id: 'b', text: 'Les oreilles', isCorrect: true },
      { id: 'c', text: 'Le nez', isCorrect: false },
    ],
    correctAnswer: 'Les oreilles',
    explanation: 'On utilise les oreilles pour entendre les sons et la musique.',
    hint: 'On les utilise pour écouter la musique.',
    tags: ['cp', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-003',
    subject: 'sciences',
    title: 'Corps : nez',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps sert à sentir les odeurs ?',
    options: [
      { id: 'a', text: 'Le nez', isCorrect: true },
      { id: 'b', text: 'La bouche', isCorrect: false },
      { id: 'c', text: 'Les yeux', isCorrect: false },
    ],
    correctAnswer: 'Le nez',
    explanation: 'Le nez permet de sentir les odeurs. On dit qu\'on a un bon odorat.',
    hint: 'On l\'utilise aussi pour respirer.',
    tags: ['cp', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-001',
    subject: 'sciences',
    title: 'Météo : pluie',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand il pleut, quel objet utilise-t-on pour ne pas être mouillé ?',
    options: [
      { id: 'a', text: 'Un ballon', isCorrect: false },
      { id: 'b', text: 'Un parapluie', isCorrect: true },
      { id: 'c', text: 'Un chapeau de soleil', isCorrect: false },
    ],
    correctAnswer: 'Un parapluie',
    explanation: 'On ouvre un parapluie pour se protéger de la pluie.',
    hint: 'On l\'ouvre au-dessus de sa tête.',
    tags: ['cp', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-002',
    subject: 'sciences',
    title: 'Météo : orage',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel temps fait-il quand on voit des éclairs dans le ciel ?',
    options: [
      { id: 'a', text: 'Il neige', isCorrect: false },
      { id: 'b', text: 'Il y a un orage', isCorrect: true },
      { id: 'c', text: 'Il fait beau', isCorrect: false },
    ],
    correctAnswer: 'Il y a un orage',
    explanation: 'Les éclairs et le tonnerre apparaissent pendant un orage.',
    hint: 'On entend aussi du tonnerre.',
    tags: ['cp', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-003',
    subject: 'sciences',
    title: 'Saison : neige',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison tombe la neige en France ?',
    options: [
      { id: 'a', text: 'En été', isCorrect: false },
      { id: 'b', text: 'En automne', isCorrect: false },
      { id: 'c', text: 'En hiver', isCorrect: true },
    ],
    correctAnswer: 'En hiver',
    explanation: 'En hiver, il fait très froid et il peut neiger. En été il fait chaud.',
    hint: 'C\'est la saison la plus froide.',
    tags: ['cp', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

  // ══════════════════════════════════════════════════════════════════
  // CE1 — 13 exercices
  // vivant : animaux (3) + plantes (3)
  // corps : fonctions (3)
  // environnement : saisons (4)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'sc-ce1-viv-001',
    subject: 'sciences',
    title: 'Animal herbivore',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal mange uniquement des plantes ?',
    options: [
      { id: 'a', text: 'Le loup', isCorrect: false },
      { id: 'b', text: 'Le lapin', isCorrect: true },
      { id: 'c', text: 'Le requin', isCorrect: false },
    ],
    correctAnswer: 'Le lapin',
    explanation: 'Le lapin est herbivore : il mange de l\'herbe, des carottes et d\'autres plantes.',
    hint: 'Cet animal adore les carottes.',
    tags: ['ce1', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-002',
    subject: 'sciences',
    title: 'Animal producteur de lait',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal produit le lait qu\'on boit ?',
    options: [
      { id: 'a', text: 'Le poulet', isCorrect: false },
      { id: 'b', text: 'La vache', isCorrect: true },
      { id: 'c', text: 'Le cochon', isCorrect: false },
    ],
    correctAnswer: 'La vache',
    explanation: 'La vache produit du lait. C\'est un mammifère qui allaite ses petits.',
    hint: 'Cet animal mange de l\'herbe dans les prés.',
    tags: ['ce1', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-003',
    subject: 'sciences',
    title: 'Animal producteur de miel',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal produit du miel ?',
    options: [
      { id: 'a', text: 'La tortue', isCorrect: false },
      { id: 'b', text: 'Le cheval', isCorrect: false },
      { id: 'c', text: 'L\'abeille', isCorrect: true },
    ],
    correctAnswer: 'L\'abeille',
    explanation: 'Les abeilles récoltent le nectar des fleurs et le transforment en miel dans la ruche.',
    hint: 'Cet animal vit dans une ruche.',
    tags: ['ce1', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-004',
    subject: 'sciences',
    title: 'Plante : besoin de lumière',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi une plante a-t-elle besoin pour pousser ?',
    options: [
      { id: 'a', text: 'De sel et de sable', isCorrect: false },
      { id: 'b', text: 'De lumière et d\'eau', isCorrect: true },
      { id: 'c', text: 'De sucre et de lait', isCorrect: false },
    ],
    correctAnswer: 'De lumière et d\'eau',
    explanation: 'Les plantes ont besoin de lumière, d\'eau et de terre pour pousser et grandir.',
    hint: 'Tu as besoin de deux choses pour faire vivre une plante en pot.',
    tags: ['ce1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis ce dont la plante a besoin.', extraHint: 'Eau + soleil.' },
    }),
  },
  {
    id: 'sc-ce1-viv-005',
    subject: 'sciences',
    title: 'Plante : racines',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie de la plante est sous la terre et absorbe l\'eau ?',
    options: [
      { id: 'a', text: 'Les feuilles', isCorrect: false },
      { id: 'b', text: 'Les fleurs', isCorrect: false },
      { id: 'c', text: 'Les racines', isCorrect: true },
    ],
    correctAnswer: 'Les racines',
    explanation: 'Les racines sont sous la terre. Elles aspirent l\'eau et les sels minéraux du sol.',
    hint: 'C\'est la partie cachée sous la terre.',
    tags: ['ce1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-006',
    subject: 'sciences',
    title: 'Plante : feuilles',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi servent principalement les feuilles d\'une plante ?',
    options: [
      { id: 'a', text: 'À boire de l\'eau', isCorrect: false },
      { id: 'b', text: 'À capter la lumière du soleil', isCorrect: true },
      { id: 'c', text: 'À attirer les insectes', isCorrect: false },
    ],
    correctAnswer: 'À capter la lumière du soleil',
    explanation: 'Les feuilles captent la lumière du soleil pour fabriquer la nourriture de la plante.',
    hint: 'Elles sont larges et plates pour mieux capter quelque chose du ciel.',
    tags: ['ce1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-cor-001',
    subject: 'sciences',
    title: 'Corps : cœur',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert le cœur dans notre corps ?',
    options: [
      { id: 'a', text: 'À digérer les aliments', isCorrect: false },
      { id: 'b', text: 'À faire circuler le sang', isCorrect: true },
      { id: 'c', text: 'À respirer l\'air', isCorrect: false },
    ],
    correctAnswer: 'À faire circuler le sang',
    explanation: 'Le cœur est un muscle qui bat et envoie le sang dans tout le corps.',
    hint: 'On le sent battre quand on pose la main sur la poitrine.',
    tags: ['ce1', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-cor-002',
    subject: 'sciences',
    title: 'Corps : crâne',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps protège le cerveau ?',
    options: [
      { id: 'a', text: 'La peau', isCorrect: false },
      { id: 'b', text: 'Le crâne', isCorrect: true },
      { id: 'c', text: 'Le genou', isCorrect: false },
    ],
    correctAnswer: 'Le crâne',
    explanation: 'Le crâne est l\'os de la tête. Il protège le cerveau des chocs.',
    hint: 'C\'est l\'os qui forme la tête.',
    tags: ['ce1', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-cor-003',
    subject: 'sciences',
    title: 'Corps : poumons',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel organe sert à respirer l\'air ?',
    options: [
      { id: 'a', text: 'L\'estomac', isCorrect: false },
      { id: 'b', text: 'Les poumons', isCorrect: true },
      { id: 'c', text: 'Le foie', isCorrect: false },
    ],
    correctAnswer: 'Les poumons',
    explanation: 'Les poumons permettent de respirer. On inspire l\'air et on expire le dioxyde de carbone.',
    hint: 'Il y en a deux, un de chaque côté de la poitrine.',
    tags: ['ce1', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-001',
    subject: 'sciences',
    title: 'Saison : feuilles tombent',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison les feuilles des arbres tombent-elles ?',
    options: [
      { id: 'a', text: 'Au printemps', isCorrect: false },
      { id: 'b', text: 'En été', isCorrect: false },
      { id: 'c', text: 'En automne', isCorrect: true },
    ],
    correctAnswer: 'En automne',
    explanation: 'En automne, les feuilles jaunissent et tombent. C\'est la saison après l\'été.',
    hint: 'C\'est la saison entre l\'été et l\'hiver.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-002',
    subject: 'sciences',
    title: 'Saison : fleurs',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison les fleurs éclosent-elles et la nature se réveille-t-elle ?',
    options: [
      { id: 'a', text: 'En hiver', isCorrect: false },
      { id: 'b', text: 'Au printemps', isCorrect: true },
      { id: 'c', text: 'En automne', isCorrect: false },
    ],
    correctAnswer: 'Au printemps',
    explanation: 'Au printemps, les fleurs s\'épanouissent, les oiseaux reviennent et les journées rallongent.',
    hint: 'C\'est la saison après l\'hiver, quand il fait plus chaud.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-003',
    subject: 'sciences',
    title: 'Nombre de saisons',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien y a-t-il de saisons dans une année ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Il y a 4 saisons : le printemps, l\'été, l\'automne et l\'hiver.',
    hint: 'Compte : printemps, été, automne, hiver.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-004',
    subject: 'sciences',
    title: 'Saison la plus chaude',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la saison la plus chaude ?',
    options: [
      { id: 'a', text: 'L\'hiver', isCorrect: false },
      { id: 'b', text: 'L\'automne', isCorrect: false },
      { id: 'c', text: 'L\'été', isCorrect: true },
    ],
    correctAnswer: 'L\'été',
    explanation: 'L\'été est la saison la plus chaude. On va à la plage et les journées sont très longues.',
    hint: 'On part en vacances pendant cette saison.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

  // ══════════════════════════════════════════════════════════════════
  // CE2 — 13 exercices
  // vivant : besoins (4) + habitats (3)
  // environnement : eau (3) + saisons (3)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'sc-ce2-viv-001',
    subject: 'sciences',
    title: 'Besoins des vivants',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi les êtres vivants ont-ils besoin pour vivre ?',
    options: [
      { id: 'a', text: 'De sel et de sable', isCorrect: false },
      { id: 'b', text: 'De nourriture, d\'eau et d\'air', isCorrect: true },
      { id: 'c', text: 'De lumière seulement', isCorrect: false },
    ],
    correctAnswer: 'De nourriture, d\'eau et d\'air',
    explanation: 'Tous les êtres vivants (animaux, plantes, humains) ont besoin de nourriture, d\'eau et d\'air pour survivre.',
    hint: 'Pense à ce dont tu as besoin chaque jour.',
    tags: ['ce2', 'sciences', 'besoins', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis ce dont on a besoin pour vivre.', extraHint: 'Eau, nourriture, air.' },
    }),
  },
  {
    id: 'sc-ce2-viv-002',
    subject: 'sciences',
    title: 'Plante et lumière',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les plantes fabriquent leur nourriture grâce à... ?',
    options: [
      { id: 'a', text: 'La pluie', isCorrect: false },
      { id: 'b', text: 'La lumière du soleil', isCorrect: true },
      { id: 'c', text: 'La lune', isCorrect: false },
    ],
    correctAnswer: 'La lumière du soleil',
    explanation: 'Les plantes utilisent la lumière du soleil, l\'eau et le CO₂ pour fabriquer leur nourriture (c\'est la photosynthèse).',
    hint: 'Les feuilles captent quelque chose venant du ciel.',
    tags: ['ce2', 'sciences', 'besoins', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-viv-003',
    subject: 'sciences',
    title: 'Animal carnivore',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les animaux carnivores se nourrissent de... ?',
    options: [
      { id: 'a', text: 'Végétaux uniquement', isCorrect: false },
      { id: 'b', text: 'D\'autres animaux', isCorrect: true },
      { id: 'c', text: 'Champignons uniquement', isCorrect: false },
    ],
    correctAnswer: 'D\'autres animaux',
    explanation: 'Les carnivores (comme le lion ou le loup) mangent d\'autres animaux pour se nourrir.',
    hint: '« Carni » vient de chair (viande).',
    tags: ['ce2', 'sciences', 'besoins', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-viv-004',
    subject: 'sciences',
    title: 'Oxygène',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel gaz les animaux respirent-ils pour vivre ?',
    options: [
      { id: 'a', text: 'L\'azote', isCorrect: false },
      { id: 'b', text: 'L\'oxygène', isCorrect: true },
      { id: 'c', text: 'Le dioxyde de carbone', isCorrect: false },
    ],
    correctAnswer: 'L\'oxygène',
    explanation: 'Les animaux et les humains respirent de l\'oxygène. Ils rejettent du dioxyde de carbone.',
    hint: 'C\'est le gaz produit par les plantes.',
    tags: ['ce2', 'sciences', 'besoins', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis les 3 propositions.', 'Quel gaz se trouve dans l\'air ?', 'C\'est l\'oxygène.'] },
    }),
  },
  {
    id: 'sc-ce2-viv-005',
    subject: 'sciences',
    title: 'Habitat : abeilles',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où vivent les abeilles ?',
    options: [
      { id: 'a', text: 'Dans une niche', isCorrect: false },
      { id: 'b', text: 'Dans une ruche', isCorrect: true },
      { id: 'c', text: 'Dans un terrier', isCorrect: false },
    ],
    correctAnswer: 'Dans une ruche',
    explanation: 'Les abeilles vivent en groupe dans une ruche. Elles y stockent aussi leur miel.',
    hint: 'C\'est une sorte de maison en bois ou en paille.',
    tags: ['ce2', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-viv-006',
    subject: 'sciences',
    title: 'Habitat : nid d\'oiseau',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où les oiseaux font-ils généralement leur nid ?',
    options: [
      { id: 'a', text: 'Sous la terre', isCorrect: false },
      { id: 'b', text: 'Dans l\'eau', isCorrect: false },
      { id: 'c', text: 'Dans les arbres ou sur les toits', isCorrect: true },
    ],
    correctAnswer: 'Dans les arbres ou sur les toits',
    explanation: 'Les oiseaux construisent leur nid en hauteur, dans les arbres ou sur les bâtiments, pour protéger leurs œufs.',
    hint: 'Ils les construisent en hauteur pour se protéger des prédateurs.',
    tags: ['ce2', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-viv-007',
    subject: 'sciences',
    title: 'Habitat : terrier',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où vivent les lapins sauvages ?',
    options: [
      { id: 'a', text: 'Dans les arbres', isCorrect: false },
      { id: 'b', text: 'Dans les terriers', isCorrect: true },
      { id: 'c', text: 'Dans les lacs', isCorrect: false },
    ],
    correctAnswer: 'Dans les terriers',
    explanation: 'Les lapins sauvages creusent des terriers sous la terre pour s\'y abriter et élever leurs petits.',
    hint: 'C\'est un trou creusé dans la terre.',
    tags: ['ce2', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-001',
    subject: 'sciences',
    title: 'États de l\'eau',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sous combien de formes différentes l\'eau peut-elle exister ?',
    options: [
      { id: 'a', text: '1 (liquide seulement)', isCorrect: false },
      { id: 'b', text: '3 (liquide, solide, gazeuse)', isCorrect: true },
      { id: 'c', text: '2 (liquide et solide)', isCorrect: false },
    ],
    correctAnswer: '3 (liquide, solide, gazeuse)',
    explanation: 'L\'eau existe sous 3 formes : liquide (rivière), solide (glace) et gazeuse (vapeur).',
    hint: 'Pense à l\'eau du robinet, à la glace et à la vapeur d\'eau.',
    tags: ['ce2', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['L\'eau liquide : rivière.', 'L\'eau solide : glace.', 'L\'eau gazeuse : vapeur. → 3 formes.'] },
    }),
  },
  {
    id: 'sc-ce2-env-002',
    subject: 'sciences',
    title: 'Eau solide',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on l\'eau à l\'état solide ?',
    options: [
      { id: 'a', text: 'La vapeur', isCorrect: false },
      { id: 'b', text: 'La glace', isCorrect: true },
      { id: 'c', text: 'La buée', isCorrect: false },
    ],
    correctAnswer: 'La glace',
    explanation: 'Quand l\'eau gèle (en dessous de 0°C), elle devient de la glace, qui est solide.',
    hint: 'On en met dans les boissons fraîches.',
    tags: ['ce2', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-003',
    subject: 'sciences',
    title: 'Origine de la pluie',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où vient la pluie ?',
    options: [
      { id: 'a', text: 'Du vent', isCorrect: false },
      { id: 'b', text: 'Des nuages', isCorrect: true },
      { id: 'c', text: 'Des étoiles', isCorrect: false },
    ],
    correctAnswer: 'Des nuages',
    explanation: 'La pluie tombe des nuages. Les nuages sont formés de petites gouttes d\'eau.',
    hint: 'Regarde ce qui est dans le ciel quand il pleut.',
    tags: ['ce2', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-004',
    subject: 'sciences',
    title: 'Saison après l\'hiver',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle saison vient juste après l\'hiver ?',
    options: [
      { id: 'a', text: 'L\'automne', isCorrect: false },
      { id: 'b', text: 'L\'été', isCorrect: false },
      { id: 'c', text: 'Le printemps', isCorrect: true },
    ],
    correctAnswer: 'Le printemps',
    explanation: 'L\'ordre des saisons est : printemps → été → automne → hiver → printemps…',
    hint: 'C\'est la saison où la nature se réveille.',
    tags: ['ce2', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-005',
    subject: 'sciences',
    title: 'Hiver : phénomène naturel',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel phénomène naturel peut se produire en hiver ?',
    options: [
      { id: 'a', text: 'Les fleurs éclosent', isCorrect: false },
      { id: 'b', text: 'Il neige', isCorrect: true },
      { id: 'c', text: 'Les feuilles tombent', isCorrect: false },
    ],
    correctAnswer: 'Il neige',
    explanation: 'En hiver, il peut neiger car les températures sont très basses. Les feuilles tombent en automne, les fleurs éclosent au printemps.',
    hint: 'C\'est la saison la plus froide.',
    tags: ['ce2', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-006',
    subject: 'sciences',
    title: 'Saison la plus chaude',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison fait-il le plus chaud en France ?',
    options: [
      { id: 'a', text: 'Au printemps', isCorrect: false },
      { id: 'b', text: 'En été', isCorrect: true },
      { id: 'c', text: 'En hiver', isCorrect: false },
    ],
    correctAnswer: 'En été',
    explanation: 'En France, l\'été est la saison la plus chaude. Les journées sont longues et ensoleillées.',
    hint: 'C\'est quand on part en vacances à la mer.',
    tags: ['ce2', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

  // ══════════════════════════════════════════════════════════════════
  // CM1 — 12 exercices
  // vivant : plantes (3) + besoins corps (3)
  // environnement : habitats (3) + eau (3)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'sc-cm1-viv-001',
    subject: 'sciences',
    title: 'Fleur → fruit',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui se forme à partir d\'une fleur après la pollinisation ?',
    options: [
      { id: 'a', text: 'Une feuille', isCorrect: false },
      { id: 'b', text: 'Un fruit', isCorrect: true },
      { id: 'c', text: 'Une racine', isCorrect: false },
    ],
    correctAnswer: 'Un fruit',
    explanation: 'Quand une fleur est pollinisée (par les abeilles ou le vent), elle se transforme en fruit qui contient des graines.',
    hint: 'La pomme vient de la fleur du pommier.',
    tags: ['cm1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-viv-002',
    subject: 'sciences',
    title: 'Chlorophylle',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Grâce à quelle substance les feuilles des plantes sont-elles vertes ?',
    options: [
      { id: 'a', text: 'Le glucose', isCorrect: false },
      { id: 'b', text: 'La chlorophylle', isCorrect: true },
      { id: 'c', text: 'L\'oxygène', isCorrect: false },
    ],
    correctAnswer: 'La chlorophylle',
    explanation: 'La chlorophylle est le pigment vert des plantes. Elle capte la lumière du soleil pour fabriquer la nourriture de la plante.',
    hint: 'Ce mot commence par « chloro » qui veut dire vert en grec.',
    tags: ['cm1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Explique à l\'oral ce que fait la chlorophylle.' },
    }),
  },
  {
    id: 'sc-cm1-viv-003',
    subject: 'sciences',
    title: 'Reproduction des plantes',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment une plante se reproduit-elle le plus souvent ?',
    options: [
      { id: 'a', text: 'Par les feuilles', isCorrect: false },
      { id: 'b', text: 'Par les graines', isCorrect: true },
      { id: 'c', text: 'Par les branches', isCorrect: false },
    ],
    correctAnswer: 'Par les graines',
    explanation: 'La plupart des plantes se reproduisent grâce aux graines contenues dans les fruits.',
    hint: 'On les plante dans la terre pour faire pousser de nouvelles plantes.',
    tags: ['cm1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-viv-004',
    subject: 'sciences',
    title: 'Organe : poumons',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel organe permet aux mammifères de respirer ?',
    options: [
      { id: 'a', text: 'Le cœur', isCorrect: false },
      { id: 'b', text: 'Les poumons', isCorrect: true },
      { id: 'c', text: 'L\'estomac', isCorrect: false },
    ],
    correctAnswer: 'Les poumons',
    explanation: 'Les poumons permettent de respirer l\'oxygène de l\'air et de rejeter le dioxyde de carbone.',
    hint: 'On en a deux, un de chaque côté de la poitrine.',
    tags: ['cm1', 'sciences', 'besoins', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-viv-005',
    subject: 'sciences',
    title: 'Digestion',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel organe sert à digérer les aliments après l\'estomac ?',
    options: [
      { id: 'a', text: 'Le cerveau', isCorrect: false },
      { id: 'b', text: 'Les intestins', isCorrect: true },
      { id: 'c', text: 'Les poumons', isCorrect: false },
    ],
    correctAnswer: 'Les intestins',
    explanation: 'Les aliments passent de l\'estomac aux intestins, qui absorbent les nutriments dont le corps a besoin.',
    hint: 'Ils viennent juste après l\'estomac.',
    tags: ['cm1', 'sciences', 'besoins', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['La bouche mâche.', 'L\'estomac digère.', 'Quel organe vient ensuite ?'] },
    }),
  },
  {
    id: 'sc-cm1-viv-006',
    subject: 'sciences',
    title: 'Nourriture des plantes',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi les plantes se nourrissent-elles ?',
    options: [
      { id: 'a', text: 'De lait et de sucre', isCorrect: false },
      { id: 'b', text: 'De minéraux du sol et de lumière', isCorrect: true },
      { id: 'c', text: 'D\'insectes', isCorrect: false },
    ],
    correctAnswer: 'De minéraux du sol et de lumière',
    explanation: 'Les plantes absorbent les minéraux du sol par leurs racines et utilisent la lumière pour fabriquer leur nourriture.',
    hint: 'Elles utilisent leurs racines ET leurs feuilles.',
    tags: ['cm1', 'sciences', 'besoins', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-001',
    subject: 'sciences',
    title: 'Habitat : ours polaire',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est l\'habitat naturel d\'un ours polaire ?',
    options: [
      { id: 'a', text: 'La savane africaine', isCorrect: false },
      { id: 'b', text: 'Les régions polaires enneigées', isCorrect: true },
      { id: 'c', text: 'La forêt tropicale', isCorrect: false },
    ],
    correctAnswer: 'Les régions polaires enneigées',
    explanation: 'L\'ours polaire est adapté au froid extrême des régions arctiques, recouvertes de glace et de neige.',
    hint: 'Cet animal est blanc comme la neige.',
    tags: ['cm1', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-002',
    subject: 'sciences',
    title: 'Amphibien',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal peut vivre à la fois dans l\'eau et sur la terre ?',
    options: [
      { id: 'a', text: 'Le lézard', isCorrect: false },
      { id: 'b', text: 'La grenouille', isCorrect: true },
      { id: 'c', text: 'Le dauphin', isCorrect: false },
    ],
    correctAnswer: 'La grenouille',
    explanation: 'La grenouille est un amphibien : elle vit dans l\'eau (têtard) et sur la terre (adulte).',
    hint: 'Cet animal commence sa vie dans l\'eau et la finit sur terre.',
    tags: ['cm1', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-003',
    subject: 'sciences',
    title: 'Hibernation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que font certains animaux comme l\'ours ou la marmotte pendant l\'hiver ?',
    options: [
      { id: 'a', text: 'Ils migrent vers le sud', isCorrect: false },
      { id: 'b', text: 'Ils hibernent', isCorrect: true },
      { id: 'c', text: 'Ils changent de couleur', isCorrect: false },
    ],
    correctAnswer: 'Ils hibernent',
    explanation: 'Certains animaux hibernent en hiver : ils dorment profondément pour économiser leur énergie quand la nourriture est rare.',
    hint: 'Ils passent tout l\'hiver à dormir.',
    tags: ['cm1', 'sciences', 'habitats', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-004',
    subject: 'sciences',
    title: 'Évaporation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le passage de l\'eau liquide à l\'état de vapeur ?',
    options: [
      { id: 'a', text: 'La condensation', isCorrect: false },
      { id: 'b', text: 'L\'évaporation', isCorrect: true },
      { id: 'c', text: 'La congélation', isCorrect: false },
    ],
    correctAnswer: 'L\'évaporation',
    explanation: 'L\'évaporation, c\'est quand l\'eau liquide se transforme en vapeur sous l\'effet de la chaleur.',
    hint: 'C\'est ce qui se passe quand une flaque d\'eau disparaît par temps chaud.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Explique ce que signifie « condensation ».' },
    }),
  },
  {
    id: 'sc-cm1-env-005',
    subject: 'sciences',
    title: 'Eau douce',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où vient l\'eau douce des rivières et des lacs ?',
    options: [
      { id: 'a', text: 'De la mer', isCorrect: false },
      { id: 'b', text: 'Des pluies et de la fonte des neiges', isCorrect: true },
      { id: 'c', text: 'Du sol directement', isCorrect: false },
    ],
    correctAnswer: 'Des pluies et de la fonte des neiges',
    explanation: 'Les rivières sont alimentées par les pluies et par l\'eau des neiges qui fondent en montagne.',
    hint: 'Pense à ce qui tombe du ciel et à ce qui fond au printemps.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-006',
    subject: 'sciences',
    title: 'Eau sur Terre',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle proportion de la surface de la Terre est recouverte par les océans ?',
    options: [
      { id: 'a', text: 'Environ un tiers', isCorrect: false },
      { id: 'b', text: 'Environ deux tiers', isCorrect: true },
      { id: 'c', text: 'Presque tout', isCorrect: false },
    ],
    correctAnswer: 'Environ deux tiers',
    explanation: 'Les océans recouvrent environ 71 % de la Terre, c\'est pourquoi on l\'appelle la « planète bleue ».',
    hint: 'La Terre est surnommée la planète bleue.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

  // ══════════════════════════════════════════════════════════════════
  // CM2 — 10 exercices de compréhension
  // vivant (3) + corps (3) + environnement (4)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'sc-cm2-com-001',
    subject: 'sciences',
    title: 'Compréhension : métamorphose',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« La chenille se transforme en papillon. Ce processus s\'appelle une métamorphose. » — Que devient une chenille ?',
    options: [
      { id: 'a', text: 'Un ver', isCorrect: false },
      { id: 'b', text: 'Un papillon', isCorrect: true },
      { id: 'c', text: 'Une abeille', isCorrect: false },
    ],
    correctAnswer: 'Un papillon',
    explanation: 'La chenille se transforme en papillon : c\'est ce qu\'on appelle une métamorphose.',
    hint: '« Métamorphose » veut dire transformation.',
    tags: ['cm2', 'sciences', 'animaux', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Lis la 1ʳᵉ phrase.', extraHint: 'La chenille devient un papillon.' },
    }),
  },
  {
    id: 'sc-cm2-com-002',
    subject: 'sciences',
    title: 'Compréhension : abeilles pollinisatrices',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Les abeilles récoltent le nectar des fleurs. En volant de fleur en fleur, elles transportent du pollen, ce qui aide les plantes à se reproduire. » — Quel service les abeilles rendent-elles aux plantes ?',
    options: [
      { id: 'a', text: 'Elles arrosent les plantes', isCorrect: false },
      { id: 'b', text: 'Elles aident les plantes à se reproduire', isCorrect: true },
      { id: 'c', text: 'Elles protègent les plantes des insectes', isCorrect: false },
    ],
    correctAnswer: 'Elles aident les plantes à se reproduire',
    explanation: 'En transportant le pollen, les abeilles permettent aux fleurs d\'être fécondées et de donner des fruits.',
    hint: 'Elles transportent du pollen d\'une fleur à l\'autre.',
    tags: ['cm2', 'sciences', 'animaux', 'plantes', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis la 2ᵉ phrase.', 'Que transportent les abeilles ?', 'À quoi cela sert-il ?'] },
    }),
  },
  {
    id: 'sc-cm2-com-003',
    subject: 'sciences',
    title: 'Compréhension : insectivore',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Un animal insectivore se nourrit d\'insectes. La hirondelle, par exemple, attrape des insectes en vol. » — Comment appelle-t-on un animal qui mange des insectes ?',
    options: [
      { id: 'a', text: 'Un herbivore', isCorrect: false },
      { id: 'b', text: 'Un carnivore', isCorrect: false },
      { id: 'c', text: 'Un insectivore', isCorrect: true },
    ],
    correctAnswer: 'Un insectivore',
    explanation: 'Le mot « insectivore » désigne un animal qui se nourrit d\'insectes.',
    hint: 'Le mot est directement dans le texte.',
    tags: ['cm2', 'sciences', 'besoins', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-004',
    subject: 'sciences',
    title: 'Compréhension : rôle du cœur',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Le cœur est un muscle qui bat environ 70 fois par minute. Il envoie le sang dans tout le corps. » — Quelle est la fonction principale du cœur ?',
    options: [
      { id: 'a', text: 'Digérer les aliments', isCorrect: false },
      { id: 'b', text: 'Faire circuler le sang dans le corps', isCorrect: true },
      { id: 'c', text: 'Filtrer l\'air respiré', isCorrect: false },
    ],
    correctAnswer: 'Faire circuler le sang dans le corps',
    explanation: 'Le cœur pompe le sang et le fait circuler dans tout le corps pour apporter de l\'oxygène aux organes.',
    hint: 'Le texte dit qu\'il envoie le sang dans tout le corps.',
    tags: ['cm2', 'sciences', 'corps', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-005',
    subject: 'sciences',
    title: 'Compréhension : digestion',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Quand on mange, les aliments passent dans la bouche, puis l\'estomac, puis les intestins. Ce trajet s\'appelle la digestion. » — Quel organe vient juste après l\'estomac ?',
    options: [
      { id: 'a', text: 'Le cœur', isCorrect: false },
      { id: 'b', text: 'Les intestins', isCorrect: true },
      { id: 'c', text: 'Les poumons', isCorrect: false },
    ],
    correctAnswer: 'Les intestins',
    explanation: 'Le trajet des aliments est : bouche → estomac → intestins.',
    hint: 'Le texte liste les organes dans l\'ordre.',
    tags: ['cm2', 'sciences', 'corps', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-006',
    subject: 'sciences',
    title: 'Compréhension : squelette',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Le squelette protège les organes du corps. Le crâne, par exemple, protège le cerveau. » — Que protège le crâne ?',
    options: [
      { id: 'a', text: 'Le cœur', isCorrect: false },
      { id: 'b', text: 'Le cerveau', isCorrect: true },
      { id: 'c', text: 'Les poumons', isCorrect: false },
    ],
    correctAnswer: 'Le cerveau',
    explanation: 'Le crâne est l\'os de la tête. Il protège le cerveau des chocs.',
    hint: 'Le texte le dit directement.',
    tags: ['cm2', 'sciences', 'corps', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm2-com-007',
    subject: 'sciences',
    title: 'Compréhension : eau et froid',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« L\'eau se transforme selon la température. Quand il fait très froid, elle se solidifie. Quand il fait très chaud, elle s\'évapore. » — Que se passe-t-il quand l\'eau se refroidit beaucoup ?',
    options: [
      { id: 'a', text: 'Elle disparaît', isCorrect: false },
      { id: 'b', text: 'Elle devient de la glace', isCorrect: true },
      { id: 'c', text: 'Elle devient de la vapeur', isCorrect: false },
    ],
    correctAnswer: 'Elle devient de la glace',
    explanation: 'Quand l\'eau se refroidit en dessous de 0°C, elle se solidifie et devient de la glace.',
    hint: '« Se solidifie » = devient solide = devient de la glace.',
    tags: ['cm2', 'sciences', 'eau', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Lis la 2ᵉ phrase.', extraHint: '« Se solidifie » = devient de la glace.' },
    }),
  },
  {
    id: 'sc-cm2-com-008',
    subject: 'sciences',
    title: 'Compréhension : cycle de l\'eau',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Le cycle de l\'eau comprend 3 étapes : l\'évaporation (l\'eau monte), la condensation (elle forme des nuages) et les précipitations (elle retombe en pluie). » — Comment appelle-t-on l\'étape où l\'eau retombe sous forme de pluie ?',
    options: [
      { id: 'a', text: 'L\'évaporation', isCorrect: false },
      { id: 'b', text: 'La condensation', isCorrect: false },
      { id: 'c', text: 'Les précipitations', isCorrect: true },
    ],
    correctAnswer: 'Les précipitations',
    explanation: 'Les précipitations désignent l\'eau qui retombe du ciel sous forme de pluie, neige ou grêle.',
    hint: 'La réponse est dans le texte entre parenthèses.',
    tags: ['cm2', 'sciences', 'eau', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis l\'étape 3.', 'Elle retombe en pluie.', 'Le nom de cette étape est ?'] },
    }),
  },
  {
    id: 'sc-cm2-com-009',
    subject: 'sciences',
    title: 'Compréhension : biodiversité',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Les forêts abritent une grande variété d\'animaux et de plantes. On dit qu\'elles ont une grande biodiversité. » — Que signifie le mot « biodiversité » ?',
    options: [
      { id: 'a', text: 'Une forêt très dense', isCorrect: false },
      { id: 'b', text: 'La diversité des êtres vivants', isCorrect: true },
      { id: 'c', text: 'Une espèce animale rare', isCorrect: false },
    ],
    correctAnswer: 'La diversité des êtres vivants',
    explanation: 'La biodiversité, c\'est la grande variété des espèces vivantes dans un milieu.',
    hint: '« Bio » = vie, « diversité » = variété.',
    tags: ['cm2', 'sciences', 'habitats', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Donne 2 exemples d\'êtres vivants qu\'on trouve dans une forêt.' },
    }),
  },
  {
    id: 'sc-cm2-com-010',
    subject: 'sciences',
    title: 'Compréhension : migration',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« Certains oiseaux comme les hirondelles quittent la France à l\'automne pour des régions plus chaudes. On dit qu\'ils migrent. » — Pourquoi les hirondelles quittent-elles la France en automne ?',
    options: [
      { id: 'a', text: 'Pour trouver de l\'eau', isCorrect: false },
      { id: 'b', text: 'Pour aller vers des régions plus chaudes', isCorrect: true },
      { id: 'c', text: 'Pour construire un nouveau nid', isCorrect: false },
    ],
    correctAnswer: 'Pour aller vers des régions plus chaudes',
    explanation: 'Les hirondelles migrent vers des régions chaudes en automne pour échapper au froid et trouver des insectes à manger.',
    hint: 'Le texte dit « vers des régions plus chaudes ».',
    tags: ['cm2', 'sciences', 'habitats', 'saisons', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
