import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm1EspaceEuropeExercises: DecouverteExercise[] = [

  {
    id: 'ddm-cm1-esp-031',
    subject: 'decouverte_du_monde',
    title: "L'Europe : continent",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'continents',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Europe est bordée par… (cocher TOUTES les mers et océans qui la bordent)",
    options: [
      { id: 'a', text: "l'océan Atlantique uniquement", isCorrect: false },
      { id: 'b', text: "l'océan Arctique, l'Atlantique et la mer Méditerranée", isCorrect: true },
      { id: 'c', text: "l'océan Indien et l'Atlantique", isCorrect: false },
      { id: 'd', text: "la mer Noire uniquement", isCorrect: false },
    ],
    correctAnswer: "l'océan Arctique, l'Atlantique et la mer Méditerranée",
    explanation: "L'Europe est bordée au nord par l'océan Arctique, à l'ouest par l'Atlantique, au sud par la Méditerranée et à l'est par l'Oural (frontière avec l'Asie).",
    hint: "L'Europe est au nord-ouest de l'Eurasie.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-032',
    subject: 'decouverte_du_monde',
    title: "Capitales : Allemagne",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'capitales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale de l'Allemagne, voisine de la France à l'est ?",
    options: [
      { id: 'a', text: 'Munich', isCorrect: false },
      { id: 'b', text: 'Berlin', isCorrect: true },
      { id: 'c', text: 'Francfort', isCorrect: false },
      { id: 'd', text: 'Hambourg', isCorrect: false },
    ],
    correctAnswer: 'Berlin',
    explanation: "Berlin est la capitale et la plus grande ville d'Allemagne. L'Allemagne est le premier pays de l'UE par la population (~83 millions d'habitants).",
    hint: "Le mur de Berlin séparait cette ville de 1961 à 1989.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-033',
    subject: 'decouverte_du_monde',
    title: "Capitales : Italie",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'capitales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale de l'Italie ?",
    options: [
      { id: 'a', text: 'Milan', isCorrect: false },
      { id: 'b', text: 'Rome', isCorrect: true },
      { id: 'c', text: 'Naples', isCorrect: false },
      { id: 'd', text: 'Venise', isCorrect: false },
    ],
    correctAnswer: 'Rome',
    explanation: "Rome est la capitale de l'Italie. L'Italie partage une frontière avec la France dans les Alpes (frontière franco-italienne autour du mont Blanc).",
    hint: "« Tous les chemins mènent à Rome. »",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-034',
    subject: 'decouverte_du_monde',
    title: "Capitales : Espagne",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'capitales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale de l'Espagne, voisine de la France au sud ?",
    options: [
      { id: 'a', text: 'Barcelone', isCorrect: false },
      { id: 'b', text: 'Madrid', isCorrect: true },
      { id: 'c', text: 'Séville', isCorrect: false },
      { id: 'd', text: 'Valence', isCorrect: false },
    ],
    correctAnswer: 'Madrid',
    explanation: "Madrid est la capitale de l'Espagne. Elle se situe au centre de la péninsule ibérique. L'Espagne est séparée de la France par les Pyrénées.",
    hint: "Madrid est la capitale, même si Barcelone est plus connue à l'étranger.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-035',
    subject: 'decouverte_du_monde',
    title: "Capitales : Royaume-Uni",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'capitales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale du Royaume-Uni ?",
    options: [
      { id: 'a', text: 'Manchester', isCorrect: false },
      { id: 'b', text: 'Londres', isCorrect: true },
      { id: 'c', text: 'Édimbourg', isCorrect: false },
      { id: 'd', text: 'Dublin', isCorrect: false },
    ],
    correctAnswer: 'Londres',
    explanation: "Londres (London) est la capitale du Royaume-Uni. Le Royaume-Uni est séparé de la France par la Manche. Le tunnel sous la Manche les relie.",
    hint: "Big Ben, la Tour de Londres, Buckingham Palace → Londres.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-036',
    subject: 'decouverte_du_monde',
    title: "Capitales : Belgique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'capitales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Bruxelles est la capitale de la Belgique et aussi le siège de l'Union européenne. La Belgique borde la France au…",
    options: [
      { id: 'a', text: 'sud', isCorrect: false },
      { id: 'b', text: 'nord', isCorrect: true },
      { id: 'c', text: 'est', isCorrect: false },
      { id: 'd', text: 'ouest', isCorrect: false },
    ],
    correctAnswer: 'nord',
    explanation: "La Belgique est au nord de la France (région Hauts-de-France). Bruxelles est à la fois la capitale belge et le siège principal des institutions européennes.",
    hint: "La Belgique est au-dessus de la France sur une carte.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-037',
    subject: 'decouverte_du_monde',
    title: "La Suisse",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Suisse est un pays enclavé (sans accès à la mer). Quelle est sa capitale ?",
    options: [
      { id: 'a', text: 'Genève', isCorrect: false },
      { id: 'b', text: 'Berne', isCorrect: true },
      { id: 'c', text: 'Zurich', isCorrect: false },
      { id: 'd', text: 'Lausanne', isCorrect: false },
    ],
    correctAnswer: 'Berne',
    explanation: "Berne est la capitale fédérale de la Suisse. Genève et Zurich sont des villes plus connues mais ne sont pas la capitale. La Suisse n'est pas dans l'UE.",
    hint: "La Suisse n'est pas dans l'UE — et sa capitale n'est pas sa ville la plus peuplée.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-038',
    subject: 'decouverte_du_monde',
    title: "Les Alpes européennes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'reliefs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Alpes sont un massif montagneux partagé entre plusieurs pays européens. Lesquels ?",
    options: [
      { id: 'a', text: "France et Espagne uniquement", isCorrect: false },
      { id: 'b', text: "France, Italie, Suisse, Autriche (et d'autres)", isCorrect: true },
      { id: 'c', text: "Allemagne et Pologne uniquement", isCorrect: false },
      { id: 'd', text: "France et Belgique uniquement", isCorrect: false },
    ],
    correctAnswer: "France, Italie, Suisse, Autriche (et d'autres)",
    explanation: "Les Alpes s'étendent sur 1 200 km, traversant la France, Monaco, l'Italie, la Suisse, le Liechtenstein, l'Autriche, l'Allemagne et la Slovénie.",
    hint: "Les Alpes sont le plus grand massif montagneux d'Europe de l'Ouest.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-039',
    subject: 'decouverte_du_monde',
    title: "La péninsule ibérique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La péninsule ibérique est occupée par…",
    options: [
      { id: 'a', text: "l'Espagne et la France", isCorrect: false },
      { id: 'b', text: "l'Espagne, le Portugal et Andorre", isCorrect: true },
      { id: 'c', text: "l'Espagne uniquement", isCorrect: false },
      { id: 'd', text: "l'Italie et l'Espagne", isCorrect: false },
    ],
    correctAnswer: "l'Espagne, le Portugal et Andorre",
    explanation: "La péninsule ibérique accueille l'Espagne, le Portugal (à l'ouest) et la principauté d'Andorre (dans les Pyrénées). Elle est entourée par l'Atlantique et la Méditerranée.",
    hint: "Ibérique = Espagne + Portugal + Andorre.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-040',
    subject: 'decouverte_du_monde',
    title: "Les pays scandinaves",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Lesquels de ces pays appartiennent à la Scandinavie ?",
    options: [
      { id: 'a', text: "Russie, Ukraine, Pologne", isCorrect: false },
      { id: 'b', text: "Norvège, Suède, Danemark", isCorrect: true },
      { id: 'c', text: "Finlande, Estonie, Lettonie", isCorrect: false },
      { id: 'd', text: "Grèce, Bulgarie, Roumanie", isCorrect: false },
    ],
    correctAnswer: "Norvège, Suède, Danemark",
    explanation: "La Scandinavie au sens traditionnel comprend la Norvège, la Suède et le Danemark. Ces pays du nord de l'Europe sont souvent associés au froid, aux fjords et aux vikings.",
    hint: "Scandinavie = nord de l'Europe, Vikings, aurores boréales.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-041',
    subject: 'decouverte_du_monde',
    title: "Le Rhin et le Danube",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Rhin se jette dans la mer du Nord (Pays-Bas). Le Danube, lui, se jette dans…",
    options: [
      { id: 'a', text: "la mer Méditerranée", isCorrect: false },
      { id: 'b', text: "la mer Noire", isCorrect: true },
      { id: 'c', text: "la mer Baltique", isCorrect: false },
      { id: 'd', text: "l'océan Atlantique", isCorrect: false },
    ],
    correctAnswer: "la mer Noire",
    explanation: "Le Danube (2 860 km) est le 2e plus long fleuve d'Europe. Il naît en Allemagne et traverse 10 pays avant de se jeter dans la mer Noire (Roumanie).",
    hint: "Le Danube traverse Vienne (Autriche) et Budapest (Hongrie).",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-042',
    subject: 'decouverte_du_monde',
    title: "L'euro",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'ue',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'euro est la monnaie commune utilisée par…",
    options: [
      { id: 'a', text: "tous les pays du monde", isCorrect: false },
      { id: 'b', text: "20 des 27 pays de l'UE (zone euro)", isCorrect: true },
      { id: 'c', text: "tous les 27 pays de l'UE", isCorrect: false },
      { id: 'd', text: "uniquement la France et l'Allemagne", isCorrect: false },
    ],
    correctAnswer: "20 des 27 pays de l'UE (zone euro)",
    explanation: "La zone euro regroupe 20 pays membres de l'UE qui utilisent l'euro. Des pays comme la Suède, la Pologne et la Tchéquie sont dans l'UE mais ont gardé leur monnaie nationale.",
    hint: "Tous les pays de l'UE ne font pas partie de la zone euro.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-043',
    subject: 'decouverte_du_monde',
    title: "La Grèce",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Grèce est un pays du sud-est de l'Europe. Sa capitale est…",
    options: [
      { id: 'a', text: 'Thessalonique', isCorrect: false },
      { id: 'b', text: 'Athènes', isCorrect: true },
      { id: 'c', text: 'Sparte', isCorrect: false },
      { id: 'd', text: 'Héraklion', isCorrect: false },
    ],
    correctAnswer: 'Athènes',
    explanation: "Athènes est la capitale de la Grèce. C'est l'une des plus anciennes villes du monde. La Grèce est en mer Méditerranée avec de nombreuses îles (Crète, Rhodes, Corfou…).",
    hint: "Athènes, l'Acropole, les Jeux olympiques antiques → Grèce.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-044',
    subject: 'decouverte_du_monde',
    title: "Les Pays-Bas",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Pays-Bas (Hollande) sont célèbres pour avoir gagné des terres sur la mer. La capitale est…",
    options: [
      { id: 'a', text: 'Rotterdam', isCorrect: false },
      { id: 'b', text: 'Amsterdam', isCorrect: true },
      { id: 'c', text: 'La Haye', isCorrect: false },
      { id: 'd', text: 'Utrecht', isCorrect: false },
    ],
    correctAnswer: 'Amsterdam',
    explanation: "Amsterdam est la capitale des Pays-Bas. Ce pays a construit des digues (polders) pour gagner des terres sur la mer du Nord. Une grande partie du pays est sous le niveau de la mer.",
    hint: "Amsterdam, les canaux, les tulipes, les moulins à vent → Pays-Bas.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-045',
    subject: 'decouverte_du_monde',
    title: "La Pologne",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Pologne est le plus grand pays d'Europe centrale par la superficie. Sa capitale est…",
    options: [
      { id: 'a', text: 'Cracovie', isCorrect: false },
      { id: 'b', text: 'Varsovie', isCorrect: true },
      { id: 'c', text: 'Gdańsk', isCorrect: false },
      { id: 'd', text: 'Poznań', isCorrect: false },
    ],
    correctAnswer: 'Varsovie',
    explanation: "Varsovie (Warszawa) est la capitale de la Pologne. La Pologne a rejoint l'UE en 2004. Elle borde la Baltique au nord et l'Allemagne à l'ouest.",
    hint: "La Pologne est entre l'Allemagne et la Russie.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-046',
    subject: 'decouverte_du_monde',
    title: "Frontières de la France en Europe",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Lequel de ces pays est un voisin terrestre de la France ?",
    options: [
      { id: 'a', text: 'Autriche', isCorrect: false },
      { id: 'b', text: 'Luxembourg', isCorrect: true },
      { id: 'c', text: 'Pologne', isCorrect: false },
      { id: 'd', text: 'Pays-Bas', isCorrect: false },
    ],
    correctAnswer: 'Luxembourg',
    explanation: "Le Luxembourg est un petit pays qui borde la France à l'est (région Grand Est). C'est l'un des 8 pays voisins terrestres de la France.",
    hint: "Le Luxembourg est enclavé entre la France, la Belgique et l'Allemagne.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-047',
    subject: 'decouverte_du_monde',
    title: "Capitale de l'UE",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'ue',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les principales institutions de l'UE sont réparties entre plusieurs villes. Le Parlement européen siège à…",
    options: [
      { id: 'a', text: 'Berlin', isCorrect: false },
      { id: 'b', text: 'Strasbourg (et Bruxelles)', isCorrect: true },
      { id: 'c', text: 'Paris', isCorrect: false },
      { id: 'd', text: 'Genève', isCorrect: false },
    ],
    correctAnswer: 'Strasbourg (et Bruxelles)',
    explanation: "Le Parlement européen siège à Strasbourg (France) pour les sessions plénières et à Bruxelles pour les commissions. La Commission européenne est à Bruxelles.",
    hint: "Strasbourg accueille le Parlement européen — et aussi le Conseil de l'Europe.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-048',
    subject: 'decouverte_du_monde',
    title: "La mer Baltique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La mer Baltique borde plusieurs pays. Lesquels parmi ceux-ci ?",
    options: [
      { id: 'a', text: "France, Espagne, Portugal", isCorrect: false },
      { id: 'b', text: "Suède, Finlande, Pologne, Allemagne, pays baltes", isCorrect: true },
      { id: 'c', text: "Grèce, Turquie, Italie", isCorrect: false },
      { id: 'd', text: "Russie uniquement", isCorrect: false },
    ],
    correctAnswer: "Suède, Finlande, Pologne, Allemagne, pays baltes",
    explanation: "La mer Baltique est une mer presque fermée au nord-est de l'Europe. Elle borde la Suède, la Finlande, la Russie, l'Estonie, la Lettonie, la Lituanie, la Pologne, l'Allemagne et le Danemark.",
    hint: "Baltique = nord-est de l'Europe.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-049',
    subject: 'decouverte_du_monde',
    title: "L'Europe : superficie",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'continents',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Russie est le plus grand pays d'Europe et du monde. Sa capitale est…",
    options: [
      { id: 'a', text: 'Saint-Pétersbourg', isCorrect: false },
      { id: 'b', text: 'Moscou', isCorrect: true },
      { id: 'c', text: 'Kiev', isCorrect: false },
      { id: 'd', text: 'Minsk', isCorrect: false },
    ],
    correctAnswer: 'Moscou',
    explanation: "Moscou (Moskva) est la capitale et la plus grande ville de Russie. La Russie s'étend sur 11 fuseaux horaires, de l'Europe à l'Asie. Elle n'est pas membre de l'UE.",
    hint: "Le Kremlin et la place Rouge se trouvent à Moscou.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-050',
    subject: 'decouverte_du_monde',
    title: "Identifier la France sur une carte d'Europe",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France se trouve dans quelle partie de l'Europe ?",
    options: [
      { id: 'a', text: "L'Europe du nord", isCorrect: false },
      { id: 'b', text: "L'Europe de l'ouest", isCorrect: true },
      { id: 'c', text: "L'Europe de l'est", isCorrect: false },
      { id: 'd', text: "L'Europe centrale", isCorrect: false },
    ],
    correctAnswer: "L'Europe de l'ouest",
    explanation: "La France est un pays d'Europe de l'ouest. Elle appartient à l'UE et est l'un des membres fondateurs de la Communauté européenne (1957, traité de Rome).",
    hint: "La France est à l'ouest de l'Allemagne et au nord de l'Espagne.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-051',
    subject: 'decouverte_du_monde',
    title: "L'Autriche",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Autriche est un pays enclavé d'Europe centrale. Sa capitale est…",
    options: [
      { id: 'a', text: 'Salzbourg', isCorrect: false },
      { id: 'b', text: 'Vienne', isCorrect: true },
      { id: 'c', text: 'Innsbruck', isCorrect: false },
      { id: 'd', text: 'Graz', isCorrect: false },
    ],
    correctAnswer: 'Vienne',
    explanation: "Vienne (Wien) est la capitale de l'Autriche. C'est une grande ville culturelle au bord du Danube. L'Autriche n'a pas accès à la mer.",
    hint: "Vienne est sur le Danube, célèbre pour sa musique classique (Mozart, Beethoven...).",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-esp-052',
    subject: 'decouverte_du_monde',
    title: "Le Portugal",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'pays_europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Portugal est le pays le plus à l'ouest de l'Europe continentale. Sa capitale est…",
    options: [
      { id: 'a', text: 'Porto', isCorrect: false },
      { id: 'b', text: 'Lisbonne', isCorrect: true },
      { id: 'c', text: 'Faro', isCorrect: false },
      { id: 'd', text: 'Braga', isCorrect: false },
    ],
    correctAnswer: 'Lisbonne',
    explanation: "Lisbonne (Lisboa) est la capitale du Portugal. Le Portugal est bordé à l'ouest par l'Atlantique. Il partage la péninsule ibérique avec l'Espagne.",
    hint: "Lisbonne est construite sur sept collines au bord du Tage.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
