import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm1VivantExercises: DecouverteExercise[] = [
  {
    id: 'ddm-cm1-vivant-001',
    subject: 'decouverte_du_monde',
    title: 'Caractéristiques du vivant',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'caracteristiques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Parmi ces propositions, laquelle est une caractéristique commune à tous les êtres vivants ?',
    options: [
      { id: 'a', text: 'Ils fabriquent tous leur propre nourriture grâce au soleil.', isCorrect: false },
      { id: 'b', text: 'Ils se reproduisent, se nourrissent et meurent.', isCorrect: true },
      { id: 'c', text: 'Ils ont tous des racines et des feuilles.', isCorrect: false },
      { id: 'd', text: 'Ils respirent tous en absorbant de l\'eau.', isCorrect: false },
    ],
    correctAnswer: 'Ils se reproduisent, se nourrissent et meurent.',
    explanation: 'Tous les êtres vivants naissent, se nourrissent, se reproduisent et meurent. Seules les plantes fabriquent leur nourriture grâce à la photosynthèse.',
    hint: 'Pense à ce que font un chien, un arbre et un champignon en commun.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-vivant-002',
    subject: 'decouverte_du_monde',
    title: 'Besoins des plantes',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'besoins',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi une plante verte a-t-elle besoin pour fabriquer sa nourriture ?',
    options: [
      { id: 'a', text: 'De lumière, d\'eau et de sels minéraux.', isCorrect: true },
      { id: 'b', text: 'De lumière, d\'air et de sucre.', isCorrect: false },
      { id: 'c', text: 'D\'eau, de sel et d\'humus uniquement.', isCorrect: false },
      { id: 'd', text: 'De lumière et de viande.', isCorrect: false },
    ],
    correctAnswer: 'De lumière, d\'eau et de sels minéraux.',
    explanation: 'Les plantes réalisent la photosynthèse grâce à la lumière du soleil, l\'eau absorbée par les racines et les sels minéraux du sol. Ce processus produit du glucose (leur nourriture).',
    hint: 'La photosynthèse se passe dans les feuilles.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-vivant-003',
    subject: 'decouverte_du_monde',
    title: 'Cycle de vie d\'un insecte',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'cycles',
    format: 'qcm',
    instructions: 'Mets les étapes dans le bon ordre.',
    prompt: 'Quel est le cycle de vie du papillon dans le bon ordre ?',
    options: [
      { id: 'a', text: 'Œuf → chenille → chrysalide → papillon', isCorrect: true },
      { id: 'b', text: 'Chenille → œuf → papillon → chrysalide', isCorrect: false },
      { id: 'c', text: 'Œuf → papillon → chrysalide → chenille', isCorrect: false },
      { id: 'd', text: 'Chrysalide → chenille → papillon → œuf', isCorrect: false },
    ],
    correctAnswer: 'Œuf → chenille → chrysalide → papillon',
    explanation: 'Le papillon commence comme un œuf, puis devient une chenille (larve) qui mange et grandit, se transforme en chrysalide (nymphe) dans un cocon, puis émerge adulte sous forme de papillon.',
    hint: 'Le papillon pond des œufs qui deviennent des chenilles.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-vivant-004',
    subject: 'decouverte_du_monde',
    title: 'Squelette et muscles',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle principal du squelette dans notre corps ?',
    options: [
      { id: 'a', text: 'Fabriquer le sang et transporter l\'oxygène.', isCorrect: false },
      { id: 'b', text: 'Soutenir le corps, le protéger et permettre les mouvements.', isCorrect: true },
      { id: 'c', text: 'Digérer les aliments.', isCorrect: false },
      { id: 'd', text: 'Filtrer l\'air que l\'on respire.', isCorrect: false },
    ],
    correctAnswer: 'Soutenir le corps, le protéger et permettre les mouvements.',
    explanation: 'Le squelette donne la forme au corps, protège les organes fragiles (comme le crâne qui protège le cerveau) et, avec les muscles qui s\'y attachent, permet de bouger.',
    hint: 'Sans squelette, on ne pourrait pas se tenir debout.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-vivant-005',
    subject: 'decouverte_du_monde',
    title: 'Hygiène et santé',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi est-il important de se laver les mains avant de manger ?',
    options: [
      { id: 'a', text: 'Pour avoir les mains plus chaudes.', isCorrect: false },
      { id: 'b', text: 'Pour éliminer les microbes et éviter les maladies.', isCorrect: true },
      { id: 'c', text: 'Pour que les aliments aient meilleur goût.', isCorrect: false },
      { id: 'd', text: 'Parce que c\'est la politesse uniquement.', isCorrect: false },
    ],
    correctAnswer: 'Pour éliminer les microbes et éviter les maladies.',
    explanation: 'Les mains touchent beaucoup d\'objets et peuvent transporter des microbes (bactéries, virus). Se laver les mains au savon élimine ces microbes et réduit le risque d\'attraper ou de transmettre des maladies.',
    hint: 'Les microbes sont invisibles à l\'œil nu.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-vivant-006',
    subject: 'decouverte_du_monde',
    title: 'Alimentation équilibrée',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'alimentation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pour avoir une alimentation équilibrée, que faut-il manger en plus grande quantité ?',
    options: [
      { id: 'a', text: 'Des produits sucrés et des graisses.', isCorrect: false },
      { id: 'b', text: 'Des fruits, des légumes et des féculents.', isCorrect: true },
      { id: 'c', text: 'Uniquement des protéines (viande, poisson).', isCorrect: false },
      { id: 'd', text: 'Des sodas et des jus de fruits.', isCorrect: false },
    ],
    correctAnswer: 'Des fruits, des légumes et des féculents.',
    explanation: 'Une alimentation équilibrée se compose surtout de fruits et légumes (vitamines, fibres) et de féculents (énergie durable). La viande, les produits laitiers et les corps gras se consomment en plus petites quantités.',
    hint: 'La pyramide alimentaire place les fruits et légumes à la base.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
