import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm1ReperesExercises: DecouverteExercise[] = [

  // CM1 · reperes · france
  {
    id: 'ddm-cm1-rep-001',
    subject: 'decouverte_du_monde',
    title: 'Capitale de la France',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment s\'appelle la capitale de la France ?',
    options: [
      { id: 'a', text: 'Lyon', isCorrect: false },
      { id: 'b', text: 'Marseille', isCorrect: false },
      { id: 'c', text: 'Nice', isCorrect: false },
      { id: 'd', text: 'Paris', isCorrect: true },
    ],
    correctAnswer: 'Paris',
    explanation: 'Paris est la capitale de la France : c\'est là que siège le gouvernement.',
    hint: 'La tour Eiffel s\'y trouve.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-003',
    subject: 'decouverte_du_monde',
    title: 'Océan Atlantique',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on la mer à l\'ouest de la France ?',
    options: [
      { id: 'a', text: 'la Méditerranée', isCorrect: false },
      { id: 'b', text: 'la mer du Nord', isCorrect: false },
      { id: 'c', text: 'l\'océan Atlantique', isCorrect: true },
      { id: 'd', text: 'la mer Noire', isCorrect: false },
    ],
    correctAnswer: 'l\'océan Atlantique',
    explanation: 'La façade atlantique de la France (Bretagne, pays Basque…) donne sur l\'océan Atlantique.',
    hint: 'Les grandes vagues des surfeurs viennent de là.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-004',
    subject: 'decouverte_du_monde',
    title: 'Le Mont Blanc',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'france',
    format: 'qcm',
    instructions: 'Choisis le bon sommet.',
    prompt: 'Quel est le plus haut sommet des Alpes françaises ?',
    options: [
      { id: 'a', text: 'Le Vercors', isCorrect: false },
      { id: 'b', text: 'Le Mont Blanc', isCorrect: true },
      { id: 'c', text: 'Le Jura', isCorrect: false },
      { id: 'd', text: 'Les Vosges', isCorrect: false },
    ],
    correctAnswer: 'Le Mont Blanc',
    explanation: 'Le Mont Blanc culmine à 4 810 m — c\'est le toit des Alpes et d\'Europe.',
    hint: 'Il est couvert de neige toute l\'année.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CM1 · reperes · capitale
  {
    id: 'ddm-cm1-rep-005',
    subject: 'decouverte_du_monde',
    title: 'Définition de capitale',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'capitale',
    format: 'qcm',
    instructions: 'Choisis la bonne définition.',
    prompt: 'Comment appelle-t-on la ville principale d\'un pays ?',
    options: [
      { id: 'a', text: 'une métropole', isCorrect: false },
      { id: 'b', text: 'une capitale', isCorrect: true },
      { id: 'c', text: 'une commune', isCorrect: false },
      { id: 'd', text: 'une province', isCorrect: false },
    ],
    correctAnswer: 'une capitale',
    explanation: 'La capitale est la ville où se trouve le gouvernement d\'un pays.',
    hint: 'C\'est la ville la plus importante politiquement.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-006',
    subject: 'decouverte_du_monde',
    title: 'Capitale de l\'Espagne',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'capitale',
    format: 'qcm',
    instructions: 'Choisis la bonne capitale.',
    prompt: 'Quelle est la capitale de l\'Espagne ?',
    options: [
      { id: 'a', text: 'Barcelone', isCorrect: false },
      { id: 'b', text: 'Séville', isCorrect: false },
      { id: 'c', text: 'Madrid', isCorrect: true },
      { id: 'd', text: 'Valence', isCorrect: false },
    ],
    correctAnswer: 'Madrid',
    explanation: 'Madrid est la capitale de l\'Espagne, notre voisin au sud.',
    hint: 'Ce n\'est pas Barcelone, même si c\'est une grande ville.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-007',
    subject: 'decouverte_du_monde',
    title: 'Capitale de l\'Italie',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'capitale',
    format: 'qcm',
    instructions: 'Choisis la bonne capitale.',
    prompt: 'Quelle est la capitale de l\'Italie ?',
    options: [
      { id: 'a', text: 'Milan', isCorrect: false },
      { id: 'b', text: 'Naples', isCorrect: false },
      { id: 'c', text: 'Florence', isCorrect: false },
      { id: 'd', text: 'Rome', isCorrect: true },
    ],
    correctAnswer: 'Rome',
    explanation: 'Rome est la capitale de l\'Italie. C\'est aussi une très ancienne ville.',
    hint: 'Là où se trouve le Colisée.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CM1 · reperes · drapeau
  {
    id: 'ddm-cm1-rep-002',
    subject: 'decouverte_du_monde',
    title: 'Drapeau français',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'drapeau',
    format: 'qcm',
    instructions: 'Choisis les bonnes couleurs.',
    prompt: 'Quelles sont les couleurs du drapeau français ?',
    options: [
      { id: 'a', text: 'rouge, blanc, vert', isCorrect: false },
      { id: 'b', text: 'bleu, blanc, rouge', isCorrect: true },
      { id: 'c', text: 'bleu, jaune, rouge', isCorrect: false },
      { id: 'd', text: 'vert, blanc, rouge', isCorrect: false },
    ],
    correctAnswer: 'bleu, blanc, rouge',
    explanation: 'Le drapeau tricolore français est bleu, blanc et rouge, dans cet ordre.',
    hint: 'On l\'appelle le drapeau tricolore.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-008',
    subject: 'decouverte_du_monde',
    title: 'Drapeau de l\'Italie',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'drapeau',
    format: 'qcm',
    instructions: 'Choisis les bonnes couleurs.',
    prompt: 'Quelles sont les couleurs du drapeau de l\'Italie ?',
    options: [
      { id: 'a', text: 'bleu, blanc, rouge', isCorrect: false },
      { id: 'b', text: 'rouge, blanc, vert', isCorrect: false },
      { id: 'c', text: 'vert, blanc, rouge', isCorrect: true },
      { id: 'd', text: 'jaune, blanc, rouge', isCorrect: false },
    ],
    correctAnswer: 'vert, blanc, rouge',
    explanation: 'Le drapeau italien est vert, blanc et rouge (dans cet ordre de gauche à droite).',
    hint: 'Même couleurs que la France mais dans un ordre différent.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-009',
    subject: 'decouverte_du_monde',
    title: 'Drapeau britannique',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'drapeau',
    format: 'qcm',
    instructions: 'Choisis les bonnes couleurs.',
    prompt: 'Le drapeau du Royaume-Uni (Union Jack) est de quelles couleurs ?',
    options: [
      { id: 'a', text: 'vert, blanc, rouge', isCorrect: false },
      { id: 'b', text: 'bleu, rouge et blanc', isCorrect: true },
      { id: 'c', text: 'jaune, bleu, rouge', isCorrect: false },
      { id: 'd', text: 'rouge, vert, blanc', isCorrect: false },
    ],
    correctAnswer: 'bleu, rouge et blanc',
    explanation: 'L\'Union Jack, le drapeau britannique, est rouge, blanc et bleu.',
    hint: 'Il ressemble à une croix dans une croix.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-012',
    subject: 'decouverte_du_monde',
    title: 'Drapeau européen',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'drapeau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quelle couleur sont les étoiles sur le drapeau de l\'Union européenne ?',
    options: [
      { id: 'a', text: 'blanches', isCorrect: false },
      { id: 'b', text: 'rouges', isCorrect: false },
      { id: 'c', text: 'dorées (jaunes)', isCorrect: true },
      { id: 'd', text: 'vertes', isCorrect: false },
    ],
    correctAnswer: 'dorées (jaunes)',
    explanation: 'Le drapeau européen est bleu avec 12 étoiles dorées (jaunes) en cercle.',
    hint: 'Le fond est bleu et les étoiles ressemblent à de l\'or.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CM1 · reperes · carte
  {
    id: 'ddm-cm1-rep-010',
    subject: 'decouverte_du_monde',
    title: 'Le nord sur une carte',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'carte',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sur la plupart des cartes, vers quel côté est le nord ?',
    options: [
      { id: 'a', text: 'en bas', isCorrect: false },
      { id: 'b', text: 'à gauche', isCorrect: false },
      { id: 'c', text: 'en haut', isCorrect: true },
      { id: 'd', text: 'à droite', isCorrect: false },
    ],
    correctAnswer: 'en haut',
    explanation: 'Par convention, le nord est en haut sur presque toutes les cartes géographiques.',
    hint: 'Les cartes sont orientées pour que le nord soit vers le haut.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm1-rep-011',
    subject: 'decouverte_du_monde',
    title: 'Paris au nord',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'reperes',
    subskill: 'carte',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sur une carte de France, Paris se trouve plutôt…',
    options: [
      { id: 'a', text: 'au sud', isCorrect: false },
      { id: 'b', text: 'à l\'est', isCorrect: false },
      { id: 'c', text: 'au nord', isCorrect: true },
      { id: 'd', text: 'à l\'ouest', isCorrect: false },
    ],
    correctAnswer: 'au nord',
    explanation: 'Paris est situé dans la moitié nord de la France.',
    hint: 'Regarde une carte de France : Paris est en haut.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
