import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm2ReperesExercises: DecouverteExercise[] = [

  // CM2 · reperes · france
  {
    id: 'ddm-cm2-rep-001',
    subject: 'decouverte_du_monde',
    title: 'Forme de la France',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'On dit souvent que la France a la forme d\'un…',
    options: [
      { id: 'a', text: 'triangle', isCorrect: false },
      { id: 'b', text: 'hexagone', isCorrect: true },
      { id: 'c', text: 'carré', isCorrect: false },
      { id: 'd', text: 'cercle', isCorrect: false },
    ],
    correctAnswer: 'hexagone',
    explanation: 'La France est souvent surnommée « l\'Hexagone » car sa forme rappelle cette figure à 6 côtés.',
    hint: 'C\'est une figure géométrique à 6 côtés.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-002',
    subject: 'decouverte_du_monde',
    title: 'Devise de la France',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'france',
    format: 'qcm',
    instructions: 'Choisis la bonne devise.',
    prompt: 'Quelle est la devise de la République française ?',
    options: [
      { id: 'a', text: 'Paix, Justice, Solidarité', isCorrect: false },
      { id: 'b', text: 'Liberté, Égalité, Fraternité', isCorrect: true },
      { id: 'c', text: 'Travail, Famille, Patrie', isCorrect: false },
      { id: 'd', text: 'Force, Honneur, Fidélité', isCorrect: false },
    ],
    correctAnswer: 'Liberté, Égalité, Fraternité',
    explanation: 'La devise de la France est « Liberté, Égalité, Fraternité ». Elle figure sur les bâtiments officiels.',
    hint: 'Elle date de la Révolution française.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-003',
    subject: 'decouverte_du_monde',
    title: 'Fleuve traversant Paris',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'france',
    format: 'qcm',
    instructions: 'Choisis le bon fleuve.',
    prompt: 'Quel fleuve traverse Paris ?',
    options: [
      { id: 'a', text: 'la Loire', isCorrect: false },
      { id: 'b', text: 'le Rhône', isCorrect: false },
      { id: 'c', text: 'la Garonne', isCorrect: false },
      { id: 'd', text: 'la Seine', isCorrect: true },
    ],
    correctAnswer: 'la Seine',
    explanation: 'La Seine traverse Paris avant de se jeter dans la Manche, près du Havre.',
    hint: 'Notre-Dame de Paris est sur une île de ce fleuve.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-007b',
    subject: 'decouverte_du_monde',
    title: 'La Manche',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Manche sépare la France de…',
    options: [
      { id: 'a', text: 'l\'Espagne', isCorrect: false },
      { id: 'b', text: 'la Belgique', isCorrect: false },
      { id: 'c', text: 'l\'Angleterre (Royaume-Uni)', isCorrect: true },
      { id: 'd', text: 'l\'Irlande', isCorrect: false },
    ],
    correctAnswer: 'l\'Angleterre (Royaume-Uni)',
    explanation: 'La Manche est un bras de mer qui sépare la France du Royaume-Uni. Le tunnel sous la Manche la traverse.',
    hint: 'L\'Eurotunnel passe dessous.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CM2 · reperes · capitale
  {
    id: 'ddm-cm2-rep-004',
    subject: 'decouverte_du_monde',
    title: 'Capitale de l\'Allemagne',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'capitale',
    format: 'qcm',
    instructions: 'Choisis la bonne capitale.',
    prompt: 'Quelle est la capitale de l\'Allemagne ?',
    options: [
      { id: 'a', text: 'Munich', isCorrect: false },
      { id: 'b', text: 'Hambourg', isCorrect: false },
      { id: 'c', text: 'Francfort', isCorrect: false },
      { id: 'd', text: 'Berlin', isCorrect: true },
    ],
    correctAnswer: 'Berlin',
    explanation: 'Berlin est la capitale de l\'Allemagne, notre grand voisin à l\'est.',
    hint: 'Son mur est tombé en 1989.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-005',
    subject: 'decouverte_du_monde',
    title: 'Capitale du Royaume-Uni',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'capitale',
    format: 'qcm',
    instructions: 'Choisis la bonne capitale.',
    prompt: 'Quelle est la capitale du Royaume-Uni ?',
    options: [
      { id: 'a', text: 'Manchester', isCorrect: false },
      { id: 'b', text: 'Édimbourg', isCorrect: false },
      { id: 'c', text: 'Londres', isCorrect: true },
      { id: 'd', text: 'Birmingham', isCorrect: false },
    ],
    correctAnswer: 'Londres',
    explanation: 'Londres (London) est la capitale du Royaume-Uni, située au bord de la Tamise.',
    hint: 'Big Ben s\'y trouve.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-006',
    subject: 'decouverte_du_monde',
    title: 'Capitale de la Belgique',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'capitale',
    format: 'qcm',
    instructions: 'Choisis la bonne capitale.',
    prompt: 'Quelle est la capitale de la Belgique ?',
    options: [
      { id: 'a', text: 'Anvers', isCorrect: false },
      { id: 'b', text: 'Liège', isCorrect: false },
      { id: 'c', text: 'Bruges', isCorrect: false },
      { id: 'd', text: 'Bruxelles', isCorrect: true },
    ],
    correctAnswer: 'Bruxelles',
    explanation: 'Bruxelles est la capitale de la Belgique. C\'est aussi le siège de l\'Union européenne.',
    hint: 'C\'est la ville de l\'Atomium.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CM2 · reperes · carte
  {
    id: 'ddm-cm2-rep-007',
    subject: 'decouverte_du_monde',
    title: 'La boussole',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'carte',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Vers quel point cardinal la boussole indique-t-elle toujours ?',
    options: [
      { id: 'a', text: 'le sud', isCorrect: false },
      { id: 'b', text: 'l\'est', isCorrect: false },
      { id: 'c', text: 'l\'ouest', isCorrect: false },
      { id: 'd', text: 'le nord', isCorrect: true },
    ],
    correctAnswer: 'le nord',
    explanation: 'L\'aiguille de la boussole est attirée par le pôle Nord magnétique. Elle indique toujours le nord.',
    hint: 'Elle est attirée par le pôle magnétique de la Terre.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
