import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm2SocieteExercises: DecouverteExercise[] = [

  {
    id: 'ddm-cm2-rep-008',
    subject: 'decouverte_du_monde',
    title: "La Déclaration des droits de l'Homme",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'droits_enfant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Déclaration universelle des droits de l'Homme (1948) comporte 30 articles. Quel est le premier droit proclamé ?",
    options: [
      { id: 'a', text: "Le droit de vote", isCorrect: false },
      { id: 'b', text: "Tous les êtres humains naissent libres et égaux en dignité et en droits.", isCorrect: true },
      { id: 'c', text: "Le droit à l'éducation", isCorrect: false },
      { id: 'd', text: "Le droit à la propriété", isCorrect: false },
    ],
    correctAnswer: "Tous les êtres humains naissent libres et égaux en dignité et en droits.",
    explanation: "L'article 1 de la DUDH affirme : « Tous les êtres humains naissent libres et égaux en dignité et en droits. » C'est le fondement de toutes les libertés et droits humains.",
    hint: "L'article 1 de la DUDH est le plus fondamental.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-009',
    subject: 'decouverte_du_monde',
    title: "La Ve République : les pouvoirs",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, qui peut dissoudre l'Assemblée nationale ?",
    options: [
      { id: 'a', text: "Le Premier ministre", isCorrect: false },
      { id: 'b', text: "Le Président de la République", isCorrect: true },
      { id: 'c', text: "Le Sénat", isCorrect: false },
      { id: 'd', text: "Le Conseil constitutionnel", isCorrect: false },
    ],
    correctAnswer: "Le Président de la République",
    explanation: "L'article 12 de la Constitution permet au Président de dissoudre l'Assemblée nationale. Il doit alors organiser de nouvelles élections législatives dans les 20 à 40 jours.",
    hint: "La dissolution de l'Assemblée est un pouvoir clé du Président de la Ve République.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-010',
    subject: 'decouverte_du_monde',
    title: "Le Conseil constitutionnel",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Conseil constitutionnel en France a pour rôle de…",
    options: [
      { id: 'a', text: "voter les lois à la place du Parlement", isCorrect: false },
      { id: 'b', text: "vérifier que les lois sont conformes à la Constitution", isCorrect: true },
      { id: 'c', text: "juger les crimes les plus graves", isCorrect: false },
      { id: 'd', text: "gérer le budget de l'État", isCorrect: false },
    ],
    correctAnswer: "vérifier que les lois sont conformes à la Constitution",
    explanation: "Le Conseil constitutionnel (9 membres) contrôle la conformité des lois à la Constitution. Si une loi est inconstitutionnelle, elle ne peut pas être appliquée.",
    hint: "Il est le gardien de la Constitution.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-011',
    subject: 'decouverte_du_monde',
    title: "La mondialisation",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La mondialisation désigne principalement…",
    options: [
      { id: 'a', text: "la disparition des frontières nationales", isCorrect: false },
      { id: 'b', text: "l'intensification des échanges économiques, culturels et humains à l'échelle mondiale", isCorrect: true },
      { id: 'c', text: "la création d'un gouvernement mondial unique", isCorrect: false },
      { id: 'd', text: "le réchauffement climatique uniquement", isCorrect: false },
    ],
    correctAnswer: "l'intensification des échanges économiques, culturels et humains à l'échelle mondiale",
    explanation: "La mondialisation est le processus d'intégration croissante des économies, des cultures et des sociétés du monde entier grâce aux échanges commerciaux, aux transports et aux communications.",
    hint: "Mondialisation = le monde comme un seul grand village.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-012',
    subject: 'decouverte_du_monde',
    title: "La liberté de la presse",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'droits_enfant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La liberté de la presse est un indicateur de démocratie. Que signifie-t-elle ?",
    options: [
      { id: 'a', text: "Les journaux sont gratuits pour tout le monde.", isCorrect: false },
      { id: 'b', text: "Les journalistes peuvent informer librement sans censure gouvernementale.", isCorrect: true },
      { id: 'c', text: "Le gouvernement peut contrôler les médias.", isCorrect: false },
      { id: 'd', text: "Les journalistes n'ont pas à vérifier leurs informations.", isCorrect: false },
    ],
    correctAnswer: "Les journalistes peuvent informer librement sans censure gouvernementale.",
    explanation: "La liberté de la presse garantit aux journalistes le droit d'informer sans que l'État ne censure ou contrôle les médias. C'est essentiel au fonctionnement d'une démocratie.",
    hint: "Une presse libre = un pouvoir contrôlé. Un pouvoir sans presse libre = risque de dictature.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-013',
    subject: 'decouverte_du_monde',
    title: "Les ONG",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "MSF (Médecins Sans Frontières) est une ONG. Qu'est-ce qu'une ONG ?",
    options: [
      { id: 'a', text: "Une organisation gouvernementale nationale", isCorrect: false },
      { id: 'b', text: "Une Organisation Non Gouvernementale : association indépendante des États", isCorrect: true },
      { id: 'c', text: "Une branche de l'ONU", isCorrect: false },
      { id: 'd', text: "Une entreprise multinationale", isCorrect: false },
    ],
    correctAnswer: "Une Organisation Non Gouvernementale : association indépendante des États",
    explanation: "Une ONG est une organisation à but non lucratif, indépendante des gouvernements. MSF fournit des soins médicaux en zones de crise. Greenpeace, Amnesty International sont aussi des ONG.",
    hint: "ONG = non gouvernementale = indépendante des États.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-014',
    subject: 'decouverte_du_monde',
    title: "Le droit international",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Cour internationale de Justice (CIJ) siège à La Haye (Pays-Bas). Son rôle est de…",
    options: [
      { id: 'a', text: "juger les individus accusés de crimes de guerre", isCorrect: false },
      { id: 'b', text: "régler les différends entre États selon le droit international", isCorrect: true },
      { id: 'c', text: "voter les traités internationaux", isCorrect: false },
      { id: 'd', text: "gérer le commerce mondial", isCorrect: false },
    ],
    correctAnswer: "régler les différends entre États selon le droit international",
    explanation: "La CIJ est la principale juridiction de l'ONU. Elle règle les litiges entre États (frontières, traités). La CPI (Cour pénale internationale) juge, elle, les individus pour crimes contre l'humanité.",
    hint: "CIJ = entre États. CPI = individus responsables de crimes contre l'humanité.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-015',
    subject: 'decouverte_du_monde',
    title: "Le changement climatique",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'accord de Paris sur le climat (2015) engage les pays signataires à…",
    options: [
      { id: 'a', text: "arrêter toute émission de CO₂ immédiatement", isCorrect: false },
      { id: 'b', text: "limiter le réchauffement climatique bien en dessous de +2°C par rapport à l'ère préindustrielle", isCorrect: true },
      { id: 'c', text: "créer un fonds mondial pour planter des arbres", isCorrect: false },
      { id: 'd', text: "interdire l'usage des énergies fossiles dès 2016", isCorrect: false },
    ],
    correctAnswer: "limiter le réchauffement climatique bien en dessous de +2°C par rapport à l'ère préindustrielle",
    explanation: "L'accord de Paris (COP21, décembre 2015) engage 196 pays à limiter le réchauffement climatique sous +2°C (idéalement +1,5°C) en réduisant les émissions de gaz à effet de serre.",
    hint: "Paris 2015 → accord climatique → objectif +2°C maximum.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-016',
    subject: 'decouverte_du_monde',
    title: "Le Parlement européen",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les eurodéputés (membres du Parlement européen) sont élus pour…",
    options: [
      { id: 'a', text: "4 ans", isCorrect: false },
      { id: 'b', text: "5 ans", isCorrect: true },
      { id: 'c', text: "6 ans", isCorrect: false },
      { id: 'd', text: "7 ans", isCorrect: false },
    ],
    correctAnswer: "5 ans",
    explanation: "Les membres du Parlement européen sont élus pour 5 ans au suffrage universel direct par les citoyens des 27 États membres. Il y a 720 eurodéputés.",
    hint: "Même durée que le mandat présidentiel français : 5 ans.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-017',
    subject: 'decouverte_du_monde',
    title: "La démocratie directe vs représentative",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, le référendum permet aux citoyens de…",
    options: [
      { id: 'a', text: "élire le Président directement", isCorrect: false },
      { id: 'b', text: "se prononcer directement sur une question (ex : accepter ou non une loi importante)", isCorrect: true },
      { id: 'c', text: "limoger un ministre", isCorrect: false },
      { id: 'd', text: "voter des lois sans passer par le Parlement", isCorrect: false },
    ],
    correctAnswer: "se prononcer directement sur une question (ex : accepter ou non une loi importante)",
    explanation: "Le référendum est un outil de démocratie directe. En France, le Président peut soumettre une question au vote populaire direct. Ex : référendum sur la Constitution européenne (2005).",
    hint: "Référendum = les citoyens votent directement sur une question.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-018',
    subject: 'decouverte_du_monde',
    title: "Les médias et la démocratie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les médias (télévision, presse, internet) sont souvent appelés le « 4e pouvoir ». Pourquoi ?",
    options: [
      { id: 'a', text: "Parce qu'ils votent les lois.", isCorrect: false },
      { id: 'b', text: "Parce qu'ils informent les citoyens et peuvent contrôler les autres pouvoirs.", isCorrect: true },
      { id: 'c', text: "Parce qu'ils sont plus puissants que le Président.", isCorrect: false },
      { id: 'd', text: "Parce qu'ils remplacent le Parlement.", isCorrect: false },
    ],
    correctAnswer: "Parce qu'ils informent les citoyens et peuvent contrôler les autres pouvoirs.",
    explanation: "En informant les citoyens sur les actions des gouvernements et des institutions, les médias libres permettent un contrôle démocratique du pouvoir — d'où l'expression « 4e pouvoir ».",
    hint: "Sans médias libres, comment saurait-on ce que font nos élus ?",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-019',
    subject: 'decouverte_du_monde',
    title: "Inégalités mondiales",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'IDH (Indice de développement humain) mesure le niveau de développement d'un pays. Il prend en compte…",
    options: [
      { id: 'a', text: "uniquement le PIB (richesse économique)", isCorrect: false },
      { id: 'b', text: "le niveau de vie, l'espérance de vie et l'éducation", isCorrect: true },
      { id: 'c', text: "la superficie du pays", isCorrect: false },
      { id: 'd', text: "le nombre d'habitants", isCorrect: false },
    ],
    correctAnswer: "le niveau de vie, l'espérance de vie et l'éducation",
    explanation: "L'IDH (créé par le PNUD en 1990) évalue le développement humain selon 3 critères : l'espérance de vie à la naissance, le niveau d'éducation et le revenu par habitant.",
    hint: "IDH = pas seulement la richesse, mais aussi la santé et l'éducation.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-020',
    subject: 'decouverte_du_monde',
    title: "Les droits de l'enfant avancés",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'droits_enfant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La CIDE (Convention internationale des droits de l'enfant) établit 4 principes fondamentaux. Lequel n'en fait PAS partie ?",
    options: [
      { id: 'a', text: "Non-discrimination", isCorrect: false },
      { id: 'b', text: "Intérêt supérieur de l'enfant", isCorrect: false },
      { id: 'c', text: "Droit à la propriété privée de l'enfant", isCorrect: true },
      { id: 'd', text: "Participation (droit à l'expression)", isCorrect: false },
    ],
    correctAnswer: "Droit à la propriété privée de l'enfant",
    explanation: "Les 4 principes fondamentaux de la CIDE sont : non-discrimination, intérêt supérieur de l'enfant, droit à la vie/survie/développement, participation. Le droit à la propriété privée n'est pas un principe fondateur.",
    hint: "Les 4 principes de la CIDE : non-discrimination, survie, intérêt supérieur, participation.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-021',
    subject: 'decouverte_du_monde',
    title: "Les impôts et les services publics",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'services',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, la part des dépenses publiques dans le PIB est d'environ…",
    options: [
      { id: 'a', text: "20 %", isCorrect: false },
      { id: 'b', text: "57 %", isCorrect: true },
      { id: 'c', text: "80 %", isCorrect: false },
      { id: 'd', text: "10 %", isCorrect: false },
    ],
    correctAnswer: "57 %",
    explanation: "La France est l'un des pays qui dépense le plus en services publics : environ 57 % du PIB. Cela finance la Sécurité sociale, l'éducation, les retraites, la défense, etc.",
    hint: "La France a un État-providence parmi les plus développés du monde.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-022',
    subject: 'decouverte_du_monde',
    title: "La citoyenneté européenne",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La citoyenneté européenne, créée par le traité de Maastricht (1992), donne aux citoyens de l'UE le droit de…",
    options: [
      { id: 'a', text: "travailler uniquement dans leur propre pays", isCorrect: false },
      { id: 'b', text: "circuler, travailler et voter aux élections locales et européennes dans tout l'UE", isCorrect: true },
      { id: 'c', text: "voter aux élections nationales dans n'importe quel pays de l'UE", isCorrect: false },
      { id: 'd', text: "payer les mêmes impôts dans tous les pays de l'UE", isCorrect: false },
    ],
    correctAnswer: "circuler, travailler et voter aux élections locales et européennes dans tout l'UE",
    explanation: "La citoyenneté européenne permet aux citoyens de l'UE de se déplacer librement, de s'établir et de travailler dans n'importe quel pays de l'UE, et de voter aux élections européennes et locales.",
    hint: "L'espace Schengen supprime les contrôles aux frontières entre pays membres.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-023',
    subject: 'decouverte_du_monde',
    title: "Démocratie et dictature",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle caractéristique est typique d'une dictature (régime non démocratique) ?",
    options: [
      { id: 'a', text: "Des élections libres et pluralistes", isCorrect: false },
      { id: 'b', text: "La censure et l'absence de liberté d'expression", isCorrect: true },
      { id: 'c', text: "La séparation des pouvoirs", isCorrect: false },
      { id: 'd', text: "Une presse libre et indépendante", isCorrect: false },
    ],
    correctAnswer: "La censure et l'absence de liberté d'expression",
    explanation: "Dans une dictature, le pouvoir est concentré entre les mains d'une seule personne ou d'un parti. La presse est contrôlée, les opposants sont réprimés et les élections sont truquées.",
    hint: "Dictature = absence de libertés fondamentales.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-024',
    subject: 'decouverte_du_monde',
    title: "Le travail des enfants",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'droits_enfant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'UNICEF estime que des millions d'enfants dans le monde travaillent de manière dangereuse. C'est une violation de…",
    options: [
      { id: 'a', text: "la loi sur le commerce international", isCorrect: false },
      { id: 'b', text: "la Convention internationale des droits de l'enfant (CIDE)", isCorrect: true },
      { id: 'c', text: "la Constitution française uniquement", isCorrect: false },
      { id: 'd', text: "aucune loi internationale", isCorrect: false },
    ],
    correctAnswer: "la Convention internationale des droits de l'enfant (CIDE)",
    explanation: "La CIDE protège les enfants contre le travail exploiteur. L'article 32 interdit le travail qui nuit à la santé ou à l'éducation de l'enfant.",
    hint: "La CIDE protège les enfants contre l'exploitation et le travail dangereux.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-025',
    subject: 'decouverte_du_monde',
    title: "Le développement durable",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le développement durable repose sur trois piliers. Lesquels ?",
    options: [
      { id: 'a', text: "Économie, politique, culture", isCorrect: false },
      { id: 'b', text: "Économie, société, environnement", isCorrect: true },
      { id: 'c', text: "Éducation, santé, logement", isCorrect: false },
      { id: 'd', text: "Énergie, eau, nourriture", isCorrect: false },
    ],
    correctAnswer: "Économie, société, environnement",
    explanation: "Le développement durable (défini en 1987 par le rapport Brundtland) vise à répondre aux besoins du présent sans compromettre ceux des générations futures, en articulant économie, équité sociale et protection de l'environnement.",
    hint: "3 E : Économie + Équité sociale + Environnement.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-026',
    subject: 'decouverte_du_monde',
    title: "Les migrations",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un réfugié, selon la Convention de Genève (1951), est une personne qui…",
    options: [
      { id: 'a', text: "voyage pour le tourisme", isCorrect: false },
      { id: 'b', text: "fuit son pays en raison de persécutions et ne peut y retourner en sécurité", isCorrect: true },
      { id: 'c', text: "travaille dans un autre pays", isCorrect: false },
      { id: 'd', text: "étudie à l'étranger", isCorrect: false },
    ],
    correctAnswer: "fuit son pays en raison de persécutions et ne peut y retourner en sécurité",
    explanation: "Un réfugié fuit son pays à cause de persécutions liées à sa race, religion, nationalité, opinions politiques ou appartenance à un groupe social. Il bénéficie d'une protection internationale.",
    hint: "Réfugié ≠ migrant économique. Le réfugié fuit la persécution.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-027',
    subject: 'decouverte_du_monde',
    title: "Le G20",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le G20 réunit les 20 principales économies mondiales. La France en fait-elle partie ?",
    options: [
      { id: 'a', text: "Non, la France n'est pas assez grande.", isCorrect: false },
      { id: 'b', text: "Oui, la France est membre du G20.", isCorrect: true },
      { id: 'c', text: "Seulement depuis 2010.", isCorrect: false },
      { id: 'd', text: "Uniquement via l'UE.", isCorrect: false },
    ],
    correctAnswer: "Oui, la France est membre du G20.",
    explanation: "La France est l'une des 20 grandes économies membres du G20. Elle y représente à la fois ses intérêts nationaux et contribue aux décisions économiques mondiales.",
    hint: "La France est dans le top 10 des économies mondiales.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-028',
    subject: 'decouverte_du_monde',
    title: "La séparation des Églises et de l'État",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La loi de séparation des Églises et de l'État est adoptée en France en…",
    options: [
      { id: 'a', text: '1789', isCorrect: false },
      { id: 'b', text: '1905', isCorrect: true },
      { id: 'c', text: '1945', isCorrect: false },
      { id: 'd', text: '1958', isCorrect: false },
    ],
    correctAnswer: '1905',
    explanation: "La loi du 9 décembre 1905 sépare l'Église de l'État en France et établit la laïcité. Elle garantit la liberté de conscience et interdit à l'État de financer les cultes.",
    hint: "1905 = loi de la séparation Église/État = laïcité.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-029',
    subject: 'decouverte_du_monde',
    title: "Fake news et esprit critique",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Face à une information sur internet, quelle est la première chose à faire pour vérifier si elle est vraie ?",
    options: [
      { id: 'a', text: "La partager immédiatement à ses amis.", isCorrect: false },
      { id: 'b', text: "Vérifier la source et chercher d'autres sources fiables qui confirment.", isCorrect: true },
      { id: 'c', text: "L'accepter si elle est partagée par beaucoup de personnes.", isCorrect: false },
      { id: 'd', text: "La croire si elle est bien écrite.", isCorrect: false },
    ],
    correctAnswer: "Vérifier la source et chercher d'autres sources fiables qui confirment.",
    explanation: "L'esprit critique exige de toujours vérifier l'origine d'une information, de la croiser avec d'autres sources fiables avant de la partager. Le nombre de partages ne garantit pas la véracité.",
    hint: "Qui dit quoi ? Où ? Pourquoi ? La source est-elle fiable et indépendante ?",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-030',
    subject: 'decouverte_du_monde',
    title: "Le Conseil de sécurité de l'ONU",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Conseil de sécurité de l'ONU compte 5 membres permanents avec un droit de veto. La France en fait-elle partie ?",
    options: [
      { id: 'a', text: "Non", isCorrect: false },
      { id: 'b', text: "Oui", isCorrect: true },
      { id: 'c', text: "Seulement depuis 2000", isCorrect: false },
      { id: 'd', text: "La France a perdu son siège en 1970", isCorrect: false },
    ],
    correctAnswer: "Oui",
    explanation: "Les 5 membres permanents du Conseil de sécurité (P5) sont : France, Royaume-Uni, États-Unis, Russie, Chine. Chacun dispose d'un droit de veto pour bloquer toute résolution.",
    hint: "Les P5 sont les vainqueurs de la 2e Guerre mondiale : France, UK, USA, Russie, Chine.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-031',
    subject: 'decouverte_du_monde',
    title: "Défense nationale",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, qui est le chef des armées ?",
    options: [
      { id: 'a', text: "Le Premier ministre", isCorrect: false },
      { id: 'b', text: "Le Président de la République", isCorrect: true },
      { id: 'c', text: "Le ministre de la Défense", isCorrect: false },
      { id: 'd', text: "Le chef d'état-major", isCorrect: false },
    ],
    correctAnswer: "Le Président de la République",
    explanation: "Selon l'article 15 de la Constitution, le Président de la République est le chef des armées. Il décide des opérations militaires françaises à l'étranger.",
    hint: "Le Président est à la fois chef de l'État et chef des armées.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-rep-032',
    subject: 'decouverte_du_monde',
    title: "Résumé : institutions de la Ve République",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'reperes',
    subskill: 'institutions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle institution française est chargée de contrôler les finances de l'État et de certifier les comptes publics ?",
    options: [
      { id: 'a', text: "Le Conseil constitutionnel", isCorrect: false },
      { id: 'b', text: "La Cour des comptes", isCorrect: true },
      { id: 'c', text: "Le Parlement", isCorrect: false },
      { id: 'd', text: "L'Autorité de la concurrence", isCorrect: false },
    ],
    correctAnswer: "La Cour des comptes",
    explanation: "La Cour des comptes est une institution indépendante chargée de vérifier que l'argent public est bien utilisé. Elle publie des rapports annuels et peut dénoncer des irrégularités.",
    hint: "La Cour des comptes = le « vérificateur » des finances publiques.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
