import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm2EspaceMondeExercises: DecouverteExercise[] = [

  {
    id: 'ddm-cm2-esp-004',
    subject: 'decouverte_du_monde',
    title: "Les continents",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'continents',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Combien y a-t-il de continents sur la Terre ?",
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
      { id: 'd', text: '4', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: "Les 7 continents sont : Afrique, Antarctique, Asie, Amérique du Nord, Amérique du Sud, Europe, Océanie. Certaines conventions regroupent les Amériques (6 continents) mais la convention française retient 6 ou 7.",
    hint: "Afrique, Asie, Europe, Amériques (x2), Océanie, Antarctique = 7.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-005',
    subject: 'decouverte_du_monde',
    title: "Les océans",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'continents',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le plus grand océan du monde ?",
    options: [
      { id: 'a', text: "Océan Atlantique", isCorrect: false },
      { id: 'b', text: "Océan Pacifique", isCorrect: true },
      { id: 'c', text: "Océan Indien", isCorrect: false },
      { id: 'd', text: "Océan Arctique", isCorrect: false },
    ],
    correctAnswer: "Océan Pacifique",
    explanation: "L'océan Pacifique est le plus grand et le plus profond des 5 océans. Il couvre plus de la moitié de la surface océanique mondiale et contient la fosse des Mariannes (le point le plus profond).",
    hint: "Pacifique = moitié de la surface des océans.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-006',
    subject: 'decouverte_du_monde',
    title: "Le continent africain",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'continents',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Afrique est le continent qui compte le plus grand nombre de…",
    options: [
      { id: 'a', text: "glaciers", isCorrect: false },
      { id: 'b', text: "pays (54 États reconnus)", isCorrect: true },
      { id: 'c', text: "habitants", isCorrect: false },
      { id: 'd', text: "millionnaires", isCorrect: false },
    ],
    correctAnswer: "pays (54 États reconnus)",
    explanation: "L'Afrique compte 54 États reconnus par l'Union africaine, ce qui en fait le continent avec le plus grand nombre de pays. Elle est aussi le 2e plus grand continent par la superficie.",
    hint: "L'Afrique compte plus de pays que tout autre continent.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-007',
    subject: 'decouverte_du_monde',
    title: "L'Asie : le plus grand continent",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'continents',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Asie est le plus grand continent. Laquelle de ces capitales n'est PAS en Asie ?",
    options: [
      { id: 'a', text: "Tokyo (Japon)", isCorrect: false },
      { id: 'b', text: "Pékin (Chine)", isCorrect: false },
      { id: 'c', text: "Le Caire (Égypte)", isCorrect: true },
      { id: 'd', text: "New Delhi (Inde)", isCorrect: false },
    ],
    correctAnswer: "Le Caire (Égypte)",
    explanation: "Le Caire est la capitale de l'Égypte, pays situé en Afrique (même si la péninsule du Sinaï est en Asie). Tokyo, Pékin et New Delhi sont bien des capitales asiatiques.",
    hint: "L'Égypte est en Afrique, même si elle est souvent associée au Proche-Orient.",
    estimatedMinutes: 1,
    adaptations: A,
    meta: { visualLoad: 'high' },
  },
  {
    id: 'ddm-cm2-esp-008',
    subject: 'decouverte_du_monde',
    title: "La Chine et l'Inde",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le pays le plus peuplé du monde en 2024 ?",
    options: [
      { id: 'a', text: "La Chine", isCorrect: false },
      { id: 'b', text: "L'Inde", isCorrect: true },
      { id: 'c', text: "Les États-Unis", isCorrect: false },
      { id: 'd', text: "Le Nigéria", isCorrect: false },
    ],
    correctAnswer: "L'Inde",
    explanation: "En 2023-2024, l'Inde a dépassé la Chine pour devenir le pays le plus peuplé du monde avec plus de 1,4 milliard d'habitants. Sa capitale est New Delhi.",
    hint: "En 2023, l'Inde a dépassé la Chine au classement démographique.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-009',
    subject: 'decouverte_du_monde',
    title: "Les États-Unis",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La capitale des États-Unis est…",
    options: [
      { id: 'a', text: "New York", isCorrect: false },
      { id: 'b', text: "Washington D.C.", isCorrect: true },
      { id: 'c', text: "Los Angeles", isCorrect: false },
      { id: 'd', text: "Chicago", isCorrect: false },
    ],
    correctAnswer: "Washington D.C.",
    explanation: "Washington D.C. (District of Columbia) est la capitale fédérale des États-Unis. La Maison Blanche, le Capitole et la Cour Suprême s'y trouvent. New York est la plus grande ville mais n'est pas la capitale.",
    hint: "La plus grande ville d'un pays n'est pas toujours sa capitale.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-010',
    subject: 'decouverte_du_monde',
    title: "Le Brésil",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Brésil est le plus grand pays d'Amérique du Sud. Sa capitale est…",
    options: [
      { id: 'a', text: "Rio de Janeiro", isCorrect: false },
      { id: 'b', text: "Brasília", isCorrect: true },
      { id: 'c', text: "São Paulo", isCorrect: false },
      { id: 'd', text: "Salvador", isCorrect: false },
    ],
    correctAnswer: "Brasília",
    explanation: "Brasília est la capitale du Brésil, construite de toutes pièces dans les années 1950. Rio de Janeiro et São Paulo sont les plus grandes villes mais ne sont pas la capitale.",
    hint: "Brasília a été construite exprès pour être la capitale du Brésil.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-011',
    subject: 'decouverte_du_monde',
    title: "L'Amazonie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La forêt amazonienne est souvent appelée « le poumon de la Terre ». Elle se trouve principalement en…",
    options: [
      { id: 'a', text: "Afrique centrale (Congo)", isCorrect: false },
      { id: 'b', text: "Amérique du Sud (Brésil et pays voisins)", isCorrect: true },
      { id: 'c', text: "Asie du Sud-Est (Indonésie)", isCorrect: false },
      { id: 'd', text: "Amérique du Nord (Canada)", isCorrect: false },
    ],
    correctAnswer: "Amérique du Sud (Brésil et pays voisins)",
    explanation: "La forêt amazonienne couvre environ 5,5 millions de km², principalement au Brésil mais aussi en Colombie, Pérou, Venezuela et autres. Elle produit 20 % de l'oxygène terrestre.",
    hint: "Amazonie = fleuve Amazone = Amérique du Sud.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-012',
    subject: 'decouverte_du_monde',
    title: "La Russie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Russie s'étend sur combien de fuseaux horaires ?",
    options: [
      { id: 'a', text: "3", isCorrect: false },
      { id: 'b', text: "11", isCorrect: true },
      { id: 'c', text: "6", isCorrect: false },
      { id: 'd', text: "24", isCorrect: false },
    ],
    correctAnswer: "11",
    explanation: "La Russie est le plus grand pays du monde (17 millions de km²) et s'étend sur 11 fuseaux horaires, de Kaliningrad (Europe) à l'extrême est de la Sibérie.",
    hint: "La Russie traverse 11 fuseaux horaires — de l'Europe à l'Asie.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-013',
    subject: 'decouverte_du_monde',
    title: "L'Antarctique",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'continents',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Antarctique est un continent particulier car…",
    options: [
      { id: 'a', text: "il est le plus peuplé du monde", isCorrect: false },
      { id: 'b', text: "il n'appartient à aucun pays et est protégé par un traité international", isCorrect: true },
      { id: 'c', text: "il appartient à l'Australie", isCorrect: false },
      { id: 'd', text: "c'est un désert de sable chaud", isCorrect: false },
    ],
    correctAnswer: "il n'appartient à aucun pays et est protégé par un traité international",
    explanation: "Le traité sur l'Antarctique (1959) interdit toute activité militaire et revendication territoriale. L'Antarctique est dédié à la recherche scientifique. C'est un désert de glace, le plus froid du monde.",
    hint: "Antarctique = continent neutre, réservé à la science.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-014',
    subject: 'decouverte_du_monde',
    title: "Le Canada",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Canada est le 2e plus grand pays du monde par la superficie. Sa capitale est…",
    options: [
      { id: 'a', text: "Toronto", isCorrect: false },
      { id: 'b', text: "Ottawa", isCorrect: true },
      { id: 'c', text: "Montréal", isCorrect: false },
      { id: 'd', text: "Vancouver", isCorrect: false },
    ],
    correctAnswer: "Ottawa",
    explanation: "Ottawa est la capitale du Canada. La ville est bilingue (anglais et français). Toronto est la plus grande ville, mais Ottawa est la capitale fédérale.",
    hint: "Ottawa, pas Toronto ni Montréal.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-015',
    subject: 'decouverte_du_monde',
    title: "L'Australie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Australie est à la fois un pays et un continent. Sa capitale est…",
    options: [
      { id: 'a', text: "Sydney", isCorrect: false },
      { id: 'b', text: "Canberra", isCorrect: true },
      { id: 'c', text: "Melbourne", isCorrect: false },
      { id: 'd', text: "Brisbane", isCorrect: false },
    ],
    correctAnswer: "Canberra",
    explanation: "Canberra est la capitale de l'Australie. Elle a été choisie comme compromis entre Sydney et Melbourne (les deux plus grandes villes rivales). L'Australie est en Océanie.",
    hint: "Sydney est la plus célèbre, mais Canberra est la capitale.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-016',
    subject: 'decouverte_du_monde',
    title: "Les déserts du monde",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'relief',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le plus grand désert du monde ?",
    options: [
      { id: 'a', text: "Le Sahara (Afrique)", isCorrect: false },
      { id: 'b', text: "L'Antarctique (désert froid)", isCorrect: true },
      { id: 'c', text: "Le désert de Gobi (Asie)", isCorrect: false },
      { id: 'd', text: "L'Atacama (Amérique du Sud)", isCorrect: false },
    ],
    correctAnswer: "L'Antarctique (désert froid)",
    explanation: "L'Antarctique est le plus grand désert du monde (14 millions de km²). Un désert est une région très aride. Le Sahara (~9 millions de km²) est le plus grand désert chaud.",
    hint: "Un désert n'est pas forcément chaud : il peut être froid et glacé.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-017',
    subject: 'decouverte_du_monde',
    title: "Le Japon",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Japon est un archipel situé en Asie de l'Est. Sa capitale est…",
    options: [
      { id: 'a', text: "Osaka", isCorrect: false },
      { id: 'b', text: "Tokyo", isCorrect: true },
      { id: 'c', text: "Kyoto", isCorrect: false },
      { id: 'd', text: "Hiroshima", isCorrect: false },
    ],
    correctAnswer: "Tokyo",
    explanation: "Tokyo est la capitale du Japon et l'une des plus grandes métropoles du monde (~37 millions d'habitants dans l'agglomération). Le Japon est composé de 4 grandes îles et environ 6 000 îles.",
    hint: "Tokyo est la plus grande métropole du monde.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-018',
    subject: 'decouverte_du_monde',
    title: "L'Himalaya",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'relief',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le mont Everest (8 849 m), le point le plus haut du monde, est situé dans…",
    options: [
      { id: 'a', text: "Les Alpes (Europe)", isCorrect: false },
      { id: 'b', text: "L'Himalaya (entre Népal et Chine)", isCorrect: true },
      { id: 'c', text: "Les Andes (Amérique du Sud)", isCorrect: false },
      { id: 'd', text: "L'Atlas (Afrique du Nord)", isCorrect: false },
    ],
    correctAnswer: "L'Himalaya (entre Népal et Chine)",
    explanation: "Le mont Everest (8 849 m) est le sommet le plus haut du monde. Il se trouve dans l'Himalaya, à la frontière du Népal et du Tibet (Chine). Les 10 plus hauts sommets sont tous dans l'Himalaya.",
    hint: "Everest = Himalaya = Asie. Pas les Alpes !",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-019',
    subject: 'decouverte_du_monde',
    title: "La francophonie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le français est parlé dans environ combien de pays dans le monde ?",
    options: [
      { id: 'a', text: "12 pays", isCorrect: false },
      { id: 'b', text: "87 pays (dont 29 où il est officiel)", isCorrect: true },
      { id: 'c', text: "50 pays", isCorrect: false },
      { id: 'd', text: "5 pays", isCorrect: false },
    ],
    correctAnswer: "87 pays (dont 29 où il est officiel)",
    explanation: "Le français est parlé dans 87 pays ou territoires selon l'OIF (Organisation internationale de la Francophonie). Il est langue officielle dans 29 pays, majoritairement en Afrique.",
    hint: "Le français est la 5e langue la plus parlée dans le monde.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-020',
    subject: 'decouverte_du_monde',
    title: "Les méridiens et parallèles",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'reperes_cartographiques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le méridien de Greenwich (0°) partage la Terre en…",
    options: [
      { id: 'a', text: "hémisphère nord et hémisphère sud", isCorrect: false },
      { id: 'b', text: "hémisphère ouest et hémisphère est", isCorrect: true },
      { id: 'c', text: "zone tropicale et zone polaire", isCorrect: false },
      { id: 'd', text: "fuseaux horaires uniquement", isCorrect: false },
    ],
    correctAnswer: "hémisphère ouest et hémisphère est",
    explanation: "Le méridien 0° (Greenwich) est la référence des longitudes. Il divise la Terre en hémisphère ouest (longitude négative) et hémisphère est. L'équateur (0° de latitude) divise nord/sud.",
    hint: "Greenwich → longitude → est/ouest. Équateur → latitude → nord/sud.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-021',
    subject: 'decouverte_du_monde',
    title: "La population mondiale",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La population mondiale est d'environ… en 2024.",
    options: [
      { id: 'a', text: "5 milliards", isCorrect: false },
      { id: 'b', text: "8 milliards", isCorrect: true },
      { id: 'c', text: "10 milliards", isCorrect: false },
      { id: 'd', text: "3 milliards", isCorrect: false },
    ],
    correctAnswer: "8 milliards",
    explanation: "La population mondiale a atteint 8 milliards d'habitants en novembre 2022. L'Asie concentre environ 60 % de la population mondiale. La croissance démographique est la plus forte en Afrique.",
    hint: "8 milliards en 2022-2024.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-022',
    subject: 'decouverte_du_monde',
    title: "Les DOM-TOM français dans le monde",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Polynésie française, territoire d'outre-mer français, est située dans…",
    options: [
      { id: 'a', text: "l'océan Atlantique", isCorrect: false },
      { id: 'b', text: "l'océan Pacifique", isCorrect: true },
      { id: 'c', text: "l'océan Indien", isCorrect: false },
      { id: 'd', text: "la mer Méditerranée", isCorrect: false },
    ],
    correctAnswer: "l'océan Pacifique",
    explanation: "La Polynésie française (Tahiti et ses îles) est un territoire d'outre-mer français dans l'océan Pacifique Sud, à plus de 18 000 km de Paris. Bora-Bora en est l'île la plus connue.",
    hint: "Tahiti, Bora-Bora → Pacifique Sud.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-023',
    subject: 'decouverte_du_monde',
    title: "Le Nil et l'Amazone",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'relief',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel fleuve est considéré comme le plus long du monde ?",
    options: [
      { id: 'a', text: "L'Amazone (Amérique du Sud)", isCorrect: false },
      { id: 'b', text: "Le Nil (Afrique)", isCorrect: true },
      { id: 'c', text: "Le Yangtsé (Chine)", isCorrect: false },
      { id: 'd', text: "Le Mississippi (États-Unis)", isCorrect: false },
    ],
    correctAnswer: "Le Nil (Afrique)",
    explanation: "Le Nil (~6 650 km) est généralement considéré comme le plus long fleuve du monde. Il traverse le Soudan et l'Égypte et se jette dans la Méditerranée. L'Amazone est le plus grand débit.",
    hint: "Nil = le plus long (Afrique). Amazone = le plus grand volume d'eau.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-024',
    subject: 'decouverte_du_monde',
    title: "Capitales d'Afrique",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Nairobi est la capitale de…",
    options: [
      { id: 'a', text: "l'Éthiopie", isCorrect: false },
      { id: 'b', text: "le Kenya", isCorrect: true },
      { id: 'c', text: "la Tanzanie", isCorrect: false },
      { id: 'd', text: "le Nigéria", isCorrect: false },
    ],
    correctAnswer: "le Kenya",
    explanation: "Nairobi est la capitale du Kenya, en Afrique de l'Est. C'est aussi le siège du Programme des Nations Unies pour l'environnement (PNUE). Le Kenya est célèbre pour ses safaris et sa faune.",
    hint: "Kenya + Nairobi + Afrique de l'Est + safaris.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-025',
    subject: 'decouverte_du_monde',
    title: "L'Inde",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Inde est un sous-continent. Sa capitale est…",
    options: [
      { id: 'a', text: "Bombay (Mumbai)", isCorrect: false },
      { id: 'b', text: "New Delhi", isCorrect: true },
      { id: 'c', text: "Calcutta (Kolkata)", isCorrect: false },
      { id: 'd', text: "Bangalore", isCorrect: false },
    ],
    correctAnswer: "New Delhi",
    explanation: "New Delhi est la capitale de l'Inde. Mumbai (Bombay) est la plus grande ville et le centre économique. L'Inde est une démocratie parlementaire et la plus grande démocratie du monde par le nombre d'électeurs.",
    hint: "New Delhi est la capitale, Mumbai est la ville financière.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-026',
    subject: 'decouverte_du_monde',
    title: "Le commerce mondial",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel pays est le premier exportateur mondial de marchandises en valeur ?",
    options: [
      { id: 'a', text: "Les États-Unis", isCorrect: false },
      { id: 'b', text: "La Chine", isCorrect: true },
      { id: 'c', text: "l'Allemagne", isCorrect: false },
      { id: 'd', text: "le Japon", isCorrect: false },
    ],
    correctAnswer: "La Chine",
    explanation: "La Chine est le premier exportateur mondial depuis 2009. Elle exporte des produits manufacturés, de l'électronique, des vêtements et des machines dans le monde entier.",
    hint: "Beaucoup de produits fabriqués dans le monde portent « Made in China ».",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-esp-027',
    subject: 'decouverte_du_monde',
    title: "La Méditerranée",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'relief',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La mer Méditerranée est bordée par des pays de 3 continents. Lesquels ?",
    options: [
      { id: 'a', text: "Asie, Afrique, Amérique", isCorrect: false },
      { id: 'b', text: "Europe, Afrique, Asie", isCorrect: true },
      { id: 'c', text: "Europe, Amérique, Océanie", isCorrect: false },
      { id: 'd', text: "Europe uniquement", isCorrect: false },
    ],
    correctAnswer: "Europe, Afrique, Asie",
    explanation: "La Méditerranée est bordée par l'Europe (France, Espagne, Italie…), l'Afrique (Maroc, Algérie, Tunisie, Libye, Égypte…) et l'Asie (Turquie, Liban, Israël, Syrie…).",
    hint: "Méditerranée = 3 continents autour : Europe, Afrique, Asie.",
    estimatedMinutes: 1,
    adaptations: A,
    meta: { visualLoad: 'high' },
  },
  {
    id: 'ddm-cm2-esp-028',
    subject: 'decouverte_du_monde',
    title: "Les ressources naturelles",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'espace',
    subskill: 'pays_monde',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'eau douce représente environ combien de pourcent de l'eau sur la Terre ?",
    options: [
      { id: 'a', text: "50 %", isCorrect: false },
      { id: 'b', text: "3 %", isCorrect: true },
      { id: 'c', text: "20 %", isCorrect: false },
      { id: 'd', text: "75 %", isCorrect: false },
    ],
    correctAnswer: "3 %",
    explanation: "Seulement 3 % de l'eau sur Terre est de l'eau douce (dont les 2/3 sont sous forme de glace polaire). Seulement 1 % est accessible pour la consommation humaine. L'eau est donc une ressource précieuse.",
    hint: "97 % de l'eau est salée (océans). Seulement 3 % est douce.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
