import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm2TempsHistoireExercises: DecouverteExercise[] = [

  {
    id: 'ddm-cm2-tem-004',
    subject: 'decouverte_du_monde',
    title: "La 2e Guerre mondiale",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Seconde Guerre mondiale se déroule de…",
    options: [
      { id: 'a', text: '1914 à 1918', isCorrect: false },
      { id: 'b', text: '1939 à 1945', isCorrect: true },
      { id: 'c', text: '1936 à 1940', isCorrect: false },
      { id: 'd', text: '1940 à 1944', isCorrect: false },
    ],
    correctAnswer: '1939 à 1945',
    explanation: "La Seconde Guerre mondiale dure de 1939 (invasion de la Pologne par l'Allemagne nazie) à 1945 (capitulations allemande en mai et japonaise en septembre).",
    hint: "39-45 → 2e Guerre mondiale.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-005',
    subject: 'decouverte_du_monde',
    title: "L'Occupation et la Résistance",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Pendant la 2e Guerre mondiale, la France est occupée par l'Allemagne nazie (1940–1944). Le chef du gouvernement collaborationniste de Vichy est…",
    options: [
      { id: 'a', text: 'Charles de Gaulle', isCorrect: false },
      { id: 'b', text: 'Philippe Pétain', isCorrect: true },
      { id: 'c', text: 'Napoléon III', isCorrect: false },
      { id: 'd', text: 'Jean Moulin', isCorrect: false },
    ],
    correctAnswer: 'Philippe Pétain',
    explanation: "Le maréchal Pétain dirige le régime de Vichy qui collabore avec l'occupant nazi. En face, de Gaulle organise la Résistance depuis Londres, et Jean Moulin unifie la Résistance intérieure.",
    hint: "Pétain = Vichy, collaboration. De Gaulle = Résistance, Londres.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-006',
    subject: 'decouverte_du_monde',
    title: "Le débarquement de Normandie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Débarquement en Normandie (Jour J) a lieu le…",
    options: [
      { id: 'a', text: '11 novembre 1918', isCorrect: false },
      { id: 'b', text: '6 juin 1944', isCorrect: true },
      { id: 'c', text: '8 mai 1945', isCorrect: false },
      { id: 'd', text: '14 juillet 1789', isCorrect: false },
    ],
    correctAnswer: '6 juin 1944',
    explanation: "Le 6 juin 1944 (D-Day), les Alliés débarquent sur les plages de Normandie (Utah, Omaha, Gold, Sword, Juno). Cette opération marque le tournant de la guerre à l'ouest.",
    hint: "Le Jour J = 6 juin 1944 = libération de la France commence.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-007',
    subject: 'decouverte_du_monde',
    title: "La Shoah",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Shoah désigne le génocide des Juifs d'Europe par les nazis. Environ combien de victimes a-t-elle causé ?",
    options: [
      { id: 'a', text: '600 000', isCorrect: false },
      { id: 'b', text: '6 millions', isCorrect: true },
      { id: 'c', text: '100 000', isCorrect: false },
      { id: 'd', text: '60 000', isCorrect: false },
    ],
    correctAnswer: '6 millions',
    explanation: "La Shoah a causé la mort d'environ 6 millions de Juifs européens, assassinés dans les camps d'extermination nazis (Auschwitz, Treblinka, Sobibor…).",
    hint: "La Shoah est l'un des plus grands crimes de l'histoire de l'humanité.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-008',
    subject: 'decouverte_du_monde',
    title: "La Ve République",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Ve République est fondée en 1958 par…",
    options: [
      { id: 'a', text: 'François Mitterrand', isCorrect: false },
      { id: 'b', text: 'Charles de Gaulle', isCorrect: true },
      { id: 'c', text: 'Napoléon III', isCorrect: false },
      { id: 'd', text: 'Georges Pompidou', isCorrect: false },
    ],
    correctAnswer: 'Charles de Gaulle',
    explanation: "La Ve République est fondée par de Gaulle le 4 octobre 1958. Elle renforce le pouvoir exécutif (Président) par rapport aux Républiques précédentes.",
    hint: "De Gaulle revient au pouvoir en 1958 et écrit une nouvelle Constitution.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-009',
    subject: 'decouverte_du_monde',
    title: "Mai 68",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les événements de Mai 68 en France sont principalement…",
    options: [
      { id: 'a', text: "une tentative de coup d'État militaire", isCorrect: false },
      { id: 'b', text: "un grand mouvement de contestation sociale et étudiante", isCorrect: true },
      { id: 'c', text: "une guerre entre la France et l'Allemagne", isCorrect: false },
      { id: 'd', text: "la fondation de la Ve République", isCorrect: false },
    ],
    correctAnswer: "un grand mouvement de contestation sociale et étudiante",
    explanation: "Mai 68 est une crise sociale majeure : étudiants et ouvriers se mobilisent pour plus de libertés et de droits sociaux. Cela conduit à des réformes importantes en France.",
    hint: "« Il est interdit d'interdire » — slogan de Mai 68.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-010',
    subject: 'decouverte_du_monde',
    title: "La chute du mur de Berlin",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le mur de Berlin, symbole de la Guerre froide, tombe le…",
    options: [
      { id: 'a', text: '9 novembre 1969', isCorrect: false },
      { id: 'b', text: '9 novembre 1989', isCorrect: true },
      { id: 'c', text: '9 novembre 1979', isCorrect: false },
      { id: 'd', text: '9 novembre 1945', isCorrect: false },
    ],
    correctAnswer: '9 novembre 1989',
    explanation: "Le mur de Berlin est construit en 1961 et tombe le 9 novembre 1989. Sa chute marque la fin de la Guerre froide et conduit à la réunification de l'Allemagne en 1990.",
    hint: "La chute du mur de Berlin = fin de la Guerre froide.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-011',
    subject: 'decouverte_du_monde',
    title: "La décolonisation",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La décolonisation correspond principalement à…",
    options: [
      { id: 'a', text: "la conquête coloniale de l'Afrique par l'Europe au XIXe siècle", isCorrect: false },
      { id: 'b', text: "l'indépendance des pays colonisés, surtout après 1945", isCorrect: true },
      { id: 'c', text: "la colonisation de l'Amérique au XVIe siècle", isCorrect: false },
      { id: 'd', text: "la fin de la Première Guerre mondiale", isCorrect: false },
    ],
    correctAnswer: "l'indépendance des pays colonisés, surtout après 1945",
    explanation: "La décolonisation est le processus par lequel les pays colonisés ont obtenu leur indépendance, surtout dans les années 1950–1970. L'Algérie, par exemple, obtient son indépendance en 1962.",
    hint: "Après 1945, de nombreux pays africains et asiatiques deviennent indépendants.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-012',
    subject: 'decouverte_du_monde',
    title: "La Révolution industrielle",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Révolution industrielle du XIXe siècle transforme les sociétés. Quelle invention en est le symbole en France ?",
    options: [
      { id: 'a', text: "L'imprimerie", isCorrect: false },
      { id: 'b', text: "Le chemin de fer à vapeur", isCorrect: true },
      { id: 'c', text: "L'automobile", isCorrect: false },
      { id: 'd', text: "L'avion", isCorrect: false },
    ],
    correctAnswer: "Le chemin de fer à vapeur",
    explanation: "Le chemin de fer (première ligne en France : Lyon-Saint-Étienne, 1827) est le symbole de la Révolution industrielle. Il transforme les transports, l'économie et les échanges.",
    hint: "Train à vapeur + usines + charbon = Révolution industrielle.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-013',
    subject: 'decouverte_du_monde',
    title: "La Première Guerre mondiale",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'armistice de la Première Guerre mondiale est signé le…",
    options: [
      { id: 'a', text: '8 mai 1945', isCorrect: false },
      { id: 'b', text: '11 novembre 1918', isCorrect: true },
      { id: 'c', text: '14 juillet 1789', isCorrect: false },
      { id: 'd', text: '6 juin 1944', isCorrect: false },
    ],
    correctAnswer: '11 novembre 1918',
    explanation: "L'armistice mettant fin à la Première Guerre mondiale est signé le 11 novembre 1918 à 11h dans un wagon à Rethondes (Oise). C'est pourquoi le 11 novembre est un jour férié en France.",
    hint: "11/11/1918 à 11h → armistice 1e Guerre mondiale.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-014',
    subject: 'decouverte_du_monde',
    title: "La Révolution française et ses symboles",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis XVI est guillotiné pendant la Révolution française en…",
    options: [
      { id: 'a', text: '1789', isCorrect: false },
      { id: 'b', text: '1793', isCorrect: true },
      { id: 'c', text: '1799', isCorrect: false },
      { id: 'd', text: '1804', isCorrect: false },
    ],
    correctAnswer: '1793',
    explanation: "Louis XVI est guillotiné le 21 janvier 1793, pendant la Terreur révolutionnaire. La monarchie est abolie le 21 septembre 1792 avec la proclamation de la Première République.",
    hint: "Louis XVI : roi jusqu'en 1793, puis guillotiné.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-015',
    subject: 'decouverte_du_monde',
    title: "Napoléon III et le Second Empire",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Second Empire de Napoléon III se termine avec…",
    options: [
      { id: 'a', text: "la Révolution française", isCorrect: false },
      { id: 'b', text: "la défaite contre la Prusse (guerre de 1870) et la Commune de Paris", isCorrect: true },
      { id: 'c', text: "la mort naturelle de Napoléon III", isCorrect: false },
      { id: 'd', text: "l'armistice de 1918", isCorrect: false },
    ],
    correctAnswer: "la défaite contre la Prusse (guerre de 1870) et la Commune de Paris",
    explanation: "Napoléon III est capturé lors de la défaite de Sedan (septembre 1870) face à la Prusse. La IIIe République est proclamée, et Paris vit la Commune (insurrection) en 1871.",
    hint: "1870 : défaite de Sedan = fin du Second Empire → IIIe République.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-016',
    subject: 'decouverte_du_monde',
    title: "La IIIe République",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La IIIe République (1870–1940) est notamment marquée par…",
    options: [
      { id: 'a', text: "la restauration de la monarchie en France", isCorrect: false },
      { id: 'b', text: "les lois Jules Ferry sur l'école laïque, gratuite et obligatoire (1882)", isCorrect: true },
      { id: 'c', text: "la fondation de l'Empire colonial romain", isCorrect: false },
      { id: 'd', text: "la Révolution française", isCorrect: false },
    ],
    correctAnswer: "les lois Jules Ferry sur l'école laïque, gratuite et obligatoire (1882)",
    explanation: "Sous la IIIe République, Jules Ferry réforme l'éducation : l'école primaire devient gratuite, laïque et obligatoire (1882). La loi de séparation de l'Église et de l'État est adoptée en 1905.",
    hint: "Jules Ferry → école pour tous → IIIe République.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-017',
    subject: 'decouverte_du_monde',
    title: "Les trente glorieuses",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les « Trente Glorieuses » désignent la période de forte croissance économique en France de…",
    options: [
      { id: 'a', text: '1914 à 1944', isCorrect: false },
      { id: 'b', text: '1945 à 1975', isCorrect: true },
      { id: 'c', text: '1968 à 1998', isCorrect: false },
      { id: 'd', text: '1918 à 1948', isCorrect: false },
    ],
    correctAnswer: '1945 à 1975',
    explanation: "Les Trente Glorieuses (1945–1975) sont une période de forte croissance économique, de plein emploi et d'amélioration du niveau de vie en France après la 2e Guerre mondiale.",
    hint: "30 ans de croissance après la guerre = Trente Glorieuses.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-018',
    subject: 'decouverte_du_monde',
    title: "La construction européenne",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le traité de Rome, fondateur de la CEE (ancêtre de l'UE), est signé en…",
    options: [
      { id: 'a', text: '1945', isCorrect: false },
      { id: 'b', text: '1957', isCorrect: true },
      { id: 'c', text: '1969', isCorrect: false },
      { id: 'd', text: '1992', isCorrect: false },
    ],
    correctAnswer: '1957',
    explanation: "Le traité de Rome est signé le 25 mars 1957 par 6 pays (France, Allemagne, Italie, Belgique, Pays-Bas, Luxembourg). Il crée la Communauté économique européenne (CEE), ancêtre de l'UE.",
    hint: "1957, 6 pays fondateurs → CEE → ancêtre de l'UE.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-019',
    subject: 'decouverte_du_monde',
    title: "Abolition de l'esclavage en France",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'esclavage est définitivement aboli en France (et ses colonies) en…",
    options: [
      { id: 'a', text: '1789', isCorrect: false },
      { id: 'b', text: '1848', isCorrect: true },
      { id: 'c', text: '1905', isCorrect: false },
      { id: 'd', text: '1944', isCorrect: false },
    ],
    correctAnswer: '1848',
    explanation: "L'esclavage est définitivement aboli par décret le 27 avril 1848, sous la IIe République, à l'initiative de Victor Schoelcher. La France avait brièvement aboli l'esclavage en 1794 avant de le rétablir en 1802 par Napoléon.",
    hint: "Schoelcher + IIe République = abolition définitive en 1848.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-020',
    subject: 'decouverte_du_monde',
    title: "Frise complexe : Xe–XXe siècles",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Classez ces événements du plus ancien au plus récent : A) Traité de Rome (1957) · B) Abolition de l'esclavage (1848) · C) Découverte de l'Amérique (1492) · D) Révolution française (1789)",
    options: [
      { id: 'a', text: "A, B, C, D", isCorrect: false },
      { id: 'b', text: "C, D, B, A", isCorrect: true },
      { id: 'c', text: "D, C, B, A", isCorrect: false },
      { id: 'd', text: "B, D, C, A", isCorrect: false },
    ],
    correctAnswer: "C, D, B, A",
    explanation: "Ordre chronologique : 1492 (Colomb) → 1789 (Révolution) → 1848 (abolition esclavage) → 1957 (traité de Rome).",
    hint: "Place les dates dans l'ordre croissant : 1492 < 1789 < 1848 < 1957.",
    estimatedMinutes: 1,
    meta: { numericLoad: 'medium' },
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-021',
    subject: 'decouverte_du_monde',
    title: "La Deuxième Guerre mondiale : bilan",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Seconde Guerre mondiale fait environ combien de victimes au total dans le monde ?",
    options: [
      { id: 'a', text: "5 millions", isCorrect: false },
      { id: 'b', text: "60 à 80 millions", isCorrect: true },
      { id: 'c', text: "10 millions", isCorrect: false },
      { id: 'd', text: "200 millions", isCorrect: false },
    ],
    correctAnswer: "60 à 80 millions",
    explanation: "La Seconde Guerre mondiale est le conflit le plus meurtrier de l'histoire : entre 60 et 80 millions de victimes (militaires et civils), dont 6 millions de Juifs victimes de la Shoah.",
    hint: "C'est le conflit le plus meurtrier de l'histoire humaine.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-022',
    subject: 'decouverte_du_monde',
    title: "Guerres napoléoniennes",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Napoléon est définitivement vaincu lors de la bataille de…",
    options: [
      { id: 'a', text: "Austerlitz (1805)", isCorrect: false },
      { id: 'b', text: "Waterloo (1815)", isCorrect: true },
      { id: 'c', text: "Iéna (1806)", isCorrect: false },
      { id: 'd', text: "Wagram (1809)", isCorrect: false },
    ],
    correctAnswer: "Waterloo (1815)",
    explanation: "La bataille de Waterloo (18 juin 1815, en Belgique) est la défaite définitive de Napoléon face aux armées alliées (Wellington/Blücher). Napoléon est ensuite exilé à Sainte-Hélène.",
    hint: "« Mon adversaire Waterloo, défaite que je dois porter ».",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-023',
    subject: 'decouverte_du_monde',
    title: "Louis XIV et l'absolutisme",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis XIV proclame « L'État, c'est moi ». Il règne pendant…",
    options: [
      { id: 'a', text: "30 ans", isCorrect: false },
      { id: 'b', text: "72 ans (1643–1715) — le plus long règne de l'histoire française", isCorrect: true },
      { id: 'c', text: "20 ans", isCorrect: false },
      { id: 'd', text: "50 ans", isCorrect: false },
    ],
    correctAnswer: "72 ans (1643–1715) — le plus long règne de l'histoire française",
    explanation: "Louis XIV règne de 1643 (à 4 ans !) à sa mort en 1715, soit 72 ans. C'est le plus long règne de monarque en Europe. Il centralise le pouvoir et fait construire Versailles.",
    hint: "Louis XIV monte sur le trône à 4 ans et règne 72 ans.",
    estimatedMinutes: 1,
    meta: { numericLoad: 'medium' },
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-024',
    subject: 'decouverte_du_monde',
    title: "La Grande Guerre : causes",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'assassinat de l'archiduc François-Ferdinand à Sarajevo le 28 juin 1914 déclenche la Première Guerre mondiale. Il est assassiné par…",
    options: [
      { id: 'a', text: "un espion allemand", isCorrect: false },
      { id: 'b', text: "un nationaliste serbe (Gavrilo Princip)", isCorrect: true },
      { id: 'c', text: "un soldat français", isCorrect: false },
      { id: 'd', text: "un anarchiste autrichien", isCorrect: false },
    ],
    correctAnswer: "un nationaliste serbe (Gavrilo Princip)",
    explanation: "Gavrilo Princip, nationaliste serbe, assassine l'archiduc austro-hongrois à Sarajevo. Cet événement déclenche une réaction en chaîne d'alliances et conduit à la Première Guerre mondiale.",
    hint: "L'étincelle : Sarajevo, 28 juin 1914 → guerre mondiale.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-025',
    subject: 'decouverte_du_monde',
    title: "Durée des grandes périodes",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la grande période la plus longue de l'histoire humaine ?",
    options: [
      { id: 'a', text: "L'Antiquité (environ 3000 ans)", isCorrect: false },
      { id: 'b', text: "La Préhistoire (environ 3 millions d'années)", isCorrect: true },
      { id: 'c', text: "Le Moyen Âge (environ 1000 ans)", isCorrect: false },
      { id: 'd', text: "Les Temps modernes (environ 300 ans)", isCorrect: false },
    ],
    correctAnswer: "La Préhistoire (environ 3 millions d'années)",
    explanation: "La Préhistoire débute avec l'apparition des premiers hominidés (environ -3 millions d'années) et s'achève avec l'invention de l'écriture (-3500 av. J.-C.). C'est de loin la période la plus longue.",
    hint: "L'histoire écrite = 5 500 ans. La Préhistoire = 3 millions d'années.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-026',
    subject: 'decouverte_du_monde',
    title: "Les Droits de la femme",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, quelle loi a accordé aux femmes la liberté de travailler sans l'autorisation de leur mari (1965) ?",
    options: [
      { id: 'a', text: "La loi Veil de 1975", isCorrect: false },
      { id: 'b', text: "La loi de juillet 1965 sur les régimes matrimoniaux", isCorrect: true },
      { id: 'c', text: "La loi de 1944 sur le droit de vote des femmes", isCorrect: false },
      { id: 'd', text: "La loi de 1982 sur la retraite à 60 ans", isCorrect: false },
    ],
    correctAnswer: "La loi de juillet 1965 sur les régimes matrimoniaux",
    explanation: "La loi de 1965 permet aux femmes mariées d'ouvrir un compte bancaire et de travailler sans l'autorisation de leur mari. C'est une avancée majeure pour l'égalité des droits.",
    hint: "Avant 1965, une femme mariée devait avoir l'autorisation de son mari pour travailler.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-027',
    subject: 'decouverte_du_monde',
    title: "L'Algérie indépendante",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'chronologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Algérie obtient son indépendance de la France en…",
    options: [
      { id: 'a', text: '1945', isCorrect: false },
      { id: 'b', text: '1962', isCorrect: true },
      { id: 'c', text: '1954', isCorrect: false },
      { id: 'd', text: '1970', isCorrect: false },
    ],
    correctAnswer: '1962',
    explanation: "L'Algérie obtient son indépendance le 5 juillet 1962, après une guerre qui débute en 1954. Les accords d'Évian (mars 1962) mettent fin au conflit.",
    hint: "Guerre d'Algérie : 1954–1962 → indépendance en 1962.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-tem-028',
    subject: 'decouverte_du_monde',
    title: "Le XXIe siècle",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le XXIe siècle débute le…",
    options: [
      { id: 'a', text: '1er janvier 1999', isCorrect: false },
      { id: 'b', text: '1er janvier 2001', isCorrect: true },
      { id: 'c', text: '1er janvier 2000', isCorrect: false },
      { id: 'd', text: '1er janvier 2010', isCorrect: false },
    ],
    correctAnswer: '1er janvier 2001',
    explanation: "Le XXIe siècle (et le 3e millénaire) commence officiellement le 1er janvier 2001, car il n'y a pas d'an zéro : après l'an 1 av. J.-C. vient l'an 1 ap. J.-C.",
    hint: "Il n'y a pas d'an 0. Le 1er siècle va de l'an 1 à l'an 100. Donc le XXIe siècle commence en 2001.",
    estimatedMinutes: 1,
    meta: { numericLoad: 'medium' },
    adaptations: A,
  },
];
