import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCm2VivantExercises: DecouverteExercise[] = [
  {
    id: 'ddm-cm2-vivant-001',
    subject: 'decouverte_du_monde',
    title: 'Reproduction des plantes à fleurs',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'reproduction',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle des abeilles dans la reproduction des plantes à fleurs ?',
    options: [
      { id: 'a', text: 'Elles mangent les graines et les détruisent.', isCorrect: false },
      { id: 'b', text: 'Elles transportent le pollen d\'une fleur à une autre, permettant la fécondation.', isCorrect: true },
      { id: 'c', text: 'Elles fabriquent les feuilles des plantes.', isCorrect: false },
      { id: 'd', text: 'Elles arrosent les plantes avec le miel.', isCorrect: false },
    ],
    correctAnswer: 'Elles transportent le pollen d\'une fleur à une autre, permettant la fécondation.',
    explanation: 'En butinant les fleurs pour récolter le nectar, les abeilles se couvrent de pollen. En visitant d\'autres fleurs, elles déposent ce pollen et permettent la pollinisation, première étape de la fécondation.',
    hint: 'Sans abeilles, beaucoup de plantes ne pourraient pas produire de fruits.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-vivant-002',
    subject: 'decouverte_du_monde',
    title: 'Cycle de vie des mammifères',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'cycles',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la principale différence entre la reproduction des mammifères et celle des oiseaux ?',
    options: [
      { id: 'a', text: 'Les mammifères pondent des œufs, les oiseaux donnent naissance à des petits vivants.', isCorrect: false },
      { id: 'b', text: 'Les mammifères donnent naissance à des petits vivants et les allaitent, les oiseaux pondent des œufs.', isCorrect: true },
      { id: 'c', text: 'Les deux pondent des œufs mais de tailles différentes.', isCorrect: false },
      { id: 'd', text: 'Les mammifères ne s\'occupent jamais de leurs petits.', isCorrect: false },
    ],
    correctAnswer: 'Les mammifères donnent naissance à des petits vivants et les allaitent, les oiseaux pondent des œufs.',
    explanation: 'Les mammifères (comme les chiens, les chats, les humains) mettent bas des petits vivants et les nourrissent de lait. Les oiseaux, eux, pondent des œufs qu\'ils couvent jusqu\'à l\'éclosion.',
    hint: '"Mammifère" vient du latin "mamma" = sein (pour l\'allaitement).',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-vivant-003',
    subject: 'decouverte_du_monde',
    title: 'Système digestif',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Remets les organes dans l\'ordre de la digestion.',
    prompt: 'Dans quel ordre les aliments traversent-ils ces organes lors de la digestion ?',
    options: [
      { id: 'a', text: 'Bouche → estomac → intestin grêle → gros intestin', isCorrect: true },
      { id: 'b', text: 'Bouche → intestin grêle → estomac → gros intestin', isCorrect: false },
      { id: 'c', text: 'Estomac → bouche → intestin grêle → gros intestin', isCorrect: false },
      { id: 'd', text: 'Bouche → gros intestin → estomac → intestin grêle', isCorrect: false },
    ],
    correctAnswer: 'Bouche → estomac → intestin grêle → gros intestin',
    explanation: 'La digestion commence dans la bouche (mastication), se poursuit dans l\'estomac (mélange acide), puis dans l\'intestin grêle (absorption des nutriments) et se termine dans le gros intestin (absorption de l\'eau).',
    hint: 'Les aliments descendent toujours dans le même sens.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-vivant-004',
    subject: 'decouverte_du_monde',
    title: 'Système respiratoire',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel échange se produit dans les poumons lors de la respiration ?',
    options: [
      { id: 'a', text: 'On absorbe du CO₂ et on rejette de l\'oxygène.', isCorrect: false },
      { id: 'b', text: 'On absorbe de l\'oxygène et on rejette du CO₂.', isCorrect: true },
      { id: 'c', text: 'On absorbe de l\'azote et on rejette de la vapeur d\'eau uniquement.', isCorrect: false },
      { id: 'd', text: 'Les poumons filtrent le sang et ne font aucun échange gazeux.', isCorrect: false },
    ],
    correctAnswer: 'On absorbe de l\'oxygène et on rejette du CO₂.',
    explanation: 'À chaque inspiration, l\'oxygène de l\'air passe dans le sang au niveau des poumons. À chaque expiration, le CO₂ (dioxyde de carbone) produit par les cellules est rejeté dans l\'air.',
    hint: 'Ce que tu rejettes en soufflant sur un miroir trouble la surface : c\'est du CO₂ et de la vapeur d\'eau.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-vivant-005',
    subject: 'decouverte_du_monde',
    title: 'Comportements favorables à la santé',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'sante',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Parmi ces habitudes, laquelle est la plus favorable à la santé sur le long terme ?',
    options: [
      { id: 'a', text: 'Regarder des écrans plus de 4 heures par jour.', isCorrect: false },
      { id: 'b', text: 'Pratiquer une activité physique régulière et dormir suffisamment.', isCorrect: true },
      { id: 'c', text: 'Manger surtout des aliments sucrés pour avoir de l\'énergie.', isCorrect: false },
      { id: 'd', text: 'Ne jamais sortir dehors pour éviter les maladies.', isCorrect: false },
    ],
    correctAnswer: 'Pratiquer une activité physique régulière et dormir suffisamment.',
    explanation: 'L\'activité physique renforce le cœur, les muscles et les os, et améliore l\'humeur. Le sommeil permet au corps et au cerveau de se régénérer. Ces deux habitudes réduisent les risques de maladies sur le long terme.',
    hint: 'Notre corps a besoin de bouger et de se reposer pour rester en bonne santé.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'ddm-cm2-vivant-006',
    subject: 'decouverte_du_monde',
    title: 'Chaînes alimentaires',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans la chaîne : herbe → lapin → renard → décomposeurs. Que se passe-t-il si les renards disparaissent ?',
    options: [
      { id: 'a', text: 'La population de lapins diminue fortement.', isCorrect: false },
      { id: 'b', text: 'La population de lapins augmente et la végétation est surpâturée.', isCorrect: true },
      { id: 'c', text: 'Les décomposeurs disparaissent aussi.', isCorrect: false },
      { id: 'd', text: 'Rien ne change, la chaîne s\'adapte automatiquement.', isCorrect: false },
    ],
    correctAnswer: 'La population de lapins augmente et la végétation est surpâturée.',
    explanation: 'Le renard régule la population de lapins. Sans prédateur, les lapins se reproduisent sans limite, mangent trop d\'herbe et déséquilibrent l\'écosystème. C\'est ce qu\'on appelle un déséquilibre de la chaîne alimentaire.',
    hint: 'Chaque maillon de la chaîne est important pour l\'équilibre de la nature.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
