import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCm2GrammaireExercises: FrenchExercise[] = [

  {
    id: 'fr-cm2-grammaire-101',
    subject: 'francais',
    title: 'Proposition principale et subordonnée',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'phrase complexe',
    format: 'qcm',
    instructions: 'Identifie la proposition subordonnée.',
    prompt: 'Je pense que tu as raison.',
    options: [
      { id: 'a', text: 'Je pense', isCorrect: false },
      { id: 'b', text: 'que tu as raison', isCorrect: true },
      { id: 'c', text: 'que tu', isCorrect: false },
    ],
    correctAnswer: 'que tu as raison',
    explanation: '"Je pense" est la proposition principale. "Que tu as raison" est la proposition subordonnée conjonctive, introduite par "que".',
    hint: 'La proposition subordonnée dépend de la principale ; elle est souvent introduite par "que".',
    tags: ['cm2', 'grammaire', 'phrase-complexe', 'subordonnee', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-102',
    subject: 'francais',
    title: 'Proposition relative',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'proposition relative',
    format: 'qcm',
    instructions: 'Choisis la proposition relative qui complète le nom.',
    prompt: 'Le livre ___ j\'ai lu cet été était passionnant.',
    options: [
      { id: 'a', text: 'dont', isCorrect: false },
      { id: 'b', text: 'que', isCorrect: true },
      { id: 'c', text: 'qui', isCorrect: false },
    ],
    correctAnswer: 'que',
    explanation: '"Que" est le pronom relatif COD : "j\'ai lu quoi ?" → le livre. On emploie "que" quand le pronom est COD. "Qui" serait sujet.',
    hint: 'Si le pronom relatif est COD du verbe qui suit, utilise "que".',
    tags: ['cm2', 'grammaire', 'proposition-relative', 'que-qui', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-103',
    subject: 'francais',
    title: 'Pronoms relatifs – qui / que / dont',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'pronoms relatifs',
    format: 'qcm',
    instructions: 'Choisis le bon pronom relatif.',
    prompt: 'Le chanteur ___ tout le monde parle sera en concert ce soir.',
    options: [
      { id: 'a', text: 'qui', isCorrect: false },
      { id: 'b', text: 'que', isCorrect: false },
      { id: 'c', text: 'dont', isCorrect: true },
    ],
    correctAnswer: 'dont',
    explanation: '"Parler de quelqu\'un" → "dont" remplace "de + nom". On parle du chanteur → le chanteur dont tout le monde parle.',
    hint: '"Dont" remplace un complément introduit par "de".',
    tags: ['cm2', 'grammaire', 'pronoms-relatifs', 'dont', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-104',
    subject: 'francais',
    title: 'COD ou attribut du sujet ?',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'fonctions',
    format: 'qcm',
    instructions: 'Quelle est la fonction du mot souligné ?',
    prompt: 'Mon frère est **médecin**.',
    options: [
      { id: 'a', text: 'COD', isCorrect: false },
      { id: 'b', text: 'Attribut du sujet', isCorrect: true },
      { id: 'c', text: 'Sujet', isCorrect: false },
    ],
    correctAnswer: 'Attribut du sujet',
    explanation: 'Après le verbe être (copule), le mot qui qualifie le sujet est un attribut du sujet. "Médecin" décrit "mon frère" via le verbe "est".',
    hint: 'Après "être", "paraître", "sembler"… le nom ou adjectif qui suit est attribut du sujet.',
    tags: ['cm2', 'grammaire', 'attribut-sujet', 'fonctions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-105',
    subject: 'francais',
    title: 'Coordination vs subordination',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'phrase complexe',
    format: 'qcm',
    instructions: 'Ces deux propositions sont-elles coordonnées ou l\'une est-elle subordonnée à l\'autre ?',
    prompt: '"Il fait froid, mais je n\'ai pas de manteau."',
    options: [
      { id: 'a', text: 'Subordonnées (l\'une dépend de l\'autre)', isCorrect: false },
      { id: 'b', text: 'Coordonnées (reliées par "mais")', isCorrect: true },
      { id: 'c', text: 'Juxtaposées (sans mot de liaison)', isCorrect: false },
    ],
    correctAnswer: 'Coordonnées (reliées par "mais")',
    explanation: '"Mais" est une conjonction de coordination. Les deux propositions sont de même rang : aucune ne dépend de l\'autre.',
    hint: '"Mais, ou, et, donc, or, ni, car" sont des conjonctions de coordination.',
    tags: ['cm2', 'grammaire', 'coordination', 'subordination', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-106',
    subject: 'francais',
    title: 'Complément du nom',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'complement du nom',
    format: 'qcm',
    instructions: 'Identifie le complément du nom.',
    prompt: 'La maison de mes grands-parents est à la campagne.',
    options: [
      { id: 'a', text: 'La maison', isCorrect: false },
      { id: 'b', text: 'de mes grands-parents', isCorrect: true },
      { id: 'c', text: 'à la campagne', isCorrect: false },
    ],
    correctAnswer: 'de mes grands-parents',
    explanation: '"De mes grands-parents" précise de qui est la maison. C\'est un complément du nom, qui complète "maison".',
    hint: 'Un complément du nom répond à la question "de qui ?" ou "de quoi ?" à propos d\'un nom.',
    tags: ['cm2', 'grammaire', 'complement-du-nom', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-107',
    subject: 'francais',
    title: 'Apposition',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'apposition',
    format: 'qcm',
    instructions: 'Quel est le rôle du groupe de mots entre virgules ?',
    prompt: 'Albert Einstein, célèbre physicien, a révolutionné la physique.',
    options: [
      { id: 'a', text: 'C\'est le sujet de la phrase', isCorrect: false },
      { id: 'b', text: 'C\'est une apposition qui précise le sujet', isCorrect: true },
      { id: 'c', text: 'C\'est un complément circonstanciel', isCorrect: false },
    ],
    correctAnswer: 'C\'est une apposition qui précise le sujet',
    explanation: '"Célèbre physicien" est apposé au sujet "Albert Einstein" : il apporte une information supplémentaire sur lui.',
    hint: 'L\'apposition est séparée du nom par des virgules et le précise.',
    tags: ['cm2', 'grammaire', 'apposition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-108',
    subject: 'francais',
    title: 'Pronom relatif "où"',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'pronoms relatifs',
    format: 'qcm',
    instructions: 'Choisis le bon pronom relatif.',
    prompt: 'La ville ___ je suis né est très animée.',
    options: [
      { id: 'a', text: 'que', isCorrect: false },
      { id: 'b', text: 'qui', isCorrect: false },
      { id: 'c', text: 'où', isCorrect: true },
    ],
    correctAnswer: 'où',
    explanation: '"Où" est pronom relatif de lieu. "La ville où je suis né" : "où" remplace "dans laquelle".',
    hint: '"Où" pronom relatif remplace un complément de lieu ou de temps.',
    tags: ['cm2', 'grammaire', 'pronom-relatif', 'ou', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-109',
    subject: 'francais',
    title: 'Accord avec plusieurs sujets',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'accord sujet verbe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Ni le chat ni le chien ne ___ envie de bouger.',
    options: [
      { id: 'a', text: 'ont', isCorrect: false },
      { id: 'b', text: 'a', isCorrect: false },
      { id: 'c', text: 'n\'ont', isCorrect: true },
    ],
    correctAnswer: 'n\'ont',
    explanation: 'Avec "ni… ni…", deux sujets singuliers peuvent prendre le verbe au pluriel car l\'ensemble désigne plusieurs êtres. "N\'ont" (pluriel) est correct ici.',
    hint: 'Avec "ni… ni…", le verbe est souvent au pluriel si les sujets désignent des êtres différents.',
    tags: ['cm2', 'grammaire', 'accord-sujet-verbe', 'ni-ni', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-110',
    subject: 'francais',
    title: 'Adverbe ou adjectif ?',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'nature des mots',
    format: 'qcm',
    instructions: 'Quelle est la nature du mot souligné ?',
    prompt: 'Elle chante **merveilleusement** bien.',
    options: [
      { id: 'a', text: 'Un adjectif', isCorrect: false },
      { id: 'b', text: 'Un adverbe', isCorrect: true },
      { id: 'c', text: 'Un verbe', isCorrect: false },
    ],
    correctAnswer: 'Un adverbe',
    explanation: '"Merveilleusement" modifie le verbe "chante". Il est invariable. C\'est un adverbe de manière.',
    hint: 'L\'adverbe modifie un verbe, un adjectif ou un autre adverbe. Il est invariable.',
    tags: ['cm2', 'grammaire', 'adverbe', 'nature-des-mots', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-111',
    subject: 'francais',
    title: 'Conjonction de subordination',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'conjonctions',
    format: 'qcm',
    instructions: 'Identifie la conjonction de subordination.',
    prompt: 'Il est rentré chez lui **parce qu\'**il se sentait fatigué.',
    options: [
      { id: 'a', text: 'mais', isCorrect: false },
      { id: 'b', text: 'parce que', isCorrect: true },
      { id: 'c', text: 'donc', isCorrect: false },
    ],
    correctAnswer: 'parce que',
    explanation: '"Parce que" est une conjonction de subordination : elle introduit une proposition subordonnée circonstancielle de cause.',
    hint: '"Parce que" exprime la cause et introduit une proposition subordonnée.',
    tags: ['cm2', 'grammaire', 'conjonction-subordination', 'cause', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cm2-grammaire-112',
    subject: 'francais',
    title: 'Phrase participiale',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'gérondif et participe',
    format: 'qcm',
    instructions: 'Que signifie le gérondif dans cette phrase ?',
    prompt: 'En travaillant régulièrement, tu progresseras rapidement.',
    options: [
      { id: 'a', text: 'La conséquence du travail', isCorrect: false },
      { id: 'b', text: 'La condition ou le moyen pour progresser', isCorrect: true },
      { id: 'c', text: 'L\'opposition au fait de progresser', isCorrect: false },
    ],
    correctAnswer: 'La condition ou le moyen pour progresser',
    explanation: '"En travaillant régulièrement" est un gérondif qui exprime le moyen (comment progresser) ou la condition.',
    hint: 'Le gérondif (en + participe présent) exprime souvent le moyen ou la simultanéité.',
    tags: ['cm2', 'grammaire', 'gerondif', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:grammaire',
  },
];
