import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCm2VocabulaireExercises: FrenchExercise[] = [

  {
    id: 'fr-cm2-vocabulaire-101',
    subject: 'francais',
    title: 'Nuances de synonymes',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'synonymes nuances',
    format: 'qcm',
    instructions: 'Choisis le synonyme le plus précis dans ce contexte.',
    prompt: 'Le vieux professeur ___ la classe depuis 30 ans. (surveiller / diriger / guider)',
    options: [
      { id: 'a', text: 'surveille', isCorrect: false },
      { id: 'b', text: 'dirige', isCorrect: true },
      { id: 'c', text: 'guide', isCorrect: false },
    ],
    correctAnswer: 'dirige',
    explanation: '"Diriger" implique une autorité et une responsabilité sur un groupe sur la durée. "Surveiller" est trop passif, "guider" trop ponctuel.',
    hint: 'Quel verbe exprime une autorité durable sur un groupe ?',
    tags: ['cm2', 'vocabulaire', 'synonymes', 'nuances', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-102',
    subject: 'francais',
    title: 'Étymologie latine',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'etymologie',
    format: 'qcm',
    instructions: 'À partir de la racine latine, devine le sens.',
    prompt: 'Le mot "lumineux" vient du latin "lumen" (= lumière). Que signifie "luminos" ?',
    options: [
      { id: 'a', text: 'Sombre, sans éclairage', isCorrect: false },
      { id: 'b', text: 'Qui émet ou réfléchit de la lumière', isCorrect: true },
      { id: 'c', text: 'Qui fait du bruit', isCorrect: false },
    ],
    correctAnswer: 'Qui émet ou réfléchit de la lumière',
    explanation: '"Lumineux" vient de "lumen" (lumière en latin). Il désigne ce qui brille ou éclaire.',
    hint: '"Lumen" en latin = lumière.',
    tags: ['cm2', 'vocabulaire', 'etymologie', 'latin', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-103',
    subject: 'francais',
    title: 'Figure de style – métaphore',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'figures de style',
    format: 'qcm',
    instructions: 'Identifie la figure de style.',
    prompt: '"La vie est un long fleuve tranquille."',
    options: [
      { id: 'a', text: 'Une comparaison (avec "comme")', isCorrect: false },
      { id: 'b', text: 'Une métaphore (comparaison sans "comme")', isCorrect: true },
      { id: 'c', text: 'Une personnification', isCorrect: false },
    ],
    correctAnswer: 'Une métaphore (comparaison sans "comme")',
    explanation: '"La vie est un long fleuve" est une métaphore : on assimile la vie à un fleuve sans employer "comme". La comparaison dirait "la vie est comme un fleuve".',
    hint: 'La métaphore compare sans utiliser "comme" ou "tel que".',
    tags: ['cm2', 'vocabulaire', 'figures-de-style', 'metaphore', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-104',
    subject: 'francais',
    title: 'Figure de style – personnification',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'figures de style',
    format: 'qcm',
    instructions: 'Identifie la figure de style.',
    prompt: '"Le vent murmurait doucement entre les branches."',
    options: [
      { id: 'a', text: 'Une hyperbole', isCorrect: false },
      { id: 'b', text: 'Une métaphore', isCorrect: false },
      { id: 'c', text: 'Une personnification', isCorrect: true },
    ],
    correctAnswer: 'Une personnification',
    explanation: '"Murmurer" est une action humaine. La prêter au vent (objet inanimé) est une personnification.',
    hint: 'Quand on donne à un objet ou à un animal des actions ou des sentiments humains.',
    tags: ['cm2', 'vocabulaire', 'figures-de-style', 'personnification', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-105',
    subject: 'francais',
    title: 'Registres de langue',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'registres de langue',
    format: 'qcm',
    instructions: 'Dans quelle phrase le registre est-il soutenu (littéraire/formel) ?',
    prompt: 'Choisis la formulation au registre soutenu.',
    options: [
      { id: 'a', text: 'J\'ai pas trop bien compris ce qu\'il racontait.', isCorrect: false },
      { id: 'b', text: 'Je n\'ai pas bien saisi le sens de ses propos.', isCorrect: true },
      { id: 'c', text: 'J\'ai rien pigé à ce qu\'il disait.', isCorrect: false },
    ],
    correctAnswer: 'Je n\'ai pas bien saisi le sens de ses propos.',
    explanation: '"Saisi le sens de ses propos" relève d\'un registre soutenu. "Pas trop bien compris" est courant ; "rien pigé" est familier.',
    hint: 'Le registre soutenu utilise un vocabulaire plus précis et des phrases complètes.',
    tags: ['cm2', 'vocabulaire', 'registres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-106',
    subject: 'francais',
    title: 'Champ sémantique – émotions',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'champ semantique',
    format: 'qcm',
    instructions: 'Quel mot n\'appartient pas au champ sémantique des émotions ?',
    prompt: 'Joie – mélancolie – frayeur – calcaire – enthousiasme.',
    options: [
      { id: 'a', text: 'mélancolie', isCorrect: false },
      { id: 'b', text: 'calcaire', isCorrect: true },
      { id: 'c', text: 'frayeur', isCorrect: false },
    ],
    correctAnswer: 'calcaire',
    explanation: '"Calcaire" est un type de roche. Tous les autres mots (joie, mélancolie, frayeur, enthousiasme) désignent des émotions.',
    hint: 'Un de ces mots n\'a rien à voir avec ce qu\'on ressent.',
    tags: ['cm2', 'vocabulaire', 'champ-semantique', 'emotions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-107',
    subject: 'francais',
    title: 'Préfixe anti-',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'prefixes',
    format: 'qcm',
    instructions: 'Que signifie le mot formé avec le préfixe "anti-" ?',
    prompt: 'Un "antibrouillard" est un équipement qui…',
    options: [
      { id: 'a', text: 'crée du brouillard', isCorrect: false },
      { id: 'b', text: 'lutte ou protège contre le brouillard', isCorrect: true },
      { id: 'c', text: 'mesure le brouillard', isCorrect: false },
    ],
    correctAnswer: 'lutte ou protège contre le brouillard',
    explanation: 'Le préfixe "anti-" signifie "contre". Un antibrouillard est un projecteur qui aide à voir dans le brouillard.',
    hint: '"Anti-" vient du grec et signifie "contre".',
    tags: ['cm2', 'vocabulaire', 'prefixes', 'anti', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-108',
    subject: 'francais',
    title: 'Sens propre et sens figuré',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'sens propre sens figure',
    format: 'qcm',
    instructions: 'Dans quelle phrase "briller" est-il au sens figuré ?',
    prompt: 'Choisis la phrase où "briller" a un sens figuré.',
    options: [
      { id: 'a', text: 'Les étoiles brillent dans la nuit.', isCorrect: false },
      { id: 'b', text: 'Cet élève brille en mathématiques.', isCorrect: true },
      { id: 'c', text: 'La lampe brille encore trop fort.', isCorrect: false },
    ],
    correctAnswer: 'Cet élève brille en mathématiques.',
    explanation: 'Au sens propre, "briller" = émettre de la lumière. Au sens figuré, "briller en maths" = exceller, se distinguer.',
    hint: 'Le sens figuré est une image, pas le sens habituel du mot.',
    tags: ['cm2', 'vocabulaire', 'sens-propre', 'sens-figure', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-109',
    subject: 'francais',
    title: 'Paronymes',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'paronymes',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Il a ___ tous ses voisins à son anniversaire.',
    options: [
      { id: 'a', text: 'invité', isCorrect: true },
      { id: 'b', text: 'infesté', isCorrect: false },
      { id: 'c', text: 'évité', isCorrect: false },
    ],
    correctAnswer: 'invité',
    explanation: '"Inviter" = demander à quelqu\'un de venir. "Infester" = envahir de nuisibles. "Éviter" = ne pas rencontrer. Seul "invité" convient au contexte festif.',
    hint: 'Des paronymes sont des mots qui se ressemblent mais ont des sens différents.',
    tags: ['cm2', 'vocabulaire', 'paronymes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-110',
    subject: 'francais',
    title: 'Mot abstrait ou concret ?',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'abstrait concret',
    format: 'qcm',
    instructions: 'Lequel de ces mots est un nom abstrait ?',
    prompt: 'Chaise – liberté – pomme – rivière.',
    options: [
      { id: 'a', text: 'chaise', isCorrect: false },
      { id: 'b', text: 'liberté', isCorrect: true },
      { id: 'c', text: 'pomme', isCorrect: false },
    ],
    correctAnswer: 'liberté',
    explanation: '"Liberté" est un nom abstrait : on ne peut pas le voir ni le toucher, c\'est une idée. Chaise, pomme et rivière sont des noms concrets.',
    hint: 'Un nom abstrait désigne quelque chose qu\'on ne peut pas percevoir directement avec les sens.',
    tags: ['cm2', 'vocabulaire', 'abstrait-concret', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-111',
    subject: 'francais',
    title: 'Hyperbole',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'figures de style',
    format: 'qcm',
    instructions: 'Identifie la figure de style.',
    prompt: '"J\'ai attendu des milliers d\'années que tu arrives !"',
    options: [
      { id: 'a', text: 'Une métaphore', isCorrect: false },
      { id: 'b', text: 'Une hyperbole (exagération)', isCorrect: true },
      { id: 'c', text: 'Une comparaison', isCorrect: false },
    ],
    correctAnswer: 'Une hyperbole (exagération)',
    explanation: 'L\'hyperbole est une exagération volontaire. Personne n\'attend vraiment des milliers d\'années ; c\'est une façon d\'exprimer une longue attente.',
    hint: 'L\'hyperbole exagère de façon intentionnelle pour créer un effet.',
    tags: ['cm2', 'vocabulaire', 'figures-de-style', 'hyperbole', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cm2-vocabulaire-112',
    subject: 'francais',
    title: 'Dérivation – suffixe -tion',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'derivation',
    format: 'qcm',
    instructions: 'Quel nom est formé à partir du verbe "organiser" ?',
    prompt: 'Nominalisation de "organiser" :',
    options: [
      { id: 'a', text: 'organisateur', isCorrect: false },
      { id: 'b', text: 'organisation', isCorrect: true },
      { id: 'c', text: 'organisé', isCorrect: false },
    ],
    correctAnswer: 'organisation',
    explanation: '"Organisation" est le nom dérivé d\'"organiser" avec le suffixe -tion. "Organisateur" est un nom d\'agent ; "organisé" est un adjectif.',
    hint: 'Le suffixe -tion transforme souvent un verbe en nom (action → résultat de l\'action).',
    tags: ['cm2', 'vocabulaire', 'derivation', 'suffixe-tion', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },
];
