import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe1VivantExercises: DecouverteExercise[] = [

  {
    id: 'ddm-ce1-vivant-001',
    subject: 'decouverte_du_monde',
    title: 'Vertébrés et invertébrés',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un vertébré est un animal qui possède…',
    options: [
      { id: 'a', text: 'des plumes uniquement', isCorrect: false },
      { id: 'b', text: 'une colonne vertébrale (un squelette interne)', isCorrect: true },
      { id: 'c', text: '6 pattes obligatoirement', isCorrect: false },
      { id: 'd', text: 'une carapace dure', isCorrect: false },
    ],
    correctAnswer: 'une colonne vertébrale (un squelette interne)',
    explanation: 'Les vertébrés ont un squelette interne avec une colonne vertébrale. Les poissons, oiseaux, reptiles, amphibiens et mammifères sont des vertébrés.',
    hint: 'Vertèbre → colonne vertébrale.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-002',
    subject: 'decouverte_du_monde',
    title: 'Les amphibiens',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La grenouille est un amphibien. Cela signifie qu'elle peut vivre…",
    options: [
      { id: 'a', text: "uniquement dans l'eau", isCorrect: false },
      { id: 'b', text: "à la fois dans l'eau et sur la terre", isCorrect: true },
      { id: 'c', text: 'uniquement sur la terre', isCorrect: false },
      { id: 'd', text: 'uniquement dans les arbres', isCorrect: false },
    ],
    correctAnswer: "à la fois dans l'eau et sur la terre",
    explanation: "Les amphibiens vivent à la fois dans l'eau et sur la terre. Les grenouilles, crapauds et salamandres sont des amphibiens.",
    hint: "« Amphi » vient du grec et signifie « des deux côtés ».",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-003',
    subject: 'decouverte_du_monde',
    title: 'Le reptile',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le serpent est un reptile. Quelle est sa particularité ?",
    options: [
      { id: 'a', text: 'Il a des plumes.', isCorrect: false },
      { id: 'b', text: "Il est recouvert d'écailles et est à sang froid.", isCorrect: true },
      { id: 'c', text: 'Il allaite ses petits.', isCorrect: false },
      { id: 'd', text: "Il vit uniquement dans l'eau.", isCorrect: false },
    ],
    correctAnswer: "Il est recouvert d'écailles et est à sang froid.",
    explanation: "Les reptiles ont des écailles et sont à sang froid (leur température dépend de l'environnement). Serpents, lézards, tortues et crocodiles sont des reptiles.",
    hint: 'Les écailles et le sang froid caractérisent les reptiles.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-004',
    subject: 'decouverte_du_monde',
    title: 'Herbivore, carnivore, omnivore',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'alimentation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'humain mange des légumes, de la viande et des fruits. Il est…",
    options: [
      { id: 'a', text: 'herbivore', isCorrect: false },
      { id: 'b', text: 'carnivore', isCorrect: false },
      { id: 'c', text: 'omnivore', isCorrect: true },
      { id: 'd', text: 'frugivore', isCorrect: false },
    ],
    correctAnswer: 'omnivore',
    explanation: "Un omnivore mange de tout : plantes, viande, fruits. Les humains, les cochons et les ours sont omnivores.",
    hint: "« Omni » = tout. L'omnivore mange de tout.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-005',
    subject: 'decouverte_du_monde',
    title: 'La chaîne alimentaire',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'alimentation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans la chaîne : herbe → lapin → renard, qui est le prédateur du lapin ?',
    options: [
      { id: 'a', text: "L'herbe", isCorrect: false },
      { id: 'b', text: 'Le renard', isCorrect: true },
      { id: 'c', text: 'Le lapin lui-même', isCorrect: false },
      { id: 'd', text: "Il n'y a pas de prédateur", isCorrect: false },
    ],
    correctAnswer: 'Le renard',
    explanation: "Le renard chasse et mange le lapin : il est le prédateur du lapin. L'herbe est la proie du lapin. Le lapin est la proie du renard.",
    hint: 'Le prédateur chasse et mange une proie.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-006',
    subject: 'decouverte_du_monde',
    title: 'La reproduction des mammifères',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'reproduction',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les mammifères (comme le chien ou le chat) donnent naissance à des…',
    options: [
      { id: 'a', text: 'oeufs', isCorrect: false },
      { id: 'b', text: 'petits vivants (vivipares)', isCorrect: true },
      { id: 'c', text: 'graines', isCorrect: false },
      { id: 'd', text: 'larves', isCorrect: false },
    ],
    correctAnswer: 'petits vivants (vivipares)',
    explanation: 'Les mammifères sont vivipares : leurs petits naissent vivants (pas d\'oeufs). La maman les nourrit ensuite avec son lait.',
    hint: 'La chatte donne naissance à des chatons vivants.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-007',
    subject: 'decouverte_du_monde',
    title: 'Pollinisation',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'abeille butine les fleurs et transporte le pollen d'une fleur à l'autre. Ce rôle s'appelle…",
    options: [
      { id: 'a', text: 'la photosynthèse', isCorrect: false },
      { id: 'b', text: 'la pollinisation', isCorrect: true },
      { id: 'c', text: "l'hibernation", isCorrect: false },
      { id: 'd', text: 'la germination', isCorrect: false },
    ],
    correctAnswer: 'la pollinisation',
    explanation: "En transportant le pollen de fleur en fleur, les abeilles permettent la reproduction des plantes. Sans pollinisation, pas de fruits ni de graines.",
    hint: "Le pollen passe d'une fleur à une autre grâce à l'abeille.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-008',
    subject: 'decouverte_du_monde',
    title: 'La germination',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La germination d'une graine, c'est le moment où…",
    options: [
      { id: 'a', text: 'la plante fleurit', isCorrect: false },
      { id: 'b', text: 'la graine commence à pousser et sort de la terre', isCorrect: true },
      { id: 'c', text: 'la plante perd ses feuilles', isCorrect: false },
      { id: 'd', text: 'les graines sont récoltées', isCorrect: false },
    ],
    correctAnswer: 'la graine commence à pousser et sort de la terre',
    explanation: "La germination est le début de la vie d'une plante : la graine absorbe l'eau, gonfle et envoie une petite racine et une tige vers le haut.",
    hint: "C'est quand la graine commence sa nouvelle vie.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-009',
    subject: 'decouverte_du_monde',
    title: 'Les habitats des animaux',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'habitat d'un animal, c'est…",
    options: [
      { id: 'a', text: "ce que l'animal mange", isCorrect: false },
      { id: 'b', text: "l'endroit où il vit naturellement", isCorrect: true },
      { id: 'c', text: 'comment il se reproduit', isCorrect: false },
      { id: 'd', text: 'sa couleur', isCorrect: false },
    ],
    correctAnswer: "l'endroit où il vit naturellement",
    explanation: "L'habitat est le milieu naturel dans lequel vit un animal. L'écureuil vit dans la forêt, le dauphin dans la mer, la taupe sous la terre.",
    hint: "L'habitat = la maison naturelle de l'animal.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-010',
    subject: 'decouverte_du_monde',
    title: 'Habitat du saumon',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le saumon vit en mer puis remonte les rivières pour pondre ses oeufs. Son habitat est…",
    options: [
      { id: 'a', text: 'uniquement la mer', isCorrect: false },
      { id: 'b', text: 'à la fois les rivières et la mer', isCorrect: true },
      { id: 'c', text: 'uniquement les rivières', isCorrect: false },
      { id: 'd', text: 'les lacs de montagne', isCorrect: false },
    ],
    correctAnswer: 'à la fois les rivières et la mer',
    explanation: "Le saumon est un poisson migrateur : il naît en rivière, vit en mer puis remonte les rivières pour se reproduire.",
    hint: "Le saumon remonte les rivières pour pondre ses oeufs.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-011',
    subject: 'decouverte_du_monde',
    title: 'Les araignées',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'araignée a 8 pattes. Est-ce un insecte ?",
    options: [
      { id: 'a', text: 'Oui, elle vole comme les insectes.', isCorrect: false },
      { id: 'b', text: "Non, un insecte a 6 pattes. L'araignée est une arachnide.", isCorrect: true },
      { id: 'c', text: 'Oui, elle a des antennes.', isCorrect: false },
      { id: 'd', text: 'On ne peut pas savoir.', isCorrect: false },
    ],
    correctAnswer: "Non, un insecte a 6 pattes. L'araignée est une arachnide.",
    explanation: "L'araignée a 8 pattes, pas 6. Elle appartient aux arachnides, pas aux insectes. Les scorpions et les tiques sont aussi des arachnides.",
    hint: '6 pattes = insecte. 8 pattes = arachnide.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-012',
    subject: 'decouverte_du_monde',
    title: 'Décomposeurs',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'alimentation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les champignons et les vers de terre décomposent les feuilles mortes et les restes d'animaux. Leur rôle est de…",
    options: [
      { id: 'a', text: 'produire du miel', isCorrect: false },
      { id: 'b', text: 'recycler la matière organique pour enrichir le sol', isCorrect: true },
      { id: 'c', text: "chasser d'autres animaux", isCorrect: false },
      { id: 'd', text: "produire de l'oxygène", isCorrect: false },
    ],
    correctAnswer: 'recycler la matière organique pour enrichir le sol',
    explanation: "Les décomposeurs transforment les restes en humus (terre fertile). Ils jouent un rôle clé dans le cycle de la matière dans la nature.",
    hint: 'Sans eux, les feuilles mortes ne disparaîtraient jamais.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-013',
    subject: 'decouverte_du_monde',
    title: 'Migration des oiseaux',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les hirondelles quittent l'Europe en automne et reviennent au printemps. Ce phénomène s'appelle…",
    options: [
      { id: 'a', text: "l'hibernation", isCorrect: false },
      { id: 'b', text: 'la migration', isCorrect: true },
      { id: 'c', text: 'la métamorphose', isCorrect: false },
      { id: 'd', text: 'la mue', isCorrect: false },
    ],
    correctAnswer: 'la migration',
    explanation: "La migration est un voyage saisonnier. Les hirondelles migrent vers l'Afrique pour fuir l'hiver européen et reviennent au printemps.",
    hint: 'Les oiseaux migrateurs voyagent avec les saisons.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-014',
    subject: 'decouverte_du_monde',
    title: 'Les champignons',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les champignons ne sont ni des plantes ni des animaux. En quoi sont-ils différents des plantes ?",
    options: [
      { id: 'a', text: 'Ils ne peuvent pas se reproduire.', isCorrect: false },
      { id: 'b', text: "Ils ne fabriquent pas leur nourriture grâce au soleil.", isCorrect: true },
      { id: 'c', text: 'Ils ne vivent que dans les forêts.', isCorrect: false },
      { id: 'd', text: 'Ils sont toujours venimeux.', isCorrect: false },
    ],
    correctAnswer: "Ils ne fabriquent pas leur nourriture grâce au soleil.",
    explanation: "Les champignons se nourrissent en décomposant des matières organiques. Ils n'ont pas de chlorophylle et ne font pas la photosynthèse.",
    hint: "Ils poussent à l'ombre, sans lumière.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-015',
    subject: 'decouverte_du_monde',
    title: 'La photosynthèse',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les feuilles vertes des plantes fabriquent leur nourriture grâce à…',
    options: [
      { id: 'a', text: 'la pluie et le vent', isCorrect: false },
      { id: 'b', text: "la lumière du soleil, l'eau et le CO₂ (air)", isCorrect: true },
      { id: 'c', text: 'la chaleur uniquement', isCorrect: false },
      { id: 'd', text: 'les insectes', isCorrect: false },
    ],
    correctAnswer: "la lumière du soleil, l'eau et le CO₂ (air)",
    explanation: "La photosynthèse est le processus par lequel les plantes transforment lumière + eau + CO₂ en sucre (nourriture) et rejettent de l'oxygène.",
    hint: 'Les feuilles vertes captent la lumière du soleil.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-016',
    subject: 'decouverte_du_monde',
    title: 'Espèces en danger',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Certaines espèces animales sont en danger. Pourquoi ?',
    options: [
      { id: 'a', text: 'Parce qu\'elles mangent trop.', isCorrect: false },
      { id: 'b', text: 'À cause de la destruction de leurs habitats, de la chasse et de la pollution.', isCorrect: true },
      { id: 'c', text: 'Parce qu\'elles sont trop grandes.', isCorrect: false },
      { id: 'd', text: 'Parce qu\'elles ne se reproduisent jamais.', isCorrect: false },
    ],
    correctAnswer: 'À cause de la destruction de leurs habitats, de la chasse et de la pollution.',
    explanation: "Les espèces menacées souffrent de la déforestation, de la chasse excessive, de la pollution et du changement climatique qui détruisent leurs habitats.",
    hint: "Quand la forêt disparaît, les animaux n'ont plus de maison.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-017',
    subject: 'decouverte_du_monde',
    title: "L'écorce de l'arbre",
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'écorce d'un arbre sert à…",
    options: [
      { id: 'a', text: 'produire des fruits', isCorrect: false },
      { id: 'b', text: "protéger l'arbre contre les chocs et les intempéries", isCorrect: true },
      { id: 'c', text: 'absorber la lumière', isCorrect: false },
      { id: 'd', text: 'faire pousser les racines', isCorrect: false },
    ],
    correctAnswer: "protéger l'arbre contre les chocs et les intempéries",
    explanation: "L'écorce est la couche externe de protection d'un arbre. Elle le protège du froid, de la chaleur, des insectes et des maladies.",
    hint: "C'est la « peau » de l'arbre.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-018',
    subject: 'decouverte_du_monde',
    title: 'Que mangent les vaches ?',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'alimentation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les vaches broutent de l'herbe. Elles sont…",
    options: [
      { id: 'a', text: 'carnivores', isCorrect: false },
      { id: 'b', text: 'herbivores', isCorrect: true },
      { id: 'c', text: 'omnivores', isCorrect: false },
      { id: 'd', text: 'insectivores', isCorrect: false },
    ],
    correctAnswer: 'herbivores',
    explanation: 'Les vaches ne mangent que des végétaux : herbe, foin, céréales. Ce sont des herbivores.',
    hint: 'Herbe + vore = herbivore.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-019',
    subject: 'decouverte_du_monde',
    title: 'Le cycle de vie du papillon',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'reproduction',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est l\'ordre correct du cycle de vie du papillon ?',
    options: [
      { id: 'a', text: 'Papillon → chenille → oeuf → chrysalide', isCorrect: false },
      { id: 'b', text: 'Oeuf → chenille → chrysalide → papillon', isCorrect: true },
      { id: 'c', text: 'Chrysalide → oeuf → chenille → papillon', isCorrect: false },
      { id: 'd', text: 'Chenille → papillon → oeuf → chrysalide', isCorrect: false },
    ],
    correctAnswer: 'Oeuf → chenille → chrysalide → papillon',
    explanation: "Le papillon passe par 4 stades : l'oeuf (pondu sur une feuille), la chenille, la chrysalide (cocon) et enfin le papillon adulte.",
    hint: "L'oeuf vient en premier, le papillon en dernier.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-vivant-020',
    subject: 'decouverte_du_monde',
    title: 'Protéger la biodiversité',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La biodiversité, c\'est…',
    options: [
      { id: 'a', text: 'le nombre de voitures dans une ville', isCorrect: false },
      { id: 'b', text: 'la variété de toutes les espèces vivantes sur Terre', isCorrect: true },
      { id: 'c', text: 'le cycle des saisons', isCorrect: false },
      { id: 'd', text: 'la distance entre les pays', isCorrect: false },
    ],
    correctAnswer: 'la variété de toutes les espèces vivantes sur Terre',
    explanation: "La biodiversité désigne la richesse et la variété des espèces vivantes (plantes, animaux, champignons…). Elle est menacée par les activités humaines.",
    hint: '« Bio » = vie, « diversité » = variété.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
