import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe1SocieteExercises: DecouverteExercise[] = [

  // CE1 · reperes · famille
  {
    id: 'ddm-ce1-rep-005',
    subject: 'decouverte_du_monde',
    title: 'Les cousins',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les enfants de ton oncle ou de ta tante sont tes…',
    options: [
      { id: 'a', text: 'frères et sœurs', isCorrect: false },
      { id: 'b', text: 'cousins et cousines', isCorrect: true },
      { id: 'c', text: 'neveux et nièces', isCorrect: false },
      { id: 'd', text: 'grands-parents', isCorrect: false },
    ],
    correctAnswer: 'cousins et cousines',
    explanation: 'Les enfants de tes oncles et tantes sont tes cousins (garçons) et cousines (filles).',
    hint: 'Ce sont les enfants des frères et sœurs de tes parents.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-006',
    subject: 'decouverte_du_monde',
    title: 'La famille monoparentale',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une famille monoparentale, c\'est une famille avec…',
    options: [
      { id: 'a', text: 'deux parents et beaucoup d\'enfants', isCorrect: false },
      { id: 'b', text: 'un seul parent (père ou mère) qui élève les enfants', isCorrect: true },
      { id: 'c', text: 'seulement des grands-parents', isCorrect: false },
      { id: 'd', text: 'des parents adoptifs uniquement', isCorrect: false },
    ],
    correctAnswer: 'un seul parent (père ou mère) qui élève les enfants',
    explanation: 'Dans une famille monoparentale, un seul parent s\'occupe des enfants, seul(e).',
    hint: '« Mono » = un seul. Un seul parent.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-007',
    subject: 'decouverte_du_monde',
    title: 'Les familles sont différentes',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Toutes les familles sont-elles identiques ?',
    options: [
      { id: 'a', text: 'Oui, toutes les familles sont pareilles.', isCorrect: false },
      { id: 'b', text: 'Non, les familles peuvent être très différentes.', isCorrect: true },
      { id: 'c', text: 'Une famille doit avoir exactement deux enfants.', isCorrect: false },
      { id: 'd', text: 'Une famille doit toujours avoir deux parents.', isCorrect: false },
    ],
    correctAnswer: 'Non, les familles peuvent être très différentes.',
    explanation: 'Les familles sont toutes différentes : petites ou grandes, avec un ou deux parents, recomposées ou adoptives. Chaque famille est unique.',
    hint: 'Regarde autour de toi : les familles de tes camarades sont toutes différentes.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CE1 · reperes · metiers
  {
    id: 'ddm-ce1-rep-008',
    subject: 'decouverte_du_monde',
    title: 'L\'infirmier / l\'infirmière',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'infirmier ou l\'infirmière travaille surtout…',
    options: [
      { id: 'a', text: 'à la boulangerie', isCorrect: false },
      { id: 'b', text: 'dans un hôpital ou une clinique', isCorrect: true },
      { id: 'c', text: 'dans une école', isCorrect: false },
      { id: 'd', text: 'dans un garage', isCorrect: false },
    ],
    correctAnswer: 'dans un hôpital ou une clinique',
    explanation: 'L\'infirmier ou l\'infirmière soigne les patients à l\'hôpital ou dans des maisons de santé.',
    hint: 'Il ou elle donne les médicaments et fait les piqûres.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-009',
    subject: 'decouverte_du_monde',
    title: 'L\'agriculteur',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle de l\'agriculteur ?',
    options: [
      { id: 'a', text: 'Il conduit les bus en ville.', isCorrect: false },
      { id: 'b', text: 'Il cultive la terre et élève des animaux pour produire des aliments.', isCorrect: true },
      { id: 'c', text: 'Il construit des bâtiments.', isCorrect: false },
      { id: 'd', text: 'Il enseigne à l\'école.', isCorrect: false },
    ],
    correctAnswer: 'Il cultive la terre et élève des animaux pour produire des aliments.',
    explanation: 'L\'agriculteur travaille à la campagne. Il cultive des céréales, des légumes et s\'occupe des animaux.',
    hint: 'Grâce à lui, on a du pain, des légumes et de la viande.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-010',
    subject: 'decouverte_du_monde',
    title: 'Le vétérinaire',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui soigne les animaux malades ?',
    options: [
      { id: 'a', text: 'le médecin', isCorrect: false },
      { id: 'b', text: 'le vétérinaire', isCorrect: true },
      { id: 'c', text: 'le pharmacien', isCorrect: false },
      { id: 'd', text: 'le pompier', isCorrect: false },
    ],
    correctAnswer: 'le vétérinaire',
    explanation: 'Le vétérinaire est le médecin des animaux. Il soigne les chiens, les chats et tous les autres animaux.',
    hint: '« Vétérinaire » vient du latin pour les animaux.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-011',
    subject: 'decouverte_du_monde',
    title: 'Le conducteur de bus',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui conduit le bus pour transporter les gens ?',
    options: [
      { id: 'a', text: 'le facteur', isCorrect: false },
      { id: 'b', text: 'le conducteur de bus', isCorrect: true },
      { id: 'c', text: 'le pompier', isCorrect: false },
      { id: 'd', text: 'le gardien', isCorrect: false },
    ],
    correctAnswer: 'le conducteur de bus',
    explanation: 'Le conducteur de bus (ou machiniste) conduit le bus et transporte les passagers en ville ou entre les villages.',
    hint: 'Il connaît tous les arrêts par cœur.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-012',
    subject: 'decouverte_du_monde',
    title: 'Le maçon',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui construit les maisons et les bâtiments ?',
    options: [
      { id: 'a', text: 'le boulanger', isCorrect: false },
      { id: 'b', text: 'le maçon', isCorrect: true },
      { id: 'c', text: 'le médecin', isCorrect: false },
      { id: 'd', text: 'le libraire', isCorrect: false },
    ],
    correctAnswer: 'le maçon',
    explanation: 'Le maçon construit les murs des maisons et des bâtiments avec de la brique, du béton et du mortier.',
    hint: 'Il utilise du béton et des briques.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-013',
    subject: 'decouverte_du_monde',
    title: 'Le bibliothécaire',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'metiers',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le bibliothécaire travaille dans…',
    options: [
      { id: 'a', text: 'une boulangerie', isCorrect: false },
      { id: 'b', text: 'une bibliothèque', isCorrect: true },
      { id: 'c', text: 'un hôpital', isCorrect: false },
      { id: 'd', text: 'une gare', isCorrect: false },
    ],
    correctAnswer: 'une bibliothèque',
    explanation: 'Le bibliothécaire gère les livres dans une bibliothèque. Il aide les lecteurs à trouver des livres.',
    hint: 'Il classe les livres et aide à trouver ce qu\'on cherche.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CE1 · reperes · regles_vie
  {
    id: 'ddm-ce1-rep-014',
    subject: 'decouverte_du_monde',
    title: 'Le Code de la route',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi doit-on respecter le Code de la route ?',
    options: [
      { id: 'a', text: 'Pour rouler le plus vite possible.', isCorrect: false },
      { id: 'b', text: 'Pour assurer la sécurité de tous sur la route.', isCorrect: true },
      { id: 'c', text: 'Pour payer moins cher l\'essence.', isCorrect: false },
      { id: 'd', text: 'Parce que c\'est amusant.', isCorrect: false },
    ],
    correctAnswer: 'Pour assurer la sécurité de tous sur la route.',
    explanation: 'Le Code de la route fixe des règles pour éviter les accidents et protéger les conducteurs, les cyclistes et les piétons.',
    hint: 'Sans règles, la route serait très dangereuse.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-015',
    subject: 'decouverte_du_monde',
    title: 'Traverser la rue',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pour traverser la rue en sécurité, on doit…',
    options: [
      { id: 'a', text: 'courir très vite sans regarder', isCorrect: false },
      { id: 'b', text: 'regarder à gauche, à droite, puis traverser sur le passage piéton', isCorrect: true },
      { id: 'c', text: 'traverser n\'importe où en agitant les bras', isCorrect: false },
      { id: 'd', text: 'attendre que quelqu\'un nous porte', isCorrect: false },
    ],
    correctAnswer: 'regarder à gauche, à droite, puis traverser sur le passage piéton',
    explanation: 'Pour traverser en sécurité, on regarde des deux côtés et on utilise le passage piéton.',
    hint: 'Gauche, droite, puis go !',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-016',
    subject: 'decouverte_du_monde',
    title: 'Le partage',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Il y a une seule balançoire et deux enfants veulent l\'utiliser. Que faire ?',
    options: [
      { id: 'a', text: 'Se battre pour l\'avoir.', isCorrect: false },
      { id: 'b', text: 'Se mettre d\'accord pour alterner et se passer la balançoire à tour de rôle.', isCorrect: true },
      { id: 'c', text: 'L\'un d\'eux part pour ne plus jamais jouer.', isCorrect: false },
      { id: 'd', text: 'Appeler un adulte pour qu\'il décide.', isCorrect: false },
    ],
    correctAnswer: 'Se mettre d\'accord pour alterner et se passer la balançoire à tour de rôle.',
    explanation: 'Partager, c\'est trouver un arrangement pour que chacun puisse profiter du matériel. C\'est une valeur importante.',
    hint: 'À tour de rôle = tout le monde est content !',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-017',
    subject: 'decouverte_du_monde',
    title: 'La solidarité',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un camarade a oublié son goûter. Tu as un grand goûter. Que peux-tu faire ?',
    options: [
      { id: 'a', text: 'Manger tout devant lui.', isCorrect: false },
      { id: 'b', text: 'Lui partager une partie de ton goûter.', isCorrect: true },
      { id: 'c', text: 'Lui demander de l\'argent.', isCorrect: false },
      { id: 'd', text: 'Faire semblant de ne pas l\'avoir vu.', isCorrect: false },
    ],
    correctAnswer: 'Lui partager une partie de ton goûter.',
    explanation: 'La solidarité, c\'est aider les autres quand on peut. Partager son goûter est un beau geste de solidarité.',
    hint: 'Partager avec quelqu\'un qui en a besoin, c\'est la solidarité.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-018',
    subject: 'decouverte_du_monde',
    title: 'Le respect des différences',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un élève parle une autre langue à la maison. Que doit-on faire ?',
    options: [
      { id: 'a', text: 'Se moquer de lui.', isCorrect: false },
      { id: 'b', text: 'Le respecter — parler plusieurs langues est une richesse.', isCorrect: true },
      { id: 'c', text: 'L\'ignorer.', isCorrect: false },
      { id: 'd', text: 'Lui interdire de parler sa langue.', isCorrect: false },
    ],
    correctAnswer: 'Le respecter — parler plusieurs langues est une richesse.',
    explanation: 'Les différences entre les personnes (langues, cultures, façons de vivre) s\'acceptent et s\'enrichissent mutuellement.',
    hint: 'La différence est une richesse, pas un problème.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-019',
    subject: 'decouverte_du_monde',
    title: 'Les règles de la classe',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi servent les règles de la classe ?',
    options: [
      { id: 'a', text: 'À punir les élèves', isCorrect: false },
      { id: 'b', text: 'À permettre à tout le monde de travailler dans de bonnes conditions', isCorrect: true },
      { id: 'c', text: 'À occuper les enfants', isCorrect: false },
      { id: 'd', text: 'À rien de particulier', isCorrect: false },
    ],
    correctAnswer: 'À permettre à tout le monde de travailler dans de bonnes conditions',
    explanation: 'Les règles de la classe (lever la main, écouter, ne pas déranger) sont faites pour que tout le monde apprenne bien.',
    hint: 'Les règles sont là pour aider tout le monde.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-020',
    subject: 'decouverte_du_monde',
    title: 'L\'égalité filles-garçons',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'regles_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À l\'école, les filles et les garçons…',
    options: [
      { id: 'a', text: 'N\'ont pas les mêmes droits.', isCorrect: false },
      { id: 'b', text: 'Ont les mêmes droits et les mêmes devoirs.', isCorrect: true },
      { id: 'c', text: 'Apprennent des matières différentes.', isCorrect: false },
      { id: 'd', text: 'Ne peuvent pas jouer ensemble.', isCorrect: false },
    ],
    correctAnswer: 'Ont les mêmes droits et les mêmes devoirs.',
    explanation: 'À l\'école républicaine française, filles et garçons ont exactement les mêmes droits et les mêmes devoirs.',
    hint: 'L\'égalité est une valeur fondamentale de la République.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-021',
    subject: 'decouverte_du_monde',
    title: 'Les services de la commune',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'services',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La mairie est un service public. Cela signifie qu\'elle…',
    options: [
      { id: 'a', text: 'Est réservée aux adultes riches.', isCorrect: false },
      { id: 'b', text: 'Sert tous les habitants de la commune.', isCorrect: true },
      { id: 'c', text: 'N\'est ouverte qu\'aux entreprises.', isCorrect: false },
      { id: 'd', text: 'Vend des produits alimentaires.', isCorrect: false },
    ],
    correctAnswer: 'Sert tous les habitants de la commune.',
    explanation: 'Un service public est un service accessible à tous les habitants, comme la mairie, l\'école ou la bibliothèque.',
    hint: '« Public » = pour tout le monde.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-022',
    subject: 'decouverte_du_monde',
    title: 'Le rôle de l\'école',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'services',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle principal de l\'école ?',
    options: [
      { id: 'a', text: 'Garder les enfants pendant que les parents travaillent.', isCorrect: false },
      { id: 'b', text: 'Transmettre des savoirs et former des citoyens.', isCorrect: true },
      { id: 'c', text: 'Offrir des repas gratuits.', isCorrect: false },
      { id: 'd', text: 'Organiser des jeux uniquement.', isCorrect: false },
    ],
    correctAnswer: 'Transmettre des savoirs et former des citoyens.',
    explanation: 'L\'école apprend à lire, écrire et compter, mais aussi à vivre ensemble et à devenir citoyen.',
    hint: 'L\'école apprend des connaissances ET des valeurs.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-023',
    subject: 'decouverte_du_monde',
    title: 'L\'hôpital public',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'services',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'hôpital public accueille les malades…',
    options: [
      { id: 'a', text: 'uniquement s\'ils ont beaucoup d\'argent', isCorrect: false },
      { id: 'b', text: 'quelles que soient leurs ressources financières', isCorrect: true },
      { id: 'c', text: 'seulement le week-end', isCorrect: false },
      { id: 'd', text: 'uniquement pour les opérations graves', isCorrect: false },
    ],
    correctAnswer: 'quelles que soient leurs ressources financières',
    explanation: 'L\'hôpital public soigne tout le monde, riche ou pauvre. C\'est un service public essentiel.',
    hint: 'Les services publics sont accessibles à tous.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-rep-024',
    subject: 'decouverte_du_monde',
    title: 'Les pompiers : mission',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'reperes',
    subskill: 'services',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les pompiers interviennent pour…',
    options: [
      { id: 'a', text: 'livrer le courrier', isCorrect: false },
      { id: 'b', text: 'éteindre les incendies et secourir les personnes en danger', isCorrect: true },
      { id: 'c', text: 'construire des routes', isCorrect: false },
      { id: 'd', text: 'vendre des médicaments', isCorrect: false },
    ],
    correctAnswer: 'éteindre les incendies et secourir les personnes en danger',
    explanation: 'Les pompiers sont des secouristes. Ils éteignent les feux, secourent les blessés et aident lors d\'accidents.',
    hint: 'Incendie, accident, inondation — ils interviennent toujours.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
