import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe1EspaceExercises: DecouverteExercise[] = [

  // CE1 · espace · maison_ecole
  {
    id: 'ddm-ce1-esp-001',
    subject: 'decouverte_du_monde',
    title: 'Le maître ou la maîtresse',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui s\'occupe des élèves dans une classe à l\'école ?',
    options: [
      { id: 'a', text: 'le facteur', isCorrect: false },
      { id: 'b', text: 'le directeur', isCorrect: false },
      { id: 'c', text: 'le maître ou la maîtresse', isCorrect: true },
      { id: 'd', text: 'le cuisinier', isCorrect: false },
    ],
    correctAnswer: 'le maître ou la maîtresse',
    explanation: 'Le maître (ou la maîtresse) est l\'enseignant(e) de la classe.',
    hint: 'C\'est l\'adulte qui t\'apprend à lire et à compter.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-002',
    subject: 'decouverte_du_monde',
    title: 'La bibliothèque',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis le bon lieu.',
    prompt: 'Dans quel bâtiment va-t-on pour emprunter des livres ?',
    options: [
      { id: 'a', text: 'la mairie', isCorrect: false },
      { id: 'b', text: 'la bibliothèque', isCorrect: true },
      { id: 'c', text: 'la boulangerie', isCorrect: false },
      { id: 'd', text: 'l\'épicerie', isCorrect: false },
    ],
    correctAnswer: 'la bibliothèque',
    explanation: 'La bibliothèque est un endroit où l\'on peut emprunter et lire des livres.',
    hint: 'On y parle doucement pour ne pas déranger les autres lecteurs.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-003',
    subject: 'decouverte_du_monde',
    title: 'Pièce de la maison',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Laquelle de ces choses trouve-t-on dans une maison ?',
    options: [
      { id: 'a', text: 'un stade', isCorrect: false },
      { id: 'b', text: 'une chambre', isCorrect: true },
      { id: 'c', text: 'un marché', isCorrect: false },
      { id: 'd', text: 'une forêt', isCorrect: false },
    ],
    correctAnswer: 'une chambre',
    explanation: 'Dans une maison, il y a des pièces comme la chambre, le salon, la cuisine…',
    hint: 'C\'est une pièce dans laquelle on dort.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-008',
    subject: 'decouverte_du_monde',
    title: 'Préparer les repas',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis la bonne pièce.',
    prompt: 'Dans quelle pièce prépare-t-on les repas à la maison ?',
    options: [
      { id: 'a', text: 'la chambre', isCorrect: false },
      { id: 'b', text: 'le salon', isCorrect: false },
      { id: 'c', text: 'la cuisine', isCorrect: true },
      { id: 'd', text: 'la salle de bains', isCorrect: false },
    ],
    correctAnswer: 'la cuisine',
    explanation: 'Dans la cuisine, il y a une cuisinière, un réfrigérateur et des ustensiles pour cuisiner.',
    hint: 'Ça sent bon quand la soupe est prête.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CE1 · espace · ville_campagne
  {
    id: 'ddm-ce1-esp-004',
    subject: 'decouverte_du_monde',
    title: 'Vivre à la campagne',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'ville_campagne',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où vit-on généralement à la campagne ?',
    options: [
      { id: 'a', text: 'dans un grand immeuble', isCorrect: false },
      { id: 'b', text: 'dans un centre commercial', isCorrect: false },
      { id: 'c', text: 'dans un village ou une ferme', isCorrect: true },
      { id: 'd', text: 'sous la mer', isCorrect: false },
    ],
    correctAnswer: 'dans un village ou une ferme',
    explanation: 'À la campagne, les maisons sont espacées, entourées de nature.',
    hint: 'Il y a moins de bruit et plus d\'animaux qu\'en ville.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-005',
    subject: 'decouverte_du_monde',
    title: 'En ville',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'ville_campagne',
    format: 'qcm',
    instructions: 'Choisis ce qu\'on trouve plutôt en ville.',
    prompt: 'Lequel de ces éléments trouve-t-on plutôt en ville ?',
    options: [
      { id: 'a', text: 'des vaches dans un pré', isCorrect: false },
      { id: 'b', text: 'des champs de blé', isCorrect: false },
      { id: 'c', text: 'des feux de signalisation', isCorrect: true },
      { id: 'd', text: 'des tracteurs', isCorrect: false },
    ],
    correctAnswer: 'des feux de signalisation',
    explanation: 'En ville, il y a beaucoup de voitures et des feux pour organiser la circulation.',
    hint: 'Rouge, orange, vert… tu les vois aux carrefours.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CE1 · espace · quartier
  {
    id: 'ddm-ce1-esp-006',
    subject: 'decouverte_du_monde',
    title: 'Le médecin',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'quartier',
    format: 'qcm',
    instructions: 'Choisis le bon endroit.',
    prompt: 'Où va-t-on quand on est malade dans le quartier ?',
    options: [
      { id: 'a', text: 'à la boulangerie', isCorrect: false },
      { id: 'b', text: 'à la piscine', isCorrect: false },
      { id: 'c', text: 'chez le médecin', isCorrect: true },
      { id: 'd', text: 'à la mairie', isCorrect: false },
    ],
    correctAnswer: 'chez le médecin',
    explanation: 'Le médecin est la personne qui soigne les malades. Son cabinet est souvent dans le quartier.',
    hint: 'C\'est lui qui donne les médicaments.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-007',
    subject: 'decouverte_du_monde',
    title: 'La pharmacie',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'quartier',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où achète-t-on des médicaments dans le quartier ?',
    options: [
      { id: 'a', text: 'à la boulangerie', isCorrect: false },
      { id: 'b', text: 'à la pharmacie', isCorrect: true },
      { id: 'c', text: 'à l\'école', isCorrect: false },
      { id: 'd', text: 'au parc', isCorrect: false },
    ],
    correctAnswer: 'à la pharmacie',
    explanation: 'La pharmacie est le magasin où l\'on achète les médicaments. On reconnaît souvent une croix verte sur la façade.',
    hint: 'Elle est repérée par une croix verte.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
