import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe1EspacePaysagesExercises: DecouverteExercise[] = [

  // CE1 · espace · paysages
  {
    id: 'ddm-ce1-esp-009',
    subject: 'decouverte_du_monde',
    title: 'Le littoral',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un littoral, c\'est…',
    options: [
      { id: 'a', text: 'un sommet de montagne', isCorrect: false },
      { id: 'b', text: 'la zone où la terre rencontre la mer', isCorrect: true },
      { id: 'c', text: 'un type de forêt tropicale', isCorrect: false },
      { id: 'd', text: 'une plaine sans végétation', isCorrect: false },
    ],
    correctAnswer: 'la zone où la terre rencontre la mer',
    explanation: 'Le littoral est la zone de contact entre la terre et la mer. On y trouve des plages, des falaises ou des dunes.',
    hint: 'C\'est là où la mer touche la terre.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-010',
    subject: 'decouverte_du_monde',
    title: 'La falaise',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une falaise est…',
    options: [
      { id: 'a', text: 'une plage de sable fin', isCorrect: false },
      { id: 'b', text: 'une paroi rocheuse abrupte au bord de la mer', isCorrect: true },
      { id: 'c', text: 'un lac de montagne', isCorrect: false },
      { id: 'd', text: 'une forêt en bord de mer', isCorrect: false },
    ],
    correctAnswer: 'une paroi rocheuse abrupte au bord de la mer',
    explanation: 'Une falaise est une paroi rocheuse verticale qui domine la mer. Les falaises d\'Étretat en Normandie sont très connues.',
    hint: 'Ce sont des roches très hautes en bord de mer.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-011',
    subject: 'decouverte_du_monde',
    title: 'La montagne et la vallée',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La vallée se trouve…',
    options: [
      { id: 'a', text: 'au sommet d\'une montagne', isCorrect: false },
      { id: 'b', text: 'entre deux reliefs (montagnes ou collines)', isCorrect: true },
      { id: 'c', text: 'au fond de la mer', isCorrect: false },
      { id: 'd', text: 'dans un désert', isCorrect: false },
    ],
    correctAnswer: 'entre deux reliefs (montagnes ou collines)',
    explanation: 'La vallée est un espace bas situé entre deux montagnes ou deux collines. Une rivière ou un fleuve y coule souvent.',
    hint: 'C\'est le creux entre deux montagnes.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-012',
    subject: 'decouverte_du_monde',
    title: 'La plaine agricole',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi cultive-t-on souvent sur les plaines ?',
    options: [
      { id: 'a', text: 'Parce que le sol est plat et facile à labourer.', isCorrect: true },
      { id: 'b', text: 'Parce qu\'il neige beaucoup sur les plaines.', isCorrect: false },
      { id: 'c', text: 'Parce que les plaines sont toujours humides.', isCorrect: false },
      { id: 'd', text: 'Parce qu\'il y a toujours un fleuve.', isCorrect: false },
    ],
    correctAnswer: 'Parce que le sol est plat et facile à labourer.',
    explanation: 'Le sol plat des plaines est plus facile à labourer avec des machines agricoles. On y cultive blé, maïs, tournesols…',
    hint: 'Le relief plat facilite le travail des machines.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-013',
    subject: 'decouverte_du_monde',
    title: 'Le bocage',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le bocage est un paysage de campagne où les champs sont…',
    options: [
      { id: 'a', text: 'entourés de grandes routes', isCorrect: false },
      { id: 'b', text: 'entourés de haies et de talus d\'arbres', isCorrect: true },
      { id: 'c', text: 'recouverts de neige en permanence', isCorrect: false },
      { id: 'd', text: 'sans aucune végétation', isCorrect: false },
    ],
    correctAnswer: 'entourés de haies et de talus d\'arbres',
    explanation: 'Le bocage est un paysage typique de Normandie et de Bretagne, avec des champs entourés de haies et d\'arbres.',
    hint: 'Typique de Normandie et Bretagne — les champs y sont séparés par des haies.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-014',
    subject: 'decouverte_du_monde',
    title: 'Le fleuve et la rivière',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la différence entre un fleuve et une rivière ?',
    options: [
      { id: 'a', text: 'Le fleuve est plus petit.', isCorrect: false },
      { id: 'b', text: 'Le fleuve se jette dans la mer, la rivière dans un autre cours d\'eau.', isCorrect: true },
      { id: 'c', text: 'La rivière est plus longue.', isCorrect: false },
      { id: 'd', text: 'Il n\'y a aucune différence.', isCorrect: false },
    ],
    correctAnswer: 'Le fleuve se jette dans la mer, la rivière dans un autre cours d\'eau.',
    explanation: 'Un fleuve se jette dans la mer ou l\'océan. Une rivière est un affluent — elle se jette dans un autre cours d\'eau.',
    hint: 'Le fleuve finit dans la mer. La rivière finit dans un fleuve ou une autre rivière.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-015',
    subject: 'decouverte_du_monde',
    title: 'Le lac',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un lac est une étendue d\'eau…',
    options: [
      { id: 'a', text: 'salée et en mouvement', isCorrect: false },
      { id: 'b', text: 'douce entourée de terres', isCorrect: true },
      { id: 'c', text: 'qui coule vers la mer', isCorrect: false },
      { id: 'd', text: 'artificielle uniquement', isCorrect: false },
    ],
    correctAnswer: 'douce entourée de terres',
    explanation: 'Un lac est une étendue d\'eau douce et calme entourée de terres. Le lac Léman et le lac d\'Annecy sont de beaux exemples.',
    hint: 'Il est entouré de terre de tous les côtés.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-016',
    subject: 'decouverte_du_monde',
    title: 'Paysages de France : Bretagne',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Bretagne est une région de France connue pour…',
    options: [
      { id: 'a', text: 'ses hautes montagnes enneigées', isCorrect: false },
      { id: 'b', text: 'ses côtes rocheuses et la mer', isCorrect: true },
      { id: 'c', text: 'ses grandes plaines de blé', isCorrect: false },
      { id: 'd', text: 'son désert aride', isCorrect: false },
    ],
    correctAnswer: 'ses côtes rocheuses et la mer',
    explanation: 'La Bretagne est une péninsule (avancée de terre dans la mer) avec de nombreuses côtes rocheuses et des plages.',
    hint: 'Elle est entourée d\'eau presque de tous les côtés.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-017',
    subject: 'decouverte_du_monde',
    title: 'Paysages de France : les Alpes',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les Alpes sont…',
    options: [
      { id: 'a', text: 'une chaîne de montagnes dans le sud-est de la France', isCorrect: true },
      { id: 'b', text: 'une côte de plages au bord de la Méditerranée', isCorrect: false },
      { id: 'c', text: 'une grande forêt en Normandie', isCorrect: false },
      { id: 'd', text: 'un fleuve qui traverse Paris', isCorrect: false },
    ],
    correctAnswer: 'une chaîne de montagnes dans le sud-est de la France',
    explanation: 'Les Alpes sont une grande chaîne de montagnes à l\'est de la France. Le mont Blanc y est le plus haut sommet d\'Europe.',
    hint: 'C\'est là où l\'on trouve le mont Blanc.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-018',
    subject: 'decouverte_du_monde',
    title: 'Paysage méditerranéen',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sur les côtes de la mer Méditerranée (sud de la France), quel paysage retrouve-t-on ?',
    options: [
      { id: 'a', text: 'des glaciers et de la neige', isCorrect: false },
      { id: 'b', text: 'des plages, des garrigues et des oliviers', isCorrect: true },
      { id: 'c', text: 'des marécages gelés', isCorrect: false },
      { id: 'd', text: 'des forêts de sapins', isCorrect: false },
    ],
    correctAnswer: 'des plages, des garrigues et des oliviers',
    explanation: 'Le paysage méditerranéen est caractérisé par un été chaud et sec, avec des oliviers, des garrigues et des plages.',
    hint: 'C\'est le paysage du Midi — chaud et sec en été.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-019',
    subject: 'decouverte_du_monde',
    title: 'La dune',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une dune est…',
    options: [
      { id: 'a', text: 'une colline rocheuse en montagne', isCorrect: false },
      { id: 'b', text: 'un tas de sable formé par le vent, souvent en bord de mer', isCorrect: true },
      { id: 'c', text: 'un type de forêt de pins', isCorrect: false },
      { id: 'd', text: 'un nom de rivière', isCorrect: false },
    ],
    correctAnswer: 'un tas de sable formé par le vent, souvent en bord de mer',
    explanation: 'Les dunes sont formées par l\'accumulation de sable poussé par le vent. La dune du Pilat en Gironde est la plus haute d\'Europe.',
    hint: 'La dune du Pilat est la plus haute d\'Europe.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-020',
    subject: 'decouverte_du_monde',
    title: 'La forêt de conifères',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les sapins et les pins sont des arbres que l\'on trouve surtout…',
    options: [
      { id: 'a', text: 'au fond des océans', isCorrect: false },
      { id: 'b', text: 'en altitude, dans les forêts de montagne', isCorrect: true },
      { id: 'c', text: 'uniquement en ville', isCorrect: false },
      { id: 'd', text: 'sur les plages de sable', isCorrect: false },
    ],
    correctAnswer: 'en altitude, dans les forêts de montagne',
    explanation: 'Les conifères (sapins, pins, épicéas) résistent au froid et poussent en altitude. On les trouve dans les Alpes et les Vosges.',
    hint: 'Ce sont des arbres à feuilles persistantes qui résistent au froid.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-021',
    subject: 'decouverte_du_monde',
    title: 'Le relief et le risque',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans les montagnes enneigées, quel danger naturel existe ?',
    options: [
      { id: 'a', text: 'les tsunamis', isCorrect: false },
      { id: 'b', text: 'les avalanches', isCorrect: true },
      { id: 'c', text: 'les cyclones', isCorrect: false },
      { id: 'd', text: 'les éruptions volcaniques uniquement', isCorrect: false },
    ],
    correctAnswer: 'les avalanches',
    explanation: 'Une avalanche est une coulée de neige qui dévale la montagne rapidement. C\'est un danger sérieux en hiver dans les Alpes.',
    hint: 'La neige peut dévaler la montagne en masse.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-022',
    subject: 'decouverte_du_monde',
    title: 'La Camargue',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Camargue est un paysage de marais (zones humides) dans le sud de la France. Quel animal emblématique y vit ?',
    options: [
      { id: 'a', text: 'l\'ours blanc', isCorrect: false },
      { id: 'b', text: 'le flamant rose', isCorrect: true },
      { id: 'c', text: 'le pingouin', isCorrect: false },
      { id: 'd', text: 'le kangourou', isCorrect: false },
    ],
    correctAnswer: 'le flamant rose',
    explanation: 'La Camargue est un delta du Rhône avec des zones humides. On y voit des flamants roses, des taureaux et des chevaux blancs.',
    hint: 'C\'est un bel oiseau rose qui aime les zones humides.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-023',
    subject: 'decouverte_du_monde',
    title: 'Zones humides',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un marais est une zone…',
    options: [
      { id: 'a', text: 'très sèche et sans végétation', isCorrect: false },
      { id: 'b', text: 'humide avec de l\'eau et des plantes aquatiques', isCorrect: true },
      { id: 'c', text: 'froide en haute montagne', isCorrect: false },
      { id: 'd', text: 'uniquement en bord de mer', isCorrect: false },
    ],
    correctAnswer: 'humide avec de l\'eau et des plantes aquatiques',
    explanation: 'Un marais est une zone humide, peu profonde, avec de l\'eau et une végétation adaptée (roseaux, nénuphars…). De nombreux oiseaux y nichent.',
    hint: 'L\'eau y est présente en permanence, mais peu profonde.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-024',
    subject: 'decouverte_du_monde',
    title: 'La forêt et ses arbres',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis le bon arbre.',
    prompt: 'Quel arbre perd ses feuilles en automne ?',
    options: [
      { id: 'a', text: 'le sapin', isCorrect: false },
      { id: 'b', text: 'le chêne', isCorrect: true },
      { id: 'c', text: 'le pin', isCorrect: false },
      { id: 'd', text: 'le cèdre', isCorrect: false },
    ],
    correctAnswer: 'le chêne',
    explanation: 'Le chêne est un arbre à feuilles caduques — il perd ses feuilles en automne. Les sapins et pins, eux, restent verts toute l\'année.',
    hint: 'Les arbres à feuilles caduques perdent leurs feuilles en automne.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-025',
    subject: 'decouverte_du_monde',
    title: 'La végétation et le climat',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi trouve-t-on des oliviers dans le sud de la France mais pas dans le nord ?',
    options: [
      { id: 'a', text: 'Parce que le nord de la France interdit les oliviers.', isCorrect: false },
      { id: 'b', text: 'Parce que les oliviers ont besoin d\'un climat chaud et sec que seul le sud offre.', isCorrect: true },
      { id: 'c', text: 'Parce que les oliviers ne poussent qu\'en Afrique.', isCorrect: false },
      { id: 'd', text: 'Parce que les oliviers aiment la neige.', isCorrect: false },
    ],
    correctAnswer: 'Parce que les oliviers ont besoin d\'un climat chaud et sec que seul le sud offre.',
    explanation: 'La végétation dépend du climat. Les oliviers ont besoin de chaleur et de sécheresse estivale — des conditions méditerranéennes.',
    hint: 'La plante pousse là où le climat lui convient.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-026',
    subject: 'decouverte_du_monde',
    title: 'La côte et le port',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sur le littoral, un port sert principalement à…',
    options: [
      { id: 'a', text: 'garer les voitures', isCorrect: false },
      { id: 'b', text: 'accueillir les bateaux de pêche et de voyageurs', isCorrect: true },
      { id: 'c', text: 'stocker du blé', isCorrect: false },
      { id: 'd', text: 'construire des maisons', isCorrect: false },
    ],
    correctAnswer: 'accueillir les bateaux de pêche et de voyageurs',
    explanation: 'Un port est un abri naturel ou artificiel pour les bateaux. On y trouve des bateaux de pêche, des ferries et des voiliers.',
    hint: 'Les bateaux s\'y abritent et s\'y ravitaillent.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-027',
    subject: 'decouverte_du_monde',
    title: 'La région et ses paysages',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une région de France peut avoir des paysages très différents (plaines, forêts, côtes). Qu\'est-ce que cela montre ?',
    options: [
      { id: 'a', text: 'Que la France est une petite île.', isCorrect: false },
      { id: 'b', text: 'Que la France a une grande diversité de paysages naturels.', isCorrect: true },
      { id: 'c', text: 'Que la France n\'a pas de montagne.', isCorrect: false },
      { id: 'd', text: 'Que tous les paysages de France sont identiques.', isCorrect: false },
    ],
    correctAnswer: 'Que la France a une grande diversité de paysages naturels.',
    explanation: 'La France est un pays varié avec des montagnes (Alpes, Pyrénées), des côtes, des plaines, des forêts et des fleuves.',
    hint: 'La France est grande et diverse !',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce1-esp-028',
    subject: 'decouverte_du_monde',
    title: 'Paysage et activité humaine',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les humains modifient les paysages. Lequel de ces exemples montre une modification humaine du paysage ?',
    options: [
      { id: 'a', text: 'Une rivière qui coule naturellement.', isCorrect: false },
      { id: 'b', text: 'La construction d\'un barrage pour retenir l\'eau.', isCorrect: true },
      { id: 'c', text: 'La poussée d\'une forêt.', isCorrect: false },
      { id: 'd', text: 'Le coucher du soleil.', isCorrect: false },
    ],
    correctAnswer: 'La construction d\'un barrage pour retenir l\'eau.',
    explanation: 'Les humains transforment les paysages en construisant des routes, des villes, des barrages ou en cultivant la terre.',
    hint: 'Une construction humaine change toujours le paysage naturel.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
