import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe1NumerationExercises: MathExercise[] = [
  {
    id: 'ma-ce1-numeration-001',
    subject: 'mathematiques',
    title: 'Dizaines et unités',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'dizaines et unités',
    format: 'qcm',
    instructions: 'Décompose le nombre.',
    prompt: '37 = ___ dizaines et ___ unités',
    options: [
      { id: 'a', text: '3 dizaines et 7 unités', isCorrect: true },
      { id: 'b', text: '7 dizaines et 3 unités', isCorrect: false },
      { id: 'c', text: '4 dizaines et 7 unités', isCorrect: false },
    ],
    correctAnswer: '3 dizaines et 7 unités',
    explanation: '37 = 3 dizaines (30) + 7 unités.',
    hint: 'Le chiffre des dizaines est le premier chiffre à gauche.',
    tags: ['ce1', 'numeration', 'dizaines', 'unités', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-002',
    subject: 'mathematiques',
    title: 'Comparer deux nombres à 2 chiffres',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Quel est le plus grand nombre ?',
    prompt: 'Quel est le plus grand : 45, 54 ou 49 ?',
    options: [
      { id: 'a', text: '45', isCorrect: false },
      { id: 'b', text: '54', isCorrect: true },
      { id: 'c', text: '49', isCorrect: false },
    ],
    correctAnswer: '54',
    explanation: '54 a 5 dizaines, 45 en a 4, donc 54 > 49 > 45.',
    hint: "Compare d'abord le chiffre des dizaines.",
    tags: ['ce1', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-003',
    subject: 'mathematiques',
    title: "Valeur positionnelle jusqu'à 100",
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'dizaines et unités',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: 'Quel nombre a 5 dizaines et 9 unités ?',
    options: [
      { id: 'a', text: '50', isCorrect: false },
      { id: 'b', text: '59', isCorrect: true },
      { id: 'c', text: '95', isCorrect: false },
    ],
    correctAnswer: '59',
    explanation: '5 dizaines = 50. 50 + 9 unités = 59.',
    hint: "5 dizaines, c'est 5 × 10 = 50. Ajoute les 9 unités.",
    tags: ['ce1', 'numeration', 'dizaines', 'unités', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { extraHint: '5 dizaines = 50. 50 + 9 = ?' },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-004',
    subject: 'mathematiques',
    title: 'Suite correcte',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve la suite correcte.',
    prompt: 'Quelle est la suite correcte ?',
    options: [
      { id: 'a', text: '15, 16, 18', isCorrect: false },
      { id: 'b', text: '15, 16, 17', isCorrect: true },
      { id: 'c', text: '15, 17, 18', isCorrect: false },
    ],
    correctAnswer: '15, 16, 17',
    explanation: 'On compte de 1 en 1 : 15, 16, 17.',
    hint: 'On ajoute 1 à chaque fois.',
    tags: ['ce1', 'numeration', 'suite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-005',
    subject: 'mathematiques',
    title: 'Suite par 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '12, 14, 16, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '17', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: 'On ajoute 2 à chaque fois : 16 + 2 = 18.',
    hint: 'Quelle est la différence entre 12 et 14 ?',
    tags: ['ce1', 'numeration', 'suite', 'pairs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Quel sera le 5ᵉ nombre après 18 ?' },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-006',
    subject: 'mathematiques',
    title: 'Encadrer un nombre',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Trouve les bons nombres.',
    prompt: 'Entre quels dizaines se trouve 47 ?',
    options: [
      { id: 'a', text: '30 et 40', isCorrect: false },
      { id: 'b', text: '40 et 50', isCorrect: true },
      { id: 'c', text: '50 et 60', isCorrect: false },
    ],
    correctAnswer: '40 et 50',
    explanation: '40 < 47 < 50. Le 47 est bien entre 40 et 50.',
    hint: 'Regarde le chiffre des dizaines : 4 → entre 40 et 50.',
    tags: ['ce1', 'numeration', 'encadrement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-007',
    subject: 'mathematiques',
    title: 'Ordre croissant',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'ordre',
    format: 'qcm',
    instructions: 'Range dans l\'ordre croissant.',
    prompt: '63, 36, 56. Quel est le bon ordre croissant ?',
    options: [
      { id: 'a', text: '63, 56, 36', isCorrect: false },
      { id: 'b', text: '36, 56, 63', isCorrect: true },
      { id: 'c', text: '36, 63, 56', isCorrect: false },
    ],
    correctAnswer: '36, 56, 63',
    explanation: '36 < 56 < 63. Ordre croissant : du plus petit au plus grand.',
    hint: 'Compare les dizaines d\'abord.',
    tags: ['ce1', 'numeration', 'ordre', 'croissant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-008',
    subject: 'mathematiques',
    title: 'Centaine',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'centaine',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de dizaines y a-t-il dans 100 ?',
    options: [
      { id: 'a', text: '10', isCorrect: true },
      { id: 'b', text: '100', isCorrect: false },
      { id: 'c', text: '1', isCorrect: false },
    ],
    correctAnswer: '10',
    explanation: '100 = 10 dizaines. 10 × 10 = 100.',
    hint: '10, 20, 30... jusqu\'à 100 : combien de pas ?',
    tags: ['ce1', 'numeration', 'centaine', 'dizaines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-009',
    subject: 'mathematiques',
    title: 'Suite par 10',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '10, 20, 30, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '35', isCorrect: false },
      { id: 'b', text: '40', isCorrect: true },
      { id: 'c', text: '50', isCorrect: false },
    ],
    correctAnswer: '40',
    explanation: 'On ajoute 10 à chaque fois : 30 + 10 = 40.',
    hint: 'C\'est la table de 10.',
    tags: ['ce1', 'numeration', 'suite', 'dizaines', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-010',
    subject: 'mathematiques',
    title: 'Chiffre des unités',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'dizaines et unités',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans le nombre 73, quel est le chiffre des unités ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '73 = 7 dizaines + 3 unités. Le chiffre des unités est 3.',
    hint: 'Le chiffre des unités est le dernier chiffre à droite.',
    tags: ['ce1', 'numeration', 'unités', 'positionnelle', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-011',
    subject: 'mathematiques',
    title: 'Nombre pair ou impair',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'parité',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '14 est un nombre pair ou impair ?',
    options: [
      { id: 'a', text: 'Impair', isCorrect: false },
      { id: 'b', text: 'Pair', isCorrect: true },
      { id: 'c', text: 'Ni l\'un ni l\'autre', isCorrect: false },
    ],
    correctAnswer: 'Pair',
    explanation: '14 se termine par 4, c\'est un chiffre pair. 14 est donc pair.',
    hint: 'Un nombre pair se termine par 0, 2, 4, 6 ou 8.',
    tags: ['ce1', 'numeration', 'pair', 'impair', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-012',
    subject: 'mathematiques',
    title: 'Centaines',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'centaines',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '3 centaines, c\'est combien ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '30', isCorrect: false },
      { id: 'c', text: '300', isCorrect: true },
    ],
    correctAnswer: '300',
    explanation: '3 centaines = 3 × 100 = 300.',
    hint: 'Une centaine = 100.',
    tags: ['ce1', 'numeration', 'centaines', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-013',
    subject: 'mathematiques',
    title: 'Décomposer 234',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'décomposition',
    format: 'qcm',
    instructions: 'Décompose ce nombre.',
    prompt: '234 = ___ centaines + ___ dizaines + ___ unités',
    options: [
      { id: 'a', text: '2 c + 3 d + 4 u', isCorrect: true },
      { id: 'b', text: '3 c + 2 d + 4 u', isCorrect: false },
      { id: 'c', text: '2 c + 4 d + 3 u', isCorrect: false },
    ],
    correctAnswer: '2 c + 3 d + 4 u',
    explanation: '234 = 2 centaines + 3 dizaines + 4 unités.',
    hint: 'Le premier chiffre = centaines, deuxième = dizaines, troisième = unités.',
    tags: ['ce1', 'numeration', 'décomposition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-014',
    subject: 'mathematiques',
    title: 'Comparer 145 et 154',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Compare ces deux nombres.',
    prompt: 'Quel est le plus grand : 145 ou 154 ?',
    options: [
      { id: 'a', text: '145', isCorrect: false },
      { id: 'b', text: '154', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '154',
    explanation: '154 > 145. Les centaines sont identiques (1), mais 5 dizaines > 4 dizaines.',
    hint: 'Regarde les dizaines : 5 ou 4 ?',
    tags: ['ce1', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-015',
    subject: 'mathematiques',
    title: 'Encadrement de 267',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Encadre ce nombre à la dizaine.',
    prompt: '267 est entre quelles dizaines ?',
    options: [
      { id: 'a', text: 'Entre 260 et 270', isCorrect: true },
      { id: 'b', text: 'Entre 270 et 280', isCorrect: false },
      { id: 'c', text: 'Entre 250 et 260', isCorrect: false },
    ],
    correctAnswer: 'Entre 260 et 270',
    explanation: '260 < 267 < 270.',
    hint: 'Regarde les dizaines de 267 : 6 dizaines = 260.',
    tags: ['ce1', 'numeration', 'encadrement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-016',
    subject: 'mathematiques',
    title: 'Nombre impair',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'pair et impair',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Parmi 12, 15, 20, lequel est impair ?',
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: '15 se termine par 5, donc c\'est impair. 12 et 20 sont pairs.',
    hint: 'Un nombre impair se termine par 1, 3, 5, 7 ou 9.',
    tags: ['ce1', 'numeration', 'pair', 'impair', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-017',
    subject: 'mathematiques',
    title: 'Suite par dizaines',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '130, 140, 150, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '155', isCorrect: false },
      { id: 'b', text: '160', isCorrect: true },
      { id: 'c', text: '170', isCorrect: false },
    ],
    correctAnswer: '160',
    explanation: 'On ajoute 10 à chaque fois : 150 + 10 = 160.',
    hint: 'La suite avance de 10 en 10.',
    tags: ['ce1', 'numeration', 'suite', 'dizaines', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce1-numeration-018',
    subject: 'mathematiques',
    title: 'Ranger 312, 123, 231',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'numeration',
    subskill: 'ordre croissant',
    format: 'qcm',
    instructions: 'Range du plus petit au plus grand.',
    prompt: '312, 123, 231 — Quel est l\'ordre croissant ?',
    options: [
      { id: 'a', text: '312, 231, 123', isCorrect: false },
      { id: 'b', text: '123, 231, 312', isCorrect: true },
      { id: 'c', text: '231, 123, 312', isCorrect: false },
    ],
    correctAnswer: '123, 231, 312',
    explanation: '123 < 231 < 312.',
    hint: 'Compare les centaines d\'abord : 1 < 2 < 3.',
    tags: ['ce1', 'numeration', 'ordre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
];
