import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe1LogiqueExercises: MathExercise[] = [
  {
    id: 'ma-ce1-logique-001',
    subject: 'mathematiques',
    title: 'Suite par 5',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '5, 10, 15, 20, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '22', isCorrect: false },
      { id: 'b', text: '24', isCorrect: false },
      { id: 'c', text: '25', isCorrect: true },
    ],
    correctAnswer: '25',
    explanation: 'On ajoute 5 à chaque fois : 20 + 5 = 25.',
    hint: "C'est la table de 5 : 5, 10, 15…",
    tags: ['ce1', 'logique', 'suite', 'table de 5', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-002',
    subject: 'mathematiques',
    title: 'Suite par 3',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '3, 6, 9, 12, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '13', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: '16', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: 'On ajoute 3 à chaque fois : 12 + 3 = 15.',
    hint: 'C\'est la table de 3.',
    tags: ['ce1', 'logique', 'suite', 'table_3', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-003',
    subject: 'mathematiques',
    title: 'Intrus dans la suite',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Trouve l\'intrus.',
    prompt: '2, 4, 6, 7, 8. Quel est l\'intrus ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: '2, 4, 6, 8 sont des nombres pairs. 7 est impair, c\'est l\'intrus.',
    hint: 'Cherche le nombre qui ne suit pas la règle.',
    tags: ['ce1', 'logique', 'intrus', 'pair', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-004',
    subject: 'mathematiques',
    title: 'Lire un graphique en barres',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de données',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans un graphique, la barre "chats" est à 5 et la barre "chiens" est à 3. Quel animal est le plus aimé ?',
    options: [
      { id: 'a', text: 'Les chiens', isCorrect: false },
      { id: 'b', text: 'Les chats', isCorrect: true },
      { id: 'c', text: 'Pareil', isCorrect: false },
    ],
    correctAnswer: 'Les chats',
    explanation: '5 > 3, donc les chats sont plus aimés.',
    hint: 'La barre la plus haute correspond à l\'animal le plus aimé.',
    tags: ['ce1', 'logique', 'graphique', 'données', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-005',
    subject: 'mathematiques',
    title: 'Suite décroissante',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '50, 45, 40, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '30', isCorrect: false },
      { id: 'b', text: '35', isCorrect: true },
      { id: 'c', text: '38', isCorrect: false },
    ],
    correctAnswer: '35',
    explanation: 'On enlève 5 à chaque fois : 40 − 5 = 35.',
    hint: 'La suite diminue. De combien à chaque fois ?',
    tags: ['ce1', 'logique', 'suite', 'decroissant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-006',
    subject: 'mathematiques',
    title: 'Condition vrai/faux',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'raisonnement',
    format: 'qcm',
    instructions: 'Vrai ou faux ?',
    prompt: 'Tous les carrés sont des rectangles. C\'est vrai ou faux ?',
    options: [
      { id: 'a', text: 'Faux', isCorrect: false },
      { id: 'b', text: 'Vrai', isCorrect: true },
      { id: 'c', text: 'Ça dépend', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: 'Un carré est un rectangle particulier où tous les côtés sont égaux.',
    hint: 'Un rectangle a 4 côtés et 4 angles droits. Un carré aussi.',
    tags: ['ce1', 'logique', 'raisonnement', 'vrai_faux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-007',
    subject: 'mathematiques',
    title: 'Suite +3',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le terme suivant.',
    prompt: '5, 8, 11, 14, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '16', isCorrect: false },
      { id: 'b', text: '17', isCorrect: true },
      { id: 'c', text: '18', isCorrect: false },
    ],
    correctAnswer: '17',
    explanation: 'On ajoute 3 à chaque fois : 14 + 3 = 17.',
    hint: 'Calcule la différence entre chaque terme.',
    tags: ['ce1', 'logique', 'suite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-008',
    subject: 'mathematiques',
    title: 'Tableau : fruits',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de tableau',
    format: 'qcm',
    instructions: 'Lis le tableau.',
    prompt: 'Pommes vendues : lundi 12, mardi 8, mercredi 15. Quel jour en a-t-on vendu le moins ?',
    options: [
      { id: 'a', text: 'Lundi', isCorrect: false },
      { id: 'b', text: 'Mardi', isCorrect: true },
      { id: 'c', text: 'Mercredi', isCorrect: false },
    ],
    correctAnswer: 'Mardi',
    explanation: '8 < 12 < 15. Le mardi est le plus petit.',
    hint: 'Compare les trois nombres : 12, 8, 15.',
    tags: ['ce1', 'logique', 'tableau', 'données', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-009',
    subject: 'mathematiques',
    title: 'Déduction : quel nombre suis-je ?',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'déduction',
    format: 'qcm',
    instructions: 'Résous l\'énigme.',
    prompt: 'Je suis un nombre entre 30 et 40. Je suis impair. Ma somme de chiffres est 8. Qui suis-je ?',
    options: [
      { id: 'a', text: '35', isCorrect: false },
      { id: 'b', text: '37', isCorrect: false },
      { id: 'c', text: '35', isCorrect: false },
    ],
    correctAnswer: '35',
    explanation: '35 est entre 30 et 40, impair, et 3 + 5 = 8.',
    hint: 'Les nombres impairs entre 30 et 40 : 31, 33, 35, 37, 39. Lequel a une somme de chiffres = 8 ?',
    tags: ['ce1', 'logique', 'déduction', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-010',
    subject: 'mathematiques',
    title: 'Graphique en barres simple',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de graphique',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans un graphique : rouge = 5 votes, bleu = 9 votes, vert = 3 votes. Quelle couleur a le plus de votes ?',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: false },
      { id: 'b', text: 'Bleu', isCorrect: true },
      { id: 'c', text: 'Vert', isCorrect: false },
    ],
    correctAnswer: 'Bleu',
    explanation: '9 > 5 > 3. Le bleu a le plus de votes.',
    hint: 'Compare 5, 9 et 3.',
    tags: ['ce1', 'logique', 'graphique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-011',
    subject: 'mathematiques',
    title: 'Suite décroissante −4',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le terme suivant.',
    prompt: '40, 36, 32, 28, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '22', isCorrect: false },
      { id: 'b', text: '24', isCorrect: true },
      { id: 'c', text: '26', isCorrect: false },
    ],
    correctAnswer: '24',
    explanation: 'On enlève 4 à chaque fois : 28 − 4 = 24.',
    hint: 'Calcule la différence entre chaque terme.',
    tags: ['ce1', 'logique', 'suite', 'décroissante', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-012',
    subject: 'mathematiques',
    title: 'L\'intrus dans les multiples',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Trouve l\'intrus.',
    prompt: 'Parmi 5, 10, 15, 18, 20, lequel n\'est pas un multiple de 5 ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: '18 ÷ 5 = 3 reste 3. 18 n\'est pas divisible par 5.',
    hint: 'Les multiples de 5 se terminent par 0 ou 5.',
    tags: ['ce1', 'logique', 'multiples', 'intrus', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-013',
    subject: 'mathematiques',
    title: 'Suite alternée de signes',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite alternée',
    format: 'qcm',
    instructions: 'Trouve ce qui vient après.',
    prompt: '+, −, +, −, ___ . Quel signe vient après ?',
    options: [
      { id: 'a', text: '−', isCorrect: false },
      { id: 'b', text: '+', isCorrect: true },
      { id: 'c', text: '×', isCorrect: false },
    ],
    correctAnswer: '+',
    explanation: 'Le motif alterne + et −. Après − vient +.',
    hint: 'Le motif se répète : + − + − ...',
    tags: ['ce1', 'logique', 'suite', 'alternée', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce1-logique-014',
    subject: 'mathematiques',
    title: 'Déduction : age',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'déduction',
    format: 'qcm',
    instructions: 'Résous le problème de logique.',
    prompt: 'Alice a 2 ans de plus que Bob. Bob a 5 ans. Quel âge a Alice ?',
    options: [
      { id: 'a', text: '5 ans', isCorrect: false },
      { id: 'b', text: '7 ans', isCorrect: true },
      { id: 'c', text: '9 ans', isCorrect: false },
    ],
    correctAnswer: '7 ans',
    explanation: 'Alice = Bob + 2 = 5 + 2 = 7 ans.',
    hint: 'Ajoute 2 à l\'âge de Bob.',
    tags: ['ce1', 'logique', 'déduction', 'âge', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
];
