import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe1MesuresExercises: MathExercise[] = [
  {
    id: 'ma-ce1-mesures-001',
    subject: 'mathematiques',
    title: 'Additionner des pièces',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Calcule la somme.',
    prompt: "J'ai une pièce de 50 centimes et une pièce de 20 centimes. Combien ai-je en tout ?",
    options: [
      { id: 'a', text: '60 centimes', isCorrect: false },
      { id: 'b', text: '70 centimes', isCorrect: true },
      { id: 'c', text: '80 centimes', isCorrect: false },
    ],
    correctAnswer: '70 centimes',
    explanation: '50 + 20 = 70 centimes.',
    hint: 'Additionne les deux pièces.',
    tags: ['ce1', 'mesures', 'monnaie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-002',
    subject: 'mathematiques',
    title: 'Durée de la récré',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: 'La récré commence à 10h00 et dure 30 minutes. À quelle heure finit-elle ?',
    options: [
      { id: 'a', text: '10h15', isCorrect: false },
      { id: 'b', text: '10h30', isCorrect: true },
      { id: 'c', text: '11h00', isCorrect: false },
    ],
    correctAnswer: '10h30',
    explanation: '10h00 + 30 minutes = 10h30.',
    hint: 'Ajoute 30 minutes à 10h00.',
    tags: ['ce1', 'mesures', 'durée', 'heures', 'minutes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { extraHint: '10h + 30 min = 10h30.' },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-003',
    subject: 'mathematiques',
    title: 'Comparer des longueurs',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'longueurs',
    format: 'qcm',
    instructions: 'Calcule la différence.',
    prompt: 'Une règle mesure 20 cm. Un crayon mesure 12 cm. Quelle est la différence de longueur ?',
    options: [
      { id: 'a', text: '7 cm', isCorrect: false },
      { id: 'b', text: '8 cm', isCorrect: true },
      { id: 'c', text: '9 cm', isCorrect: false },
    ],
    correctAnswer: '8 cm',
    explanation: '20 − 12 = 8 cm.',
    hint: 'Soustrais la longueur du crayon de la longueur de la règle.',
    tags: ['ce1', 'mesures', 'longueurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-004',
    subject: 'mathematiques',
    title: 'Comparer des masses',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'comparaison de masses',
    format: 'qcm',
    instructions: 'Quel est le plus lourd ?',
    prompt: '2 kg ou 800 g ?',
    options: [
      { id: 'a', text: '800 g', isCorrect: false },
      { id: 'b', text: '2 kg', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '2 kg',
    explanation: "1 kg = 1 000 g, donc 2 kg = 2 000 g. C'est bien plus lourd que 800 g.",
    hint: '1 kg vaut 1 000 grammes.',
    tags: ['ce1', 'mesures', 'masse', 'kg', 'grammes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Lequel pèse le plus ?', extraHint: '1 kg = 1 000 g.' },
    }),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-005',
    subject: 'mathematiques',
    title: 'Heure et demie',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'lecture de l\'heure',
    format: 'qcm',
    instructions: 'Lis l\'heure.',
    prompt: 'Il est 4 heures et demie. Quelle heure est-il ?',
    options: [
      { id: 'a', text: '4h00', isCorrect: false },
      { id: 'b', text: '4h30', isCorrect: true },
      { id: 'c', text: '5h00', isCorrect: false },
    ],
    correctAnswer: '4h30',
    explanation: 'Quatre heures et demie = 4h30.',
    hint: 'Une demie heure = 30 minutes.',
    tags: ['ce1', 'mesures', 'heure', 'demie', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-006',
    subject: 'mathematiques',
    title: 'Convertir des cm en m',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'longueurs',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de centimètres y a-t-il dans 1 mètre ?',
    options: [
      { id: 'a', text: '10 cm', isCorrect: false },
      { id: 'b', text: '100 cm', isCorrect: true },
      { id: 'c', text: '1 000 cm', isCorrect: false },
    ],
    correctAnswer: '100 cm',
    explanation: '1 m = 100 cm.',
    hint: 'Une règle de 1 mètre mesure 100 centimètres.',
    tags: ['ce1', 'mesures', 'longueur', 'conversion', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-007',
    subject: 'mathematiques',
    title: 'Durée en minutes',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Calcule la durée.',
    prompt: 'Un film commence à 14h00 et dure 1 heure. À quelle heure se termine-t-il ?',
    options: [
      { id: 'a', text: '14h30', isCorrect: false },
      { id: 'b', text: '15h00', isCorrect: true },
      { id: 'c', text: '16h00', isCorrect: false },
    ],
    correctAnswer: '15h00',
    explanation: '14h00 + 1 heure = 15h00.',
    hint: 'Ajoute 1 heure à 14h.',
    tags: ['ce1', 'mesures', 'durée', 'heure', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-008',
    subject: 'mathematiques',
    title: 'Calcul avec des euros',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'Un cahier coûte 2 € et un stylo 1 €. Combien coûtent-ils ensemble ?',
    options: [
      { id: 'a', text: '2 €', isCorrect: false },
      { id: 'b', text: '3 €', isCorrect: true },
      { id: 'c', text: '4 €', isCorrect: false },
    ],
    correctAnswer: '3 €',
    explanation: '2 € + 1 € = 3 €.',
    hint: 'Additionne les prix.',
    tags: ['ce1', 'mesures', 'monnaie', 'euros', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-009',
    subject: 'mathematiques',
    title: 'Rendu de monnaie',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Calcule la monnaie rendue.',
    prompt: 'Tu paies 5 € pour un jouet qui coûte 3 €. Combien reçois-tu en retour ?',
    options: [
      { id: 'a', text: '1 €', isCorrect: false },
      { id: 'b', text: '2 €', isCorrect: true },
      { id: 'c', text: '3 €', isCorrect: false },
    ],
    correctAnswer: '2 €',
    explanation: '5 € − 3 € = 2 €.',
    hint: 'Soustrais le prix de la somme payée.',
    tags: ['ce1', 'mesures', 'monnaie', 'rendu', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-010',
    subject: 'mathematiques',
    title: 'Combien de minutes dans une heure ?',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien y a-t-il de minutes dans une heure ?',
    options: [
      { id: 'a', text: '24', isCorrect: false },
      { id: 'b', text: '60', isCorrect: true },
      { id: 'c', text: '100', isCorrect: false },
    ],
    correctAnswer: '60',
    explanation: '1 heure = 60 minutes.',
    hint: 'La grande aiguille fait un tour complet en 60 minutes.',
    tags: ['ce1', 'mesures', 'heure', 'minutes', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-011',
    subject: 'mathematiques',
    title: '1 km en mètres',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '2 km = ___ m',
    options: [
      { id: 'a', text: '200 m', isCorrect: false },
      { id: 'b', text: '2000 m', isCorrect: true },
      { id: 'c', text: '20 m', isCorrect: false },
    ],
    correctAnswer: '2000 m',
    explanation: '1 km = 1000 m. Donc 2 km = 2000 m.',
    hint: '1 km = 1000 m.',
    tags: ['ce1', 'mesures', 'longueur', 'conversion', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-012',
    subject: 'mathematiques',
    title: '500 g en kg',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '500 g = ___ kg',
    options: [
      { id: 'a', text: '0,05 kg', isCorrect: false },
      { id: 'b', text: '0,5 kg', isCorrect: true },
      { id: 'c', text: '5 kg', isCorrect: false },
    ],
    correctAnswer: '0,5 kg',
    explanation: '1000 g = 1 kg. 500 g = 0,5 kg (la moitié).',
    hint: '1 kg = 1000 g. 500 c\'est la moitié de 1000.',
    tags: ['ce1', 'mesures', 'masse', 'conversion', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-013',
    subject: 'mathematiques',
    title: 'Durée d\'un trajet',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Calcule la durée.',
    prompt: 'Le bus part à 9 h 00 et arrive à 9 h 35. Combien de temps dure le trajet ?',
    options: [
      { id: 'a', text: '25 minutes', isCorrect: false },
      { id: 'b', text: '35 minutes', isCorrect: true },
      { id: 'c', text: '45 minutes', isCorrect: false },
    ],
    correctAnswer: '35 minutes',
    explanation: '9 h 35 − 9 h 00 = 35 minutes.',
    hint: 'De 9 h à 9 h 35, combien de minutes se sont écoulées ?',
    tags: ['ce1', 'mesures', 'durée', 'trajet', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-014',
    subject: 'mathematiques',
    title: 'Aire sur quadrillage',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'aire',
    format: 'qcm',
    instructions: 'Calcule l\'aire.',
    prompt: 'Une figure couvre 12 carreaux sur un quadrillage. Chaque carreau = 1 cm². Quelle est son aire ?',
    options: [
      { id: 'a', text: '10 cm²', isCorrect: false },
      { id: 'b', text: '12 cm²', isCorrect: true },
      { id: 'c', text: '14 cm²', isCorrect: false },
    ],
    correctAnswer: '12 cm²',
    explanation: 'L\'aire = nombre de carreaux = 12 cm².',
    hint: 'Compte le nombre de carreaux couverts.',
    tags: ['ce1', 'mesures', 'aire', 'quadrillage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-015',
    subject: 'mathematiques',
    title: 'Lire une heure',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'heure',
    format: 'qcm',
    instructions: 'Quelle heure est-il ?',
    prompt: 'La grande aiguille est sur 12 et la petite sur 3. Quelle heure est-il ?',
    options: [
      { id: 'a', text: '12 h 03', isCorrect: false },
      { id: 'b', text: '3 h 00', isCorrect: true },
      { id: 'c', text: '3 h 12', isCorrect: false },
    ],
    correctAnswer: '3 h 00',
    explanation: 'Grande aiguille sur 12 = pile l\'heure. Petite sur 3 = 3 heures.',
    hint: 'La grande aiguille indique les minutes, la petite les heures.',
    tags: ['ce1', 'mesures', 'heure', 'horloge', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-016',
    subject: 'mathematiques',
    title: '100 cm en mètre',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '100 cm = ___ m',
    options: [
      { id: 'a', text: '0,1 m', isCorrect: false },
      { id: 'b', text: '1 m', isCorrect: true },
      { id: 'c', text: '10 m', isCorrect: false },
    ],
    correctAnswer: '1 m',
    explanation: '100 cm = 1 m.',
    hint: '1 m = 100 cm.',
    tags: ['ce1', 'mesures', 'longueur', 'conversion', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-017',
    subject: 'mathematiques',
    title: 'Heure et demie',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Calcule l\'heure d\'arrivée.',
    prompt: 'Le film commence à 14 h. Il dure 1 h 30 min. À quelle heure finit-il ?',
    options: [
      { id: 'a', text: '15 h 00', isCorrect: false },
      { id: 'b', text: '15 h 30', isCorrect: true },
      { id: 'c', text: '16 h 00', isCorrect: false },
    ],
    correctAnswer: '15 h 30',
    explanation: '14 h + 1 h 30 min = 15 h 30.',
    hint: '14 h + 1 h = 15 h. 15 h + 30 min = 15 h 30.',
    tags: ['ce1', 'mesures', 'durée', 'heure', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce1-mesures-018',
    subject: 'mathematiques',
    title: 'Comparaison de masses',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'masses',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un livre pèse 400 g et un cahier 200 g. Combien pèsent-ils ensemble ?',
    options: [
      { id: 'a', text: '500 g', isCorrect: false },
      { id: 'b', text: '600 g', isCorrect: true },
      { id: 'c', text: '700 g', isCorrect: false },
    ],
    correctAnswer: '600 g',
    explanation: '400 + 200 = 600 g.',
    hint: 'Additionne les deux masses.',
    tags: ['ce1', 'mesures', 'masse', 'addition', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
];
