import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe1ProblemesExercises: MathExercise[] = [
  {
    id: 'ma-ce1-problemes-001',
    subject: 'mathematiques',
    title: 'Problème de billes',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Léa a 6 billes. Elle en gagne 4. Combien en a-t-elle maintenant ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '9', isCorrect: false },
      { id: 'c', text: '10', isCorrect: true },
    ],
    correctAnswer: '10',
    explanation: '6 + 4 = 10 billes.',
    hint: 'Elle en avait 6, elle en gagne 4 : additionne.',
    tags: ['ce1', 'problemes', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-002',
    subject: 'mathematiques',
    title: 'Problème de bonbons',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Un paquet contient 12 bonbons. Tom en mange 5. Combien en reste-t-il ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: '12 − 5 = 7 bonbons.',
    hint: 'Il en avait 12, il en mange 5 : soustrais.',
    tags: ['ce1', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-003',
    subject: 'mathematiques',
    title: 'Problème de chaises',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Il y a 3 tables avec 4 chaises chacune. Combien y a-t-il de chaises en tout ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '12', isCorrect: true },
      { id: 'c', text: '14', isCorrect: false },
    ],
    correctAnswer: '12',
    explanation: '3 × 4 = 12 chaises.',
    hint: 'Additionne 4 + 4 + 4 ou fais 3 × 4.',
    tags: ['ce1', 'problemes', 'multiplication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-004',
    subject: 'mathematiques',
    title: 'Comparer des collections',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction en contexte',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: 'Sam a 13 billes. Son ami en a 8. Combien Sam en a-t-il de plus ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '13 − 8 = 5. Sam a 5 billes de plus.',
    hint: 'Calcule la différence : 13 − 8.',
    tags: ['ce1', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis la phrase.', 'Quel calcul faire ?', 'Calcule 13 − 8.'] },
    }),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-005',
    subject: 'mathematiques',
    title: 'Problème à deux étapes',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'multi-étapes',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Emma a 10 €. Elle achète un livre à 4 € et un crayon à 2 €. Combien lui reste-t-il ?',
    options: [
      { id: 'a', text: '3 €', isCorrect: false },
      { id: 'b', text: '4 €', isCorrect: true },
      { id: 'c', text: '6 €', isCorrect: false },
    ],
    correctAnswer: '4 €',
    explanation: 'Elle dépense 4 + 2 = 6 €. Il lui reste 10 − 6 = 4 €.',
    hint: 'Calcule d\'abord le total dépensé, puis soustrais.',
    tags: ['ce1', 'problemes', 'multi-etapes', 'monnaie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 4 + 2.', 'Calcule 10 − le total.'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-006',
    subject: 'mathematiques',
    title: 'Partage équitable',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'division simple',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: '12 bonbons partagés entre 4 enfants. Combien chacun en reçoit-il ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '12 ÷ 4 = 3 bonbons chacun.',
    hint: 'Partager, c\'est diviser. 12 ÷ 4 = ?',
    tags: ['ce1', 'problemes', 'division', 'partage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-007',
    subject: 'mathematiques',
    title: 'Achat et monnaie',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: 'Un pain au chocolat coûte 1 €. Tu en achètes 3. Combien dépenses-tu ?',
    options: [
      { id: 'a', text: '2 €', isCorrect: false },
      { id: 'b', text: '3 €', isCorrect: true },
      { id: 'c', text: '4 €', isCorrect: false },
    ],
    correctAnswer: '3 €',
    explanation: '1 € × 3 = 3 €.',
    hint: '1 + 1 + 1 = ?',
    tags: ['ce1', 'problemes', 'monnaie', 'multiplication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-008',
    subject: 'mathematiques',
    title: 'Distance parcourue',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'mesures en contexte',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: 'Paul marche 30 m puis encore 20 m. Quelle distance a-t-il parcourue au total ?',
    options: [
      { id: 'a', text: '40 m', isCorrect: false },
      { id: 'b', text: '50 m', isCorrect: true },
      { id: 'c', text: '60 m', isCorrect: false },
    ],
    correctAnswer: '50 m',
    explanation: '30 + 20 = 50 m.',
    hint: 'Additionne les deux distances.',
    tags: ['ce1', 'problemes', 'mesures', 'longueur', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-009',
    subject: 'mathematiques',
    title: 'Problème avec groupes',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: 'Il y a 4 groupes de 5 élèves. Combien y a-t-il d\'élèves en tout ?',
    options: [
      { id: 'a', text: '15', isCorrect: false },
      { id: 'b', text: '20', isCorrect: true },
      { id: 'c', text: '25', isCorrect: false },
    ],
    correctAnswer: '20',
    explanation: '4 × 5 = 20 élèves.',
    hint: '5 + 5 + 5 + 5 = ?',
    tags: ['ce1', 'problemes', 'multiplication', 'groupes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-010',
    subject: 'mathematiques',
    title: 'Durée d\'un trajet',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Lis et réponds.',
    prompt: 'Le bus part à 8h15 et arrive à 8h45. Combien de temps dure le trajet ?',
    options: [
      { id: 'a', text: '20 minutes', isCorrect: false },
      { id: 'b', text: '30 minutes', isCorrect: true },
      { id: 'c', text: '45 minutes', isCorrect: false },
    ],
    correctAnswer: '30 minutes',
    explanation: 'De 8h15 à 8h45 = 30 minutes.',
    hint: '45 − 15 = 30 minutes.',
    tags: ['ce1', 'problemes', 'durée', 'heure', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-011',
    subject: 'mathematiques',
    title: 'Partage de 18',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'partage',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: '18 bonbons partagés entre 3 enfants. Combien chacun en reçoit ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '18 ÷ 3 = 6.',
    hint: '3 × ? = 18.',
    tags: ['ce1', 'problemes', 'partage', 'division', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-012',
    subject: 'mathematiques',
    title: 'Prix total avec 4 objets',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Calcule le prix total.',
    prompt: '4 crayons à 2 € chacun. Combien cela coûte-t-il en tout ?',
    options: [
      { id: 'a', text: '6 €', isCorrect: false },
      { id: 'b', text: '8 €', isCorrect: true },
      { id: 'c', text: '10 €', isCorrect: false },
    ],
    correctAnswer: '8 €',
    explanation: '4 × 2 = 8 €.',
    hint: 'Multiplie le nombre de crayons par le prix unitaire.',
    tags: ['ce1', 'problemes', 'monnaie', 'multiplication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-013',
    subject: 'mathematiques',
    title: 'Reste de monnaie',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Calcule la monnaie.',
    prompt: 'J\'ai 10 €. J\'achète un livre à 7 €. Combien me reste-t-il ?',
    options: [
      { id: 'a', text: '2 €', isCorrect: false },
      { id: 'b', text: '3 €', isCorrect: true },
      { id: 'c', text: '4 €', isCorrect: false },
    ],
    correctAnswer: '3 €',
    explanation: '10 − 7 = 3 €.',
    hint: 'Soustrais le prix de ta somme initiale.',
    tags: ['ce1', 'problemes', 'monnaie', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-014',
    subject: 'mathematiques',
    title: 'Distance totale',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'Léa marche 300 m puis 450 m. Quelle distance a-t-elle parcourue en tout ?',
    options: [
      { id: 'a', text: '700 m', isCorrect: false },
      { id: 'b', text: '750 m', isCorrect: true },
      { id: 'c', text: '800 m', isCorrect: false },
    ],
    correctAnswer: '750 m',
    explanation: '300 + 450 = 750 m.',
    hint: 'Additionne les deux distances.',
    tags: ['ce1', 'problemes', 'distance', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-015',
    subject: 'mathematiques',
    title: 'Masse totale',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'masses',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'Un sac pèse 2 kg. On y met 500 g de fruits. Combien pèse le sac maintenant ?',
    options: [
      { id: 'a', text: '2 kg', isCorrect: false },
      { id: 'b', text: '2,5 kg', isCorrect: true },
      { id: 'c', text: '3 kg', isCorrect: false },
    ],
    correctAnswer: '2,5 kg',
    explanation: '2 kg + 500 g = 2 kg + 0,5 kg = 2,5 kg.',
    hint: '500 g = 0,5 kg.',
    tags: ['ce1', 'problemes', 'masse', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-016',
    subject: 'mathematiques',
    title: 'Problème multi-étapes',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'multi-étapes',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'Tom a 25 billes. Il en gagne 8 et en perd 5. Combien en a-t-il maintenant ?',
    options: [
      { id: 'a', text: '26', isCorrect: false },
      { id: 'b', text: '28', isCorrect: true },
      { id: 'c', text: '30', isCorrect: false },
    ],
    correctAnswer: '28',
    explanation: '25 + 8 = 33, puis 33 − 5 = 28.',
    hint: 'D\'abord ajoute, ensuite soustrait.',
    tags: ['ce1', 'problemes', 'multi-etapes', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-017',
    subject: 'mathematiques',
    title: 'Groupes de 4',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: '5 boîtes de 4 œufs. Combien d\'œufs en tout ?',
    options: [
      { id: 'a', text: '16', isCorrect: false },
      { id: 'b', text: '20', isCorrect: true },
      { id: 'c', text: '24', isCorrect: false },
    ],
    correctAnswer: '20',
    explanation: '5 × 4 = 20 œufs.',
    hint: 'Multiplie le nombre de boîtes par le nombre d\'œufs par boîte.',
    tags: ['ce1', 'problemes', 'multiplication', 'groupes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-ce1-problemes-018',
    subject: 'mathematiques',
    title: 'Différence de prix',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'Un jouet coûte 15 €. Un autre coûte 9 €. Quelle est leur différence de prix ?',
    options: [
      { id: 'a', text: '5 €', isCorrect: false },
      { id: 'b', text: '6 €', isCorrect: true },
      { id: 'c', text: '7 €', isCorrect: false },
    ],
    correctAnswer: '6 €',
    explanation: '15 − 9 = 6 €.',
    hint: 'Calcule 15 − 9.',
    tags: ['ce1', 'problemes', 'monnaie', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
];
