import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe1CalculExercises: MathExercise[] = [
  {
    id: 'ma-ce1-calcul-001',
    subject: 'mathematiques',
    title: 'Addition à 2 chiffres',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '14 + 5 = ?',
    options: [
      { id: 'a', text: '18', isCorrect: false },
      { id: 'b', text: '19', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '19',
    explanation: '14 + 5 = 19.',
    hint: 'Pars de 14 et ajoute 5.',
    tags: ['ce1', 'calcul', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-002',
    subject: 'mathematiques',
    title: 'Soustraction à 2 chiffres',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '18 − 6 = ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '11', isCorrect: false },
      { id: 'c', text: '12', isCorrect: true },
    ],
    correctAnswer: '12',
    explanation: '18 − 6 = 12.',
    hint: 'Pars de 18 et enlève 6.',
    tags: ['ce1', 'calcul', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-003',
    subject: 'mathematiques',
    title: 'Ajouter une dizaine',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '23 + 10 = ?',
    options: [
      { id: 'a', text: '32', isCorrect: false },
      { id: 'b', text: '33', isCorrect: true },
      { id: 'c', text: '34', isCorrect: false },
    ],
    correctAnswer: '33',
    explanation: '23 + 10 = 33. On ajoute 1 dizaine.',
    hint: "Ajouter 10, c'est ajouter une dizaine.",
    tags: ['ce1', 'calcul', 'addition', 'dizaines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-004',
    subject: 'mathematiques',
    title: 'Soustraction avec retenue',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '30 − 12 = ?',
    options: [
      { id: 'a', text: '17', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '19', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: '30 − 12 = 18.',
    hint: 'Pense à 30 = 28 + 2, puis enlève 12.',
    tags: ['ce1', 'calcul', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-005',
    subject: 'mathematiques',
    title: 'Addition répétée',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '5 + 5 + 5 = ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: '5 + 5 = 10, puis 10 + 5 = 15.',
    hint: "Calcule d'abord 5 + 5, puis ajoute encore 5.",
    tags: ['ce1', 'calcul', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-006',
    subject: 'mathematiques',
    title: 'Addition avec retenue',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'addition avec retenue',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '47 + 6 = ?',
    options: [
      { id: 'a', text: '51', isCorrect: false },
      { id: 'b', text: '53', isCorrect: true },
      { id: 'c', text: '57', isCorrect: false },
    ],
    correctAnswer: '53',
    explanation: '47 + 6 : 7 + 6 = 13, on pose 3 et on retient 1. 4 + 1 = 5. Résultat : 53.',
    hint: 'Commence par les unités : 7 + 6 = ?',
    tags: ['ce1', 'calcul', 'addition', 'retenue', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { extraHint: '47 + 3 = 50, puis 50 + 3 = 53.' },
      progressif: { splitSteps: ['Calcule 7 + 6.', 'Si tu obtiens 13, pose 3 et retiens 1.', 'Calcule 4 + 1 pour les dizaines.'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-007',
    subject: 'mathematiques',
    title: 'Ajouter 10',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'addition dizaines',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '45 + 10 = ?',
    options: [
      { id: 'a', text: '54', isCorrect: false },
      { id: 'b', text: '55', isCorrect: true },
      { id: 'c', text: '56', isCorrect: false },
    ],
    correctAnswer: '55',
    explanation: "45 + 10 = 55. On ajoute une dizaine : 4 dizaines deviennent 5.",
    hint: "Ajouter 10, c'est juste changer le chiffre des dizaines.",
    tags: ['ce1', 'calcul', 'addition', 'dizaines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-008',
    subject: 'mathematiques',
    title: 'Soustraction simples',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '25 − 10 = ?',
    options: [
      { id: 'a', text: '14', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: '16', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: '25 − 10 = 15. On enlève une dizaine.',
    hint: 'Soustraire 10, c\'est enlever une dizaine.',
    tags: ['ce1', 'calcul', 'soustraction', 'dizaines', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-009',
    subject: 'mathematiques',
    title: 'Addition à 2 chiffres sans retenue',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '32 + 15 = ?',
    options: [
      { id: 'a', text: '46', isCorrect: false },
      { id: 'b', text: '47', isCorrect: true },
      { id: 'c', text: '48', isCorrect: false },
    ],
    correctAnswer: '47',
    explanation: '32 + 15 : unités 2 + 5 = 7, dizaines 3 + 1 = 4 → 47.',
    hint: 'Additionne les unités puis les dizaines séparément.',
    tags: ['ce1', 'calcul', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-010',
    subject: 'mathematiques',
    title: 'Soustraction sans retenue',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '57 − 23 = ?',
    options: [
      { id: 'a', text: '33', isCorrect: false },
      { id: 'b', text: '34', isCorrect: true },
      { id: 'c', text: '35', isCorrect: false },
    ],
    correctAnswer: '34',
    explanation: '57 − 23 : unités 7 − 3 = 4, dizaines 5 − 2 = 3 → 34.',
    hint: 'Soustrais les unités puis les dizaines.',
    tags: ['ce1', 'calcul', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-011',
    subject: 'mathematiques',
    title: 'Doubles jusqu\'à 10',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'doubles',
    format: 'qcm',
    instructions: 'Calcule le double.',
    prompt: 'Quel est le double de 7 ?',
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '14', isCorrect: true },
      { id: 'c', text: '16', isCorrect: false },
    ],
    correctAnswer: '14',
    explanation: 'Le double de 7 = 7 + 7 = 14.',
    hint: 'Ajoute 7 à lui-même.',
    tags: ['ce1', 'calcul', 'doubles', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-012',
    subject: 'mathematiques',
    title: 'Moitié',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'moitié',
    format: 'qcm',
    instructions: 'Calcule la moitié.',
    prompt: 'Quelle est la moitié de 16 ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: 'La moitié de 16 = 16 ÷ 2 = 8.',
    hint: '16 = 8 + 8. La moitié, c\'est diviser par 2.',
    tags: ['ce1', 'calcul', 'moitie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-013',
    subject: 'mathematiques',
    title: 'Multiplication par 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '4 × 2 = ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: '4 × 2 = 4 + 4 = 8.',
    hint: '4 × 2, c\'est le double de 4.',
    tags: ['ce1', 'calcul', 'multiplication', 'table_2', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-014',
    subject: 'mathematiques',
    title: 'Multiplication par 5',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '3 × 5 = ?',
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: '3 × 5 = 5 + 5 + 5 = 15.',
    hint: 'Compte 5, 10, 15.',
    tags: ['ce1', 'calcul', 'multiplication', 'table_5', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-015',
    subject: 'mathematiques',
    title: 'Complément à 50',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'complément',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '50 − 17 = ?',
    options: [
      { id: 'a', text: '32', isCorrect: false },
      { id: 'b', text: '33', isCorrect: true },
      { id: 'c', text: '34', isCorrect: false },
    ],
    correctAnswer: '33',
    explanation: '50 − 17 = 33.',
    hint: '17 + ? = 50. Essaie 17 + 30 = 47, puis 47 + 3 = 50.',
    tags: ['ce1', 'calcul', 'soustraction', 'complement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-016',
    subject: 'mathematiques',
    title: '35 + 28',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '35 + 28 = ?',
    options: [
      { id: 'a', text: '61', isCorrect: false },
      { id: 'b', text: '63', isCorrect: true },
      { id: 'c', text: '65', isCorrect: false },
    ],
    correctAnswer: '63',
    explanation: '35 + 28 = 35 + 25 + 3 = 60 + 3 = 63.',
    hint: '35 + 20 = 55, puis 55 + 8 = 63.',
    tags: ['ce1', 'calcul', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-017',
    subject: 'mathematiques',
    title: '72 − 45',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '72 − 45 = ?',
    options: [
      { id: 'a', text: '25', isCorrect: false },
      { id: 'b', text: '27', isCorrect: true },
      { id: 'c', text: '29', isCorrect: false },
    ],
    correctAnswer: '27',
    explanation: '72 − 45 = 27.',
    hint: '72 − 40 = 32, puis 32 − 5 = 27.',
    tags: ['ce1', 'calcul', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-018',
    subject: 'mathematiques',
    title: 'Table de 3 (×3)',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '6 × 3 = ?',
    options: [
      { id: 'a', text: '15', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '21', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: '6 × 3 = 18.',
    hint: '3, 6, 9, 12, 15, 18… On compte de 3 en 3.',
    tags: ['ce1', 'calcul', 'multiplication', 'table-3', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-019',
    subject: 'mathematiques',
    title: 'Table de 4 (×4)',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '7 × 4 = ?',
    options: [
      { id: 'a', text: '24', isCorrect: false },
      { id: 'b', text: '28', isCorrect: true },
      { id: 'c', text: '32', isCorrect: false },
    ],
    correctAnswer: '28',
    explanation: '7 × 4 = 28.',
    hint: '4, 8, 12, 16, 20, 24, 28… On compte de 4 en 4.',
    tags: ['ce1', 'calcul', 'multiplication', 'table-4', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-020',
    subject: 'mathematiques',
    title: 'Division simple',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'calcul',
    subskill: 'division',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '24 ÷ 4 = ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '24 ÷ 4 = 6 car 6 × 4 = 24.',
    hint: 'Cherche combien de fois 4 entre dans 24.',
    tags: ['ce1', 'calcul', 'division', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-021',
    subject: 'mathematiques',
    title: 'Calcul mental : × 10',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Calcule rapidement.',
    prompt: '8 × 10 = ?',
    options: [
      { id: 'a', text: '18', isCorrect: false },
      { id: 'b', text: '80', isCorrect: true },
      { id: 'c', text: '800', isCorrect: false },
    ],
    correctAnswer: '80',
    explanation: '8 × 10 = 80. Multiplier par 10 ajoute un zéro.',
    hint: 'Multiplier par 10 : on ajoute un 0 à droite.',
    tags: ['ce1', 'calcul', 'multiplication', 'dix', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-ce1-calcul-022',
    subject: 'mathematiques',
    title: '100 − 38',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'calcul',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '100 − 38 = ?',
    options: [
      { id: 'a', text: '60', isCorrect: false },
      { id: 'b', text: '62', isCorrect: true },
      { id: 'c', text: '64', isCorrect: false },
    ],
    correctAnswer: '62',
    explanation: '100 − 38 = 62.',
    hint: '100 − 40 = 60, puis + 2 = 62.',
    tags: ['ce1', 'calcul', 'soustraction', 'centaine', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
];
