import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe1GeometrieExercises: MathExercise[] = [
  {
    id: 'ma-ce1-geometrie-001',
    subject: 'mathematiques',
    title: 'Côtés du rectangle',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'reconnaissance de formes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de côtés a un rectangle ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '5', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Un rectangle a 4 côtés : 2 longs et 2 courts.',
    hint: 'Pense à une porte ou une feuille de cahier.',
    tags: ['ce1', 'geometrie', 'rectangle', 'côtés', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-002',
    subject: 'mathematiques',
    title: 'Carré ou rectangle ?',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'reconnaissance de formes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quelle est la différence entre un carré et un rectangle ?',
    options: [
      { id: 'a', text: 'Le carré a plus de côtés', isCorrect: false },
      { id: 'b', text: 'Le carré a 4 côtés égaux, le rectangle a 2 côtés longs et 2 courts', isCorrect: true },
      { id: 'c', text: 'Le rectangle n\'a pas de coins', isCorrect: false },
    ],
    correctAnswer: 'Le carré a 4 côtés égaux, le rectangle a 2 côtés longs et 2 courts',
    explanation: 'Le carré a tous ses côtés de la même longueur. Dans un rectangle, les côtés opposés sont égaux mais pas tous.',
    hint: 'Un carré est un rectangle particulier dont tous les côtés sont égaux.',
    tags: ['ce1', 'geometrie', 'carré', 'rectangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-003',
    subject: 'mathematiques',
    title: 'Angle droit',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'angles',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien d\'angles droits a un carré ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: false },
      { id: 'c', text: '4', isCorrect: true },
    ],
    correctAnswer: '4',
    explanation: 'Un carré a 4 coins qui sont tous des angles droits (comme le coin d\'une feuille).',
    hint: 'Compte les coins du carré.',
    tags: ['ce1', 'geometrie', 'angle_droit', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-004',
    subject: 'mathematiques',
    title: 'Périmètre du carré',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Calcule le périmètre.',
    prompt: 'Un carré a des côtés de 4 cm. Quel est son périmètre ?',
    options: [
      { id: 'a', text: '12 cm', isCorrect: false },
      { id: 'b', text: '16 cm', isCorrect: true },
      { id: 'c', text: '20 cm', isCorrect: false },
    ],
    correctAnswer: '16 cm',
    explanation: 'Périmètre du carré = 4 × 4 = 16 cm.',
    hint: 'Additionne les 4 côtés : 4 + 4 + 4 + 4.',
    tags: ['ce1', 'geometrie', 'périmètre', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-005',
    subject: 'mathematiques',
    title: 'Droite ou courbe ?',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'lignes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Le côté d\'un carré est-il une ligne droite ou courbe ?',
    options: [
      { id: 'a', text: 'Courbe', isCorrect: false },
      { id: 'b', text: 'Droite', isCorrect: true },
      { id: 'c', text: 'Les deux', isCorrect: false },
    ],
    correctAnswer: 'Droite',
    explanation: 'Les côtés d\'un carré sont des segments droits.',
    hint: 'Trace un côté du carré : est-il droit ou arrondi ?',
    tags: ['ce1', 'geometrie', 'lignes', 'droite', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-006',
    subject: 'mathematiques',
    title: 'Symétrie axiale',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'symétrie',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un rectangle a-t-il un axe de symétrie ?',
    options: [
      { id: 'a', text: 'Non, jamais', isCorrect: false },
      { id: 'b', text: 'Oui, il en a', isCorrect: true },
      { id: 'c', text: 'Seulement s\'il est carré', isCorrect: false },
    ],
    correctAnswer: 'Oui, il en a',
    explanation: 'Un rectangle a 2 axes de symétrie : une ligne horizontale et une ligne verticale en son milieu.',
    hint: 'Imagine plier le rectangle en deux : les deux moitiés se superposent.',
    tags: ['ce1', 'geometrie', 'symétrie', 'rectangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-007',
    subject: 'mathematiques',
    title: 'Identifier la forme',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'reconnaissance de formes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Une forme a 3 côtés et 3 angles. Comment s\'appelle-t-elle ?',
    options: [
      { id: 'a', text: 'Carré', isCorrect: false },
      { id: 'b', text: 'Triangle', isCorrect: true },
      { id: 'c', text: 'Rectangle', isCorrect: false },
    ],
    correctAnswer: 'Triangle',
    explanation: 'Le triangle a exactement 3 côtés et 3 angles.',
    hint: '"Tri" signifie 3.',
    tags: ['ce1', 'geometrie', 'triangle', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-008',
    subject: 'mathematiques',
    title: 'Repérage sur quadrillage',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'repérage',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Sur un quadrillage, on avance de 2 cases vers la droite depuis la case (1, 1). Où arrive-t-on ?',
    options: [
      { id: 'a', text: '(1, 3)', isCorrect: false },
      { id: 'b', text: '(3, 1)', isCorrect: true },
      { id: 'c', text: '(2, 2)', isCorrect: false },
    ],
    correctAnswer: '(3, 1)',
    explanation: 'On part de (1,1). Se déplacer vers la droite augmente le premier chiffre. 1 + 2 = 3. On arrive en (3, 1).',
    hint: 'Vers la droite = le premier chiffre augmente.',
    tags: ['ce1', 'geometrie', 'quadrillage', 'repérage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-009',
    subject: 'mathematiques',
    title: 'Côtés du rectangle',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'figures planes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un rectangle a des côtés opposés ___ .',
    options: [
      { id: 'a', text: 'tous différents', isCorrect: false },
      { id: 'b', text: 'égaux', isCorrect: true },
      { id: 'c', text: 'perpendiculaires', isCorrect: false },
    ],
    correctAnswer: 'égaux',
    explanation: 'Dans un rectangle, les côtés opposés sont égaux deux à deux.',
    hint: 'Mesure les côtés d\'un rectangle : les deux longs sont pareils, les deux courts aussi.',
    tags: ['ce1', 'geometrie', 'rectangle', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-010',
    subject: 'mathematiques',
    title: 'Périmètre d\'un carré de 4 cm',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Calcule le périmètre.',
    prompt: 'Un carré a un côté de 4 cm. Quel est son périmètre ?',
    options: [
      { id: 'a', text: '12 cm', isCorrect: false },
      { id: 'b', text: '16 cm', isCorrect: true },
      { id: 'c', text: '20 cm', isCorrect: false },
    ],
    correctAnswer: '16 cm',
    explanation: 'Périmètre du carré = 4 × côté = 4 × 4 = 16 cm.',
    hint: 'Le périmètre = somme de tous les côtés.',
    tags: ['ce1', 'geometrie', 'périmètre', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-011',
    subject: 'mathematiques',
    title: 'Axe de symétrie',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'symétrie',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un carré a combien d\'axes de symétrie ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Le carré a 4 axes de symétrie : 2 médiatrices et 2 diagonales.',
    hint: 'Essaie de plier le carré en 2 de toutes les façons possibles.',
    tags: ['ce1', 'geometrie', 'symétrie', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-012',
    subject: 'mathematiques',
    title: 'Ligne droite ou courbe ?',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'lignes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Le cercle est tracé avec une ligne ___ .',
    options: [
      { id: 'a', text: 'droite', isCorrect: false },
      { id: 'b', text: 'courbe', isCorrect: true },
      { id: 'c', text: 'brisée', isCorrect: false },
    ],
    correctAnswer: 'courbe',
    explanation: 'Le cercle est tracé avec une ligne courbe fermée.',
    hint: 'Une ligne courbe n\'est pas droite.',
    tags: ['ce1', 'geometrie', 'ligne', 'cercle', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-013',
    subject: 'mathematiques',
    title: 'Droites perpendiculaires',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'geometrie',
    subskill: 'perpendiculaires',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Deux droites perpendiculaires forment un angle de ___ .',
    options: [
      { id: 'a', text: '45°', isCorrect: false },
      { id: 'b', text: '90°', isCorrect: true },
      { id: 'c', text: '180°', isCorrect: false },
    ],
    correctAnswer: '90°',
    explanation: 'Des droites perpendiculaires forment un angle droit de 90°.',
    hint: 'L\'angle droit mesure 90 degrés.',
    tags: ['ce1', 'geometrie', 'perpendiculaire', 'angle', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-014',
    subject: 'mathematiques',
    title: 'Triangle rectangle',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'geometrie',
    subskill: 'triangles',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un triangle rectangle possède combien d\'angles droits ?',
    options: [
      { id: 'a', text: '0', isCorrect: false },
      { id: 'b', text: '1', isCorrect: true },
      { id: 'c', text: '2', isCorrect: false },
    ],
    correctAnswer: '1',
    explanation: 'Un triangle rectangle possède exactement 1 angle droit.',
    hint: 'Un angle droit = angle de 90°.',
    tags: ['ce1', 'geometrie', 'triangle', 'angle-droit', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-015',
    subject: 'mathematiques',
    title: 'Périmètre d\'un rectangle',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Calcule le périmètre.',
    prompt: 'Un rectangle fait 6 cm de long et 3 cm de large. Quel est son périmètre ?',
    options: [
      { id: 'a', text: '15 cm', isCorrect: false },
      { id: 'b', text: '18 cm', isCorrect: true },
      { id: 'c', text: '20 cm', isCorrect: false },
    ],
    correctAnswer: '18 cm',
    explanation: 'Périmètre = 2 × (6 + 3) = 2 × 9 = 18 cm.',
    hint: 'Périmètre = 2 × (longueur + largeur).',
    tags: ['ce1', 'geometrie', 'périmètre', 'rectangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-ce1-geometrie-016',
    subject: 'mathematiques',
    title: 'Solide à 6 faces',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'solides',
    format: 'qcm',
    instructions: 'Trouve le bon solide.',
    prompt: 'Quel solide a 6 faces rectangulaires ?',
    options: [
      { id: 'a', text: 'La pyramide', isCorrect: false },
      { id: 'b', text: 'Le pavé droit', isCorrect: true },
      { id: 'c', text: 'La sphère', isCorrect: false },
    ],
    correctAnswer: 'Le pavé droit',
    explanation: 'Le pavé droit (ou rectangulaire) a 6 faces, toutes rectangulaires.',
    hint: 'Pense à une boîte à chaussures.',
    tags: ['ce1', 'geometrie', 'solide', 'pavé', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
];
