import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe1GrammaireExercises: FrenchExercise[] = [
  {
    id: 'fr-ce1-grammaire-101',
    subject: 'francais',
    title: 'Trouver le sujet',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'identifier le sujet',
    format: 'qcm',
    instructions: 'Choisis celui qui fait l’action.',
    prompt: 'Les enfants chantent.',
    options: [
      { id: 'a', text: 'Les enfants', isCorrect: true },
      { id: 'b', text: 'chantent', isCorrect: false }
    ],
    correctAnswer: 'Les enfants',
    explanation: 'Le sujet est celui qui fait l’action.',
    hint: 'Qui chante ?',
    tags: ['ce1','grammaire','sujet','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-102',
    subject: 'francais',
    title: 'Trouver le verbe',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'identifier le verbe',
    format: 'qcm',
    instructions: 'Choisis le verbe dans la phrase.',
    prompt: 'Lina chante dans la cour.',
    options: [
      { id: 'a', text: 'Lina', isCorrect: false },
      { id: 'b', text: 'chante', isCorrect: true },
      { id: 'c', text: 'cour', isCorrect: false }
    ],
    correctAnswer: 'chante',
    explanation: 'Le verbe dit ce que fait Lina.',
    hint: 'Cherche l’action.',
    tags: ['ce1','grammaire','verbe','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-103',
    subject: 'francais',
    title: 'Nom ou verbe',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'nature des mots',
    format: 'qcm',
    instructions: 'Choisis le verbe.',
    prompt: 'Le train arrive vite.',
    options: [
      { id: 'a', text: 'train', isCorrect: false },
      { id: 'b', text: 'arrive', isCorrect: true },
      { id: 'c', text: 'vite', isCorrect: false }
    ],
    correctAnswer: 'arrive',
    explanation: 'Arrive est le verbe de la phrase.',
    hint: 'Cherche ce qui se passe.',
    tags: ['ce1','grammaire','verbe','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-104',
    subject: 'francais',
    title: 'Trouver le déterminant',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'determinant',
    format: 'qcm',
    instructions: 'Choisis le déterminant.',
    prompt: 'La tortue avance.',
    options: [
      { id: 'a', text: 'La', isCorrect: true },
      { id: 'b', text: 'tortue', isCorrect: false },
      { id: 'c', text: 'avance', isCorrect: false }
    ],
    correctAnswer: 'La',
    explanation: 'Le déterminant est placé devant le nom.',
    hint: 'Cherche le petit mot devant le nom.',
    tags: ['ce1','grammaire','determinant','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-105',
    subject: 'francais',
    title: 'Singulier ou pluriel',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'singulier-pluriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'des pommes',
    options: [
      { id: 'a', text: 'Singulier', isCorrect: false },
      { id: 'b', text: 'Pluriel', isCorrect: true }
    ],
    correctAnswer: 'Pluriel',
    explanation: 'Des pommes veut dire plusieurs pommes.',
    hint: 'Une ou plusieurs ?',
    tags: ['ce1','grammaire','singulier-pluriel','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-106',
    subject: 'francais',
    title: 'Masculin ou féminin',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'masculin-feminin',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'robe',
    options: [
      { id: 'a', text: 'Masculin', isCorrect: false },
      { id: 'b', text: 'Féminin', isCorrect: true }
    ],
    correctAnswer: 'Féminin',
    explanation: 'On dit une robe.',
    hint: 'Essaie avec un ou une.',
    tags: ['ce1','grammaire','masculin-feminin','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-107',
    subject: 'francais',
    title: 'Repérer le sujet 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'identifier le sujet',
    format: 'qcm',
    instructions: 'Choisis le sujet.',
    prompt: 'Le lapin mange une carotte.',
    options: [
      { id: 'a', text: 'Le lapin', isCorrect: true },
      { id: 'b', text: 'mange', isCorrect: false },
      { id: 'c', text: 'une carotte', isCorrect: false }
    ],
    correctAnswer: 'Le lapin',
    explanation: 'Le lapin fait l’action de manger.',
    hint: 'Qui mange ?',
    tags: ['ce1','grammaire','sujet','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-108',
    subject: 'francais',
    title: 'Repérer le verbe 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'identifier le verbe',
    format: 'qcm',
    instructions: 'Choisis le verbe.',
    prompt: 'Papa cuisine ce soir.',
    options: [
      { id: 'a', text: 'Papa', isCorrect: false },
      { id: 'b', text: 'cuisine', isCorrect: true },
      { id: 'c', text: 'soir', isCorrect: false }
    ],
    correctAnswer: 'cuisine',
    explanation: 'Cuisine est l’action.',
    hint: 'Que fait papa ?',
    tags: ['ce1','grammaire','verbe','famille','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-109',
    subject: 'francais',
    title: 'Nom ou verbe 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'nature des mots',
    format: 'qcm',
    instructions: 'Dans la phrase « Mila danse », le mot danse est :',
    prompt: 'Mila danse.',
    options: [
      { id: 'a', text: 'un nom', isCorrect: false },
      { id: 'b', text: 'un verbe', isCorrect: true }
    ],
    correctAnswer: 'un verbe',
    explanation: 'Danse dit ce que fait Mila.',
    hint: 'Est-ce une action ?',
    tags: ['ce1','grammaire','nature-des-mots','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-110',
    subject: 'francais',
    title: 'Trouver le nom',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'identifier le nom',
    format: 'qcm',
    instructions: 'Choisis le nom.',
    prompt: 'Le camion roule.',
    options: [
      { id: 'a', text: 'camion', isCorrect: true },
      { id: 'b', text: 'roule', isCorrect: false }
    ],
    correctAnswer: 'camion',
    explanation: 'Camion est un nom.',
    hint: 'Le nom désigne une chose ou un être vivant.',
    tags: ['ce1','grammaire','nom','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-111',
    subject: 'francais',
    title: 'Déterminant 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'determinant',
    format: 'qcm',
    instructions: 'Choisis le déterminant.',
    prompt: 'Les oiseaux chantent.',
    options: [
      { id: 'a', text: 'Les', isCorrect: true },
      { id: 'b', text: 'oiseaux', isCorrect: false },
      { id: 'c', text: 'chantent', isCorrect: false }
    ],
    correctAnswer: 'Les',
    explanation: 'Les accompagne le nom oiseaux.',
    hint: 'Cherche le petit mot avant le nom.',
    tags: ['ce1','grammaire','determinant','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-112',
    subject: 'francais',
    title: 'Singulier ou pluriel 2',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'singulier-pluriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'un cahier',
    options: [
      { id: 'a', text: 'Singulier', isCorrect: true },
      { id: 'b', text: 'Pluriel', isCorrect: false }
    ],
    correctAnswer: 'Singulier',
    explanation: 'Un cahier veut dire un seul cahier.',
    hint: 'Y en a-t-il un seul ?',
    tags: ['ce1','grammaire','singulier-pluriel','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-113',
    subject: 'francais',
    title: 'Masculin ou féminin 2',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'masculin-feminin',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'ballon',
    options: [
      { id: 'a', text: 'Masculin', isCorrect: true },
      { id: 'b', text: 'Féminin', isCorrect: false }
    ],
    correctAnswer: 'Masculin',
    explanation: 'On dit un ballon.',
    hint: 'Essaie avec un ou une.',
    tags: ['ce1','grammaire','masculin-feminin','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-114',
    subject: 'francais',
    title: 'Trouver le complément déplacé ? non',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'identifier le sujet',
    format: 'qcm',
    instructions: 'Choisis celui qui fait l’action.',
    prompt: 'Le maître explique la leçon.',
    options: [
      { id: 'a', text: 'Le maître', isCorrect: true },
      { id: 'b', text: 'explique', isCorrect: false },
      { id: 'c', text: 'la leçon', isCorrect: false }
    ],
    correctAnswer: 'Le maître',
    explanation: 'Le maître fait l’action d’expliquer.',
    hint: 'Qui explique ?',
    tags: ['ce1','grammaire','sujet','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-115',
    subject: 'francais',
    title: 'Verbe avec phrase simple',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'identifier le verbe',
    format: 'qcm',
    instructions: 'Choisis le verbe.',
    prompt: 'Les vagues bougent vite.',
    options: [
      { id: 'a', text: 'vagues', isCorrect: false },
      { id: 'b', text: 'bougent', isCorrect: true },
      { id: 'c', text: 'vite', isCorrect: false }
    ],
    correctAnswer: 'bougent',
    explanation: 'Bougent exprime l’action.',
    hint: 'Cherche ce qui se passe.',
    tags: ['ce1','grammaire','verbe','nature','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-116',
    subject: 'francais',
    title: 'Nom dans la phrase',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'identifier le nom',
    format: 'qcm',
    instructions: 'Choisis le nom.',
    prompt: 'La cloche sonne.',
    options: [
      { id: 'a', text: 'cloche', isCorrect: true },
      { id: 'b', text: 'sonne', isCorrect: false }
    ],
    correctAnswer: 'cloche',
    explanation: 'Cloche est le nom.',
    hint: 'Quel mot désigne une chose ?',
    tags: ['ce1','grammaire','nom','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-117',
    subject: 'francais',
    title: 'Nature des mots 3',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'nature des mots',
    format: 'qcm',
    instructions: 'Identifie la nature du mot.',
    prompt: 'Dans « Le chien dort », le mot « chien » est :',
    options: [
      { id: 'a', text: 'un nom', isCorrect: true },
      { id: 'b', text: 'un verbe', isCorrect: false }
    ],
    correctAnswer: 'un nom',
    explanation: 'Chien désigne un animal, c’est un nom.',
    hint: 'Le mot désigne-t-il une chose ou une action ?',
    tags: ['ce1','grammaire','nature-des-mots','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

    {
    id: 'fr-ce1-grammaire-118',
    subject: 'francais',
    title: 'Déterminant 3',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'determinant',
    format: 'qcm',
    instructions: 'Choisis le déterminant.',
    prompt: 'Une étoile brille.',
    options: [
      { id: 'a', text: 'Une', isCorrect: true },
      { id: 'b', text: 'étoile', isCorrect: false },
      { id: 'c', text: 'brille', isCorrect: false }
    ],
    correctAnswer: 'Une',
    explanation: 'Une accompagne le nom étoile.',
    hint: 'Cherche le petit mot placé avant le nom.',
    tags: ['ce1','grammaire','determinant','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },
];
