import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe1LectureExercises: FrenchExercise[] = [
  {
    id: 'fr-ce1-lecture-101',
    subject: 'francais',
    title: 'Comprendre une cause',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis la phrase puis réponds.',
    prompt: 'Tom ferme la fenêtre parce qu’il a froid. Pourquoi Tom ferme-t-il la fenêtre ?',
    options: [
      { id: 'a', text: 'Parce qu’il a froid', isCorrect: true },
      { id: 'b', text: 'Parce qu’il veut courir', isCorrect: false },
      { id: 'c', text: 'Parce qu’il dort', isCorrect: false }
    ],
    correctAnswer: 'Parce qu’il a froid',
    explanation: 'La raison est donnée dans la phrase.',
    hint: 'Relis la fin de la phrase.',
    tags: ['ce1','lecture','comprehension','cause','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-102',
    subject: 'francais',
    title: 'Trouver le lieu',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Lina pose son sac sur la chaise. Où pose-t-elle son sac ?',
    options: [
      { id: 'a', text: 'Sur la chaise', isCorrect: true },
      { id: 'b', text: 'Sous la pluie', isCorrect: false },
      { id: 'c', text: 'Dans le jardin', isCorrect: false }
    ],
    correctAnswer: 'Sur la chaise',
    explanation: 'La phrase dit où se trouve le sac.',
    hint: 'Cherche le lieu.',
    tags: ['ce1','lecture','comprehension','lieu','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-103',
    subject: 'francais',
    title: 'Identifier le personnage',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du sujet',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le boulanger prépare le pain. Qui prépare le pain ?',
    options: [
      { id: 'a', text: 'Le boulanger', isCorrect: true },
      { id: 'b', text: 'Le pain', isCorrect: false },
      { id: 'c', text: 'Le four', isCorrect: false }
    ],
    correctAnswer: 'Le boulanger',
    explanation: 'C’est le boulanger qui fait l’action.',
    hint: 'Qui fait l’action ?',
    tags: ['ce1','lecture','sujet','metier','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-104',
    subject: 'francais',
    title: 'Comprendre une action',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Mila arrose les fleurs. Que fait Mila ?',
    options: [
      { id: 'a', text: 'Elle arrose les fleurs', isCorrect: true },
      { id: 'b', text: 'Elle cueille des pommes', isCorrect: false },
      { id: 'c', text: 'Elle ferme la porte', isCorrect: false }
    ],
    correctAnswer: 'Elle arrose les fleurs',
    explanation: 'La phrase donne l’action exacte.',
    hint: 'Cherche le verbe.',
    tags: ['ce1','lecture','action','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-105',
    subject: 'francais',
    title: 'Repérer un objet',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Noé range ses feutres dans sa trousse. Que range Noé ?',
    options: [
      { id: 'a', text: 'Ses feutres', isCorrect: true },
      { id: 'b', text: 'Ses chaussures', isCorrect: false },
      { id: 'c', text: 'Son goûter', isCorrect: false }
    ],
    correctAnswer: 'Ses feutres',
    explanation: 'La phrase dit ce que Noé range.',
    hint: 'Relis le milieu de la phrase.',
    tags: ['ce1','lecture','objet','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-106',
    subject: 'francais',
    title: 'Comprendre une information simple',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le chat se cache sous le lit pendant l’orage. Où se cache le chat ?',
    options: [
      { id: 'a', text: 'Sous le lit', isCorrect: true },
      { id: 'b', text: 'Dans la forêt', isCorrect: false },
      { id: 'c', text: 'Sur le toit', isCorrect: false }
    ],
    correctAnswer: 'Sous le lit',
    explanation: 'Le lieu est écrit dans la phrase.',
    hint: 'Cherche après le verbe.',
    tags: ['ce1','lecture','lieu','maison','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-107',
    subject: 'francais',
    title: 'Reformuler une phrase simple',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'association de sens',
    format: 'qcm',
    instructions: 'Choisis la phrase qui dit la même chose.',
    prompt: 'La fillette lit un livre dans sa chambre.',
    options: [
      { id: 'a', text: 'La fille lit une histoire dans sa chambre', isCorrect: true },
      { id: 'b', text: 'La fillette dort dans le salon', isCorrect: false },
      { id: 'c', text: 'Le livre lit la fillette dans le jardin', isCorrect: false }
    ],
    correctAnswer: 'La fille lit une histoire dans sa chambre',
    explanation: 'Fillette = fille, livre = histoire : les deux phrases ont le même sens.',
    hint: 'Cherche une phrase qui parle de la même personne, de la même action et du même endroit.',
    tags: ['ce1','lecture','association','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-108',
    subject: 'francais',
    title: 'Répondre à pourquoi',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Léo met ses bottes car il pleut. Pourquoi met-il ses bottes ?',
    options: [
      { id: 'a', text: 'Car il pleut', isCorrect: true },
      { id: 'b', text: 'Car il nage', isCorrect: false },
      { id: 'c', text: 'Car il a sommeil', isCorrect: false }
    ],
    correctAnswer: 'Car il pleut',
    explanation: 'La réponse est donnée directement.',
    hint: 'Cherche le mot car.',
    tags: ['ce1','lecture','cause','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-109',
    subject: 'francais',
    title: 'Repérer une information de temps',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Ce matin, Zoé arrive en avance à l’école. Quand Zoé arrive-t-elle à l’école ?',
    options: [
      { id: 'a', text: 'Ce matin', isCorrect: true },
      { id: 'b', text: 'Cette nuit', isCorrect: false },
      { id: 'c', text: 'Demain soir', isCorrect: false }
    ],
    correctAnswer: 'Ce matin',
    explanation: 'L’indication de temps est au début de la phrase.',
    hint: 'Regarde le début.',
    tags: ['ce1','lecture','temps','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-110',
    subject: 'francais',
    title: 'Comprendre une consigne simple',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Papa coupe le gâteau pour le dessert. Que coupe papa ?',
    options: [
      { id: 'a', text: 'Le gâteau', isCorrect: true },
      { id: 'b', text: 'La fenêtre', isCorrect: false },
      { id: 'c', text: 'Le manteau', isCorrect: false }
    ],
    correctAnswer: 'Le gâteau',
    explanation: 'L’objet coupé est dans la phrase.',
    hint: 'Cherche ce que papa coupe.',
    tags: ['ce1','lecture','objet','famille','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-111',
    subject: 'francais',
    title: 'Identifier le bon lieu',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Les enfants jouent dans la cour après la classe. Où jouent les enfants ?',
    options: [
      { id: 'a', text: 'Dans la cour', isCorrect: true },
      { id: 'b', text: 'Dans le grenier', isCorrect: false },
      { id: 'c', text: 'Dans l’étang', isCorrect: false }
    ],
    correctAnswer: 'Dans la cour',
    explanation: 'Le lieu est clairement écrit.',
    hint: 'Relis la fin.',
    tags: ['ce1','lecture','lieu','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-112',
    subject: 'francais',
    title: 'Petit raisonnement explicite',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Emma prend un parapluie avant de sortir. Que va-t-elle sûrement rencontrer ?',
    options: [
      { id: 'a', text: 'La pluie', isCorrect: true },
      { id: 'b', text: 'Le sable', isCorrect: false },
      { id: 'c', text: 'Le feu', isCorrect: false }
    ],
    correctAnswer: 'La pluie',
    explanation: 'On prend souvent un parapluie quand il pleut.',
    hint: 'Pense à l’objet.',
    tags: ['ce1','lecture','inference-simple','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-113',
    subject: 'francais',
    title: 'Repérer le sujet',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du sujet',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le voisin repeint sa porte. Qui repeint la porte ?',
    options: [
      { id: 'a', text: 'Le voisin', isCorrect: true },
      { id: 'b', text: 'La porte', isCorrect: false },
      { id: 'c', text: 'La peinture', isCorrect: false }
    ],
    correctAnswer: 'Le voisin',
    explanation: 'Le voisin fait l’action.',
    hint: 'Qui agit ?',
    tags: ['ce1','lecture','sujet','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-114',
    subject: 'francais',
    title: 'Repérer l’objet de l’action',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Lina nettoie son vélo avec une éponge. Que nettoie Lina ?',
    options: [
      { id: 'a', text: 'Son vélo', isCorrect: true },
      { id: 'b', text: 'Son pull', isCorrect: false },
      { id: 'c', text: 'Son cahier', isCorrect: false }
    ],
    correctAnswer: 'Son vélo',
    explanation: 'La phrase dit ce qu’elle nettoie.',
    hint: 'Cherche l’objet.',
    tags: ['ce1','lecture','objet','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-115',
    subject: 'francais',
    title: 'Phrase équivalente',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'association de sens',
    format: 'qcm',
    instructions: 'Choisis la phrase qui correspond.',
    prompt: 'Le chien aboie devant la maison.',
    options: [
      { id: 'a', text: 'Le chien fait du bruit devant la maison', isCorrect: true },
      { id: 'b', text: 'Le chien dort sous la table', isCorrect: false },
      { id: 'c', text: 'La maison aboie sur le chien', isCorrect: false }
    ],
    correctAnswer: 'Le chien aboie devant la maison',
    explanation: 'Une seule phrase garde le même sens.',
    hint: 'Compare personnage, action et lieu.',
    tags: ['ce1','lecture','association','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-116',
    subject: 'francais',
    title: 'Répondre à qui',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du sujet',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'La maîtresse distribue les cahiers. Qui distribue les cahiers ?',
    options: [
      { id: 'a', text: 'La maîtresse', isCorrect: true },
      { id: 'b', text: 'Les cahiers', isCorrect: false },
      { id: 'c', text: 'La table', isCorrect: false }
    ],
    correctAnswer: 'La maîtresse',
    explanation: 'C’est la maîtresse qui fait l’action.',
    hint: 'Cherche qui agit.',
    tags: ['ce1','lecture','sujet','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-117',
    subject: 'francais',
    title: 'Comprendre une phrase avec avant',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Avant de courir, Sami attache ses lacets. Que fait Sami avant de courir ?',
    options: [
      { id: 'a', text: 'Il attache ses lacets', isCorrect: true },
      { id: 'b', text: 'Il prépare une soupe', isCorrect: false },
      { id: 'c', text: 'Il fait ses devoirs', isCorrect: false }
    ],
    correctAnswer: 'Il attache ses lacets',
    explanation: 'L’action est donnée dans la phrase.',
    hint: 'Cherche ce qu’il fait avant.',
    tags: ['ce1','lecture','temps','action','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-118',
    subject: 'francais',
    title: 'Repérer le bon moment',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Après le repas, Inès brosse ses dents. Quand se brosse-t-elle les dents ?',
    options: [
      { id: 'a', text: 'Après le repas', isCorrect: true },
      { id: 'b', text: 'Avant le réveil', isCorrect: false },
      { id: 'c', text: 'Pendant la récréation', isCorrect: false }
    ],
    correctAnswer: 'Après le repas',
    explanation: 'Le moment est écrit au début.',
    hint: 'Regarde le premier groupe de mots.',
    tags: ['ce1','lecture','temps','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-119',
    subject: 'francais',
    title: 'Comprendre un petit texte très court',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Paul a perdu son ballon. Il cherche partout dans le jardin. Que cherche Paul ?',
    options: [
      { id: 'a', text: 'Son ballon', isCorrect: true },
      { id: 'b', text: 'Son manteau', isCorrect: false },
      { id: 'c', text: 'Son vélo', isCorrect: false }
    ],
    correctAnswer: 'Son ballon',
    explanation: 'La deuxième phrase reprend l’objet perdu.',
    hint: 'Cherche ce qui a été perdu.',
    tags: ['ce1','lecture','petit-texte','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

    {
    id: 'fr-ce1-lecture-120',
    subject: 'francais',
    title: 'Repérer une cause simple 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension explicite',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Maya allume la lampe parce qu’il fait sombre. Pourquoi allume-t-elle la lampe ?',
    options: [
      { id: 'a', text: 'Parce qu’il fait sombre', isCorrect: true },
      { id: 'b', text: 'Parce qu’elle nage', isCorrect: false },
      { id: 'c', text: 'Parce qu’elle part en vacances', isCorrect: false }
    ],
    correctAnswer: 'Parce qu’il fait sombre',
    explanation: 'La raison est écrite dans la phrase.',
    hint: 'Relis après parce que.',
    tags: ['ce1','lecture','cause','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },
];
