import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe1OrthographeExercises: FrenchExercise[] = [
  {
    id: 'fr-ce1-orthographe-101',
    subject: 'francais',
    title: 'Et ou est',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Le chat ___ noir.',
    options: [
      { id: 'a', text: 'et', isCorrect: false },
      { id: 'b', text: 'est', isCorrect: true }
    ],
    correctAnswer: 'est',
    explanation: 'Ici, est est le verbe être.',
    hint: 'Peut-on dire était ?',
    tags: ['ce1','orthographe','et-est','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-102',
    subject: 'francais',
    title: 'A ou à',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Lina ___ un vélo.',
    options: [
      { id: 'a', text: 'a', isCorrect: true },
      { id: 'b', text: 'à', isCorrect: false }
    ],
    correctAnswer: 'a',
    explanation: 'Ici, a est le verbe avoir.',
    hint: 'Peut-on dire avait ?',
    tags: ['ce1','orthographe','a-a-grave','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-103',
    subject: 'francais',
    title: 'On ou ont',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Ils ___ une surprise.',
    options: [
      { id: 'a', text: 'on', isCorrect: false },
      { id: 'b', text: 'ont', isCorrect: true }
    ],
    correctAnswer: 'ont',
    explanation: 'Avec ils, on utilise le verbe avoir : ils ont.',
    hint: 'Peut-on dire avaient ?',
    tags: ['ce1','orthographe','on-ont','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-104',
    subject: 'francais',
    title: 'Ce ou se',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ matin, il se lève tôt.',
    options: [
      { id: 'a', text: 'Ce', isCorrect: true },
      { id: 'b', text: 'Se', isCorrect: false }
    ],
    correctAnswer: 'Ce',
    explanation: 'On dit ce matin pour montrer le moment.',
    hint: 'Peut-on remplacer par ce jour-là ?',
    tags: ['ce1','orthographe','ce-se','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-105',
    subject: 'francais',
    title: 'Son ou sont',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ cartable est lourd.',
    options: [
      { id: 'a', text: 'Son', isCorrect: true },
      { id: 'b', text: 'Sont', isCorrect: false }
    ],
    correctAnswer: 'Son',
    explanation: 'On parle ici d’un objet qui appartient à quelqu’un.',
    hint: 'Montre-t-on un objet ou une action ?',
    tags: ['ce1','orthographe','son-sont','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-106',
    subject: 'francais',
    title: 'Ou ou où',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Sais-tu ___ il habite ?',
    options: [
      { id: 'a', text: 'ou', isCorrect: false },
      { id: 'b', text: 'où', isCorrect: true }
    ],
    correctAnswer: 'où',
    explanation: 'Où sert à parler d’un lieu.',
    hint: 'La phrase parle-t-elle d’un endroit ?',
    tags: ['ce1','orthographe','ou-ou-accent','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-107',
    subject: 'francais',
    title: 'Et ou est 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Léo ___ Mila arrivent.',
    options: [
      { id: 'a', text: 'et', isCorrect: true },
      { id: 'b', text: 'est', isCorrect: false }
    ],
    correctAnswer: 'et',
    explanation: 'Le mot et relie deux prénoms.',
    hint: 'Relie-t-on deux personnes ?',
    tags: ['ce1','orthographe','et-est','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-108',
    subject: 'francais',
    title: 'A ou à 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Il va ___ l’école.',
    options: [
      { id: 'a', text: 'a', isCorrect: false },
      { id: 'b', text: 'à', isCorrect: true }
    ],
    correctAnswer: 'à',
    explanation: 'À indique un lieu.',
    hint: 'Parle-t-on d’un endroit ?',
    tags: ['ce1','orthographe','a-a-grave','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-109',
    subject: 'francais',
    title: 'On ou ont 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ joue dans la cour.',
    options: [
      { id: 'a', text: 'On', isCorrect: true },
      { id: 'b', text: 'Ont', isCorrect: false }
    ],
    correctAnswer: 'On',
    explanation: 'On remplace ici une ou plusieurs personnes.',
    hint: 'Peut-on dire nous ?',
    tags: ['ce1','orthographe','on-ont','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-110',
    subject: 'francais',
    title: 'Ce ou se 2',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Il ___ cache derrière la porte.',
    options: [
      { id: 'a', text: 'ce', isCorrect: false },
      { id: 'b', text: 'se', isCorrect: true }
    ],
    correctAnswer: 'se',
    explanation: 'Se fait partie du verbe se cacher.',
    hint: 'Le verbe est-il pronominal ?',
    tags: ['ce1','orthographe','ce-se','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-111',
    subject: 'francais',
    title: 'Son ou sont 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Ils ___ prêts.',
    options: [
      { id: 'a', text: 'son', isCorrect: false },
      { id: 'b', text: 'sont', isCorrect: true }
    ],
    correctAnswer: 'sont',
    explanation: 'Avec ils, on peut utiliser le verbe être : ils sont.',
    hint: 'Peut-on dire ils étaient ?',
    tags: ['ce1','orthographe','son-sont','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-112',
    subject: 'francais',
    title: 'Ou ou où 2',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Tu veux du pain ___ du riz ?',
    options: [
      { id: 'a', text: 'ou', isCorrect: true },
      { id: 'b', text: 'où', isCorrect: false }
    ],
    correctAnswer: 'ou',
    explanation: 'Ou sert à proposer un choix.',
    hint: 'Y a-t-il un choix ?',
    tags: ['ce1','orthographe','ou-ou-accent','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-113',
    subject: 'francais',
    title: 'Le ou les',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'determinants frequents',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ enfants jouent.',
    options: [
      { id: 'a', text: 'Le', isCorrect: false },
      { id: 'b', text: 'Les', isCorrect: true }
    ],
    correctAnswer: 'Les',
    explanation: 'Enfants est au pluriel, on dit les enfants.',
    hint: 'Y en a-t-il plusieurs ?',
    tags: ['ce1','orthographe','determinants','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-114',
    subject: 'francais',
    title: 'Ma ou mon',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'determinants possessifs',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ trousse est bleue.',
    options: [
      { id: 'a', text: 'Ma', isCorrect: true },
      { id: 'b', text: 'Mon', isCorrect: false }
    ],
    correctAnswer: 'Ma',
    explanation: 'On dit ma trousse.',
    hint: 'Trousse est féminin.',
    tags: ['ce1','orthographe','ma-mon','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-115',
    subject: 'francais',
    title: 'Mes ou mais',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ crayons sont neufs.',
    options: [
      { id: 'a', text: 'Mes', isCorrect: true },
      { id: 'b', text: 'Mais', isCorrect: false }
    ],
    correctAnswer: 'Mes',
    explanation: 'Mes montre que les crayons appartiennent à quelqu’un.',
    hint: 'Parle-t-on d’une possession ?',
    tags: ['ce1','orthographe','mes-mais','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-116',
    subject: 'francais',
    title: 'Ces ou ses',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ chaussures sont sales.',
    options: [
      { id: 'a', text: 'Ces', isCorrect: true },
      { id: 'b', text: 'Ses', isCorrect: false }
    ],
    correctAnswer: 'Ces',
    explanation: 'Ces sert à montrer plusieurs choses.',
    hint: 'Peut-on dire ces chaussures-là ?',
    tags: ['ce1','orthographe','ces-ses','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-117',
    subject: 'francais',
    title: 'Ses ou ces',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Lina range ___ livres.',
    options: [
      { id: 'a', text: 'ses', isCorrect: true },
      { id: 'b', text: 'ces', isCorrect: false }
    ],
    correctAnswer: 'ses',
    explanation: 'On parle des livres de Lina.',
    hint: 'À qui appartiennent-ils ?',
    tags: ['ce1','orthographe','ces-ses','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

    {
    id: 'fr-ce1-orthographe-118',
    subject: 'francais',
    title: 'Mais ou mes',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Je viens, ___ je suis en retard.',
    options: [
      { id: 'a', text: 'mes', isCorrect: false },
      { id: 'b', text: 'mais', isCorrect: true }
    ],
    correctAnswer: 'mais',
    explanation: 'Mais sert à opposer deux idées.',
    hint: 'Y a-t-il une opposition ?',
    tags: ['ce1','orthographe','mes-mais','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:orthographe',
  },
];
