import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe1ExpressionExercises: FrenchExercise[] = [
  {
    id: 'fr-ce1-expressionecrite-101',
    subject: 'francais',
    title: 'Choisir la phrase correcte',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'expression_ecrite',
    subskill: 'phrase correcte',
    format: 'qcm',
    instructions: 'Choisis la phrase bien écrite.',
    prompt: 'Quelle phrase est correcte ?',
    options: [
      { id: 'a', text: 'Le chat dort.', isCorrect: true },
      { id: 'b', text: 'chat le dort', isCorrect: false },
      { id: 'c', text: 'Dort le chat.', isCorrect: false }
    ],
    correctAnswer: 'Le chat dort.',
    explanation: 'La phrase correcte suit un bon ordre et se lit bien.',
    hint: 'Cherche la phrase qui sonne juste.',
    tags: ['ce1','expression-ecrite','phrase-correcte','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:expression_ecrite',
  },

    {
    id: 'fr-ce1-expressionecrite-102',
    subject: 'francais',
    title: 'Trouver le bon ordre',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'expression_ecrite',
    subskill: 'ordre des mots',
    format: 'qcm',
    instructions: 'Choisis la meilleure phrase.',
    prompt: 'Pour dire qu’un chien court, quelle phrase choisis-tu ?',
    options: [
      { id: 'a', text: 'Court chien le.', isCorrect: false },
      { id: 'b', text: 'Le chien court.', isCorrect: true },
      { id: 'c', text: 'Le court chien.', isCorrect: false }
    ],
    correctAnswer: 'Le chien court.',
    explanation: 'La phrase correcte a un ordre simple et clair.',
    hint: 'Commence par le personnage.',
    tags: ['ce1','expression-ecrite','ordre-des-mots','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:expression_ecrite',
  },

    {
    id: 'fr-ce1-expressionecrite-103',
    subject: 'francais',
    title: 'Phrase complète',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'expression_ecrite',
    subskill: 'phrase correcte',
    format: 'qcm',
    instructions: 'Choisis la phrase complète.',
    prompt: 'Quelle solution est correcte ?',
    options: [
      { id: 'a', text: 'La poule picore.', isCorrect: true },
      { id: 'b', text: 'La poule', isCorrect: false },
      { id: 'c', text: 'Picore dans', isCorrect: false }
    ],
    correctAnswer: 'La poule picore.',
    explanation: 'Une phrase complète a du sens.',
    hint: 'Cherche une phrase qui finit bien.',
    tags: ['ce1','expression-ecrite','phrase-correcte','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:expression_ecrite',
  },

    {
    id: 'fr-ce1-expressionecrite-104',
    subject: 'francais',
    title: 'Majuscule et point',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'expression_ecrite',
    subskill: 'ponctuation simple',
    format: 'qcm',
    instructions: 'Choisis la phrase bien écrite.',
    prompt: 'Quelle phrase commence bien et finit bien ?',
    options: [
      { id: 'a', text: 'le chat dort', isCorrect: false },
      { id: 'b', text: 'Le chat dort.', isCorrect: true },
      { id: 'c', text: 'Le chat dort', isCorrect: false }
    ],
    correctAnswer: 'Le chat dort.',
    explanation: 'Une phrase correcte commence par une majuscule et finit par un point.',
    hint: 'Regarde le début et la fin.',
    tags: ['ce1','expression-ecrite','ponctuation','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:expression_ecrite',
  },

    {
    id: 'fr-ce1-expressionecrite-105',
    subject: 'francais',
    title: 'Phrase qui a du sens',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'expression_ecrite',
    subskill: 'coherence de phrase',
    format: 'qcm',
    instructions: 'Choisis la phrase qui a du sens.',
    prompt: 'Quelle phrase a du sens ?',
    options: [
      { id: 'a', text: 'La banane lit un cahier.', isCorrect: false },
      { id: 'b', text: 'Le garçon mange une pomme.', isCorrect: true },
      { id: 'c', text: 'Le trottoir dort vite.', isCorrect: false }
    ],
    correctAnswer: 'Le garçon mange une pomme.',
    explanation: 'Une seule phrase est logique.',
    hint: 'Cherche une scène possible.',
    tags: ['ce1','expression-ecrite','coherence','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:expression_ecrite',
  },

    {
    id: 'fr-ce1-expressionecrite-106',
    subject: 'francais',
    title: 'Ordre des mots 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'expression_ecrite',
    subskill: 'ordre des mots',
    format: 'qcm',
    instructions: 'Choisis la phrase bien rangée.',
    prompt: 'Pour parler de Léa qui lit, choisis la bonne phrase.',
    options: [
      { id: 'a', text: 'Lit Léa.', isCorrect: false },
      { id: 'b', text: 'Léa lit.', isCorrect: true },
      { id: 'c', text: 'Lea la lit.', isCorrect: false }
    ],
    correctAnswer: 'Léa lit.',
    explanation: 'Léa lit est une phrase bien ordonnée.',
    hint: 'Qui fait l’action ?',
    tags: ['ce1','expression-ecrite','ordre-des-mots','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:expression_ecrite',
  },

    {
    id: 'fr-ce1-expressionecrite-107',
    subject: 'francais',
    title: 'Phrase correcte 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'expression_ecrite',
    subskill: 'phrase correcte',
    format: 'qcm',
    instructions: 'Choisis la meilleure phrase.',
    prompt: 'Quelle phrase est la mieux écrite ?',
    options: [
      { id: 'a', text: 'Ma sœur chante.', isCorrect: true },
      { id: 'b', text: 'Ma chante sœur.', isCorrect: false },
      { id: 'c', text: 'Chante ma sœur le.', isCorrect: false }
    ],
    correctAnswer: 'Ma sœur chante.',
    explanation: 'La phrase correcte suit un ordre simple.',
    hint: 'Lis les phrases à voix basse.',
    tags: ['ce1','expression-ecrite','phrase-correcte','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:expression_ecrite',
  },

    {
    id: 'fr-ce1-expressionecrite-108',
    subject: 'francais',
    title: 'Logique et ponctuation',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'expression_ecrite',
    subskill: 'ponctuation simple',
    format: 'qcm',
    instructions: 'Choisis la bonne phrase.',
    prompt: 'Quelle phrase est bien écrite ?',
    options: [
      { id: 'a', text: 'Nous jouons dehors.', isCorrect: true },
      { id: 'b', text: 'nous jouons dehors', isCorrect: false },
      { id: 'c', text: 'Nous dehors jouons', isCorrect: false }
    ],
    correctAnswer: 'Nous jouons dehors.',
    explanation: 'La bonne phrase a une majuscule, un bon ordre et un point.',
    hint: 'Regarde la majuscule, l’ordre et le point.',
    tags: ['ce1','expression-ecrite','ponctuation','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:expression_ecrite',
  },
];
