import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe1VocabulaireExercises: FrenchExercise[] = [
  {
    id: 'fr-ce1-vocabulaire-101',
    subject: 'francais',
    title: 'Synonyme simple',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'synonymes',
    format: 'qcm',
    instructions: 'Choisis le mot qui veut presque dire la même chose.',
    prompt: 'Le synonyme de content est :',
    options: [
      { id: 'a', text: 'heureux', isCorrect: true },
      { id: 'b', text: 'triste', isCorrect: false },
      { id: 'c', text: 'rapide', isCorrect: false }
    ],
    correctAnswer: 'heureux',
    explanation: 'Content et heureux ont un sens proche.',
    hint: 'Cherche un mot positif.',
    tags: ['ce1','vocabulaire','synonymes','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-102',
    subject: 'francais',
    title: 'Trouver le contraire',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'contraires',
    format: 'qcm',
    instructions: 'Choisis le contraire.',
    prompt: 'Le contraire de grand est :',
    options: [
      { id: 'a', text: 'petit', isCorrect: true },
      { id: 'b', text: 'chaud', isCorrect: false },
      { id: 'c', text: 'long', isCorrect: false }
    ],
    correctAnswer: 'petit',
    explanation: 'Petit est le contraire de grand.',
    hint: 'Cherche le mot opposé.',
    tags: ['ce1','vocabulaire','contraires','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-103',
    subject: 'francais',
    title: 'Catégorie animal',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'categories',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Lequel est un animal ?',
    options: [
      { id: 'a', text: 'renard', isCorrect: true },
      { id: 'b', text: 'armoire', isCorrect: false },
      { id: 'c', text: 'savon', isCorrect: false }
    ],
    correctAnswer: 'renard',
    explanation: 'Le renard est un animal.',
    hint: 'Cherche un être vivant.',
    tags: ['ce1','vocabulaire','categories','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-104',
    subject: 'francais',
    title: 'Intrus simple',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'intrus',
    format: 'qcm',
    instructions: 'Choisis l’intrus.',
    prompt: 'Lequel n’est pas un fruit ?',
    options: [
      { id: 'a', text: 'pomme', isCorrect: false },
      { id: 'b', text: 'poire', isCorrect: false },
      { id: 'c', text: 'chaussette', isCorrect: true }
    ],
    correctAnswer: 'chaussette',
    explanation: 'Chaussette n’est pas un fruit.',
    hint: 'Deux mots vont ensemble.',
    tags: ['ce1','vocabulaire','intrus','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-105',
    subject: 'francais',
    title: 'Synonyme 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'synonymes',
    format: 'qcm',
    instructions: 'Choisis le synonyme.',
    prompt: 'Le synonyme de joli est :',
    options: [
      { id: 'a', text: 'beau', isCorrect: true },
      { id: 'b', text: 'sale', isCorrect: false },
      { id: 'c', text: 'dur', isCorrect: false }
    ],
    correctAnswer: 'beau',
    explanation: 'Joli et beau ont un sens proche.',
    hint: 'Cherche un mot positif.',
    tags: ['ce1','vocabulaire','synonymes','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-106',
    subject: 'francais',
    title: 'Contraire 2',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'contraires',
    format: 'qcm',
    instructions: 'Choisis le contraire.',
    prompt: 'Le contraire de chaud est :',
    options: [
      { id: 'a', text: 'froid', isCorrect: true },
      { id: 'b', text: 'rapide', isCorrect: false },
      { id: 'c', text: 'clair', isCorrect: false }
    ],
    correctAnswer: 'froid',
    explanation: 'Froid est le contraire de chaud.',
    hint: 'Cherche l’opposé.',
    tags: ['ce1','vocabulaire','contraires','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-107',
    subject: 'francais',
    title: 'Objet d’école',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'categories',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Lequel est un objet de la classe ?',
    options: [
      { id: 'a', text: 'règle', isCorrect: true },
      { id: 'b', text: 'requin', isCorrect: false },
      { id: 'c', text: 'forêt', isCorrect: false }
    ],
    correctAnswer: 'règle',
    explanation: 'La règle est un objet de la classe.',
    hint: 'Cherche un objet pour apprendre.',
    tags: ['ce1','vocabulaire','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-108',
    subject: 'francais',
    title: 'Intrus animaux',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'intrus',
    format: 'qcm',
    instructions: 'Choisis l’intrus.',
    prompt: 'Quel mot n’est pas un animal ?',
    options: [
      { id: 'a', text: 'chien', isCorrect: false },
      { id: 'b', text: 'chat', isCorrect: false },
      { id: 'c', text: 'crayon', isCorrect: true }
    ],
    correctAnswer: 'crayon',
    explanation: 'Crayon n’est pas un animal.',
    hint: 'Deux mots sont des animaux.',
    tags: ['ce1','vocabulaire','intrus','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-109',
    subject: 'francais',
    title: 'Catégorie vêtement',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'categories',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Lequel est un vêtement ?',
    options: [
      { id: 'a', text: 'manteau', isCorrect: true },
      { id: 'b', text: 'banane', isCorrect: false },
      { id: 'c', text: 'ardoise', isCorrect: false }
    ],
    correctAnswer: 'manteau',
    explanation: 'Le manteau est un vêtement.',
    hint: 'On le porte sur soi.',
    tags: ['ce1','vocabulaire','vetements','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-110',
    subject: 'francais',
    title: 'Synonyme 3',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'synonymes',
    format: 'qcm',
    instructions: 'Choisis le synonyme.',
    prompt: 'Le synonyme de rapide est :',
    options: [
      { id: 'a', text: 'vite', isCorrect: true },
      { id: 'b', text: 'lourd', isCorrect: false },
      { id: 'c', text: 'sale', isCorrect: false }
    ],
    correctAnswer: 'vite',
    explanation: 'Rapide et vite expriment une idée proche ici.',
    hint: 'Cherche un mot proche.',
    tags: ['ce1','vocabulaire','synonymes','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-111',
    subject: 'francais',
    title: 'Contraire 3',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'contraires',
    format: 'qcm',
    instructions: 'Choisis le contraire.',
    prompt: 'Le contraire de ouvrir est :',
    options: [
      { id: 'a', text: 'fermer', isCorrect: true },
      { id: 'b', text: 'porter', isCorrect: false },
      { id: 'c', text: 'chanter', isCorrect: false }
    ],
    correctAnswer: 'fermer',
    explanation: 'Fermer est le contraire de ouvrir.',
    hint: 'Pense à une porte.',
    tags: ['ce1','vocabulaire','contraires','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-112',
    subject: 'francais',
    title: 'Intrus vêtements',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'intrus',
    format: 'qcm',
    instructions: 'Choisis l’intrus.',
    prompt: 'Lequel n’est pas un vêtement ?',
    options: [
      { id: 'a', text: 'pull', isCorrect: false },
      { id: 'b', text: 'botte', isCorrect: false },
      { id: 'c', text: 'carotte', isCorrect: true }
    ],
    correctAnswer: 'carotte',
    explanation: 'Carotte n’est pas un vêtement.',
    hint: 'Deux mots se portent.',
    tags: ['ce1','vocabulaire','intrus','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-113',
    subject: 'francais',
    title: 'Catégorie maison',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'categories',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Lequel est dans la maison ?',
    options: [
      { id: 'a', text: 'canapé', isCorrect: true },
      { id: 'b', text: 'nuage', isCorrect: false },
      { id: 'c', text: 'girafe', isCorrect: false }
    ],
    correctAnswer: 'canapé',
    explanation: 'Le canapé se trouve dans la maison.',
    hint: 'Cherche un objet du salon.',
    tags: ['ce1','vocabulaire','maison','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-114',
    subject: 'francais',
    title: 'Synonyme 4',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'synonymes',
    format: 'qcm',
    instructions: 'Choisis le synonyme.',
    prompt: 'Le synonyme de fâché est :',
    options: [
      { id: 'a', text: 'en colère', isCorrect: true },
      { id: 'b', text: 'content', isCorrect: false },
      { id: 'c', text: 'calme', isCorrect: false }
    ],
    correctAnswer: 'en colère',
    explanation: 'Fâché et en colère ont un sens proche.',
    hint: 'Cherche un mot proche du sentiment.',
    tags: ['ce1','vocabulaire','synonymes','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-115',
    subject: 'francais',
    title: 'Contraire 4',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'contraires',
    format: 'qcm',
    instructions: 'Choisis le contraire.',
    prompt: 'Le contraire de monter est :',
    options: [
      { id: 'a', text: 'descendre', isCorrect: true },
      { id: 'b', text: 'laver', isCorrect: false },
      { id: 'c', text: 'porter', isCorrect: false }
    ],
    correctAnswer: 'descendre',
    explanation: 'Descendre est le contraire de monter.',
    hint: 'Cherche le mouvement inverse.',
    tags: ['ce1','vocabulaire','contraires','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

    {
    id: 'fr-ce1-vocabulaire-116',
    subject: 'francais',
    title: 'Intrus école',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'intrus',
    format: 'qcm',
    instructions: 'Choisis l’intrus.',
    prompt: 'Lequel n’est pas un objet d’école ?',
    options: [
      { id: 'a', text: 'trousse', isCorrect: false },
      { id: 'b', text: 'cahier', isCorrect: false },
      { id: 'c', text: 'poisson', isCorrect: true }
    ],
    correctAnswer: 'poisson',
    explanation: 'Poisson n’est pas un objet d’école.',
    hint: 'Deux mots servent à travailler.',
    tags: ['ce1','vocabulaire','intrus','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:vocabulaire',
  },
];
