import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCe1ConjugaisonExercises: FrenchExercise[] = [
  {
    id: 'fr-ce1-conjugaison-101',
    subject: 'francais',
    title: 'Avoir avec nous',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'verbe avoir au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ une balle.',
    options: [
      { id: 'a', text: 'avons', isCorrect: true },
      { id: 'b', text: 'avez', isCorrect: false },
      { id: 'c', text: 'ont', isCorrect: false }
    ],
    correctAnswer: 'avons',
    explanation: 'Avec nous, on dit nous avons.',
    hint: 'Pense à : nous avons.',
    tags: ['ce1','conjugaison','avoir','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-102',
    subject: 'francais',
    title: 'Être avec tu',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Tu ___ content.',
    options: [
      { id: 'a', text: 'es', isCorrect: true },
      { id: 'b', text: 'est', isCorrect: false },
      { id: 'c', text: 'suis', isCorrect: false }
    ],
    correctAnswer: 'es',
    explanation: 'Avec tu, on dit tu es.',
    hint: 'Pense à : tu es.',
    tags: ['ce1','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-103',
    subject: 'francais',
    title: 'Être avec ils',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Ils ___ prêts.',
    options: [
      { id: 'a', text: 'sont', isCorrect: true },
      { id: 'b', text: 'sommes', isCorrect: false },
      { id: 'c', text: 'êtes', isCorrect: false }
    ],
    correctAnswer: 'sont',
    explanation: 'Avec ils, on dit ils sont.',
    hint: 'Pense à : ils sont.',
    tags: ['ce1','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-104',
    subject: 'francais',
    title: 'Avoir avec j’',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'verbe avoir au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'J’___ une idée.',
    options: [
      { id: 'a', text: 'ai', isCorrect: true },
      { id: 'b', text: 'as', isCorrect: false },
      { id: 'c', text: 'a', isCorrect: false }
    ],
    correctAnswer: 'ai',
    explanation: 'Avec j’, on dit j’ai.',
    hint: 'Pense à : j’ai.',
    tags: ['ce1','conjugaison','avoir','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-105',
    subject: 'francais',
    title: 'Aller avec nous',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe aller au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ à la piscine.',
    options: [
      { id: 'a', text: 'allons', isCorrect: true },
      { id: 'b', text: 'allez', isCorrect: false },
      { id: 'c', text: 'vais', isCorrect: false }
    ],
    correctAnswer: 'allons',
    explanation: 'Avec nous, on dit nous allons.',
    hint: 'Pense à : nous allons.',
    tags: ['ce1','conjugaison','aller','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-106',
    subject: 'francais',
    title: 'Aller avec je',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe aller au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Je ___ au parc.',
    options: [
      { id: 'a', text: 'vais', isCorrect: true },
      { id: 'b', text: 'va', isCorrect: false },
      { id: 'c', text: 'allons', isCorrect: false }
    ],
    correctAnswer: 'vais',
    explanation: 'Avec je, on dit je vais.',
    hint: 'Pense à : je vais.',
    tags: ['ce1','conjugaison','aller','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-107',
    subject: 'francais',
    title: '1er groupe avec nous',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present 1er groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ en classe.',
    options: [
      { id: 'a', text: 'chantons', isCorrect: true },
      { id: 'b', text: 'chante', isCorrect: false },
      { id: 'c', text: 'chantez', isCorrect: false }
    ],
    correctAnswer: 'chantons',
    explanation: 'Avec nous, on dit nous chantons.',
    hint: 'Pense à : nous chantons.',
    tags: ['ce1','conjugaison','1er-groupe','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-108',
    subject: 'francais',
    title: '1er groupe avec tu',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present 1er groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Tu ___ bien.',
    options: [
      { id: 'a', text: 'dessines', isCorrect: true },
      { id: 'b', text: 'dessine', isCorrect: false },
      { id: 'c', text: 'dessinons', isCorrect: false }
    ],
    correctAnswer: 'dessines',
    explanation: 'Avec tu, on dit tu dessines.',
    hint: 'Pense à : tu dessines.',
    tags: ['ce1','conjugaison','1er-groupe','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-109',
    subject: 'francais',
    title: 'Être avec nous',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Nous ___ contents.',
    options: [
      { id: 'a', text: 'sommes', isCorrect: true },
      { id: 'b', text: 'êtes', isCorrect: false },
      { id: 'c', text: 'sont', isCorrect: false }
    ],
    correctAnswer: 'sommes',
    explanation: 'Avec nous, on dit nous sommes.',
    hint: 'Pense à : nous sommes.',
    tags: ['ce1','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-110',
    subject: 'francais',
    title: 'Avoir avec ils',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe avoir au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Ils ___ faim.',
    options: [
      { id: 'a', text: 'ont', isCorrect: true },
      { id: 'b', text: 'avons', isCorrect: false },
      { id: 'c', text: 'avez', isCorrect: false }
    ],
    correctAnswer: 'ont',
    explanation: 'Avec ils, on dit ils ont.',
    hint: 'Pense à : ils ont.',
    tags: ['ce1','conjugaison','avoir','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-111',
    subject: 'francais',
    title: '1er groupe avec je',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present 1er groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Je ___ dans la cour.',
    options: [
      { id: 'a', text: 'joue', isCorrect: true },
      { id: 'b', text: 'joues', isCorrect: false },
      { id: 'c', text: 'jouons', isCorrect: false }
    ],
    correctAnswer: 'joue',
    explanation: 'Avec je, on dit je joue.',
    hint: 'Pense à : je joue.',
    tags: ['ce1','conjugaison','1er-groupe','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-112',
    subject: 'francais',
    title: 'Avoir avec tu',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'verbe avoir au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Tu ___ un livre.',
    options: [
      { id: 'a', text: 'as', isCorrect: true },
      { id: 'b', text: 'ai', isCorrect: false },
      { id: 'c', text: 'a', isCorrect: false }
    ],
    correctAnswer: 'as',
    explanation: 'Avec tu, on dit tu as.',
    hint: 'Pense à : tu as.',
    tags: ['ce1','conjugaison','avoir','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-113',
    subject: 'francais',
    title: 'Être avec il',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Il ___ fatigué.',
    options: [
      { id: 'a', text: 'est', isCorrect: true },
      { id: 'b', text: 'es', isCorrect: false },
      { id: 'c', text: 'suis', isCorrect: false }
    ],
    correctAnswer: 'est',
    explanation: 'Avec il, on dit il est.',
    hint: 'Pense à : il est.',
    tags: ['ce1','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-114',
    subject: 'francais',
    title: 'Aller avec ils',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'verbe aller au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Ils ___ au stade.',
    options: [
      { id: 'a', text: 'vont', isCorrect: true },
      { id: 'b', text: 'allez', isCorrect: false },
      { id: 'c', text: 'vais', isCorrect: false }
    ],
    correctAnswer: 'vont',
    explanation: 'Avec ils, on dit ils vont.',
    hint: 'Pense à : ils vont.',
    tags: ['ce1','conjugaison','aller','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-115',
    subject: 'francais',
    title: '1er groupe avec vous',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'conjugaison',
    subskill: 'present 1er groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Vous ___ vite.',
    options: [
      { id: 'a', text: 'marchez', isCorrect: true },
      { id: 'b', text: 'marche', isCorrect: false },
      { id: 'c', text: 'marchons', isCorrect: false }
    ],
    correctAnswer: 'marchez',
    explanation: 'Avec vous, on dit vous marchez.',
    hint: 'Pense à : vous marchez.',
    tags: ['ce1','conjugaison','1er-groupe','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:conjugaison',
  },

    {
    id: 'fr-ce1-conjugaison-116',
    subject: 'francais',
    title: 'Être avec vous',
    schoolClass: 'CE1',
    generalLevel: 'advanced',
    skill: 'conjugaison',
    subskill: 'verbe etre au present',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Vous ___ en avance.',
    options: [
      { id: 'a', text: 'êtes', isCorrect: true },
      { id: 'b', text: 'sommes', isCorrect: false },
      { id: 'c', text: 'sont', isCorrect: false }
    ],
    correctAnswer: 'êtes',
    explanation: 'Avec vous, on dit vous êtes.',
    hint: 'Pense à : vous êtes.',
    tags: ['ce1','conjugaison','etre','present','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:conjugaison',
  },
];
