import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm1GeoLieuxHabiteExercises: HgExercise[] = [

  {
    id: 'hg-cm1-geo-hab-001',
    subject: 'histoire_geo',
    title: 'Ville ou campagne ?',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'lieux_habites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un endroit qui compte de nombreux habitants, des immeubles et des transports en commun s\'appelle…',
    options: [
      { id: 'a', text: 'un hameau', isCorrect: false },
      { id: 'b', text: 'une ville', isCorrect: true },
      { id: 'c', text: 'une forêt', isCorrect: false },
      { id: 'd', text: 'une ferme', isCorrect: false },
    ],
    correctAnswer: 'une ville',
    explanation: 'Une ville est caractérisée par une forte densité de population, des immeubles, des commerces et des transports.',
    hint: 'Plus il y a de monde, plus c\'est une grande ville.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-002',
    subject: 'histoire_geo',
    title: 'La densité de population',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'lieux_habites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la ville la plus peuplée de France ?',
    options: [
      { id: 'a', text: 'Lyon', isCorrect: false },
      { id: 'b', text: 'Marseille', isCorrect: false },
      { id: 'c', text: 'Paris', isCorrect: true },
      { id: 'd', text: 'Bordeaux', isCorrect: false },
    ],
    correctAnswer: 'Paris',
    explanation: 'Paris est la ville la plus peuplée de France avec plus de 2 millions d\'habitants intra-muros.',
    hint: 'C\'est aussi la capitale de la France.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-003',
    subject: 'histoire_geo',
    title: 'Habiter en montagne',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_habites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les habitants des régions de montagne adaptent leur mode de vie au relief et au climat. Quelle activité économique est très développée en montagne en hiver ?',
    options: [
      { id: 'a', text: 'La pêche en mer', isCorrect: false },
      { id: 'b', text: 'Le tourisme de ski', isCorrect: true },
      { id: 'c', text: 'La culture du blé', isCorrect: false },
      { id: 'd', text: 'La navigation fluviale', isCorrect: false },
    ],
    correctAnswer: 'Le tourisme de ski',
    explanation: 'Les stations de ski attirent de nombreux vacanciers en hiver dans les Alpes, les Pyrénées ou le Massif Central.',
    hint: 'En hiver, les montagnes sont couvertes de neige et les gens y viennent pour le sport.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-004',
    subject: 'histoire_geo',
    title: 'Habiter au bord de la mer',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_habites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les habitants du littoral vivent près de la mer. Quelle activité professionnelle est traditionnelle dans ces régions ?',
    options: [
      { id: 'a', text: 'L\'élevage de moutons', isCorrect: false },
      { id: 'b', text: 'La pêche', isCorrect: true },
      { id: 'c', text: 'La viticulture (vin)', isCorrect: false },
      { id: 'd', text: 'L\'exploitation forestière', isCorrect: false },
    ],
    correctAnswer: 'La pêche',
    explanation: 'Dans les zones côtières, la pêche est une activité traditionnelle importante. Les pêcheurs partent en mer pour ramener du poisson.',
    hint: 'Ce métier consiste à attraper des poissons dans la mer.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-005',
    subject: 'histoire_geo',
    title: 'Les espaces ruraux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_habites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on les espaces en dehors des villes, où l\'on trouve des champs, des forêts et des villages ?',
    options: [
      { id: 'a', text: 'Les espaces urbains', isCorrect: false },
      { id: 'b', text: 'Les espaces ruraux', isCorrect: true },
      { id: 'c', text: 'Les espaces industriels', isCorrect: false },
      { id: 'd', text: 'Les espaces maritimes', isCorrect: false },
    ],
    correctAnswer: 'Les espaces ruraux',
    explanation: 'Les espaces ruraux désignent les campagnes, avec leurs villages, leurs champs et leurs forêts, par opposition aux espaces urbains.',
    hint: 'En France, une grande partie du territoire est encore couverte de ces espaces.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-006',
    subject: 'histoire_geo',
    title: 'La banlieue',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'lieux_habites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on les zones situées autour d\'une grande ville, qui en dépendent mais n\'en font pas partie ?',
    options: [
      { id: 'a', text: 'Les quartiers', isCorrect: false },
      { id: 'b', text: 'Les banlieues', isCorrect: true },
      { id: 'c', text: 'Les communes rurales', isCorrect: false },
      { id: 'd', text: 'Les îles', isCorrect: false },
    ],
    correctAnswer: 'Les banlieues',
    explanation: 'La banlieue est la zone qui entoure une grande ville. Beaucoup de personnes habitent en banlieue et travaillent en ville.',
    hint: 'Ces zones se trouvent à la périphérie des grandes villes.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-007',
    subject: 'histoire_geo',
    title: "Agglomération et aire urbaine",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Une ville principale entourée de communes qui lui sont liées forme une agglomération. L'ensemble plus large incluant aussi les zones résidentielles autour s'appelle…",
    options: [
      { id: 'a', text: "Un village", isCorrect: false },
      { id: 'b', text: "Une aire urbaine", isCorrect: true },
      { id: 'c', text: "Un département", isCorrect: false },
      { id: 'd', text: "Une région", isCorrect: false },
    ],
    correctAnswer: "Une aire urbaine",
    explanation: "L'aire urbaine est l'ensemble formé par une ville (le pôle urbain) et les communes autour dont les habitants viennent travailler en ville. C'est la plus grande unité de mesure d'une ville.",
    hint: "Aire urbaine = ville + zones résidentielles autour.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-008',
    subject: 'histoire_geo',
    title: "Métropoles régionales",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Après Paris, quelles sont les principales métropoles régionales françaises ?",
    options: [
      { id: 'a', text: "Chartres, Beauvais et Laval", isCorrect: false },
      { id: 'b', text: "Lyon, Marseille, Toulouse, Bordeaux, Lille", isCorrect: true },
      { id: 'c', text: "Versailles, Reims et Amiens uniquement", isCorrect: false },
      { id: 'd', text: "Dijon, Troyes et Bourges uniquement", isCorrect: false },
    ],
    correctAnswer: "Lyon, Marseille, Toulouse, Bordeaux, Lille",
    explanation: "Les principales métropoles régionales françaises sont Lyon, Marseille, Toulouse, Bordeaux, Lille, Nantes, Strasbourg et Nice. Chacune est le cœur économique et culturel de sa région.",
    hint: "Lyon, Marseille, Toulouse, Bordeaux, Lille = les grandes villes hors Paris.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-009',
    subject: 'histoire_geo',
    title: "Rural attractif",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "On observe depuis quelques décennies un phénomène de rurbanisation : des citadins s'installent à la campagne. Pourquoi ?",
    options: [
      { id: 'a', text: "Parce que les salaires sont plus élevés à la campagne", isCorrect: false },
      { id: 'b', text: "Pour chercher plus d'espace, de nature et une meilleure qualité de vie", isCorrect: true },
      { id: 'c', text: "Parce que les villes ont été interdites d'habitation", isCorrect: false },
      { id: 'd', text: "Parce que le réseau internet n'existe qu'en campagne", isCorrect: false },
    ],
    correctAnswer: "Pour chercher plus d'espace, de nature et une meilleure qualité de vie",
    explanation: "La rurbanisation (ou exode urbain) désigne le retour de citadins vers les zones rurales. Ils cherchent plus d'espace, de nature, des maisons moins chères et une vie plus calme, tout en travaillant parfois en télétravail.",
    hint: "Campagne + télétravail → retour des citadins vers la nature.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-010',
    subject: 'histoire_geo',
    title: "Quartiers d'une ville",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Une grande ville est souvent divisée en quartiers aux fonctions différentes. Qu'est-ce que le centre historique ?",
    options: [
      { id: 'a', text: "Une zone industrielle avec des usines", isCorrect: false },
      { id: 'b', text: "Le cœur ancien de la ville avec des monuments, commerces et rues étroites", isCorrect: true },
      { id: 'c', text: "Une zone résidentielle moderne en banlieue", isCorrect: false },
      { id: 'd', text: "Un quartier d'affaires avec des gratte-ciels", isCorrect: false },
    ],
    correctAnswer: "Le cœur ancien de la ville avec des monuments, commerces et rues étroites",
    explanation: "Le centre historique est le noyau originel de la ville : il abrite souvent la cathédrale, la mairie, des rues médiévales et des commerces. Paris, Lyon, Strasbourg ont des centres historiques remarquables.",
    hint: "Centre historique = vieille ville, monuments, rues étroites.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-011',
    subject: 'histoire_geo',
    title: "Les DOM",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France possède des départements et régions d'outre-mer (DROM). Lesquels se trouvent dans les Caraïbes (Antilles) ?",
    options: [
      { id: 'a', text: "La Réunion et Mayotte", isCorrect: false },
      { id: 'b', text: "La Martinique et la Guadeloupe", isCorrect: true },
      { id: 'c', text: "La Guyane et la Réunion", isCorrect: false },
      { id: 'd', text: "Mayotte et la Guyane", isCorrect: false },
    ],
    correctAnswer: "La Martinique et la Guadeloupe",
    explanation: "La Martinique et la Guadeloupe sont deux îles françaises dans les Caraïbes. La Guyane est en Amérique du Sud, la Réunion dans l'océan Indien, Mayotte dans l'océan Indien (îles Comores).",
    hint: "Caraïbes = Antilles = Martinique + Guadeloupe.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-012',
    subject: 'histoire_geo',
    title: "Densité de population",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La densité de population mesure le nombre d'habitants par km². Quelle région de France a la densité la plus élevée ?",
    options: [
      { id: 'a', text: "La Bretagne", isCorrect: false },
      { id: 'b', text: "L'Île-de-France (région parisienne)", isCorrect: true },
      { id: 'c', text: "La Corse", isCorrect: false },
      { id: 'd', text: "La Nouvelle-Aquitaine", isCorrect: false },
    ],
    correctAnswer: "L'Île-de-France (région parisienne)",
    explanation: "L'Île-de-France est la région la plus dense de France (environ 1 000 hab/km²). Paris intra-muros atteint 20 000 hab/km². La Corse et le Massif Central sont les zones les moins densément peuplées.",
    hint: "Paris = ville la plus peuplée → Île-de-France = région la plus dense.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-013',
    subject: 'histoire_geo',
    title: "Habitat dispersé vs groupé",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Dans certaines régions, les maisons sont regroupées dans des villages. Dans d'autres, elles sont éparpillées dans la campagne. Comment appelle-t-on ce deuxième type d'habitat ?",
    options: [
      { id: 'a', text: "L'habitat groupé", isCorrect: false },
      { id: 'b', text: "L'habitat dispersé", isCorrect: true },
      { id: 'c', text: "L'habitat vertical", isCorrect: false },
      { id: 'd', text: "L'habitat collectif", isCorrect: false },
    ],
    correctAnswer: "L'habitat dispersé",
    explanation: "L'habitat dispersé (fermes isolées) est typique de l'ouest de la France (Bretagne, Normandie). L'habitat groupé (villages denses) est plus courant dans le Midi et en Alsace.",
    hint: "Dispersé = éparpillé dans la campagne. Groupé = village dense.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-014',
    subject: 'histoire_geo',
    title: "Le littoral habité",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les littoraux (côtes maritimes) accueillent de nombreux habitants. Quelle est la principale raison pour laquelle les gens s'y installent ?",
    options: [
      { id: 'a', text: "Il n'y fait jamais froid", isCorrect: false },
      { id: 'b', text: "Les activités économiques (pêche, tourisme, ports) et la qualité de vie", isCorrect: true },
      { id: 'c', text: "Les terres agricoles y sont les plus fertiles", isCorrect: false },
      { id: 'd', text: "Les salaires y sont réglementés par l'État", isCorrect: false },
    ],
    correctAnswer: "Les activités économiques (pêche, tourisme, ports) et la qualité de vie",
    explanation: "Les littoraux attirent par leur économie (ports commerciaux, pêche, tourisme estival) et leur cadre de vie (mer, plages). La Côte d'Azur et la Bretagne sont parmi les plus peuplées.",
    hint: "Littoral = mer + activités + qualité de vie.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-015',
    subject: 'histoire_geo',
    title: "Urbanisation mondiale",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Dans le monde entier, de plus en plus de gens quittent la campagne pour aller vivre en ville. Comment appelle-t-on ce phénomène ?",
    options: [
      { id: 'a', text: "La déforestation", isCorrect: false },
      { id: 'b', text: "L'urbanisation", isCorrect: true },
      { id: 'c', text: "La désertification", isCorrect: false },
      { id: 'd', text: "L'exode agricole", isCorrect: false },
    ],
    correctAnswer: "L'urbanisation",
    explanation: "L'urbanisation est le processus par lequel une part croissante de la population mondiale vit en ville. En 2023, plus de 55% des habitants de la Terre vivent en zone urbaine.",
    hint: "Urbanisation = les villes grandissent car les gens quittent la campagne.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-016',
    subject: 'histoire_geo',
    title: "Le tourisme rural",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le « tourisme vert » (ou tourisme rural) consiste à passer ses vacances à la campagne. Quel avantage cela représente-t-il pour les territoires ruraux ?",
    options: [
      { id: 'a', text: "Il n'y a aucun avantage", isCorrect: false },
      { id: 'b', text: "Il apporte des revenus et aide à maintenir des services (commerces, hébergements)", isCorrect: true },
      { id: 'c', text: "Il attire uniquement des personnes âgées", isCorrect: false },
      { id: 'd', text: "Il oblige les agriculteurs à cesser leurs activités", isCorrect: false },
    ],
    correctAnswer: "Il apporte des revenus et aide à maintenir des services (commerces, hébergements)",
    explanation: "Le tourisme rural génère des revenus pour les agriculteurs (gîtes, fermes pédagogiques) et aide à maintenir des services dans des zones sinon menacées de déprise économique.",
    hint: "Tourisme vert → revenus pour la campagne → services maintenus.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-017',
    subject: 'histoire_geo',
    title: "Maison individuelle vs appartement",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, où trouve-t-on principalement des appartements collectifs (immeubles) ?",
    options: [
      { id: 'a', text: "Dans les villages ruraux", isCorrect: false },
      { id: 'b', text: "Dans les grandes villes denses", isCorrect: true },
      { id: 'c', text: "Dans les zones de montagne", isCorrect: false },
      { id: 'd', text: "Dans les zones industrielles", isCorrect: false },
    ],
    correctAnswer: "Dans les grandes villes denses",
    explanation: "Les appartements sont concentrés dans les grandes villes où le foncier est rare et cher. Les maisons individuelles dominent en banlieue, en zones périurbaines et en milieu rural.",
    hint: "Ville dense → appartements. Campagne/banlieue → maisons individuelles.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-018',
    subject: 'histoire_geo',
    title: "Aire urbaine périurbaine",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un espace périurbain est une zone autour d'une ville où des habitants travaillent en ville mais résident à la campagne. Quel mode de transport utilisent-ils surtout ?",
    options: [
      { id: 'a', text: "Le vélo", isCorrect: false },
      { id: 'b', text: "La voiture ou le train (navettes domicile-travail)", isCorrect: true },
      { id: 'c', text: "Le métro souterrain", isCorrect: false },
      { id: 'd', text: "La trottinette électrique uniquement", isCorrect: false },
    ],
    correctAnswer: "La voiture ou le train (navettes domicile-travail)",
    explanation: "Les habitants des espaces périurbains font des navettes quotidiennes (trajets domicile-travail) en voiture ou en train. Ces déplacements, appelés « migrations pendulaires », peuvent durer 1h ou plus.",
    hint: "Périurbain + travail en ville = navette matin/soir, souvent en voiture ou train.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-019',
    subject: 'histoire_geo',
    title: "Les zones industrielles",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les zones industrielles sont des espaces dédiés aux usines et entrepôts. Où sont-elles généralement situées ?",
    options: [
      { id: 'a', text: "Au centre des villes historiques", isCorrect: false },
      { id: 'b', text: "En périphérie des villes, le long des grands axes de transport", isCorrect: true },
      { id: 'c', text: "Dans les centres touristiques", isCorrect: false },
      { id: 'd', text: "En haute montagne", isCorrect: false },
    ],
    correctAnswer: "En périphérie des villes, le long des grands axes de transport",
    explanation: "Les zones industrielles sont installées en périphérie pour avoir de l'espace, être proches des autoroutes et voies ferrées (livraisons) et ne pas perturber le centre-ville.",
    hint: "Usines en périphérie = espace + accès camions facile.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-hab-020',
    subject: 'histoire_geo',
    title: "La ville touristique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'lieux_de_vie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France est le premier pays au monde pour le tourisme. Quelle ville est la plus visitée ?",
    options: [
      { id: 'a', text: "Nice", isCorrect: false },
      { id: 'b', text: "Paris", isCorrect: true },
      { id: 'c', text: "Lyon", isCorrect: false },
      { id: 'd', text: "Bordeaux", isCorrect: false },
    ],
    correctAnswer: "Paris",
    explanation: "Paris est l'une des villes les plus visitées au monde (environ 30 millions de touristes par an). La tour Eiffel, le Louvre, Notre-Dame, Versailles en sont les principales attractions.",
    hint: "Tour Eiffel, Louvre, Notre-Dame → Paris = capitale touristique mondiale.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
