import type { HgExercise } from '../hg.types';
import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';

const A = cloneDefaultAdaptations();

export const hgCm1GeoFluxEchangesExercises: HgExercise[] = [
  {
    id: 'hg-cm1-geo-flx-001',
    subject: 'histoire_geo',
    title: 'Les échanges commerciaux mondiaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'appelle-t-on un « flux » en géographie ?',
    options: [
      { id: 'a', text: 'Un mouvement de personnes, de marchandises ou d\'informations d\'un endroit à un autre', isCorrect: true },
      { id: 'b', text: 'Une frontière entre deux pays', isCorrect: false },
      { id: 'c', text: 'Une zone d\'activité industrielle', isCorrect: false },
      { id: 'd', text: 'Un réseau de villes reliées entre elles', isCorrect: false },
    ],
    correctAnswer: 'a',
    explanation: 'En géographie, un flux désigne tout mouvement : migration de personnes, transport de marchandises, circulation d\'informations ou de capitaux.',
    hint: 'Pense au mot "courant" — quelque chose qui se déplace.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-002',
    subject: 'histoire_geo',
    title: 'Le commerce mondial',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel continent exporte le plus de marchandises dans le monde ?',
    options: [
      { id: 'a', text: 'L\'Afrique', isCorrect: false },
      { id: 'b', text: 'L\'Asie', isCorrect: true },
      { id: 'c', text: 'L\'Amérique du Sud', isCorrect: false },
      { id: 'd', text: 'L\'Océanie', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'Asie, notamment la Chine, le Japon et la Corée du Sud, est le premier continent exportateur mondial de marchandises industrielles.',
    hint: 'Pense au pays surnommé « l\'usine du monde ».',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-003',
    subject: 'histoire_geo',
    title: 'Les ports et le commerce',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les ports maritimes sont-ils si importants pour le commerce mondial ?',
    options: [
      { id: 'a', text: 'Parce qu\'ils produisent des marchandises', isCorrect: false },
      { id: 'b', text: 'Parce que plus de 80 % des échanges mondiaux de marchandises se font par bateau', isCorrect: true },
      { id: 'c', text: 'Parce qu\'ils stockent toutes les ressources naturelles', isCorrect: false },
      { id: 'd', text: 'Parce que les avions ne peuvent pas transporter de marchandises', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le transport maritime est le plus utilisé dans le monde car il est peu coûteux et peut transporter de très grandes quantités de marchandises.',
    hint: 'Pense à la taille des porte-conteneurs.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-004',
    subject: 'histoire_geo',
    title: 'La mondialisation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que signifie la mondialisation ?',
    options: [
      { id: 'a', text: 'La fabrication de tous les produits dans un seul pays', isCorrect: false },
      { id: 'b', text: 'Le développement des échanges économiques, culturels et humains à l\'échelle de la planète', isCorrect: true },
      { id: 'c', text: 'La disparition des frontières entre les pays', isCorrect: false },
      { id: 'd', text: 'L\'utilisation d\'une seule monnaie dans le monde entier', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La mondialisation désigne le développement des liens économiques, culturels et humains entre les pays du monde entier, rendant les économies de plus en plus interdépendantes.',
    hint: 'Pense à comment un téléphone peut être fabriqué avec des pièces venant de 10 pays différents.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-005',
    subject: 'histoire_geo',
    title: 'Les migrations',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une migration ?',
    options: [
      { id: 'a', text: 'Un voyage touristique dans un autre pays', isCorrect: false },
      { id: 'b', text: 'Le déplacement de personnes qui quittent leur lieu de vie pour s\'installer ailleurs', isCorrect: true },
      { id: 'c', text: 'Un échange de produits entre deux pays', isCorrect: false },
      { id: 'd', text: 'Un accord commercial entre deux pays', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Une migration est le déplacement d\'une personne ou d\'un groupe qui quitte son pays ou sa région pour s\'installer ailleurs, souvent pour trouver de meilleures conditions de vie.',
    hint: 'Les oiseaux migrent vers le sud en hiver : ils se déplacent pour s\'installer ailleurs.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-006',
    subject: 'histoire_geo',
    title: 'Internet et les flux d\'informations',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les informations circulent-elles principalement à l\'échelle mondiale aujourd\'hui ?',
    options: [
      { id: 'a', text: 'Par le courrier postal', isCorrect: false },
      { id: 'b', text: 'Par des câbles sous-marins et des satellites qui permettent l\'accès à Internet', isCorrect: true },
      { id: 'c', text: 'Par des pigeons voyageurs', isCorrect: false },
      { id: 'd', text: 'Par des porteurs à pied', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Internet fonctionne grâce à un réseau de câbles sous-marins qui relient les continents et de satellites en orbite, permettant d\'échanger des informations en une fraction de seconde.',
    hint: 'Des câbles au fond des océans relient les continents.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-007',
    subject: 'histoire_geo',
    title: 'Les conteneurs et le transport',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi servent les conteneurs dans le commerce mondial ?',
    options: [
      { id: 'a', text: 'À stocker l\'eau potable sur les bateaux', isCorrect: false },
      { id: 'b', text: 'À transporter des marchandises de façon standardisée par bateau, train ou camion', isCorrect: true },
      { id: 'c', text: 'À loger les marins à bord des navires', isCorrect: false },
      { id: 'd', text: 'À mesurer la profondeur des océans', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les conteneurs sont des boîtes métalliques standardisées qui permettent de transporter des marchandises facilement d\'un bateau à un train ou à un camion, accélérant le commerce mondial.',
    hint: 'Ces grandes boîtes métalliques qu\'on voit sur les quais des ports.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-008',
    subject: 'histoire_geo',
    title: 'Exportations et importations',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une importation pour la France ?',
    options: [
      { id: 'a', text: 'Un produit fabriqué en France et vendu à l\'étranger', isCorrect: false },
      { id: 'b', text: 'Un produit fabriqué à l\'étranger et acheté par la France', isCorrect: true },
      { id: 'c', text: 'Un produit fabriqué et consommé en France', isCorrect: false },
      { id: 'd', text: 'Un produit interdit à la vente en France', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Une importation est un produit fabriqué à l\'étranger qu\'un pays achète. À l\'inverse, une exportation est un produit fabriqué dans le pays et vendu à l\'étranger.',
    hint: 'Im-porter = faire entrer dans le pays.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-009',
    subject: 'histoire_geo',
    title: 'Les grandes routes maritimes',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel détroit relie la mer Méditerranée à l\'océan Atlantique et est essentiel pour le commerce ?',
    options: [
      { id: 'a', text: 'Le détroit de Magellan', isCorrect: false },
      { id: 'b', text: 'Le détroit de Gibraltar', isCorrect: true },
      { id: 'c', text: 'Le détroit de Bering', isCorrect: false },
      { id: 'd', text: 'Le détroit de Malacca', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le détroit de Gibraltar, entre l\'Espagne et le Maroc, est l\'un des passages maritimes les plus fréquentés au monde. Il relie la Méditerranée à l\'Atlantique.',
    hint: 'Il se trouve à l\'entrée de la Méditerranée, entre l\'Espagne et l\'Afrique.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-010',
    subject: 'histoire_geo',
    title: 'Le canal de Suez',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi le canal de Suez est-il très important pour le commerce mondial ?',
    options: [
      { id: 'a', text: 'Parce qu\'il fournit de l\'eau douce à l\'Égypte', isCorrect: false },
      { id: 'b', text: 'Parce qu\'il relie la mer Méditerranée à la mer Rouge, évitant le tour de l\'Afrique', isCorrect: true },
      { id: 'c', text: 'Parce qu\'il produit de l\'électricité pour l\'Afrique', isCorrect: false },
      { id: 'd', text: 'Parce qu\'il permet aux avions de traverser l\'Égypte plus vite', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le canal de Suez, creusé en Égypte, relie la mer Méditerranée à la mer Rouge. Il évite aux navires de faire le tour de l\'Afrique, économisant des milliers de kilomètres.',
    hint: 'Il traverse l\'Égypte de nord en sud.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-011',
    subject: 'histoire_geo',
    title: 'Les flux touristiques',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel pays est le plus visité au monde par les touristes ?',
    options: [
      { id: 'a', text: 'Les États-Unis', isCorrect: false },
      { id: 'b', text: 'L\'Espagne', isCorrect: false },
      { id: 'c', text: 'La France', isCorrect: true },
      { id: 'd', text: 'La Chine', isCorrect: false },
    ],
    correctAnswer: 'c',
    explanation: 'La France est régulièrement le pays le plus visité au monde avec environ 90 millions de touristes par an, grâce à Paris, ses châteaux, ses côtes et sa gastronomie.',
    hint: 'Paris est l\'une des villes les plus visitées au monde.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-012',
    subject: 'histoire_geo',
    title: 'Les réseaux de transport en France',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel moyen de transport permet de relier Paris à Lyon en moins de 2 heures ?',
    options: [
      { id: 'a', text: 'La voiture sur autoroute', isCorrect: false },
      { id: 'b', text: 'Le TGV', isCorrect: true },
      { id: 'c', text: 'L\'avion', isCorrect: false },
      { id: 'd', text: 'Le vélo', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le TGV (Train à Grande Vitesse) relie Paris à Lyon en environ 1h50, contre 4h en voiture. La France possède l\'un des réseaux de trains à grande vitesse les plus étendus d\'Europe.',
    hint: 'Ce train peut dépasser 300 km/h.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-013',
    subject: 'histoire_geo',
    title: 'Le pétrole et les échanges',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où provient la majorité du pétrole utilisé en Europe ?',
    options: [
      { id: 'a', text: 'De l\'Arctique', isCorrect: false },
      { id: 'b', text: 'Du Moyen-Orient et de Russie principalement', isCorrect: true },
      { id: 'c', text: 'De la mer du Nord uniquement', isCorrect: false },
      { id: 'd', text: 'De l\'Amérique du Sud', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'Europe importe la majorité de son pétrole du Moyen-Orient (Arabie saoudite, Irak) et de Russie. Ce pétrole voyage par tankers ou par oléoducs (pipelines).',
    hint: 'Le Golfe Persique et la Russie sont d\'importants producteurs.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-014',
    subject: 'histoire_geo',
    title: 'Les inégalités face aux échanges',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi tous les pays ne profitent-ils pas de la même façon du commerce mondial ?',
    options: [
      { id: 'a', text: 'Parce que certains pays n\'ont pas accès à la mer', isCorrect: false },
      { id: 'b', text: 'Parce que les pays riches ont plus de moyens de transport, de technologies et de capitaux pour participer aux échanges', isCorrect: true },
      { id: 'c', text: 'Parce que le commerce mondial est interdit aux pays pauvres', isCorrect: false },
      { id: 'd', text: 'Parce que les pays pauvres n\'ont pas de produits à vendre', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les inégalités face au commerce mondial s\'expliquent par les différences de moyens : les pays riches ont de meilleures infrastructures, technologies et accès aux capitaux, ce qui leur donne un avantage.',
    hint: 'Imagine deux marchands : l\'un avec une boutique moderne, l\'autre sans moyen de transport.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm1-geo-flx-015',
    subject: 'histoire_geo',
    title: 'Commerce équitable',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'flux et échanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le commerce équitable ?',
    options: [
      { id: 'a', text: 'Un commerce qui vend des produits au même prix partout dans le monde', isCorrect: false },
      { id: 'b', text: 'Un système qui garantit un prix juste aux producteurs des pays pauvres pour leurs produits', isCorrect: true },
      { id: 'c', text: 'Un commerce qui n\'utilise que des produits locaux', isCorrect: false },
      { id: 'd', text: 'Un marché où les clients peuvent négocier les prix', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le commerce équitable garantit aux agriculteurs et artisans des pays pauvres un prix juste pour leurs produits (café, cacao, coton…), leur permettant de vivre dignement.',
    hint: 'Le logo Max Havelaar sur certains produits est un signe de commerce équitable.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
