import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm1HistoireVieQuotidienneExercises: HgExercise[] = [

  {
    id: 'hg-cm1-hist-vq-001',
    subject: 'histoire_geo',
    title: "La vie dans un village médiéval",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au Moyen Âge, la majorité de la population vivait dans des villages. Quelle était l'activité principale de ces villageois ?",
    options: [
      { id: 'a', text: "Le commerce maritime", isCorrect: false },
      { id: 'b', text: "L'agriculture : cultiver la terre du seigneur et la leur", isCorrect: true },
      { id: 'c', text: "La fabrication d'automobiles", isCorrect: false },
      { id: 'd', text: "La pêche en haute mer", isCorrect: false },
    ],
    correctAnswer: "L'agriculture : cultiver la terre du seigneur et la leur",
    explanation: "Au Moyen Âge, environ 90 % de la population était paysanne. Ils cultivaient les terres du seigneur (corvées) et leurs propres terres pour se nourrir. La vie était rythmée par les saisons et les fêtes religieuses.",
    hint: "90 % de la population médiévale = paysans = agriculteurs.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-002',
    subject: 'histoire_geo',
    title: "Les foires médiévales",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les grandes foires médiévales (ex. : foires de Champagne, XIIe-XIIIe s.) étaient des événements importants. Pourquoi ?",
    options: [
      { id: 'a', text: "C'était des tournois militaires entre chevaliers", isCorrect: false },
      { id: 'b', text: "C'était des lieux d'échanges commerciaux internationaux où se retrouvaient marchands d'Europe et d'Orient", isCorrect: true },
      { id: 'c', text: "C'était des marchés réservés aux nobles uniquement", isCorrect: false },
      { id: 'd', text: "C'était des spectacles de jongleurs et acrobates uniquement", isCorrect: false },
    ],
    correctAnswer: "C'était des lieux d'échanges commerciaux internationaux où se retrouvaient marchands d'Europe et d'Orient",
    explanation: "Les foires de Champagne (Troyes, Provins, Lagny…) attiraient des marchands italiens, flamands, allemands et orientaux. On y échangeait draps, épices, fourrures et métaux précieux.",
    hint: "Foires de Champagne = commerce international = marchands d'Europe et d'Orient.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-003',
    subject: 'histoire_geo',
    title: "La santé au Moyen Âge",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Peste noire (1347-1351) a tué environ un tiers de la population européenne. Comment se propageait-elle ?",
    options: [
      { id: 'a', text: "Par l'air uniquement", isCorrect: false },
      { id: 'b', text: "Par les puces des rats (bactérie Yersinia pestis), mais aussi par voie aérienne (forme pulmonaire)", isCorrect: true },
      { id: 'c', text: "Par l'eau des rivières uniquement", isCorrect: false },
      { id: 'd', text: "Par les oiseaux migrateurs", isCorrect: false },
    ],
    correctAnswer: "Par les puces des rats (bactérie Yersinia pestis), mais aussi par voie aérienne (forme pulmonaire)",
    explanation: "La Peste noire était causée par la bactérie Yersinia pestis, transmise par les puces des rats noirs. Elle arriva en Europe par les navires génois depuis la Crimée. Elle dévasta 25-30 millions d'Européens.",
    hint: "Peste noire 1347 = puces de rats → humains. 1/3 de l'Europe décimé.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-004',
    subject: 'histoire_geo',
    title: "L'imprimerie et ses effets",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Gutenberg invente l'imprimerie à caractères mobiles vers 1450. Quel effet majeur cela a-t-il sur la société ?",
    options: [
      { id: 'a', text: "Les livres disparaissent car plus personne ne sait écrire", isCorrect: false },
      { id: 'b', text: "Les livres se multiplient et deviennent moins chers, diffusant les idées plus rapidement", isCorrect: true },
      { id: 'c', text: "Seuls les rois ont accès aux livres imprimés", isCorrect: false },
      { id: 'd', text: "L'imprimerie remplace l'écriture à la main partout immédiatement", isCorrect: false },
    ],
    correctAnswer: "Les livres se multiplient et deviennent moins chers, diffusant les idées plus rapidement",
    explanation: "Avant Gutenberg, un livre copiait à la main pouvait prendre des mois. Avec l'imprimerie, on produit des centaines d'exemplaires identiques. Les idées (humanisme, Réforme…) se diffusent bien plus vite.",
    hint: "Gutenberg 1450 = livres en série = idées diffusées rapidement = révolution culturelle.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-005',
    subject: 'histoire_geo',
    title: "Les métiers au Moyen Âge",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au Moyen Âge, les artisans d'un même métier se regroupaient en « corporations » ou « guildes ». Quel était leur rôle principal ?",
    options: [
      { id: 'a', text: "Espionner les marchands étrangers", isCorrect: false },
      { id: 'b', text: "Réglementer l'apprentissage du métier, contrôler la qualité et réguler les prix", isCorrect: true },
      { id: 'c', text: "Organiser des fêtes pour les nobles", isCorrect: false },
      { id: 'd', text: "Collecter les impôts pour le seigneur", isCorrect: false },
    ],
    correctAnswer: "Réglementer l'apprentissage du métier, contrôler la qualité et réguler les prix",
    explanation: "Les corporations médiévales regroupaient les artisans d'un même métier (boulangers, drapiers, orfèvres…). Elles fixaient les règles d'apprentissage (apprenti → compagnon → maître), contrôlaient la qualité et limitaient la concurrence.",
    hint: "Corporations = groupements d'artisans = règles du métier, qualité, prix.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-006',
    subject: 'histoire_geo',
    title: "Versailles : le quotidien du roi",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_ancien_regime',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "À Versailles, le réveil de Louis XIV (le « lever du roi ») était une cérémonie publique. À quoi servait-elle politiquement ?",
    options: [
      { id: 'a', text: "À montrer que le roi était en bonne santé et à contrôler l'accès à sa personne", isCorrect: true },
      { id: 'b', text: "À distraire les paysans du village voisin", isCorrect: false },
      { id: 'c', text: "À permettre aux nobles de dormir dans la chambre du roi", isCorrect: false },
      { id: 'd', text: "À prouver que le roi se levait tôt pour travailler", isCorrect: false },
    ],
    correctAnswer: "À montrer que le roi était en bonne santé et à contrôler l'accès à sa personne",
    explanation: "Le lever du roi était codifié : certains nobles avaient le privilège d'y assister. C'était un outil politique : ceux admis montraient leur faveur royale. Cela montrait aussi la santé et la puissance du roi.",
    hint: "Lever du roi = cérémonie politique = montrer faveur royale + santé du roi.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-007',
    subject: 'histoire_geo',
    title: "La vie des soldats napoléoniens",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_epoque_contemporaine',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les soldats de Napoléon marchaient à pied sur des centaines de kilomètres. Quelle était leur principale souffrance lors de la retraite de Russie (1812) ?",
    options: [
      { id: 'a', text: "Le manque de divertissements", isCorrect: false },
      { id: 'b', text: "Le froid intense, la faim et l'épuisement lors du long retrait à travers la Russie en hiver", isCorrect: true },
      { id: 'c', text: "L'absence de fusils", isCorrect: false },
      { id: 'd', text: "L'impossibilité de rentrer en France par bateau", isCorrect: false },
    ],
    correctAnswer: "Le froid intense, la faim et l'épuisement lors du long retrait à travers la Russie en hiver",
    explanation: "La campagne de Russie (1812) fut une catastrophe. La Grande Armée de 600 000 hommes fut décimée par le froid sibérien (-30°C), la faim (les Russes brûlaient leurs réserves) et les maladies. Moins de 100 000 revinrent.",
    hint: "Retraite de Russie 1812 = froid + faim + épuisement = catastrophe militaire.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-008',
    subject: 'histoire_geo',
    title: "La vie ouvrière au XIXe siècle",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_epoque_contemporaine',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Dans les usines du XIXe siècle, les ouvriers travaillaient souvent 12 à 14 heures par jour. Quelle loi a limité cela en France ?",
    options: [
      { id: 'a', text: "La loi de Jules Ferry sur l'école (1882)", isCorrect: false },
      { id: 'b', text: "La loi de 1848 limitant le travail à 12h par jour", isCorrect: true },
      { id: 'c', text: "La Constitution de 1958", isCorrect: false },
      { id: 'd', text: "Le Code civil de 1804 uniquement", isCorrect: false },
    ],
    correctAnswer: "La loi de 1848 limitant le travail à 12h par jour",
    explanation: "En 1848, la IIe République vota une loi limitant la durée du travail à 12 heures par jour pour les adultes. C'était déjà un progrès immense. La journée de 8 heures ne sera conquise qu'en 1919.",
    hint: "1848 = IIe République = loi 12h max de travail. 8h seulement en 1919.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-009',
    subject: 'histoire_geo',
    title: "L'hygiène dans le passé",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Contrairement à la légende, les gens du Moyen Âge ne refusaient pas de se laver. Comment se lavaient-ils ?",
    options: [
      { id: 'a', text: "Ils ne se lavaient jamais par peur de l'eau", isCorrect: false },
      { id: 'b', text: "Ils utilisaient des bains publics (étuves), lavaient leurs mains avant les repas et se nettoyaient régulièrement", isCorrect: true },
      { id: 'c', text: "Ils se douchaient chaque matin avec de l'eau froide courante", isCorrect: false },
      { id: 'd', text: "Ils ne se lavaient qu'une fois par an au bain de rivière", isCorrect: false },
    ],
    correctAnswer: "Ils utilisaient des bains publics (étuves), lavaient leurs mains avant les repas et se nettoyaient régulièrement",
    explanation: "La légende du Moyen Âge sale est fausse. Les villes médiévales avaient des étuves (bains publics). Les gens se lavaient les mains avant les repas. L'hygiène médiévale était différente de la nôtre mais pas absente.",
    hint: "Moyen Âge ≠ pas de lavage. Étuves = bains publics médiévaux.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-010',
    subject: 'histoire_geo',
    title: "Les femmes au Moyen Âge",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au Moyen Âge, quelle activité était principalement réservée aux femmes nobles ?",
    options: [
      { id: 'a', text: "Diriger les armées à la place des hommes", isCorrect: false },
      { id: 'b', text: "Gérer le château et l'économie domestique, pratiquer la broderie et surveiller l'éducation des enfants", isCorrect: true },
      { id: 'c', text: "Travailler dans les mines", isCorrect: false },
      { id: 'd', text: "Rédiger les lois du royaume", isCorrect: false },
    ],
    correctAnswer: "Gérer le château et l'économie domestique, pratiquer la broderie et surveiller l'éducation des enfants",
    explanation: "Les femmes nobles géraient le château et les domaines quand leur époux était absent en guerre. Elles supervisaient les domestiques, éduquaient les enfants et pratiquaient des activités artistiques comme la broderie.",
    hint: "Femme noble médiévale = gérer le domaine + éducation enfants + broderie.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-011',
    subject: 'histoire_geo',
    title: "Les cathédrales gothiques",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La construction d'une cathédrale gothique au Moyen Âge pouvait durer plusieurs siècles. Qui y participait ?",
    options: [
      { id: 'a', text: "Uniquement des esclaves comme dans l'Antiquité", isCorrect: false },
      { id: 'b', text: "Des artisans spécialisés (tailleurs de pierre, charpentiers, verriers) payés et organisés par les évêques", isCorrect: true },
      { id: 'c', text: "Uniquement des moines dans le secret des monastères", isCorrect: false },
      { id: 'd', text: "Les rois seuls finançaient et construisaient les cathédrales", isCorrect: false },
    ],
    correctAnswer: "Des artisans spécialisés (tailleurs de pierre, charpentiers, verriers) payés et organisés par les évêques",
    explanation: "Les cathédrales mobilisaient des centaines d'artisans qualifiés et libres : maîtres d'œuvre, tailleurs de pierre, charpentiers, verriers (vitraux), sculpteurs. Elles étaient financées par l'évêché, les nobles et les fidèles.",
    hint: "Cathédrale gothique = artisans spécialisés + financement évêché + plusieurs siècles.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-012',
    subject: 'histoire_geo',
    title: "L'alimentation à la Renaissance",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "À la Renaissance (XVe-XVIe siècle), quels nouveaux aliments arrivèrent d'Amérique en Europe ?",
    options: [
      { id: 'a', text: "Le blé et le riz", isCorrect: false },
      { id: 'b', text: "La tomate, la pomme de terre, le maïs et le chocolat", isCorrect: true },
      { id: 'c', text: "Le beurre et le fromage", isCorrect: false },
      { id: 'd', text: "Le pain et le vin", isCorrect: false },
    ],
    correctAnswer: "La tomate, la pomme de terre, le maïs et le chocolat",
    explanation: "La découverte de l'Amérique (1492) provoqua un « échange colombien » : l'Europe reçut tomate, pomme de terre, maïs, chocolat, piments, haricots. En retour, l'Amérique reçut blé, chevaux et maladies européennes.",
    hint: "Échange colombien = Amérique → Europe : tomate, pomme de terre, maïs, chocolat.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-013',
    subject: 'histoire_geo',
    title: "La famille au XIXe siècle",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_epoque_contemporaine',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au XIXe siècle, les familles ouvrières étaient souvent nombreuses. Pourquoi avaient-elles beaucoup d'enfants ?",
    options: [
      { id: 'a', text: "Parce que les enfants travaillaient et rapportaient de l'argent", isCorrect: false },
      { id: 'b', text: "Parce que la mortalité infantile était élevée et les enfants étaient une aide pour les parents âgés", isCorrect: true },
      { id: 'c', text: "Parce que le gouvernement obligeait les familles à avoir beaucoup d'enfants", isCorrect: false },
      { id: 'd', text: "Parce qu'il n'y avait rien d'autre à faire le soir", isCorrect: false },
    ],
    correctAnswer: "Parce que la mortalité infantile était élevée et les enfants étaient une aide pour les parents âgés",
    explanation: "Au XIXe s., beaucoup d'enfants mouraient en bas âge (maladies, malnutrition). Les familles nombreuses compensaient cette mortalité. Les enfants aidaient aussi aux travaux et assuraient la vieillesse des parents.",
    hint: "XIXe s. = mortalité infantile élevée + enfants = aide future → familles nombreuses.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-014',
    subject: 'histoire_geo',
    title: "Les loisirs au fil du temps",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_comparaison',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Avant la télévision et Internet, comment les gens passaient-ils leurs soirées et leurs temps libres ?",
    options: [
      { id: 'a', text: "Ils ne faisaient rien car le travail occupait tout leur temps", isCorrect: false },
      { id: 'b', text: "Jeux de société, lecture à voix haute, musique, danse, spectacles (théâtre, cirque) et réunions entre voisins", isCorrect: true },
      { id: 'c', text: "Uniquement des activités sportives à l'extérieur", isCorrect: false },
      { id: 'd', text: "Ils dormaient dès la nuit tombée", isCorrect: false },
    ],
    correctAnswer: "Jeux de société, lecture à voix haute, musique, danse, spectacles (théâtre, cirque) et réunions entre voisins",
    explanation: "Avant la radio et la télé, les loisirs étaient collectifs : on lisait à voix haute en famille, on jouait (cartes, échecs, osselets), on allait au théâtre ou au cirque, on organisait des bals et des veillées.",
    hint: "Avant TV/Internet = loisirs collectifs et actifs : jeux, musique, spectacles, réunions.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-vq-015',
    subject: 'histoire_geo',
    title: "Comparer les sociétés",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'vie_quotidienne_comparaison',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la principale différence entre la vie d'un enfant au Moyen Âge et celle d'un enfant aujourd'hui en France ?",
    options: [
      { id: 'a', text: "Les enfants du Moyen Âge jouaient beaucoup plus que ceux d'aujourd'hui", isCorrect: false },
      { id: 'b', text: "Aujourd'hui, l'école est obligatoire et le travail des enfants est interdit, alors qu'au Moyen Âge beaucoup travaillaient jeunes", isCorrect: true },
      { id: 'c', text: "Les enfants du Moyen Âge avaient plus de jouets", isCorrect: false },
      { id: 'd', text: "La vie des enfants était exactement la même", isCorrect: false },
    ],
    correctAnswer: "Aujourd'hui, l'école est obligatoire et le travail des enfants est interdit, alors qu'au Moyen Âge beaucoup travaillaient jeunes",
    explanation: "Au Moyen Âge, les enfants pauvres aidaient aux travaux des champs dès 6-7 ans. L'école n'existait pas pour tous. Aujourd'hui, l'école est obligatoire jusqu'à 16 ans et le travail des mineurs est très réglementé.",
    hint: "Enfant médiéval = travail jeune. Enfant d'aujourd'hui = école obligatoire + travail interdit.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
