import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm1GeoEuropeExercises: HgExercise[] = [

  {
    id: 'hg-cm1-geo-eur-001',
    subject: 'histoire_geo',
    title: "L'Union européenne : quand et comment ?",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Union européenne (UE) a été officiellement créée par le traité de Maastricht en 1992. Combien de pays membres compte-t-elle en 2024 ?",
    options: [
      { id: 'a', text: "6 pays", isCorrect: false },
      { id: 'b', text: "27 pays", isCorrect: true },
      { id: 'c', text: "50 pays", isCorrect: false },
      { id: 'd', text: "15 pays", isCorrect: false },
    ],
    correctAnswer: "27 pays",
    explanation: "L'UE comptait 28 membres, mais le Royaume-Uni l'a quittée en 2020 (Brexit). Elle compte désormais 27 membres. Elle a débuté avec 6 pays fondateurs en 1957 (traité de Rome).",
    hint: "UE 2024 = 27 membres. Le Royaume-Uni est parti en 2020 (Brexit).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-002',
    subject: 'histoire_geo',
    title: "L'euro",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'euro est la monnaie commune de nombreux pays de l'UE. Combien de pays de l'UE utilisent l'euro ?",
    options: [
      { id: 'a', text: "Tous les 27 membres de l'UE", isCorrect: false },
      { id: 'b', text: "20 pays (zone euro en 2024)", isCorrect: true },
      { id: 'c', text: "Seulement 5 pays", isCorrect: false },
      { id: 'd', text: "Aucun, chaque pays a sa propre monnaie", isCorrect: false },
    ],
    correctAnswer: "20 pays (zone euro en 2024)",
    explanation: "20 des 27 pays de l'UE utilisent l'euro (zone euro). Les autres membres gardent leur monnaie nationale (Suède, Danemark, Pologne, Tchéquie, Hongrie…). L'euro a été créé en 1999 (billets et pièces en 2002).",
    hint: "Zone euro = 20 pays en 2024. Pas tous les membres de l'UE.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-003',
    subject: 'histoire_geo',
    title: "Les institutions de l'UE",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Parlement européen est élu par les citoyens européens. Dans quelle ville principale siège-t-il ?",
    options: [
      { id: 'a', text: "Paris", isCorrect: false },
      { id: 'b', text: "Strasbourg (et Bruxelles)", isCorrect: true },
      { id: 'c', text: "Berlin", isCorrect: false },
      { id: 'd', text: "Genève", isCorrect: false },
    ],
    correctAnswer: "Strasbourg (et Bruxelles)",
    explanation: "Le Parlement européen siège principalement à Strasbourg (France) pour les séances plénières, mais ses commissions et son secrétariat sont aussi à Bruxelles. La Commission européenne est à Bruxelles.",
    hint: "Parlement européen = Strasbourg (plénière) + Bruxelles (commissions).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-004',
    subject: 'histoire_geo',
    title: "Les pays fondateurs de l'Europe",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Six pays fondent la CEE (Communauté Économique Européenne) en 1957. Parmi ces groupes, lequel représente les 6 fondateurs ?",
    options: [
      { id: 'a', text: "France, Allemagne, Italie, Espagne, Portugal, Grèce", isCorrect: false },
      { id: 'b', text: "France, Allemagne de l'Ouest, Italie, Belgique, Pays-Bas, Luxembourg", isCorrect: true },
      { id: 'c', text: "France, Royaume-Uni, Allemagne, Italie, Espagne, Pologne", isCorrect: false },
      { id: 'd', text: "France, Suisse, Autriche, Hongrie, Tchéquie, Slovaquie", isCorrect: false },
    ],
    correctAnswer: "France, Allemagne de l'Ouest, Italie, Belgique, Pays-Bas, Luxembourg",
    explanation: "Les 6 pays fondateurs de la CEE (1957) sont : France, Allemagne de l'Ouest, Italie + Bénélux (Belgique, Pays-Bas, Luxembourg). Le Royaume-Uni n'a rejoint qu'en 1973.",
    hint: "6 fondateurs 1957 = France + Allemagne + Italie + Bénélux (Belgique, Pays-Bas, Luxembourg).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-005',
    subject: 'histoire_geo',
    title: "Les capitales européennes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la capitale de la Pologne, grand pays d'Europe centrale ?",
    options: [
      { id: 'a', text: "Cracovie", isCorrect: false },
      { id: 'b', text: "Varsovie", isCorrect: true },
      { id: 'c', text: "Prague", isCorrect: false },
      { id: 'd', text: "Budapest", isCorrect: false },
    ],
    correctAnswer: "Varsovie",
    explanation: "Varsovie est la capitale de la Pologne, le plus grand pays d'Europe centrale. Cracovie est l'ancienne capitale. Prague est la capitale de la Tchéquie, Budapest celle de la Hongrie.",
    hint: "Varsovie = capitale de la Pologne. Cracovie = ancienne capitale.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-006',
    subject: 'histoire_geo',
    title: "La libre circulation en Europe",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'espace Schengen permet aux citoyens européens de circuler librement entre les pays membres. Qu'est-ce que cela signifie concrètement ?",
    options: [
      { id: 'a', text: "On peut traverser les frontières sans passeport ni contrôle", isCorrect: true },
      { id: 'b', text: "On doit obligatoirement avoir un visa pour chaque pays", isCorrect: false },
      { id: 'c', text: "On ne peut se déplacer qu'en train", isCorrect: false },
      { id: 'd', text: "La libre circulation concerne uniquement les marchandises", isCorrect: false },
    ],
    correctAnswer: "On peut traverser les frontières sans passeport ni contrôle",
    explanation: "L'espace Schengen (26 pays) permet de circuler librement sans contrôle aux frontières intérieures. Un Français peut aller en Allemagne ou en Espagne sans montrer son passeport. C'est une réalisation majeure de l'UE.",
    hint: "Schengen = frontières ouvertes = circuler sans passeport en Europe.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-007',
    subject: 'histoire_geo',
    title: "Le relief européen",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les grandes chaînes de montagnes européennes se trouvent surtout…",
    options: [
      { id: 'a', text: "Au nord de l'Europe (Scandinavie)", isCorrect: false },
      { id: 'b', text: "Au sud de l'Europe (Alpes, Pyrénées, Apennins, Carpates)", isCorrect: true },
      { id: 'c', text: "À l'ouest de l'Europe uniquement (Îles Britanniques)", isCorrect: false },
      { id: 'd', text: "Au centre de l'Europe dans les grandes plaines", isCorrect: false },
    ],
    correctAnswer: "Au sud de l'Europe (Alpes, Pyrénées, Apennins, Carpates)",
    explanation: "Les principales chaînes de montagnes européennes sont au sud : Alpes (France/Suisse/Italie/Autriche), Pyrénées (France/Espagne), Apennins (Italie), Carpates (Europe centrale), Balkans (sud-est). Le nord est plus plat.",
    hint: "Montagnes européennes = surtout au sud. Alpes, Pyrénées, Apennins, Carpates.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-008',
    subject: 'histoire_geo',
    title: "Les grandes plaines d'Europe",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La grande plaine d'Europe du Nord s'étend de la France aux plaines russes. Dans quels domaines est-elle importante ?",
    options: [
      { id: 'a', text: "Principalement pour l'extraction minière", isCorrect: false },
      { id: 'b', text: "Pour l'agriculture intensive (céréales, betteraves, élevage) et les grandes villes industrielles", isCorrect: true },
      { id: 'c', text: "Pour le tourisme de montagne", isCorrect: false },
      { id: 'd', text: "Pour la pêche en haute mer", isCorrect: false },
    ],
    correctAnswer: "Pour l'agriculture intensive (céréales, betteraves, élevage) et les grandes villes industrielles",
    explanation: "La grande plaine d'Europe du Nord (des Pays-Bas à la Russie) est très fertile. Elle accueille une agriculture productive (blé, betteraves, élevage) et de grandes villes industrielles (Paris, Bruxelles, Hambourg, Berlin).",
    hint: "Grande plaine nord-européenne = agriculture productive + grandes villes industrielles.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-009',
    subject: 'histoire_geo',
    title: "Les fleuves européens",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Danube est le deuxième plus long fleuve d'Europe. Combien de pays traverse-t-il ?",
    options: [
      { id: 'a', text: "2 pays", isCorrect: false },
      { id: 'b', text: "10 pays", isCorrect: true },
      { id: 'c', text: "4 pays", isCorrect: false },
      { id: 'd', text: "20 pays", isCorrect: false },
    ],
    correctAnswer: "10 pays",
    explanation: "Le Danube (2 850 km) traverse ou borde 10 pays : Allemagne, Autriche, Slovaquie, Hongrie, Croatie, Serbie, Roumanie, Bulgarie, Moldova, Ukraine. Il se jette dans la mer Noire.",
    hint: "Danube = 10 pays traversés, de l'Allemagne à la mer Noire.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-010',
    subject: 'histoire_geo',
    title: "Les mers européennes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Europe est entourée de plusieurs mers et océans. Laquelle de ces mers borde l'Europe du Nord ?",
    options: [
      { id: 'a', text: "La mer Méditerranée", isCorrect: false },
      { id: 'b', text: "La mer Baltique", isCorrect: true },
      { id: 'c', text: "La mer Noire", isCorrect: false },
      { id: 'd', text: "La mer Rouge", isCorrect: false },
    ],
    correctAnswer: "La mer Baltique",
    explanation: "La mer Baltique borde la Scandinavie, la Finlande, les pays baltes (Estonie, Lettonie, Lituanie), la Pologne et l'Allemagne. C'est une mer peu salée (apports d'eau douce importants).",
    hint: "Mer Baltique = nord de l'Europe (Scandinavie, pays baltes, Pologne, Allemagne).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-011',
    subject: 'histoire_geo',
    title: "Les pays baltes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les pays baltes (Estonie, Lettonie, Lituanie) sont de petits pays d'Europe du Nord. À quelle grande organisation appartiennent-ils ?",
    options: [
      { id: 'a', text: "À la Communauté des États Indépendants (ancienne URSS)", isCorrect: false },
      { id: 'b', text: "À l'Union européenne et à l'OTAN", isCorrect: true },
      { id: 'c', text: "À aucune organisation internationale", isCorrect: false },
      { id: 'd', text: "Uniquement à l'ONU", isCorrect: false },
    ],
    correctAnswer: "À l'Union européenne et à l'OTAN",
    explanation: "Les trois pays baltes ont intégré l'UE et l'OTAN (alliance militaire) en 2004. Après avoir appartenu à l'URSS (1940-1991), leur adhésion symbolise leur ancrage dans le bloc occidental.",
    hint: "Pays baltes = ex-URSS + intégration UE et OTAN en 2004.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-012',
    subject: 'histoire_geo',
    title: "La péninsule ibérique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La péninsule ibérique est une grande péninsule au sud-ouest de l'Europe. Quels pays l'occupent ?",
    options: [
      { id: 'a', text: "La France et l'Italie", isCorrect: false },
      { id: 'b', text: "L'Espagne et le Portugal", isCorrect: true },
      { id: 'c', text: "La Grèce et la Turquie", isCorrect: false },
      { id: 'd', text: "La Suisse et l'Autriche", isCorrect: false },
    ],
    correctAnswer: "L'Espagne et le Portugal",
    explanation: "La péninsule ibérique est occupée par l'Espagne (80 %) et le Portugal (20 %), avec la petite principauté d'Andorre dans les Pyrénées. Elle est bordée par l'Atlantique à l'ouest et la Méditerranée à l'est.",
    hint: "Péninsule ibérique = Espagne + Portugal (+ Andorre). Sud-ouest de l'Europe.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-013',
    subject: 'histoire_geo',
    title: "Le Brexit",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Brexit (2016-2020) est la sortie du Royaume-Uni de l'Union européenne. Quelle en est la conséquence principale pour les Britanniques ?",
    options: [
      { id: 'a', text: "Ils peuvent maintenant circuler plus librement en Europe", isCorrect: false },
      { id: 'b', text: "Ils ont perdu le droit de circuler et travailler librement dans l'UE et doivent un passeport pour entrer dans l'UE", isCorrect: true },
      { id: 'c', text: "Ils ont rejoint l'espace Schengen", isCorrect: false },
      { id: 'd', text: "Rien n'a changé pour les citoyens britanniques", isCorrect: false },
    ],
    correctAnswer: "Ils ont perdu le droit de circuler et travailler librement dans l'UE et doivent un passeport pour entrer dans l'UE",
    explanation: "Depuis le Brexit (effectif le 31 janvier 2020), les Britanniques ne peuvent plus circuler et s'installer librement dans l'UE. Ils ont besoin d'un visa pour travailler en Europe et les échanges commerciaux sont plus complexes.",
    hint: "Brexit = Royaume-Uni quitte l'UE → fin libre circulation → passeport obligatoire.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-014',
    subject: 'histoire_geo',
    title: "L'hymne européen",
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'hymne de l'Union européenne est adapté de la 9e symphonie d'un grand compositeur. De qui s'agit-il ?",
    options: [
      { id: 'a', text: "Wolfgang Amadeus Mozart", isCorrect: false },
      { id: 'b', text: "Ludwig van Beethoven", isCorrect: true },
      { id: 'c', text: "Johann Sebastian Bach", isCorrect: false },
      { id: 'd', text: "Frédéric Chopin", isCorrect: false },
    ],
    correctAnswer: "Ludwig van Beethoven",
    explanation: "L'Hymne à la joie est tiré de la 9e symphonie de Beethoven (1824). Adopté par le Conseil de l'Europe en 1972, puis par l'UE, il symbolise les valeurs communes des Européens : liberté, paix, solidarité.",
    hint: "Hymne européen = Hymne à la joie = Beethoven, 9e symphonie (1824).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-eur-015',
    subject: 'histoire_geo',
    title: "Localiser des pays européens",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'europe',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel pays européen est une péninsule scandinave au nord-ouest, avec une longue côte découpée de fjords donnant sur l'océan Atlantique ?",
    options: [
      { id: 'a', text: "La Finlande", isCorrect: false },
      { id: 'b', text: "La Norvège", isCorrect: true },
      { id: 'c', text: "La Suède", isCorrect: false },
      { id: 'd', text: "Le Danemark", isCorrect: false },
    ],
    correctAnswer: "La Norvège",
    explanation: "La Norvège est située à l'ouest de la péninsule scandinave. Sa côte atlantique est découpée de milliers de fjords (bras de mer étroits et profonds). Sa capitale est Oslo.",
    hint: "Norvège = côte ouest de la Scandinavie + fjords + Atlantique. Capitale : Oslo.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
