import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm1GeoReliefsClimatsExercises: HgExercise[] = [

  {
    id: 'hg-cm1-geo-rls-001',
    subject: 'histoire_geo',
    title: "Les grandes zones climatiques",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Terre possède plusieurs zones climatiques. Laquelle de ces zones se trouve autour de l'équateur ?",
    options: [
      { id: 'a', text: "La zone polaire", isCorrect: false },
      { id: 'b', text: "La zone intertropicale (chaude et humide)", isCorrect: true },
      { id: 'c', text: "La zone tempérée", isCorrect: false },
      { id: 'd', text: "La zone froide", isCorrect: false },
    ],
    correctAnswer: "La zone intertropicale (chaude et humide)",
    explanation: "La zone intertropicale (entre les tropiques du Cancer et du Capricorne) est chaude et souvent humide toute l'année. On y trouve les forêts tropicales (Amazonie, Afrique centrale, Asie du Sud-Est).",
    hint: "Équateur = zone intertropicale = chaud et humide toute l'année.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-002',
    subject: 'histoire_geo',
    title: "Le climat méditerranéen",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le climat méditerranéen (sud de la France, Espagne, Italie, Grèce) est caractérisé par…",
    options: [
      { id: 'a', text: "Des hivers très froids et des étés frais", isCorrect: false },
      { id: 'b', text: "Des étés chauds et secs, des hivers doux et humides", isCorrect: true },
      { id: 'c', text: "Des pluies abondantes toute l'année", isCorrect: false },
      { id: 'd', text: "Un froid intense en toutes saisons", isCorrect: false },
    ],
    correctAnswer: "Des étés chauds et secs, des hivers doux et humides",
    explanation: "Le climat méditerranéen se caractérise par des étés chauds et secs (peu de pluies) et des hivers doux et pluvieux. Cette saisonnalité inversée par rapport aux pluies est typique du bassin méditerranéen.",
    hint: "Méditerranéen = étés secs et chauds + hivers doux et pluvieux.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-003',
    subject: 'histoire_geo',
    title: "Les déserts dans le monde",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Qu'est-ce qu'un désert en géographie ?",
    options: [
      { id: 'a', text: "Un endroit sans aucun être vivant", isCorrect: false },
      { id: 'b', text: "Une zone qui reçoit moins de 250 mm de précipitations par an", isCorrect: true },
      { id: 'c', text: "Un endroit uniquement couvert de sable", isCorrect: false },
      { id: 'd', text: "Une zone sans relief", isCorrect: false },
    ],
    correctAnswer: "Une zone qui reçoit moins de 250 mm de précipitations par an",
    explanation: "Un désert est défini par ses faibles précipitations (< 250 mm/an). L'Antarctique est le plus grand désert du monde (froid et sec). Le Sahara est le plus grand désert chaud. Les déserts ne sont pas tous de sable.",
    hint: "Désert = moins de 250 mm de pluie par an. Peut être chaud (Sahara) ou froid (Antarctique).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-004',
    subject: 'histoire_geo',
    title: "La forêt tropicale humide",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La forêt tropicale humide (forêt équatoriale) est très riche en biodiversité. Pourquoi pousse-t-elle aussi dense ?",
    options: [
      { id: 'a', text: "Grâce aux températures froides qui favorisent la croissance", isCorrect: false },
      { id: 'b', text: "Grâce à une chaleur constante et des pluies abondantes toute l'année", isCorrect: true },
      { id: 'c', text: "Grâce aux sols très secs qui forcent les plantes à pousser vite", isCorrect: false },
      { id: 'd', text: "Grâce à l'absence totale de vent", isCorrect: false },
    ],
    correctAnswer: "Grâce à une chaleur constante et des pluies abondantes toute l'année",
    explanation: "La forêt tropicale humide pousse dans des conditions idéales : chaleur constante (25-30°C), pluies abondantes (> 2 000 mm/an) et lumière intense. Ces conditions favorisent une croissance rapide et une biodiversité exceptionnelle.",
    hint: "Forêt tropicale = chaleur + pluies toute l'année = conditions idéales de croissance.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-005',
    subject: 'histoire_geo',
    title: "Les montagnes les plus hautes du monde",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle chaîne de montagnes abrite les plus hauts sommets du monde, dont l'Everest (8 849 m) ?",
    options: [
      { id: 'a', text: "Les Alpes", isCorrect: false },
      { id: 'b', text: "L'Himalaya", isCorrect: true },
      { id: 'c', text: "Les Andes", isCorrect: false },
      { id: 'd', text: "Les Appalaches", isCorrect: false },
    ],
    correctAnswer: "L'Himalaya",
    explanation: "L'Himalaya est la chaîne de montagnes la plus haute du monde, en Asie du Sud (entre Inde, Népal, Tibet). L'Everest (8 849 m) est le point culminant du globe. Les Andes sont les plus longues (Amérique du Sud).",
    hint: "Himalaya = plus hautes montagnes + Everest (8 849 m). Asie du Sud.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-006',
    subject: 'histoire_geo',
    title: "Les Andes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Andes sont la plus longue chaîne de montagnes du monde. Sur quel continent se trouvent-elles ?",
    options: [
      { id: 'a', text: "L'Asie", isCorrect: false },
      { id: 'b', text: "L'Amérique du Sud", isCorrect: true },
      { id: 'c', text: "L'Afrique", isCorrect: false },
      { id: 'd', text: "L'Europe", isCorrect: false },
    ],
    correctAnswer: "L'Amérique du Sud",
    explanation: "Les Andes s'étendent sur 7 500 km le long de la côte ouest de l'Amérique du Sud, du Venezuela à la Patagonie. Elles accueillaient jadis l'empire Inca. Beaucoup de volcans actifs s'y trouvent.",
    hint: "Andes = plus longue chaîne = Amérique du Sud = côte ouest.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-007',
    subject: 'histoire_geo',
    title: "Le climat tempéré",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France a principalement un climat tempéré. Quelles sont ses caractéristiques ?",
    options: [
      { id: 'a', text: "Des températures extrêmes et des précipitations très rares", isCorrect: false },
      { id: 'b', text: "Des saisons bien marquées, des températures modérées et des précipitations réparties sur l'année", isCorrect: true },
      { id: 'c', text: "Un été très humide et un hiver très sec", isCorrect: false },
      { id: 'd', text: "Des températures identiques toute l'année", isCorrect: false },
    ],
    correctAnswer: "Des saisons bien marquées, des températures modérées et des précipitations réparties sur l'année",
    explanation: "Le climat tempéré se caractérise par 4 saisons bien distinctes, des températures ni trop chaudes ni trop froides, et des précipitations régulières. C'est le climat dominant en Europe de l'Ouest.",
    hint: "Tempéré = 4 saisons + températures modérées + pluies régulières.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-008',
    subject: 'histoire_geo',
    title: "Les zones polaires",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Groenland est une île couverte de glace. Dans quelle zone climatique se trouve-t-il ?",
    options: [
      { id: 'a', text: "La zone tropicale", isCorrect: false },
      { id: 'b', text: "La zone polaire ou subarctique", isCorrect: true },
      { id: 'c', text: "La zone méditerranéenne", isCorrect: false },
      { id: 'd', text: "La zone tempérée oceanique", isCorrect: false },
    ],
    correctAnswer: "La zone polaire ou subarctique",
    explanation: "Le Groenland (Arctique) est en zone polaire ou subarctique. 80 % de son territoire est couvert d'une calotte glaciaire permanente. Les températures peuvent descendre à -40°C en hiver.",
    hint: "Groenland = Arctique = zone polaire = glace permanente.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-009',
    subject: 'histoire_geo',
    title: "Les volcans",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les volcans actifs sont nombreux dans le monde. La zone qui en concentre le plus s'appelle…",
    options: [
      { id: 'a', text: "La ceinture de feu du Pacifique", isCorrect: true },
      { id: 'b', text: "La ceinture verte de l'Amazonie", isCorrect: false },
      { id: 'c', text: "Le plateau africain", isCorrect: false },
      { id: 'd', text: "Les plaines d'Europe du Nord", isCorrect: false },
    ],
    correctAnswer: "La ceinture de feu du Pacifique",
    explanation: "La ceinture de feu du Pacifique concentre plus de 75 % des volcans actifs mondiaux. Elle longe les côtes du Pacifique (Japon, Philippines, Indonésie, côte ouest des Amériques). C'est aussi la zone de séismes la plus active.",
    hint: "Ceinture de feu = autour du Pacifique = 75 % des volcans actifs.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-010',
    subject: 'histoire_geo',
    title: "Les grandes plaines d'Asie",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Sibérie est une immense région de Russie en Asie du Nord. Quel est son principal trait climatique ?",
    options: [
      { id: 'a', text: "Chaleur intense toute l'année", isCorrect: false },
      { id: 'b', text: "Hivers extrêmement froids (jusqu'à -50°C) et courts étés chauds", isCorrect: true },
      { id: 'c', text: "Pluies tropicales abondantes", isCorrect: false },
      { id: 'd', text: "Absence totale de précipitations", isCorrect: false },
    ],
    correctAnswer: "Hivers extrêmement froids (jusqu'à -50°C) et courts étés chauds",
    explanation: "La Sibérie a un climat continental extrême : hivers glacials (-30 à -50°C à Iakoutsk, la ville la plus froide du monde) et étés courts mais chauds (+25°C). Le sol y est souvent gelé en profondeur (permafrost).",
    hint: "Sibérie = hivers extrêmes (-50°C) + permafrost + courts étés chauds.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-011',
    subject: 'histoire_geo',
    title: "La Prairie nord-américaine",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Prairie nord-américaine (États-Unis, Canada) est une vaste plaine céréalière. Comment s'appelle cette région agricole ?",
    options: [
      { id: 'a', text: "Le Midwest ou le grenier à blé de l'Amérique", isCorrect: true },
      { id: 'b', text: "La Silicon Valley", isCorrect: false },
      { id: 'c', text: "La Côte Est", isCorrect: false },
      { id: 'd', text: "La Rust Belt", isCorrect: false },
    ],
    correctAnswer: "Le Midwest ou le grenier à blé de l'Amérique",
    explanation: "Le Midwest américain (et les Prairies canadiennes) est une vaste plaine fertile surnommée le « grenier à blé de l'Amérique ». On y cultive blé, maïs, soja, et on y élève des bovins sur d'immenses ranchs.",
    hint: "Midwest USA = grenier à blé = grande plaine céréalière nord-américaine.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-012',
    subject: 'histoire_geo',
    title: "La taïga et la toundra",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La taïga est une immense forêt de conifères qui s'étend en Russie, Canada et Scandinavie. Que trouve-t-on encore plus au nord ?",
    options: [
      { id: 'a', text: "La forêt tropicale humide", isCorrect: false },
      { id: 'b', text: "La toundra : vaste zone sans arbres, gelée en profondeur", isCorrect: true },
      { id: 'c', text: "Le désert du Sahara", isCorrect: false },
      { id: 'd', text: "La savane africaine", isCorrect: false },
    ],
    correctAnswer: "La toundra : vaste zone sans arbres, gelée en profondeur",
    explanation: "La toundra est plus au nord que la taïga. Les arbres ne peuvent plus pousser (trop froid). Le sol est gelé en profondeur (permafrost). Seules des herbes, des mousses et des lichens résistent.",
    hint: "Nord → taïga (conifères) → toundra (pas d'arbres, permafrost) → glace polaire.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-013',
    subject: 'histoire_geo',
    title: "Les séismes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les séismes (tremblements de terre) se produisent lorsque…",
    options: [
      { id: 'a', text: "Il fait très froid", isCorrect: false },
      { id: 'b', text: "Les plaques tectoniques (grands morceaux de la croûte terrestre) se déplacent ou se fracturent", isCorrect: true },
      { id: 'c', text: "Les volcans émettent trop de fumée", isCorrect: false },
      { id: 'd', text: "Les océans se réchauffent", isCorrect: false },
    ],
    correctAnswer: "Les plaques tectoniques (grands morceaux de la croûte terrestre) se déplacent ou se fracturent",
    explanation: "La Terre est divisée en grandes plaques tectoniques qui se déplacent lentement. Quand deux plaques se frôlent, s'éloignent ou s'affrontent, elles libèrent de l'énergie : c'est le séisme. Les zones de contact sont les plus exposées.",
    hint: "Séisme = plaques tectoniques en mouvement → libération d'énergie.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-014',
    subject: 'histoire_geo',
    title: "La savane africaine",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_climats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La savane africaine est une vaste étendue de graminées (herbes) avec quelques arbres. Quel est son régime climatique ?",
    options: [
      { id: 'a', text: "Pluies abondantes toute l'année", isCorrect: false },
      { id: 'b', text: "Une saison sèche et une saison des pluies alternées", isCorrect: true },
      { id: 'c', text: "Pas de pluie du tout", isCorrect: false },
      { id: 'd', text: "Froid intense en toutes saisons", isCorrect: false },
    ],
    correctAnswer: "Une saison sèche et une saison des pluies alternées",
    explanation: "La savane a un régime tropical avec deux saisons : la saison sèche (végétation brûlée) et la saison des pluies (herbes verdissantes). C'est l'habitat des grands herbivores africains (gnous, zèbres, éléphants).",
    hint: "Savane = tropical = saison sèche + saison des pluies alternées.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-rls-015',
    subject: 'histoire_geo',
    title: "L'altitude et le climat",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'reliefs_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quand on monte en altitude (vers le sommet d'une montagne), que se passe-t-il avec la température ?",
    options: [
      { id: 'a', text: "La température augmente", isCorrect: false },
      { id: 'b', text: "La température diminue (d'environ 6°C par 1 000 m)", isCorrect: true },
      { id: 'c', text: "La température reste identique", isCorrect: false },
      { id: 'd', text: "La température augmente jusqu'à 3 000 m puis diminue", isCorrect: false },
    ],
    correctAnswer: "La température diminue (d'environ 6°C par 1 000 m)",
    explanation: "La température diminue d'environ 6°C par 1 000 m d'altitude. C'est pourquoi les sommets des montagnes sont enneigés même sous des latitudes chaudes. L'Himalaya est enneigé sous les tropiques à cause de son altitude.",
    hint: "Altitude↑ → température↓. Environ -6°C par 1 000 m. D'où les sommets enneigés.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
