import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm1HistoireTempsRoisExercises: HgExercise[] = [

  {
    id: 'hg-cm1-hist-rois-001',
    subject: 'histoire_geo',
    title: 'Le premier roi des Francs',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel roi franc fut baptisé à Reims vers 496, unissant ainsi les Francs et le christianisme ?',
    options: [
      { id: 'a', text: 'Louis XIV', isCorrect: false },
      { id: 'b', text: 'Charlemagne', isCorrect: false },
      { id: 'c', text: 'Clovis', isCorrect: true },
      { id: 'd', text: 'François Ier', isCorrect: false },
    ],
    correctAnswer: 'Clovis',
    explanation: 'Clovis, roi des Francs, fut baptisé à Reims. Il est souvent considéré comme le premier roi de France.',
    hint: 'Son prénom commence par C et rime avec la ville où il fut baptisé.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-002',
    subject: 'histoire_geo',
    title: 'Louis XIV, le Roi-Soleil',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Louis XIV est surnommé le "Roi-Soleil". Quel grand château fit-il construire ?',
    options: [
      { id: 'a', text: 'Le château de Chambord', isCorrect: false },
      { id: 'b', text: 'Le château de Versailles', isCorrect: true },
      { id: 'c', text: 'Le Louvre', isCorrect: false },
      { id: 'd', text: 'Le Mont-Saint-Michel', isCorrect: false },
    ],
    correctAnswer: 'Le château de Versailles',
    explanation: 'Louis XIV fit construire et agrandir le château de Versailles, qui devint la résidence des rois de France.',
    hint: 'Ce château se trouve dans la ville qui porte le même nom, près de Paris.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-003',
    subject: 'histoire_geo',
    title: 'La Renaissance',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Renaissance est une période où les arts et les sciences ont beaucoup progressé. Quel roi français a favorisé la Renaissance en France ?',
    options: [
      { id: 'a', text: 'Henri IV', isCorrect: false },
      { id: 'b', text: 'François Ier', isCorrect: true },
      { id: 'c', text: 'Louis XVI', isCorrect: false },
      { id: 'd', text: 'Napoléon', isCorrect: false },
    ],
    correctAnswer: 'François Ier',
    explanation: 'François Ier a invité des artistes et des savants italiens en France, dont Léonard de Vinci, favorisant ainsi la Renaissance.',
    hint: 'Il régna au XVIe siècle et aimait beaucoup les arts.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-004',
    subject: 'histoire_geo',
    title: 'Henri IV et l\'Édit de Nantes',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Henri IV signa l\'Édit de Nantes en 1598. Qu\'est-ce que cet édit permettait ?',
    options: [
      { id: 'a', text: 'De construire le château de Versailles', isCorrect: false },
      { id: 'b', text: 'D\'abolir la noblesse', isCorrect: false },
      { id: 'c', text: 'Aux protestants de pratiquer leur religion librement', isCorrect: true },
      { id: 'd', text: 'De créer les premières écoles de France', isCorrect: false },
    ],
    correctAnswer: 'Aux protestants de pratiquer leur religion librement',
    explanation: 'L\'Édit de Nantes mettait fin aux guerres de Religion en accordant aux protestants le droit de pratiquer leur foi.',
    hint: 'Cet édit visait à mettre fin aux guerres entre catholiques et protestants.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-005',
    subject: 'histoire_geo',
    title: 'L\'invention de l\'imprimerie',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qui inventa l\'imprimerie à caractères mobiles au XVe siècle, permettant de diffuser les livres ?',
    options: [
      { id: 'a', text: 'Léonard de Vinci', isCorrect: false },
      { id: 'b', text: 'Johannes Gutenberg', isCorrect: true },
      { id: 'c', text: 'Christophe Colomb', isCorrect: false },
      { id: 'd', text: 'Louis XIV', isCorrect: false },
    ],
    correctAnswer: 'Johannes Gutenberg',
    explanation: 'Gutenberg inventa l\'imprimerie à caractères mobiles vers 1450, révolutionnant la diffusion du savoir.',
    hint: 'C\'était un Allemand dont le prénom commence par J.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-006',
    subject: 'histoire_geo',
    title: 'Les grandes découvertes',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En 1492, Christophe Colomb traversa l\'Atlantique pour rejoindre l\'Asie et découvrit un continent inconnu des Européens. Quel continent est-ce ?',
    options: [
      { id: 'a', text: 'L\'Afrique', isCorrect: false },
      { id: 'b', text: 'L\'Australie', isCorrect: false },
      { id: 'c', text: 'L\'Amérique', isCorrect: true },
      { id: 'd', text: 'L\'Antarctique', isCorrect: false },
    ],
    correctAnswer: 'L\'Amérique',
    explanation: 'En cherchant une route vers l\'Asie, Christophe Colomb atteignit les Caraïbes en 1492, ouvrant l\'ère des grandes découvertes.',
    hint: 'Ce continent porte aujourd\'hui le prénom d\'un autre explorateur, Amerigo Vespucci.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-007',
    subject: 'histoire_geo',
    title: "Saint Louis et les Croisades",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'rois_de_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis IX, dit Saint Louis, participa à deux croisades. Où mourut-il en 1270 ?",
    options: [
      { id: 'a', text: "À Paris", isCorrect: false },
      { id: 'b', text: "À Tunis (en Afrique du Nord)", isCorrect: true },
      { id: 'c', text: "À Jérusalem", isCorrect: false },
      { id: 'd', text: "À Londres", isCorrect: false },
    ],
    correctAnswer: "À Tunis (en Afrique du Nord)",
    explanation: "Louis IX mourut de la peste devant Tunis en 1270 lors de la 8e croisade. Il fut canonisé (déclaré saint) par le pape en 1297.",
    hint: "Saint Louis mourut loin de France, lors d'une croisade en Afrique du Nord.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-008',
    subject: 'histoire_geo',
    title: "La Guerre de Cent Ans",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'guerre_cent_ans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Guerre de Cent Ans (1337-1453) opposa la France à l'Angleterre. Quelle est la raison principale de ce conflit ?",
    options: [
      { id: 'a', text: "Le contrôle de la mer Méditerranée", isCorrect: false },
      { id: 'b', text: "La succession au trône de France (les rois anglais revendiquaient le trône)", isCorrect: true },
      { id: 'c', text: "La découverte de l'Amérique", isCorrect: false },
      { id: 'd', text: "La religion catholique vs protestante", isCorrect: false },
    ],
    correctAnswer: "La succession au trône de France (les rois anglais revendiquaient le trône)",
    explanation: "Les rois d'Angleterre, descendants de capétiens, revendiquaient le trône de France. Ce conflit de 116 ans (avec des trêves) s'achève par la victoire française en 1453.",
    hint: "Guerre de Cent Ans = qui sera roi de France ?",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-009',
    subject: 'histoire_geo',
    title: "1492 et Christophe Colomb",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En 1492, Christophe Colomb atteint un continent inconnu des Européens. Cela marque le début des Temps modernes. Quel est ce continent ?",
    options: [
      { id: 'a', text: "L'Afrique", isCorrect: false },
      { id: 'b', text: "L'Amérique", isCorrect: true },
      { id: 'c', text: "L'Australie", isCorrect: false },
      { id: 'd', text: "L'Asie", isCorrect: false },
    ],
    correctAnswer: "L'Amérique",
    explanation: "En 1492, Colomb débarque aux Bahamas, ouvrant l'ère des grandes découvertes. Les Européens commencent à coloniser l'Amérique, transformant profondément l'histoire du monde.",
    hint: "1492 = Colomb = Amérique = début des Temps modernes.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-010',
    subject: 'histoire_geo',
    title: "Léonard de Vinci en France",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'temps_modernes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel roi français a invité Léonard de Vinci à venir en France vers 1516 ?",
    options: [
      { id: 'a', text: "Louis XIV", isCorrect: false },
      { id: 'b', text: "François Ier", isCorrect: true },
      { id: 'c', text: "Henri IV", isCorrect: false },
      { id: 'd', text: "Louis XVI", isCorrect: false },
    ],
    correctAnswer: "François Ier",
    explanation: "François Ier, grand mécène de la Renaissance, invita Léonard de Vinci à sa cour. L'artiste apporta la Joconde en France, où elle est conservée au Louvre.",
    hint: "Renaissance + Joconde + châteaux de la Loire → François Ier.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-011',
    subject: 'histoire_geo',
    title: "Louis XIV et Versailles",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'louis_xiv',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis XIV installe la cour royale à Versailles. Quel était l'avantage pour le roi d'avoir la noblesse à Versailles ?",
    options: [
      { id: 'a', text: "Les nobles construisaient les jardins eux-mêmes", isCorrect: false },
      { id: 'b', text: "Le roi pouvait surveiller les nobles et les éloigner de leurs fiefs où ils auraient pu comploter", isCorrect: true },
      { id: 'c', text: "Les nobles payaient un loyer qui enrichissait le roi", isCorrect: false },
      { id: 'd', text: "Les nobles apprenaient à jardiner", isCorrect: false },
    ],
    correctAnswer: "Le roi pouvait surveiller les nobles et les éloigner de leurs fiefs où ils auraient pu comploter",
    explanation: "Louis XIV avait compris que les nobles dans leurs provinces pouvaient se rebeller (comme pendant la Fronde). En les gardant à Versailles, il les contrôlait, renforçant l'absolutisme royal.",
    hint: "Versailles = cage dorée pour les nobles.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-012',
    subject: 'histoire_geo',
    title: "L'absolutisme royal",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'louis_xiv',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis XIV est réputé pour avoir dit « L'État, c'est moi ». Que signifie cette phrase ?",
    options: [
      { id: 'a', text: "Il était seul à payer les impôts", isCorrect: false },
      { id: 'b', text: "Il concentrait tout le pouvoir en sa personne sans partage", isCorrect: true },
      { id: 'c', text: "Il s'occupait lui-même de toutes les constructions", isCorrect: false },
      { id: 'd', text: "Il était aussi ministre et général", isCorrect: false },
    ],
    correctAnswer: "Il concentrait tout le pouvoir en sa personne sans partage",
    explanation: "Cette phrase illustre l'absolutisme : le roi est la loi, personne ne peut le contredire. Louis XIV gouvernait seul, sans Premier ministre, contrôlant l'armée, la justice et les finances.",
    hint: "Absolu = total, sans limite. L'absolutisme = pouvoir total du roi.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-013',
    subject: 'histoire_geo',
    title: "La révocation de l'Édit de Nantes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'guerres_de_religion',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Édit de Nantes (1598) accordait la liberté de culte aux protestants. Louis XIV le révoqua en 1685. Quelle en fut la conséquence principale ?",
    options: [
      { id: 'a', text: "Les protestants reçurent de nouvelles terres", isCorrect: false },
      { id: 'b', text: "Des centaines de milliers de protestants quittèrent la France", isCorrect: true },
      { id: 'c', text: "Les protestants furent nommés ministres", isCorrect: false },
      { id: 'd', text: "Les protestants construisirent de nouvelles cathédrales", isCorrect: false },
    ],
    correctAnswer: "Des centaines de milliers de protestants quittèrent la France",
    explanation: "La révocation de l'Édit de Nantes (1685) obligea les protestants à se convertir ou à fuir. Environ 200 000 à 300 000 protestants émigrèrent (Angleterre, Prusse, Hollande…).",
    hint: "Révocation 1685 → fuite des protestants hors de France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-014',
    subject: 'histoire_geo',
    title: "Louis XVI",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'veille_revolution',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis XVI, qui régna au moment de la Révolution, était le petit-fils (à plusieurs générations) de Louis XIV. Quelle était la femme de Louis XVI ?",
    options: [
      { id: 'a', text: "Marie-Thérèse d'Espagne", isCorrect: false },
      { id: 'b', text: "Marie-Antoinette d'Autriche", isCorrect: true },
      { id: 'c', text: "Marie Stuart d'Écosse", isCorrect: false },
      { id: 'd', text: "Catherine de Médicis", isCorrect: false },
    ],
    correctAnswer: "Marie-Antoinette d'Autriche",
    explanation: "Louis XVI épousa Marie-Antoinette d'Autriche en 1770 pour consolider l'alliance franco-autrichienne. Tous deux furent guillotinés en 1793.",
    hint: "Marie-Antoinette = L'Autrichienne (surnom populaire).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-015',
    subject: 'histoire_geo',
    title: "Les Trois Ordres",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'veille_revolution',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Sous l'Ancien Régime, la société française était divisée en 3 ordres. Lequel payait les impôts ?",
    options: [
      { id: 'a', text: "Le Clergé", isCorrect: false },
      { id: 'b', text: "La Noblesse", isCorrect: false },
      { id: 'c', text: "Le Tiers État (les paysans, les bourgeois)", isCorrect: true },
      { id: 'd', text: "Les trois ordres payaient les mêmes impôts", isCorrect: false },
    ],
    correctAnswer: "Le Tiers État (les paysans, les bourgeois)",
    explanation: "L'Ancien Régime divisait la société en 3 ordres : le Clergé (prie), la Noblesse (combat) et le Tiers État (travaille et paie). Cette injustice fut l'une des causes de la Révolution.",
    hint: "Tiers État = 97% de la population → paie tout.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-016',
    subject: 'histoire_geo',
    title: "Richelieu",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'rois_de_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le cardinal de Richelieu était le puissant ministre du roi Louis XIII. Que cherchait-il surtout à faire ?",
    options: [
      { id: 'a', text: "Affaiblir le pouvoir du roi au profit de la noblesse", isCorrect: false },
      { id: 'b', text: "Renforcer l'autorité du roi et l'unité de la France", isCorrect: true },
      { id: 'c', text: "Signer la paix définitive avec l'Angleterre", isCorrect: false },
      { id: 'd', text: "Construire Versailles", isCorrect: false },
    ],
    correctAnswer: "Renforcer l'autorité du roi et l'unité de la France",
    explanation: "Richelieu (1585-1642), Premier ministre de Louis XIII, centralisa le pouvoir royal, affaiblit les grands nobles et les protestants, et fit de la France une grande puissance européenne.",
    hint: "Richelieu = ministre qui renforce le roi et unifie la France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-017',
    subject: 'histoire_geo',
    title: "Henri IV et l'Édit de Nantes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'guerres_de_religion',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Henri IV signa l'Édit de Nantes en 1598. Quel problème cela résolvait-il ?",
    options: [
      { id: 'a', text: "La guerre avec l'Espagne", isCorrect: false },
      { id: 'b', text: "Les guerres de Religion entre catholiques et protestants", isCorrect: true },
      { id: 'c', text: "La famine qui touchait la France", isCorrect: false },
      { id: 'd', text: "Les invasions vikings", isCorrect: false },
    ],
    correctAnswer: "Les guerres de Religion entre catholiques et protestants",
    explanation: "Les guerres de Religion (1562-1598) opposèrent catholiques et protestants. L'Édit de Nantes accorda aux protestants la liberté de culte, ramenant la paix religieuse en France.",
    hint: "Édit de Nantes = paix entre catholiques et protestants.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-018',
    subject: 'histoire_geo',
    title: "Durée du règne de Louis XIV",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'louis_xiv',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis XIV est monté sur le trône en 1643 et est mort en 1715. Combien de temps a-t-il régné ?",
    options: [
      { id: 'a', text: "30 ans", isCorrect: false },
      { id: 'b', text: "72 ans", isCorrect: true },
      { id: 'c', text: "50 ans", isCorrect: false },
      { id: 'd', text: "100 ans", isCorrect: false },
    ],
    correctAnswer: "72 ans",
    explanation: "Louis XIV régna de 1643 à 1715, soit 72 ans — le règne le plus long de l'histoire de France.",
    hint: "1715 - 1643 = 72 ans.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-019',
    subject: 'histoire_geo',
    title: "Jeanne d'Arc libère Orléans",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'guerre_cent_ans',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En 1429, Jeanne d'Arc leva le siège d'Orléans assiégée par les Anglais. Quelle fut la fin de Jeanne d'Arc ?",
    options: [
      { id: 'a', text: "Elle devint reine de France", isCorrect: false },
      { id: 'b', text: "Elle fut capturée par les Bourguignons et brûlée à Rouen en 1431", isCorrect: true },
      { id: 'c', text: "Elle s'exila en Angleterre", isCorrect: false },
      { id: 'd', text: "Elle mourut au combat à Orléans", isCorrect: false },
    ],
    correctAnswer: "Elle fut capturée par les Bourguignons et brûlée à Rouen en 1431",
    explanation: "Après ses victoires, Jeanne d'Arc fut capturée par les Bourguignons (alliés des Anglais), vendue aux Anglais et brûlée vive à Rouen le 30 mai 1431. Elle fut canonisée en 1920.",
    hint: "Rouen 1431 = lieu et date de la mort de Jeanne d'Arc.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-rois-020',
    subject: 'histoire_geo',
    title: "Les Capétiens",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'rois_de_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Hugues Capet est couronné roi de France en 987. Il fonde une longue lignée royale. Comment s'appelle cette première grande dynastie médiévale ?",
    options: [
      { id: 'a', text: "Les Mérovingiens", isCorrect: false },
      { id: 'b', text: "Les Capétiens", isCorrect: true },
      { id: 'c', text: "Les Carolingiens", isCorrect: false },
      { id: 'd', text: "Les Bourbons", isCorrect: false },
    ],
    correctAnswer: "Les Capétiens",
    explanation: "Hugues Capet fonde la dynastie capétienne en 987. Les Capétiens régnèrent jusqu'en 1328. Leurs descendants (Valois, Bourbons) gouvernèrent la France jusqu'en 1792.",
    hint: "Capet → Capétiens. 987, début du Moyen Âge royal en France.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
