import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm1HistoireAvantFranceExercises: HgExercise[] = [

  {
    id: 'hg-cm1-hist-avt-001',
    subject: 'histoire_geo',
    title: 'La Préhistoire',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'prehistoire',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les hommes de la Préhistoire ne connaissaient pas encore l\'écriture. Comment appelle-t-on cette période ?',
    options: [
      { id: 'a', text: 'L\'Antiquité', isCorrect: false },
      { id: 'b', text: 'La Préhistoire', isCorrect: true },
      { id: 'c', text: 'Le Moyen Âge', isCorrect: false },
      { id: 'd', text: 'Les Temps modernes', isCorrect: false },
    ],
    correctAnswer: 'La Préhistoire',
    explanation: 'La Préhistoire est la période qui précède l\'invention de l\'écriture. Les hommes vivaient de la chasse et de la cueillette.',
    hint: 'C\'est la toute première grande période de l\'histoire humaine.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-002',
    subject: 'histoire_geo',
    title: 'Les premiers hommes',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'prehistoire',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les hommes préhistoriques ont laissé des peintures sur les parois des grottes. Quel célèbre site préhistorique se trouve en France ?',
    options: [
      { id: 'a', text: 'Pompéi', isCorrect: false },
      { id: 'b', text: 'Lascaux', isCorrect: true },
      { id: 'c', text: 'Stonehenge', isCorrect: false },
      { id: 'd', text: 'Le Colisée', isCorrect: false },
    ],
    correctAnswer: 'Lascaux',
    explanation: 'La grotte de Lascaux, en Dordogne, contient de magnifiques peintures réalisées il y a environ 17 000 ans.',
    hint: 'Cette grotte se trouve dans le Périgord, au sud-ouest de la France.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-003',
    subject: 'histoire_geo',
    title: 'Les Gaulois',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'antiquite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel peuple habitait en Gaule (l\'actuelle France) avant la conquête romaine ?',
    options: [
      { id: 'a', text: 'Les Romains', isCorrect: false },
      { id: 'b', text: 'Les Gaulois', isCorrect: true },
      { id: 'c', text: 'Les Grecs', isCorrect: false },
      { id: 'd', text: 'Les Francs', isCorrect: false },
    ],
    correctAnswer: 'Les Gaulois',
    explanation: 'Les Gaulois vivaient en Gaule avant que Jules César ne la conquière pour Rome, au Ier siècle avant J.-C.',
    hint: 'Astérix et Obélix sont des personnages de bande dessinée appartenant à ce peuple.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-004',
    subject: 'histoire_geo',
    title: 'L\'Empire romain',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'antiquite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle ville était la capitale de l\'Empire romain ?',
    options: [
      { id: 'a', text: 'Athènes', isCorrect: false },
      { id: 'b', text: 'Carthage', isCorrect: false },
      { id: 'c', text: 'Rome', isCorrect: true },
      { id: 'd', text: 'Paris', isCorrect: false },
    ],
    correctAnswer: 'Rome',
    explanation: 'Rome était la capitale du puissant Empire romain. On dit souvent "tous les chemins mènent à Rome".',
    hint: 'C\'est aussi le nom d\'une grande ville d\'Italie aujourd\'hui.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-005',
    subject: 'histoire_geo',
    title: 'Le Moyen Âge — les châteaux forts',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Au Moyen Âge, les seigneurs vivaient dans des constructions fortifiées. Comment s\'appellent-elles ?',
    options: [
      { id: 'a', text: 'Des cathédrales', isCorrect: false },
      { id: 'b', text: 'Des châteaux forts', isCorrect: true },
      { id: 'c', text: 'Des forums', isCorrect: false },
      { id: 'd', text: 'Des menhirs', isCorrect: false },
    ],
    correctAnswer: 'Des châteaux forts',
    explanation: 'Les châteaux forts servaient à la fois de résidence aux seigneurs et de protection pour les habitants des environs.',
    hint: 'Ces constructions avaient des tours, des douves et un pont-levis.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-006',
    subject: 'histoire_geo',
    title: 'Charlemagne',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Charlemagne fut couronné empereur en l\'an 800. Quelle fut l\'une de ses grandes actions pour le peuple ?',
    options: [
      { id: 'a', text: 'Il construisit la tour Eiffel', isCorrect: false },
      { id: 'b', text: 'Il développa les écoles pour apprendre à lire et à écrire', isCorrect: true },
      { id: 'c', text: 'Il découvrit l\'Amérique', isCorrect: false },
      { id: 'd', text: 'Il inventa l\'imprimerie', isCorrect: false },
    ],
    correctAnswer: 'Il développa les écoles pour apprendre à lire et à écrire',
    explanation: 'Charlemagne a encouragé la création d\'écoles dans tout son empire pour que les gens sachent lire et écrire.',
    hint: 'Il est souvent associé à l\'histoire de l\'école en France.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-007',
    subject: 'histoire_geo',
    title: "Le feu au Paléolithique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'prehistoire',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La maîtrise du feu est l'une des premières grandes découvertes de l'humanité. À quelle grande période de la Préhistoire les hommes utilisaient-ils déjà le feu ?",
    options: [
      { id: 'a', text: "Le Néolithique uniquement", isCorrect: false },
      { id: 'b', text: "Le Paléolithique (la plus ancienne période de la Préhistoire)", isCorrect: true },
      { id: 'c', text: "L'Antiquité", isCorrect: false },
      { id: 'd', text: "Le Moyen Âge", isCorrect: false },
    ],
    correctAnswer: "Le Paléolithique (la plus ancienne période de la Préhistoire)",
    explanation: "Le Paléolithique est la plus longue période de la Préhistoire. Les hommes maîtrisaient le feu depuis au moins 400 000 ans, ce qui leur permettait de se chauffer, cuisiner et se protéger.",
    hint: "Paléo = vieux, lithique = pierre. Le feu est apparu il y a des centaines de milliers d'années.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-008',
    subject: 'histoire_geo',
    title: "Le Néolithique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'prehistoire',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le Néolithique (environ -7000 à -3300 av. J.-C.) est marqué par deux grandes révolutions. Lesquelles ?",
    options: [
      { id: 'a', text: "L'invention de l'écriture et du bateau", isCorrect: false },
      { id: 'b', text: "L'agriculture et l'élevage (les hommes se sédentarisent)", isCorrect: true },
      { id: 'c', text: "La métallurgie et la construction de pyramides", isCorrect: false },
      { id: 'd', text: "La peinture rupestre et la chasse collective", isCorrect: false },
    ],
    correctAnswer: "L'agriculture et l'élevage (les hommes se sédentarisent)",
    explanation: "Au Néolithique, les humains cessent d'être nomades : ils cultivent la terre et élèvent des animaux. Cette « révolution néolithique » permet de former des villages permanents.",
    hint: "Néo = nouveau, lithique = pierre. Néolithique = agriculture + sédentarité.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-009',
    subject: 'histoire_geo',
    title: "Les mégalithes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'prehistoire',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, notamment en Bretagne, on trouve d'imposantes constructions en pierre érigées au Néolithique. Comment appelle-t-on ces pierres dressées verticalement ?",
    options: [
      { id: 'a', text: "Des châteaux forts", isCorrect: false },
      { id: 'b', text: "Des menhirs", isCorrect: true },
      { id: 'c', text: "Des colonnes romaines", isCorrect: false },
      { id: 'd', text: "Des obélisques", isCorrect: false },
    ],
    correctAnswer: "Des menhirs",
    explanation: "Les menhirs sont des pierres dressées verticalement par les hommes du Néolithique. Les dolmens sont des tombeaux de pierres. Les alignements de Carnac (Bretagne) en comptent des milliers.",
    hint: "Menhir = grande pierre dressée. Carnac (Bretagne) = site le plus célèbre.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-010',
    subject: 'histoire_geo',
    title: "Les Celtes en Gaule",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'gaule',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Avant la conquête romaine, la Gaule était peuplée de tribus celtes. Comment appelait-on ces populations ?",
    options: [
      { id: 'a', text: "Les Romains", isCorrect: false },
      { id: 'b', text: "Les Gaulois", isCorrect: true },
      { id: 'c', text: "Les Francs", isCorrect: false },
      { id: 'd', text: "Les Normands", isCorrect: false },
    ],
    correctAnswer: "Les Gaulois",
    explanation: "Les Gaulois sont les peuples celtes qui habitaient la Gaule avant la conquête romaine. Ils étaient organisés en tribus et parlaient des langues celtiques.",
    hint: "Astérix et Obélix sont des personnages gaulois fictifs.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-011',
    subject: 'histoire_geo',
    title: "Vercingétorix et Alésia",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'gaule',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En 52 av. J.-C., Vercingétorix se rendit à Jules César après la défaite d'Alésia. Cette défaite marqua…",
    options: [
      { id: 'a', text: "La libération de la Gaule", isCorrect: false },
      { id: 'b', text: "La fin de la résistance gauloise et le début de la domination romaine sur la Gaule", isCorrect: true },
      { id: 'c', text: "La destruction de Rome par les Gaulois", isCorrect: false },
      { id: 'd', text: "Le début de la construction de Versailles", isCorrect: false },
    ],
    correctAnswer: "La fin de la résistance gauloise et le début de la domination romaine sur la Gaule",
    explanation: "La défaite d'Alésia (-52) est la dernière grande résistance gauloise. La Gaule devient une province romaine. Vercingétorix sera exécuté à Rome 6 ans plus tard.",
    hint: "Alésia -52 = Gaule romaine pendant 500 ans.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-012',
    subject: 'histoire_geo',
    title: "La romanisation",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'gaule_romaine',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Après la conquête, la Gaule s'est « romanisée ». Quelle langue les Gaulois ont-ils progressivement adoptée ?",
    options: [
      { id: 'a', text: "Le grec ancien", isCorrect: false },
      { id: 'b', text: "Le latin", isCorrect: true },
      { id: 'c', text: "L'arabe", isCorrect: false },
      { id: 'd', text: "Le germanique", isCorrect: false },
    ],
    correctAnswer: "Le latin",
    explanation: "Les Gaulois ont adopté le latin parlé par les Romains. Cette langue a évolué pour donner le français (et les autres langues romanes : espagnol, italien, portugais…).",
    hint: "Le français vient du latin → romanisation de la Gaule.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-013',
    subject: 'histoire_geo',
    title: "L'héritage romain en Gaule",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'gaule_romaine',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Romains ont laissé de nombreux monuments en Gaule. Lequel est d'origine romaine ?",
    options: [
      { id: 'a', text: "La tour Eiffel (Paris)", isCorrect: false },
      { id: 'b', text: "Le Pont du Gard (aqueduc romain)", isCorrect: true },
      { id: 'c', text: "Notre-Dame de Paris", isCorrect: false },
      { id: 'd', text: "Le château de Versailles", isCorrect: false },
    ],
    correctAnswer: "Le Pont du Gard (aqueduc romain)",
    explanation: "Le Pont du Gard est un aqueduc construit par les Romains au Ier siècle pour amener l'eau jusqu'à Nîmes. Il est classé au Patrimoine mondial de l'UNESCO.",
    hint: "Aqueduc romain = pont transportant l'eau sur de longues distances.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-014',
    subject: 'histoire_geo',
    title: "Clovis et les Francs",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'haut_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Après la chute de l'Empire romain (476), les Francs s'installent en Gaule. Leur roi Clovis se convertit au christianisme vers 496. Cela est important car…",
    options: [
      { id: 'a', text: "Clovis inventa l'imprimerie", isCorrect: false },
      { id: 'b', text: "Clovis devint le premier roi franc chrétien, fondant le lien entre royauté et Église en France", isCorrect: true },
      { id: 'c', text: "Clovis construisit Notre-Dame de Paris", isCorrect: false },
      { id: 'd', text: "Clovis reconquit Jérusalem", isCorrect: false },
    ],
    correctAnswer: "Clovis devint le premier roi franc chrétien, fondant le lien entre royauté et Église en France",
    explanation: "Le baptême de Clovis (~496) fait des Francs un peuple chrétien. Cela unifie le territoire et établit un lien fort entre pouvoir royal et Église catholique, qui durera tout le Moyen Âge.",
    hint: "Baptême de Clovis ~496 = premier roi chrétien de France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-015',
    subject: 'histoire_geo',
    title: "Mérovingiens et Carolingiens",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'haut_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Clovis est le fondateur de la première dynastie franque. Comment s'appellent les deux grandes dynasties franques du haut Moyen Âge ?",
    options: [
      { id: 'a', text: "Les Capétiens et les Valois", isCorrect: false },
      { id: 'b', text: "Les Mérovingiens et les Carolingiens", isCorrect: true },
      { id: 'c', text: "Les Bourbons et les Orléans", isCorrect: false },
      { id: 'd', text: "Les Romains et les Gaulois", isCorrect: false },
    ],
    correctAnswer: "Les Mérovingiens et les Carolingiens",
    explanation: "Les Mérovingiens (Clovis, Ve-VIIIe s.) puis les Carolingiens (Charlemagne, VIIIe-Xe s.) sont les deux premières dynasties royales franques.",
    hint: "Clovis = Mérovingiens. Charlemagne = Carolingiens.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-016',
    subject: 'histoire_geo',
    title: "Les invasions vikings",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'haut_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au IXe siècle, des guerriers scandinaves ravagèrent les côtes et fleuves d'Europe. Comment les appelait-on en France ?",
    options: [
      { id: 'a', text: "Les Huns", isCorrect: false },
      { id: 'b', text: "Les Vikings (ou Normands)", isCorrect: true },
      { id: 'c', text: "Les Saracènes", isCorrect: false },
      { id: 'd', text: "Les Wisigoths", isCorrect: false },
    ],
    correctAnswer: "Les Vikings (ou Normands)",
    explanation: "Les Vikings viennent de Scandinavie. Ils remontèrent les fleuves français et pillèrent de nombreuses villes. Le roi carolingien leur céda la Normandie en 911.",
    hint: "Vikings = hommes du Nord = Normands. La Normandie porte leur nom.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-017',
    subject: 'histoire_geo',
    title: "Les moines copistes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au Moyen Âge, les monastères jouaient un rôle crucial pour conserver le savoir. Quelle activité les moines pratiquaient-ils pour transmettre les textes ?",
    options: [
      { id: 'a', text: "L'imprimerie industrielle", isCorrect: false },
      { id: 'b', text: "La copie à la main de manuscrits (moines copistes)", isCorrect: true },
      { id: 'c', text: "La construction d'arsenaux militaires", isCorrect: false },
      { id: 'd', text: "Le commerce maritime avec l'Orient", isCorrect: false },
    ],
    correctAnswer: "La copie à la main de manuscrits (moines copistes)",
    explanation: "Avant l'imprimerie (XVe s.), les moines copistes recopiaient les livres à la main dans les scriptoria. Ils ont ainsi conservé de nombreux textes antiques et chrétiens.",
    hint: "Moines copistes → scriptorium → copie de manuscrits.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-018',
    subject: 'histoire_geo',
    title: "La féodalité",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La société féodale du Moyen Âge est organisée selon des liens entre seigneurs et vassaux. Un vassal jurait fidélité à son seigneur en échange de…",
    options: [
      { id: 'a', text: "D'argent et de bijoux", isCorrect: false },
      { id: 'b', text: "D'une terre (le fief) et de protection", isCorrect: true },
      { id: 'c', text: "D'un titre de noblesse héréditaire", isCorrect: false },
      { id: 'd', text: "D'une armée personnelle", isCorrect: false },
    ],
    correctAnswer: "D'une terre (le fief) et de protection",
    explanation: "Dans la féodalité, le vassal prête serment de fidélité et de service militaire à son seigneur. En échange, il reçoit un fief (terre) et la protection du seigneur.",
    hint: "Féodalité → fief → vassal jure fidélité à son seigneur en échange de terre.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-019',
    subject: 'histoire_geo',
    title: "Les croisades",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les Croisades étaient des expéditions militaires organisées pour reprendre la Terre sainte. Quelle ville voulait-on libérer ?",
    options: [
      { id: 'a', text: "Rome", isCorrect: false },
      { id: 'b', text: "Jérusalem", isCorrect: true },
      { id: 'c', text: "Constantinople", isCorrect: false },
      { id: 'd', text: "Paris", isCorrect: false },
    ],
    correctAnswer: "Jérusalem",
    explanation: "Les Croisades (XIe-XIIIe s.) avaient pour but de reprendre Jérusalem (ville sainte pour chrétiens, juifs et musulmans). La 1re croisade (1099) réussit à prendre la ville.",
    hint: "Croisades = guerres saintes pour reprendre Jérusalem.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-hist-avt-020',
    subject: 'histoire_geo',
    title: "Jeanne d'Arc",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'fin_moyen_age',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Jeanne d'Arc (1412-1431) combattit durant la Guerre de Cent Ans pour chasser qui de France ?",
    options: [
      { id: 'a', text: "Les Espagnols", isCorrect: false },
      { id: 'b', text: "Les Anglais", isCorrect: true },
      { id: 'c', text: "Les Romains", isCorrect: false },
      { id: 'd', text: "Les Vikings", isCorrect: false },
    ],
    correctAnswer: "Les Anglais",
    explanation: "Durant la Guerre de Cent Ans (1337-1453), les Anglais occupaient une grande partie de la France. Jeanne d'Arc mena les armées françaises à la victoire à Orléans (1429) avant d'être capturée et brûlée à Rouen en 1431.",
    hint: "Guerre de Cent Ans = France vs Angleterre. Jeanne d'Arc → France.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
