import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm1GeoVivreFranceExercises: HgExercise[] = [

  {
    id: 'hg-cm1-geo-vfr-001',
    subject: 'histoire_geo',
    title: 'Les régions de France',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'vivre_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La France métropolitaine est divisée en grandes régions administratives. Combien en compte-t-elle depuis 2016 ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '13', isCorrect: true },
      { id: 'c', text: '22', isCorrect: false },
      { id: 'd', text: '96', isCorrect: false },
    ],
    correctAnswer: '13',
    explanation: 'Depuis la réforme de 2016, la France métropolitaine compte 13 régions. À cela s\'ajoutent 5 régions d\'outre-mer.',
    hint: 'Ce chiffre est inférieur à 20 mais supérieur à 10.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-002',
    subject: 'histoire_geo',
    title: 'Les grands fleuves de France',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'vivre_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le plus long fleuve de France, qui traverse les régions Centre, Pays-de-la-Loire et Bretagne ?',
    options: [
      { id: 'a', text: 'Le Rhône', isCorrect: false },
      { id: 'b', text: 'La Seine', isCorrect: false },
      { id: 'c', text: 'La Loire', isCorrect: true },
      { id: 'd', text: 'La Garonne', isCorrect: false },
    ],
    correctAnswer: 'La Loire',
    explanation: 'Avec plus de 1 000 km, la Loire est le plus long fleuve de France. Elle se jette dans l\'Atlantique à Saint-Nazaire.',
    hint: 'Ce fleuve donne son nom à une vallée célèbre pour ses châteaux.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-003',
    subject: 'histoire_geo',
    title: 'Les massifs montagneux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle chaîne de montagnes forme la frontière naturelle entre la France et l\'Espagne ?',
    options: [
      { id: 'a', text: 'Les Alpes', isCorrect: false },
      { id: 'b', text: 'Le Massif central', isCorrect: false },
      { id: 'c', text: 'Les Pyrénées', isCorrect: true },
      { id: 'd', text: 'Les Vosges', isCorrect: false },
    ],
    correctAnswer: 'Les Pyrénées',
    explanation: 'Les Pyrénées séparent la France de l\'Espagne (et d\'Andorre) du côté sud-ouest.',
    hint: 'Cette chaîne de montagnes se trouve au sud de la France.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-004',
    subject: 'histoire_geo',
    title: 'Les mers qui bordent la France',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La France est bordée par deux mers et un océan. Lequel de ces espaces maritimes se trouve à l\'ouest et au nord-ouest ?',
    options: [
      { id: 'a', text: 'La mer Méditerranée', isCorrect: false },
      { id: 'b', text: 'La mer du Nord', isCorrect: false },
      { id: 'c', text: 'L\'océan Atlantique', isCorrect: true },
      { id: 'd', text: 'La mer Noire', isCorrect: false },
    ],
    correctAnswer: 'L\'océan Atlantique',
    explanation: 'L\'océan Atlantique borde la France à l\'ouest (Bretagne, Pays basque). La Manche est au nord-ouest et la Méditerranée au sud.',
    hint: 'C\'est le plus grand des espaces maritimes qui bordent la France.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-005',
    subject: 'histoire_geo',
    title: 'La France d\'outre-mer',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La France possède des territoires situés hors d\'Europe. Lequel de ces territoires est un département et région d\'outre-mer (DROM) ?',
    options: [
      { id: 'a', text: 'Monaco', isCorrect: false },
      { id: 'b', text: 'La Corse', isCorrect: false },
      { id: 'c', text: 'La Martinique', isCorrect: true },
      { id: 'd', text: 'La Belgique', isCorrect: false },
    ],
    correctAnswer: 'La Martinique',
    explanation: 'La Martinique est une île des Caraïbes qui est un département et région d\'outre-mer français depuis 1946.',
    hint: 'Cette île se trouve dans la mer des Caraïbes, en Amérique.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-006',
    subject: 'histoire_geo',
    title: 'Le relief de la France',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'vivre_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le point culminant de la France (et d\'Europe occidentale) ?',
    options: [
      { id: 'a', text: 'Le Puy-de-Dôme', isCorrect: false },
      { id: 'b', text: 'Le Mont Blanc', isCorrect: true },
      { id: 'c', text: 'Le Mont Ventoux', isCorrect: false },
      { id: 'd', text: 'Le Vignemale', isCorrect: false },
    ],
    correctAnswer: 'Le Mont Blanc',
    explanation: 'Le Mont Blanc culmine à 4 810 mètres dans les Alpes, à la frontière franco-italienne. C\'est le toit de l\'Europe occidentale.',
    hint: 'Ce sommet des Alpes est recouvert de neige toute l\'année.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-007',
    subject: 'histoire_geo',
    title: "Les trois secteurs économiques",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "On classe les activités économiques en 3 secteurs. Quel secteur regroupe l'agriculture, la pêche et l'extraction minière ?",
    options: [
      { id: 'a', text: "Le secteur secondaire (industrie)", isCorrect: false },
      { id: 'b', text: "Le secteur primaire", isCorrect: true },
      { id: 'c', text: "Le secteur tertiaire (services)", isCorrect: false },
      { id: 'd', text: "Le secteur numérique", isCorrect: false },
    ],
    correctAnswer: "Le secteur primaire",
    explanation: "Le secteur primaire regroupe les activités qui exploitent directement les ressources naturelles : agriculture, élevage, pêche, sylviculture (forêts), mines.",
    hint: "Primaire = première transformation de la nature. Agriculture, pêche, mines.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-008',
    subject: 'histoire_geo',
    title: "La France, premier pays agricole de l'UE",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France est le premier pays agricole de l'Union européenne. Quelle est sa principale production céréalière ?",
    options: [
      { id: 'a', text: "Le riz", isCorrect: false },
      { id: 'b', text: "Le blé", isCorrect: true },
      { id: 'c', text: "Le coton", isCorrect: false },
      { id: 'd', text: "Le cacao", isCorrect: false },
    ],
    correctAnswer: "Le blé",
    explanation: "La France est le premier producteur de blé d'Europe. La Beauce (région céréalière entre Chartres et Orléans) est surnommée le « grenier à blé de la France ».",
    hint: "Beauce → champs de blé → France 1er producteur en Europe.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-009',
    subject: 'histoire_geo',
    title: "Le tourisme en France",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France est le premier pays au monde pour le nombre de touristes accueillis. Environ combien de touristes étrangers visite la France chaque année ?",
    options: [
      { id: 'a', text: "5 millions", isCorrect: false },
      { id: 'b', text: "90 millions", isCorrect: true },
      { id: 'c', text: "200 millions", isCorrect: false },
      { id: 'd', text: "10 millions", isCorrect: false },
    ],
    correctAnswer: "90 millions",
    explanation: "La France accueille environ 80 à 100 millions de touristes étrangers par an, ce qui en fait la 1re destination mondiale. Paris, la Côte d'Azur, les châteaux de la Loire et les Alpes en sont les principales attractions.",
    hint: "France = 1er pays touristique mondial → dizaines de millions de visiteurs.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-010',
    subject: 'histoire_geo',
    title: "Les services publics",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les services publics sont des services assurés par l'État pour tous les citoyens. Lequel n'est PAS un service public ?",
    options: [
      { id: 'a', text: "L'école", isCorrect: false },
      { id: 'b', text: "L'hôpital", isCorrect: false },
      { id: 'c', text: "Un restaurant privé", isCorrect: true },
      { id: 'd', text: "La police", isCorrect: false },
    ],
    correctAnswer: "Un restaurant privé",
    explanation: "L'école, l'hôpital et la police sont des services publics (gérés par l'État). Un restaurant privé est une entreprise commerciale. Les services publics sont accessibles à tous, souvent gratuitement.",
    hint: "Service public = géré par l'État pour tous. Restaurant = entreprise privée.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-011',
    subject: 'histoire_geo',
    title: "Le réseau ferroviaire",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France possède l'un des plus importants réseaux de trains à grande vitesse d'Europe. Comment s'appelle ce train ?",
    options: [
      { id: 'a', text: "Le TER (Transport Express Régional)", isCorrect: false },
      { id: 'b', text: "Le TGV (Train à Grande Vitesse)", isCorrect: true },
      { id: 'c', text: "L'Eurostar", isCorrect: false },
      { id: 'd', text: "Le RER (Réseau Express Régional)", isCorrect: false },
    ],
    correctAnswer: "Le TGV (Train à Grande Vitesse)",
    explanation: "Le TGV (Train à Grande Vitesse) permet de traverser la France très rapidement (Paris-Lyon en 2h, Paris-Marseille en 3h). La SNCF exploite le réseau ferroviaire national.",
    hint: "TGV = Train à Grande Vitesse, le plus rapide des trains français.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-012',
    subject: 'histoire_geo',
    title: "Les ports maritimes",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le plus grand port commercial de France ?",
    options: [
      { id: 'a', text: "Bordeaux", isCorrect: false },
      { id: 'b', text: "Le Havre", isCorrect: true },
      { id: 'c', text: "Brest", isCorrect: false },
      { id: 'd', text: "Calais", isCorrect: false },
    ],
    correctAnswer: "Le Havre",
    explanation: "Le Havre (Seine-Maritime, Normandie) est le 1er port commercial de France et l'un des plus importants d'Europe. Il accueille des millions de conteneurs chaque année.",
    hint: "Le Havre est à l'embouchure de la Seine, en Normandie.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-013',
    subject: 'histoire_geo',
    title: "Le télétravail",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le télétravail consiste à travailler depuis chez soi grâce aux outils numériques. Quel impact a-t-il sur la géographie des lieux de vie ?",
    options: [
      { id: 'a', text: "Il ne change rien à l'organisation du territoire", isCorrect: false },
      { id: 'b', text: "Il permet de vivre plus loin du lieu de travail, favorisant certaines zones rurales ou périurbaines", isCorrect: true },
      { id: 'c', text: "Il oblige à vivre en ville", isCorrect: false },
      { id: 'd', text: "Il supprime le besoin d'internet haut débit", isCorrect: false },
    ],
    correctAnswer: "Il permet de vivre plus loin du lieu de travail, favorisant certaines zones rurales ou périurbaines",
    explanation: "Avec le télétravail, certains salariés peuvent s'installer à la campagne ou dans de petites villes tout en travaillant pour une entreprise parisienne. Cela transforme la géographie des habitats.",
    hint: "Télétravail → pas besoin d'être proche du bureau → on peut vivre en campagne.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-014',
    subject: 'histoire_geo',
    title: "Le patrimoine culturel",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'UNESCO (organisation mondiale) peut classer des sites comme « Patrimoine mondial de l'Humanité ». Lequel est un site français classé ?",
    options: [
      { id: 'a', text: "La tour Montparnasse (Paris)", isCorrect: false },
      { id: 'b', text: "Le Mont-Saint-Michel (Normandie)", isCorrect: true },
      { id: 'c', text: "La Défense (quartier d'affaires de Paris)", isCorrect: false },
      { id: 'd', text: "L'aéroport Charles-de-Gaulle", isCorrect: false },
    ],
    correctAnswer: "Le Mont-Saint-Michel (Normandie)",
    explanation: "Le Mont-Saint-Michel (inscrit en 1979) est une abbaye médiévale sur un rocher entouré de marées. C'est l'un des sites les plus visités de France.",
    hint: "Mont-Saint-Michel = abbaye sur un rocher en mer → UNESCO.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-015',
    subject: 'histoire_geo',
    title: "L'agriculture et les paysages",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La viticulture (culture de la vigne) est une activité agricole importante en France. Dans quelle région les vignobles de Bordeaux sont-ils situés ?",
    options: [
      { id: 'a', text: "En Bretagne", isCorrect: false },
      { id: 'b', text: "En Nouvelle-Aquitaine (autour de Bordeaux)", isCorrect: true },
      { id: 'c', text: "En Alsace uniquement", isCorrect: false },
      { id: 'd', text: "En Normandie", isCorrect: false },
    ],
    correctAnswer: "En Nouvelle-Aquitaine (autour de Bordeaux)",
    explanation: "Les vignobles de Bordeaux (Gironde, Nouvelle-Aquitaine) sont parmi les plus célèbres au monde. La France est l'un des premiers producteurs et exportateurs de vin.",
    hint: "Bordeaux → vin → vignobles de la Gironde.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-016',
    subject: 'histoire_geo',
    title: "Les aéroports",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le plus grand aéroport de France, situé au nord de Paris ?",
    options: [
      { id: 'a', text: "Orly", isCorrect: false },
      { id: 'b', text: "Roissy-Charles-de-Gaulle", isCorrect: true },
      { id: 'c', text: "Lyon Saint-Exupéry", isCorrect: false },
      { id: 'd', text: "Nice Côte d'Azur", isCorrect: false },
    ],
    correctAnswer: "Roissy-Charles-de-Gaulle",
    explanation: "L'aéroport Roissy-Charles-de-Gaulle (CDG), au nord de Paris, est le plus grand aéroport de France et l'un des plus importants d'Europe. Orly est le second aéroport parisien.",
    hint: "CDG = Charles de Gaulle = aéroport au nord de Paris = le plus grand de France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-017',
    subject: 'histoire_geo',
    title: "L'emploi en France",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, la grande majorité des emplois est dans le secteur tertiaire (services). Qu'est-ce que le secteur tertiaire ?",
    options: [
      { id: 'a', text: "L'agriculture et la pêche", isCorrect: false },
      { id: 'b', text: "L'ensemble des services : santé, commerce, éducation, banque, transport", isCorrect: true },
      { id: 'c', text: "L'industrie et la fabrication de produits", isCorrect: false },
      { id: 'd', text: "La construction de routes et de bâtiments", isCorrect: false },
    ],
    correctAnswer: "L'ensemble des services : santé, commerce, éducation, banque, transport",
    explanation: "Le secteur tertiaire regroupe tous les services non matériels : santé, éducation, commerce, transports, finance, tourisme. En France, environ 75% des emplois y appartiennent.",
    hint: "Tertiaire = services. Infirmier, vendeur, enseignant → secteur tertiaire.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-018',
    subject: 'histoire_geo',
    title: "Les voies navigables",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France possède un réseau de canaux et de rivières navigables (voies navigables). À quoi servent-elles principalement ?",
    options: [
      { id: 'a', text: "Au tourisme fluvial et au transport de marchandises lourdes", isCorrect: true },
      { id: 'b', text: "À la navigation militaire", isCorrect: false },
      { id: 'c', text: "À l'irrigation uniquement", isCorrect: false },
      { id: 'd', text: "À la pêche industrielle", isCorrect: false },
    ],
    correctAnswer: "Au tourisme fluvial et au transport de marchandises lourdes",
    explanation: "Les canaux et rivières navigables servent au transport de marchandises lourdes (pétrole, granulats) et au tourisme fluvial (péniches). La Seine, le Rhône et les canaux alsaciens sont très utilisés.",
    hint: "Canaux → péniches → marchandises lourdes + tourisme.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-019',
    subject: 'histoire_geo',
    title: "La ruralité économique",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Certains territoires ruraux font face à la « déprise » : commerces, services et habitants qui partent. Quelle est la conséquence principale pour les habitants qui restent ?",
    options: [
      { id: 'a', text: "Ils paient moins d'impôts", isCorrect: false },
      { id: 'b', text: "Ils doivent parcourir de longues distances pour accéder aux services", isCorrect: true },
      { id: 'c', text: "Leur qualité de vie s'améliore", isCorrect: false },
      { id: 'd', text: "Ils reçoivent plus d'aides de l'État", isCorrect: false },
    ],
    correctAnswer: "Ils doivent parcourir de longues distances pour accéder aux services",
    explanation: "La déprise rurale entraîne la fermeture des commerces, médecins, écoles et transports. Les habitants restants doivent faire de longs trajets pour accéder aux services essentiels.",
    hint: "Déprise rurale → fermetures → longs trajets pour médecin, boulangerie.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm1-geo-vfr-020',
    subject: 'histoire_geo',
    title: "Zone industrielle française",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'vivre_en_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La France est connue pour son industrie automobile. Dans quelle ville se trouve le siège social de Renault ?",
    options: [
      { id: 'a', text: "Strasbourg", isCorrect: false },
      { id: 'b', text: "Boulogne-Billancourt (région parisienne)", isCorrect: true },
      { id: 'c', text: "Bordeaux", isCorrect: false },
      { id: 'd', text: "Lyon", isCorrect: false },
    ],
    correctAnswer: "Boulogne-Billancourt (région parisienne)",
    explanation: "Renault, fondé en 1899, a son siège historique à Boulogne-Billancourt, dans la banlieue parisienne. La France possède aussi PSA (Peugeot-Citroën-Stellantis), basé à Paris.",
    hint: "Renault → banlieue parisienne → grande industrie automobile française.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
