import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm2GramCanCantExercises: EnglishExercise[] = [
  {
    id: 'en-cm2-gram-004',
    subject: 'anglais',
    title: 'Can : Can you speak French?',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « Can you speak French? » en français ?',
    options: [
      { id: 'a', text: 'Parles-tu français ?', isCorrect: true },
      { id: 'b', text: 'Tu aimes le français ?', isCorrect: false },
      { id: 'c', text: 'Tu apprends le français ?', isCorrect: false },
    ],
    correctAnswer: 'Parles-tu français ?',
    explanation: '« Can you » = peux-tu / sais-tu. « Speak French » = parler français.',
    hint: '« Can » en question = peux-tu ? / sais-tu ?',
    tags: ['cm2', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-005',
    subject: 'anglais',
    title: "Can't : contexte",
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Complète : « I ___ ride a bike, I don't have one. »",
    options: [
      { id: 'a', text: 'can', isCorrect: false },
      { id: 'b', text: "can't", isCorrect: true },
      { id: 'c', text: 'am not', isCorrect: false },
    ],
    correctAnswer: "can't",
    explanation: "La phrase dit qu'il n'a pas de vélo donc il ne peut pas en faire : can't.",
    hint: "Pas de vélo → impossible → can't.",
    tags: ['cm2', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis toute la phrase.', 'A-t-il un vélo ?', "Non → impossible → can't."] },
    }),
  },
  {
    id: 'en-cm2-gram-006',
    subject: 'anglais',
    title: 'Can : We can play',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « We can play football » en français ?',
    options: [
      { id: 'a', text: 'Nous voulons jouer au football.', isCorrect: false },
      { id: 'b', text: 'Nous pouvons jouer au football.', isCorrect: true },
      { id: 'c', text: 'Nous jouons au football.', isCorrect: false },
    ],
    correctAnswer: 'Nous pouvons jouer au football.',
    explanation: '« We can » = nous pouvons. « Play football » = jouer au football.',
    hint: '« Can » = pouvoir.',
    tags: ['cm2', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-010',
    subject: 'anglais',
    title: "Can't : They can't fly",
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: "Que veut dire « They can't fly » en français ?",
    options: [
      { id: 'a', text: 'Ils peuvent voler.', isCorrect: false },
      { id: 'b', text: 'Ils aiment voler.', isCorrect: false },
      { id: 'c', text: 'Ils ne peuvent pas voler.', isCorrect: true },
    ],
    correctAnswer: 'Ils ne peuvent pas voler.',
    explanation: "« They can't » = ils ne peuvent pas. « Fly » = voler.",
    hint: "« Can't » = ne peut/peuvent pas.",
    tags: ['cm2', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
