import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm2VocEnvironmentExercises: EnglishExercise[] = [
  {
    id: 'en-cm2-voc-019',
    subject: 'anglais',
    title: 'Environnement : environment',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « environment » en français ?',
    options: [
      { id: 'a', text: 'L\'entourage (personnes)', isCorrect: false },
      { id: 'b', text: 'L\'environnement / la nature', isCorrect: true },
      { id: 'c', text: 'L\'environnement urbain uniquement', isCorrect: false },
    ],
    correctAnswer: 'L\'environnement / la nature',
    explanation: '« Environment » = environnement. Même mot qu\'en français (presque) !',
    hint: 'Même racine qu\'en français.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-020',
    subject: 'anglais',
    title: 'Environnement : pollution',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « pollution » en français ?',
    options: [
      { id: 'a', text: 'La population', isCorrect: false },
      { id: 'b', text: 'La pollution', isCorrect: true },
      { id: 'c', text: 'La solution', isCorrect: false },
    ],
    correctAnswer: 'La pollution',
    explanation: '« Pollution » = pollution. Même mot ! Un faux ami à ne pas confondre avec « population ».',
    hint: 'Même mot qu\'en français.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-021',
    subject: 'anglais',
    title: 'Environnement : recycle',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « to recycle » en français ?',
    options: [
      { id: 'a', text: 'Jeter à la poubelle', isCorrect: false },
      { id: 'b', text: 'Recycler', isCorrect: true },
      { id: 'c', text: 'Brûler les déchets', isCorrect: false },
    ],
    correctAnswer: 'Recycler',
    explanation: '« To recycle » = recycler. Même mot qu\'en français !',
    hint: 'Même mot qu\'en français.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-022',
    subject: 'anglais',
    title: 'Environnement : solar panel',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « solar panel » en français ?',
    options: [
      { id: 'a', text: 'L\'éolienne', isCorrect: false },
      { id: 'b', text: 'Le panneau solaire', isCorrect: true },
      { id: 'c', text: 'Le barrage hydraulique', isCorrect: false },
    ],
    correctAnswer: 'Le panneau solaire',
    explanation: '« Solar » = solaire. « Panel » = panneau. Un panneau solaire capte l\'énergie du soleil.',
    hint: '« Solar » = solaire (du soleil).',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-023',
    subject: 'anglais',
    title: 'Environnement : wind turbine',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « wind turbine » en français ?',
    options: [
      { id: 'a', text: 'Le panneau solaire', isCorrect: false },
      { id: 'b', text: 'L\'éolienne', isCorrect: true },
      { id: 'c', text: 'Le moulin à eau', isCorrect: false },
    ],
    correctAnswer: 'L\'éolienne',
    explanation: '« Wind » = vent. « Turbine » = turbine. Une éolienne utilise le vent pour produire de l\'électricité.',
    hint: '« Wind » = vent. Ça tourne grâce au vent.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-024',
    subject: 'anglais',
    title: 'Environnement : greenhouse effect',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « greenhouse effect » en français ?',
    options: [
      { id: 'a', text: 'La serre de jardinage', isCorrect: false },
      { id: 'b', text: 'L\'effet de serre', isCorrect: true },
      { id: 'c', text: 'Le jardinage biologique', isCorrect: false },
    ],
    correctAnswer: 'L\'effet de serre',
    explanation: '« Greenhouse » = serre. « Effect » = effet. L\'effet de serre réchauffe la planète.',
    hint: '« Greenhouse » = serre. « Effect » = effet.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-025',
    subject: 'anglais',
    title: 'Environnement : endangered species',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « endangered species » en français ?',
    options: [
      { id: 'a', text: 'Les espèces invasives', isCorrect: false },
      { id: 'b', text: 'Les espèces en voie d\'extinction', isCorrect: true },
      { id: 'c', text: 'Les espèces protégées', isCorrect: false },
    ],
    correctAnswer: 'Les espèces en voie d\'extinction',
    explanation: '« Endangered » = en danger. « Species » = espèces. Ce sont des animaux ou plantes qui risquent de disparaître.',
    hint: '« Endangered » = en danger de disparition.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-026',
    subject: 'anglais',
    title: 'Environnement : rainforest',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « rainforest » en français ?',
    options: [
      { id: 'a', text: 'La forêt tempérée', isCorrect: false },
      { id: 'b', text: 'La forêt tropicale / la forêt humide', isCorrect: true },
      { id: 'c', text: 'La forêt de sapins', isCorrect: false },
    ],
    correctAnswer: 'La forêt tropicale / la forêt humide',
    explanation: '« Rain » = pluie. « Forest » = forêt. La rainforest est une forêt très humide (ex : Amazonie).',
    hint: '« Rain » = pluie. Forêt très pluvieuse.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-027',
    subject: 'anglais',
    title: 'Environnement : plastic waste',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « plastic waste » en français ?',
    options: [
      { id: 'a', text: 'Les bouteilles en plastique', isCorrect: false },
      { id: 'b', text: 'Les déchets plastiques', isCorrect: true },
      { id: 'c', text: 'Les objets recyclés', isCorrect: false },
    ],
    correctAnswer: 'Les déchets plastiques',
    explanation: '« Waste » = déchets, gaspillage. « Plastic waste » = les déchets en plastique.',
    hint: '« Waste » = déchets. « Plastic » = plastique.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-028',
    subject: 'anglais',
    title: 'Environnement : climate change',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « climate change » en français ?',
    options: [
      { id: 'a', text: 'La météo changeante', isCorrect: false },
      { id: 'b', text: 'Le changement climatique', isCorrect: true },
      { id: 'c', text: 'Le changement de saison', isCorrect: false },
    ],
    correctAnswer: 'Le changement climatique',
    explanation: '« Climate » = climat. « Change » = changement. C\'est un problème mondial majeur.',
    hint: '« Climate » = climat. « Change » = changement.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-029',
    subject: 'anglais',
    title: 'Environnement : reduce / reuse / recycle',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « reduce » dans l\'expression « reduce, reuse, recycle » ?',
    options: [
      { id: 'a', text: 'Recycler', isCorrect: false },
      { id: 'b', text: 'Réduire (les déchets)', isCorrect: true },
      { id: 'c', text: 'Réutiliser', isCorrect: false },
    ],
    correctAnswer: 'Réduire (les déchets)',
    explanation: '« Reduce » = réduire. « Reuse » = réutiliser. « Recycle » = recycler. Les 3R !',
    hint: 'Les 3R : reduce = réduire / reuse = réutiliser / recycle = recycler.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-030',
    subject: 'anglais',
    title: 'Environnement : renewable energy',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « renewable energy » en français ?',
    options: [
      { id: 'a', text: 'L\'énergie nucléaire', isCorrect: false },
      { id: 'b', text: 'L\'énergie renouvelable', isCorrect: true },
      { id: 'c', text: 'L\'énergie fossile', isCorrect: false },
    ],
    correctAnswer: 'L\'énergie renouvelable',
    explanation: '« Renewable » = renouvelable. « Energy » = énergie. Soleil, vent, eau → énergies renouvelables.',
    hint: '« Renewable » = qui peut se renouveler.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-031',
    subject: 'anglais',
    title: 'Environnement : carbon footprint',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « carbon footprint » en français ?',
    options: [
      { id: 'a', text: 'Les empreintes de pas', isCorrect: false },
      { id: 'b', text: 'L\'empreinte carbone', isCorrect: true },
      { id: 'c', text: 'La pollution de l\'air', isCorrect: false },
    ],
    correctAnswer: 'L\'empreinte carbone',
    explanation: '« Carbon » = carbone. « Footprint » = empreinte. L\'empreinte carbone mesure notre impact sur le climat.',
    hint: '« Footprint » = empreinte. « Carbon » = carbone.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-032',
    subject: 'anglais',
    title: 'Environnement : wildlife',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « wildlife » en français ?',
    options: [
      { id: 'a', text: 'La vie en plein air', isCorrect: false },
      { id: 'b', text: 'La faune sauvage / la vie sauvage', isCorrect: true },
      { id: 'c', text: 'Les animaux de compagnie', isCorrect: false },
    ],
    correctAnswer: 'La faune sauvage / la vie sauvage',
    explanation: '« Wild » = sauvage. « Life » = vie. « Wildlife » = la faune et flore sauvages.',
    hint: '« Wild » = sauvage. « Life » = vie.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-033',
    subject: 'anglais',
    title: 'Environnement : protect the planet',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « We must protect the planet » en français ?',
    options: [
      { id: 'a', text: 'Nous pourrions protéger la planète.', isCorrect: false },
      { id: 'b', text: 'Nous devons protéger la planète.', isCorrect: true },
      { id: 'c', text: 'Nous avons protégé la planète.', isCorrect: false },
    ],
    correctAnswer: 'Nous devons protéger la planète.',
    explanation: '« Must » = devoir (obligation). « Protect » = protéger. « Planet » = planète.',
    hint: '« Must » = devoir (obligation). « Protect » = protéger.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-034',
    subject: 'anglais',
    title: 'Environnement : ocean',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « Plastic waste is destroying our oceans » en français ?',
    options: [
      { id: 'a', text: 'Les déchets plastiques polluent légèrement les océans.', isCorrect: false },
      { id: 'b', text: 'Les déchets plastiques détruisent nos océans.', isCorrect: true },
      { id: 'c', text: 'Les déchets plastiques viennent des océans.', isCorrect: false },
    ],
    correctAnswer: 'Les déchets plastiques détruisent nos océans.',
    explanation: '« Destroying » = en train de détruire. « Oceans » = océans. « Plastic waste » = déchets plastiques.',
    hint: '« Destroying » = détruire (progressif). « Oceans » = océans.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'environnement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
