import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm2GramPastSimpleExercises: EnglishExercise[] = [
  {
    id: 'en-cm2-gram-038',
    subject: 'anglais',
    title: 'Past simple : deux ans ago',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « two years ago » en français ?',
    options: [
      { id: 'a', text: 'Dans deux ans', isCorrect: false },
      { id: 'b', text: 'Il y a deux ans', isCorrect: true },
      { id: 'c', text: 'Pendant deux ans', isCorrect: false },
    ],
    correctAnswer: 'Il y a deux ans',
    explanation: '« Ago » = il y a (dans le passé). « Two years ago » = il y a deux ans.',
    hint: '« Ago » = il y a (passé). « Two years » = deux ans.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-039',
    subject: 'anglais',
    title: 'Past simple consolidé : wrote',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « She wrote a letter to her friend » en français ?',
    options: [
      { id: 'a', text: 'Elle écrit une lettre à son amie.', isCorrect: false },
      { id: 'b', text: 'Elle a écrit une lettre à son amie.', isCorrect: true },
      { id: 'c', text: 'Elle va écrire une lettre à son amie.', isCorrect: false },
    ],
    correctAnswer: 'Elle a écrit une lettre à son amie.',
    explanation: '« Wrote » = past simple irrégulier de « write ». Write → wrote.',
    hint: '« Wrote » = past simple de « write » (irrégulier).',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-040',
    subject: 'anglais',
    title: 'Past simple consolidé : came',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « He came home late last night » en français ?',
    options: [
      { id: 'a', text: 'Il rentre tard à la maison ce soir.', isCorrect: false },
      { id: 'b', text: 'Il est rentré tard à la maison hier soir.', isCorrect: true },
      { id: 'c', text: 'Il va rentrer tard à la maison.', isCorrect: false },
    ],
    correctAnswer: 'Il est rentré tard à la maison hier soir.',
    explanation: '« Came » = past simple irrégulier de « come ». Come → came. « Last night » = hier soir.',
    hint: '« Came » = past simple de « come » (irrégulier). Come → came.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-041',
    subject: 'anglais',
    title: 'Past simple : question avec did',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne question.',
    prompt: 'Comment forme-t-on correctement une question au past simple ?',
    options: [
      { id: 'a', text: 'She visited Paris last year?', isCorrect: false },
      { id: 'b', text: 'Did she visit Paris last year?', isCorrect: true },
      { id: 'c', text: 'Did she visited Paris last year?', isCorrect: false },
    ],
    correctAnswer: 'Did she visit Paris last year?',
    explanation: 'Question : Did + sujet + verbe base. Pas de -ed après Did.',
    hint: 'Did + sujet + infinitif (sans -ed).',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-042',
    subject: 'anglais',
    title: 'Past simple : réponse courte',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse courte.',
    prompt: '« Did you enjoy the concert? » → Oui (réponse courte)',
    options: [
      { id: 'a', text: 'Yes, I enjoyed.', isCorrect: false },
      { id: 'b', text: 'Yes, I did.', isCorrect: true },
      { id: 'c', text: 'Yes, I do.', isCorrect: false },
    ],
    correctAnswer: 'Yes, I did.',
    explanation: 'Réponse courte positive : Yes, + pronom + did. (Pas de verbe en entier.)',
    hint: 'Réponse courte positive au past simple = Yes, + pronom + did.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-043',
    subject: 'anglais',
    title: 'Past simple : négation courte',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse courte négative.',
    prompt: '« Did they win the match? » → Non (réponse courte)',
    options: [
      { id: 'a', text: 'No, they didn\'t win.', isCorrect: false },
      { id: 'b', text: 'No, they didn\'t.', isCorrect: true },
      { id: 'c', text: 'No, they don\'t.', isCorrect: false },
    ],
    correctAnswer: 'No, they didn\'t.',
    explanation: 'Réponse courte négative : No, + pronom + didn\'t.',
    hint: 'Réponse courte négative au past simple = No, + pronom + didn\'t.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-044',
    subject: 'anglais',
    title: 'Past simple : when',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « When I arrived, she was cooking » en français ?',
    options: [
      { id: 'a', text: 'Quand j\'arriverai, elle cuisinera.', isCorrect: false },
      { id: 'b', text: 'Quand je suis arrivé, elle cuisinait.', isCorrect: true },
      { id: 'c', text: 'Quand j\'arrive, elle cuisine.', isCorrect: false },
    ],
    correctAnswer: 'Quand je suis arrivé, elle cuisinait.',
    explanation: '« When I arrived » (past simple = action ponctuelle) + « was cooking » (action en cours).',
    hint: '« When » = quand. « Arrived » = suis arrivé(e).',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-045',
    subject: 'anglais',
    title: 'Past simple : because',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « She stayed at home because it rained » en français ?',
    options: [
      { id: 'a', text: 'Elle reste à la maison quand il pleut.', isCorrect: false },
      { id: 'b', text: 'Elle est restée à la maison parce qu\'il pleuvait.', isCorrect: true },
      { id: 'c', text: 'Elle est sortie malgré la pluie.', isCorrect: false },
    ],
    correctAnswer: 'Elle est restée à la maison parce qu\'il pleuvait.',
    explanation: '« Stayed » = est restée. « Because » = parce que. « Rained » = il pleuvait / il a plu.',
    hint: '« Because » = parce que. « Stayed » = est resté(e).',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-046',
    subject: 'anglais',
    title: 'Past simple : irrégulier took',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « He took a photo of the eiffel tower » en français ?',
    options: [
      { id: 'a', text: 'Il prend une photo de la Tour Eiffel.', isCorrect: false },
      { id: 'b', text: 'Il a pris une photo de la Tour Eiffel.', isCorrect: true },
      { id: 'c', text: 'Il regardait la Tour Eiffel.', isCorrect: false },
    ],
    correctAnswer: 'Il a pris une photo de la Tour Eiffel.',
    explanation: '« Took » = past simple irrégulier de « take ». Take → took.',
    hint: '« Took » = past simple de « take » (irrégulier). Take → took.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-047',
    subject: 'anglais',
    title: 'Past simple : irrégulier bought',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « My mum bought new shoes yesterday » en français ?',
    options: [
      { id: 'a', text: 'Ma maman achète de nouvelles chaussures.', isCorrect: false },
      { id: 'b', text: 'Ma maman a acheté de nouvelles chaussures hier.', isCorrect: true },
      { id: 'c', text: 'Ma maman voulait acheter des chaussures.', isCorrect: false },
    ],
    correctAnswer: 'Ma maman a acheté de nouvelles chaussures hier.',
    explanation: '« Bought » = past simple irrégulier de « buy ». Buy → bought.',
    hint: '« Bought » = past simple de « buy » (irrégulier). Buy → bought.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-048',
    subject: 'anglais',
    title: 'Past simple : time markers récapitulatif',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis le bon marqueur de temps.',
    prompt: 'Laquelle de ces expressions n\'accompagne PAS le past simple ?',
    options: [
      { id: 'a', text: 'Yesterday', isCorrect: false },
      { id: 'b', text: 'Last week', isCorrect: false },
      { id: 'c', text: 'Tomorrow', isCorrect: true },
    ],
    correctAnswer: 'Tomorrow',
    explanation: '« Tomorrow » = demain → futur. « Yesterday » et « last week » → passé = past simple.',
    hint: '« Tomorrow » = demain. Le past simple parle du passé.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-049',
    subject: 'anglais',
    title: 'Past simple : régulier loved',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « We ___ the show last Saturday. » (love)',
    options: [
      { id: 'a', text: 'love', isCorrect: false },
      { id: 'b', text: 'loved', isCorrect: true },
      { id: 'c', text: 'loves', isCorrect: false },
    ],
    correctAnswer: 'loved',
    explanation: '« Last Saturday » → passé. « Love » → « loved » (+ -d car le verbe finit en -e).',
    hint: '« Last Saturday » → passé. Love → loved.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-050',
    subject: 'anglais',
    title: 'Past simple : irrégulier knew',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « She knew the answer immediately » en français ?',
    options: [
      { id: 'a', text: 'Elle connaît la réponse maintenant.', isCorrect: false },
      { id: 'b', text: 'Elle a su la réponse immédiatement.', isCorrect: true },
      { id: 'c', text: 'Elle cherchait la réponse.', isCorrect: false },
    ],
    correctAnswer: 'Elle a su la réponse immédiatement.',
    explanation: '« Knew » = past simple irrégulier de « know ». Know → knew.',
    hint: '« Knew » = past simple de « know » (irrégulier). Know → knew.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-051',
    subject: 'anglais',
    title: 'Past simple : question ouverte',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « Where did you go last summer? » en français ?',
    options: [
      { id: 'a', text: 'Où vas-tu cet été ?', isCorrect: false },
      { id: 'b', text: 'Où es-tu allé(e) l\'été dernier ?', isCorrect: true },
      { id: 'c', text: 'Où iras-tu l\'été prochain ?', isCorrect: false },
    ],
    correctAnswer: 'Où es-tu allé(e) l\'été dernier ?',
    explanation: '« Where did you go » = où es-tu allé(e) ? « Last summer » = l\'été dernier.',
    hint: '« Where did you go » = où es-tu allé(e) ? (passé)',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-052',
    subject: 'anglais',
    title: 'Past simple : irrégulier thought',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I thought the film was boring » en français ?',
    options: [
      { id: 'a', text: 'Je pense que le film est ennuyeux.', isCorrect: false },
      { id: 'b', text: 'J\'ai trouvé que le film était ennuyeux.', isCorrect: true },
      { id: 'c', text: 'Je voudrais voir un film ennuyeux.', isCorrect: false },
    ],
    correctAnswer: 'J\'ai trouvé que le film était ennuyeux.',
    explanation: '« Thought » = past simple irrégulier de « think ». Think → thought.',
    hint: '« Thought » = past simple de « think » (irrégulier). Think → thought.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-053',
    subject: 'anglais',
    title: 'Past simple : forme courte négative',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la phrase correcte.',
    prompt: 'Laquelle de ces phrases est correcte ?',
    options: [
      { id: 'a', text: 'We not went to school yesterday.', isCorrect: false },
      { id: 'b', text: 'We didn\'t go to school yesterday.', isCorrect: true },
      { id: 'c', text: 'We didn\'t went to school yesterday.', isCorrect: false },
    ],
    correctAnswer: 'We didn\'t go to school yesterday.',
    explanation: 'Négation past simple : didn\'t + infinitif. Pas « didn\'t went ».',
    hint: 'didn\'t + infinitif (go, pas went).',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-054',
    subject: 'anglais',
    title: 'Past simple : ago vs last',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne expression.',
    prompt: 'Comment dit-on « il y a trois jours » en anglais ?',
    options: [
      { id: 'a', text: 'Last three days', isCorrect: false },
      { id: 'b', text: 'Three days ago', isCorrect: true },
      { id: 'c', text: 'Before three days', isCorrect: false },
    ],
    correctAnswer: 'Three days ago',
    explanation: '« Ago » se place APRÈS la durée : « three days ago » = il y a trois jours.',
    hint: '« Ago » se place après la durée : X + ago = il y a X.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-055',
    subject: 'anglais',
    title: 'Past simple : révision complète',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Lis ce texte et réponds.',
    prompt: '« Last weekend, Jack and his family drove to the seaside. They swam in the sea and ate fish and chips. Jack didn\'t want to leave. »\nQu\'a mangé la famille ?',
    options: [
      { id: 'a', text: 'Des sandwichs', isCorrect: false },
      { id: 'b', text: 'Du fish and chips', isCorrect: true },
      { id: 'c', text: 'Des glaces', isCorrect: false },
    ],
    correctAnswer: 'Du fish and chips',
    explanation: '« Ate fish and chips » = ont mangé du fish and chips.',
    hint: '« Ate » = passé de « eat ». Fish and chips = plat anglais classique.',
    tags: ['cm2', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
];
