import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm2CommExercises: EnglishExercise[] = [
  {
    id: 'en-cm2-comp-008',
    subject: 'anglais',
    title: 'Dialogue : at the restaurant',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue au restaurant.',
    prompt: '— « Are you ready to order? »\n— « Yes, I\'d like the pasta, please. »\nQue commande la personne ?',
    options: [
      { id: 'a', text: 'Une pizza', isCorrect: false },
      { id: 'b', text: 'Des pâtes', isCorrect: true },
      { id: 'c', text: 'Une soupe', isCorrect: false },
    ],
    correctAnswer: 'Des pâtes',
    explanation: '« Pasta » = pâtes (mot emprunté à l\'italien). « I\'d like » = je voudrais.',
    hint: '« Pasta » = pâtes (mot italien utilisé en anglais).',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-009',
    subject: 'anglais',
    title: 'Dialogue : on the phone',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue téléphonique.',
    prompt: '— « Hello, this is Emma speaking. »\nQue veut dire cette formule ?',
    options: [
      { id: 'a', text: 'Bonjour, Emma est là.', isCorrect: false },
      { id: 'b', text: 'Bonjour, c\'est Emma à l\'appareil.', isCorrect: true },
      { id: 'c', text: 'Bonjour, je cherche Emma.', isCorrect: false },
    ],
    correctAnswer: 'Bonjour, c\'est Emma à l\'appareil.',
    explanation: '« This is… speaking » = c\'est… à l\'appareil. Formule téléphonique standard.',
    hint: '« This is Emma speaking » = formule pour se présenter au téléphone.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-010',
    subject: 'anglais',
    title: 'Dialogue : shopping',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue en magasin.',
    prompt: '— « Do you have this in a bigger size? »\nQue demande le client ?',
    options: [
      { id: 'a', text: 'Si l\'article existe en couleur différente', isCorrect: false },
      { id: 'b', text: 'Si l\'article existe en taille plus grande', isCorrect: true },
      { id: 'c', text: 'Si l\'article est en solde', isCorrect: false },
    ],
    correctAnswer: 'Si l\'article existe en taille plus grande',
    explanation: '« Bigger size » = taille plus grande. « Do you have… ? » = Avez-vous… ?',
    hint: '« Size » = taille. « Bigger » = plus grand.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-011',
    subject: 'anglais',
    title: 'Dialogue : giving advice',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « You should eat more vegetables » en français ?',
    options: [
      { id: 'a', text: 'Tu manges trop de légumes.', isCorrect: false },
      { id: 'b', text: 'Tu devrais manger plus de légumes.', isCorrect: true },
      { id: 'c', text: 'Tu aimeras les légumes.', isCorrect: false },
    ],
    correctAnswer: 'Tu devrais manger plus de légumes.',
    explanation: '« Should » = devoir (conseil). « You should… » = tu devrais…',
    hint: '« Should » = devoir / il faudrait.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-012',
    subject: 'anglais',
    title: 'Dialogue : agreeing',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Ton ami dit une idée et tu es d\'accord. Comment réponds-tu ?',
    options: [
      { id: 'a', text: 'I disagree.', isCorrect: false },
      { id: 'b', text: 'I agree!', isCorrect: true },
      { id: 'c', text: 'I don\'t think so.', isCorrect: false },
    ],
    correctAnswer: 'I agree!',
    explanation: '« I agree » = je suis d\'accord. « I disagree » = je ne suis pas d\'accord.',
    hint: '« Agree » = être d\'accord.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-013',
    subject: 'anglais',
    title: 'Dialogue : making plans',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « What are you doing this Saturday? »\n— « I\'m not sure yet. Why? »\nQue signifie « I\'m not sure yet » ?',
    options: [
      { id: 'a', text: 'Je suis occupé(e).', isCorrect: false },
      { id: 'b', text: 'Je ne sais pas encore.', isCorrect: true },
      { id: 'c', text: 'Je ne veux pas sortir.', isCorrect: false },
    ],
    correctAnswer: 'Je ne sais pas encore.',
    explanation: '« Not sure » = pas certain(e). « Yet » = encore / pour l\'instant.',
    hint: '« Not sure » = pas sûr(e) / je ne sais pas.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-014',
    subject: 'anglais',
    title: 'Dialogue : complaining',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « I\'m afraid this soup is cold. »\nQue veut dire « I\'m afraid… » dans ce contexte ?',
    options: [
      { id: 'a', text: 'J\'ai peur de la soupe.', isCorrect: false },
      { id: 'b', text: 'Je suis désolé(e) de dire que…', isCorrect: true },
      { id: 'c', text: 'Je n\'aime pas la soupe.', isCorrect: false },
    ],
    correctAnswer: 'Je suis désolé(e) de dire que…',
    explanation: '« I\'m afraid… » (dans ce sens) = je suis désolé de vous dire que… (formule polie pour se plaindre).',
    hint: '« I\'m afraid » ici = formule polie pour annoncer un problème.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-015',
    subject: 'anglais',
    title: 'Dialogue : expressing surprise',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Ton ami annonce une grande nouvelle et tu es surpris. Que dis-tu ?',
    options: [
      { id: 'a', text: 'Of course!', isCorrect: false },
      { id: 'b', text: 'No way! / Really?', isCorrect: true },
      { id: 'c', text: 'I agree!', isCorrect: false },
    ],
    correctAnswer: 'No way! / Really?',
    explanation: '« No way! » = pas possible ! / c\'est incroyable ! « Really? » = vraiment ? Expressions de surprise.',
    hint: '« No way! » = expression de surprise (familière).',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-016',
    subject: 'anglais',
    title: 'Dialogue : at the doctor\'s',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « What\'s the matter? »\n— « I have a headache and a sore throat. »\nQue décrit l\'enfant ?',
    options: [
      { id: 'a', text: 'Il a mal au ventre et au dos.', isCorrect: false },
      { id: 'b', text: 'Il a mal à la tête et à la gorge.', isCorrect: true },
      { id: 'c', text: 'Il a de la fièvre et un rhume.', isCorrect: false },
    ],
    correctAnswer: 'Il a mal à la tête et à la gorge.',
    explanation: '« Headache » = mal de tête. « Sore throat » = mal de gorge. « What\'s the matter? » = Qu\'est-ce qui ne va pas ?',
    hint: '« Head » = tête. « Throat » = gorge.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-017',
    subject: 'anglais',
    title: 'Dialogue : talking about the future',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I\'m going to be a doctor when I grow up » en français ?',
    options: [
      { id: 'a', text: 'J\'aimerais être médecin.', isCorrect: false },
      { id: 'b', text: 'Je vais être médecin quand je serai grand(e).', isCorrect: true },
      { id: 'c', text: 'Je suis médecin.', isCorrect: false },
    ],
    correctAnswer: 'Je vais être médecin quand je serai grand(e).',
    explanation: '« I\'m going to… » = je vais… (futur planifié). « When I grow up » = quand je serai grand(e).',
    hint: '« When I grow up » = quand je grandis / serai grand(e).',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-018',
    subject: 'anglais',
    title: 'Dialogue : expressing preferences',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I prefer reading to watching TV » en français ?',
    options: [
      { id: 'a', text: 'J\'aime lire et regarder la télé.', isCorrect: false },
      { id: 'b', text: 'Je préfère lire plutôt que regarder la télé.', isCorrect: true },
      { id: 'c', text: 'Je ne lis pas parce que je regarde la télé.', isCorrect: false },
    ],
    correctAnswer: 'Je préfère lire plutôt que regarder la télé.',
    explanation: '« I prefer A to B » = je préfère A plutôt que B. Formule de préférence.',
    hint: '« I prefer A to B » = je préfère A plutôt que B.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-019',
    subject: 'anglais',
    title: 'Dialogue : directions (complex)',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ces directions.',
    prompt: '« Take the first left, then go straight on until you reach the roundabout. »\nQu\'est-ce qu\'un « roundabout » ?',
    options: [
      { id: 'a', text: 'Un feu rouge', isCorrect: false },
      { id: 'b', text: 'Un rond-point', isCorrect: true },
      { id: 'c', text: 'Un carrefour en T', isCorrect: false },
    ],
    correctAnswer: 'Un rond-point',
    explanation: '« Roundabout » = rond-point. « Take the first left » = prenez la première à gauche.',
    hint: '« Round » = rond → un « roundabout » tourne en rond.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-020',
    subject: 'anglais',
    title: 'Dialogue : narrative text',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce court texte.',
    prompt: '« Last Saturday, Jake went to the market with his grandmother. They bought fresh vegetables and some flowers. On the way home, it started to rain. »\nQue se passe-t-il au retour ?',
    options: [
      { id: 'a', text: 'Il fait beau sur le chemin du retour.', isCorrect: false },
      { id: 'b', text: 'Il commence à pleuvoir sur le chemin du retour.', isCorrect: true },
      { id: 'c', text: 'Ils s\'arrêtent dans un café sur le chemin du retour.', isCorrect: false },
    ],
    correctAnswer: 'Il commence à pleuvoir sur le chemin du retour.',
    explanation: '« It started to rain » = il a commencé à pleuvoir. « On the way home » = sur le chemin du retour.',
    hint: '« Rain » = pluie. « Started to » = a commencé à.',
    tags: ['cm2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
];
