import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm2VocHobbiesExercises: EnglishExercise[] = [
  {
    id: 'en-cm2-voc-007',
    subject: 'anglais',
    title: 'Hobbies : martial arts',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « martial arts » en français ?',
    options: [
      { id: 'a', text: 'Les arts plastiques', isCorrect: false },
      { id: 'b', text: 'Les arts martiaux', isCorrect: true },
      { id: 'c', text: 'Les arts de la scène', isCorrect: false },
    ],
    correctAnswer: 'Les arts martiaux',
    explanation: '« Martial arts » = arts martiaux (judo, karaté, kung-fu…). Même terme qu\'en français !',
    hint: 'Ce terme est presque identique en français.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-008',
    subject: 'anglais',
    title: 'Hobbies : hiking',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « hiking » en français ?',
    options: [
      { id: 'a', text: 'Le cyclisme', isCorrect: false },
      { id: 'b', text: 'La randonnée', isCorrect: true },
      { id: 'c', text: 'Le camping', isCorrect: false },
    ],
    correctAnswer: 'La randonnée',
    explanation: '« Hiking » = la randonnée (marcher en pleine nature). « To hike » = faire de la randonnée.',
    hint: '« Hike » = marche en nature / randonnée.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-009',
    subject: 'anglais',
    title: 'Hobbies : volunteering',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « volunteering » en français ?',
    options: [
      { id: 'a', text: 'Le bénévolat', isCorrect: true },
      { id: 'b', text: 'Le volontariat militaire', isCorrect: false },
      { id: 'c', text: 'L\'entrepreneuriat', isCorrect: false },
    ],
    correctAnswer: 'Le bénévolat',
    explanation: '« Volunteering » = le bénévolat (travailler pour aider gratuitement). « Volunteer » = bénévole.',
    hint: '« Volunteer » = quelqu\'un qui aide sans être payé.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-010',
    subject: 'anglais',
    title: 'Hobbies : collecting',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « collecting stamps » en français ?',
    options: [
      { id: 'a', text: 'Envoyer des lettres', isCorrect: false },
      { id: 'b', text: 'Collectionner des timbres', isCorrect: true },
      { id: 'c', text: 'Acheter des cartes postales', isCorrect: false },
    ],
    correctAnswer: 'Collectionner des timbres',
    explanation: '« Collecting » = collectionner. « Stamps » = timbres (postaux).',
    hint: '« Collect » = ramasser / collectionner.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-011',
    subject: 'anglais',
    title: 'Hobbies : team sport',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « team sport » en français ?',
    options: [
      { id: 'a', text: 'Sport individuel', isCorrect: false },
      { id: 'b', text: 'Sport collectif / d\'équipe', isCorrect: true },
      { id: 'c', text: 'Sport d\'hiver', isCorrect: false },
    ],
    correctAnswer: 'Sport collectif / d\'équipe',
    explanation: '« Team » = équipe. « Team sport » = sport d\'équipe (football, basketball, rugby…).',
    hint: '« Team » = équipe.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-012',
    subject: 'anglais',
    title: 'Hobbies : I\'m into…',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « I\'m really into music » en français ?',
    options: [
      { id: 'a', text: 'Je déteste la musique.', isCorrect: false },
      { id: 'b', text: 'Je suis vraiment passionné(e) de musique.', isCorrect: true },
      { id: 'c', text: 'Je fais de la musique parfois.', isCorrect: false },
    ],
    correctAnswer: 'Je suis vraiment passionné(e) de musique.',
    explanation: '« I\'m into… » = je suis passionné(e) par… (expression familière). « Really » = vraiment.',
    hint: '« I\'m into » = familier pour dire qu\'on est fan / passionné.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-013',
    subject: 'anglais',
    title: 'Hobbies : spare time',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « spare time » en français ?',
    options: [
      { id: 'a', text: 'Le temps d\'attente', isCorrect: false },
      { id: 'b', text: 'Le temps libre', isCorrect: true },
      { id: 'c', text: 'L\'heure de récréation', isCorrect: false },
    ],
    correctAnswer: 'Le temps libre',
    explanation: '« Spare time » = temps libre. Synonyme de « free time ».',
    hint: '« Spare » = de réserve / disponible.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-014',
    subject: 'anglais',
    title: 'Hobbies : creative hobby',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « knitting » en français ?',
    options: [
      { id: 'a', text: 'La couture', isCorrect: false },
      { id: 'b', text: 'Le tricot', isCorrect: true },
      { id: 'c', text: 'La broderie', isCorrect: false },
    ],
    correctAnswer: 'Le tricot',
    explanation: '« Knitting » = le tricot (faire des pulls, écharpes avec des aiguilles à tricoter).',
    hint: 'On utilise des aiguilles et de la laine.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-015',
    subject: 'anglais',
    title: 'Hobbies : physical activity',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « I work out at the gym » en français ?',
    options: [
      { id: 'a', text: 'Je travaille dans une salle de sport.', isCorrect: false },
      { id: 'b', text: 'Je m\'entraîne en salle de sport.', isCorrect: true },
      { id: 'c', text: 'Je fais du yoga à la maison.', isCorrect: false },
    ],
    correctAnswer: 'Je m\'entraîne en salle de sport.',
    explanation: '« Work out » = s\'entraîner (faire du sport). « Gym » = salle de sport.',
    hint: '« Work out » = faire de l\'exercice / s\'entraîner.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-016',
    subject: 'anglais',
    title: 'Hobbies : at the weekend',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I hang out with my friends at the weekend » ?',
    options: [
      { id: 'a', text: 'Je me bats avec mes amis le week-end.', isCorrect: false },
      { id: 'b', text: 'Je traîne / retrouve mes amis le week-end.', isCorrect: true },
      { id: 'c', text: 'J\'attends mes amis le week-end.', isCorrect: false },
    ],
    correctAnswer: 'Je traîne / retrouve mes amis le week-end.',
    explanation: '« Hang out with » = traîner avec / passer du temps avec (expression familière).',
    hint: '« Hang out » = passer du temps informellement avec des amis.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-017',
    subject: 'anglais',
    title: 'Hobbies : social media',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « scrolling through social media » en français ?',
    options: [
      { id: 'a', text: 'Créer des vidéos pour internet', isCorrect: false },
      { id: 'b', text: 'Faire défiler les réseaux sociaux', isCorrect: true },
      { id: 'c', text: 'Jouer à des jeux en ligne', isCorrect: false },
    ],
    correctAnswer: 'Faire défiler les réseaux sociaux',
    explanation: '« Scrolling » = faire défiler. « Social media » = réseaux sociaux.',
    hint: '« Scroll » = faire défiler avec le doigt ou la souris.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-018',
    subject: 'anglais',
    title: 'Hobbies : le bon mot',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Choisis le bon mot anglais.',
    prompt: 'Comment dit-on « la randonnée » en anglais ?',
    options: [
      { id: 'a', text: 'cycling', isCorrect: false },
      { id: 'b', text: 'hiking', isCorrect: true },
      { id: 'c', text: 'volunteering', isCorrect: false },
    ],
    correctAnswer: 'hiking',
    explanation: '« Hiking » = randonnée. « Cycling » = vélo. « Volunteering » = bénévolat.',
    hint: 'On marche en pleine nature.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
