import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm2GramPlurielExercises: EnglishExercise[] = [
  {
    id: 'en-cm2-gram-001',
    subject: 'anglais',
    title: 'Pluriel : cats',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot anglais ?',
    prompt: 'Quel est le pluriel de « cat » ?',
    options: [
      { id: 'a', text: 'cats', isCorrect: true },
      { id: 'b', text: 'cates', isCorrect: false },
      { id: 'c', text: 'caties', isCorrect: false },
    ],
    correctAnswer: 'cats',
    explanation: 'En anglais, on ajoute généralement « s » pour former le pluriel : cat → cats.',
    hint: 'En anglais, le pluriel le plus courant se forme en ajoutant « s ».',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-002',
    subject: 'anglais',
    title: 'Pluriel : boxes',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot anglais ?',
    prompt: 'Quel est le pluriel de « box » ?',
    options: [
      { id: 'a', text: 'boxs', isCorrect: false },
      { id: 'b', text: 'boxes', isCorrect: true },
      { id: 'c', text: 'boxies', isCorrect: false },
    ],
    correctAnswer: 'boxes',
    explanation: 'Les mots finissant par -x, -s, -sh, -ch prennent « es » au pluriel : box → boxes.',
    hint: 'Les mots en -x prennent « es » : box → boxes.',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis le bon pluriel.', extraHint: 'box → boxes (comme "boîtes").' },
    }),
  },
  {
    id: 'en-cm2-gram-003',
    subject: 'anglais',
    title: 'Pluriel irrégulier : children',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot ?',
    prompt: 'Quel est le pluriel irrégulier de « child » (enfant) ?',
    options: [
      { id: 'a', text: 'childs', isCorrect: false },
      { id: 'b', text: 'childes', isCorrect: false },
      { id: 'c', text: 'children', isCorrect: true },
    ],
    correctAnswer: 'children',
    explanation: '« Child » a un pluriel irrégulier : children (comme "man" → "men").',
    hint: 'Certains pluriels en anglais sont irréguliers.',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Trouve un autre pluriel irrégulier anglais.' },
    }),
  },
  {
    id: 'en-cm2-gram-007',
    subject: 'anglais',
    title: 'Pluriel : dogs',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot anglais ?',
    prompt: 'Quel est le pluriel de « dog » ?',
    options: [
      { id: 'a', text: 'dogies', isCorrect: false },
      { id: 'b', text: 'dogs', isCorrect: true },
      { id: 'c', text: 'doges', isCorrect: false },
    ],
    correctAnswer: 'dogs',
    explanation: 'En anglais, on ajoute « s » pour le pluriel : dog → dogs.',
    hint: 'La règle générale : mot + s.',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-008',
    subject: 'anglais',
    title: 'Pluriel : dishes',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot anglais ?',
    prompt: 'Quel est le pluriel de « dish » (assiette) ?',
    options: [
      { id: 'a', text: 'dishes', isCorrect: true },
      { id: 'b', text: 'dishs', isCorrect: false },
      { id: 'c', text: 'dishies', isCorrect: false },
    ],
    correctAnswer: 'dishes',
    explanation: 'Les mots en -sh, -ch, -x, -s prennent « es » au pluriel : dish → dishes.',
    hint: 'Les mots en -sh prennent « es ».',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis le bon pluriel.', extraHint: 'dish → dishes.' },
    }),
  },
  {
    id: 'en-cm2-gram-009',
    subject: 'anglais',
    title: 'Pluriel irrégulier : men',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel irrégulier de ce mot ?',
    prompt: 'Quel est le pluriel de « man » (homme) ?',
    options: [
      { id: 'a', text: 'mans', isCorrect: false },
      { id: 'b', text: 'manes', isCorrect: false },
      { id: 'c', text: 'men', isCorrect: true },
    ],
    correctAnswer: 'men',
    explanation: '« Man » a un pluriel irrégulier : men (comme « child » → « children »).',
    hint: 'Ce pluriel change complètement le mot.',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
