import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCe1MatiereExercises: ScienceExercise[] = [
  {
    id: 'sc-ce1-mat-001',
    subject: 'sciences',
    title: 'États de la matière : les 3 états',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'etats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quels sont les trois états de la matière ?',
    options: [
      { id: 'a', text: 'Dur, mou, fondant', isCorrect: false },
      { id: 'b', text: 'Solide, liquide, gazeux', isCorrect: true },
      { id: 'c', text: 'Chaud, tiède, froid', isCorrect: false },
    ],
    correctAnswer: 'Solide, liquide, gazeux',
    explanation: 'La matière peut exister sous trois états : solide (glace), liquide (eau), gazeux (vapeur).',
    hint: 'Pense à l\'eau sous ses différentes formes.',
    tags: ['ce1', 'sciences', 'matiere', 'etats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-002',
    subject: 'sciences',
    title: 'Changement d\'état : fusion',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'changements-etat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment s\'appelle le passage de l\'état solide à l\'état liquide ?',
    options: [
      { id: 'a', text: 'La solidification', isCorrect: false },
      { id: 'b', text: 'La fusion', isCorrect: true },
      { id: 'c', text: 'L\'évaporation', isCorrect: false },
    ],
    correctAnswer: 'La fusion',
    explanation: 'La fusion est le passage du solide au liquide (ex : glace → eau). Elle se produit en chauffant.',
    hint: 'Un glaçon fond dans un verre chaud.',
    tags: ['ce1', 'sciences', 'matiere', 'fusion', 'changements-etat', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-003',
    subject: 'sciences',
    title: 'Changement d\'état : solidification',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'changements-etat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le passage de l\'eau liquide à l\'état solide (glace) ?',
    options: [
      { id: 'a', text: 'La solidification', isCorrect: true },
      { id: 'b', text: 'La fusion', isCorrect: false },
      { id: 'c', text: 'L\'évaporation', isCorrect: false },
    ],
    correctAnswer: 'La solidification',
    explanation: 'La solidification est le passage du liquide au solide. L\'eau se solidifie à 0°C pour former de la glace.',
    hint: 'Le contraire de la fusion.',
    tags: ['ce1', 'sciences', 'matiere', 'solidification', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-004',
    subject: 'sciences',
    title: 'Matériaux : conducteur ou isolant',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel matériau conduit le mieux la chaleur ?',
    options: [
      { id: 'a', text: 'Le plastique', isCorrect: false },
      { id: 'b', text: 'Le métal', isCorrect: true },
      { id: 'c', text: 'Le bois', isCorrect: false },
    ],
    correctAnswer: 'Le métal',
    explanation: 'Le métal est un bon conducteur de chaleur. C\'est pour cela que les casseroles ont des poignées en plastique ou bois.',
    hint: 'Pourquoi les poignées de casseroles ne sont-elles pas en métal ?',
    tags: ['ce1', 'sciences', 'materiaux', 'chaleur', 'conducteur', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-005',
    subject: 'sciences',
    title: 'Objets techniques : levier',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un levier ?',
    options: [
      { id: 'a', text: 'Un liquide qui aide à soulever', isCorrect: false },
      { id: 'b', text: 'Une barre rigide qui aide à soulever ou déplacer des objets', isCorrect: true },
      { id: 'c', text: 'Un type de roue', isCorrect: false },
    ],
    correctAnswer: 'Une barre rigide qui aide à soulever ou déplacer des objets',
    explanation: 'Le levier est une barre qui tourne autour d\'un point d\'appui. Il permet de soulever des charges plus facilement.',
    hint: 'La balançoire fonctionne comme un levier.',
    tags: ['ce1', 'sciences', 'objets-techniques', 'levier', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-006',
    subject: 'sciences',
    title: 'Mélange : sucre et eau',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'melanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il quand on met du sucre dans de l\'eau et qu\'on mélange ?',
    options: [
      { id: 'a', text: 'Le sucre flotte à la surface', isCorrect: false },
      { id: 'b', text: 'Le sucre se dissout dans l\'eau', isCorrect: true },
      { id: 'c', text: 'L\'eau devient solide', isCorrect: false },
    ],
    correctAnswer: 'Le sucre se dissout dans l\'eau',
    explanation: 'Le sucre est soluble dans l\'eau : il se dissout et disparaît. Le mélange devient sucré mais reste liquide.',
    hint: 'On ne voit plus le sucre, mais on le goûte.',
    tags: ['ce1', 'sciences', 'matiere', 'melanges', 'dissolution', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-007',
    subject: 'sciences',
    title: 'Objets techniques : roue et axe',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel outil utilise le principe de la vis pour soulever ?',
    options: [
      { id: 'a', text: 'Le marteau', isCorrect: false },
      { id: 'b', text: 'Le cric de voiture', isCorrect: true },
      { id: 'c', text: 'Les ciseaux', isCorrect: false },
    ],
    correctAnswer: 'Le cric de voiture',
    explanation: 'Le cric utilise une vis pour soulever une voiture. En tournant, la vis fait monter la charge.',
    hint: 'Il sert à soulever une voiture pour changer un pneu.',
    tags: ['ce1', 'sciences', 'objets-techniques', 'vis', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-008',
    subject: 'sciences',
    title: 'Matériaux : tissu',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où vient le tissu en coton ?',
    options: [
      { id: 'a', text: 'Des rochers', isCorrect: false },
      { id: 'b', text: 'De la plante du coton', isCorrect: true },
      { id: 'c', text: 'Du pétrole uniquement', isCorrect: false },
    ],
    correctAnswer: 'De la plante du coton',
    explanation: 'Le coton est une fibre naturelle qui vient de la plante du même nom. On en fait des T-shirts, des draps, etc.',
    hint: 'C\'est une plante qui produit des boules blanches.',
    tags: ['ce1', 'sciences', 'materiaux', 'coton', 'naturel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-009',
    subject: 'sciences',
    title: 'Mélange : sable et eau',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'melanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il quand on mélange du sable et de l\'eau, puis on attend ?',
    options: [
      { id: 'a', text: 'Le sable disparaît comme le sucre', isCorrect: false },
      { id: 'b', text: 'Le sable se dépose au fond', isCorrect: true },
      { id: 'c', text: 'L\'eau devient solide', isCorrect: false },
    ],
    correctAnswer: 'Le sable se dépose au fond',
    explanation: 'Le sable n\'est pas soluble dans l\'eau. Il se dépose au fond : c\'est un mélange non homogène.',
    hint: 'Le sable est plus lourd que l\'eau.',
    tags: ['ce1', 'sciences', 'matiere', 'melanges', 'sable', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-010',
    subject: 'sciences',
    title: 'Objets techniques : plan incliné',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi utilise-t-on une rampe inclinée pour monter des meubles dans un camion ?',
    options: [
      { id: 'a', text: 'Pour que ça aille plus vite', isCorrect: false },
      { id: 'b', text: 'Pour pousser plus facilement qu\'en soulevant', isCorrect: true },
      { id: 'c', text: 'Pour protéger les meubles de la pluie', isCorrect: false },
    ],
    correctAnswer: 'Pour pousser plus facilement qu\'en soulevant',
    explanation: 'Le plan incliné (rampe) répartit l\'effort sur une plus grande distance. Il est plus facile de pousser que de soulever.',
    hint: 'Le toboggan utilise le même principe.',
    tags: ['ce1', 'sciences', 'objets-techniques', 'plan-incline', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-011',
    subject: 'sciences',
    title: 'Matière : magnétisme',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un aimant attire... ?',
    options: [
      { id: 'a', text: 'Tous les matériaux', isCorrect: false },
      { id: 'b', text: 'Les objets en métal ferreux (fer, acier)', isCorrect: true },
      { id: 'c', text: 'Uniquement l\'eau', isCorrect: false },
    ],
    correctAnswer: 'Les objets en métal ferreux (fer, acier)',
    explanation: 'L\'aimant attire certains métaux comme le fer et l\'acier. Il n\'attire pas le plastique, le bois ou l\'aluminium.',
    hint: 'Un aimant colle sur un réfrigérateur en acier.',
    tags: ['ce1', 'sciences', 'matiere', 'magnetisme', 'aimant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-012',
    subject: 'sciences',
    title: 'Objets techniques : circuit électrique',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'electricite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pour allumer une ampoule, il faut... ?',
    options: [
      { id: 'a', text: 'La secouer', isCorrect: false },
      { id: 'b', text: 'La brancher dans un circuit électrique complet avec une pile', isCorrect: true },
      { id: 'c', text: 'La chauffer', isCorrect: false },
    ],
    correctAnswer: 'La brancher dans un circuit électrique complet avec une pile',
    explanation: 'Une ampoule s\'allume si le circuit est fermé (sans interruption) et si on fournit de l\'électricité (pile ou secteur).',
    hint: 'Le circuit doit être complet (fermé) pour que le courant passe.',
    tags: ['ce1', 'sciences', 'electricite', 'circuit', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-013',
    subject: 'sciences',
    title: 'Matière : masse',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Avec quoi mesure-t-on la masse d\'un objet ?',
    options: [
      { id: 'a', text: 'Une règle', isCorrect: false },
      { id: 'b', text: 'Une balance', isCorrect: true },
      { id: 'c', text: 'Un thermomètre', isCorrect: false },
    ],
    correctAnswer: 'Une balance',
    explanation: 'La balance compare ou mesure la masse des objets. La masse s\'exprime en grammes (g) ou kilogrammes (kg).',
    hint: 'On l\'utilise pour peser des ingrédients en cuisine.',
    tags: ['ce1', 'sciences', 'matiere', 'masse', 'balance', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-mat-014',
    subject: 'sciences',
    title: 'Objets techniques : fabrication',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pour fabriquer un pont solide, quel matériau choisit-on principalement ?',
    options: [
      { id: 'a', text: 'Du papier', isCorrect: false },
      { id: 'b', text: 'Du béton et du métal', isCorrect: true },
      { id: 'c', text: 'Du tissu', isCorrect: false },
    ],
    correctAnswer: 'Du béton et du métal',
    explanation: 'Le béton et le métal sont des matériaux résistants. Les ponts sont construits en béton armé (béton + barres de métal).',
    hint: 'Un pont doit supporter des voitures lourdes.',
    tags: ['ce1', 'sciences', 'materiaux', 'construction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
