import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCe1EnvironnementExercises: ScienceExercise[] = [
  {
    id: 'sc-ce1-env-001',
    subject: 'sciences',
    title: 'Saison : feuilles tombent',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison les feuilles des arbres tombent-elles ?',
    options: [
      { id: 'a', text: 'Au printemps', isCorrect: false },
      { id: 'b', text: 'En été', isCorrect: false },
      { id: 'c', text: 'En automne', isCorrect: true },
    ],
    correctAnswer: 'En automne',
    explanation: 'En automne, les feuilles jaunissent et tombent. C\'est la saison après l\'été.',
    hint: 'C\'est la saison entre l\'été et l\'hiver.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-env-002',
    subject: 'sciences',
    title: 'Saison : fleurs',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison les fleurs éclosent-elles et la nature se réveille-t-elle ?',
    options: [
      { id: 'a', text: 'En hiver', isCorrect: false },
      { id: 'b', text: 'Au printemps', isCorrect: true },
      { id: 'c', text: 'En automne', isCorrect: false },
    ],
    correctAnswer: 'Au printemps',
    explanation: 'Au printemps, les fleurs s\'épanouissent, les oiseaux reviennent et les journées rallongent.',
    hint: 'C\'est la saison après l\'hiver, quand il fait plus chaud.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-env-003',
    subject: 'sciences',
    title: 'Nombre de saisons',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien y a-t-il de saisons dans une année ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Il y a 4 saisons : le printemps, l\'été, l\'automne et l\'hiver.',
    hint: 'Compte : printemps, été, automne, hiver.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-env-004',
    subject: 'sciences',
    title: 'Saison la plus chaude',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la saison la plus chaude ?',
    options: [
      { id: 'a', text: 'L\'hiver', isCorrect: false },
      { id: 'b', text: 'L\'automne', isCorrect: false },
      { id: 'c', text: 'L\'été', isCorrect: true },
    ],
    correctAnswer: 'L\'été',
    explanation: 'L\'été est la saison la plus chaude. On va à la plage et les journées sont très longues.',
    hint: 'On part en vacances pendant cette saison.',
    tags: ['ce1', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-env-005',
    subject: 'sciences',
    title: 'Météo : nuages',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi sont faits les nuages ?',
    options: [
      { id: 'a', text: 'De coton', isCorrect: false },
      { id: 'b', text: 'De petites gouttes d\'eau', isCorrect: true },
      { id: 'c', text: 'De fumée', isCorrect: false },
    ],
    correctAnswer: 'De petites gouttes d\'eau',
    explanation: 'Les nuages sont formés de millions de toutes petites gouttes d\'eau en suspension dans l\'air.',
    hint: 'Ils peuvent donner de la pluie.',
    tags: ['ce1', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-env-006',
    subject: 'sciences',
    title: 'Météo : thermomètre',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel instrument indique la température qu\'il fait dehors ?',
    options: [
      { id: 'a', text: 'Le baromètre', isCorrect: false },
      { id: 'b', text: 'La règle', isCorrect: false },
      { id: 'c', text: 'Le thermomètre', isCorrect: true },
    ],
    correctAnswer: 'Le thermomètre',
    explanation: 'Le thermomètre mesure la température. Il indique s\'il fait chaud ou froid.',
    hint: 'On l\'utilise aussi quand on a de la fièvre.',
    tags: ['ce1', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-007',
    subject: 'sciences',
    title: 'États de l\'eau : glace',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'eau liquide se transforme en glace quand... ?',
    options: [
      { id: 'a', text: 'Il fait très chaud', isCorrect: false },
      { id: 'b', text: 'Il fait très froid (en dessous de 0°C)', isCorrect: true },
      { id: 'c', text: 'Il vente', isCorrect: false },
    ],
    correctAnswer: 'Il fait très froid (en dessous de 0°C)',
    explanation: 'L\'eau se solidifie à 0°C et en dessous. Elle devient de la glace.',
    hint: 'Les glaçons se forment dans le congélateur.',
    tags: ['ce1', 'sciences', 'eau', 'etats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-008',
    subject: 'sciences',
    title: 'États de l\'eau : vapeur',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il quand on chauffe de l\'eau dans une casserole ?',
    options: [
      { id: 'a', text: 'Elle devient solide', isCorrect: false },
      { id: 'b', text: 'Elle s\'évapore en vapeur', isCorrect: true },
      { id: 'c', text: 'Elle devient rouge', isCorrect: false },
    ],
    correctAnswer: 'Elle s\'évapore en vapeur',
    explanation: 'En chauffant, l\'eau se transforme en vapeur d\'eau (gaz invisible). On voit la buée au-dessus de la casserole.',
    hint: 'La vapeur monte au-dessus de l\'eau bouillante.',
    tags: ['ce1', 'sciences', 'eau', 'etats', 'vapeur', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-009',
    subject: 'sciences',
    title: 'Pollution de l\'eau',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui peut polluer une rivière ?',
    options: [
      { id: 'a', text: 'Les feuilles des arbres', isCorrect: false },
      { id: 'b', text: 'Les déchets plastiques jetés dedans', isCorrect: true },
      { id: 'c', text: 'La pluie', isCorrect: false },
    ],
    correctAnswer: 'Les déchets plastiques jetés dedans',
    explanation: 'Les déchets plastiques dans les rivières polluent l\'eau et menacent les animaux aquatiques.',
    hint: 'On ne jette pas ses détritus dans l\'eau.',
    tags: ['ce1', 'sciences', 'environnement', 'pollution', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-010',
    subject: 'sciences',
    title: 'Météo : pression atmosphérique',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel instrument mesure la pression atmosphérique pour prévoir le temps ?',
    options: [
      { id: 'a', text: 'Le thermomètre', isCorrect: false },
      { id: 'b', text: 'Le baromètre', isCorrect: true },
      { id: 'c', text: 'La règle', isCorrect: false },
    ],
    correctAnswer: 'Le baromètre',
    explanation: 'Le baromètre mesure la pression de l\'air. Une pression haute annonce souvent du beau temps.',
    hint: 'Les météorologues l\'utilisent.',
    tags: ['ce1', 'sciences', 'meteo', 'instruments', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-011',
    subject: 'sciences',
    title: 'Cycle de l\'eau : pluie',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment se forme la pluie ?',
    options: [
      { id: 'a', text: 'L\'eau des mers monte dans l\'air, forme des nuages, puis retombe', isCorrect: true },
      { id: 'b', text: 'Des géants arrosent la terre depuis le ciel', isCorrect: false },
      { id: 'c', text: 'L\'eau sort directement des nuages sans avoir été ailleurs', isCorrect: false },
    ],
    correctAnswer: 'L\'eau des mers monte dans l\'air, forme des nuages, puis retombe',
    explanation: 'Le cycle de l\'eau : évaporation → nuages (condensation) → pluie (précipitations).',
    hint: 'L\'eau monte d\'abord sous forme de vapeur.',
    tags: ['ce1', 'sciences', 'eau', 'cycle-eau', 'pluie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-012',
    subject: 'sciences',
    title: 'Nature : préserver l\'environnement',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que peut-on faire pour économiser l\'eau ?',
    options: [
      { id: 'a', text: 'Laisser le robinet couler pendant le brossage des dents', isCorrect: false },
      { id: 'b', text: 'Fermer le robinet pendant le brossage des dents', isCorrect: true },
      { id: 'c', text: 'Prendre un bain très long tous les jours', isCorrect: false },
    ],
    correctAnswer: 'Fermer le robinet pendant le brossage des dents',
    explanation: 'Un robinet ouvert gaspille plusieurs litres d\'eau par minute. Fermer le robinet permet d\'économiser l\'eau.',
    hint: 'L\'eau est précieuse et il ne faut pas la gaspiller.',
    tags: ['ce1', 'sciences', 'environnement', 'eau', 'ecologie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-013',
    subject: 'sciences',
    title: 'Relief : montagne',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une montagne ?',
    options: [
      { id: 'a', text: 'Un grand creux dans la terre', isCorrect: false },
      { id: 'b', text: 'Une élévation importante du terrain', isCorrect: true },
      { id: 'c', text: 'Une grande surface d\'eau', isCorrect: false },
    ],
    correctAnswer: 'Une élévation importante du terrain',
    explanation: 'Une montagne est une grande élévation du sol. On y trouve de la neige au sommet en hiver.',
    hint: 'On y fait du ski.',
    tags: ['ce1', 'sciences', 'paysages', 'relief', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-014',
    subject: 'sciences',
    title: 'Soleil et ombre',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi voit-on son ombre par beau temps ?',
    options: [
      { id: 'a', text: 'Parce que la lune nous éclaire', isCorrect: false },
      { id: 'b', text: 'Parce que le soleil éclaire et notre corps bloque la lumière', isCorrect: true },
      { id: 'c', text: 'Parce qu\'on est fatigué', isCorrect: false },
    ],
    correctAnswer: 'Parce que le soleil éclaire et notre corps bloque la lumière',
    explanation: 'L\'ombre se forme quand un objet opaque (notre corps) bloque la lumière du soleil.',
    hint: 'L\'ombre est du côté opposé au soleil.',
    tags: ['ce1', 'sciences', 'soleil', 'lumiere', 'ombre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-env-015',
    subject: 'sciences',
    title: 'Météo : grêle',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la grêle ?',
    options: [
      { id: 'a', text: 'De la pluie très froide', isCorrect: false },
      { id: 'b', text: 'Des petites billes de glace qui tombent du ciel', isCorrect: true },
      { id: 'c', text: 'De la neige poudreuse', isCorrect: false },
    ],
    correctAnswer: 'Des petites billes de glace qui tombent du ciel',
    explanation: 'La grêle est formée de billes de glace qui se forment dans les nuages d\'orage.',
    hint: 'Ça fait du bruit sur les toits.',
    tags: ['ce1', 'sciences', 'meteo', 'grele', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
