import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCe1VivantExercises: ScienceExercise[] = [
  {
    id: 'sc-ce1-viv-001',
    subject: 'sciences',
    title: 'Animal herbivore',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal mange uniquement des plantes ?',
    options: [
      { id: 'a', text: 'Le loup', isCorrect: false },
      { id: 'b', text: 'Le lapin', isCorrect: true },
      { id: 'c', text: 'Le requin', isCorrect: false },
    ],
    correctAnswer: 'Le lapin',
    explanation: 'Le lapin est herbivore : il mange de l\'herbe, des carottes et d\'autres plantes.',
    hint: 'Cet animal adore les carottes.',
    tags: ['ce1', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-002',
    subject: 'sciences',
    title: 'Animal producteur de lait',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal produit le lait qu\'on boit ?',
    options: [
      { id: 'a', text: 'Le poulet', isCorrect: false },
      { id: 'b', text: 'La vache', isCorrect: true },
      { id: 'c', text: 'Le cochon', isCorrect: false },
    ],
    correctAnswer: 'La vache',
    explanation: 'La vache produit du lait. C\'est un mammifère qui allaite ses petits.',
    hint: 'Cet animal mange de l\'herbe dans les prés.',
    tags: ['ce1', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-003',
    subject: 'sciences',
    title: 'Animal producteur de miel',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal produit du miel ?',
    options: [
      { id: 'a', text: 'La tortue', isCorrect: false },
      { id: 'b', text: 'Le cheval', isCorrect: false },
      { id: 'c', text: 'L\'abeille', isCorrect: true },
    ],
    correctAnswer: 'L\'abeille',
    explanation: 'Les abeilles récoltent le nectar des fleurs et le transforment en miel dans la ruche.',
    hint: 'Cet animal vit dans une ruche.',
    tags: ['ce1', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-004',
    subject: 'sciences',
    title: 'Plante : besoin de lumière',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi une plante a-t-elle besoin pour pousser ?',
    options: [
      { id: 'a', text: 'De sel et de sable', isCorrect: false },
      { id: 'b', text: 'De lumière et d\'eau', isCorrect: true },
      { id: 'c', text: 'De sucre et de lait', isCorrect: false },
    ],
    correctAnswer: 'De lumière et d\'eau',
    explanation: 'Les plantes ont besoin de lumière, d\'eau et de terre pour pousser et grandir.',
    hint: 'Tu as besoin de deux choses pour faire vivre une plante en pot.',
    tags: ['ce1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis ce dont la plante a besoin.', extraHint: 'Eau + soleil.' },
    }),
  },

    {
    id: 'sc-ce1-viv-005',
    subject: 'sciences',
    title: 'Plante : racines',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie de la plante est sous la terre et absorbe l\'eau ?',
    options: [
      { id: 'a', text: 'Les feuilles', isCorrect: false },
      { id: 'b', text: 'Les fleurs', isCorrect: false },
      { id: 'c', text: 'Les racines', isCorrect: true },
    ],
    correctAnswer: 'Les racines',
    explanation: 'Les racines sont sous la terre. Elles aspirent l\'eau et les sels minéraux du sol.',
    hint: 'C\'est la partie cachée sous la terre.',
    tags: ['ce1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-006',
    subject: 'sciences',
    title: 'Plante : feuilles',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi servent principalement les feuilles d\'une plante ?',
    options: [
      { id: 'a', text: 'À boire de l\'eau', isCorrect: false },
      { id: 'b', text: 'À capter la lumière du soleil', isCorrect: true },
      { id: 'c', text: 'À attirer les insectes', isCorrect: false },
    ],
    correctAnswer: 'À capter la lumière du soleil',
    explanation: 'Les feuilles captent la lumière du soleil pour fabriquer la nourriture de la plante.',
    hint: 'Elles sont larges et plates pour mieux capter quelque chose du ciel.',
    tags: ['ce1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-007',
    subject: 'sciences',
    title: 'Non vivant : caillou',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces objets N\'EST PAS vivant ?',
    options: [
      { id: 'a', text: 'Un champignon', isCorrect: false },
      { id: 'b', text: 'Un caillou', isCorrect: true },
      { id: 'c', text: 'Un arbre', isCorrect: false },
    ],
    correctAnswer: 'Un caillou',
    explanation: 'Un caillou n\'est pas vivant : il ne grandit pas, ne mange pas et ne se reproduit pas. Le champignon et l\'arbre sont des êtres vivants.',
    hint: 'Cet objet ne grandit jamais, même après des années.',
    tags: ['ce1', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-008',
    subject: 'sciences',
    title: 'Vivant : arbuste',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces éléments est vivant ?',
    options: [
      { id: 'a', text: 'Une voiture', isCorrect: false },
      { id: 'b', text: 'La flamme d\'une bougie', isCorrect: false },
      { id: 'c', text: 'Un arbuste', isCorrect: true },
    ],
    correctAnswer: 'Un arbuste',
    explanation: 'Un arbuste est vivant : il pousse, a des feuilles, a besoin d\'eau et de lumière. Une voiture et une flamme ne sont pas des êtres vivants.',
    hint: 'Cet élément pousse et a des feuilles.',
    tags: ['ce1', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-009',
    subject: 'sciences',
    title: 'Vivant : critère',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment sait-on qu\'un être est vivant ?',
    options: [
      { id: 'a', text: 'Il est grand et coloré', isCorrect: false },
      { id: 'b', text: 'Il grandit et se nourrit', isCorrect: true },
      { id: 'c', text: 'Il est de couleur verte', isCorrect: false },
    ],
    correctAnswer: 'Il grandit et se nourrit',
    explanation: 'Un être vivant grandit, se nourrit, respire et se reproduit. La taille et la couleur ne suffisent pas.',
    hint: 'Pense à ce que font les plantes et les animaux.',
    tags: ['ce1', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis ce que font les êtres vivants.', extraHint: 'Les vivants grandissent et mangent.' },
    }),
  },

    {
    id: 'sc-ce1-viv-010',
    subject: 'sciences',
    title: 'Habitat : poisson rouge',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où vit un poisson rouge ?',
    options: [
      { id: 'a', text: 'Dans un nid', isCorrect: false },
      { id: 'b', text: 'Dans un aquarium ou un étang', isCorrect: true },
      { id: 'c', text: 'Dans un terrier', isCorrect: false },
    ],
    correctAnswer: 'Dans un aquarium ou un étang',
    explanation: 'Le poisson rouge vit dans l\'eau, dans un aquarium à la maison ou dans un étang dehors.',
    hint: 'Cet animal a besoin d\'eau pour vivre.',
    tags: ['ce1', 'sciences', 'habitats', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce1-viv-011',
    subject: 'sciences',
    title: 'Plante : germination',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le moment où une graine commence à pousser ?',
    options: [
      { id: 'a', text: 'La floraison', isCorrect: false },
      { id: 'b', text: 'La germination', isCorrect: true },
      { id: 'c', text: 'La pollinisation', isCorrect: false },
    ],
    correctAnswer: 'La germination',
    explanation: 'La germination, c\'est quand une graine plantée en terre commence à pousser et à donner une jeune plante.',
    hint: 'C\'est le début de la vie d\'une nouvelle plante.',
    tags: ['ce1', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-012',
    subject: 'sciences',
    title: 'Classification : reptile',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal est un reptile ?',
    options: [
      { id: 'a', text: 'Le dauphin', isCorrect: false },
      { id: 'b', text: 'Le serpent', isCorrect: true },
      { id: 'c', text: 'L\'aigle', isCorrect: false },
    ],
    correctAnswer: 'Le serpent',
    explanation: 'Le serpent est un reptile : il a des écailles, est à sang froid et rampe sur le sol.',
    hint: 'Cet animal rampe et a des écailles.',
    tags: ['ce1', 'sciences', 'animaux', 'reptiles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-013',
    subject: 'sciences',
    title: 'Chaîne alimentaire',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans la chaîne : herbe → lapin → renard. Que mange le renard ?',
    options: [
      { id: 'a', text: 'L\'herbe', isCorrect: false },
      { id: 'b', text: 'Le lapin', isCorrect: true },
      { id: 'c', text: 'Les deux', isCorrect: false },
    ],
    correctAnswer: 'Le lapin',
    explanation: 'Dans cette chaîne alimentaire, le renard mange le lapin, qui mange l\'herbe.',
    hint: 'Lis la chaîne de droite à gauche.',
    tags: ['ce1', 'sciences', 'animaux', 'chaine-alimentaire', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-014',
    subject: 'sciences',
    title: 'Classification : oiseau',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui caractérise un oiseau ?',
    options: [
      { id: 'a', text: 'Des écailles et des nageoires', isCorrect: false },
      { id: 'b', text: 'Des plumes et un bec', isCorrect: true },
      { id: 'c', text: 'De la fourrure et des griffes', isCorrect: false },
    ],
    correctAnswer: 'Des plumes et un bec',
    explanation: 'Tous les oiseaux ont des plumes et un bec. Ils ont deux ailes et deux pattes.',
    hint: 'Pense au moineau ou à l\'aigle.',
    tags: ['ce1', 'sciences', 'animaux', 'oiseaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-015',
    subject: 'sciences',
    title: 'Cycle de vie : grenouille',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Par quelle étape passe la grenouille avant de devenir adulte ?',
    options: [
      { id: 'a', text: 'Elle naît directement adulte', isCorrect: false },
      { id: 'b', text: 'Elle commence comme têtard', isCorrect: true },
      { id: 'c', text: 'Elle sort d\'un cocon', isCorrect: false },
    ],
    correctAnswer: 'Elle commence comme têtard',
    explanation: 'La grenouille naît de l\'œuf sous forme de têtard (avec une queue). Le têtard se transforme progressivement en grenouille.',
    hint: 'Cet animal vit d\'abord dans l\'eau comme un poisson.',
    tags: ['ce1', 'sciences', 'animaux', 'metamorphose', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-016',
    subject: 'sciences',
    title: 'Plante : photosynthèse simple',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les feuilles vertes d\'une plante fabriquent sa nourriture grâce à... ?',
    options: [
      { id: 'a', text: 'La pluie et le vent', isCorrect: false },
      { id: 'b', text: 'La lumière du soleil et l\'eau', isCorrect: true },
      { id: 'c', text: 'La nuit uniquement', isCorrect: false },
    ],
    correctAnswer: 'La lumière du soleil et l\'eau',
    explanation: 'La photosynthèse est le processus par lequel les feuilles utilisent la lumière et l\'eau pour fabriquer la nourriture de la plante.',
    hint: 'Les feuilles sont vertes grâce à la chlorophylle.',
    tags: ['ce1', 'sciences', 'plantes', 'photosynthese', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-017',
    subject: 'sciences',
    title: 'Animal : migration',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les hirondelles quittent-elles la France en automne ?',
    options: [
      { id: 'a', text: 'Pour aller faire les courses', isCorrect: false },
      { id: 'b', text: 'Pour trouver des régions plus chaudes avec de la nourriture', isCorrect: true },
      { id: 'c', text: 'Parce qu\'elles ne supportent pas le soleil', isCorrect: false },
    ],
    correctAnswer: 'Pour trouver des régions plus chaudes avec de la nourriture',
    explanation: 'Les hirondelles migrent en Afrique car les insectes dont elles se nourrissent disparaissent en hiver en France.',
    hint: 'Les hirondelles mangent des insectes.',
    tags: ['ce1', 'sciences', 'animaux', 'migration', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-018',
    subject: 'sciences',
    title: 'Animal : amphibien',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un animal amphibien peut vivre...',
    options: [
      { id: 'a', text: 'Uniquement dans l\'eau', isCorrect: false },
      { id: 'b', text: 'Sur terre ET dans l\'eau', isCorrect: true },
      { id: 'c', text: 'Uniquement en l\'air', isCorrect: false },
    ],
    correctAnswer: 'Sur terre ET dans l\'eau',
    explanation: 'Les amphibiens (grenouilles, salamandres, crapauds) vivent sur terre et dans l\'eau selon leurs besoins.',
    hint: 'La grenouille est un exemple.',
    tags: ['ce1', 'sciences', 'animaux', 'amphibiens', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-019',
    subject: 'sciences',
    title: 'Plante : pollinisation',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel insecte aide les fleurs à se reproduire en transportant le pollen ?',
    options: [
      { id: 'a', text: 'La fourmi', isCorrect: false },
      { id: 'b', text: 'L\'abeille', isCorrect: true },
      { id: 'c', text: 'Le moustique', isCorrect: false },
    ],
    correctAnswer: 'L\'abeille',
    explanation: 'Les abeilles transportent le pollen de fleur en fleur, permettant ainsi la fécondation des plantes.',
    hint: 'Elle fait aussi du miel.',
    tags: ['ce1', 'sciences', 'plantes', 'pollinisation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-020',
    subject: 'sciences',
    title: 'Classification : poisson',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment respire un poisson dans l\'eau ?',
    options: [
      { id: 'a', text: 'Avec des poumons', isCorrect: false },
      { id: 'b', text: 'Avec des branchies', isCorrect: true },
      { id: 'c', text: 'Avec des nageoires', isCorrect: false },
    ],
    correctAnswer: 'Avec des branchies',
    explanation: 'Les poissons respirent grâce à leurs branchies qui filtrent l\'oxygène dissous dans l\'eau.',
    hint: 'Ce sont les fentes sur les côtés de la tête du poisson.',
    tags: ['ce1', 'sciences', 'animaux', 'poissons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-021',
    subject: 'sciences',
    title: 'Champignons : vivants ?',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'champignons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un champignon est-il une plante ?',
    options: [
      { id: 'a', text: 'Oui, car il pousse dans la terre', isCorrect: false },
      { id: 'b', text: 'Non, il appartient à un groupe à part (les fungi)', isCorrect: true },
      { id: 'c', text: 'Oui, car il a des feuilles vertes', isCorrect: false },
    ],
    correctAnswer: 'Non, il appartient à un groupe à part (les fungi)',
    explanation: 'Les champignons ne sont ni des plantes ni des animaux. Ils n\'ont pas de chlorophylle et se nourrissent de matières organiques.',
    hint: 'Un champignon n\'a pas de feuilles vertes.',
    tags: ['ce1', 'sciences', 'champignons', 'classification', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-022',
    subject: 'sciences',
    title: 'Habitat : prairie',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal vit principalement dans une prairie ?',
    options: [
      { id: 'a', text: 'Le requin', isCorrect: false },
      { id: 'b', text: 'La vache', isCorrect: true },
      { id: 'c', text: 'L\'aigle de mer', isCorrect: false },
    ],
    correctAnswer: 'La vache',
    explanation: 'La vache broute l\'herbe dans les prairies. Elle est élevée par les agriculteurs pour son lait et sa viande.',
    hint: 'Elle dit "meuh" et mange de l\'herbe.',
    tags: ['ce1', 'sciences', 'animaux', 'habitats', 'prairie', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-023',
    subject: 'sciences',
    title: 'Animal nocturne',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un animal nocturne est actif... ?',
    options: [
      { id: 'a', text: 'Le jour', isCorrect: false },
      { id: 'b', text: 'La nuit', isCorrect: true },
      { id: 'c', text: 'Uniquement au lever du soleil', isCorrect: false },
    ],
    correctAnswer: 'La nuit',
    explanation: 'Un animal nocturne dort le jour et se réveille la nuit pour chercher sa nourriture. La chouette et la chauve-souris sont nocturnes.',
    hint: 'Chouette = animal de la nuit.',
    tags: ['ce1', 'sciences', 'animaux', 'nocturne', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-024',
    subject: 'sciences',
    title: 'Plante : arbre ou arbuste',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la différence entre un arbre et un arbuste ?',
    options: [
      { id: 'a', text: 'L\'arbre a des fleurs, l\'arbuste non', isCorrect: false },
      { id: 'b', text: 'L\'arbre a un tronc plus grand et vit plus longtemps', isCorrect: true },
      { id: 'c', text: 'Ils sont identiques', isCorrect: false },
    ],
    correctAnswer: 'L\'arbre a un tronc plus grand et vit plus longtemps',
    explanation: 'Un arbre a un seul tronc principal et peut atteindre plusieurs mètres de haut. Un arbuste est plus petit avec plusieurs tiges.',
    hint: 'Le chêne est un arbre, le rosier est un arbuste.',
    tags: ['ce1', 'sciences', 'plantes', 'arbres', 'arbustes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-025',
    subject: 'sciences',
    title: 'Animal herbivore CE1',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal est herbivore (mange seulement des plantes) ?',
    options: [
      { id: 'a', text: 'L\'aigle', isCorrect: false },
      { id: 'b', text: 'Le lapin', isCorrect: true },
      { id: 'c', text: 'Le hibou', isCorrect: false },
    ],
    correctAnswer: 'Le lapin',
    explanation: 'Le lapin mange des herbes, des légumes et des fruits. L\'aigle et le hibou sont des rapaces carnivores.',
    hint: 'Il mange des carottes et de la salade.',
    tags: ['ce1', 'sciences', 'animaux', 'herbivore', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-026',
    subject: 'sciences',
    title: 'Plante : conifères',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi le sapin garde-t-il ses feuilles en hiver ?',
    options: [
      { id: 'a', text: 'Parce qu\'il boit plus d\'eau', isCorrect: false },
      { id: 'b', text: 'Parce que ses aiguilles résistent au froid', isCorrect: true },
      { id: 'c', text: 'Parce qu\'il fait plus chaud sous la neige', isCorrect: false },
    ],
    correctAnswer: 'Parce que ses aiguilles résistent au froid',
    explanation: 'Le sapin est un conifère. Ses feuilles en forme d\'aiguilles résistent au gel et restent vertes toute l\'année.',
    hint: 'On utilise le sapin comme arbre de Noël.',
    tags: ['ce1', 'sciences', 'plantes', 'coniferes', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-027',
    subject: 'sciences',
    title: 'Animal : la toile d\'araignée',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi l\'araignée tisse une toile ?',
    options: [
      { id: 'a', text: 'Pour dormir dedans', isCorrect: false },
      { id: 'b', text: 'Pour attraper des insectes à manger', isCorrect: true },
      { id: 'c', text: 'Pour décorer son logement', isCorrect: false },
    ],
    correctAnswer: 'Pour attraper des insectes à manger',
    explanation: 'La toile d\'araignée est un piège collant. Les insectes qui la touchent restent coincés et l\'araignée peut les manger.',
    hint: 'La toile est sticky (collante) pour les insectes.',
    tags: ['ce1', 'sciences', 'animaux', 'araignee', 'alimentation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-028',
    subject: 'sciences',
    title: 'Plante : la graine voyage',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les graines du gui voyagent-elles pour coloniser de nouveaux arbres ?',
    options: [
      { id: 'a', text: 'Par le vent', isCorrect: false },
      { id: 'b', text: 'Dans les excréments des oiseaux qui mangent ses baies', isCorrect: true },
      { id: 'c', text: 'En roulant sur le sol', isCorrect: false },
    ],
    correctAnswer: 'Dans les excréments des oiseaux qui mangent ses baies',
    explanation: 'Les oiseaux mangent les baies du gui et déposent les graines sur les branches d\'arbres avec leurs fientes, permettant au gui de pousser.',
    hint: 'Les oiseaux mangent les fruits et rejettent les graines.',
    tags: ['ce1', 'sciences', 'plantes', 'dispersion', 'graines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-029',
    subject: 'sciences',
    title: 'Animal : abeille et miel',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les abeilles fabriquent-elles le miel ?',
    options: [
      { id: 'a', text: 'Elles trouvent du miel sous la terre', isCorrect: false },
      { id: 'b', text: 'Elles transforment le nectar des fleurs en miel dans la ruche', isCorrect: true },
      { id: 'c', text: 'Elles mangent des graines sucrées', isCorrect: false },
    ],
    correctAnswer: 'Elles transforment le nectar des fleurs en miel dans la ruche',
    explanation: 'Les abeilles récoltent le nectar des fleurs et le transforment en miel dans la ruche. Une ruche peut produire jusqu\'à 30 kg de miel par an.',
    hint: 'Miel = nectar transformé par les abeilles.',
    tags: ['ce1', 'sciences', 'animaux', 'abeilles', 'alimentation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-030',
    subject: 'sciences',
    title: 'Cycle de vie : papillon complet',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans quel ordre se déroule le cycle du papillon ?',
    options: [
      { id: 'a', text: 'Œuf → papillon → chenille → chrysalide', isCorrect: false },
      { id: 'b', text: 'Œuf → chenille → chrysalide → papillon', isCorrect: true },
      { id: 'c', text: 'Chenille → œuf → chrysalide → papillon', isCorrect: false },
    ],
    correctAnswer: 'Œuf → chenille → chrysalide → papillon',
    explanation: 'La femelle pond un œuf. L\'œuf donne une chenille qui se transforme en chrysalide. La chrysalide s\'ouvre et laisse sortir un papillon.',
    hint: 'La chenille est l\'étape avant la chrysalide.',
    tags: ['ce1', 'sciences', 'animaux', 'metamorphose', 'cycle-vie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-031',
    subject: 'sciences',
    title: 'Écosystème : forêt',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosysteme',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal vit principalement dans une forêt ?',
    options: [
      { id: 'a', text: 'Le dauphin', isCorrect: false },
      { id: 'b', text: 'Le cerf', isCorrect: true },
      { id: 'c', text: 'Le pingouin', isCorrect: false },
    ],
    correctAnswer: 'Le cerf',
    explanation: 'Le cerf vit dans les forêts et les bois. Il se nourrit d\'herbe, de feuilles et d\'écorce.',
    hint: 'Il a de grandes cornes appelées bois.',
    tags: ['ce1', 'sciences', 'animaux', 'foret', 'ecosysteme', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-viv-032',
    subject: 'sciences',
    title: 'Plante : sauvage ou cultivée',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle plante est cultivée (plantée et soignée par les humains) ?',
    options: [
      { id: 'a', text: 'Le pissenlit qui pousse dans la pelouse', isCorrect: false },
      { id: 'b', text: 'Le blé dans un champ agricole', isCorrect: true },
      { id: 'c', text: 'La fougère dans la forêt', isCorrect: false },
    ],
    correctAnswer: 'Le blé dans un champ agricole',
    explanation: 'Le blé est une plante cultivée : les agriculteurs sèment, arrosent et récoltent le blé pour faire de la farine.',
    hint: 'On fait du pain avec la farine de blé.',
    tags: ['ce1', 'sciences', 'plantes', 'cultivee', 'agriculture', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
