import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCe1TerreExercises: ScienceExercise[] = [
  {
    id: 'sc-ce1-ter-001',
    subject: 'sciences',
    title: 'Système solaire : planètes',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien y a-t-il de planètes dans notre système solaire ?',
    options: [
      { id: 'a', text: '5 planètes', isCorrect: false },
      { id: 'b', text: '8 planètes', isCorrect: true },
      { id: 'c', text: '12 planètes', isCorrect: false },
    ],
    correctAnswer: '8 planètes',
    explanation: 'Notre système solaire compte 8 planètes : Mercure, Vénus, Terre, Mars, Jupiter, Saturne, Uranus et Neptune. Pluton est maintenant classée "planète naine".',
    hint: 'Un truc pour les retenir : Ma Vieille Tante Marthe… ',
    tags: ['ce1', 'sciences', 'terre', 'astronomie', 'planetes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-002',
    subject: 'sciences',
    title: 'Terre : rotation et révolution',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de temps la Terre met-elle pour faire le tour du Soleil ?',
    options: [
      { id: 'a', text: '24 heures (un jour)', isCorrect: false },
      { id: 'b', text: '365 jours (un an)', isCorrect: true },
      { id: 'c', text: '28 jours (un mois)', isCorrect: false },
    ],
    correctAnswer: '365 jours (un an)',
    explanation: 'La Terre tourne sur elle-même en 24h (= un jour). Elle fait le tour du Soleil en 365 jours (= un an). C\'est pour ça que les années durent 365 jours.',
    hint: 'Révolution = tour autour du Soleil. Rotation = tour sur elle-même.',
    tags: ['ce1', 'sciences', 'terre', 'astronomie', 'revolution', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-003',
    subject: 'sciences',
    title: 'Saisons : cause des saisons',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi y a-t-il des saisons ?',
    options: [
      { id: 'a', text: 'Parce que la Terre s\'éloigne et se rapproche du Soleil', isCorrect: false },
      { id: 'b', text: 'Parce que la Terre est inclinée sur son axe', isCorrect: true },
      { id: 'c', text: 'Parce que le Soleil tourne autour de la Terre', isCorrect: false },
    ],
    correctAnswer: 'Parce que la Terre est inclinée sur son axe',
    explanation: 'L\'axe de la Terre est incliné. Selon la position de la Terre sur son orbite, certaines régions reçoivent plus ou moins de lumière solaire. C\'est cette inclinaison qui cause les saisons.',
    hint: 'L\'inclinaison fait que le soleil est plus haut en été et plus bas en hiver.',
    tags: ['ce1', 'sciences', 'terre', 'saisons', 'inclinaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-004',
    subject: 'sciences',
    title: 'Météo : les types de nuages',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les cumulus sont des nuages... ?',
    options: [
      { id: 'a', text: 'Plats et gris qui annoncent la pluie', isCorrect: false },
      { id: 'b', text: 'Blancs et duveteux comme du coton par beau temps', isCorrect: true },
      { id: 'c', text: 'Très hauts et fins comme des voiles', isCorrect: false },
    ],
    correctAnswer: 'Blancs et duveteux comme du coton par beau temps',
    explanation: 'Les cumulus sont les gros nuages blancs en forme de choux-fleurs qu\'on voit par beau temps. Les nimbus sont les nuages sombres de pluie.',
    hint: 'Cumulus vient du latin "cumul" = tas. Ce sont les nuages en tas de beau temps.',
    tags: ['ce1', 'sciences', 'terre', 'meteo', 'nuages', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-005',
    subject: 'sciences',
    title: 'Eau : cycle de l\'eau',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans le cycle de l\'eau, dans quel ordre se succèdent les étapes ?',
    options: [
      { id: 'a', text: 'Pluie → évaporation → nuages → pluie', isCorrect: false },
      { id: 'b', text: 'Évaporation → nuages → pluie → rivières → évaporation', isCorrect: true },
      { id: 'c', text: 'Rivières → pluie → nuages → évaporation', isCorrect: false },
    ],
    correctAnswer: 'Évaporation → nuages → pluie → rivières → évaporation',
    explanation: 'L\'eau s\'évapore (soleil), monte et forme des nuages (condensation), retombe en pluie, rejoint les rivières et la mer… et recommence. Ce cycle se répète sans fin.',
    hint: 'Le cycle de l\'eau n\'a ni début ni fin : c\'est un cercle.',
    tags: ['ce1', 'sciences', 'terre', 'eau', 'cycle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-006',
    subject: 'sciences',
    title: 'Sol : composition du sol',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi est principalement composé le sol des jardins (humus) ?',
    options: [
      { id: 'a', text: 'De sable et de cailloux uniquement', isCorrect: false },
      { id: 'b', text: 'De matières végétales et animales décomposées mélangées à des minéraux', isCorrect: true },
      { id: 'c', text: 'D\'eau et de pierres broyées', isCorrect: false },
    ],
    correctAnswer: 'De matières végétales et animales décomposées mélangées à des minéraux',
    explanation: 'L\'humus est formé par la décomposition des feuilles, animaux morts, excréments d\'animaux. Il rend le sol fertile car il libère des nutriments pour les plantes.',
    hint: 'L\'humus est la couche sombre et riche en surface du sol.',
    tags: ['ce1', 'sciences', 'terre', 'sol', 'humus', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-007',
    subject: 'sciences',
    title: 'Astronomie : taille de la Lune',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi la Lune paraît-elle aussi grande que le Soleil dans le ciel alors qu\'elle est beaucoup plus petite ?',
    options: [
      { id: 'a', text: 'Parce que la Lune grossit la nuit', isCorrect: false },
      { id: 'b', text: 'Parce que la Lune est beaucoup plus proche de la Terre que le Soleil', isCorrect: true },
      { id: 'c', text: 'Parce qu\'elles ont en réalité la même taille', isCorrect: false },
    ],
    correctAnswer: 'Parce que la Lune est beaucoup plus proche de la Terre que le Soleil',
    explanation: 'Le Soleil est 400 fois plus grand que la Lune mais 400 fois plus loin. C\'est pour ça qu\'ils semblent de la même taille. C\'est ce qui rend les éclipses totales de Soleil possibles.',
    hint: 'Un objet proche paraît grand même s\'il est petit. Éloigné, il paraît petit même s\'il est grand.',
    tags: ['ce1', 'sciences', 'terre', 'astronomie', 'lune', 'soleil', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-008',
    subject: 'sciences',
    title: 'Météo : températures et saisons',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi fait-il plus chaud en été qu\'en hiver en France ?',
    options: [
      { id: 'a', text: 'Parce que la Terre est plus proche du Soleil en été', isCorrect: false },
      { id: 'b', text: 'Parce que le Soleil est plus haut dans le ciel et les jours sont plus longs', isCorrect: true },
      { id: 'c', text: 'Parce que la Terre tourne moins vite en été', isCorrect: false },
    ],
    correctAnswer: 'Parce que le Soleil est plus haut dans le ciel et les jours sont plus longs',
    explanation: 'En été, le Soleil est plus haut dans le ciel et brille plus longtemps. Les rayons du soleil tombent plus verticalement et chauffent plus efficacement. En hiver, c\'est l\'inverse.',
    hint: 'En été, les jours sont longs. En hiver, les nuits sont longues.',
    tags: ['ce1', 'sciences', 'terre', 'saisons', 'temperatures', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-009',
    subject: 'sciences',
    title: 'Volcans : lave',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'geologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la lave ?',
    options: [
      { id: 'a', text: 'De l\'eau très chaude qui sort du volcan', isCorrect: false },
      { id: 'b', text: 'De la roche fondue à très haute température qui sort du volcan', isCorrect: true },
      { id: 'c', text: 'De la cendre volcanique mélangée à des gaz', isCorrect: false },
    ],
    correctAnswer: 'De la roche fondue à très haute température qui sort du volcan',
    explanation: 'La lave est du magma (roche liquide) qui jaillit hors du volcan. Elle peut atteindre 1 200°C. En refroidissant, elle forme de nouvelles roches.',
    hint: 'La lave est si chaude qu\'elle fait fondre presque tout sur son passage.',
    tags: ['ce1', 'sciences', 'terre', 'volcans', 'lave', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-010',
    subject: 'sciences',
    title: 'Eau : eau douce vs eau salée',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel pourcentage de l\'eau de la Terre est de l\'eau douce (non salée) ?',
    options: [
      { id: 'a', text: 'Environ 97 %', isCorrect: false },
      { id: 'b', text: 'Environ 3 %', isCorrect: true },
      { id: 'c', text: 'Environ 50 %', isCorrect: false },
    ],
    correctAnswer: 'Environ 3 %',
    explanation: 'L\'eau douce ne représente que 3 % de l\'eau sur Terre. Et la plupart est piégée dans les glaciers. L\'eau douce accessible (rivières, lacs, nappes) est très précieuse.',
    hint: 'C\'est pour ça qu\'il ne faut pas gaspiller l\'eau du robinet.',
    tags: ['ce1', 'sciences', 'terre', 'eau', 'eau-douce', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-011',
    subject: 'sciences',
    title: 'Météo : météorologie',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le spécialiste qui prédit la météo ?',
    options: [
      { id: 'a', text: 'Un astronome', isCorrect: false },
      { id: 'b', text: 'Un météorologue', isCorrect: true },
      { id: 'c', text: 'Un géologue', isCorrect: false },
    ],
    correctAnswer: 'Un météorologue',
    explanation: 'Le météorologue étudie l\'atmosphère et les phénomènes météorologiques pour prévoir le temps. Il utilise des satellites, des stations météo et des ordinateurs.',
    hint: 'La météo est présentée chaque soir à la télévision.',
    tags: ['ce1', 'sciences', 'terre', 'meteo', 'meteorologue', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-012',
    subject: 'sciences',
    title: 'Astronomie : éclipse de Lune',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une éclipse de Lune ?',
    options: [
      { id: 'a', text: 'Quand la Lune passe devant le Soleil', isCorrect: false },
      { id: 'b', text: 'Quand la Terre passe entre le Soleil et la Lune, projetant son ombre sur la Lune', isCorrect: true },
      { id: 'c', text: 'Quand la Lune sort de l\'atmosphère terrestre', isCorrect: false },
    ],
    correctAnswer: 'Quand la Terre passe entre le Soleil et la Lune, projetant son ombre sur la Lune',
    explanation: 'Lors d\'une éclipse de Lune, la Terre se trouve exactement entre le Soleil et la Lune. La Lune entre dans l\'ombre de la Terre et devient rouge-orangée.',
    hint: 'Une "Lune rouge" est souvent une éclipse de Lune.',
    tags: ['ce1', 'sciences', 'terre', 'astronomie', 'eclipse-lune', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-013',
    subject: 'sciences',
    title: 'Sol : érosion',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'geologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les montagnes s\'usent-elles très lentement au fil du temps ?',
    options: [
      { id: 'a', text: 'Parce que des géants les grignottent', isCorrect: false },
      { id: 'b', text: 'Parce que la pluie, le vent et le gel brisent et emportent les roches (érosion)', isCorrect: true },
      { id: 'c', text: 'Parce que la gravité les fait s\'effondrer rapidement', isCorrect: false },
    ],
    correctAnswer: 'Parce que la pluie, le vent et le gel brisent et emportent les roches (érosion)',
    explanation: 'L\'érosion est le processus par lequel la pluie, le vent, le gel et les rivières usent les roches sur des millions d\'années. Les particules arrachées forment les plages et les sédiments.',
    hint: 'Les Alpes sont plus jeunes que les Vosges, donc plus hautes (moins érodées).',
    tags: ['ce1', 'sciences', 'terre', 'geologie', 'erosion', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-014',
    subject: 'sciences',
    title: 'Ressources naturelles : pétrole',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'ressources',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le pétrole est-il une ressource renouvelable ?',
    options: [
      { id: 'a', text: 'Oui, il se reforme en quelques années', isCorrect: false },
      { id: 'b', text: 'Non, il s\'est formé en millions d\'années et s\'épuise', isCorrect: true },
      { id: 'c', text: 'Oui, si on recycle les plastiques', isCorrect: false },
    ],
    correctAnswer: 'Non, il s\'est formé en millions d\'années et s\'épuise',
    explanation: 'Le pétrole est formé de matières organiques (plantes, animaux marins) mortes il y a des millions d\'années, transformées sous pression. Il est non renouvelable : une fois consommé, il n\'y en a plus.',
    hint: 'À l\'opposé, le soleil et le vent sont des ressources renouvelables.',
    tags: ['ce1', 'sciences', 'terre', 'ressources', 'petrole', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-015',
    subject: 'sciences',
    title: 'Astronomie : comètes',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une comète a une longue queue brillante. De quoi est-elle faite ?',
    options: [
      { id: 'a', text: 'De lave volcanique projetée dans l\'espace', isCorrect: false },
      { id: 'b', text: 'De gaz et de poussières libérés par la glace qui fond sous l\'effet du Soleil', isCorrect: true },
      { id: 'c', text: 'D\'éclairs électriques dans l\'atmosphère terrestre', isCorrect: false },
    ],
    correctAnswer: 'De gaz et de poussières libérés par la glace qui fond sous l\'effet du Soleil',
    explanation: 'Une comète est une "boule de neige sale" faite de glace, de roche et de poussières. En s\'approchant du Soleil, la glace se sublime et libère une queue lumineuse de gaz et poussières.',
    hint: 'La comète de Halley est visible depuis la Terre tous les 75 ans environ.',
    tags: ['ce1', 'sciences', 'terre', 'astronomie', 'comete', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-016',
    subject: 'sciences',
    title: 'Atmosphère : couches',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'atmosphere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La couche d\'ozone nous protège de... ?',
    options: [
      { id: 'a', text: 'Des étoiles filantes qui tombent sur Terre', isCorrect: false },
      { id: 'b', text: 'Des rayons ultraviolets dangereux du Soleil', isCorrect: true },
      { id: 'c', text: 'Du vent solaire qui ferait tourner la Terre plus vite', isCorrect: false },
    ],
    correctAnswer: 'Des rayons ultraviolets dangereux du Soleil',
    explanation: 'La couche d\'ozone (dans la stratosphère) absorbe la majorité des rayons UV du Soleil. Ces rayons peuvent causer des cancers de la peau et endommager les yeux sans cette protection.',
    hint: 'On met de la crème solaire sur la plage pour se protéger des UV que l\'ozone ne filtre pas tous.',
    tags: ['ce1', 'sciences', 'terre', 'atmosphere', 'ozone', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-017',
    subject: 'sciences',
    title: 'Recyclage : déchets',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'ecologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi trier les déchets (plastiques, papiers, verre) est-il important ?',
    options: [
      { id: 'a', text: 'Pour que les poubelles soient plus ordonnées', isCorrect: false },
      { id: 'b', text: 'Pour que les matières soient recyclées et qu\'on économise les ressources naturelles', isCorrect: true },
      { id: 'c', text: 'Parce que la loi l\'oblige mais sans effet sur l\'environnement', isCorrect: false },
    ],
    correctAnswer: 'Pour que les matières soient recyclées et qu\'on économise les ressources naturelles',
    explanation: 'Le recyclage permet de refabriquer des objets à partir des déchets. Par exemple, les vieilles bouteilles en verre deviennent de nouvelles bouteilles, économisant du sable et de l\'énergie.',
    hint: 'Une bouteille en plastique non recyclée peut mettre 400 ans à se décomposer.',
    tags: ['ce1', 'sciences', 'terre', 'ecologie', 'recyclage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-018',
    subject: 'sciences',
    title: 'Météo : instrument de mesure',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel instrument mesure la température de l\'air ?',
    options: [
      { id: 'a', text: 'Un baromètre', isCorrect: false },
      { id: 'b', text: 'Un thermomètre', isCorrect: true },
      { id: 'c', text: 'Une girouette', isCorrect: false },
    ],
    correctAnswer: 'Un thermomètre',
    explanation: 'Le thermomètre mesure la température. Le baromètre mesure la pression atmosphérique (utile pour prévoir la pluie). La girouette indique la direction du vent.',
    hint: 'Thermo = chaleur (en grec). Thermomètre = mesure de chaleur.',
    tags: ['ce1', 'sciences', 'terre', 'meteo', 'thermometre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-019',
    subject: 'sciences',
    title: 'Astres : étoile filante',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une étoile filante, c\'est vraiment une étoile qui tombe ?',
    options: [
      { id: 'a', text: 'Oui, les étoiles tombent parfois sur Terre', isCorrect: false },
      { id: 'b', text: 'Non, c\'est une poussière ou un caillou de l\'espace qui brûle dans l\'atmosphère', isCorrect: true },
      { id: 'c', text: 'Oui, c\'est un morceau du Soleil qui s\'est détaché', isCorrect: false },
    ],
    correctAnswer: 'Non, c\'est une poussière ou un caillou de l\'espace qui brûle dans l\'atmosphère',
    explanation: 'Une étoile filante (météore) est un caillou ou grain de poussière provenant de l\'espace. En entrant dans l\'atmosphère à grande vitesse, il brûle et crée un trait lumineux.',
    hint: 'Si le météore ne brûle pas complètement et tombe au sol, on l\'appelle une météorite.',
    tags: ['ce1', 'sciences', 'terre', 'astronomie', 'etoile-filante', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-020',
    subject: 'sciences',
    title: 'Énergie : énergie solaire',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'energie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les panneaux solaires transforment la lumière du Soleil en quoi ?',
    options: [
      { id: 'a', text: 'En chaleur pour chauffer les maisons uniquement', isCorrect: false },
      { id: 'b', text: 'En électricité', isCorrect: true },
      { id: 'c', text: 'En eau chaude directement', isCorrect: false },
    ],
    correctAnswer: 'En électricité',
    explanation: 'Les panneaux solaires photovoltaïques convertissent la lumière du soleil directement en électricité. Cette énergie renouvelable ne produit ni pollution ni CO₂.',
    hint: 'Photo = lumière, voltaïque = électrique.',
    tags: ['ce1', 'sciences', 'terre', 'energie', 'solaire', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-021',
    subject: 'sciences',
    title: 'Météo : grêle',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La grêle est faite de... ?',
    options: [
      { id: 'a', text: 'De flocons de neige très durs', isCorrect: false },
      { id: 'b', text: 'De billes de glace formées dans les nuages d\'orage', isCorrect: true },
      { id: 'c', text: 'De gouttes de pluie gelées au contact du sol froid', isCorrect: false },
    ],
    correctAnswer: 'De billes de glace formées dans les nuages d\'orage',
    explanation: 'Dans les gros nuages d\'orage, les gouttelettes d\'eau sont soulevées très haut par des courants d\'air forts. Elles gèlent et forment des billes de glace (grêlons) qui tombent.',
    hint: 'La grêle peut endommager les récoltes et les voitures.',
    tags: ['ce1', 'sciences', 'terre', 'meteo', 'grele', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-022',
    subject: 'sciences',
    title: 'Sol : fossiles',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'geologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un fossile ?',
    options: [
      { id: 'a', text: 'Un caillou très dur qui ressemble à un animal', isCorrect: false },
      { id: 'b', text: 'Les restes ou traces pétrifiés d\'un être vivant du passé conservés dans la roche', isCorrect: true },
      { id: 'c', text: 'Une plante séchée trouvée dans le sol', isCorrect: false },
    ],
    correctAnswer: 'Les restes ou traces pétrifiés d\'un être vivant du passé conservés dans la roche',
    explanation: 'Un fossile est formé quand un organisme meurt, est enseveli sous des sédiments, et ses restes sont lentement remplacés par des minéraux. On peut voir des coquilles, os ou empreintes fossilisés.',
    hint: 'Les fossiles de dinosaures ont été conservés pendant des millions d\'années.',
    tags: ['ce1', 'sciences', 'terre', 'geologie', 'fossiles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-023',
    subject: 'sciences',
    title: 'Planètes : Jupiter',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la plus grande planète du système solaire ?',
    options: [
      { id: 'a', text: 'Saturne', isCorrect: false },
      { id: 'b', text: 'Jupiter', isCorrect: true },
      { id: 'c', text: 'La Terre', isCorrect: false },
    ],
    correctAnswer: 'Jupiter',
    explanation: 'Jupiter est la plus grande planète. Elle est tellement grande que 1 300 Terres rentreraient dedans. C\'est une planète gazeuse, sans surface solide.',
    hint: 'Jupiter a une grande tache rouge qui est en réalité une tempête géante.',
    tags: ['ce1', 'sciences', 'terre', 'astronomie', 'jupiter', 'planetes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce1-ter-024',
    subject: 'sciences',
    title: 'Séismes : tremblement de terre',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'geologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui cause les tremblements de terre ?',
    options: [
      { id: 'a', text: 'Des explosions de volcans sous la Terre', isCorrect: false },
      { id: 'b', text: 'Le mouvement des plaques tectoniques (grandes plaques de la croûte terrestre)', isCorrect: true },
      { id: 'c', text: 'Des tempêtes très violentes qui font vibrer le sol', isCorrect: false },
    ],
    correctAnswer: 'Le mouvement des plaques tectoniques (grandes plaques de la croûte terrestre)',
    explanation: 'La croûte terrestre est découpée en grandes plaques qui bougent très lentement. Quand deux plaques se heurtent ou glissent l\'une contre l\'autre, elles provoquent des séismes.',
    hint: 'Le Japon et la Californie sont souvent touchés par des séismes (zones de plaques).',
    tags: ['ce1', 'sciences', 'terre', 'geologie', 'seismes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
