import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCpOrthographeExercises: FrenchExercise[] = [
{
    id: 'fr-cp-orthographe-201',
    subject: 'francais',
    title: 'Son de la lettre M',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre M ?',
    prompt: 'Quel son fait la lettre M ?',
    options: [
      { id: 'a', text: '[m]', isCorrect: true },
      { id: 'b', text: '[l]', isCorrect: false },
      { id: 'c', text: '[r]', isCorrect: false },
    ],
    correctAnswer: '[m]',
    explanation: 'La lettre M fait le son [m] comme dans "maman".',
    hint: 'Pense à "maman".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-202',
    subject: 'francais',
    title: 'Son de la lettre L',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre L ?',
    prompt: 'Quel son fait la lettre L ?',
    options: [
      { id: 'a', text: '[l]', isCorrect: true },
      { id: 'b', text: '[m]', isCorrect: false },
      { id: 'c', text: '[f]', isCorrect: false },
    ],
    correctAnswer: '[l]',
    explanation: 'La lettre L fait le son [l] comme dans "lapin".',
    hint: 'Pense à "lapin".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'l'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-203',
    subject: 'francais',
    title: 'Son de la lettre R',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre R ?',
    prompt: 'Quel son fait la lettre R ?',
    options: [
      { id: 'a', text: '[r]', isCorrect: true },
      { id: 'b', text: '[l]', isCorrect: false },
      { id: 'c', text: '[n]', isCorrect: false },
    ],
    correctAnswer: '[r]',
    explanation: 'La lettre R fait le son [r] comme dans "rat".',
    hint: 'Pense à "rat".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'r'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-204',
    subject: 'francais',
    title: 'Son de la lettre S',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre S ?',
    prompt: 'Quel son fait la lettre S ?',
    options: [
      { id: 'a', text: '[s]', isCorrect: true },
      { id: 'b', text: '[t]', isCorrect: false },
      { id: 'c', text: '[p]', isCorrect: false },
    ],
    correctAnswer: '[s]',
    explanation: 'La lettre S fait le son [s] comme dans "sapin".',
    hint: 'Pense à "sapin".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 's'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-205',
    subject: 'francais',
    title: 'Son de la lettre T',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre T ?',
    prompt: 'Quel son fait la lettre T ?',
    options: [
      { id: 'a', text: '[t]', isCorrect: true },
      { id: 'b', text: '[d]', isCorrect: false },
      { id: 'c', text: '[s]', isCorrect: false },
    ],
    correctAnswer: '[t]',
    explanation: 'La lettre T fait le son [t] comme dans "table".',
    hint: 'Pense à "table".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 't'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-206',
    subject: 'francais',
    title: 'Son de la lettre P',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre P ?',
    prompt: 'Quel son fait la lettre P ?',
    options: [
      { id: 'a', text: '[p]', isCorrect: true },
      { id: 'b', text: '[b]', isCorrect: false },
      { id: 'c', text: '[t]', isCorrect: false },
    ],
    correctAnswer: '[p]',
    explanation: 'La lettre P fait le son [p] comme dans "panda".',
    hint: 'Pense à "panda".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'p'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-207',
    subject: 'francais',
    title: 'Son de la lettre F',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre F ?',
    prompt: 'Quel son fait la lettre F ?',
    options: [
      { id: 'a', text: '[f]', isCorrect: true },
      { id: 'b', text: '[v]', isCorrect: false },
      { id: 'c', text: '[p]', isCorrect: false },
    ],
    correctAnswer: '[f]',
    explanation: 'La lettre F fait le son [f] comme dans "farine".',
    hint: 'Pense à "farine".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'f'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-208',
    subject: 'francais',
    title: 'Son de la lettre V',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre V ?',
    prompt: 'Quel son fait la lettre V ?',
    options: [
      { id: 'a', text: '[v]', isCorrect: true },
      { id: 'b', text: '[f]', isCorrect: false },
      { id: 'c', text: '[b]', isCorrect: false },
    ],
    correctAnswer: '[v]',
    explanation: 'La lettre V fait le son [v] comme dans "vache".',
    hint: 'Pense à "vache".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'v'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-209',
    subject: 'francais',
    title: 'Son de la lettre N',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre N ?',
    prompt: 'Quel son fait la lettre N ?',
    options: [
      { id: 'a', text: '[n]', isCorrect: true },
      { id: 'b', text: '[m]', isCorrect: false },
      { id: 'c', text: '[d]', isCorrect: false },
    ],
    correctAnswer: '[n]',
    explanation: 'La lettre N fait le son [n] comme dans "nez".',
    hint: 'Pense à "nez".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'n'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-210',
    subject: 'francais',
    title: 'Son de la lettre D',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre D ?',
    prompt: 'Quel son fait la lettre D ?',
    options: [
      { id: 'a', text: '[d]', isCorrect: true },
      { id: 'b', text: '[t]', isCorrect: false },
      { id: 'c', text: '[b]', isCorrect: false },
    ],
    correctAnswer: '[d]',
    explanation: 'La lettre D fait le son [d] comme dans "dent".',
    hint: 'Pense à "dent".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'd'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-211',
    subject: 'francais',
    title: 'Son de la lettre B',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la lettre B ?',
    prompt: 'Quel son fait la lettre B ?',
    options: [
      { id: 'a', text: '[b]', isCorrect: true },
      { id: 'b', text: '[p]', isCorrect: false },
      { id: 'c', text: '[d]', isCorrect: false },
    ],
    correctAnswer: '[b]',
    explanation: 'La lettre B fait le son [b] comme dans "bébé".',
    hint: 'Pense à "bébé".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'foundation', 'b'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-212',
    subject: 'francais',
    title: 'Mot commençant par [m]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'son initial',
    format: 'qcm',
    instructions: 'Quel mot commence par le son [m] ?',
    prompt: 'Quel mot commence par le son [m] ?',
    options: [
      { id: 'a', text: 'maman', isCorrect: true },
      { id: 'b', text: 'sapin', isCorrect: false },
      { id: 'c', text: 'tapis', isCorrect: false },
    ],
    correctAnswer: 'maman',
    explanation: '"Maman" commence par [m].',
    hint: 'Dis les mots à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'son_initial', 'foundation', 'm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-213',
    subject: 'francais',
    title: 'Mot commençant par [l]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'son initial',
    format: 'qcm',
    instructions: 'Quel mot commence par le son [l] ?',
    prompt: 'Quel mot commence par le son [l] ?',
    options: [
      { id: 'a', text: 'lapin', isCorrect: true },
      { id: 'b', text: 'sapin', isCorrect: false },
      { id: 'c', text: 'maman', isCorrect: false },
    ],
    correctAnswer: 'lapin',
    explanation: '"Lapin" commence par [l].',
    hint: 'Dis les mots à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'son_initial', 'foundation', 'l'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-214',
    subject: 'francais',
    title: 'Mot commençant par [r]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'son initial',
    format: 'qcm',
    instructions: 'Quel mot commence par le son [r] ?',
    prompt: 'Quel mot commence par le son [r] ?',
    options: [
      { id: 'a', text: 'rat', isCorrect: true },
      { id: 'b', text: 'table', isCorrect: false },
      { id: 'c', text: 'vache', isCorrect: false },
    ],
    correctAnswer: 'rat',
    explanation: '"Rat" commence par [r].',
    hint: 'Dis les mots à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'son_initial', 'foundation', 'r'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-215',
    subject: 'francais',
    title: 'Mot commençant par [t]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'son initial',
    format: 'qcm',
    instructions: 'Quel mot commence par le son [t] ?',
    prompt: 'Quel mot commence par le son [t] ?',
    options: [
      { id: 'a', text: 'tomate', isCorrect: true },
      { id: 'b', text: 'lapin', isCorrect: false },
      { id: 'c', text: 'noir', isCorrect: false },
    ],
    correctAnswer: 'tomate',
    explanation: '"Tomate" commence par [t].',
    hint: 'Dis les mots à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'son_initial', 'foundation', 't'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-216',
    subject: 'francais',
    title: 'Mot commençant par [p]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'son initial',
    format: 'qcm',
    instructions: 'Quel mot commence par le son [p] ?',
    prompt: 'Quel mot commence par le son [p] ?',
    options: [
      { id: 'a', text: 'panda', isCorrect: true },
      { id: 'b', text: 'rose', isCorrect: false },
      { id: 'c', text: 'lune', isCorrect: false },
    ],
    correctAnswer: 'panda',
    explanation: '"Panda" commence par [p].',
    hint: 'Dis les mots à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'son_initial', 'foundation', 'p'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-217',
    subject: 'francais',
    title: 'Mot commençant par [f]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'son initial',
    format: 'qcm',
    instructions: 'Quel mot commence par le son [f] ?',
    prompt: 'Quel mot commence par le son [f] ?',
    options: [
      { id: 'a', text: 'farine', isCorrect: true },
      { id: 'b', text: 'dent', isCorrect: false },
      { id: 'c', text: 'robe', isCorrect: false },
    ],
    correctAnswer: 'farine',
    explanation: '"Farine" commence par [f].',
    hint: 'Dis les mots à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'son_initial', 'foundation', 'f'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-218',
    subject: 'francais',
    title: 'Mot commençant par [v]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'son initial',
    format: 'qcm',
    instructions: 'Quel mot commence par le son [v] ?',
    prompt: 'Quel mot commence par le son [v] ?',
    options: [
      { id: 'a', text: 'vache', isCorrect: true },
      { id: 'b', text: 'tapis', isCorrect: false },
      { id: 'c', text: 'lit', isCorrect: false },
    ],
    correctAnswer: 'vache',
    explanation: '"Vache" commence par [v].',
    hint: 'Dis les mots à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'son_initial', 'foundation', 'v'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-219',
    subject: 'francais',
    title: 'Vrai ou faux : [m] dans "maman"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Vrai ou faux ?',
    prompt: 'Le mot "maman" commence par le son [m].',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: '"Maman" commence bien par [m].',
    hint: 'Dis le mot à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'vrai_faux', 'standard', 'm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-220',
    subject: 'francais',
    title: 'Vrai ou faux : [t] dans "sapin"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Vrai ou faux ?',
    prompt: 'Le mot "sapin" commence par le son [t].',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: false },
      { id: 'b', text: 'Faux', isCorrect: true },
    ],
    correctAnswer: 'Faux',
    explanation: '"Sapin" commence par [s], pas par [t].',
    hint: 'Dis le mot à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'vrai_faux', 'standard', 's'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-221',
    subject: 'francais',
    title: 'Vrai ou faux : [f] dans "farine"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Vrai ou faux ?',
    prompt: 'Le mot "farine" commence par le son [f].',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: '"Farine" commence bien par [f].',
    hint: 'Dis le mot à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'vrai_faux', 'standard', 'f'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-222',
    subject: 'francais',
    title: 'Vrai ou faux : [l] dans "rat"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Vrai ou faux ?',
    prompt: 'Le mot "rat" commence par le son [l].',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: false },
      { id: 'b', text: 'Faux', isCorrect: true },
    ],
    correctAnswer: 'Faux',
    explanation: '"Rat" commence par [r], pas par [l].',
    hint: 'Dis le mot à voix haute.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'vrai_faux', 'standard', 'r'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-223',
    subject: 'francais',
    title: 'Quelle lettre fait [t] ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quelle lettre fait le son [t] ?',
    prompt: 'Parmi M, L et T, quelle lettre fait le son [t] ?',
    options: [
      { id: 'a', text: 'T', isCorrect: true },
      { id: 'b', text: 'M', isCorrect: false },
      { id: 'c', text: 'L', isCorrect: false },
    ],
    correctAnswer: 'T',
    explanation: 'La lettre T fait le son [t].',
    hint: 'Pense à "table".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'standard'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-224',
    subject: 'francais',
    title: 'Quelle lettre fait [v] ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quelle lettre fait le son [v] ?',
    prompt: 'Parmi P, F et V, quelle lettre fait le son [v] ?',
    options: [
      { id: 'a', text: 'V', isCorrect: true },
      { id: 'b', text: 'P', isCorrect: false },
      { id: 'c', text: 'F', isCorrect: false },
    ],
    correctAnswer: 'V',
    explanation: 'La lettre V fait le son [v].',
    hint: 'Pense à "vache".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'standard'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-225',
    subject: 'francais',
    title: 'Quelle lettre fait [n] ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quelle lettre fait le son [n] ?',
    prompt: 'Parmi R, S, N, D et B, quelle lettre fait le son [n] ?',
    options: [
      { id: 'a', text: 'N', isCorrect: true },
      { id: 'b', text: 'R', isCorrect: false },
      { id: 'c', text: 'B', isCorrect: false },
    ],
    correctAnswer: 'N',
    explanation: 'La lettre N fait le son [n].',
    hint: 'Pense à "nez".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'consonnes_simples', 'standard'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-226',
    subject: 'francais',
    title: 'Son de la voyelle A',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la voyelle A ?',
    prompt: 'Quel son fait la voyelle A ?',
    options: [
      { id: 'a', text: '[a]', isCorrect: true },
      { id: 'b', text: '[e]', isCorrect: false },
      { id: 'c', text: '[i]', isCorrect: false },
    ],
    correctAnswer: '[a]',
    explanation: 'La voyelle A fait le son [a] comme dans "ami".',
    hint: 'Pense à "ami".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'a'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-227',
    subject: 'francais',
    title: 'Son de la voyelle E',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la voyelle E ?',
    prompt: 'Quel son fait la voyelle E ?',
    options: [
      { id: 'a', text: '[e]', isCorrect: true },
      { id: 'b', text: '[a]', isCorrect: false },
      { id: 'c', text: '[o]', isCorrect: false },
    ],
    correctAnswer: '[e]',
    explanation: 'La voyelle E fait le son [e] comme dans "été".',
    hint: 'Pense à "été".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'e'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-228',
    subject: 'francais',
    title: 'Son de la voyelle I',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la voyelle I ?',
    prompt: 'Quel son fait la voyelle I ?',
    options: [
      { id: 'a', text: '[i]', isCorrect: true },
      { id: 'b', text: '[o]', isCorrect: false },
      { id: 'c', text: '[u]', isCorrect: false },
    ],
    correctAnswer: '[i]',
    explanation: 'La voyelle I fait le son [i] comme dans "lit".',
    hint: 'Pense à "lit".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'i'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-229',
    subject: 'francais',
    title: 'Son de la voyelle O',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la voyelle O ?',
    prompt: 'Quel son fait la voyelle O ?',
    options: [
      { id: 'a', text: '[o]', isCorrect: true },
      { id: 'b', text: '[a]', isCorrect: false },
      { id: 'c', text: '[u]', isCorrect: false },
    ],
    correctAnswer: '[o]',
    explanation: 'La voyelle O fait le son [o] comme dans "pot".',
    hint: 'Pense à "pot".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'o'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-230',
    subject: 'francais',
    title: 'Son de la voyelle U',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel son fait la voyelle U ?',
    prompt: 'Quel son fait la voyelle U ?',
    options: [
      { id: 'a', text: '[u]', isCorrect: true },
      { id: 'b', text: '[i]', isCorrect: false },
      { id: 'c', text: '[e]', isCorrect: false },
    ],
    correctAnswer: '[u]',
    explanation: 'La voyelle U fait le son [u] comme dans "lune".',
    hint: 'Pense à "lune".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'u'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-231',
    subject: 'francais',
    title: 'Mot avec [a]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [a] ?',
    prompt: 'Quel mot contient le son [a] ?',
    options: [
      { id: 'a', text: 'ami', isCorrect: true },
      { id: 'b', text: 'été', isCorrect: false },
      { id: 'c', text: 'lit', isCorrect: false },
    ],
    correctAnswer: 'ami',
    explanation: '"Ami" contient le son [a].',
    hint: 'Écoute le début du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'a'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-232',
    subject: 'francais',
    title: 'Mot avec [e]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [e] ?',
    prompt: 'Quel mot contient le son [e] ?',
    options: [
      { id: 'a', text: 'le', isCorrect: true },
      { id: 'b', text: 'lit', isCorrect: false },
      { id: 'c', text: 'ami', isCorrect: false },
    ],
    correctAnswer: 'le',
    explanation: '"Le" contient le son [e].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'e'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-233',
    subject: 'francais',
    title: 'Mot avec [i]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [i] ?',
    prompt: 'Quel mot contient le son [i] ?',
    options: [
      { id: 'a', text: 'lit', isCorrect: true },
      { id: 'b', text: 'pot', isCorrect: false },
      { id: 'c', text: 'été', isCorrect: false },
    ],
    correctAnswer: 'lit',
    explanation: '"Lit" contient le son [i].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'i'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-234',
    subject: 'francais',
    title: 'Mot avec [o]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [o] ?',
    prompt: 'Quel mot contient le son [o] ?',
    options: [
      { id: 'a', text: 'pot', isCorrect: true },
      { id: 'b', text: 'lit', isCorrect: false },
      { id: 'c', text: 'été', isCorrect: false },
    ],
    correctAnswer: 'pot',
    explanation: '"Pot" contient le son [o].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'o'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-235',
    subject: 'francais',
    title: 'Mot avec [u]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [u] ?',
    prompt: 'Quel mot contient le son [u] ?',
    options: [
      { id: 'a', text: 'lune', isCorrect: true },
      { id: 'b', text: 'ami', isCorrect: false },
      { id: 'c', text: 'pot', isCorrect: false },
    ],
    correctAnswer: 'lune',
    explanation: '"Lune" contient le son [u].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'foundation', 'u'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-236',
    subject: 'francais',
    title: 'Mot commençant par [a]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot commence par [a] ?',
    prompt: 'Quel mot commence par [a] ?',
    options: [
      { id: 'a', text: 'ami', isCorrect: true },
      { id: 'b', text: 'été', isCorrect: false },
      { id: 'c', text: 'lit', isCorrect: false },
    ],
    correctAnswer: 'ami',
    explanation: '"Ami" commence par [a].',
    hint: 'Écoute le tout premier son du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'son_initial', 'foundation', 'a'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-237',
    subject: 'francais',
    title: 'Mot commençant par [e]',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot commence par [e] ?',
    prompt: 'Quel mot commence par [e] ?',
    options: [
      { id: 'a', text: 'été', isCorrect: true },
      { id: 'b', text: 'lit', isCorrect: false },
      { id: 'c', text: 'pot', isCorrect: false },
    ],
    correctAnswer: 'été',
    explanation: '"Été" commence par [e].',
    hint: 'Écoute le tout premier son du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'son_initial', 'foundation', 'e'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-238',
    subject: 'francais',
    title: 'Vrai ou faux : [a] dans "ami"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'C\'est vrai ou c\'est faux ?',
    prompt: 'Le mot "ami" commence par [a]. Vrai ou faux ?',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: '"Ami" commence bien par [a].',
    hint: 'Prononce le mot doucement et écoute le début.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'vrai_faux', 'standard', 'a'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-239',
    subject: 'francais',
    title: 'Vrai ou faux : [a] dans "lit"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'C\'est vrai ou c\'est faux ?',
    prompt: 'Le mot "lit" commence par [a]. Vrai ou faux ?',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: false },
      { id: 'b', text: 'Faux', isCorrect: true },
    ],
    correctAnswer: 'Faux',
    explanation: '"Lit" commence par [i], pas par [a].',
    hint: 'Prononce le mot doucement et écoute le début.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'vrai_faux', 'standard', 'i'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-240',
    subject: 'francais',
    title: 'Vrai ou faux : [o] dans "pot"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'C\'est vrai ou c\'est faux ?',
    prompt: 'Le mot "pot" commence par [o]. Vrai ou faux ?',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: '"Pot" commence bien par [o].',
    hint: 'Prononce le mot doucement et écoute le début.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'vrai_faux', 'standard', 'o'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-241',
    subject: 'francais',
    title: 'Vrai ou faux : [i] dans "lune"',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'C\'est vrai ou c\'est faux ?',
    prompt: 'Le mot "lune" commence par [i]. Vrai ou faux ?',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: false },
      { id: 'b', text: 'Faux', isCorrect: true },
    ],
    correctAnswer: 'Faux',
    explanation: '"Lune" commence par [u], pas par [i].',
    hint: 'Prononce le mot doucement et écoute le début.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'vrai_faux', 'standard', 'u'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-242',
    subject: 'francais',
    title: 'Quelle lettre fait le son [i] ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quelle lettre fait le son [i] ?',
    prompt: 'Parmi A, E et I, quelle lettre fait le son [i] ?',
    options: [
      { id: 'a', text: 'I', isCorrect: true },
      { id: 'b', text: 'A', isCorrect: false },
      { id: 'c', text: 'E', isCorrect: false },
    ],
    correctAnswer: 'I',
    explanation: 'La lettre I fait le son [i] comme dans "lit".',
    hint: 'Pense au mot "lit".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'i'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-243',
    subject: 'francais',
    title: 'Quelle lettre fait le son [u] ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quelle lettre fait le son [u] ?',
    prompt: 'Parmi O, U et A, quelle lettre fait le son [u] ?',
    options: [
      { id: 'a', text: 'U', isCorrect: true },
      { id: 'b', text: 'O', isCorrect: false },
      { id: 'c', text: 'A', isCorrect: false },
    ],
    correctAnswer: 'U',
    explanation: 'La lettre U fait le son [u] comme dans "lune".',
    hint: 'Pense au mot "lune".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'u'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-244',
    subject: 'francais',
    title: 'Quelle lettre fait le son [o] ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quelle lettre fait le son [o] ?',
    prompt: 'Parmi A, E, I, O et U, quelle lettre fait le son [o] ?',
    options: [
      { id: 'a', text: 'O', isCorrect: true },
      { id: 'b', text: 'A', isCorrect: false },
      { id: 'c', text: 'U', isCorrect: false },
    ],
    correctAnswer: 'O',
    explanation: 'La lettre O fait le son [o] comme dans "pot".',
    hint: 'Pense au mot "pot".',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'o'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-245',
    subject: 'francais',
    title: 'Mot avec [a] — niveau 2',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [a] ?',
    prompt: 'Quel mot a le son [a] ?',
    options: [
      { id: 'a', text: 'chat', isCorrect: true },
      { id: 'b', text: 'été', isCorrect: false },
      { id: 'c', text: 'lit', isCorrect: false },
    ],
    correctAnswer: 'chat',
    explanation: '"Chat" contient le son [a].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'a'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-246',
    subject: 'francais',
    title: 'Mot avec [e] — niveau 2',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [e] ?',
    prompt: 'Quel mot a le son [e] ?',
    options: [
      { id: 'a', text: 'été', isCorrect: true },
      { id: 'b', text: 'ami', isCorrect: false },
      { id: 'c', text: 'pot', isCorrect: false },
    ],
    correctAnswer: 'été',
    explanation: '"Été" contient le son [e].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'e'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-247',
    subject: 'francais',
    title: 'Mot avec [i] — niveau 2',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [i] ?',
    prompt: 'Quel mot a le son [i] ?',
    options: [
      { id: 'a', text: 'tigre', isCorrect: true },
      { id: 'b', text: 'pot', isCorrect: false },
      { id: 'c', text: 'lune', isCorrect: false },
    ],
    correctAnswer: 'tigre',
    explanation: '"Tigre" contient le son [i].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'i'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-248',
    subject: 'francais',
    title: 'Mot avec [o] — niveau 2',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [o] ?',
    prompt: 'Quel mot a le son [o] ?',
    options: [
      { id: 'a', text: 'soleil', isCorrect: true },
      { id: 'b', text: 'ami', isCorrect: false },
      { id: 'c', text: 'lit', isCorrect: false },
    ],
    correctAnswer: 'soleil',
    explanation: '"Soleil" contient le son [o].',
    hint: 'Écoute la voyelle dans le mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'o'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-249',
    subject: 'francais',
    title: 'Mot avec [u] — niveau 2',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [u] ?',
    prompt: 'Quel mot a le son [u] ?',
    options: [
      { id: 'a', text: 'pur', isCorrect: true },
      { id: 'b', text: 'ami', isCorrect: false },
      { id: 'c', text: 'pot', isCorrect: false },
    ],
    correctAnswer: 'pur',
    explanation: '"Pur" contient le son [u].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'u'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-250',
    subject: 'francais',
    title: 'Mot avec [a] — niveau 2 (bis)',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: 'Quel mot a le son [a] ?',
    prompt: 'Quel mot a le son [a] ?',
    options: [
      { id: 'a', text: 'table', isCorrect: true },
      { id: 'b', text: 'lit', isCorrect: false },
      { id: 'c', text: 'été', isCorrect: false },
    ],
    correctAnswer: 'table',
    explanation: '"Table" contient le son [a].',
    hint: 'Écoute la voyelle du mot.',
    tags: ['cp', 'orthographe', 'sons_gpp', 'voyelles_simples', 'standard', 'a'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-lecture-101',
    subject: 'francais',
    title: 'Comprendre une action simple',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis la phrase et réponds.',
    prompt: 'Lina ferme la porte. Que fait Lina ?',
    options: [
      { id: 'a', text: 'Elle ferme la porte', isCorrect: true },
      { id: 'b', text: 'Elle ouvre la fenêtre', isCorrect: false },
      { id: 'c', text: 'Elle lave la table', isCorrect: false }
    ],
    correctAnswer: 'Elle ferme la porte',
    explanation: 'La phrase dit que Lina ferme la porte.',
    hint: 'Cherche le verbe dans la phrase.',
    tags: ['cp','lecture','action','maison','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-102',
    subject: 'francais',
    title: 'Trouver le lieu',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du lieu',
    format: 'qcm',
    instructions: 'Lis la phrase puis réponds.',
    prompt: 'Milo joue dans la cour. Où joue Milo ?',
    options: [
      { id: 'a', text: 'Dans la cour', isCorrect: true },
      { id: 'b', text: 'Dans le bain', isCorrect: false },
      { id: 'c', text: 'Dans le cartable', isCorrect: false }
    ],
    correctAnswer: 'Dans la cour',
    explanation: 'La phrase dit que Milo joue dans la cour.',
    hint: 'Relis la fin de la phrase.',
    tags: ['cp','lecture','lieu','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-103',
    subject: 'francais',
    title: 'Trouver le personnage',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du sujet',
    format: 'qcm',
    instructions: 'Lis la phrase et réponds.',
    prompt: 'Le bébé dort. Qui dort ?',
    options: [
      { id: 'a', text: 'Le bébé', isCorrect: true },
      { id: 'b', text: 'Le lit', isCorrect: false },
      { id: 'c', text: 'La lampe', isCorrect: false }
    ],
    correctAnswer: 'Le bébé',
    explanation: 'C’est le bébé qui dort.',
    hint: 'Cherche qui fait l’action.',
    tags: ['cp','lecture','sujet','famille','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-104',
    subject: 'francais',
    title: 'Trouver l’objet',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Nora dessine une étoile. Que dessine Nora ?',
    options: [
      { id: 'a', text: 'Une étoile', isCorrect: true },
      { id: 'b', text: 'Une chaussure', isCorrect: false },
      { id: 'c', text: 'Une soupe', isCorrect: false }
    ],
    correctAnswer: 'Une étoile',
    explanation: 'La phrase dit que Nora dessine une étoile.',
    hint: 'Cherche ce que Nora dessine.',
    tags: ['cp','lecture','objet','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-105',
    subject: 'francais',
    title: 'Compléter une phrase logique',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Choisis le mot qui complète bien la phrase.',
    prompt: 'Le poisson nage dans l\'...',
    options: [
      { id: 'a', text: 'eau', isCorrect: true },
      { id: 'b', text: 'cahier', isCorrect: false },
      { id: 'c', text: 'pull', isCorrect: false }
    ],
    correctAnswer: 'eau',
    explanation: 'Un poisson nage dans l’eau.',
    hint: 'Cherche où vit le poisson.',
    tags: ['cp','lecture','phrase-simple','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-106',
    subject: 'francais',
    title: 'Associer deux phrases proches',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'association de sens',
    format: 'qcm',
    instructions: 'Choisis la phrase qui veut dire presque la même chose.',
    prompt: 'Le chat dort sur le canapé.',
    options: [
      { id: 'a', text: 'Le chat est endormi sur le canapé', isCorrect: true },
      { id: 'b', text: 'Le chat mange sous la table', isCorrect: false },
      { id: 'c', text: 'Le chien dort dehors', isCorrect: false }
    ],
    correctAnswer: 'Le chat est endormi sur le canapé',
    explanation: 'La première réponse reprend exactement le sens de la phrase.',
    hint: 'Compare le personnage, l’action et le lieu.',
    tags: ['cp','lecture','association','maison','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-107',
    subject: 'francais',
    title: 'Comprendre une consigne simple',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Papa lave la voiture. Que lave papa ?',
    options: [
      { id: 'a', text: 'La voiture', isCorrect: true },
      { id: 'b', text: 'Le vélo', isCorrect: false },
      { id: 'c', text: 'La veste', isCorrect: false }
    ],
    correctAnswer: 'La voiture',
    explanation: 'La phrase dit que papa lave la voiture.',
    hint: 'Cherche l’objet de l’action.',
    tags: ['cp','lecture','objet','famille','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-108',
    subject: 'francais',
    title: 'Identifier le lieu d’une action',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du lieu',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Lila dort dans son lit. Où dort Lila ?',
    options: [
      { id: 'a', text: 'Dans son lit', isCorrect: true },
      { id: 'b', text: 'Dans la rue', isCorrect: false },
      { id: 'c', text: 'Dans la cuisine', isCorrect: false }
    ],
    correctAnswer: 'Dans son lit',
    explanation: 'La phrase dit que Lila dort dans son lit.',
    hint: 'Cherche le lieu.',
    tags: ['cp','lecture','lieu','maison','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-109',
    subject: 'francais',
    title: 'Qui fait l’action ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du sujet',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le lapin saute. Qui saute ?',
    options: [
      { id: 'a', text: 'Le lapin', isCorrect: true },
      { id: 'b', text: 'La carotte', isCorrect: false },
      { id: 'c', text: 'Le jardin', isCorrect: false }
    ],
    correctAnswer: 'Le lapin',
    explanation: 'C’est le lapin qui saute.',
    hint: 'Cherche qui fait l’action.',
    tags: ['cp','lecture','sujet','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-110',
    subject: 'francais',
    title: 'Que mange le personnage ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Tom mange une banane. Que mange Tom ?',
    options: [
      { id: 'a', text: 'Une banane', isCorrect: true },
      { id: 'b', text: 'Une craie', isCorrect: false },
      { id: 'c', text: 'Un ballon', isCorrect: false }
    ],
    correctAnswer: 'Une banane',
    explanation: 'La phrase dit que Tom mange une banane.',
    hint: 'Cherche ce que Tom mange.',
    tags: ['cp','lecture','nourriture','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-111',
    subject: 'francais',
    title: 'Trouver la bonne fin',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Choisis la bonne fin de phrase.',
    prompt: 'La maîtresse écrit au ...',
    options: [
      { id: 'a', text: 'tableau', isCorrect: true },
      { id: 'b', text: 'nuage', isCorrect: false },
      { id: 'c', text: 'gâteau', isCorrect: false }
    ],
    correctAnswer: 'tableau',
    explanation: 'Une maîtresse écrit au tableau.',
    hint: 'Pense à l’école.',
    tags: ['cp','lecture','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-112',
    subject: 'francais',
    title: 'Lire et repérer un animal',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le cheval court vite. Quel animal court ?',
    options: [
      { id: 'a', text: 'Le cheval', isCorrect: true },
      { id: 'b', text: 'Le tracteur', isCorrect: false },
      { id: 'c', text: 'Le banc', isCorrect: false }
    ],
    correctAnswer: 'Le cheval',
    explanation: 'La phrase parle du cheval.',
    hint: 'Cherche l’animal.',
    tags: ['cp','lecture','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-113',
    subject: 'francais',
    title: 'Comprendre un lieu naturel',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du lieu',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Le canard nage dans la mare. Où nage le canard ?',
    options: [
      { id: 'a', text: 'Dans la mare', isCorrect: true },
      { id: 'b', text: 'Dans la classe', isCorrect: false },
      { id: 'c', text: 'Dans la boîte', isCorrect: false }
    ],
    correctAnswer: 'Dans la mare',
    explanation: 'Le canard nage dans la mare.',
    hint: 'Cherche le lieu.',
    tags: ['cp','lecture','nature','lieu','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-114',
    subject: 'francais',
    title: 'Repérer une action de classe',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Emma lit un livre. Que fait Emma ?',
    options: [
      { id: 'a', text: 'Elle lit', isCorrect: true },
      { id: 'b', text: 'Elle saute', isCorrect: false },
      { id: 'c', text: 'Elle peint', isCorrect: false }
    ],
    correctAnswer: 'Elle lit',
    explanation: 'La phrase dit qu’Emma lit.',
    hint: 'Cherche l’action.',
    tags: ['cp','lecture','ecole','action','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-115',
    subject: 'francais',
    title: 'Choisir la phrase identique',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'association de sens',
    format: 'qcm',
    instructions: 'Choisis la phrase qui dit la même chose.',
    prompt: 'Un oiseau chante sur le toit.',
    options: [
      { id: 'a', text: 'Sur le toit, un oiseau chante.', isCorrect: true },
      { id: 'b', text: 'Un oiseau dort sous la table', isCorrect: false },
      { id: 'c', text: 'Le toit chante', isCorrect: false }
    ],
    correctAnswer: 'Sur le toit, un oiseau chante.',
    explanation: 'La phrase dit la même chose, les mots sont juste dans un ordre différent.',
    hint: 'Relis toute la phrase.',
    tags: ['cp','lecture','association','nature','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-116',
    subject: 'francais',
    title: 'Identifier un objet d’école',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Noé range son cahier. Que range Noé ?',
    options: [
      { id: 'a', text: 'Son cahier', isCorrect: true },
      { id: 'b', text: 'Son oreiller', isCorrect: false },
      { id: 'c', text: 'Son manteau', isCorrect: false }
    ],
    correctAnswer: 'Son cahier',
    explanation: 'La phrase dit que Noé range son cahier.',
    hint: 'Cherche l’objet.',
    tags: ['cp','lecture','ecole','objet','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-117',
    subject: 'francais',
    title: 'Identifier le personnage dans une phrase',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'identification du sujet',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'La maîtresse parle. Qui parle ?',
    options: [
      { id: 'a', text: 'La maîtresse', isCorrect: true },
      { id: 'b', text: 'La classe', isCorrect: false },
      { id: 'c', text: 'Le tableau', isCorrect: false }
    ],
    correctAnswer: 'La maîtresse',
    explanation: 'La maîtresse fait l’action de parler.',
    hint: 'Qui fait l’action ?',
    tags: ['cp','lecture','sujet','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-118',
    subject: 'francais',
    title: 'Trouver la bonne réponse explicite',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Léo met son manteau car il a froid. Pourquoi met-il son manteau ?',
    options: [
      { id: 'a', text: 'Car il a froid', isCorrect: true },
      { id: 'b', text: 'Car il nage', isCorrect: false },
      { id: 'c', text: 'Car il dort', isCorrect: false }
    ],
    correctAnswer: 'Car il a froid',
    explanation: 'La raison est donnée dans la phrase.',
    hint: 'Relis la fin.',
    tags: ['cp','lecture','cause','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-119',
    subject: 'francais',
    title: 'Comprendre un petit déplacement',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'comprehension de phrase',
    format: 'qcm',
    instructions: 'Lis puis réponds.',
    prompt: 'Zoé va au parc avec sa balle. Où va Zoé ?',
    options: [
      { id: 'a', text: 'Au parc', isCorrect: true },
      { id: 'b', text: 'À la cave', isCorrect: false },
      { id: 'c', text: 'Au garage', isCorrect: false }
    ],
    correctAnswer: 'Au parc',
    explanation: 'La phrase dit que Zoé va au parc.',
    hint: 'Cherche où elle va.',
    tags: ['cp','lecture','lieu','jeux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-lecture-120',
    subject: 'francais',
    title: 'Associer phrase et sens',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'lecture',
    subskill: 'association de sens',
    format: 'qcm',
    instructions: 'Choisis la phrase qui correspond.',
    prompt: 'Le bébé pleure dans son lit.',
    options: [
      { id: 'a', text: 'Dans son lit, le bébé pleure.', isCorrect: true },
      { id: 'b', text: 'Le bébé rit dans le jardin', isCorrect: false },
      { id: 'c', text: 'Le lit pleure', isCorrect: false }
    ],
    correctAnswer: 'Dans son lit, le bébé pleure.',
    explanation: 'Les mots sont les mêmes, dans un ordre légèrement différent — le sens ne change pas.',
    hint: 'Compare tous les mots.',
    tags: ['cp','lecture','association','famille','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },
  /* =====================================================================
     CP — ORTHOGRAPHE (fr-cp-orthographe-101 à 118)
  ===================================================================== */
  {
    id: 'fr-cp-orthographe-101',
    subject: 'francais',
    title: 'Choisir un ou une',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'determinants un-une',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ girafe court.',
    options: [
      { id: 'a', text: 'Un', isCorrect: false },
      { id: 'b', text: 'Une', isCorrect: true }
    ],
    correctAnswer: 'Une',
    explanation: 'On dit une girafe.',
    hint: 'Girafe est féminin.',
    tags: ['cp','orthographe','determinants','un-une','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-102',
    subject: 'francais',
    title: 'Choisir le ou la',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'determinants le-la',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ ballon roule.',
    options: [
      { id: 'a', text: 'Le', isCorrect: true },
      { id: 'b', text: 'La', isCorrect: false }
    ],
    correctAnswer: 'Le',
    explanation: 'On dit le ballon.',
    hint: 'Ballon est masculin.',
    tags: ['cp','orthographe','determinants','le-la','jeux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-103',
    subject: 'francais',
    title: 'Pluriel simple',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'pluriel en s',
    format: 'qcm',
    instructions: 'Choisis la bonne écriture.',
    prompt: 'Plusieurs lapin :',
    options: [
      { id: 'a', text: 'des lapins', isCorrect: true },
      { id: 'b', text: 'des lapin', isCorrect: false }
    ],
    correctAnswer: 'des lapins',
    explanation: 'Au pluriel, on ajoute souvent un s.',
    hint: 'Il y en a plusieurs.',
    tags: ['cp','orthographe','pluriel','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-104',
    subject: 'francais',
    title: 'Mon ou ma',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'ma-mon',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ veste est rouge.',
    options: [
      { id: 'a', text: 'Mon', isCorrect: false },
      { id: 'b', text: 'Ma', isCorrect: true }
    ],
    correctAnswer: 'Ma',
    explanation: 'On dit ma veste.',
    hint: 'Veste est féminin.',
    tags: ['cp','orthographe','ma-mon','vetements','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-105',
    subject: 'francais',
    title: 'Et ou est',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Léo ___ Mila jouent.',
    options: [
      { id: 'a', text: 'et', isCorrect: true },
      { id: 'b', text: 'est', isCorrect: false }
    ],
    correctAnswer: 'et',
    explanation: 'Le mot et relie deux prénoms.',
    hint: 'Ici, on ajoute une personne.',
    tags: ['cp','orthographe','et-est','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-106',
    subject: 'francais',
    title: 'Son ou sont',
    schoolClass: 'CP',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ cartable est bleu.',
    options: [
      { id: 'a', text: 'Son', isCorrect: true },
      { id: 'b', text: 'Sont', isCorrect: false }
    ],
    correctAnswer: 'Son',
    explanation: 'On parle du cartable de quelqu’un.',
    hint: 'On montre un objet.',
    tags: ['cp','orthographe','son-sont','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-107',
    subject: 'francais',
    title: 'Un ou une avec objet',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'determinants un-une',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ tomate est ronde.',
    options: [
      { id: 'a', text: 'Un', isCorrect: false },
      { id: 'b', text: 'Une', isCorrect: true }
    ],
    correctAnswer: 'Une',
    explanation: 'On dit une tomate.',
    hint: 'Tomate est féminin.',
    tags: ['cp','orthographe','determinants','un-une','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-108',
    subject: 'francais',
    title: 'Le ou la avec véhicule',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'determinants le-la',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ vélo est neuf.',
    options: [
      { id: 'a', text: 'Le', isCorrect: true },
      { id: 'b', text: 'La', isCorrect: false }
    ],
    correctAnswer: 'Le',
    explanation: 'On dit le vélo.',
    hint: 'Vélo est masculin.',
    tags: ['cp','orthographe','determinants','le-la','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-109',
    subject: 'francais',
    title: 'Ma ou mon avec maison',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'ma-mon',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ chambre est rangée.',
    options: [
      { id: 'a', text: 'Mon', isCorrect: false },
      { id: 'b', text: 'Ma', isCorrect: true }
    ],
    correctAnswer: 'Ma',
    explanation: 'On dit ma chambre.',
    hint: 'Chambre est féminin.',
    tags: ['cp','orthographe','ma-mon','maison','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-110',
    subject: 'francais',
    title: 'Mon ou ma avec école',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'ma-mon',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ cahier est propre.',
    options: [
      { id: 'a', text: 'Mon', isCorrect: true },
      { id: 'b', text: 'Ma', isCorrect: false }
    ],
    correctAnswer: 'Mon',
    explanation: 'On dit mon cahier.',
    hint: 'Cahier est masculin.',
    tags: ['cp','orthographe','ma-mon','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-111',
    subject: 'francais',
    title: 'Pluriel avec objet',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'pluriel en s',
    format: 'qcm',
    instructions: 'Choisis la bonne écriture.',
    prompt: 'Plusieurs vélo :',
    options: [
      { id: 'a', text: 'des vélos', isCorrect: true },
      { id: 'b', text: 'des vélo', isCorrect: false }
    ],
    correctAnswer: 'des vélos',
    explanation: 'Au pluriel, on ajoute un s.',
    hint: 'Ils sont plusieurs.',
    tags: ['cp','orthographe','pluriel','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-112',
    subject: 'francais',
    title: 'Pluriel avec animal',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'pluriel en s',
    format: 'qcm',
    instructions: 'Choisis la bonne écriture.',
    prompt: 'Plusieurs chat :',
    options: [
      { id: 'a', text: 'des chats', isCorrect: true },
      { id: 'b', text: 'des chat', isCorrect: false }
    ],
    correctAnswer: 'des chats',
    explanation: 'Au pluriel, on écrit des chats.',
    hint: 'Regarde s’il y en a plusieurs.',
    tags: ['cp','orthographe','pluriel','animaux','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-113',
    subject: 'francais',
    title: 'Et ou est avec verbe',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Le chat ___ noir.',
    options: [
      { id: 'a', text: 'et', isCorrect: false },
      { id: 'b', text: 'est', isCorrect: true }
    ],
    correctAnswer: 'est',
    explanation: 'Ici, est est le verbe être.',
    hint: 'Peut-on dire était ?',
    tags: ['cp','orthographe','et-est','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-114',
    subject: 'francais',
    title: 'Son ou sont avec pluriel',
    schoolClass: 'CP',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux simples',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Ils ___ prêts.',
    options: [
      { id: 'a', text: 'son', isCorrect: false },
      { id: 'b', text: 'sont', isCorrect: true }
    ],
    correctAnswer: 'sont',
    explanation: 'Avec ils, on utilise souvent sont.',
    hint: 'Peut-on dire ils étaient ?',
    tags: ['cp','orthographe','son-sont','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-115',
    subject: 'francais',
    title: 'Le ou la avec nature',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'determinants le-la',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ soleil brille.',
    options: [
      { id: 'a', text: 'Le', isCorrect: true },
      { id: 'b', text: 'La', isCorrect: false }
    ],
    correctAnswer: 'Le',
    explanation: 'On dit le soleil.',
    hint: 'Soleil est masculin.',
    tags: ['cp','orthographe','determinants','nature','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-116',
    subject: 'francais',
    title: 'Un ou une avec classe',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'determinants un-une',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ règle est longue.',
    options: [
      { id: 'a', text: 'Un', isCorrect: false },
      { id: 'b', text: 'Une', isCorrect: true }
    ],
    correctAnswer: 'Une',
    explanation: 'On dit une règle.',
    hint: 'Règle est féminin.',
    tags: ['cp','orthographe','determinants','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-117',
    subject: 'francais',
    title: 'Ma ou mon avec famille',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'ma-mon',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: '___ frère joue.',
    options: [
      { id: 'a', text: 'Mon', isCorrect: true },
      { id: 'b', text: 'Ma', isCorrect: false }
    ],
    correctAnswer: 'Mon',
    explanation: 'On dit mon frère.',
    hint: 'Frère est masculin.',
    tags: ['cp','orthographe','ma-mon','famille','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-orthographe-118',
    subject: 'francais',
    title: 'Pluriel avec fourniture',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'pluriel en s',
    format: 'qcm',
    instructions: 'Choisis la bonne écriture.',
    prompt: 'Plusieurs crayon :',
    options: [
      { id: 'a', text: 'des crayons', isCorrect: true },
      { id: 'b', text: 'des crayon', isCorrect: false }
    ],
    correctAnswer: 'des crayons',
    explanation: 'Au pluriel, on écrit des crayons.',
    hint: 'On parle de plusieurs objets.',
    tags: ['cp','orthographe','pluriel','ecole','qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

];
