import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCpRevisionExercises: FrenchExercise[] = [
  /* =====================================================================
     CP — RÉVISIONS MÉLANGÉES (fr-cp-revision-101 à 125)
  ===================================================================== */
  {
    id: 'fr-cp-revision-101',
    subject: 'francais',
    title: 'Son [m] — quel son fait M ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: "Quel son fait la lettre M ?",
    prompt: "Quel son fait la lettre M ?",
    options: [
      { id: 'a', text: '[m]', isCorrect: true },
      { id: 'b', text: '[l]', isCorrect: false },
      { id: 'c', text: '[p]', isCorrect: false },
    ],
    correctAnswer: '[m]',
    explanation: "M fait le son [m] comme dans maman.",
    hint: "Pense au mot maman.",
    tags: ['cp', 'revision', 'sons', 'correspondance_lettre_son', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-revision-102',
    subject: 'francais',
    title: 'Son [a] — quel son fait A ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: "Quel son fait la lettre A ?",
    prompt: "Quel son fait la lettre A ?",
    options: [
      { id: 'a', text: '[a]', isCorrect: true },
      { id: 'b', text: '[o]', isCorrect: false },
      { id: 'c', text: '[i]', isCorrect: false },
    ],
    correctAnswer: '[a]',
    explanation: "A fait le son [a] comme dans ananas.",
    hint: "Pense au mot ananas.",
    tags: ['cp', 'revision', 'voyelles', 'correspondance_lettre_son', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-revision-103',
    subject: 'francais',
    title: 'M est une lettre — vrai ou faux ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'reconnaissance des lettres',
    format: 'qcm',
    instructions: "C'est une lettre ou un nombre ?",
    prompt: "M. C'est une lettre. Vrai ou faux ?",
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: "M est une lettre de l'alphabet.",
    hint: "Regarde si c'est un signe pour compter ou une lettre.",
    tags: ['cp', 'revision', 'lettres', 'alphabet', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-revision-104',
    subject: 'francais',
    title: 'Voyelle O — laquelle est une voyelle ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'voyelles simples',
    format: 'qcm',
    instructions: "Laquelle est une voyelle ?",
    prompt: "Laquelle est une voyelle ?",
    options: [
      { id: 'a', text: 'O', isCorrect: true },
      { id: 'b', text: 'M', isCorrect: false },
      { id: 'c', text: 'R', isCorrect: false },
    ],
    correctAnswer: 'O',
    explanation: "O est une voyelle comme A, E, I, U.",
    hint: "Les voyelles sont A, E, I, O, U.",
    tags: ['cp', 'revision', 'voyelles', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-revision-105',
    subject: 'francais',
    title: 'Syllabe MA — laquelle est MA ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'decodage syllabique',
    format: 'qcm',
    instructions: "Laquelle est la syllabe MA ?",
    prompt: "Laquelle est la syllabe MA ?",
    options: [
      { id: 'a', text: 'MA', isCorrect: true },
      { id: 'b', text: 'MO', isCorrect: false },
      { id: 'c', text: 'AM', isCorrect: false },
    ],
    correctAnswer: 'MA',
    explanation: "MA est la syllabe M + A.",
    hint: "M + A = MA.",
    tags: ['cp', 'revision', 'syllabes', 'decodage', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-106',
    subject: 'francais',
    title: "Mot maman — c'est le mot maman ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'lecture de mots simples',
    format: 'qcm',
    instructions: "C'est le mot maman ?",
    prompt: "Maman. C'est le mot maman. Vrai ou faux ?",
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: "Maman est un mot très fréquent.",
    hint: "Lis les lettres une par une.",
    tags: ['cp', 'revision', 'mots', 'lecture_mots', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-107',
    subject: 'francais',
    title: "Papa dort — qui dort ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrases simples',
    format: 'qcm',
    instructions: "Lis la phrase. Qui dort ?",
    prompt: "Papa dort. Qui dort ?",
    options: [
      { id: 'a', text: 'Papa', isCorrect: true },
      { id: 'b', text: 'Maman', isCorrect: false },
      { id: 'c', text: 'Le chat', isCorrect: false },
    ],
    correctAnswer: 'Papa',
    explanation: "Papa est celui qui dort dans la phrase.",
    hint: "Lis bien le début de la phrase.",
    tags: ['cp', 'revision', 'comprehension', 'phrases_simples', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-108',
    subject: 'francais',
    title: "Le chat — c'est un animal ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'categories semantiques',
    format: 'qcm',
    instructions: "Le chat, c'est un animal. Vrai ou faux ?",
    prompt: "Le chat. C'est un animal. Vrai ou faux ?",
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: "Le chat est un animal domestique.",
    hint: "Pense aux animaux que tu connais.",
    tags: ['cp', 'revision', 'vocabulaire', 'animaux', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:vocabulaire',
  },

  {
    id: 'fr-cp-revision-109',
    subject: 'francais',
    title: "Majuscule au début — bien écrit ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'ponctuation de phrase simple',
    format: 'qcm',
    instructions: "La phrase est bien écrite avec une majuscule ?",
    prompt: "Papa dort. C'est bien écrit avec majuscule. Vrai ou faux ?",
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: "Une phrase commence toujours par une majuscule.",
    hint: "Regarde la première lettre.",
    tags: ['cp', 'revision', 'ponctuation', 'majuscule', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cp-revision-110',
    subject: 'francais',
    title: "Point final — bien écrit ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'ponctuation de phrase simple',
    format: 'qcm',
    instructions: "La phrase est bien écrite avec un point ?",
    prompt: "Papa dort. C'est bien écrit avec un point. Vrai ou faux ?",
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: "Une phrase se termine toujours par un point.",
    hint: "Regarde la fin de la phrase.",
    tags: ['cp', 'revision', 'ponctuation', 'point', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cp-revision-111',
    subject: 'francais',
    title: "Mot chat — lequel est chat ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'lecture de mots simples',
    format: 'qcm',
    instructions: "Lis. C'est quel mot ?",
    prompt: "Laquelle est le mot chat ?",
    options: [
      { id: 'a', text: 'chat', isCorrect: true },
      { id: 'b', text: 'chien', isCorrect: false },
      { id: 'c', text: 'oiseau', isCorrect: false },
    ],
    correctAnswer: 'chat',
    explanation: "Chat est un animal domestique.",
    hint: "Lis chaque mot lentement.",
    tags: ['cp', 'revision', 'mots', 'lecture_mots', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-112',
    subject: 'francais',
    title: "Syllabe LI — laquelle est LI ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'decodage syllabique',
    format: 'qcm',
    instructions: "Laquelle est la syllabe LI ?",
    prompt: "Laquelle est la syllabe LI ?",
    options: [
      { id: 'a', text: 'LI', isCorrect: true },
      { id: 'b', text: 'IL', isCorrect: false },
      { id: 'c', text: 'LA', isCorrect: false },
    ],
    correctAnswer: 'LI',
    explanation: "LI est la syllabe L + I.",
    hint: "L + I = LI.",
    tags: ['cp', 'revision', 'syllabes', 'decodage', 'foundation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-113',
    subject: 'francais',
    title: "Maman lit — qui lit ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrases simples',
    format: 'qcm',
    instructions: "Lis la phrase. Qui lit ?",
    prompt: "Maman lit. Qui lit ?",
    options: [
      { id: 'a', text: 'Maman', isCorrect: true },
      { id: 'b', text: 'Papa', isCorrect: false },
      { id: 'c', text: 'Tom', isCorrect: false },
    ],
    correctAnswer: 'Maman',
    explanation: "Maman est celle qui lit dans la phrase.",
    hint: "Lis bien le début de la phrase.",
    tags: ['cp', 'revision', 'comprehension', 'phrases_simples', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-114',
    subject: 'francais',
    title: "Papa joue — bonne phrase ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'ordre des mots',
    format: 'qcm',
    instructions: "Quelle est la bonne phrase ?",
    prompt: "Laquelle est la bonne phrase ?",
    options: [
      { id: 'a', text: 'Papa joue', isCorrect: true },
      { id: 'b', text: 'joue Papa', isCorrect: false },
    ],
    correctAnswer: 'Papa joue',
    explanation: "Papa joue est dans le bon ordre : sujet puis verbe.",
    hint: "Le sujet vient avant le verbe.",
    tags: ['cp', 'revision', 'syntaxe', 'ordre_mots', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cp-revision-115',
    subject: 'francais',
    title: "Voyelle I — laquelle est une voyelle ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'voyelles simples',
    format: 'qcm',
    instructions: "Laquelle est une voyelle ?",
    prompt: "Laquelle est une voyelle ?",
    options: [
      { id: 'a', text: 'I', isCorrect: true },
      { id: 'b', text: 'T', isCorrect: false },
      { id: 'c', text: 'N', isCorrect: false },
    ],
    correctAnswer: 'I',
    explanation: "I est une voyelle comme A, E, O, U.",
    hint: "Les voyelles sont A, E, I, O, U.",
    tags: ['cp', 'revision', 'voyelles', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-revision-116',
    subject: 'francais',
    title: "Son [l] — quel son fait L ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: "Quel son fait la lettre L ?",
    prompt: "Quel son fait la lettre L ?",
    options: [
      { id: 'a', text: '[l]', isCorrect: true },
      { id: 'b', text: '[r]', isCorrect: false },
      { id: 'c', text: '[m]', isCorrect: false },
    ],
    correctAnswer: '[l]',
    explanation: "L fait le son [l] comme dans lapin.",
    hint: "Pense au mot lapin.",
    tags: ['cp', 'revision', 'sons', 'correspondance_lettre_son', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-revision-117',
    subject: 'francais',
    title: "Mot soleil — lequel est soleil ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'lecture de mots simples',
    format: 'qcm',
    instructions: "Lis. C'est quel mot ?",
    prompt: "Laquelle est le mot soleil ?",
    options: [
      { id: 'a', text: 'soleil', isCorrect: true },
      { id: 'b', text: 'lune', isCorrect: false },
      { id: 'c', text: "etoile", isCorrect: false },
    ],
    correctAnswer: 'soleil',
    explanation: "Le soleil brille dans le ciel.",
    hint: "Lis chaque mot lentement.",
    tags: ['cp', 'revision', 'mots', 'lecture_mots', 'nature', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-118',
    subject: 'francais',
    title: "Phrase complète — majuscule et point ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'ponctuation de phrase simple',
    format: 'qcm',
    instructions: "La phrase est bien écrite avec majuscule et point ?",
    prompt: "Le chat dort. C'est bien écrit avec majuscule et point. Vrai ou faux ?",
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: "La phrase a une majuscule au debut et un point a la fin.",
    hint: "Verifie le debut et la fin de la phrase.",
    tags: ['cp', 'revision', 'ponctuation', 'majuscule', 'point', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cp-revision-119',
    subject: 'francais',
    title: "Tu manges une pomme — quoi ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrases simples',
    format: 'qcm',
    instructions: "Lis la phrase. Tu manges quoi ?",
    prompt: "Tu manges une pomme. Tu manges quoi ?",
    options: [
      { id: 'a', text: 'une pomme', isCorrect: true },
      { id: 'b', text: 'une orange', isCorrect: false },
      { id: 'c', text: "un gateau", isCorrect: false },
    ],
    correctAnswer: 'une pomme',
    explanation: "Une pomme est ce qu'on mange dans la phrase.",
    hint: "Lis bien toute la phrase.",
    tags: ['cp', 'revision', 'comprehension', 'phrases_simples', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-120',
    subject: 'francais',
    title: "Syllabe RO — laquelle est RO ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'decodage syllabique',
    format: 'qcm',
    instructions: "Laquelle est la syllabe RO ?",
    prompt: "Laquelle est la syllabe RO ?",
    options: [
      { id: 'a', text: 'RO', isCorrect: true },
      { id: 'b', text: 'OR', isCorrect: false },
      { id: 'c', text: 'RA', isCorrect: false },
    ],
    correctAnswer: 'RO',
    explanation: "RO est la syllabe R + O.",
    hint: "R + O = RO.",
    tags: ['cp', 'revision', 'syllabes', 'decodage', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-121',
    subject: 'francais',
    title: "Elle mange une pomme — bonne phrase ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'ordre des mots',
    format: 'qcm',
    instructions: "Quelle est la bonne phrase ?",
    prompt: "Laquelle est la bonne phrase ?",
    options: [
      { id: 'a', text: 'Elle mange une pomme', isCorrect: true },
      { id: 'b', text: 'mange Elle une pomme', isCorrect: false },
    ],
    correctAnswer: 'Elle mange une pomme',
    explanation: "Elle mange une pomme est dans le bon ordre.",
    hint: "Le sujet vient avant le verbe.",
    tags: ['cp', 'revision', 'syntaxe', 'ordre_mots', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cp-revision-122',
    subject: 'francais',
    title: "Son [r] — quel son fait R ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'correspondance lettre-son',
    format: 'qcm',
    instructions: "Quel son fait la lettre R ?",
    prompt: "Quel son fait la lettre R ?",
    options: [
      { id: 'a', text: '[r]', isCorrect: true },
      { id: 'b', text: '[l]', isCorrect: false },
      { id: 'c', text: '[d]', isCorrect: false },
    ],
    correctAnswer: '[r]',
    explanation: "R fait le son [r] comme dans rat.",
    hint: "Pense au mot rat.",
    tags: ['cp', 'revision', 'sons', 'correspondance_lettre_son', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cp-revision-123',
    subject: 'francais',
    title: "Mot oiseau — lequel est oiseau ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'lecture de mots simples',
    format: 'qcm',
    instructions: "Lis. C'est quel mot ?",
    prompt: "Laquelle est le mot oiseau ?",
    options: [
      { id: 'a', text: 'oiseau', isCorrect: true },
      { id: 'b', text: 'poisson', isCorrect: false },
      { id: 'c', text: 'insecte', isCorrect: false },
    ],
    correctAnswer: 'oiseau',
    explanation: "Un oiseau est un animal qui vole.",
    hint: "Lis chaque mot lentement.",
    tags: ['cp', 'revision', 'mots', 'lecture_mots', 'animaux', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

  {
    id: 'fr-cp-revision-124',
    subject: 'francais',
    title: "Tu joues ? — bien écrit ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'ponctuation de phrase simple',
    format: 'qcm',
    instructions: "La phrase est bien ecrite avec un point d'interrogation ?",
    prompt: "Tu joues ? C'est bien ecrit avec point d'interrogation. Vrai ou faux ?",
    options: [
      { id: 'a', text: 'Vrai', isCorrect: true },
      { id: 'b', text: 'Faux', isCorrect: false },
    ],
    correctAnswer: 'Vrai',
    explanation: "Une question se termine par un point d'interrogation.",
    hint: "Regarde le signe a la fin de la phrase.",
    tags: ['cp', 'revision', 'ponctuation', 'point_interrogation', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:grammaire',
  },

  {
    id: 'fr-cp-revision-125',
    subject: 'francais',
    title: "La fille saute — qui saute ?",
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'lecture',
    subskill: 'comprehension de phrases simples',
    format: 'qcm',
    instructions: "Lis. Qui fait quoi ?",
    prompt: "La fille saute. Qui saute ?",
    options: [
      { id: 'a', text: 'la fille', isCorrect: true },
      { id: 'b', text: 'le garcon', isCorrect: false },
      { id: 'c', text: 'le chat', isCorrect: false },
    ],
    correctAnswer: 'la fille',
    explanation: "La fille est celle qui saute dans la phrase.",
    hint: "Lis bien le debut de la phrase.",
    tags: ['cp', 'revision', 'comprehension', 'phrases_simples', 'standard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:lecture',
  },

];
