import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCpFacteurs2Exercises: MathExercise[] = [
  {
    id: 'ma-cp-calcul-025',
    subject: 'mathematiques',
    title: 'Le double de 2',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'doubles',
    format: 'qcm',
    instructions: 'Calcule le double.',
    prompt: 'Le double de 2, c\'est combien ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Le double de 2 = 2 + 2 = 4.',
    hint: 'Le double, c\'est ajouter le même nombre : 2 + 2.',
    tags: ['cp', 'calcul', 'double', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-026',
    subject: 'mathematiques',
    title: 'Le double de 3',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'doubles',
    format: 'qcm',
    instructions: 'Calcule le double.',
    prompt: 'Le double de 3, c\'est combien ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '9', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '3 + 3 = 6.',
    hint: 'Compte deux fois 3.',
    tags: ['cp', 'calcul', 'double', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-027',
    subject: 'mathematiques',
    title: 'Le double de 4',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'doubles',
    format: 'qcm',
    instructions: 'Calcule le double.',
    prompt: 'Le double de 4, c\'est combien ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: '4 + 4 = 8.',
    hint: '4 + 4 = ?',
    tags: ['cp', 'calcul', 'double', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-028',
    subject: 'mathematiques',
    title: 'Le double de 5',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'doubles',
    format: 'qcm',
    instructions: 'Calcule le double.',
    prompt: 'Le double de 5, c\'est combien ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '10', isCorrect: true },
      { id: 'c', text: '12', isCorrect: false },
    ],
    correctAnswer: '10',
    explanation: '5 + 5 = 10.',
    hint: '5 doigts d\'une main + 5 de l\'autre = ?',
    tags: ['cp', 'calcul', 'double', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-029',
    subject: 'mathematiques',
    title: 'La moitié de 4',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'moitiés',
    format: 'qcm',
    instructions: 'Calcule la moitié.',
    prompt: 'La moitié de 4, c\'est combien ?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '2', isCorrect: true },
      { id: 'c', text: '3', isCorrect: false },
    ],
    correctAnswer: '2',
    explanation: '4 partagé en 2 = 2. La moitié de 4 est 2.',
    hint: 'Partage 4 en 2 groupes égaux.',
    tags: ['cp', 'calcul', 'moitié', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-030',
    subject: 'mathematiques',
    title: 'La moitié de 6',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'moitiés',
    format: 'qcm',
    instructions: 'Calcule la moitié.',
    prompt: 'La moitié de 6, c\'est combien ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '6 partagé en 2 = 3. La moitié de 6 est 3.',
    hint: '6 billes partagées en 2 tas égaux : combien par tas ?',
    tags: ['cp', 'calcul', 'moitié', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-031',
    subject: 'mathematiques',
    title: 'La moitié de 10',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'moitiés',
    format: 'qcm',
    instructions: 'Calcule la moitié.',
    prompt: 'La moitié de 10, c\'est combien ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '10 partagé en 2 = 5.',
    hint: 'Partage 10 en 2 groupes égaux.',
    tags: ['cp', 'calcul', 'moitié', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-032',
    subject: 'mathematiques',
    title: 'Compter par 2',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'compter par 2',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '2, 4, 6, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '9', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: 'On compte de 2 en 2 : 2, 4, 6, 8.',
    hint: 'Ajoute 2 à chaque fois.',
    tags: ['cp', 'calcul', 'suite', 'deux', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-033',
    subject: 'mathematiques',
    title: 'Compter par 5',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'compter par 5',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '5, 10, 15, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '18', isCorrect: false },
      { id: 'b', text: '20', isCorrect: true },
      { id: 'c', text: '25', isCorrect: false },
    ],
    correctAnswer: '20',
    explanation: 'On compte de 5 en 5 : 5, 10, 15, 20.',
    hint: 'Ajoute 5 à 15.',
    tags: ['cp', 'calcul', 'suite', 'cinq', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-034',
    subject: 'mathematiques',
    title: 'Compter par 10',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'compter par 10',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '10, 20, 30, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '35', isCorrect: false },
      { id: 'b', text: '40', isCorrect: true },
      { id: 'c', text: '50', isCorrect: false },
    ],
    correctAnswer: '40',
    explanation: 'On compte de 10 en 10 : 10, 20, 30, 40.',
    hint: 'Ajoute 10 à 30.',
    tags: ['cp', 'calcul', 'suite', 'dix', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-035',
    subject: 'mathematiques',
    title: 'Double ou pas ?',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'doubles',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Louis a 3 billes. Sa sœur en a le double. Combien de billes a la sœur ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '5', isCorrect: false },
      { id: 'c', text: '6', isCorrect: true },
    ],
    correctAnswer: '6',
    explanation: 'Le double de 3 = 3 + 3 = 6.',
    hint: 'Le double, c\'est deux fois la même chose.',
    tags: ['cp', 'calcul', 'double', 'problème', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-036',
    subject: 'mathematiques',
    title: '2 fois un nombre',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication par 2',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '2 fois 4 = ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: '2 fois 4 = 4 + 4 = 8.',
    hint: 'Ajoute 4 + 4.',
    tags: ['cp', 'calcul', 'multiplication', 'deux', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-037',
    subject: 'mathematiques',
    title: '5 fois un nombre',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication par 5',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '5 fois 2 = ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '10', isCorrect: true },
      { id: 'c', text: '12', isCorrect: false },
    ],
    correctAnswer: '10',
    explanation: '5 × 2 = 5 + 5 = 10.',
    hint: 'Compte 2 fois 5.',
    tags: ['cp', 'calcul', 'multiplication', 'cinq', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cp-calcul-038',
    subject: 'mathematiques',
    title: 'Le double de 1',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'doubles',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'Le double de 1, c\'est combien ?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '2', isCorrect: true },
      { id: 'c', text: '3', isCorrect: false },
    ],
    correctAnswer: '2',
    explanation: '1 + 1 = 2.',
    hint: 'Ajoute 1 + 1.',
    tags: ['cp', 'calcul', 'double', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
];
