import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCpGrandeursExercises: MathExercise[] = [
  {
    id: 'ma-cp-mesures-001',
    subject: 'mathematiques',
    title: 'Comparer des tailles',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'comparaison de tailles',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Lequel est le plus grand : un éléphant ou un chat ?',
    options: [
      { id: 'a', text: 'Un éléphant', isCorrect: true },
      { id: 'b', text: 'Un chat', isCorrect: false },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: 'Un éléphant',
    explanation: "L'éléphant est beaucoup plus grand qu'un chat.",
    hint: 'Pense à la taille de chaque animal.',
    tags: ['cp', 'mesures', 'taille', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-002',
    subject: 'mathematiques',
    title: 'Comparer des poids',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'comparaison de poids',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: "Qu'est-ce qui est le plus lourd : une plume ou un livre ?",
    options: [
      { id: 'a', text: 'Une plume', isCorrect: false },
      { id: 'b', text: 'Un livre', isCorrect: true },
      { id: 'c', text: 'Ils pèsent pareil', isCorrect: false },
    ],
    correctAnswer: 'Un livre',
    explanation: "Un livre est beaucoup plus lourd qu'une plume.",
    hint: 'Imagine tenir les deux dans tes mains.',
    tags: ['cp', 'mesures', 'poids', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-003',
    subject: 'mathematiques',
    title: 'Le plus long',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'comparaison de longueurs',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: "Lequel est le plus long : un crayon de 10 cm ou une règle de 20 cm ?",
    options: [
      { id: 'a', text: 'Le crayon', isCorrect: false },
      { id: 'b', text: 'La règle', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: 'La règle',
    explanation: '20 cm est plus grand que 10 cm, donc la règle est plus longue.',
    hint: 'Regarde quel nombre est plus grand.',
    tags: ['cp', 'mesures', 'longueur', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-004',
    subject: 'mathematiques',
    title: 'La plus pleine',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'comparaison de contenances',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: "Une bouteille contient 1 litre. Un verre contient 20 cl. Laquelle peut contenir le plus d'eau ?",
    options: [
      { id: 'a', text: 'Le verre', isCorrect: false },
      { id: 'b', text: 'La bouteille', isCorrect: true },
      { id: 'c', text: 'Pareil', isCorrect: false },
    ],
    correctAnswer: 'La bouteille',
    explanation: '1 litre = 100 cl. 100 cl > 20 cl. La bouteille contient plus.',
    hint: 'Une bouteille est bien plus grande qu\'un verre.',
    tags: ['cp', 'mesures', 'contenance', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-005',
    subject: 'mathematiques',
    title: 'Matin ou après-midi',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'lecture de l\'heure',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'L\'école commence à 8h30. C\'est le matin ou l\'après-midi ?',
    options: [
      { id: 'a', text: 'L\'après-midi', isCorrect: false },
      { id: 'b', text: 'Le matin', isCorrect: true },
      { id: 'c', text: 'Le soir', isCorrect: false },
    ],
    correctAnswer: 'Le matin',
    explanation: '8h30 est le matin, car c\'est avant midi.',
    hint: 'Le matin c\'est avant 12h.',
    tags: ['cp', 'mesures', 'heure', 'matin', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-006',
    subject: 'mathematiques',
    title: 'Jours de la semaine',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quel jour vient après mercredi ?',
    options: [
      { id: 'a', text: 'Mardi', isCorrect: false },
      { id: 'b', text: 'Jeudi', isCorrect: true },
      { id: 'c', text: 'Vendredi', isCorrect: false },
    ],
    correctAnswer: 'Jeudi',
    explanation: 'La semaine : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche.',
    hint: 'Récite les jours dans l\'ordre.',
    tags: ['cp', 'mesures', 'calendrier', 'jours', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-007',
    subject: 'mathematiques',
    title: 'Combien de jours dans une semaine ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien y a-t-il de jours dans une semaine ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '30', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: 'Une semaine a 7 jours : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche.',
    hint: 'Compte les jours de lundi à dimanche.',
    tags: ['cp', 'mesures', 'calendrier', 'semaine', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-008',
    subject: 'mathematiques',
    title: 'Saisons',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quelle saison vient après l\'hiver ?',
    options: [
      { id: 'a', text: 'L\'automne', isCorrect: false },
      { id: 'b', text: 'Le printemps', isCorrect: true },
      { id: 'c', text: 'L\'été', isCorrect: false },
    ],
    correctAnswer: 'Le printemps',
    explanation: 'L\'ordre des saisons : hiver, printemps, été, automne.',
    hint: 'Récite les 4 saisons dans l\'ordre.',
    tags: ['cp', 'mesures', 'calendrier', 'saisons', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-009',
    subject: 'mathematiques',
    title: 'Heure entière',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'lecture de l\'heure',
    format: 'qcm',
    instructions: 'Lis l\'heure.',
    prompt: 'L\'aiguille des heures est sur le 3, l\'aiguille des minutes est sur le 12. Quelle heure est-il ?',
    options: [
      { id: 'a', text: '12h03', isCorrect: false },
      { id: 'b', text: '3h00', isCorrect: true },
      { id: 'c', text: '3h30', isCorrect: false },
    ],
    correctAnswer: '3h00',
    explanation: 'Quand la grande aiguille est sur le 12, c\'est une heure pile. L\'heure : 3h00.',
    hint: 'La grande aiguille sur le 12 = heure pile.',
    tags: ['cp', 'mesures', 'heure', 'horloge', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-010',
    subject: 'mathematiques',
    title: 'Demi-heure',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'lecture de l\'heure',
    format: 'qcm',
    instructions: 'Lis l\'heure.',
    prompt: 'Il est 2h30. Combien de minutes restent avant 3h00 ?',
    options: [
      { id: 'a', text: '20 minutes', isCorrect: false },
      { id: 'b', text: '30 minutes', isCorrect: true },
      { id: 'c', text: '60 minutes', isCorrect: false },
    ],
    correctAnswer: '30 minutes',
    explanation: 'De 2h30 à 3h00, il y a 30 minutes.',
    hint: 'De la demie à l\'heure pile, c\'est toujours 30 minutes.',
    tags: ['cp', 'mesures', 'heure', 'demi-heure', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-011',
    subject: 'mathematiques',
    title: 'Le plus court',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'comparaison de longueurs',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Lequel est le plus court : 5 cm ou 8 cm ?',
    options: [
      { id: 'a', text: '8 cm', isCorrect: false },
      { id: 'b', text: '5 cm', isCorrect: true },
      { id: 'c', text: 'Pareils', isCorrect: false },
    ],
    correctAnswer: '5 cm',
    explanation: '5 cm est plus petit que 8 cm, donc c\'est le plus court.',
    hint: '5 est plus petit que 8.',
    tags: ['cp', 'mesures', 'longueur', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-012',
    subject: 'mathematiques',
    title: 'Combien de mois dans une année ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien y a-t-il de mois dans une année ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '10', isCorrect: false },
      { id: 'c', text: '12', isCorrect: true },
    ],
    correctAnswer: '12',
    explanation: 'Une année a 12 mois, de janvier à décembre.',
    hint: 'L\'année commence en janvier et finit en décembre.',
    tags: ['cp', 'mesures', 'calendrier', 'mois', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-013',
    subject: 'mathematiques',
    title: 'Le mètre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'longueurs',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Pour mesurer la hauteur d\'une porte, quelle unité utilise-t-on ?',
    options: [
      { id: 'a', text: 'Le gramme', isCorrect: false },
      { id: 'b', text: 'Le mètre', isCorrect: true },
      { id: 'c', text: 'Le litre', isCorrect: false },
    ],
    correctAnswer: 'Le mètre',
    explanation: 'On mesure les longueurs en mètres.',
    hint: 'Pour mesurer une distance, on utilise une unité de longueur.',
    tags: ['cp', 'mesures', 'longueur', 'mètre', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-014',
    subject: 'mathematiques',
    title: 'Le kilogramme',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'masses',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Pour peser des fruits, quelle unité utilise-t-on ?',
    options: [
      { id: 'a', text: 'Le mètre', isCorrect: false },
      { id: 'b', text: 'Le kilogramme', isCorrect: true },
      { id: 'c', text: 'La minute', isCorrect: false },
    ],
    correctAnswer: 'Le kilogramme',
    explanation: 'On pèse les aliments en kilogrammes (ou en grammes).',
    hint: 'Pour peser, on utilise une unité de masse.',
    tags: ['cp', 'mesures', 'masse', 'kilogramme', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-015',
    subject: 'mathematiques',
    title: 'Le litre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'contenances',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Pour mesurer une bouteille d\'eau, quelle unité utilise-t-on ?',
    options: [
      { id: 'a', text: 'Le mètre', isCorrect: false },
      { id: 'b', text: 'Le litre', isCorrect: true },
      { id: 'c', text: 'L\'euro', isCorrect: false },
    ],
    correctAnswer: 'Le litre',
    explanation: 'On mesure les liquides en litres.',
    hint: 'Pour mesurer de l\'eau, on utilise une unité de contenance.',
    tags: ['cp', 'mesures', 'contenance', 'litre', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-016',
    subject: 'mathematiques',
    title: 'Plus lourd ou plus léger ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'comparaison de masses',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un éléphant est ___ qu\'une souris.',
    options: [
      { id: 'a', text: 'plus léger', isCorrect: false },
      { id: 'b', text: 'plus lourd', isCorrect: true },
      { id: 'c', text: 'pareil', isCorrect: false },
    ],
    correctAnswer: 'plus lourd',
    explanation: 'Un éléphant pèse beaucoup plus qu\'une souris.',
    hint: 'Lequel est le plus grand animal ?',
    tags: ['cp', 'mesures', 'masse', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-017',
    subject: 'mathematiques',
    title: 'Plus long ou plus court ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'comparaison de longueurs',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un crayon mesure 15 cm. Une règle mesure 30 cm. Qui est le plus long ?',
    options: [
      { id: 'a', text: 'Le crayon', isCorrect: false },
      { id: 'b', text: 'La règle', isCorrect: true },
      { id: 'c', text: 'Ils font la même taille', isCorrect: false },
    ],
    correctAnswer: 'La règle',
    explanation: '30 cm > 15 cm. La règle est plus longue.',
    hint: 'Compare 15 et 30.',
    tags: ['cp', 'mesures', 'longueur', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-cp-mesures-018',
    subject: 'mathematiques',
    title: 'Heures ou minutes ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un film dure environ 1 heure 30 minutes. C\'est environ combien de minutes ?',
    options: [
      { id: 'a', text: '60 minutes', isCorrect: false },
      { id: 'b', text: '90 minutes', isCorrect: true },
      { id: 'c', text: '120 minutes', isCorrect: false },
    ],
    correctAnswer: '90 minutes',
    explanation: '1 heure = 60 minutes. 60 + 30 = 90 minutes.',
    hint: '1 heure = 60 minutes. Ajoute encore 30.',
    tags: ['cp', 'mesures', 'durée', 'minutes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:mesures',
  },
];
