import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCpGeometrieExercises: MathExercise[] = [
  {
    id: 'ma-cp-geometrie-001',
    subject: 'mathematiques',
    title: 'Côtés du carré',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de côtés a un carré ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '5', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Un carré a 4 côtés égaux.',
    hint: 'Dessine un carré et compte ses côtés.',
    tags: ['cp', 'geometrie', 'formes', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-002',
    subject: 'mathematiques',
    title: 'Forme sans coin',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: "Quelle forme n'a pas de coin ?",
    options: [
      { id: 'a', text: 'Carré', isCorrect: false },
      { id: 'b', text: 'Triangle', isCorrect: false },
      { id: 'c', text: 'Cercle', isCorrect: true },
    ],
    correctAnswer: 'Cercle',
    explanation: "Le cercle est rond, il n'a pas de coin.",
    hint: 'Pense à une roue de vélo.',
    tags: ['cp', 'geometrie', 'formes', 'cercle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-003',
    subject: 'mathematiques',
    title: 'Côtés du triangle',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de côtés a un triangle ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: 'Un triangle a 3 côtés et 3 angles.',
    hint: 'Tri veut dire 3.',
    tags: ['cp', 'geometrie', 'formes', 'triangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-004',
    subject: 'mathematiques',
    title: 'Reconnaître le rectangle',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quelle forme a 4 côtés, mais 2 longs et 2 courts ?',
    options: [
      { id: 'a', text: 'Carré', isCorrect: false },
      { id: 'b', text: 'Rectangle', isCorrect: true },
      { id: 'c', text: 'Triangle', isCorrect: false },
    ],
    correctAnswer: 'Rectangle',
    explanation: 'Le rectangle a 4 côtés : 2 longs et 2 courts. Le carré, lui, a 4 côtés tous pareils.',
    hint: 'Pense à une porte ou à une feuille de cahier.',
    tags: ['cp', 'geometrie', 'formes', 'rectangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-005',
    subject: 'mathematiques',
    title: 'Coins du carré',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de coins a un carré ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '5', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Un carré a 4 coins et 4 côtés.',
    hint: 'Dessine un carré et compte ses pointes.',
    tags: ['cp', 'geometrie', 'formes', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-006',
    subject: 'mathematiques',
    title: 'Forme avec 3 coins',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quelle forme a exactement 3 coins ?',
    options: [
      { id: 'a', text: 'Le carré', isCorrect: false },
      { id: 'b', text: 'Le triangle', isCorrect: true },
      { id: 'c', text: 'Le cercle', isCorrect: false },
    ],
    correctAnswer: 'Le triangle',
    explanation: 'Le triangle a 3 coins et 3 côtés.',
    hint: 'Tri veut dire 3.',
    tags: ['cp', 'geometrie', 'formes', 'triangle', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-007',
    subject: 'mathematiques',
    title: 'Objet rond',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Quel objet est de forme ronde ?',
    prompt: 'Lequel de ces objets ressemble à un cercle ?',
    options: [
      { id: 'a', text: 'Une porte', isCorrect: false },
      { id: 'b', text: 'Une pièce de monnaie', isCorrect: true },
      { id: 'c', text: 'Un livre', isCorrect: false },
    ],
    correctAnswer: 'Une pièce de monnaie',
    explanation: 'Une pièce de monnaie est ronde, comme un cercle.',
    hint: 'Quel objet est complètement rond ?',
    tags: ['cp', 'geometrie', 'cercle', 'vie_quotidienne', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-008',
    subject: 'mathematiques',
    title: 'Objet carré',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Quel objet est de forme carrée ?',
    prompt: 'Lequel de ces objets ressemble à un carré ?',
    options: [
      { id: 'a', text: 'Une fenêtre carrée', isCorrect: true },
      { id: 'b', text: 'Une roue', isCorrect: false },
      { id: 'c', text: 'Une feuille de cahier', isCorrect: false },
    ],
    correctAnswer: 'Une fenêtre carrée',
    explanation: 'Une fenêtre carrée a 4 côtés tous égaux, comme un carré.',
    hint: 'Le carré a 4 côtés tous de la même longueur.',
    tags: ['cp', 'geometrie', 'carré', 'vie_quotidienne', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-009',
    subject: 'mathematiques',
    title: 'Dessus et dessous',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'position dans l\'espace',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Si le ballon est sur la table, où est-il par rapport à la table ?',
    options: [
      { id: 'a', text: 'Dessous', isCorrect: false },
      { id: 'b', text: 'Dessus', isCorrect: true },
      { id: 'c', text: 'À côté', isCorrect: false },
    ],
    correctAnswer: 'Dessus',
    explanation: 'Le ballon est posé dessus la table.',
    hint: '"Sur" veut dire dessus.',
    tags: ['cp', 'geometrie', 'position', 'espace', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-010',
    subject: 'mathematiques',
    title: 'Gauche ou droite',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'position dans l\'espace',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Luca regarde devant lui. Le parc est sur sa gauche. De quel côté est le parc ?',
    options: [
      { id: 'a', text: 'À droite', isCorrect: false },
      { id: 'b', text: 'À gauche', isCorrect: true },
      { id: 'c', text: 'Derrière', isCorrect: false },
    ],
    correctAnswer: 'À gauche',
    explanation: 'Le parc est à gauche de Luca.',
    hint: 'Le problème dit "sur sa gauche".',
    tags: ['cp', 'geometrie', 'position', 'gauche_droite', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-011',
    subject: 'mathematiques',
    title: 'Forme avec le plus de côtés',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'formes géométriques',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Laquelle de ces formes a le plus de côtés ?',
    options: [
      { id: 'a', text: 'Le triangle', isCorrect: false },
      { id: 'b', text: 'Le carré', isCorrect: false },
      { id: 'c', text: 'Le pentagone (5 côtés)', isCorrect: true },
    ],
    correctAnswer: 'Le pentagone (5 côtés)',
    explanation: 'Triangle = 3, carré = 4, pentagone = 5. Le pentagone en a le plus.',
    hint: 'Compte les côtés de chaque forme.',
    tags: ['cp', 'geometrie', 'formes', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-012',
    subject: 'mathematiques',
    title: 'Symétrie simple',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'symétrie',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'On plie une feuille en deux. Les deux moitiés sont pareilles. Comment s\'appelle cette propriété ?',
    options: [
      { id: 'a', text: 'La rotation', isCorrect: false },
      { id: 'b', text: 'La symétrie', isCorrect: true },
      { id: 'c', text: 'La translation', isCorrect: false },
    ],
    correctAnswer: 'La symétrie',
    explanation: 'Quand on peut plier une figure et que les deux moitiés se superposent, c\'est une symétrie.',
    hint: 'Pense à un papillon dont les deux ailes sont pareilles.',
    tags: ['cp', 'geometrie', 'symétrie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-013',
    subject: 'mathematiques',
    title: 'Dessus ou dessous ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'positions',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Le chat est ___ la table. La balle est ___ la table. Quelle affirmation est vraie si le chat est sur la table ?',
    options: [
      { id: 'a', text: 'Le chat est sous la table', isCorrect: false },
      { id: 'b', text: 'Le chat est sur la table', isCorrect: true },
      { id: 'c', text: 'Le chat est à côté de la table', isCorrect: false },
    ],
    correctAnswer: 'Le chat est sur la table',
    explanation: '"Sur" signifie au-dessus et en contact.',
    hint: 'Sur = au-dessus en contact.',
    tags: ['cp', 'geometrie', 'position', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-014',
    subject: 'mathematiques',
    title: 'Devant ou derrière ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'positions',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Paul est devant Marie dans la queue. Qui est en premier ?',
    options: [
      { id: 'a', text: 'Marie', isCorrect: false },
      { id: 'b', text: 'Paul', isCorrect: true },
      { id: 'c', text: 'Ils sont ensemble', isCorrect: false },
    ],
    correctAnswer: 'Paul',
    explanation: '"Devant" veut dire en premier dans la file.',
    hint: 'Devant = plus en avant.',
    tags: ['cp', 'geometrie', 'position', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-015',
    subject: 'mathematiques',
    title: 'Côtés du carré',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'figures planes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de côtés a un carré ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '5', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Un carré a 4 côtés égaux.',
    hint: 'Trace un carré avec ton doigt et compte les côtés.',
    tags: ['cp', 'geometrie', 'carré', 'côtés', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-016',
    subject: 'mathematiques',
    title: 'Angles du triangle',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'figures planes',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien d\'angles a un triangle ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: 'Un triangle a 3 angles (3 coins).',
    hint: 'Triangle = 3 coins.',
    tags: ['cp', 'geometrie', 'triangle', 'angles', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-017',
    subject: 'mathematiques',
    title: 'Quelle forme est ronde ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'reconnaissance de formes',
    format: 'qcm',
    instructions: 'Trouve la bonne réponse.',
    prompt: 'Quelle figure n\'a pas de coin ?',
    options: [
      { id: 'a', text: 'Le carré', isCorrect: false },
      { id: 'b', text: 'Le cercle', isCorrect: true },
      { id: 'c', text: 'Le triangle', isCorrect: false },
    ],
    correctAnswer: 'Le cercle',
    explanation: 'Le cercle est rond, il n\'a pas de coins ni de côtés droits.',
    hint: 'Quelle forme ressemble à une roue de vélo ?',
    tags: ['cp', 'geometrie', 'cercle', 'formes', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cp-geometrie-018',
    subject: 'mathematiques',
    title: 'Gauche ou droite ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'positions',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'L\'oiseau est à gauche du chat. Qui est à droite ?',
    options: [
      { id: 'a', text: 'L\'oiseau', isCorrect: false },
      { id: 'b', text: 'Le chat', isCorrect: true },
      { id: 'c', text: 'Ni l\'un ni l\'autre', isCorrect: false },
    ],
    correctAnswer: 'Le chat',
    explanation: 'Si l\'oiseau est à gauche du chat, alors le chat est à droite de l\'oiseau.',
    hint: 'Gauche et droite sont des positions opposées.',
    tags: ['cp', 'geometrie', 'position', 'gauche', 'droite', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
];
