import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCpNombres20Exercises: MathExercise[] = [
  {
    id: 'ma-cp-numeration-006',
    subject: 'mathematiques',
    title: 'Comparer deux nombres',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quel est le plus grand : 8 ou 15 ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: "15 est plus grand que 8 : sur la droite des nombres, 15 est plus loin.",
    hint: "Compte jusqu'à 8, puis jusqu'à 15.",
    tags: ['cp', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-008',
    subject: 'mathematiques',
    title: 'Nombre après 10',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Quel nombre vient après ?',
    prompt: 'Quel nombre vient juste après 10 ?',
    options: [
      { id: 'a', text: '9', isCorrect: false },
      { id: 'b', text: '11', isCorrect: true },
      { id: 'c', text: '12', isCorrect: false },
    ],
    correctAnswer: '11',
    explanation: 'Après 10 vient 11 : 9, 10, 11.',
    hint: 'Compte à partir de 10.',
    tags: ['cp', 'numeration', 'suite', 'dizaine', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-009',
    subject: 'mathematiques',
    title: 'Chiffre en lettres',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture des nombres',
    format: 'qcm',
    instructions: 'Quel est le bon chiffre ?',
    prompt: 'Écris en chiffres : treize',
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '13', isCorrect: true },
      { id: 'c', text: '14', isCorrect: false },
    ],
    correctAnswer: '13',
    explanation: 'Treize s\'écrit 13.',
    hint: 'Compte jusqu\'à treize sur tes doigts.',
    tags: ['cp', 'numeration', 'lecture_nombres', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-010',
    subject: 'mathematiques',
    title: 'Chiffre en lettres',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture des nombres',
    format: 'qcm',
    instructions: 'Quel est le bon chiffre ?',
    prompt: 'Écris en chiffres : dix-huit',
    options: [
      { id: 'a', text: '17', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '19', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: 'Dix-huit s\'écrit 18.',
    hint: 'Dix-huit, c\'est 10 + 8.',
    tags: ['cp', 'numeration', 'lecture_nombres', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-011',
    subject: 'mathematiques',
    title: 'Comparer deux nombres',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Quel est le plus grand ?',
    prompt: 'Quel est le plus grand : 11 ou 19 ?',
    options: [
      { id: 'a', text: '11', isCorrect: false },
      { id: 'b', text: '19', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '19',
    explanation: '19 est plus grand que 11.',
    hint: 'Sur la droite des nombres, 19 est plus loin que 11.',
    tags: ['cp', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-012',
    subject: 'mathematiques',
    title: 'Suite numérique',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Complète la suite.',
    prompt: '11, 12, 13, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '13', isCorrect: false },
      { id: 'b', text: '14', isCorrect: true },
      { id: 'c', text: '15', isCorrect: false },
    ],
    correctAnswer: '14',
    explanation: 'On ajoute 1 à chaque fois : après 13 vient 14.',
    hint: 'Compte de 1 en 1 : 11, 12, 13, …',
    tags: ['cp', 'numeration', 'suite', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-013',
    subject: 'mathematiques',
    title: 'Nombre entre deux',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Trouve le nombre manquant.',
    prompt: 'Quel nombre est entre 16 et 18 ?',
    options: [
      { id: 'a', text: '15', isCorrect: false },
      { id: 'b', text: '17', isCorrect: true },
      { id: 'c', text: '19', isCorrect: false },
    ],
    correctAnswer: '17',
    explanation: '16, 17, 18. Le nombre entre 16 et 18 est 17.',
    hint: 'Compte après 16 : 17.',
    tags: ['cp', 'numeration', 'encadrement', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-014',
    subject: 'mathematiques',
    title: 'Vingt en chiffres',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture des nombres',
    format: 'qcm',
    instructions: 'Quel est le bon chiffre ?',
    prompt: 'Écris en chiffres : vingt',
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '20', isCorrect: true },
      { id: 'c', text: '22', isCorrect: false },
    ],
    correctAnswer: '20',
    explanation: 'Vingt s\'écrit 20.',
    hint: 'Vingt, c\'est 2 dizaines.',
    tags: ['cp', 'numeration', 'lecture_nombres', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-015',
    subject: 'mathematiques',
    title: 'Le plus petit',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Quel est le plus petit ?',
    prompt: 'Quel est le plus petit : 13 ou 15 ?',
    options: [
      { id: 'a', text: '13', isCorrect: true },
      { id: 'b', text: '15', isCorrect: false },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '13',
    explanation: '13 est plus petit que 15.',
    hint: '13 vient avant 15 sur la droite des nombres.',
    tags: ['cp', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-016',
    subject: 'mathematiques',
    title: 'Suite numérique',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Complète la suite.',
    prompt: '15, 16, 17, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '17', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '19', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: 'On ajoute 1 : après 17 vient 18.',
    hint: 'Compte de 1 en 1.',
    tags: ['cp', 'numeration', 'suite', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-017',
    subject: 'mathematiques',
    title: 'Compter des étoiles',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'dénombrement',
    format: 'qcm',
    instructions: 'Compte les étoiles.',
    prompt: 'Combien y a-t-il d\'étoiles ? ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '12', isCorrect: true },
      { id: 'c', text: '14', isCorrect: false },
    ],
    correctAnswer: '12',
    explanation: 'Il y a 12 étoiles.',
    hint: 'Compte-les une par une.',
    tags: ['cp', 'numeration', 'denombrement', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-018',
    subject: 'mathematiques',
    title: 'Le plus grand parmi trois',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Quel est le plus grand ?',
    prompt: 'Quel est le plus grand : 16, 12 ou 19 ?',
    options: [
      { id: 'a', text: '16', isCorrect: false },
      { id: 'b', text: '12', isCorrect: false },
      { id: 'c', text: '19', isCorrect: true },
    ],
    correctAnswer: '19',
    explanation: '19 est le plus grand des trois.',
    hint: 'Sur la droite des nombres, lequel est le plus à droite ?',
    tags: ['cp', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-040',
    subject: 'mathematiques',
    title: 'Avant 13',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'voisins',
    format: 'qcm',
    instructions: 'Trouve le nombre juste avant.',
    prompt: 'Quel nombre vient juste avant 13 ?',
    options: [
      { id: 'a', text: '11', isCorrect: false },
      { id: 'b', text: '12', isCorrect: true },
      { id: 'c', text: '14', isCorrect: false },
    ],
    correctAnswer: '12',
    explanation: '12 vient juste avant 13.',
    hint: '13 − 1 = ?',
    tags: ['cp', 'numeration', 'voisins', '11-20', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-041',
    subject: 'mathematiques',
    title: 'Après 17',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'voisins',
    format: 'qcm',
    instructions: 'Trouve le nombre juste après.',
    prompt: 'Quel nombre vient juste après 17 ?',
    options: [
      { id: 'a', text: '16', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '19', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: '18 vient juste après 17.',
    hint: '17 + 1 = ?',
    tags: ['cp', 'numeration', 'voisins', '11-20', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-042',
    subject: 'mathematiques',
    title: 'Dizaines de 15',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'dizaines et unités',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans 15, combien y a-t-il de dizaines ?',
    options: [
      { id: 'a', text: '0 dizaine', isCorrect: false },
      { id: 'b', text: '1 dizaine', isCorrect: true },
      { id: 'c', text: '5 dizaines', isCorrect: false },
    ],
    correctAnswer: '1 dizaine',
    explanation: '15 = 1 dizaine et 5 unités.',
    hint: 'Le premier chiffre (à gauche) indique les dizaines.',
    tags: ['cp', 'numeration', 'dizaines', '11-20', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-043',
    subject: 'mathematiques',
    title: 'Encadrement de 16',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '16 est entre quelles dizaines ?',
    options: [
      { id: 'a', text: 'Entre 0 et 10', isCorrect: false },
      { id: 'b', text: 'Entre 10 et 20', isCorrect: true },
      { id: 'c', text: 'Entre 20 et 30', isCorrect: false },
    ],
    correctAnswer: 'Entre 10 et 20',
    explanation: '10 < 16 < 20.',
    hint: '16 commence par 1, donc il est dans les dizaines de 1.',
    tags: ['cp', 'numeration', 'encadrement', '11-20', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-044',
    subject: 'mathematiques',
    title: 'Suite de 11 à 15',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '11, 12, 13, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '13', isCorrect: false },
      { id: 'b', text: '14', isCorrect: true },
      { id: 'c', text: '15', isCorrect: false },
    ],
    correctAnswer: '14',
    explanation: 'On compte : 11, 12, 13, 14.',
    hint: 'Ajoute 1 à 13.',
    tags: ['cp', 'numeration', 'suite', '11-20', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-045',
    subject: 'mathematiques',
    title: 'Décomposer 18',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'dizaines et unités',
    format: 'qcm',
    instructions: 'Décompose le nombre.',
    prompt: '18 = ___ dizaines + ___ unités',
    options: [
      { id: 'a', text: '8 dizaines + 1 unité', isCorrect: false },
      { id: 'b', text: '1 dizaine + 8 unités', isCorrect: true },
      { id: 'c', text: '2 dizaines + 8 unités', isCorrect: false },
    ],
    correctAnswer: '1 dizaine + 8 unités',
    explanation: '18 = 10 + 8 = 1 dizaine et 8 unités.',
    hint: '18 commence par 1 (une dizaine) et se finit par 8 (les unités).',
    tags: ['cp', 'numeration', 'décomposition', '11-20', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
];
