import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCpNombres30Exercises: MathExercise[] = [
  {
    id: 'ma-cp-numeration-019',
    subject: 'mathematiques',
    title: 'Lire 21',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture de nombres',
    format: 'qcm',
    instructions: 'Quel nombre vois-tu ?',
    prompt: 'Vingt et un s\'écrit comment en chiffres ?',
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '21', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '21',
    explanation: 'Vingt et un = 20 + 1 = 21.',
    hint: '20 + 1 = ?',
    tags: ['cp', 'numeration', 'lecture', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-020',
    subject: 'mathematiques',
    title: 'Lire 25',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture de nombres',
    format: 'qcm',
    instructions: 'Lis le nombre.',
    prompt: 'Comment lit-on le nombre 25 ?',
    options: [
      { id: 'a', text: 'Vingt', isCorrect: false },
      { id: 'b', text: 'Vingt-cinq', isCorrect: true },
      { id: 'c', text: 'Cinquante-deux', isCorrect: false },
    ],
    correctAnswer: 'Vingt-cinq',
    explanation: '25 = 20 + 5 = vingt-cinq.',
    hint: '2 dizaines et 5 unités.',
    tags: ['cp', 'numeration', 'lecture', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-021',
    subject: 'mathematiques',
    title: 'Lire 30',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture de nombres',
    format: 'qcm',
    instructions: 'Lis le nombre.',
    prompt: 'Comment lit-on le nombre 30 ?',
    options: [
      { id: 'a', text: 'Vingt', isCorrect: false },
      { id: 'b', text: 'Vingt-dix', isCorrect: false },
      { id: 'c', text: 'Trente', isCorrect: true },
    ],
    correctAnswer: 'Trente',
    explanation: '30 = 3 dizaines = trente.',
    hint: '3 dizaines = ?',
    tags: ['cp', 'numeration', 'lecture', '30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-022',
    subject: 'mathematiques',
    title: 'Suite après 20',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '20, 21, 22, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '20', isCorrect: false },
      { id: 'b', text: '23', isCorrect: true },
      { id: 'c', text: '24', isCorrect: false },
    ],
    correctAnswer: '23',
    explanation: 'On compte : 20, 21, 22, 23.',
    hint: 'Ajoute 1 à 22.',
    tags: ['cp', 'numeration', 'suite', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-023',
    subject: 'mathematiques',
    title: 'Avant 27',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'voisins',
    format: 'qcm',
    instructions: 'Trouve le nombre qui vient juste avant.',
    prompt: 'Quel nombre vient juste avant 27 ?',
    options: [
      { id: 'a', text: '25', isCorrect: false },
      { id: 'b', text: '26', isCorrect: true },
      { id: 'c', text: '28', isCorrect: false },
    ],
    correctAnswer: '26',
    explanation: '26 vient juste avant 27.',
    hint: '27 − 1 = ?',
    tags: ['cp', 'numeration', 'voisins', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-024',
    subject: 'mathematiques',
    title: 'Après 28',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'voisins',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: 'Quel nombre vient juste après 28 ?',
    options: [
      { id: 'a', text: '27', isCorrect: false },
      { id: 'b', text: '29', isCorrect: true },
      { id: 'c', text: '30', isCorrect: false },
    ],
    correctAnswer: '29',
    explanation: '29 vient juste après 28.',
    hint: '28 + 1 = ?',
    tags: ['cp', 'numeration', 'voisins', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-025',
    subject: 'mathematiques',
    title: 'Comparer 23 et 27',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Compare ces deux nombres.',
    prompt: 'Quel est le plus grand : 23 ou 27 ?',
    options: [
      { id: 'a', text: '23', isCorrect: false },
      { id: 'b', text: '27', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '27',
    explanation: '27 > 23. 27 est plus grand que 23.',
    hint: 'Les deux nombres commencent par 2. Regarde les unités : 3 ou 7 ?',
    tags: ['cp', 'numeration', 'comparaison', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-026',
    subject: 'mathematiques',
    title: 'Dizaines et unités de 24',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'dizaines et unités',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans 24, combien y a-t-il de dizaines ?',
    options: [
      { id: 'a', text: '1 dizaine', isCorrect: false },
      { id: 'b', text: '2 dizaines', isCorrect: true },
      { id: 'c', text: '4 dizaines', isCorrect: false },
    ],
    correctAnswer: '2 dizaines',
    explanation: '24 = 2 dizaines et 4 unités.',
    hint: 'Le premier chiffre à gauche indique les dizaines.',
    tags: ['cp', 'numeration', 'dizaines', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-027',
    subject: 'mathematiques',
    title: 'Dénombrer jusqu\'à 30',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'dénombrement',
    format: 'qcm',
    instructions: 'Compte les objets.',
    prompt: 'Il y a 2 dizaines et 6 unités. Quel nombre est-ce ?',
    options: [
      { id: 'a', text: '62', isCorrect: false },
      { id: 'b', text: '26', isCorrect: true },
      { id: 'c', text: '28', isCorrect: false },
    ],
    correctAnswer: '26',
    explanation: '2 dizaines = 20 et 6 unités = 6. 20 + 6 = 26.',
    hint: '2 dizaines = 20. Ajoute les 6 unités.',
    tags: ['cp', 'numeration', 'dénombrement', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-028',
    subject: 'mathematiques',
    title: 'Suite décroissante depuis 30',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'suite décroissante',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '30, 29, 28, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '26', isCorrect: false },
      { id: 'b', text: '27', isCorrect: true },
      { id: 'c', text: '28', isCorrect: false },
    ],
    correctAnswer: '27',
    explanation: 'On compte à rebours : 30, 29, 28, 27.',
    hint: 'On enlève 1 à chaque fois.',
    tags: ['cp', 'numeration', 'suite', 'décroissante', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-029',
    subject: 'mathematiques',
    title: 'Encadrer 25',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '25 est entre quels dizaines ?',
    options: [
      { id: 'a', text: 'Entre 10 et 20', isCorrect: false },
      { id: 'b', text: 'Entre 20 et 30', isCorrect: true },
      { id: 'c', text: 'Entre 30 et 40', isCorrect: false },
    ],
    correctAnswer: 'Entre 20 et 30',
    explanation: '20 < 25 < 30.',
    hint: 'Regarde le premier chiffre de 25 : c\'est 2, donc c\'est après 20.',
    tags: ['cp', 'numeration', 'encadrement', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-030',
    subject: 'mathematiques',
    title: 'Ranger dans l\'ordre',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'ordre croissant',
    format: 'qcm',
    instructions: 'Range du plus petit au plus grand.',
    prompt: '28, 22, 25. Quel est l\'ordre croissant ?',
    options: [
      { id: 'a', text: '28, 25, 22', isCorrect: false },
      { id: 'b', text: '22, 25, 28', isCorrect: true },
      { id: 'c', text: '25, 22, 28', isCorrect: false },
    ],
    correctAnswer: '22, 25, 28',
    explanation: '22 < 25 < 28.',
    hint: 'Les trois nombres commencent par 2. Regarde les unités : 2, 5, 8.',
    tags: ['cp', 'numeration', 'ordre', '21-30', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-031',
    subject: 'mathematiques',
    title: 'Le nombre 30',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'dizaines',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '30 = ___ dizaines + ___ unités',
    options: [
      { id: 'a', text: '2 dizaines + 10 unités', isCorrect: false },
      { id: 'b', text: '3 dizaines + 0 unités', isCorrect: true },
      { id: 'c', text: '1 dizaine + 20 unités', isCorrect: false },
    ],
    correctAnswer: '3 dizaines + 0 unités',
    explanation: '30 = 3 dizaines et 0 unités.',
    hint: '30 c\'est trois fois 10.',
    tags: ['cp', 'numeration', 'dizaines', '30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-032',
    subject: 'mathematiques',
    title: 'Quel nombre est le plus petit ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Trouve le plus petit nombre.',
    prompt: 'Parmi 30, 21 et 29, quel est le plus petit ?',
    options: [
      { id: 'a', text: '30', isCorrect: false },
      { id: 'b', text: '21', isCorrect: true },
      { id: 'c', text: '29', isCorrect: false },
    ],
    correctAnswer: '21',
    explanation: '21 < 29 < 30. Le plus petit est 21.',
    hint: 'Regarde les dizaines : 21 = 2 dizaines, 29 = 2 dizaines, 30 = 3 dizaines.',
    tags: ['cp', 'numeration', 'comparaison', '21-30', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
];
