import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCpNombres10Exercises: MathExercise[] = [
  {
    id: 'ma-cp-numeration-001',
    subject: 'mathematiques',
    title: 'Nombre suivant',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quel chiffre vient après 4 ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: 'Après 4 vient 5 : 1, 2, 3, 4, 5.',
    hint: 'Compte sur tes doigts.',
    tags: ['cp', 'numeration', 'suite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-002',
    subject: 'mathematiques',
    title: 'Comparer deux nombres',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Quel est le plus grand nombre ?',
    prompt: 'Quel est le plus grand : 3 ou 7 ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: '7 est plus grand que 3.',
    hint: 'Sur la droite des nombres, 7 est plus à droite que 3.',
    tags: ['cp', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-003',
    subject: 'mathematiques',
    title: 'Compter des points',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'dénombrement',
    format: 'qcm',
    instructions: 'Compte les points.',
    prompt: 'Combien y a-t-il de points ? ● ● ● ●',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '5', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Il y a 4 points : ● ● ● ●.',
    hint: 'Pointe chaque point avec ton doigt en comptant.',
    tags: ['cp', 'numeration', 'dénombrement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-004',
    subject: 'mathematiques',
    title: 'Chiffre en lettres',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture des nombres',
    format: 'qcm',
    instructions: 'Quel est le bon chiffre ?',
    prompt: 'Écris en chiffres : huit',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '7', isCorrect: false },
      { id: 'c', text: '8', isCorrect: true },
    ],
    correctAnswer: '8',
    explanation: "Huit s'écrit 8.",
    hint: "Compte sur tes doigts jusqu'à huit.",
    tags: ['cp', 'numeration', 'lecture_nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-005',
    subject: 'mathematiques',
    title: 'Nombre encadré',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Trouve le nombre manquant.',
    prompt: 'Quel nombre est entre 5 et 7 ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '6 est entre 5 et 7 : 5, 6, 7.',
    hint: 'Compte après 5 : 5, puis…',
    tags: ['cp', 'numeration', 'encadrement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-007',
    subject: 'mathematiques',
    title: 'Le plus petit nombre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quel est le plus petit nombre : 2, 8 ou 5 ?',
    options: [
      { id: 'a', text: '2', isCorrect: true },
      { id: 'b', text: '5', isCorrect: false },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '2',
    explanation: '2 est plus petit que 5 et 8.',
    hint: 'Sur la droite des nombres, le plus petit est le plus à gauche.',
    tags: ['cp', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-logique-001',
    subject: 'mathematiques',
    title: 'Suite numérique simple',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '1, 2, 3, 4, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: "On ajoute 1 à chaque fois : après 4 vient 5.",
    hint: 'Regarde le schéma : on compte de 1 en 1.',
    tags: ['cp', 'logique', 'suite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cp-logique-002',
    subject: 'mathematiques',
    title: 'Suite des nombres pairs',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Complète la suite.',
    prompt: 'Suite : 2, 4, 6, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '9', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: "On ajoute 2 à chaque fois : après 6 vient 8.",
    hint: 'On compte de 2 en 2 : 2, 4, 6…',
    tags: ['cp', 'logique', 'suite', 'pairs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cp-logique-003',
    subject: 'mathematiques',
    title: 'Suite décroissante',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '6, 5, 4, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: "On enlève 1 à chaque fois : après 4 vient 3.",
    hint: "On compte à rebours : on enlève 1.",
    tags: ['cp', 'logique', 'suite', 'decroissante', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Continue à rebours : que vient après 3 ? Et après 2 ?' },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cp-logique-005',
    subject: 'mathematiques',
    title: 'Nombre manquant au milieu',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre manquant.',
    prompt: '1, 2, ___, 4. Quel est le nombre manquant ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '5', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: 'On compte de 1 en 1 : 1, 2, 3, 4.',
    hint: 'Compte normalement : 1, 2, …, 4.',
    tags: ['cp', 'logique', 'suite', 'manquant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cp-logique-006',
    subject: 'mathematiques',
    title: 'Nombre manquant dans une suite',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre manquant.',
    prompt: '7, 8, ___, 10. Quel est le nombre manquant ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '9', isCorrect: true },
      { id: 'c', text: '11', isCorrect: false },
    ],
    correctAnswer: '9',
    explanation: 'On compte de 1 en 1 : 7, 8, 9, 10.',
    hint: 'Compte après 8.',
    tags: ['cp', 'logique', 'suite', 'manquant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cp-numeration-033',
    subject: 'mathematiques',
    title: 'Écrire 5 en chiffre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture de nombres',
    format: 'qcm',
    instructions: 'Quel chiffre représente "cinq" ?',
    prompt: 'Cinq, c\'est quel chiffre ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '"Cinq" s\'écrit 5.',
    hint: 'Compte 5 doigts.',
    tags: ['cp', 'numeration', 'lecture', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-034',
    subject: 'mathematiques',
    title: 'Le nombre juste avant 7',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'voisins',
    format: 'qcm',
    instructions: 'Trouve le nombre juste avant.',
    prompt: 'Quel nombre vient juste avant 7 ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '6 vient juste avant 7.',
    hint: '7 − 1 = ?',
    tags: ['cp', 'numeration', 'voisins', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-035',
    subject: 'mathematiques',
    title: 'Le nombre juste après 4',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'voisins',
    format: 'qcm',
    instructions: 'Trouve le nombre juste après.',
    prompt: 'Quel nombre vient juste après 4 ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '5 vient juste après 4.',
    hint: '4 + 1 = ?',
    tags: ['cp', 'numeration', 'voisins', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-036',
    subject: 'mathematiques',
    title: 'Comparer 3 et 8',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Quel est le plus grand ?',
    prompt: 'Quel est le plus grand : 3 ou 8 ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: 'Ils sont pareils', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: '8 > 3. 8 est plus grand.',
    hint: 'Sur la droite numérique, lequel est plus loin ?',
    tags: ['cp', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-037',
    subject: 'mathematiques',
    title: 'Ranger 2, 5, 1',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'ordre croissant',
    format: 'qcm',
    instructions: 'Range du plus petit au plus grand.',
    prompt: 'Mets dans l\'ordre croissant : 2, 5, 1',
    options: [
      { id: 'a', text: '5, 2, 1', isCorrect: false },
      { id: 'b', text: '1, 2, 5', isCorrect: true },
      { id: 'c', text: '2, 1, 5', isCorrect: false },
    ],
    correctAnswer: '1, 2, 5',
    explanation: '1 < 2 < 5.',
    hint: 'Quel est le plus petit ? Puis le suivant ?',
    tags: ['cp', 'numeration', 'ordre', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-038',
    subject: 'mathematiques',
    title: 'Dénombrer jusqu\'à 10',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'dénombrement',
    format: 'qcm',
    instructions: 'Compte les points.',
    prompt: '●●●●●●● — Combien y a-t-il de points ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: 'Il y a 7 points.',
    hint: 'Compte chaque point un par un.',
    tags: ['cp', 'numeration', 'dénombrement', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cp-numeration-039',
    subject: 'mathematiques',
    title: 'Le nombre zéro',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'lecture de nombres',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Zéro, c\'est quel chiffre ?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '0', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '0',
    explanation: 'Zéro s\'écrit 0. C\'est le nombre qui représente "rien".',
    hint: 'Il vient avant 1 dans la suite des nombres.',
    tags: ['cp', 'numeration', 'zéro', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
];
