import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCpProblemesExercises: MathExercise[] = [
  {
    id: 'ma-cp-problemes-001',
    subject: 'mathematiques',
    title: 'Problème soustraction simple',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Léa a 3 pommes. Elle en mange 1. Combien lui en reste-t-il ?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '2', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '2',
    explanation: '3 − 1 = 2.',
    hint: 'Elle enlève 1 pomme des 3.',
    tags: ['cp', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-002',
    subject: 'mathematiques',
    title: 'Problème addition simple',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'addition en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: "Il y a 2 chats et 3 chiens dans le jardin. Combien y a-t-il d'animaux ?",
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '2 + 3 = 5 animaux.',
    hint: 'Ajoute les chats et les chiens.',
    tags: ['cp', 'problemes', 'addition', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-003',
    subject: 'mathematiques',
    title: 'Problème avec don',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'addition en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Tom a 4 bonbons. Sa sœur lui en donne 2. Combien en a-t-il maintenant ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '4 + 2 = 6 bonbons.',
    hint: 'Il commence avec 4 et reçoit 2 de plus.',
    tags: ['cp', 'problemes', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-004',
    subject: 'mathematiques',
    title: 'Problème soustraction',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Max a 5 voitures. Il en perd 2. Combien lui en reste-t-il ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '5 − 2 = 3 voitures.',
    hint: 'Il enlève 2 de ses 5 voitures.',
    tags: ['cp', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-005',
    subject: 'mathematiques',
    title: 'Problème addition',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'addition en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Il y a 4 filles et 5 garçons. Combien d\'enfants y a-t-il en tout ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '9', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '9',
    explanation: '4 + 5 = 9 enfants.',
    hint: 'Ajoute les filles et les garçons.',
    tags: ['cp', 'problemes', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-006',
    subject: 'mathematiques',
    title: 'Problème soustraction',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Une boîte contient 8 crayons. On en prend 3. Combien en reste-t-il ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '8 − 3 = 5 crayons.',
    hint: 'Il enlève 3 de la boîte.',
    tags: ['cp', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-007',
    subject: 'mathematiques',
    title: 'Problème addition',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'addition en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Nora a 6 billes. Son frère en a autant. Combien en ont-ils ensemble ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '12', isCorrect: true },
      { id: 'c', text: '14', isCorrect: false },
    ],
    correctAnswer: '12',
    explanation: '6 + 6 = 12 billes.',
    hint: '"Autant" veut dire le même nombre.',
    tags: ['cp', 'problemes', 'addition', 'double', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-008',
    subject: 'mathematiques',
    title: 'Problème soustraction',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Il y a 10 biscuits. On en mange 4. Combien en reste-t-il ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '10 − 4 = 6 biscuits.',
    hint: 'Soustrais 4 des 10 biscuits.',
    tags: ['cp', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-009',
    subject: 'mathematiques',
    title: 'Problème multiplication simple',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'addition en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: '3 enfants ont chacun 2 ballons. Combien y a-t-il de ballons en tout ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '2 + 2 + 2 = 6 ballons.',
    hint: 'Additionne 2 trois fois : 2 + 2 + 2.',
    tags: ['cp', 'problemes', 'addition', 'repetee', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-010',
    subject: 'mathematiques',
    title: 'Problème soustraction',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Eva a 9 pièces. Elle en donne 3 à son amie. Combien lui en reste-t-il ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '9 − 3 = 6 pièces.',
    hint: 'Elle enlève 3 de ses 9 pièces.',
    tags: ['cp', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-011',
    subject: 'mathematiques',
    title: 'Problème multiplication simple',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'addition en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Il y a 5 boîtes. Chaque boîte contient 2 crayons. Combien de crayons y a-t-il en tout ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '10', isCorrect: true },
      { id: 'c', text: '12', isCorrect: false },
    ],
    correctAnswer: '10',
    explanation: '2 + 2 + 2 + 2 + 2 = 10 crayons.',
    hint: 'Ajoute 2 cinq fois.',
    tags: ['cp', 'problemes', 'addition', 'repetee', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-012',
    subject: 'mathematiques',
    title: 'Problème addition',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'addition en contexte',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Paul a 7 billes. Il en reçoit 3. Combien en a-t-il maintenant ?',
    options: [
      { id: 'a', text: '9', isCorrect: false },
      { id: 'b', text: '10', isCorrect: true },
      { id: 'c', text: '11', isCorrect: false },
    ],
    correctAnswer: '10',
    explanation: '7 + 3 = 10 billes.',
    hint: 'Il avait 7 et en reçoit 3.',
    tags: ['cp', 'problemes', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-013',
    subject: 'mathematiques',
    title: 'Partage en deux',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'partage',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: '8 biscuits à partager entre 2 enfants. Combien chacun en reçoit ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '5', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: '8 ÷ 2 = 4. Chaque enfant reçoit 4 biscuits.',
    hint: 'Partage les 8 biscuits en 2 tas égaux.',
    tags: ['cp', 'problemes', 'partage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-014',
    subject: 'mathematiques',
    title: 'Prix de 3 bonbons',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Calcule le prix.',
    prompt: 'Un bonbon coûte 2 centimes. Combien coûtent 3 bonbons ?',
    options: [
      { id: 'a', text: '5 centimes', isCorrect: false },
      { id: 'b', text: '6 centimes', isCorrect: true },
      { id: 'c', text: '7 centimes', isCorrect: false },
    ],
    correctAnswer: '6 centimes',
    explanation: '3 × 2 = 2 + 2 + 2 = 6 centimes.',
    hint: 'Ajoute 2 centimes trois fois.',
    tags: ['cp', 'problemes', 'monnaie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-015',
    subject: 'mathematiques',
    title: 'Ce qui reste dans le sac',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'Un sac contient 10 billes. On en retire 4. Combien en reste-t-il ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '10 − 4 = 6 billes.',
    hint: 'Enlève 4 de 10.',
    tags: ['cp', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-016',
    subject: 'mathematiques',
    title: 'Qui a le plus de crayons ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Anna a 5 crayons. Bart en a 3. Combien Anna en a-t-elle de plus que Bart ?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '2', isCorrect: true },
      { id: 'c', text: '3', isCorrect: false },
    ],
    correctAnswer: '2',
    explanation: '5 − 3 = 2. Anna a 2 crayons de plus.',
    hint: 'Calcule 5 − 3.',
    tags: ['cp', 'problemes', 'comparaison', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-017',
    subject: 'mathematiques',
    title: 'Places libres dans la voiture',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'soustraction',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'Une voiture a 5 places. 2 sont occupées. Combien de places restent libres ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '5 − 2 = 3 places libres.',
    hint: '5 places au total − 2 occupées = ?',
    tags: ['cp', 'problemes', 'soustraction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-018',
    subject: 'mathematiques',
    title: 'Filles et garçons',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'addition',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'Il y a 4 filles et 5 garçons dans la classe. Combien d\'élèves en tout ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '9', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '9',
    explanation: '4 + 5 = 9 élèves.',
    hint: 'Additionne les filles et les garçons.',
    tags: ['cp', 'problemes', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-019',
    subject: 'mathematiques',
    title: 'Partage de gâteaux',
    schoolClass: 'CP',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'partage',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: '6 gâteaux partagés entre 2 enfants. Combien chacun en reçoit ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '6 ÷ 2 = 3.',
    hint: 'Partage 6 en 2 parts égales.',
    tags: ['cp', 'problemes', 'partage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cp-problemes-020',
    subject: 'mathematiques',
    title: 'Acheter puis prêter',
    schoolClass: 'CP',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'multi-étapes',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'J\'ai 5 livres. J\'en achète 3 et prête 2. Combien en ai-je maintenant ?',
    options: [
      { id: 'a', text: '5', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: '5 + 3 = 8 puis 8 − 2 = 6.',
    hint: 'D\'abord ajoute, ensuite soustrait.',
    tags: ['cp', 'problemes', 'multi-etapes', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
];
