import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCm1ConjugaisonExercises: FrenchExercise[] = [

  {
    id: 'fr-cm1-conjugaison-101',
    subject: 'francais',
    title: 'Présent – verbe du 3e groupe (venir)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present 3e groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Mes cousins ___ nous rendre visite chaque dimanche.',
    options: [
      { id: 'a', text: 'viennent', isCorrect: true },
      { id: 'b', text: 'venons', isCorrect: false },
      { id: 'c', text: 'vient', isCorrect: false },
    ],
    correctAnswer: 'viennent',
    explanation: 'Au présent, le verbe venir avec "ils/elles" donne viennent.',
    hint: 'Le sujet est "mes cousins" = ils.',
    tags: ['cm1', 'conjugaison', 'present', '3e-groupe', 'venir', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-102',
    subject: 'francais',
    title: 'Présent – verbe du 3e groupe (prendre)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'present 3e groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Je ___ mon cartable et je pars à l\'école.',
    options: [
      { id: 'a', text: 'prendons', isCorrect: false },
      { id: 'b', text: 'prends', isCorrect: true },
      { id: 'c', text: 'prend', isCorrect: false },
    ],
    correctAnswer: 'prends',
    explanation: 'Au présent, "prendre" avec "je" donne prends (avec un s final muet).',
    hint: 'Je, tu → -ds pour les verbes du 3e groupe en -dre.',
    tags: ['cm1', 'conjugaison', 'present', '3e-groupe', 'prendre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-103',
    subject: 'francais',
    title: 'Imparfait – 1er groupe',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'imparfait 1er groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme à l\'imparfait.',
    prompt: 'Hier soir, les enfants ___ dans la piscine.',
    options: [
      { id: 'a', text: 'nagent', isCorrect: false },
      { id: 'b', text: 'nageaient', isCorrect: true },
      { id: 'c', text: 'nagerons', isCorrect: false },
    ],
    correctAnswer: 'nageaient',
    explanation: 'L\'imparfait avec "les enfants" (= ils) donne nageaient.',
    hint: 'L\'imparfait exprime une action passée qui durait. Cherche la terminaison -aient.',
    tags: ['cm1', 'conjugaison', 'imparfait', '1er-groupe', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-104',
    subject: 'francais',
    title: 'Imparfait – être',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'conjugaison',
    subskill: 'imparfait etre',
    format: 'qcm',
    instructions: 'Choisis la bonne forme à l\'imparfait.',
    prompt: 'Quand j\'avais cinq ans, j\' ___ très timide.',
    options: [
      { id: 'a', text: 'es', isCorrect: false },
      { id: 'b', text: 'étais', isCorrect: true },
      { id: 'c', text: 'serai', isCorrect: false },
    ],
    correctAnswer: 'étais',
    explanation: 'Le verbe être à l\'imparfait avec "je" donne étais.',
    hint: 'L\'imparfait de "être" avec je : j\'étais.',
    tags: ['cm1', 'conjugaison', 'imparfait', 'etre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-105',
    subject: 'francais',
    title: 'Futur simple – 1er groupe',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'futur simple 1er groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme au futur simple.',
    prompt: 'Demain, nous ___ un gâteau pour l\'anniversaire de maman.',
    options: [
      { id: 'a', text: 'préparons', isCorrect: false },
      { id: 'b', text: 'préparerons', isCorrect: true },
      { id: 'c', text: 'préparions', isCorrect: false },
    ],
    correctAnswer: 'préparerons',
    explanation: 'Au futur simple, "préparer" avec "nous" donne préparerons.',
    hint: 'Le futur simple des verbes en -er : infinitif + terminaisons (-ai, -as, -a, -ons, -ez, -ont).',
    tags: ['cm1', 'conjugaison', 'futur-simple', '1er-groupe', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-106',
    subject: 'francais',
    title: 'Futur simple – avoir',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'futur simple avoir',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Tu ___ de meilleures notes si tu révises régulièrement.',
    options: [
      { id: 'a', text: 'as', isCorrect: false },
      { id: 'b', text: 'avais', isCorrect: false },
      { id: 'c', text: 'auras', isCorrect: true },
    ],
    correctAnswer: 'auras',
    explanation: 'Le verbe avoir au futur simple avec "tu" donne auras.',
    hint: 'Le futur de "avoir" : j\'aurai, tu auras, il aura…',
    tags: ['cm1', 'conjugaison', 'futur-simple', 'avoir', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-107',
    subject: 'francais',
    title: 'Passé composé – auxiliaire avoir',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'passe compose avoir',
    format: 'qcm',
    instructions: 'Choisis la bonne forme au passé composé.',
    prompt: 'Ce matin, Léa ___ toutes ses affaires.',
    options: [
      { id: 'a', text: 'a rangé', isCorrect: true },
      { id: 'b', text: 'a ranger', isCorrect: false },
      { id: 'c', text: 'est rangée', isCorrect: false },
    ],
    correctAnswer: 'a rangé',
    explanation: 'Le passé composé de "ranger" se forme avec l\'auxiliaire avoir : a rangé.',
    hint: 'Le passé composé = auxiliaire avoir/être + participe passé.',
    tags: ['cm1', 'conjugaison', 'passe-compose', 'avoir', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-108',
    subject: 'francais',
    title: 'Passé composé – auxiliaire être',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'passe compose etre',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Hier, Camille ___ au marché avec sa grand-mère.',
    options: [
      { id: 'a', text: 'a allé', isCorrect: false },
      { id: 'b', text: 'est allée', isCorrect: true },
      { id: 'c', text: 'est allé', isCorrect: false },
    ],
    correctAnswer: 'est allée',
    explanation: 'Aller se conjugue avec être. Camille est féminin, donc allée s\'accorde : est allée.',
    hint: 'Avec être, le participe passé s\'accorde avec le sujet.',
    tags: ['cm1', 'conjugaison', 'passe-compose', 'etre', 'accord', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-109',
    subject: 'francais',
    title: 'Infinitif ou passé composé ?',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'conjugaison',
    subskill: 'infinitif vs participe passe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'J\'ai envie de ___ une promenade en forêt.',
    options: [
      { id: 'a', text: 'fait', isCorrect: false },
      { id: 'b', text: 'faire', isCorrect: true },
      { id: 'c', text: 'faisait', isCorrect: false },
    ],
    correctAnswer: 'faire',
    explanation: 'Après "envie de", on emploie l\'infinitif : envie de faire.',
    hint: 'Après une préposition (de, à, pour…), on utilise l\'infinitif.',
    tags: ['cm1', 'conjugaison', 'infinitif', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-110',
    subject: 'francais',
    title: 'Identifier le temps',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'identifier le temps',
    format: 'qcm',
    instructions: 'Dans quelle phrase le verbe est-il au futur simple ?',
    prompt: 'Repère la phrase où le verbe est conjugué au futur simple.',
    options: [
      { id: 'a', text: 'Les enfants jouaient dans le parc.', isCorrect: false },
      { id: 'b', text: 'Elle viendra demain matin.', isCorrect: true },
      { id: 'c', text: 'Nous avons mangé des crêpes.', isCorrect: false },
    ],
    correctAnswer: 'Elle viendra demain matin.',
    explanation: '"Jouaient" est à l\'imparfait, "avons mangé" au passé composé. "Viendra" est bien au futur simple.',
    hint: 'Le futur simple exprime une action à venir. Cherche la terminaison -ra.',
    tags: ['cm1', 'conjugaison', 'futur-simple', 'identifier-temps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-111',
    subject: 'francais',
    title: 'Imparfait – 2e groupe',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'imparfait 2e groupe',
    format: 'qcm',
    instructions: 'Choisis la bonne forme à l\'imparfait.',
    prompt: 'Quand il était petit, il ___ très fort.',
    options: [
      { id: 'a', text: 'grandissait', isCorrect: true },
      { id: 'b', text: 'grandira', isCorrect: false },
      { id: 'c', text: 'a grandi', isCorrect: false },
    ],
    correctAnswer: 'grandissait',
    explanation: '"Grandir" au 2e groupe à l\'imparfait avec "il" : grandissait.',
    hint: 'L\'imparfait des verbes en -ir (2e groupe) : je grandissais, tu grandissais, il grandissait…',
    tags: ['cm1', 'conjugaison', 'imparfait', '2e-groupe', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },

  {
    id: 'fr-cm1-conjugaison-112',
    subject: 'francais',
    title: 'Futur simple – être',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'conjugaison',
    subskill: 'futur simple etre',
    format: 'qcm',
    instructions: 'Choisis la bonne forme au futur.',
    prompt: 'Dans dix ans, vous ___ beaucoup plus grands.',
    options: [
      { id: 'a', text: 'êtes', isCorrect: false },
      { id: 'b', text: 'étiez', isCorrect: false },
      { id: 'c', text: 'serez', isCorrect: true },
    ],
    correctAnswer: 'serez',
    explanation: 'Le futur simple de "être" avec "vous" est serez.',
    hint: 'Le futur de "être" : je serai, tu seras, il sera, nous serons, vous serez, ils seront.',
    tags: ['cm1', 'conjugaison', 'futur-simple', 'etre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'francais:conjugaison',
  },
];
