import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { FrenchExercise } from '../french.types';

export const frenchCm1OrthographeExercises: FrenchExercise[] = [

  {
    id: 'fr-cm1-orthographe-101',
    subject: 'francais',
    title: 'a ou à ?',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Elle ___ décidé d\'aller ___ la mer.',
    options: [
      { id: 'a', text: 'a / à', isCorrect: true },
      { id: 'b', text: 'à / a', isCorrect: false },
      { id: 'c', text: 'a / a', isCorrect: false },
    ],
    correctAnswer: 'a / à',
    explanation: '"A" (sans accent) est le verbe avoir conjugué. "À" (avec accent) est une préposition.',
    hint: 'Si on peut le remplacer par "avait", c\'est le verbe avoir (sans accent).',
    tags: ['cm1', 'orthographe', 'a-a', 'homophones', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-102',
    subject: 'francais',
    title: 'et ou est ?',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Le ciel ___ bleu ___ les nuages ont disparu.',
    options: [
      { id: 'a', text: 'et / est', isCorrect: false },
      { id: 'b', text: 'est / et', isCorrect: true },
      { id: 'c', text: 'est / est', isCorrect: false },
    ],
    correctAnswer: 'est / et',
    explanation: '"Est" (verbe être) suit le sujet "le ciel". "Et" est une conjonction de coordination qui relie deux propositions.',
    hint: 'Si on peut remplacer par "était", c\'est le verbe être. Sinon, c\'est "et".',
    tags: ['cm1', 'orthographe', 'et-est', 'homophones', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-103',
    subject: 'francais',
    title: 'son ou sont ?',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Les élèves ___ dans la cour avec ___ professeur.',
    options: [
      { id: 'a', text: 'son / sont', isCorrect: false },
      { id: 'b', text: 'sont / son', isCorrect: true },
      { id: 'c', text: 'sont / sont', isCorrect: false },
    ],
    correctAnswer: 'sont / son',
    explanation: '"Sont" = verbe être (ils sont). "Son" = déterminant possessif (son professeur).',
    hint: 'Si on peut remplacer par "étaient", c\'est le verbe être (sont). Sinon, c\'est le déterminant (son).',
    tags: ['cm1', 'orthographe', 'son-sont', 'homophones', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-104',
    subject: 'francais',
    title: 'ou ou où ?',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Tu viens ___ tu restes ? C\'est toi qui décides ___ tu veux aller.',
    options: [
      { id: 'a', text: 'où / ou', isCorrect: false },
      { id: 'b', text: 'ou / où', isCorrect: true },
      { id: 'c', text: 'ou / ou', isCorrect: false },
    ],
    correctAnswer: 'ou / où',
    explanation: '"Ou" exprime un choix (ou bien). "Où" exprime un lieu ou une question sur le lieu.',
    hint: 'Si on peut remplacer par "ou bien", c\'est "ou". S\'il s\'agit d\'un lieu, c\'est "où".',
    tags: ['cm1', 'orthographe', 'ou-ou', 'homophones', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-105',
    subject: 'francais',
    title: 'Accord de l\'adjectif',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'accord adjectif',
    format: 'qcm',
    instructions: 'Choisis la forme correcte.',
    prompt: 'Les maisons ___ se dressent au sommet de la colline.',
    options: [
      { id: 'a', text: 'ancien', isCorrect: false },
      { id: 'b', text: 'ancienne', isCorrect: false },
      { id: 'c', text: 'anciennes', isCorrect: true },
    ],
    correctAnswer: 'anciennes',
    explanation: '"Maisons" est féminin pluriel. L\'adjectif s\'accorde : ancienne → anciennes.',
    hint: 'L\'adjectif s\'accorde en genre et en nombre avec le nom qu\'il qualifie.',
    tags: ['cm1', 'orthographe', 'accord-adjectif', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-106',
    subject: 'francais',
    title: 'Pluriel des noms en -al',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'pluriel des noms',
    format: 'qcm',
    instructions: 'Choisis la bonne forme au pluriel.',
    prompt: 'Les ___ du zoo étaient magnifiques.',
    options: [
      { id: 'a', text: 'animals', isCorrect: false },
      { id: 'b', text: 'animaux', isCorrect: true },
      { id: 'c', text: 'animales', isCorrect: false },
    ],
    correctAnswer: 'animaux',
    explanation: 'Les noms en -al font leur pluriel en -aux : animal → animaux.',
    hint: 'Les noms en -al ne prennent pas un simple "s" au pluriel.',
    tags: ['cm1', 'orthographe', 'pluriel', 'al-aux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-107',
    subject: 'francais',
    title: 'Pluriel des noms en -eau',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'pluriel des noms',
    format: 'qcm',
    instructions: 'Choisis la bonne forme au pluriel.',
    prompt: 'Les ___ peints par les enfants sont affichés dans le couloir.',
    options: [
      { id: 'a', text: 'tableaus', isCorrect: false },
      { id: 'b', text: 'tableaux', isCorrect: true },
      { id: 'c', text: 'tableus', isCorrect: false },
    ],
    correctAnswer: 'tableaux',
    explanation: 'Les noms en -eau prennent un x au pluriel : tableau → tableaux.',
    hint: '-eau → -eaux au pluriel.',
    tags: ['cm1', 'orthographe', 'pluriel', 'eau-eaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-108',
    subject: 'francais',
    title: 'Féminin des adjectifs – doublement de consonne',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'orthographe',
    subskill: 'feminin des adjectifs',
    format: 'qcm',
    instructions: 'Choisis la bonne forme au féminin.',
    prompt: 'Une réponse ___ (bon).',
    options: [
      { id: 'a', text: 'bone', isCorrect: false },
      { id: 'b', text: 'bonne', isCorrect: true },
      { id: 'c', text: 'bons', isCorrect: false },
    ],
    correctAnswer: 'bonne',
    explanation: 'L\'adjectif "bon" fait "bonne" au féminin avec doublement du n.',
    hint: 'Certains adjectifs doublent leur consonne finale au féminin.',
    tags: ['cm1', 'orthographe', 'feminin-adjectif', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-109',
    subject: 'francais',
    title: 'Participe passé en -é ou infinitif en -er ?',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'infinitif vs participe passe',
    format: 'qcm',
    instructions: 'Choisis la bonne orthographe.',
    prompt: 'Le gâteau est bien ___ (cuire).',
    options: [
      { id: 'a', text: 'cuire', isCorrect: false },
      { id: 'b', text: 'cuit', isCorrect: true },
      { id: 'c', text: 'cuité', isCorrect: false },
    ],
    correctAnswer: 'cuit',
    explanation: '"Est cuit" = être + participe passé. Le participe passé de "cuire" est "cuit".',
    hint: 'Avec le verbe être, on utilise le participe passé, pas l\'infinitif.',
    tags: ['cm1', 'orthographe', 'participe-passe', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-110',
    subject: 'francais',
    title: 'Majuscule aux noms propres',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'orthographe',
    subskill: 'majuscules',
    format: 'qcm',
    instructions: 'Quelle phrase est correctement écrite ?',
    prompt: 'Repère la phrase correctement orthographiée.',
    options: [
      { id: 'a', text: 'Mon ami thomas habite à paris.', isCorrect: false },
      { id: 'b', text: 'Mon ami Thomas habite à Paris.', isCorrect: true },
      { id: 'c', text: 'mon ami thomas habite à Paris.', isCorrect: false },
    ],
    correctAnswer: 'Mon ami Thomas habite à Paris.',
    explanation: 'Les noms propres (prénom Thomas, ville Paris) prennent une majuscule. La phrase commence aussi par une majuscule.',
    hint: 'Les prénoms, noms de famille et noms de villes prennent une majuscule.',
    tags: ['cm1', 'orthographe', 'majuscules', 'noms-propres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-111',
    subject: 'francais',
    title: 'Accord du verbe avec un sujet inversé',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'accord sujet verbe',
    format: 'qcm',
    instructions: 'Choisis la forme correcte.',
    prompt: 'Dans la montagne ___ de nombreux bouquetins.',
    options: [
      { id: 'a', text: 'vit', isCorrect: false },
      { id: 'b', text: 'vivent', isCorrect: true },
      { id: 'c', text: 'vivons', isCorrect: false },
    ],
    correctAnswer: 'vivent',
    explanation: 'Le sujet réel est "de nombreux bouquetins" (pluriel), même s\'il est après le verbe. Le verbe s\'accorde : vivent.',
    hint: 'Repère le vrai sujet même s\'il est après le verbe.',
    tags: ['cm1', 'orthographe', 'accord-sujet-verbe', 'sujet-inverse', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:orthographe',
  },

  {
    id: 'fr-cm1-orthographe-112',
    subject: 'francais',
    title: 'Ni ou n\'y ?',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'orthographe',
    subskill: 'homophones grammaticaux',
    format: 'qcm',
    instructions: 'Choisis le bon mot.',
    prompt: 'Il ne mange ___ fruits ___ légumes.',
    options: [
      { id: 'a', text: 'n\'y / ni', isCorrect: false },
      { id: 'b', text: 'ni / ni', isCorrect: true },
      { id: 'c', text: 'ni / n\'y', isCorrect: false },
    ],
    correctAnswer: 'ni / ni',
    explanation: '"Ni… ni" est une conjonction de coordination négative qui remplace "et" dans une phrase négative.',
    hint: '"Ni… ni" relie deux éléments dans une phrase négative (comme "et" mais en négatif).',
    tags: ['cm1', 'orthographe', 'ni-ny', 'homophones', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'francais:orthographe',
  },
];
