import type { HgExercise } from '../hg.types';
import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';

const A = cloneDefaultAdaptations();

export const hgCm2GeoMondeVillesExercises: HgExercise[] = [
  {
    id: 'hg-cm2-geo-vil-001',
    subject: 'histoire_geo',
    title: 'L\'urbanisation mondiale',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Aujourd\'hui, quelle part de la population mondiale vit en ville ?',
    options: [
      { id: 'a', text: 'Environ 30 % de la population mondiale', isCorrect: false },
      { id: 'b', text: 'Plus de la moitié (plus de 55 %)', isCorrect: true },
      { id: 'c', text: 'Environ 80 % de la population mondiale', isCorrect: false },
      { id: 'd', text: 'Moins de 20 % de la population mondiale', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Depuis 2007, plus de la moitié de la population mondiale vit en ville. Cette urbanisation est particulièrement rapide en Afrique et en Asie.',
    hint: 'La majorité de l\'humanité est désormais citadine.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-002',
    subject: 'histoire_geo',
    title: 'Les mégapoles',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'appelle-t-on une mégapole ou mégalopole ?',
    options: [
      { id: 'a', text: 'Une ville de plus de 100 000 habitants', isCorrect: false },
      { id: 'b', text: 'Une ville ou aire urbaine de plus de 10 millions d\'habitants', isCorrect: true },
      { id: 'c', text: 'Une capitale d\'État très moderne', isCorrect: false },
      { id: 'd', text: 'Une ville qui possède un réseau de métro', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Une mégapole est une ville ou agglomération de plus de 10 millions d\'habitants. Tokyo, Delhi, Shanghai, São Paulo sont des exemples de mégapoles mondiales.',
    hint: 'Le préfixe « méga » signifie très grand ou million.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-003',
    subject: 'histoire_geo',
    title: 'La plus grande ville du monde',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la plus grande aire urbaine du monde en nombre d\'habitants ?',
    options: [
      { id: 'a', text: 'New York', isCorrect: false },
      { id: 'b', text: 'Tokyo', isCorrect: true },
      { id: 'c', text: 'Shanghai', isCorrect: false },
      { id: 'd', text: 'Mexico', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Tokyo, au Japon, est la plus grande aire urbaine du monde avec environ 37 millions d\'habitants dans son agglomération. C\'est une des villes les mieux organisées au monde malgré sa taille.',
    hint: 'C\'est la capitale du Japon.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-004',
    subject: 'histoire_geo',
    title: 'Les villes mondiales',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui caractérise une « ville mondiale » (ou ville globale) ?',
    options: [
      { id: 'a', text: 'Une ville avec le plus grand nombre d\'habitants de son pays', isCorrect: false },
      { id: 'b', text: 'Une ville qui concentre des fonctions de commandement économique, financier et culturel à l\'échelle mondiale', isCorrect: true },
      { id: 'c', text: 'Une ville qui accueille des Jeux olympiques', isCorrect: false },
      { id: 'd', text: 'Une ville reliée par avion à tous les autres continents', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Une ville mondiale comme New York, Londres, Tokyo ou Paris concentre des sièges de grandes entreprises, des bourses, des institutions culturelles et des organisations internationales qui influencent le monde entier.',
    hint: 'Ces villes « dirigent » l\'économie mondiale depuis leurs gratte-ciels.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-005',
    subject: 'histoire_geo',
    title: 'Les bidonvilles',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'appelle-t-on les bidonvilles dans les grandes villes du monde en développement ?',
    options: [
      { id: 'a', text: 'Des quartiers industriels en dehors des villes', isCorrect: false },
      { id: 'b', text: 'Des quartiers construits spontanément par des migrants pauvres, sans eau courante ni électricité', isCorrect: true },
      { id: 'c', text: 'Des zones commerciales réservées aux marchés', isCorrect: false },
      { id: 'd', text: 'Des quartiers historiques anciens mal entretenus', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les bidonvilles (favelas au Brésil, slums en Inde, shanty towns en Afrique) sont des quartiers précaires construits par des migrants ruraux qui arrivent en ville sans ressources et s\'installent en dehors des zones officielles.',
    hint: 'Ces quartiers naissent de l\'afflux de personnes pauvres vers les grandes villes.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-006',
    subject: 'histoire_geo',
    title: 'Paris dans le monde',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien d\'habitants compte l\'agglomération parisienne (Île-de-France) ?',
    options: [
      { id: 'a', text: 'Environ 2 millions', isCorrect: false },
      { id: 'b', text: 'Environ 12 millions', isCorrect: true },
      { id: 'c', text: 'Environ 30 millions', isCorrect: false },
      { id: 'd', text: 'Environ 5 millions', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La région Île-de-France, qui comprend Paris et ses banlieues, compte environ 12 millions d\'habitants, soit près d\'un Français sur cinq. C\'est une mégalopole à l\'échelle européenne.',
    hint: 'C\'est environ 20 % de la population française concentrée dans une seule région.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-007',
    subject: 'histoire_geo',
    title: 'Les problèmes des grandes villes',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est l\'un des principaux problèmes liés à la croissance rapide des villes dans les pays en développement ?',
    options: [
      { id: 'a', text: 'Un excès de musées et de lieux culturels', isCorrect: false },
      { id: 'b', text: 'Le manque d\'infrastructures (routes, eau, égouts, logements) pour accueillir les nouveaux habitants', isCorrect: true },
      { id: 'c', text: 'Un trop grand nombre d\'emplois disponibles', isCorrect: false },
      { id: 'd', text: 'Une population trop âgée qui ralentit la croissance', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La croissance urbaine rapide crée des défis immenses : construire des logements, des routes, des réseaux d\'eau potable et d\'assainissement pour des millions de nouveaux habitants est une tâche très difficile.',
    hint: 'Les villes grandissent plus vite que les services ne peuvent suivre.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-008',
    subject: 'histoire_geo',
    title: 'Les villes et l\'environnement',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les grandes villes peuvent-elles réduire leur impact sur l\'environnement ?',
    options: [
      { id: 'a', text: 'En interdisant les voitures uniquement le dimanche', isCorrect: false },
      { id: 'b', text: 'En développant les transports en commun, les pistes cyclables et les espaces verts', isCorrect: true },
      { id: 'c', text: 'En construisant plus de parkings pour libérer les rues', isCorrect: false },
      { id: 'd', text: 'En déplaçant toutes les usines en dehors de la ville', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les villes durables réduisent leur empreinte écologique en favorisant les transports en commun, les mobilités douces (vélo, marche) et en augmentant les espaces verts qui captent le CO₂ et rafraîchissent l\'air.',
    hint: 'Moins de voitures = moins de pollution.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-009',
    subject: 'histoire_geo',
    title: 'Les villes d\'Asie',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle ville est la capitale économique de la Chine et l\'une des plus grandes villes du monde ?',
    options: [
      { id: 'a', text: 'Pékin (Beijing)', isCorrect: false },
      { id: 'b', text: 'Shanghai', isCorrect: true },
      { id: 'c', text: 'Hong Kong', isCorrect: false },
      { id: 'd', text: 'Guangzhou', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Shanghai est le principal centre économique et financier de la Chine, avec environ 25 millions d\'habitants. Son port est l\'un des plus actifs au monde. Pékin est la capitale politique.',
    hint: 'Cette ville est connue pour ses gratte-ciels sur le fleuve Huangpu.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-010',
    subject: 'histoire_geo',
    title: 'Les capitales africaines',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la ville la plus peuplée d\'Afrique ?',
    options: [
      { id: 'a', text: 'Le Caire (Égypte)', isCorrect: false },
      { id: 'b', text: 'Lagos (Nigeria)', isCorrect: true },
      { id: 'c', text: 'Johannesburg (Afrique du Sud)', isCorrect: false },
      { id: 'd', text: 'Kinshasa (RD Congo)', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Lagos, au Nigeria, est la ville la plus peuplée d\'Afrique avec environ 15 millions d\'habitants dans la ville et plus de 20 millions dans son agglomération. Elle connaît une croissance très rapide.',
    hint: 'Cette ville se trouve en Afrique de l\'Ouest, dans le pays le plus peuplé d\'Afrique.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-011',
    subject: 'histoire_geo',
    title: 'New York',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle organisation internationale a son siège à New York ?',
    options: [
      { id: 'a', text: 'L\'Union européenne', isCorrect: false },
      { id: 'b', text: 'L\'Organisation des Nations Unies (ONU)', isCorrect: true },
      { id: 'c', text: 'L\'OTAN', isCorrect: false },
      { id: 'd', text: 'Le Fonds monétaire international (FMI)', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le siège de l\'ONU est situé à New York depuis 1945. Cette organisation réunit presque tous les pays du monde et joue un rôle central dans le maintien de la paix internationale.',
    hint: 'Ce grand bâtiment de verre se trouve le long de l\'East River.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-012',
    subject: 'histoire_geo',
    title: 'L\'exode rural',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'appelle-t-on l\'exode rural ?',
    options: [
      { id: 'a', text: 'Le départ de citadins vers les campagnes', isCorrect: false },
      { id: 'b', text: 'Le déplacement de populations rurales vers les villes à la recherche d\'emploi', isCorrect: true },
      { id: 'c', text: 'La migration de paysans vers d\'autres pays', isCorrect: false },
      { id: 'd', text: 'L\'abandon des terres agricoles en raison de la sécheresse', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'exode rural désigne le mouvement de populations qui quittent les campagnes pour s\'installer en ville. Ce phénomène a été très important en France au XIXe et XXe siècles et continue dans les pays en développement.',
    hint: 'L\'exode, c\'est quitter un endroit ; rural concerne la campagne.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-013',
    subject: 'histoire_geo',
    title: 'Les villes et les réseaux de transport',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les grandes villes mondiales ont-elles toutes un aéroport international important ?',
    options: [
      { id: 'a', text: 'Pour accueillir les avions militaires en cas de guerre', isCorrect: false },
      { id: 'b', text: 'Pour relier la ville au reste du monde et attirer entreprises, touristes et travailleurs qualifiés', isCorrect: true },
      { id: 'c', text: 'Parce que la loi internationale oblige chaque grande ville à avoir un aéroport', isCorrect: false },
      { id: 'd', text: 'Pour permettre aux habitants de la ville de partir en vacances', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les aéroports internationaux sont essentiels pour les villes mondiales car ils permettent les échanges rapides de personnes, de marchandises et d\'informations, indispensables à leur rôle dans l\'économie mondiale.',
    hint: 'Être bien connecté au reste du monde est crucial pour une ville mondiale.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-014',
    subject: 'histoire_geo',
    title: 'São Paulo',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans quel pays se trouve São Paulo, l\'une des plus grandes villes du monde ?',
    options: [
      { id: 'a', text: 'L\'Argentine', isCorrect: false },
      { id: 'b', text: 'Le Brésil', isCorrect: true },
      { id: 'c', text: 'Le Mexique', isCorrect: false },
      { id: 'd', text: 'La Colombie', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'São Paulo est la plus grande ville du Brésil et d\'Amérique du Sud, avec plus de 22 millions d\'habitants dans son agglomération. C\'est le principal centre économique et financier de l\'Amérique latine.',
    hint: 'C\'est la plus grande ville d\'Amérique du Sud.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-vil-015',
    subject: 'histoire_geo',
    title: 'Villes et inégalités',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes et urbanisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les inégalités sociales se lisent-elles dans l\'espace urbain ?',
    options: [
      { id: 'a', text: 'Toutes les personnes pauvres vivent au centre-ville', isCorrect: false },
      { id: 'b', text: 'Les quartiers aisés et les quartiers pauvres sont souvent séparés, avec de grandes différences en qualité de logement et d\'accès aux services', isCorrect: true },
      { id: 'c', text: 'Les inégalités n\'existent pas dans les villes modernes', isCorrect: false },
      { id: 'd', text: 'Les riches et les pauvres vivent toujours dans les mêmes quartiers', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Dans la plupart des grandes villes, on observe une ségrégation spatiale : les quartiers riches (centre historique ou banlieues résidentielles) et les quartiers pauvres (périphéries, bidonvilles) sont clairement séparés.',
    hint: 'Une carte d\'une ville révèle souvent les inégalités par la qualité des quartiers.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
