import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm2GeoMieuxHabiterExercises: HgExercise[] = [

  {
    id: 'hg-cm2-geo-mhab-001',
    subject: 'histoire_geo',
    title: 'Le développement durable',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'mieux_habiter',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le développement durable consiste à répondre aux besoins d\'aujourd\'hui sans nuire aux générations futures. Lequel de ces gestes est un exemple de développement durable ?',
    options: [
      { id: 'a', text: 'Laisser le robinet couler en se brossant les dents', isCorrect: false },
      { id: 'b', text: 'Trier ses déchets pour les recycler', isCorrect: true },
      { id: 'c', text: 'Jeter ses déchets dans la nature', isCorrect: false },
      { id: 'd', text: 'Utiliser du plastique à usage unique', isCorrect: false },
    ],
    correctAnswer: 'Trier ses déchets pour les recycler',
    explanation: 'Trier ses déchets permet de les recycler et de réduire les décharges. C\'est un geste simple qui préserve l\'environnement pour les générations futures.',
    hint: 'Ce geste consiste à séparer le verre, le papier, le plastique…',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-002',
    subject: 'histoire_geo',
    title: 'Les énergies renouvelables',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'mieux_habiter',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle énergie est renouvelable et propre, car elle ne pollue pas ?',
    options: [
      { id: 'a', text: 'Le charbon', isCorrect: false },
      { id: 'b', text: 'Le pétrole', isCorrect: false },
      { id: 'c', text: 'L\'énergie solaire', isCorrect: true },
      { id: 'd', text: 'Le fioul', isCorrect: false },
    ],
    correctAnswer: 'L\'énergie solaire',
    explanation: 'L\'énergie solaire est produite par les panneaux photovoltaïques qui captent la lumière du soleil. Elle ne produit pas de gaz polluants, contrairement au pétrole ou au charbon.',
    hint: 'Cette énergie vient de la lumière et de la chaleur du soleil.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-003',
    subject: 'histoire_geo',
    title: 'Les espaces verts en ville',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'mieux_habiter',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les villes aménagent-elles des parcs et des espaces verts pour leurs habitants ?',
    options: [
      { id: 'a', text: 'Pour construire davantage d\'immeubles', isCorrect: false },
      { id: 'b', text: 'Pour améliorer la qualité de l\'air et offrir des espaces de détente', isCorrect: true },
      { id: 'c', text: 'Pour empêcher les habitants de se déplacer', isCorrect: false },
      { id: 'd', text: 'Pour augmenter la circulation automobile', isCorrect: false },
    ],
    correctAnswer: 'Pour améliorer la qualité de l\'air et offrir des espaces de détente',
    explanation: 'Les espaces verts en ville améliorent la qualité de l\'air, réduisent la chaleur et offrent des lieux de promenade et de détente aux habitants.',
    hint: 'Les arbres et les plantes produisent de l\'oxygène et absorbent le CO₂.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-004',
    subject: 'histoire_geo',
    title: 'La gestion de l\'eau',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'mieux_habiter',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'eau douce est une ressource précieuse et limitée. Quel geste quotidien permet d\'économiser l\'eau ?',
    options: [
      { id: 'a', text: 'Prendre un bain au lieu d\'une douche', isCorrect: false },
      { id: 'b', text: 'Fermer le robinet pendant qu\'on se savonne les mains', isCorrect: true },
      { id: 'c', text: 'Arroser le jardin à midi en été', isCorrect: false },
      { id: 'd', text: 'Laisser l\'eau couler pour vérifier sa température', isCorrect: false },
    ],
    correctAnswer: 'Fermer le robinet pendant qu\'on se savonne les mains',
    explanation: 'Fermer le robinet pendant le savonnage évite de gaspiller des litres d\'eau. Une douche consomme aussi beaucoup moins d\'eau qu\'un bain.',
    hint: 'Ce geste simple permet d\'éviter de laisser couler l\'eau inutilement.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-005',
    subject: 'histoire_geo',
    title: 'Les déchets et le recyclage',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'mieux_habiter',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le recyclage du papier permet de préserver des forêts. Combien de fois peut-on environ recycler une feuille de papier ?',
    options: [
      { id: 'a', text: '1 fois', isCorrect: false },
      { id: 'b', text: '5 à 7 fois', isCorrect: true },
      { id: 'c', text: '50 fois', isCorrect: false },
      { id: 'd', text: '200 fois', isCorrect: false },
    ],
    correctAnswer: '5 à 7 fois',
    explanation: 'Le papier peut être recyclé environ 5 à 7 fois. Cela permet de couper moins d\'arbres et d\'économiser l\'eau et l\'énergie utilisées pour fabriquer du papier neuf.',
    hint: 'Ce n\'est pas illimité, mais c\'est déjà plusieurs fois.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-006',
    subject: 'histoire_geo',
    title: 'Les villes durables',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'mieux_habiter',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une ville "durable" cherche à mieux vivre tout en respectant l\'environnement. Laquelle de ces caractéristiques correspond à une ville durable ?',
    options: [
      { id: 'a', text: 'Elle construit uniquement des autoroutes', isCorrect: false },
      { id: 'b', text: 'Elle développe les transports en commun et les pistes cyclables', isCorrect: true },
      { id: 'c', text: 'Elle supprime tous les espaces verts pour construire', isCorrect: false },
      { id: 'd', text: 'Elle brûle ses déchets sans les trier', isCorrect: false },
    ],
    correctAnswer: 'Elle développe les transports en commun et les pistes cyclables',
    explanation: 'Une ville durable favorise les modes de transport propres (vélo, transports en commun), réduit la pollution et préserve les espaces naturels.',
    hint: 'Ces aménagements réduisent la place de la voiture et la pollution.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-007',
    subject: 'histoire_geo',
    title: "L'îlot de chaleur urbain",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes_durables',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les villes sont souvent plus chaudes que les campagnes environnantes, surtout la nuit. Ce phénomène s'appelle…",
    options: [
      { id: 'a', text: "Le serre de verre", isCorrect: false },
      { id: 'b', text: "L'îlot de chaleur urbain", isCorrect: true },
      { id: 'c', text: "La canicule rurale", isCorrect: false },
      { id: 'd', text: "Le smog thermique", isCorrect: false },
    ],
    correctAnswer: "L'îlot de chaleur urbain",
    explanation: "L'îlot de chaleur urbain est causé par les surfaces minérales (béton, asphalte) qui absorbent la chaleur, la densité des bâtiments, les activités humaines et la faible végétation. Les villes peuvent être 5 à 8°C plus chaudes que la campagne.",
    hint: "Ville plus chaude que la campagne = îlot de chaleur urbain.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-008',
    subject: 'histoire_geo',
    title: "Les villes côtières menacées",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'changement_climatique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le réchauffement climatique fait monter le niveau des mers. Quelle ville française est menacée par ce phénomène ?",
    options: [
      { id: 'a', text: "Paris (Île-de-France)", isCorrect: false },
      { id: 'b', text: "Bordeaux et le littoral atlantique bas", isCorrect: true },
      { id: 'c', text: "Grenoble (Alpes)", isCorrect: false },
      { id: 'd', text: "Strasbourg (Alsace)", isCorrect: false },
    ],
    correctAnswer: "Bordeaux et le littoral atlantique bas",
    explanation: "La montée des eaux menace particulièrement les zones côtières basses : littoral atlantique, certaines parties de Bordeaux et ses alentours, ainsi que le Mont-Saint-Michel et les deltas (Camargue).",
    hint: "Montée des eaux → menace les littoraux et zones côtières basses.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-009',
    subject: 'histoire_geo',
    title: "Les éco-quartiers",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes_durables',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un éco-quartier est un quartier construit selon les principes du développement durable. Lequel de ces éléments s'y trouve ?",
    options: [
      { id: 'a', text: "Des parkings géants et des usines polluantes", isCorrect: false },
      { id: 'b', text: "Des bâtiments basse consommation, espaces verts et mobilités douces", isCorrect: true },
      { id: 'c', text: "Des habitations sans fenêtres pour économiser la chaleur", isCorrect: false },
      { id: 'd', text: "Des quartiers sans aucun habitant pour protéger la nature", isCorrect: false },
    ],
    correctAnswer: "Des bâtiments basse consommation, espaces verts et mobilités douces",
    explanation: "Un éco-quartier intègre bâtiments à faible consommation d'énergie, espaces verts, gestion de l'eau de pluie, mobilités douces (vélo, marche) et mixité sociale. Exemples : Clichy-Batignolles (Paris), La Confluence (Lyon).",
    hint: "Éco-quartier = bâtiments économes + espaces verts + transports doux.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-010',
    subject: 'histoire_geo',
    title: "Les ODD 2030",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'developpement_durable',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les ODD sont les Objectifs de Développement Durable fixés par l'ONU pour 2030. Combien y en a-t-il ?",
    options: [
      { id: 'a', text: "5", isCorrect: false },
      { id: 'b', text: "17", isCorrect: true },
      { id: 'c', text: "50", isCorrect: false },
      { id: 'd', text: "100", isCorrect: false },
    ],
    correctAnswer: "17",
    explanation: "Les 17 ODD (2015) couvrent des domaines comme la fin de la pauvreté, l'éducation pour tous, l'accès à l'eau, l'énergie propre, la lutte contre le changement climatique et la vie sur Terre et sous l'eau.",
    hint: "17 ODD pour 2030 → fixés par l'ONU en 2015.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-011',
    subject: 'histoire_geo',
    title: "L'accès à l'eau potable dans le monde",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inegalites_mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Aujourd'hui, combien de personnes dans le monde n'ont pas accès à l'eau potable de manière sûre ?",
    options: [
      { id: 'a', text: "Moins de 1 million", isCorrect: false },
      { id: 'b', text: "Environ 2 milliards", isCorrect: true },
      { id: 'c', text: "Toute la population mondiale a accès à l'eau potable", isCorrect: false },
      { id: 'd', text: "Seulement les habitants des déserts", isCorrect: false },
    ],
    correctAnswer: "Environ 2 milliards",
    explanation: "Selon l'OMS/ONU, environ 2 milliards de personnes n'ont pas accès à une eau potable sûre. C'est un enjeu majeur des ODD. L'Afrique subsaharienne et l'Asie du Sud sont les plus touchées.",
    hint: "~2 milliards de personnes sans eau potable sûre = enjeu ODD mondial.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-012',
    subject: 'histoire_geo',
    title: "La désertification",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'changement_climatique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La désertification est l'avancée du désert sur des terres autrefois fertiles. Dans quelle région du monde est-elle la plus grave ?",
    options: [
      { id: 'a', text: "Europe de l'Ouest", isCorrect: false },
      { id: 'b', text: "Sahel (Afrique subsaharienne)", isCorrect: true },
      { id: 'c', text: "Canada arctique", isCorrect: false },
      { id: 'd', text: "Amazonie uniquement", isCorrect: false },
    ],
    correctAnswer: "Sahel (Afrique subsaharienne)",
    explanation: "Le Sahel (bande d'Afrique au sud du Sahara : Mali, Niger, Tchad, Soudan…) est la zone la plus touchée par la désertification. Le recul des terres cultivables pousse des millions de personnes à migrer.",
    hint: "Désertification la plus grave = Sahel (bande africaine au sud du Sahara).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-013',
    subject: 'histoire_geo',
    title: "L'agriculture urbaine",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes_durables',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'agriculture urbaine consiste à cultiver des plantes en ville. Quel avantage principal apporte-t-elle ?",
    options: [
      { id: 'a', text: "Elle remplace entièrement les supermarchés", isCorrect: false },
      { id: 'b', text: "Elle réduit les distances entre production et consommation (circuit court) et reverdit la ville", isCorrect: true },
      { id: 'c', text: "Elle permet de nourrir toute la ville sans aucun apport extérieur", isCorrect: false },
      { id: 'd', text: "Elle est obligatoire dans tous les quartiers de France", isCorrect: false },
    ],
    correctAnswer: "Elle réduit les distances entre production et consommation (circuit court) et reverdit la ville",
    explanation: "L'agriculture urbaine (toits, jardins partagés, murs végétaux) permet de produire localement, réduire les transports, végétaliser la ville et créer du lien social.",
    hint: "Agriculture urbaine = produire en ville → circuit court + verdure.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-014',
    subject: 'histoire_geo',
    title: "La rénovation énergétique",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes_durables',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La rénovation énergétique d'un bâtiment consiste à…",
    options: [
      { id: 'a', text: "Démolir les vieux bâtiments pour en construire des neufs", isCorrect: false },
      { id: 'b', text: "Améliorer l'isolation et le chauffage pour réduire la consommation d'énergie", isCorrect: true },
      { id: 'c', text: "Peindre les façades des bâtiments en blanc pour réfléchir le soleil", isCorrect: false },
      { id: 'd', text: "Installer des panneaux publicitaires sur les toits", isCorrect: false },
    ],
    correctAnswer: "Améliorer l'isolation et le chauffage pour réduire la consommation d'énergie",
    explanation: "La rénovation énergétique améliore l'isolation des murs, toits et fenêtres, et modernise les systèmes de chauffage. Elle réduit les factures d'énergie et les émissions de CO₂.",
    hint: "Rénovation énergétique = mieux isoler les bâtiments → moins d'énergie consommée.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-015',
    subject: 'histoire_geo',
    title: "L'étalement urbain",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'amenagement_territoire',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'étalement urbain désigne l'expansion des villes sur les campagnes environnantes. Quel problème principal pose-t-il ?",
    options: [
      { id: 'a', text: "Les villes deviennent trop belles", isCorrect: false },
      { id: 'b', text: "Il consomme des terres agricoles et oblige à utiliser la voiture pour tout déplacement", isCorrect: true },
      { id: 'c', text: "Il crée trop d'emplois dans les nouvelles banlieues", isCorrect: false },
      { id: 'd', text: "Il réduit le nombre d'habitants dans les villes", isCorrect: false },
    ],
    correctAnswer: "Il consomme des terres agricoles et oblige à utiliser la voiture pour tout déplacement",
    explanation: "L'étalement urbain (lotissements périurbains) artificialise des terres agricoles ou naturelles et crée une dépendance à la voiture, car les transports en commun y sont rares. C'est un enjeu d'aménagement durable.",
    hint: "Étalement urbain = banlieues qui s'étendent → terres agricoles perdues + voiture obligatoire.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-016',
    subject: 'histoire_geo',
    title: "Les toits végétalisés",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'villes_durables',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les toits végétalisés (toitures plantées de végétaux) présentent plusieurs avantages en ville. Lequel ?",
    options: [
      { id: 'a', text: "Ils permettent de faire pousser des céréales pour nourrir la ville entière", isCorrect: false },
      { id: 'b', text: "Ils isolent le bâtiment, absorbent l'eau de pluie et réduisent l'îlot de chaleur urbain", isCorrect: true },
      { id: 'c', text: "Ils éliminent tous les polluants de l'air urbain", isCorrect: false },
      { id: 'd', text: "Ils sont obligatoires sur tous les immeubles neufs en France", isCorrect: false },
    ],
    correctAnswer: "Ils isolent le bâtiment, absorbent l'eau de pluie et réduisent l'îlot de chaleur urbain",
    explanation: "Les toits végétalisés apportent une isolation thermique naturelle, absorbent l'eau de pluie (réduisant les risques d'inondation), et créent de la biodiversité. Ils aident à lutter contre les îlots de chaleur.",
    hint: "Toit végétalisé = isolation + absorption eau de pluie + moins de chaleur.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-017',
    subject: 'histoire_geo',
    title: "L'empreinte écologique",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'developpement_durable',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'empreinte écologique mesure la surface terrestre nécessaire pour produire ce qu'une personne consomme. Que révèle-t-elle ?",
    options: [
      { id: 'a', text: "Que les pays riches consomment moins de ressources que les pays pauvres", isCorrect: false },
      { id: 'b', text: "Que si tout le monde vivait comme un Français, il faudrait environ 2 planètes Terre", isCorrect: true },
      { id: 'c', text: "Que la Terre peut accueillir une population illimitée sans problème", isCorrect: false },
      { id: 'd', text: "Que seuls les agriculteurs ont un impact sur la planète", isCorrect: false },
    ],
    correctAnswer: "Que si tout le monde vivait comme un Français, il faudrait environ 2 planètes Terre",
    explanation: "L'empreinte écologique d'un Français moyen nécessite environ 2,8 planètes Terre. Cela signifie que notre mode de vie consomme les ressources naturelles plus vite qu'elles ne peuvent se renouveler.",
    hint: "Empreinte écologique d'un Français ≈ 2 à 3 planètes nécessaires. Insoutenable.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-018',
    subject: 'histoire_geo',
    title: "Les migrations climatiques",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'changement_climatique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les migrations climatiques désignent des déplacements de populations causés par des changements environnementaux. Quelle en est une cause directe ?",
    options: [
      { id: 'a', text: "La construction de nouvelles usines dans les villes", isCorrect: false },
      { id: 'b', text: "La montée des eaux, les sécheresses ou les inondations qui rendent des zones inhabitables", isCorrect: true },
      { id: 'c', text: "La croissance économique des pays pauvres", isCorrect: false },
      { id: 'd', text: "L'ouverture de nouvelles universités dans les pays riches", isCorrect: false },
    ],
    correctAnswer: "La montée des eaux, les sécheresses ou les inondations qui rendent des zones inhabitables",
    explanation: "Le changement climatique provoque des migrations : populations des îles du Pacifique menacées par la montée des eaux, paysans du Sahel chassés par la sécheresse, habitants de zones inondées contraints de partir.",
    hint: "Migrations climatiques = zones devenues inhabitables (inondées, sèches, etc.).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-019',
    subject: 'histoire_geo',
    title: "La solidarité internationale",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inegalites_mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Des organisations humanitaires comme la Croix-Rouge ou Médecins Sans Frontières interviennent dans les zones de crise. Qui les finance principalement ?",
    options: [
      { id: 'a', text: "Uniquement les gouvernements des pays riches", isCorrect: false },
      { id: 'b', text: "Les dons de particuliers, des entreprises et des États", isCorrect: true },
      { id: 'c', text: "Les pays en développement eux-mêmes", isCorrect: false },
      { id: 'd', text: "L'ONU uniquement", isCorrect: false },
    ],
    correctAnswer: "Les dons de particuliers, des entreprises et des États",
    explanation: "Les ONG humanitaires comme la Croix-Rouge ou MSF sont financées par des dons de citoyens, d'entreprises et de gouvernements. Elles interviennent lors de guerres, catastrophes naturelles ou épidémies.",
    hint: "ONG humanitaires = financées par dons (particuliers + entreprises + États).",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-mhab-020',
    subject: 'histoire_geo',
    title: "Les zones protégées",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'developpement_durable',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les parcs naturels nationaux sont des zones protégées. Quel est leur principal objectif ?",
    options: [
      { id: 'a', text: "Accueillir le maximum de touristes possible", isCorrect: false },
      { id: 'b', text: "Protéger la biodiversité, les paysages et les espèces sauvages", isCorrect: true },
      { id: 'c', text: "Permettre l'exploitation agricole intensive des terres", isCorrect: false },
      { id: 'd', text: "Créer des zones sans aucun être humain", isCorrect: false },
    ],
    correctAnswer: "Protéger la biodiversité, les paysages et les espèces sauvages",
    explanation: "Les parcs naturels nationaux (ex. Vanoise, Mercantour, Cévennes) protègent des milieux naturels et leur biodiversité. Des activités humaines y sont réglementées pour préserver les écosystèmes.",
    hint: "Parc naturel national = protection biodiversité + paysages + espèces.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
