import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm2GeoSeDeplacerExercises: HgExercise[] = [

  {
    id: 'hg-cm2-geo-dep-001',
    subject: 'histoire_geo',
    title: 'Les moyens de transport',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'se_deplacer',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pour aller de Paris à Marseille rapidement, quel moyen de transport est le plus utilisé en France ?',
    options: [
      { id: 'a', text: 'Le bateau', isCorrect: false },
      { id: 'b', text: 'Le TGV (train à grande vitesse)', isCorrect: true },
      { id: 'c', text: 'La calèche', isCorrect: false },
      { id: 'd', text: 'Le vélo', isCorrect: false },
    ],
    correctAnswer: 'Le TGV (train à grande vitesse)',
    explanation: 'Le TGV relie Paris à Marseille en environ 3 heures. C\'est un moyen de transport rapide et largement utilisé en France.',
    hint: 'Ce train peut rouler à plus de 300 km/h.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-002',
    subject: 'histoire_geo',
    title: 'Les aéroports',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'geographie',
    subskill: 'se_deplacer',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le plus grand aéroport de France, situé au nord de Paris ?',
    options: [
      { id: 'a', text: 'Aéroport de Lyon-Saint-Exupéry', isCorrect: false },
      { id: 'b', text: 'Aéroport de Paris-Charles-de-Gaulle', isCorrect: true },
      { id: 'c', text: 'Aéroport de Nice-Côte d\'Azur', isCorrect: false },
      { id: 'd', text: 'Aéroport de Marseille-Provence', isCorrect: false },
    ],
    correctAnswer: 'Aéroport de Paris-Charles-de-Gaulle',
    explanation: 'L\'aéroport Paris-Charles-de-Gaulle, à Roissy, est le plus grand de France et l\'un des plus importants d\'Europe.',
    hint: 'Il porte le nom d\'un célèbre général français.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-003',
    subject: 'histoire_geo',
    title: 'Le transport maritime',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'se_deplacer',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les marchandises (téléphones, vêtements, nourriture) voyagent souvent à travers le monde par la mer. Quel type de bateau transporte ces grandes quantités ?',
    options: [
      { id: 'a', text: 'Un voilier', isCorrect: false },
      { id: 'b', text: 'Un bateau de croisière', isCorrect: false },
      { id: 'c', text: 'Un porte-conteneurs', isCorrect: true },
      { id: 'd', text: 'Une pirogue', isCorrect: false },
    ],
    correctAnswer: 'Un porte-conteneurs',
    explanation: 'Les porte-conteneurs sont d\'immenses navires qui transportent des milliers de boîtes métalliques (conteneurs) remplies de marchandises du monde entier.',
    hint: 'Ces navires transportent des grandes boîtes métalliques empilées.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-004',
    subject: 'histoire_geo',
    title: 'Le tunnel sous la Manche',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'se_deplacer',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le tunnel sous la Manche relie la France à quel autre pays ?',
    options: [
      { id: 'a', text: 'La Belgique', isCorrect: false },
      { id: 'b', text: 'Le Royaume-Uni', isCorrect: true },
      { id: 'c', text: 'L\'Espagne', isCorrect: false },
      { id: 'd', text: 'L\'Allemagne', isCorrect: false },
    ],
    correctAnswer: 'Le Royaume-Uni',
    explanation: 'Le tunnel sous la Manche, ouvert en 1994, relie Calais (France) à Folkestone (Angleterre). L\'Eurostar y circule.',
    hint: 'Ce pays est une île séparée de la France par la Manche.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-005',
    subject: 'histoire_geo',
    title: 'Les transports en commun en ville',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'geographie',
    subskill: 'se_deplacer',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est l\'avantage principal des transports en commun (bus, métro, tramway) par rapport à la voiture individuelle ?',
    options: [
      { id: 'a', text: 'Ils sont plus lents que la voiture', isCorrect: false },
      { id: 'b', text: 'Ils transportent beaucoup de personnes à la fois, réduisant ainsi la pollution', isCorrect: true },
      { id: 'c', text: 'Ils coûtent plus cher que la voiture', isCorrect: false },
      { id: 'd', text: 'Ils ne fonctionnent qu\'en été', isCorrect: false },
    ],
    correctAnswer: 'Ils transportent beaucoup de personnes à la fois, réduisant ainsi la pollution',
    explanation: 'Un bus peut transporter 80 personnes, ce qui réduit le nombre de voitures en circulation et donc la pollution et les embouteillages.',
    hint: 'Un seul véhicule peut remplacer des dizaines de voitures.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-006',
    subject: 'histoire_geo',
    title: 'La mondialisation des échanges',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'se_deplacer',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Aujourd\'hui, les produits que nous consommons viennent souvent de pays très lointains. Comment appelle-t-on ce phénomène d\'échanges à l\'échelle du monde ?',
    options: [
      { id: 'a', text: 'Le localisme', isCorrect: false },
      { id: 'b', text: 'La mondialisation', isCorrect: true },
      { id: 'c', text: 'L\'autarcie', isCorrect: false },
      { id: 'd', text: 'Le régionalisme', isCorrect: false },
    ],
    correctAnswer: 'La mondialisation',
    explanation: 'La mondialisation désigne le développement des échanges de marchandises, de personnes et d\'informations à l\'échelle planétaire.',
    hint: 'Ce mot contient le mot "monde".',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-007',
    subject: 'histoire_geo',
    title: "Le réseau LGV en France",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "LGV signifie « Ligne à Grande Vitesse ». Quel est l'avantage principal des LGV en France ?",
    options: [
      { id: 'a', text: "Elles transportent des marchandises plus vite que les camions", isCorrect: false },
      { id: 'b', text: "Elles permettent de relier les grandes villes très rapidement, concurrençant l'avion", isCorrect: true },
      { id: 'c', text: "Elles remplacent les autoroutes pour les voitures", isCorrect: false },
      { id: 'd', text: "Elles sont moins chères que le train ordinaire", isCorrect: false },
    ],
    correctAnswer: "Elles permettent de relier les grandes villes très rapidement, concurrençant l'avion",
    explanation: "Les LGV permettent au TGV de rouler à plus de 300 km/h. Paris-Lyon prend 2h, Paris-Bordeaux 2h05. Elles réduisent la durée des trajets et rivalisent avec l'avion sur des distances moyennes.",
    hint: "LGV + TGV = train très rapide → concurrence l'avion en France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-008',
    subject: 'histoire_geo',
    title: "Les mobilités douces",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'mobilites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Lesquels de ces transports font partie des « mobilités douces » ?",
    options: [
      { id: 'a', text: "L'avion et le bateau à moteur", isCorrect: false },
      { id: 'b', text: "Le vélo, la marche à pied et la trottinette", isCorrect: true },
      { id: 'c', text: "La voiture hybride et le bus diesel", isCorrect: false },
      { id: 'd', text: "Le TGV et le métro", isCorrect: false },
    ],
    correctAnswer: "Le vélo, la marche à pied et la trottinette",
    explanation: "Les mobilités douces (ou actives) désignent les déplacements sans moteur thermique, propulsés par l'effort humain : vélo, marche, trottinette. Elles ne polluent pas et bénéficient à la santé.",
    hint: "Doux = sans moteur thermique, propulsé par l'effort humain.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-009',
    subject: 'histoire_geo',
    title: "Le covoiturage",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'mobilites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le covoiturage consiste à partager sa voiture avec d'autres personnes faisant le même trajet. Quel avantage principal présente-t-il ?",
    options: [
      { id: 'a', text: "Il permet d'aller plus vite que seul", isCorrect: false },
      { id: 'b', text: "Il réduit le nombre de voitures sur les routes et divise les coûts et les émissions de CO₂", isCorrect: true },
      { id: 'c', text: "Il est subventionné par l'État et donc gratuit", isCorrect: false },
      { id: 'd', text: "Il remplace les transports en commun", isCorrect: false },
    ],
    correctAnswer: "Il réduit le nombre de voitures sur les routes et divise les coûts et les émissions de CO₂",
    explanation: "Le covoiturage permet de partager les frais et de réduire l'impact environnemental. 4 personnes dans 1 voiture = 4 fois moins d'émissions de CO₂ par personne que 4 voitures séparées.",
    hint: "Covoiturage = moins de voitures = moins de CO₂ = moins de coût.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-010',
    subject: 'histoire_geo',
    title: "L'Eurostar",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_europeens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "L'Eurostar est un train international passant sous la Manche. Quelles villes relie-t-il principalement ?",
    options: [
      { id: 'a', text: "Paris et Berlin", isCorrect: false },
      { id: 'b', text: "Paris et Londres", isCorrect: true },
      { id: 'c', text: "Paris et Bruxelles uniquement", isCorrect: false },
      { id: 'd', text: "Calais et Douvres en voiture", isCorrect: false },
    ],
    correctAnswer: "Paris et Londres",
    explanation: "L'Eurostar relie Paris à Londres via le tunnel sous la Manche (Eurotunnel) en environ 2h15. Il passe aussi par Bruxelles. La traversée du tunnel dure environ 25 minutes.",
    hint: "Eurostar = Paris → tunnel sous la Manche → Londres.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-011',
    subject: 'histoire_geo',
    title: "Empreinte CO₂ par mode de transport",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'mobilites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel mode de transport émet le plus de CO₂ par kilomètre et par voyageur ?",
    options: [
      { id: 'a', text: "Le train", isCorrect: false },
      { id: 'b', text: "L'avion", isCorrect: true },
      { id: 'c', text: "Le bus", isCorrect: false },
      { id: 'd', text: "Le vélo", isCorrect: false },
    ],
    correctAnswer: "L'avion",
    explanation: "L'avion est le mode de transport le plus émetteur de CO₂ par km/voyageur. Le train électrique est le moins polluant. L'ordre approximatif : avion > voiture > bus > train > vélo (0).",
    hint: "CO₂ : avion > voiture > bus > train. Le vélo = 0.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-012',
    subject: 'histoire_geo',
    title: "Le véhicule électrique",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'mobilites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La voiture électrique est-elle toujours 100 % propre ?",
    options: [
      { id: 'a', text: "Oui, elle ne produit aucune pollution", isCorrect: false },
      { id: 'b', text: "Non, la fabrication de sa batterie et l'électricité utilisée peuvent polluer", isCorrect: true },
      { id: 'c', text: "Oui, car son moteur est silencieux", isCorrect: false },
      { id: 'd', text: "Non, elle consomme autant de pétrole qu'une voiture essence", isCorrect: false },
    ],
    correctAnswer: "Non, la fabrication de sa batterie et l'électricité utilisée peuvent polluer",
    explanation: "La voiture électrique ne rejette pas de gaz d'échappement, mais sa batterie (lithium, cobalt) nécessite une extraction minière polluante. Son bilan dépend aussi de la source d'électricité utilisée.",
    hint: "Voiture électrique = moins de CO₂ à l'usage, mais fabrication de batterie polluante.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-013',
    subject: 'histoire_geo',
    title: "Les grands ports mondiaux",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transport_maritime',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Plus de 80 % des marchandises mondiales sont transportées par mer. Quel type de navire est le plus utilisé pour ce commerce ?",
    options: [
      { id: 'a', text: "Les paquebots de croisière", isCorrect: false },
      { id: 'b', text: "Les porte-conteneurs", isCorrect: true },
      { id: 'c', text: "Les sous-marins cargo", isCorrect: false },
      { id: 'd', text: "Les canots pneumatiques motorisés", isCorrect: false },
    ],
    correctAnswer: "Les porte-conteneurs",
    explanation: "Les porte-conteneurs transportent des marchandises dans des boîtes métalliques standardisées (conteneurs de 20 ou 40 pieds). Ils permettent une manutention rapide dans les grands ports mondiaux.",
    hint: "Commerce maritime mondial = porte-conteneurs = boîtes métalliques standardisées.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-014',
    subject: 'histoire_geo',
    title: "Métro, tramway et RER",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_urbains',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quelle est la différence principale entre le métro et le tramway ?",
    options: [
      { id: 'a', text: "Le métro est plus lent que le tramway", isCorrect: false },
      { id: 'b', text: "Le métro circule principalement sous terre ou sur voies séparées ; le tramway circule en surface dans les rues", isCorrect: true },
      { id: 'c', text: "Le tramway peut circuler à grande vitesse (300 km/h)", isCorrect: false },
      { id: 'd', text: "Le métro n'existe qu'à Paris", isCorrect: false },
    ],
    correctAnswer: "Le métro circule principalement sous terre ou sur voies séparées ; le tramway circule en surface dans les rues",
    explanation: "Le métro circule sur des voies séparées (souvent souterraines) sans croiser la circulation. Le tramway circule sur des rails en surface, généralement en milieu urbain, et partage parfois la chaussée.",
    hint: "Métro = sous terre ou séparé. Tramway = en surface dans la rue.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-015',
    subject: 'histoire_geo',
    title: "Les autoroutes françaises",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, la plupart des autoroutes sont à péage. À quoi servent principalement ces péages ?",
    options: [
      { id: 'a', text: "À financer le fonctionnement de la SNCF", isCorrect: false },
      { id: 'b', text: "À financer la construction, l'entretien et l'exploitation des autoroutes", isCorrect: true },
      { id: 'c', text: "À financer les aides aux agriculteurs", isCorrect: false },
      { id: 'd', text: "À payer les policiers qui font respecter le Code de la route", isCorrect: false },
    ],
    correctAnswer: "À financer la construction, l'entretien et l'exploitation des autoroutes",
    explanation: "Les péages d'autoroute financent principalement la construction et l'entretien du réseau autoroutier. En France, la grande majorité des autoroutes sont concédées à des sociétés privées.",
    hint: "Péage autoroute = payer pour financer l'entretien et la construction de la route.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-016',
    subject: 'histoire_geo',
    title: "La fracture des mobilités",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'mobilites',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En France, certaines personnes vivant loin des villes ont du mal à se déplacer. Pour quelle raison principale ?",
    options: [
      { id: 'a', text: "Il n'y a pas d'essence dans les villages", isCorrect: false },
      { id: 'b', text: "Les transports en commun sont rares en milieu rural, rendant la voiture indispensable", isCorrect: true },
      { id: 'c', text: "Les routes de campagne sont trop mauvaises", isCorrect: false },
      { id: 'd', text: "L'État interdit les voitures en dehors des villes", isCorrect: false },
    ],
    correctAnswer: "Les transports en commun sont rares en milieu rural, rendant la voiture indispensable",
    explanation: "Les zones rurales et périurbaines sont souvent mal desservies par les transports en commun. Les habitants sans voiture ou ne pouvant pas conduire (âgés, jeunes, personnes à mobilité réduite) peuvent être isolés.",
    hint: "Rural = peu de transports communs → voiture obligatoire → ceux sans voiture isolés.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-017',
    subject: 'histoire_geo',
    title: "Le transport aérien et le low-cost",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les compagnies aériennes « low-cost » ont démocratisé le voyage en avion. Que signifie « low-cost » ?",
    options: [
      { id: 'a', text: "Vol lent (vitesse réduite)", isCorrect: false },
      { id: 'b', text: "Vol à bas prix, avec des services réduits", isCorrect: true },
      { id: 'c', text: "Vol long-courrier intercontinental", isCorrect: false },
      { id: 'd', text: "Vol à haute altitude uniquement", isCorrect: false },
    ],
    correctAnswer: "Vol à bas prix, avec des services réduits",
    explanation: "Low-cost (anglais) = faible coût. Les compagnies low-cost proposent des billets moins chers en réduisant les services (pas de repas inclus, frais pour bagages). Elles ont augmenté le trafic aérien mais aussi les émissions de CO₂.",
    hint: "Low-cost = faible coût = moins cher mais avec moins de services.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-018',
    subject: 'histoire_geo',
    title: "Le tunnel sous la Manche",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_europeens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le tunnel sous la Manche (Eurotunnel) relie la France et le Royaume-Uni. Quelle est sa longueur approximative ?",
    options: [
      { id: 'a', text: "Environ 5 km", isCorrect: false },
      { id: 'b', text: "Environ 50 km", isCorrect: true },
      { id: 'c', text: "Environ 200 km", isCorrect: false },
      { id: 'd', text: "Environ 500 km", isCorrect: false },
    ],
    correctAnswer: "Environ 50 km",
    explanation: "L'Eurotunnel mesure 50,5 km (dont 38 km sous la mer). Il relie Coquelles (près de Calais) à Folkestone (Angleterre). Il a été inauguré en 1994.",
    hint: "Tunnel sous la Manche ≈ 50 km dont 38 km sous la mer. Inauguration 1994.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-019',
    subject: 'histoire_geo',
    title: "Les navettes spatiales",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_futurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La Station spatiale internationale (ISS) est un laboratoire en orbite à environ 400 km de la Terre. Comment les astronautes y accèdent-ils ?",
    options: [
      { id: 'a', text: "Par hélicoptère à très longue portée", isCorrect: false },
      { id: 'b', text: "Par fusée ou capsule spatiale (ex. Soyouz, SpaceX Crew Dragon)", isCorrect: true },
      { id: 'c', text: "Par ascenseur spatial", isCorrect: false },
      { id: 'd', text: "Par avion supersonique", isCorrect: false },
    ],
    correctAnswer: "Par fusée ou capsule spatiale (ex. Soyouz, SpaceX Crew Dragon)",
    explanation: "Les astronautes rejoignent l'ISS via des capsules spatiales lancées par des fusées. Après le retrait des navettes américaines (2011), la Russie (Soyouz) assura les rotations, puis SpaceX (Crew Dragon) depuis 2020.",
    hint: "ISS = 400 km de altitude → accessible uniquement par fusée/capsule spatiale.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-geo-dep-020',
    subject: 'histoire_geo',
    title: "Les ports français",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'transports_france',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Quel est le premier port français en termes de trafic de marchandises ?",
    options: [
      { id: 'a', text: "Marseille", isCorrect: false },
      { id: 'b', text: "Le Havre", isCorrect: true },
      { id: 'c', text: "Bordeaux", isCorrect: false },
      { id: 'd', text: "Dunkerque", isCorrect: false },
    ],
    correctAnswer: "Le Havre",
    explanation: "Le Havre est le premier port à conteneurs français et l'un des plus importants d'Europe du Nord. Il est situé à l'embouchure de la Seine et est essentiel pour le commerce international de la France.",
    hint: "Le Havre = 1er port français pour les conteneurs et marchandises.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
