import type { HgExercise } from '../hg.types';
import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';

const A = cloneDefaultAdaptations();

export const hgCm2HistoireVieQuotidienneExercises: HgExercise[] = [
  {
    id: 'hg-cm2-hist-vq-001',
    subject: 'histoire_geo',
    title: 'La vie sous l\'Ancien Régime',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle était la principale source de revenus de la noblesse sous l\'Ancien Régime ?',
    options: [
      { id: 'a', text: 'Le commerce maritime avec les colonies', isCorrect: false },
      { id: 'b', text: 'Les droits perçus sur les paysans (seigneuriage) et les revenus des terres', isCorrect: true },
      { id: 'c', text: 'La fabrication et la vente d\'armes', isCorrect: false },
      { id: 'd', text: 'Le travail dans les manufactures du roi', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Sous l\'Ancien Régime, la noblesse tirait ses revenus de ses terres et des droits seigneuriaux prélevés sur les paysans (redevances, banalités, corvées). La noblesse ne payait pas d\'impôts.',
    hint: 'Les seigneurs possédaient des terres cultivées par des paysans.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-002',
    subject: 'histoire_geo',
    title: 'La vie paysanne au XIXe siècle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle innovation a profondément changé la vie des paysans français au XIXe siècle ?',
    options: [
      { id: 'a', text: 'L\'invention de l\'électricité', isCorrect: false },
      { id: 'b', text: 'L\'arrivée du chemin de fer qui a désenclavé les campagnes', isCorrect: true },
      { id: 'c', text: 'La construction de grands canaux d\'irrigation', isCorrect: false },
      { id: 'd', text: 'L\'invention du tracteur à vapeur', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le développement du réseau ferroviaire à partir des années 1840 a profondément changé la vie rurale : les paysans pouvaient désormais vendre leurs produits dans des marchés éloignés et accéder aux villes plus facilement.',
    hint: 'Ce moyen de transport a mis en contact les campagnes isolées avec le reste du pays.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-003',
    subject: 'histoire_geo',
    title: 'Les enfants à l\'école au XIXe siècle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que les lois Jules Ferry de 1881-1882 ont instauré en France ?',
    options: [
      { id: 'a', text: 'La scolarité obligatoire jusqu\'à l\'âge de 16 ans', isCorrect: false },
      { id: 'b', text: 'L\'école primaire gratuite et laïque, et l\'instruction obligatoire de 6 à 13 ans', isCorrect: true },
      { id: 'c', text: 'La création des lycées et des baccalauréats', isCorrect: false },
      { id: 'd', text: 'Le droit à l\'école pour les filles uniquement', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les lois Jules Ferry (1881-1882) ont rendu l\'école primaire gratuite et laïque, et ont instauré l\'obligation scolaire de 6 à 13 ans. Pour la première fois, tous les enfants devaient aller à l\'école.',
    hint: 'Ces lois ont transformé l\'instruction publique en France.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-004',
    subject: 'histoire_geo',
    title: 'La vie ouvrière au XIXe siècle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle était la durée de travail habituelle d\'un ouvrier d\'usine au milieu du XIXe siècle ?',
    options: [
      { id: 'a', text: '7 à 8 heures par jour', isCorrect: false },
      { id: 'b', text: '12 à 15 heures par jour, 6 jours sur 7', isCorrect: true },
      { id: 'c', text: '5 jours sur 7 avec des week-ends libres', isCorrect: false },
      { id: 'd', text: '10 heures par jour avec de longues pauses', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Au début de l\'ère industrielle, les ouvriers travaillaient 12 à 15 heures par jour, 6 jours sur 7, dans des conditions difficiles. Les luttes ouvrières du XIXe siècle ont progressivement réduit ce temps de travail.',
    hint: 'Les conditions de travail étaient très dures avant les premières lois sociales.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-005',
    subject: 'histoire_geo',
    title: 'La vie pendant la Grande Guerre',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel rôle les femmes ont-elles joué en France pendant la Première Guerre mondiale (1914-1918) ?',
    options: [
      { id: 'a', text: 'Elles ont combattu dans les tranchées aux côtés des soldats', isCorrect: false },
      { id: 'b', text: 'Elles ont remplacé les hommes partis au front dans les usines, les champs et les services', isCorrect: true },
      { id: 'c', text: 'Elles ont été évacuées à l\'étranger pour leur sécurité', isCorrect: false },
      { id: 'd', text: 'Elles n\'ont pas eu de rôle particulier pendant ce conflit', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Avec 8 millions d\'hommes mobilisés, les femmes ont dû assurer la production industrielle (munitions, équipements), les travaux agricoles et de nombreux services, jouant un rôle essentiel dans l\'effort de guerre.',
    hint: 'Les usines et les champs devaient continuer à fonctionner sans les hommes.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-006',
    subject: 'histoire_geo',
    title: 'La vie sous l\'Occupation',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'était la carte de rationnement pendant la Seconde Guerre mondiale en France ?',
    options: [
      { id: 'a', text: 'Une carte permettant de voyager librement en zone occupée', isCorrect: false },
      { id: 'b', text: 'Un document qui limitait la quantité de nourriture et de biens que chaque personne pouvait acheter', isCorrect: true },
      { id: 'c', text: 'Une carte d\'identité spéciale pour les résistants', isCorrect: false },
      { id: 'd', text: 'Un laissez-passer pour traverser la ligne de démarcation', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Pendant l\'Occupation, les Allemands réquisitionnaient une grande partie des denrées alimentaires françaises. Les cartes de rationnement limitaient les achats de nourriture (pain, viande, sucre…) pour chaque habitant.',
    hint: 'La nourriture était rare et devait être partagée équitablement.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-007',
    subject: 'histoire_geo',
    title: 'Les Trente Glorieuses',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'appelle-t-on les « Trente Glorieuses » en France ?',
    options: [
      { id: 'a', text: 'La période de la Révolution française de 1789 à 1815', isCorrect: false },
      { id: 'b', text: 'La période de forte croissance économique et de progrès social de 1945 à 1975', isCorrect: true },
      { id: 'c', text: 'Les trente premières années de la IIIe République', isCorrect: false },
      { id: 'd', text: 'La période de colonisation française en Afrique', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les Trente Glorieuses (1945-1975) désignent la période de forte croissance économique de la France après la Seconde Guerre mondiale : plein emploi, hausse des salaires, développement de la consommation et de l\'État-providence.',
    hint: 'Cette expression désigne une époque de prospérité qui a suivi la guerre.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-008',
    subject: 'histoire_geo',
    title: 'L\'évolution du logement',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans les années 1950-1960 en France, qu\'ont représenté les HLM (Habitations à Loyer Modéré) ?',
    options: [
      { id: 'a', text: 'Des villas de luxe construites pour les classes aisées', isCorrect: false },
      { id: 'b', text: 'Des logements collectifs construits pour loger les familles ouvrières dans des appartements modernes', isCorrect: true },
      { id: 'c', text: 'Des casernes militaires reconverties en logements', isCorrect: false },
      { id: 'd', text: 'Des fermes modernisées pour accueillir les agriculteurs', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les HLM ont été construites à partir des années 1950 pour faire face à la crise du logement et offrir aux familles ouvrières des appartements avec eau courante, électricité et chauffage central.',
    hint: 'Ces grands immeubles ont permis à beaucoup de familles d\'accéder au confort moderne.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-009',
    subject: 'histoire_geo',
    title: 'L\'évolution des loisirs',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle innovation a révolutionné les loisirs à partir des années 1950 en France ?',
    options: [
      { id: 'a', text: 'L\'invention du cinéma parlant', isCorrect: false },
      { id: 'b', text: 'La télévision qui s\'est répandue dans les foyers', isCorrect: true },
      { id: 'c', text: 'L\'ouverture des premières médiathèques', isCorrect: false },
      { id: 'd', text: 'La construction de grands stades sportifs', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La télévision, qui s\'est démocratisée dans les années 1950-1960, a profondément changé les habitudes de loisirs des Français : on regardait le journal télévisé, les émissions de variétés et le football en famille.',
    hint: 'Ce grand écran dans le salon a rassemblé les familles.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-010',
    subject: 'histoire_geo',
    title: 'Les congés payés',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand les congés payés ont-ils été instaurés en France ?',
    options: [
      { id: 'a', text: 'En 1900, sous la Troisième République', isCorrect: false },
      { id: 'b', text: 'En 1936, sous le gouvernement du Front Populaire', isCorrect: true },
      { id: 'c', text: 'En 1945, à la Libération', isCorrect: false },
      { id: 'd', text: 'En 1968, après les grèves de mai', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'En 1936, le gouvernement du Front Populaire dirigé par Léon Blum a instauré deux semaines de congés payés pour les travailleurs. Pour beaucoup d\'ouvriers, c\'était la première fois qu\'ils pouvaient partir en vacances.',
    hint: 'C\'est une conquête sociale des années 30, liée au Front Populaire.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-011',
    subject: 'histoire_geo',
    title: 'L\'évolution de l\'alimentation',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle technique a permis de conserver les aliments beaucoup plus longtemps à partir du XIXe siècle ?',
    options: [
      { id: 'a', text: 'La surgélation industrielle', isCorrect: false },
      { id: 'b', text: 'La stérilisation en boîtes de conserve inventée par Nicolas Appert', isCorrect: true },
      { id: 'c', text: 'Le séchage au soleil traditionnel', isCorrect: false },
      { id: 'd', text: 'Le fumage dans des cheminées spéciales', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Nicolas Appert a inventé la technique de la conserve (appertisation) au début du XIXe siècle : chauffer les aliments dans des bocaux hermétiques permet de les conserver pendant des mois.',
    hint: 'Cette technique porte le nom de son inventeur français.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-012',
    subject: 'histoire_geo',
    title: 'Les progrès médicaux au XXe siècle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle découverte médicale du XXe siècle a sauvé des millions de vies en permettant de traiter les infections ?',
    options: [
      { id: 'a', text: 'La découverte de l\'aspirine par Bayer', isCorrect: false },
      { id: 'b', text: 'La découverte de la pénicilline (premier antibiotique) par Alexander Fleming en 1928', isCorrect: true },
      { id: 'c', text: 'L\'invention de la radiographie par Röntgen', isCorrect: false },
      { id: 'd', text: 'La création du premier vaccin contre la tuberculose', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Alexander Fleming a découvert la pénicilline en 1928, le premier antibiotique. Utilisée à grande échelle à partir de 1945, elle a permis de traiter des infections autrefois mortelles (pneumonie, gangrène…).',
    hint: 'Ce médecin écossais a observé une moisissure qui tuait des bactéries.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-013',
    subject: 'histoire_geo',
    title: 'L\'émancipation des femmes au XXe siècle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle année les femmes françaises ont-elles obtenu le droit de vote ?',
    options: [
      { id: 'a', text: 'En 1918, à la fin de la Première Guerre mondiale', isCorrect: false },
      { id: 'b', text: 'En 1944, à la Libération', isCorrect: true },
      { id: 'c', text: 'En 1936, sous le Front Populaire', isCorrect: false },
      { id: 'd', text: 'En 1958, avec la Ve République', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les femmes françaises ont obtenu le droit de vote en 1944 par une ordonnance du gouvernement provisoire du général de Gaulle. Elles ont exercé ce droit pour la première fois aux élections municipales d\'avril 1945.',
    hint: 'C\'est à la fin de la Seconde Guerre mondiale.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-014',
    subject: 'histoire_geo',
    title: 'La Sécurité sociale',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand la Sécurité sociale a-t-elle été créée en France ?',
    options: [
      { id: 'a', text: 'En 1900, sous la Troisième République', isCorrect: false },
      { id: 'b', text: 'En 1945, après la Libération', isCorrect: true },
      { id: 'c', text: 'En 1936, pendant le Front Populaire', isCorrect: false },
      { id: 'd', text: 'En 1968, après les grèves', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La Sécurité sociale a été créée en octobre 1945, à la Libération. Elle garantit à tous les Français une protection contre les risques de maladie, d\'accident, de vieillesse et de maternité.',
    hint: 'Cette institution protège les Français depuis la fin de la Seconde Guerre mondiale.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-vq-015',
    subject: 'histoire_geo',
    title: 'La révolution numérique',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'vie quotidienne à travers les époques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quoi Internet a-t-il transformé la vie quotidienne depuis les années 1990-2000 ?',
    options: [
      { id: 'a', text: 'Il a uniquement permis d\'envoyer des courriers électroniques', isCorrect: false },
      { id: 'b', text: 'Il a bouleversé les communications, le commerce, l\'information et les loisirs à l\'échelle mondiale', isCorrect: true },
      { id: 'c', text: 'Il a surtout profité aux pays pauvres', isCorrect: false },
      { id: 'd', text: 'Il a remplacé uniquement la télévision', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Internet a profondément transformé la vie quotidienne : communications instantanées mondiales, commerce en ligne, accès immédiat à l\'information, streaming, réseaux sociaux… Cette révolution est comparable à celle de l\'imprimerie.',
    hint: 'Pense à tout ce qu\'on ne pouvait pas faire avant Internet.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
