import type { HgExercise } from '../hg.types';
import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';

const A = cloneDefaultAdaptations();

export const hgCm2GeoMondeFluxExercises: HgExercise[] = [
  {
    id: 'hg-cm2-geo-flx-001',
    subject: 'histoire_geo',
    title: 'La mondialisation des échanges',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel phénomène a le plus favorisé le développement des échanges mondiaux au XXe siècle ?',
    options: [
      { id: 'a', text: 'La disparition des monnaies nationales', isCorrect: false },
      { id: 'b', text: 'La baisse des coûts de transport et de communication grâce aux innovations technologiques', isCorrect: true },
      { id: 'c', text: 'La création d\'un gouvernement mondial', isCorrect: false },
      { id: 'd', text: 'L\'unification des langues utilisées dans le commerce', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La baisse des coûts des transports maritimes (conteneurisation) et la révolution d\'Internet ont permis d\'échanger marchandises et informations à l\'échelle mondiale à des coûts très bas, accélérant la mondialisation.',
    hint: 'Transporter moins cher et communiquer instantanément : les deux clés.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-002',
    subject: 'histoire_geo',
    title: 'Les migrations internationales',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelles sont les principales raisons qui poussent des personnes à migrer vers un autre pays ?',
    options: [
      { id: 'a', text: 'Uniquement pour trouver un emploi mieux payé', isCorrect: false },
      { id: 'b', text: 'Des raisons économiques (emploi, pauvreté), politiques (guerre, persécutions) ou climatiques (catastrophes)', isCorrect: true },
      { id: 'c', text: 'Uniquement pour fuir les guerres', isCorrect: false },
      { id: 'd', text: 'Pour suivre des études supérieures uniquement', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les migrations s\'expliquent par des facteurs multiples : économiques (chercher un emploi), politiques (fuir une guerre ou des persécutions) ou climatiques (catastrophes naturelles). Ces raisons se combinent souvent.',
    hint: 'On ne quitte pas facilement son pays — il faut une raison forte.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-003',
    subject: 'histoire_geo',
    title: 'Les réfugiés',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un réfugié au sens du droit international ?',
    options: [
      { id: 'a', text: 'Toute personne qui quitte son pays pour trouver du travail', isCorrect: false },
      { id: 'b', text: 'Une personne qui a fui son pays en raison de persécutions et qui ne peut pas y retourner en sécurité', isCorrect: true },
      { id: 'c', text: 'Un touriste qui reste plus de 3 mois dans un autre pays', isCorrect: false },
      { id: 'd', text: 'Un étudiant qui part faire ses études à l\'étranger', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Selon la Convention de Genève (1951), un réfugié est une personne qui a fui son pays en raison de persécutions (pour sa race, sa religion, sa nationalité ou ses opinions politiques) et qui bénéficie d\'une protection internationale.',
    hint: 'Ce statut est défini par une convention internationale de 1951.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-004',
    subject: 'histoire_geo',
    title: 'Le UNHCR',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel organisme de l\'ONU est chargé de protéger les réfugiés dans le monde ?',
    options: [
      { id: 'a', text: 'L\'UNICEF', isCorrect: false },
      { id: 'b', text: 'Le HCR (Haut Commissariat pour les Réfugiés)', isCorrect: true },
      { id: 'c', text: 'L\'UNESCO', isCorrect: false },
      { id: 'd', text: 'L\'OMS (Organisation mondiale de la santé)', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le HCR (ou UNHCR en anglais), créé en 1950, est l\'agence de l\'ONU chargée de protéger les réfugiés et les personnes déplacées dans le monde entier et de trouver des solutions durables à leur situation.',
    hint: 'Cette agence de l\'ONU aide spécifiquement les personnes forcées de fuir.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-005',
    subject: 'histoire_geo',
    title: 'Les flux financiers',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que les « transferts de fonds » des migrants ?',
    options: [
      { id: 'a', text: 'L\'argent que les gouvernements envoient aux pays pauvres', isCorrect: false },
      { id: 'b', text: 'L\'argent que les migrants envoient à leur famille restée dans leur pays d\'origine', isCorrect: true },
      { id: 'c', text: 'Les impôts payés par les entreprises multinationales', isCorrect: false },
      { id: 'd', text: 'Les profits des banques internationales', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les transferts de fonds des migrants (remittances) sont l\'argent envoyé par les travailleurs émigrés à leur famille dans leur pays d\'origine. Ces flux représentent des montants supérieurs à l\'aide publique au développement.',
    hint: 'Un migrant travaillant à l\'étranger aide souvent financièrement sa famille.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-006',
    subject: 'histoire_geo',
    title: 'Les flux de marchandises',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Entre quelles zones du monde s\'effectuent les échanges commerciaux les plus importants ?',
    options: [
      { id: 'a', text: 'Entre l\'Afrique et l\'Amérique du Sud', isCorrect: false },
      { id: 'b', text: 'Entre l\'Asie, l\'Europe et l\'Amérique du Nord (la « triade »)', isCorrect: true },
      { id: 'c', text: 'Entre l\'Océanie et l\'Asie uniquement', isCorrect: false },
      { id: 'd', text: 'Entre les pays de l\'OPEP et l\'Europe', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La majeure partie du commerce mondial s\'effectue entre les trois pôles de la « triade » : l\'Asie de l\'Est (Chine, Japon, Corée), l\'Europe et l\'Amérique du Nord. Ces régions concentrent aussi la richesse mondiale.',
    hint: 'Ce sont les trois régions les plus industrialisées et riches du monde.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-007',
    subject: 'histoire_geo',
    title: 'Internet et les flux d\'informations',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle infrastructure permet à Internet de relier les continents à très grande vitesse ?',
    options: [
      { id: 'a', text: 'Des satellites géostationnaires uniquement', isCorrect: false },
      { id: 'b', text: 'Un réseau de câbles sous-marins en fibre optique qui relient les continents', isCorrect: true },
      { id: 'c', text: 'Des antennes radio installées sur des îles', isCorrect: false },
      { id: 'd', text: 'Des avions relais qui transmettent les données', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La majorité des données Internet (plus de 95 %) transitent par des câbles sous-marins en fibre optique qui relient les continents. Il en existe plus de 400 dans le monde, pour une longueur totale de plus d\'1 million de km.',
    hint: 'Des câbles au fond des océans relient les continents.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-008',
    subject: 'histoire_geo',
    title: 'La fracture numérique',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'appelle-t-on la « fracture numérique » ?',
    options: [
      { id: 'a', text: 'La panne d\'Internet qui touche parfois certaines régions', isCorrect: false },
      { id: 'b', text: 'Les inégalités d\'accès aux technologies numériques (Internet, ordinateurs) entre pays riches et pays pauvres', isCorrect: true },
      { id: 'c', text: 'La différence de vitesse entre Internet mobile et Internet fixe', isCorrect: false },
      { id: 'd', text: 'Le fossé entre les jeunes qui maîtrisent le numérique et les personnes âgées', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La fracture numérique désigne les inégalités d\'accès aux outils numériques (Internet, smartphones, ordinateurs) entre pays développés et pays en développement, mais aussi entre zones urbaines et rurales.',
    hint: 'Pas tout le monde sur Terre a accès à Internet.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-009',
    subject: 'histoire_geo',
    title: 'Les flux touristiques mondiaux',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel continent reçoit le plus de touristes internationaux dans le monde ?',
    options: [
      { id: 'a', text: 'L\'Amérique du Nord', isCorrect: false },
      { id: 'b', text: 'L\'Europe', isCorrect: true },
      { id: 'c', text: 'L\'Asie', isCorrect: false },
      { id: 'd', text: 'L\'Afrique', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'Europe est le continent le plus visité au monde, recevant environ la moitié des touristes internationaux. La France, l\'Espagne et l\'Italie sont parmi les destinations les plus prisées.',
    hint: 'C\'est le continent le plus visité, avec la France en tête mondiale.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-010',
    subject: 'histoire_geo',
    title: 'Les multinationales',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une entreprise multinationale ?',
    options: [
      { id: 'a', text: 'Une entreprise dont les produits sont vendus dans plusieurs pays', isCorrect: false },
      { id: 'b', text: 'Une entreprise qui possède des usines ou des filiales dans plusieurs pays différents', isCorrect: true },
      { id: 'c', text: 'Une entreprise dont le capital appartient à plusieurs États', isCorrect: false },
      { id: 'd', text: 'Une entreprise qui emploie des travailleurs de plusieurs nationalités', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Une entreprise multinationale est une société qui a des sites de production, des filiales ou des bureaux dans plusieurs pays. Elle organise ses activités à l\'échelle mondiale pour réduire ses coûts et accéder à plus de marchés.',
    hint: 'Multi = plusieurs, nationale = pays : présente dans plusieurs pays.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-011',
    subject: 'histoire_geo',
    title: 'Le commerce international',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel organisme international régule le commerce mondial ?',
    options: [
      { id: 'a', text: 'Le FMI (Fonds monétaire international)', isCorrect: false },
      { id: 'b', text: 'L\'OMC (Organisation mondiale du commerce)', isCorrect: true },
      { id: 'c', text: 'La Banque mondiale', isCorrect: false },
      { id: 'd', text: 'L\'OCDE (Organisation de coopération et de développement économiques)', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'OMC (Organisation mondiale du commerce), créée en 1995, établit les règles du commerce international entre les pays et tente de faciliter les échanges en réduisant les barrières douanières.',
    hint: 'Cet organisme crée les règles des échanges commerciaux entre pays.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-012',
    subject: 'histoire_geo',
    title: 'Les routes maritimes',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel passage maritime relie l\'océan Atlantique et l\'océan Pacifique en Amérique centrale ?',
    options: [
      { id: 'a', text: 'Le canal de Suez', isCorrect: false },
      { id: 'b', text: 'Le canal de Panama', isCorrect: true },
      { id: 'c', text: 'Le détroit de Magellan', isCorrect: false },
      { id: 'd', text: 'Le détroit de Gibraltar', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le canal de Panama (ouvert en 1914, agrandi en 2016) traverse l\'isthme de Panama en Amérique centrale et relie l\'Atlantique au Pacifique, évitant aux navires le long contournement de l\'Amérique du Sud.',
    hint: 'Ce canal se trouve en Amérique centrale.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-013',
    subject: 'histoire_geo',
    title: 'Les flux d\'énergie',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment le pétrole est-il principalement transporté à travers le monde ?',
    options: [
      { id: 'a', text: 'Par des camions-citernes sur les routes internationales', isCorrect: false },
      { id: 'b', text: 'Par des navires pétroliers (tankers) et des oléoducs (pipelines)', isCorrect: true },
      { id: 'c', text: 'Par des trains à travers les continents', isCorrect: false },
      { id: 'd', text: 'Par des avions cargo spécialement équipés', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le pétrole brut est transporté par des pétroliers géants (supertankers) sur les mers, puis par des oléoducs (pipelines) sur terre. Ces infrastructures forment un réseau mondial d\'approvisionnement en énergie.',
    hint: 'Ces grands navires noirs transportent le brut d\'un continent à l\'autre.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-014',
    subject: 'histoire_geo',
    title: 'Les ONG et l\'aide humanitaire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une ONG (Organisation Non Gouvernementale) ?',
    options: [
      { id: 'a', text: 'Une organisation créée par les gouvernements pour gérer l\'aide étrangère', isCorrect: false },
      { id: 'b', text: 'Une association indépendante des gouvernements qui agit pour des causes humanitaires, sociales ou environnementales', isCorrect: true },
      { id: 'c', text: 'Une entreprise internationale qui vend des produits dans plusieurs pays', isCorrect: false },
      { id: 'd', text: 'Une organisation qui regroupe les Nations Unies', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Une ONG est une association privée, indépendante des gouvernements, qui agit pour des causes d\'intérêt général : aide humanitaire (Médecins Sans Frontières), défense des droits humains (Amnesty), environnement (Greenpeace)…',
    hint: 'Non Gouvernementale = indépendante des États.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-flx-015',
    subject: 'histoire_geo',
    title: 'Les inégalités de développement',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'flux mondiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on l\'indicateur qui mesure le niveau de vie d\'un pays en tenant compte du revenu, de l\'espérance de vie et de l\'éducation ?',
    options: [
      { id: 'a', text: 'Le PIB (Produit Intérieur Brut)', isCorrect: false },
      { id: 'b', text: 'L\'IDH (Indice de Développement Humain)', isCorrect: true },
      { id: 'c', text: 'L\'IPC (Indice des Prix à la Consommation)', isCorrect: false },
      { id: 'd', text: 'Le taux de chômage', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'IDH (Indice de Développement Humain) est un indicateur créé par l\'ONU qui combine trois dimensions : le revenu par habitant, l\'espérance de vie et le niveau d\'éducation. Il permet de comparer le développement des pays.',
    hint: 'Cet indice dépasse le seul critère économique pour mesurer le bien-être.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
