import type { HgExercise } from '../hg.types';
import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';

const A = cloneDefaultAdaptations();

export const hgCm2HistoireMemoiresExercises: HgExercise[] = [
  {
    id: 'hg-cm2-hist-mem-001',
    subject: 'histoire_geo',
    title: 'La mémoire et l\'histoire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la différence entre la mémoire et l\'histoire ?',
    options: [
      { id: 'a', text: 'La mémoire et l\'histoire sont exactement la même chose', isCorrect: false },
      { id: 'b', text: 'La mémoire est le souvenir vécu ou transmis ; l\'histoire est l\'étude scientifique et critique du passé', isCorrect: true },
      { id: 'c', text: 'L\'histoire est plus ancienne que la mémoire', isCorrect: false },
      { id: 'd', text: 'La mémoire est étudiée par les géographes, l\'histoire par les historiens', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La mémoire est le souvenir que des individus ou des groupes conservent d\'événements passés. L\'histoire, elle, est une discipline qui analyse et critique les sources pour reconstituer le passé de façon rigoureuse.',
    hint: 'La mémoire peut être partielle ou émotionnelle ; l\'histoire cherche l\'objectivité.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-002',
    subject: 'histoire_geo',
    title: 'La commémoration du 11 novembre',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que commémore-t-on le 11 novembre en France ?',
    options: [
      { id: 'a', text: 'La fin de la Seconde Guerre mondiale', isCorrect: false },
      { id: 'b', text: 'L\'armistice qui a mis fin à la Première Guerre mondiale en 1918', isCorrect: true },
      { id: 'c', text: 'La libération de Paris en 1944', isCorrect: false },
      { id: 'd', text: 'L\'entrée en guerre de la France en 1914', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le 11 novembre 1918, l\'armistice a mis fin aux combats de la Première Guerre mondiale. Ce jour est férié en France pour honorer la mémoire des soldats morts au combat.',
    hint: 'Ce jour met fin à la Grande Guerre en 1918.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-003',
    subject: 'histoire_geo',
    title: 'Le 8 mai',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que commémore le 8 mai en France ?',
    options: [
      { id: 'a', text: 'La fin de la Première Guerre mondiale', isCorrect: false },
      { id: 'b', text: 'La victoire des Alliés sur l\'Allemagne nazie et la fin de la Seconde Guerre mondiale en Europe', isCorrect: true },
      { id: 'c', text: 'Le Débarquement allié en Normandie', isCorrect: false },
      { id: 'd', text: 'La libération de Paris', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le 8 mai 1945, l\'Allemagne nazie a signé sa capitulation sans condition, marquant la fin de la Seconde Guerre mondiale en Europe. Ce jour férié commémore cette victoire.',
    hint: 'La capitulation de l\'Allemagne nazie a été signée ce jour-là.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-004',
    subject: 'histoire_geo',
    title: 'Les lieux de mémoire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un lieu de mémoire ?',
    options: [
      { id: 'a', text: 'Une bibliothèque où sont conservés les livres d\'histoire', isCorrect: false },
      { id: 'b', text: 'Un endroit (mémorial, cimetière, musée) qui rappelle un événement historique important', isCorrect: true },
      { id: 'c', text: 'Un musée qui présente des objets préhistoriques', isCorrect: false },
      { id: 'd', text: 'L\'école où sont enseignés les faits historiques', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Un lieu de mémoire est un endroit symbolique lié à un événement historique important : cimetières militaires, mémoriaux, sites de batailles, monuments aux morts…',
    hint: 'Le Mémorial de Caen ou Verdun en sont des exemples.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-005',
    subject: 'histoire_geo',
    title: 'La mémoire de la Shoah',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la Shoah ?',
    options: [
      { id: 'a', text: 'La bataille qui a marqué la fin de la Seconde Guerre mondiale', isCorrect: false },
      { id: 'b', text: 'Le génocide des Juifs d\'Europe organisé par les nazis pendant la Seconde Guerre mondiale', isCorrect: true },
      { id: 'c', text: 'L\'occupation de la France par l\'Allemagne nazie', isCorrect: false },
      { id: 'd', text: 'La résistance française contre les nazis', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La Shoah désigne le génocide de six millions de Juifs européens, organisé par les nazis entre 1941 et 1945. Ce mot hébreu signifie « catastrophe ».',
    hint: 'Ce mot hébreu désigne une destruction massive et organisée.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-006',
    subject: 'histoire_geo',
    title: 'Le 27 janvier',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que commémore le 27 janvier, journée internationale dédiée à la mémoire des victimes de la Shoah ?',
    options: [
      { id: 'a', text: 'La fin de la Seconde Guerre mondiale', isCorrect: false },
      { id: 'b', text: 'La libération du camp d\'extermination d\'Auschwitz-Birkenau en 1945', isCorrect: true },
      { id: 'c', text: 'Le début de la persécution des Juifs en Allemagne', isCorrect: false },
      { id: 'd', text: 'L\'entrée des États-Unis dans la Seconde Guerre mondiale', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le 27 janvier 1945, les soldats soviétiques ont libéré le camp d\'Auschwitz-Birkenau en Pologne. Cette date est devenue la Journée internationale à la mémoire des victimes de la Shoah.',
    hint: 'Ce camp en Pologne fut libéré par des soldats russes.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-007',
    subject: 'histoire_geo',
    title: 'Les témoins et témoignages',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les témoignages des survivants sont-ils précieux pour l\'histoire ?',
    options: [
      { id: 'a', text: 'Parce qu\'ils remplacent les archives et les documents officiels', isCorrect: false },
      { id: 'b', text: 'Parce qu\'ils transmettent le vécu personnel et les émotions que les documents officiels ne capturent pas', isCorrect: true },
      { id: 'c', text: 'Parce qu\'ils sont toujours plus précis que les livres d\'histoire', isCorrect: false },
      { id: 'd', text: 'Parce qu\'ils permettent d\'éviter d\'étudier les archives', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les témoignages des survivants transmettent la dimension humaine et les émotions d\'événements historiques. Ils complètent les documents officiels en donnant une vision de l\'intérieur.',
    hint: 'Un document officiel décrit les faits ; un témoignage dit comment on l\'a vécu.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-008',
    subject: 'histoire_geo',
    title: 'La mémoire de l\'esclavage',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel jour commémore-t-on en France l\'abolition de l\'esclavage ?',
    options: [
      { id: 'a', text: 'Le 14 juillet', isCorrect: false },
      { id: 'b', text: 'Le 10 mai', isCorrect: true },
      { id: 'c', text: 'Le 11 novembre', isCorrect: false },
      { id: 'd', text: 'Le 8 mai', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le 10 mai est la Journée nationale des mémoires de la traite, de l\'esclavage et de leurs abolitions en France, instaurée en 2006 pour rappeler ce crime contre l\'humanité.',
    hint: 'Cette journée a été instaurée par la loi Taubira.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-009',
    subject: 'histoire_geo',
    title: 'Les monuments aux morts',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi presque toutes les communes de France ont-elles un monument aux morts ?',
    options: [
      { id: 'a', text: 'Pour décorer les places des villages', isCorrect: false },
      { id: 'b', text: 'Pour honorer la mémoire des habitants morts pour la France lors des conflits, notamment les deux guerres mondiales', isCorrect: true },
      { id: 'c', text: 'Pour rappeler les batailles gagnées par chaque village', isCorrect: false },
      { id: 'd', text: 'Pour marquer l\'emplacement des anciens cimetières', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Après la Première Guerre mondiale, qui a fait 1,4 million de morts français, presque chaque commune a érigé un monument pour honorer ses morts. Ils portent les noms des soldats tombés.',
    hint: 'La Grande Guerre a touché chaque village de France.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-010',
    subject: 'histoire_geo',
    title: 'Le devoir de mémoire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'appelle-t-on le « devoir de mémoire » ?',
    options: [
      { id: 'a', text: 'L\'obligation d\'apprendre par cœur les dates historiques', isCorrect: false },
      { id: 'b', text: 'La responsabilité de se souvenir des souffrances passées pour éviter qu\'elles se reproduisent', isCorrect: true },
      { id: 'c', text: 'L\'interdiction d\'oublier les défaites militaires', isCorrect: false },
      { id: 'd', text: 'La règle qui oblige à visiter les musées d\'histoire', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le devoir de mémoire est l\'engagement moral de se souvenir des tragédies historiques (génocides, guerres) afin de transmettre cette connaissance aux générations futures et d\'éviter que ces crimes se reproduisent.',
    hint: 'On dit souvent : « Plus jamais ça. »',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-011',
    subject: 'histoire_geo',
    title: 'Les archives nationales',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle des archives nationales ?',
    options: [
      { id: 'a', text: 'Organiser les cérémonies commémoratives officielles', isCorrect: false },
      { id: 'b', text: 'Conserver les documents officiels de l\'État et les rendre accessibles pour la recherche historique', isCorrect: true },
      { id: 'c', text: 'Former les historiens à l\'université', isCorrect: false },
      { id: 'd', text: 'Publier les manuels scolaires d\'histoire', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les Archives nationales conservent les documents officiels de l\'État (lois, décrets, actes…) depuis des siècles, les préservant pour les chercheurs et les citoyens qui veulent consulter les traces du passé.',
    hint: 'Elles gardent les traces écrites de la vie de l\'État.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-012',
    subject: 'histoire_geo',
    title: 'La mémoire de la Résistance',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel acte symbolique commémore-t-on le 18 juin en France ?',
    options: [
      { id: 'a', text: 'Le débarquement allié en Normandie', isCorrect: false },
      { id: 'b', text: 'L\'Appel du général de Gaulle à continuer le combat depuis Londres en 1940', isCorrect: true },
      { id: 'c', text: 'La libération de Paris en 1944', isCorrect: false },
      { id: 'd', text: 'La capitulation de la France devant l\'Allemagne', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le 18 juin 1940, le général de Gaulle a lancé depuis Londres un appel à la résistance sur les ondes de la BBC. Cet acte fondateur de la France Libre est commémoré chaque année.',
    hint: 'Ce général a refusé la défaite et a parlé à la radio britannique.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-013',
    subject: 'histoire_geo',
    title: 'Les génocides au XXe siècle',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un génocide ?',
    options: [
      { id: 'a', text: 'Une guerre entre deux pays voisins', isCorrect: false },
      { id: 'b', text: 'L\'extermination volontaire et systématique d\'un groupe humain pour ce qu\'il est', isCorrect: true },
      { id: 'c', text: 'Une épidémie qui tue une grande partie de la population', isCorrect: false },
      { id: 'd', text: 'Un conflit religieux entre deux communautés', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Un génocide est la destruction délibérée et systématique d\'un groupe en raison de son origine, sa religion ou son ethnie. La Shoah et le génocide des Arméniens en sont des exemples.',
    hint: 'Ce crime vise à éliminer tout un groupe humain en raison de ce qu\'il est.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-014',
    subject: 'histoire_geo',
    title: 'La transmission de la mémoire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quels sont les principaux moyens de transmettre la mémoire historique aux générations futures ?',
    options: [
      { id: 'a', text: 'Uniquement par l\'école obligatoire', isCorrect: false },
      { id: 'b', text: 'Par l\'école, les musées, les cérémonies, les films, les livres et les témoignages', isCorrect: true },
      { id: 'c', text: 'Seulement par les commémorations officielles', isCorrect: false },
      { id: 'd', text: 'Uniquement par les familles des victimes', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La mémoire se transmet par de nombreux canaux : l\'enseignement scolaire, les musées et mémoriaux, les cérémonies, le cinéma, la littérature et les témoignages directs des survivants.',
    hint: 'Pense à tous les endroits où on peut apprendre l\'histoire.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-hist-mem-015',
    subject: 'histoire_geo',
    title: 'Mémoire et réconciliation',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'mémoires et commémorations',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel geste symbolique fort a illustré la réconciliation franco-allemande après la Seconde Guerre mondiale ?',
    options: [
      { id: 'a', text: 'La signature du traité de Versailles', isCorrect: false },
      { id: 'b', text: 'La poignée de main entre le président Mitterrand et le chancelier Kohl à Verdun en 1984', isCorrect: true },
      { id: 'c', text: 'La création de l\'euro commun aux deux pays', isCorrect: false },
      { id: 'd', text: 'La construction du tunnel sous la Manche', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'En 1984, François Mitterrand et Helmut Kohl se sont tenus la main devant l\'ossuaire de Douaumont à Verdun, symbolisant la réconciliation entre la France et l\'Allemagne sur les lieux des pires batailles de 1914-1918.',
    hint: 'Cette image forte a eu lieu sur un champ de bataille de la Grande Guerre.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
