import type { HgExercise } from '../hg.types';
import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';

const A = cloneDefaultAdaptations();

export const hgCm2GeoInegalitesExercises: HgExercise[] = [
  {
    id: 'hg-cm2-geo-ine-001',
    subject: 'histoire_geo',
    title: 'Les inégalités mondiales',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment divise-t-on souvent les pays du monde en fonction de leur niveau de développement ?',
    options: [
      { id: 'a', text: 'En pays du Nord et pays du Sud', isCorrect: true },
      { id: 'b', text: 'En pays forts et pays faibles', isCorrect: false },
      { id: 'c', text: 'En pays industriels et pays agricoles uniquement', isCorrect: false },
      { id: 'd', text: 'En pays capitalistes et pays communistes', isCorrect: false },
    ],
    correctAnswer: 'a',
    explanation: 'On parle souvent des pays du « Nord » (pays riches et développés, souvent dans l\'hémisphère Nord) et des pays du « Sud » (pays en développement, souvent dans l\'hémisphère Sud), même si cette division est simplificatrice.',
    hint: 'Cette division géographique symbolique sépare les pays riches des pauvres.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-002',
    subject: 'histoire_geo',
    title: 'Le PIB par habitant',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le PIB (Produit Intérieur Brut) par habitant permet de mesurer ?',
    options: [
      { id: 'a', text: 'La superficie totale des terres agricoles d\'un pays', isCorrect: false },
      { id: 'b', text: 'La richesse économique produite par un pays divisée par le nombre d\'habitants', isCorrect: true },
      { id: 'c', text: 'Le nombre total de travailleurs dans un pays', isCorrect: false },
      { id: 'd', text: 'La quantité de ressources naturelles disponibles dans un pays', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le PIB par habitant est la valeur de tout ce qui est produit dans un pays en un an, divisée par sa population. C\'est un indicateur économique qui permet de comparer la richesse moyenne entre pays.',
    hint: 'C\'est la richesse du pays partagée entre tous ses habitants.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-003',
    subject: 'histoire_geo',
    title: 'L\'accès à l\'eau potable',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de personnes dans le monde n\'ont pas accès à une eau potable de qualité ?',
    options: [
      { id: 'a', text: 'Quelques milliers de personnes', isCorrect: false },
      { id: 'b', text: 'Plus de 2 milliards de personnes', isCorrect: true },
      { id: 'c', text: 'Environ 100 millions de personnes', isCorrect: false },
      { id: 'd', text: 'Moins d\'un million de personnes', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Plus de 2 milliards de personnes dans le monde n\'ont pas accès à une eau potable gérée de façon sûre. Ce manque affecte surtout les pays d\'Afrique subsaharienne et certaines régions d\'Asie.',
    hint: 'C\'est une inégalité fondamentale qui touche des milliards de personnes.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-004',
    subject: 'histoire_geo',
    title: 'L\'accès à l\'école',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi certains enfants dans le monde ne vont-ils pas à l\'école ?',
    options: [
      { id: 'a', text: 'Parce qu\'ils préfèrent travailler plutôt qu\'apprendre', isCorrect: false },
      { id: 'b', text: 'En raison de la pauvreté, de conflits armés, de la distance aux écoles ou de discriminations', isCorrect: true },
      { id: 'c', text: 'Parce que l\'école n\'est pas obligatoire dans la plupart des pays', isCorrect: false },
      { id: 'd', text: 'Parce que leurs parents ont décidé de les instruire à la maison', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Environ 250 millions d\'enfants dans le monde ne vont pas à l\'école ou ne maîtrisent pas les bases après des années de scolarisation. Les causes sont multiples : pauvreté, guerres, éloignement et inégalités de genre.',
    hint: 'La pauvreté est souvent la cause principale.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-005',
    subject: 'histoire_geo',
    title: 'L\'espérance de vie',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi l\'espérance de vie est-elle beaucoup plus élevée dans les pays riches que dans les pays pauvres ?',
    options: [
      { id: 'a', text: 'Parce que les gens des pays riches mangent mieux', isCorrect: false },
      { id: 'b', text: 'Parce que les pays riches ont de meilleurs systèmes de santé, d\'eau potable, d\'alimentation et de conditions de vie', isCorrect: true },
      { id: 'c', text: 'Parce que les pays riches ont un climat plus sain', isCorrect: false },
      { id: 'd', text: 'Parce que les habitants des pays pauvres travaillent plus dur', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'espérance de vie dépend de l\'accès aux soins médicaux, à l\'eau potable, à une alimentation suffisante et à des conditions de vie décentes. Dans les pays très pauvres, elle peut être inférieure de 20 à 30 ans à celle des pays riches.',
    hint: 'Accès aux médecins, aux médicaments et à une eau propre : voilà les clés.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-006',
    subject: 'histoire_geo',
    title: 'Les pays émergents',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que désigne le groupe des « BRICS » ?',
    options: [
      { id: 'a', text: 'Les pays les plus pauvres du monde', isCorrect: false },
      { id: 'b', text: 'Le Brésil, la Russie, l\'Inde, la Chine et l\'Afrique du Sud, grandes économies émergentes', isCorrect: true },
      { id: 'c', text: 'Les pays qui refusent de participer à l\'ONU', isCorrect: false },
      { id: 'd', text: 'Les cinq plus grandes démocraties du monde', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les BRICS (Brésil, Russie, Inde, Chine, Afrique du Sud) sont de grandes puissances émergentes dont l\'influence économique mondiale s\'est considérablement accrue depuis les années 2000.',
    hint: 'Ces initiales forment un groupe de pays en forte croissance économique.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-007',
    subject: 'histoire_geo',
    title: 'L\'aide au développement',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que l\'aide publique au développement (APD) ?',
    options: [
      { id: 'a', text: 'Des prêts que les banques accordent aux entreprises des pays pauvres', isCorrect: false },
      { id: 'b', text: 'Des dons ou prêts accordés par les pays riches aux pays en développement pour financer leur progrès', isCorrect: true },
      { id: 'c', text: 'L\'aide que les ONG envoient lors des catastrophes naturelles', isCorrect: false },
      { id: 'd', text: 'Les investissements des multinationales dans les pays pauvres', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'aide publique au développement est l\'aide financière que les États riches accordent aux pays en développement pour financer des projets d\'infrastructure, d\'éducation ou de santé. L\'ONU recommande que les pays riches y consacrent 0,7 % de leur richesse nationale.',
    hint: 'C\'est l\'aide des États riches, pas des ONG privées.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-008',
    subject: 'histoire_geo',
    title: 'La faim dans le monde',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle région du monde est la plus touchée par la malnutrition et la faim ?',
    options: [
      { id: 'a', text: 'L\'Amérique du Nord', isCorrect: false },
      { id: 'b', text: 'L\'Afrique subsaharienne', isCorrect: true },
      { id: 'c', text: 'L\'Europe de l\'Est', isCorrect: false },
      { id: 'd', text: 'L\'Océanie', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'Afrique subsaharienne (au sud du Sahara) est la région du monde la plus touchée par la faim et la malnutrition, en raison de la pauvreté, des conflits armés, des sécheresses et de l\'insuffisance des systèmes agricoles.',
    hint: 'Cette région d\'Afrique concentre les indicateurs les plus difficiles.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-009',
    subject: 'histoire_geo',
    title: 'Les objectifs de développement durable',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En 2015, l\'ONU a adopté 17 objectifs de développement durable (ODD). Quel est le premier d\'entre eux ?',
    options: [
      { id: 'a', text: 'Lutter contre le changement climatique', isCorrect: false },
      { id: 'b', text: 'Éliminer la pauvreté sous toutes ses formes dans le monde', isCorrect: true },
      { id: 'c', text: 'Garantir l\'accès à l\'éducation pour tous', isCorrect: false },
      { id: 'd', text: 'Protéger les océans et leurs ressources', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le premier des 17 Objectifs de Développement Durable (ODD) adoptés par l\'ONU en 2015 est « Pas de pauvreté » : éliminer la pauvreté extrême pour tous les peuples et partout dans le monde d\'ici 2030.',
    hint: 'Réduire les inégalités commence par s\'attaquer à la pauvreté.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-010',
    subject: 'histoire_geo',
    title: 'Les inégalités de genre',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans quels domaines les filles et les femmes sont-elles encore défavorisées dans de nombreux pays ?',
    options: [
      { id: 'a', text: 'Uniquement dans le domaine du sport', isCorrect: false },
      { id: 'b', text: 'Dans l\'accès à l\'éducation, à l\'emploi, aux soins et à la participation politique', isCorrect: true },
      { id: 'c', text: 'Uniquement dans les pays d\'Europe de l\'Est', isCorrect: false },
      { id: 'd', text: 'Dans les pays riches uniquement', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les inégalités de genre touchent de nombreux pays : les filles ont moins souvent accès à l\'école, les femmes sont moins bien payées et sous-représentées en politique. Ces inégalités ralentissent le développement.',
    hint: 'Ces inégalités touchent l\'éducation, le travail et la politique.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-011',
    subject: 'histoire_geo',
    title: 'Le travail des enfants',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi le travail des enfants est-il encore fréquent dans certains pays en développement ?',
    options: [
      { id: 'a', text: 'Parce que les enfants travaillent mieux que les adultes', isCorrect: false },
      { id: 'b', text: 'Parce que les familles très pauvres ont besoin du revenu des enfants pour survivre', isCorrect: true },
      { id: 'c', text: 'Parce que la scolarité n\'est pas considérée comme utile dans ces pays', isCorrect: false },
      { id: 'd', text: 'Parce que ces pays manquent d\'adultes disponibles', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le travail des enfants est souvent lié à l\'extrême pauvreté : les familles envoient leurs enfants travailler parce qu\'elles ont besoin de ce revenu pour survivre. Environ 160 millions d\'enfants dans le monde travaillent encore.',
    hint: 'La pauvreté extrême force parfois les familles à des choix difficiles.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-012',
    subject: 'histoire_geo',
    title: 'Les inégalités en France',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le seuil de pauvreté en France ?',
    options: [
      { id: 'a', text: 'Le niveau de revenu en dessous duquel on ne peut pas se nourrir', isCorrect: false },
      { id: 'b', text: 'Le niveau de revenu en dessous duquel on est considéré comme pauvre par rapport au niveau de vie moyen de la société', isCorrect: true },
      { id: 'c', text: 'Le montant minimum du salaire légal en France', isCorrect: false },
      { id: 'd', text: 'Le revenu maximum pour avoir droit aux aides sociales', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le seuil de pauvreté est défini en France à 60 % du revenu médian. En dessous de ce seuil, une personne est considérée comme pauvre car elle ne peut pas vivre convenablement dans le contexte économique de son pays.',
    hint: 'C\'est un seuil relatif qui dépend du niveau de vie de l\'ensemble de la société.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-013',
    subject: 'histoire_geo',
    title: 'Les DOM-TOM et les inégalités',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les départements d\'outre-mer français (Martinique, Guadeloupe, Guyane, Réunion, Mayotte) connaissent-ils souvent un niveau de vie inférieur à la métropole ?',
    options: [
      { id: 'a', text: 'Parce qu\'ils sont plus éloignés de Paris', isCorrect: false },
      { id: 'b', text: 'En raison d\'un taux de chômage plus élevé et d\'un tissu économique moins diversifié', isCorrect: true },
      { id: 'c', text: 'Parce qu\'ils n\'ont pas droit aux aides sociales françaises', isCorrect: false },
      { id: 'd', text: 'Parce qu\'ils ont refusé l\'aide de l\'État français', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les DOM connaissent un chômage beaucoup plus élevé (parfois 3 fois plus qu\'en métropole) et une économie souvent moins diversifiée, héritages en partie du passé colonial. Malgré les aides de l\'État, les inégalités restent fortes.',
    hint: 'L\'histoire coloniale et l\'isolement géographique ont des conséquences économiques.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-014',
    subject: 'histoire_geo',
    title: 'La dette des pays pauvres',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi la dette extérieure est-elle un problème pour beaucoup de pays pauvres ?',
    options: [
      { id: 'a', text: 'Parce que la dette empêche ces pays de commercer avec d\'autres', isCorrect: false },
      { id: 'b', text: 'Parce que rembourser la dette accapare des ressources qui devraient servir à financer les écoles, les hôpitaux et les routes', isCorrect: true },
      { id: 'c', text: 'Parce que la dette interdit aux pays d\'emprunter à nouveau', isCorrect: false },
      { id: 'd', text: 'Parce que la dette provoque automatiquement des guerres civiles', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Beaucoup de pays pauvres consacrent une grande partie de leurs revenus au remboursement de dettes contractées auprès de pays riches ou de banques internationales. Cet argent manque alors pour financer le développement.',
    hint: 'Rembourser ses dettes laisse moins d\'argent pour construire des écoles.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-ine-015',
    subject: 'histoire_geo',
    title: 'Réduire les inégalités',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'inégalités mondiales',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est l\'un des moyens les plus efficaces pour réduire les inégalités mondiales à long terme ?',
    options: [
      { id: 'a', text: 'Interdire les entreprises multinationales', isCorrect: false },
      { id: 'b', text: 'Développer l\'accès à une éducation de qualité pour tous', isCorrect: true },
      { id: 'c', text: 'Fermer les frontières des pays riches', isCorrect: false },
      { id: 'd', text: 'Supprimer le commerce international', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'éducation est l\'un des leviers les plus puissants pour réduire les inégalités : elle permet aux individus et aux pays d\'acquérir des compétences, de participer à l\'économie et d\'améliorer leurs conditions de vie à long terme.',
    hint: 'Avec une bonne éducation, chacun a plus de chances de s\'en sortir.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
