import type { HgExercise } from '../hg.types';
import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';

const A = cloneDefaultAdaptations();

export const hgCm2GeoRisquesExercises: HgExercise[] = [
  {
    id: 'hg-cm2-geo-rsk-001',
    subject: 'histoire_geo',
    title: 'Risques naturels et technologiques',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la différence entre un risque naturel et un risque technologique ?',
    options: [
      { id: 'a', text: 'Les risques naturels sont plus dangereux que les risques technologiques', isCorrect: false },
      { id: 'b', text: 'Les risques naturels sont dus à des phénomènes de la nature ; les risques technologiques viennent des activités humaines (usines, transport, nucléaire)', isCorrect: true },
      { id: 'c', text: 'Les risques technologiques ne touchent que les grandes villes', isCorrect: false },
      { id: 'd', text: 'Les risques naturels sont toujours plus prévisibles', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Un risque naturel vient de la nature (séisme, inondation, volcan). Un risque technologique vient des activités humaines : accident industriel, explosion d\'une usine chimique, accident nucléaire ou déversement d\'hydrocarbures.',
    hint: 'L\'un vient de la nature, l\'autre des activités de l\'homme.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-002',
    subject: 'histoire_geo',
    title: 'L\'accident de Tchernobyl',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle année a eu lieu la catastrophe nucléaire de Tchernobyl ?',
    options: [
      { id: 'a', text: '1979', isCorrect: false },
      { id: 'b', text: '1986', isCorrect: true },
      { id: 'c', text: '2011', isCorrect: false },
      { id: 'd', text: '1999', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La catastrophe nucléaire de Tchernobyl a eu lieu le 26 avril 1986 en Ukraine (alors URSS). L\'explosion du réacteur a libéré d\'importantes quantités de radioactivité sur une grande partie de l\'Europe.',
    hint: 'Cette catastrophe s\'est produite à la fin des années 1980.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-003',
    subject: 'histoire_geo',
    title: 'Fukushima',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle catastrophe a provoqué l\'accident nucléaire de Fukushima en 2011 au Japon ?',
    options: [
      { id: 'a', text: 'Une attaque terroriste sur la centrale', isCorrect: false },
      { id: 'b', text: 'Un séisme suivi d\'un tsunami qui a endommagé les systèmes de refroidissement de la centrale', isCorrect: true },
      { id: 'c', text: 'Une erreur humaine lors d\'un test de sécurité', isCorrect: false },
      { id: 'd', text: 'Une sécheresse qui a coupé l\'eau nécessaire au refroidissement', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le 11 mars 2011, un puissant séisme a déclenché un tsunami qui a déferlé sur la côte nord-est du Japon. Les vagues ont inondé la centrale de Fukushima, coupant l\'alimentation électrique et entraînant la fusion de réacteurs.',
    hint: 'Une catastrophe naturelle a déclenché cette catastrophe technologique.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-004',
    subject: 'histoire_geo',
    title: 'Les marées noires',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une marée noire ?',
    options: [
      { id: 'a', text: 'Une marée de nuit qui noie les plages', isCorrect: false },
      { id: 'b', text: 'Une pollution marine causée par un déversement accidentel de pétrole brut dans la mer', isCorrect: true },
      { id: 'c', text: 'Une tempête qui colore les vagues en noir', isCorrect: false },
      { id: 'd', text: 'Un phénomène naturel lié aux algues toxiques', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Une marée noire se produit quand un pétrolier se fracasse sur des rochers ou qu\'une plateforme pétrolière explose, déversant des milliers de tonnes de pétrole brut dans la mer, détruisant la faune et la flore marines.',
    hint: 'Le pétrole flotte sur l\'eau et souille tout ce qu\'il touche.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-005',
    subject: 'histoire_geo',
    title: 'Les Plans de Prévention des Risques',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En France, à quoi sert un Plan de Prévention des Risques (PPR) ?',
    options: [
      { id: 'a', text: 'À former les pompiers aux interventions d\'urgence', isCorrect: false },
      { id: 'b', text: 'À définir les zones à risque et à règlementer les constructions dans ces zones pour protéger la population', isCorrect: true },
      { id: 'c', text: 'À prévenir les maladies épidémiques dans les villes', isCorrect: false },
      { id: 'd', text: 'À organiser l\'évacuation des habitants lors des crues', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le PPR est un document officiel qui cartographie les zones exposées à des risques (inondations, séismes, glissements de terrain…) et réglemente les constructions dans ces zones pour limiter les dommages en cas de catastrophe.',
    hint: 'Ce plan guide les règles de construction dans les zones dangereuses.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-006',
    subject: 'histoire_geo',
    title: 'Le risque industriel en France',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que signifie le classement « SEVESO » pour une usine en Europe ?',
    options: [
      { id: 'a', text: 'C\'est une norme de qualité pour les produits alimentaires', isCorrect: false },
      { id: 'b', text: 'C\'est une directive européenne qui classe les usines présentant un risque d\'accident industriel majeur', isCorrect: true },
      { id: 'c', text: 'C\'est un label qui garantit que l\'usine respecte l\'environnement', isCorrect: false },
      { id: 'd', text: 'C\'est une certification pour les usines qui emploient plus de 500 personnes', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La directive SEVESO (du nom d\'un accident chimique en Italie en 1976) oblige les usines manipulant des substances dangereuses à informer les riverains, à réaliser des études de risques et à mettre en place des plans d\'urgence.',
    hint: 'Ce nom vient d\'une catastrophe industrielle italienne des années 1970.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-007',
    subject: 'histoire_geo',
    title: 'Les îles et les risques',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi certaines îles du Pacifique sont-elles particulièrement menacées par le changement climatique ?',
    options: [
      { id: 'a', text: 'Parce qu\'elles sont situées sur la ceinture de feu volcanique', isCorrect: false },
      { id: 'b', text: 'Parce que la montée des eaux liée au réchauffement climatique risque de les submerger entièrement', isCorrect: true },
      { id: 'c', text: 'Parce qu\'elles sont trop petites pour se défendre contre les cyclones', isCorrect: false },
      { id: 'd', text: 'Parce qu\'elles n\'ont pas accès à l\'eau douce', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Des États insulaires comme Tuvalu ou les Maldives sont à quelques mètres à peine au-dessus du niveau de la mer. La montée des eaux due au réchauffement climatique menace de les submerger et d\'obliger leurs habitants à migrer.',
    hint: 'Ces îles sont très basses, à peine au-dessus de l\'océan.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-008',
    subject: 'histoire_geo',
    title: 'La gestion des risques',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelles sont les trois étapes principales de la gestion d\'un risque majeur ?',
    options: [
      { id: 'a', text: 'Ignorer, surveiller, réparer', isCorrect: false },
      { id: 'b', text: 'Prévenir, alerter et protéger, gérer la crise et reconstruire', isCorrect: true },
      { id: 'c', text: 'Étudier, financer, construire', isCorrect: false },
      { id: 'd', text: 'Observer, mesurer, calculer', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'La gestion des risques se fait en trois temps : la prévention (anticiper et réduire les risques), la gestion de crise (alerter, évacuer, secourir lors d\'une catastrophe) et la reconstruction (réparer les dégâts après).',
    hint: 'Avant, pendant et après : trois temps distincts de gestion.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-009',
    subject: 'histoire_geo',
    title: 'Les incendies de forêt en France',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle mesure préventive permet de limiter la propagation des incendies de forêt ?',
    options: [
      { id: 'a', text: 'Planter davantage d\'arbres dans les zones à risque', isCorrect: false },
      { id: 'b', text: 'Créer des coupe-feux (espaces dégagés qui coupent la progression du feu)', isCorrect: true },
      { id: 'c', text: 'Arroser les forêts avec des avions en permanence', isCorrect: false },
      { id: 'd', text: 'Interdire complètement l\'accès aux forêts toute l\'année', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les coupe-feux sont des bandes de terrain débroussaillées qui interrompent la continuité de la végétation et empêchent le feu de se propager. Ils font partie des mesures préventives essentielles dans les zones à risque.',
    hint: 'Ces trouées dans la végétation arrêtent l\'avancée des flammes.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-010',
    subject: 'histoire_geo',
    title: 'La solidarité internationale',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel mécanisme permet aux pays européens de s\'entraider lors de catastrophes naturelles ou technologiques majeures ?',
    options: [
      { id: 'a', text: 'Chaque pays gère ses catastrophes tout seul', isCorrect: false },
      { id: 'b', text: 'Le mécanisme européen de protection civile qui permet de partager ressources et personnels', isCorrect: true },
      { id: 'c', text: 'Un fonds privé alimenté par les assurances', isCorrect: false },
      { id: 'd', text: 'L\'OTAN qui intervient avec ses forces militaires', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'Union européenne dispose d\'un mécanisme de protection civile qui permet aux États membres de partager rapidement leurs ressources (avions bombardiers d\'eau, équipes de secours, matériel) en cas de catastrophe dans l\'un d\'eux.',
    hint: 'L\'Europe dispose d\'un système de solidarité pour les catastrophes.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-011',
    subject: 'histoire_geo',
    title: 'L\'érosion des côtes',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la principale cause de l\'érosion des côtes en France ?',
    options: [
      { id: 'a', text: 'La pollution des mers par les déchets plastiques', isCorrect: false },
      { id: 'b', text: 'L\'action combinée des vagues, des tempêtes et de la montée du niveau de la mer', isCorrect: true },
      { id: 'c', text: 'La surpopulation des littoraux par les touristes', isCorrect: false },
      { id: 'd', text: 'L\'extraction de sable sur les plages', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'L\'érosion côtière est accélérée par les tempêtes, les vagues et la montée du niveau de la mer liée au changement climatique. Des falaises comme celles d\'Étretat reculent de plusieurs centimètres par an.',
    hint: 'La mer grignote progressivement les côtes.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-012',
    subject: 'histoire_geo',
    title: 'Les risques en Martinique et Guadeloupe',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quels risques naturels menacent particulièrement les Antilles françaises (Martinique et Guadeloupe) ?',
    options: [
      { id: 'a', text: 'Les avalanches et les glissements de terrain uniquement', isCorrect: false },
      { id: 'b', text: 'Les cyclones, les séismes, les tsunamis et les éruptions volcaniques', isCorrect: true },
      { id: 'c', text: 'Les inondations et les sécheresses uniquement', isCorrect: false },
      { id: 'd', text: 'Uniquement les cyclones tropicaux', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les Antilles françaises cumulent de nombreux risques naturels : elles sont situées sur une zone sismique active, dans le couloir des cyclones atlantiques, exposées aux tsunamis et possèdent des volcans (la Soufrière en Guadeloupe).',
    hint: 'Ces îles concentrent presque tous les types de risques naturels.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-013',
    subject: 'histoire_geo',
    title: 'Le DDRM',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le DDRM (Dossier Départemental sur les Risques Majeurs) ?',
    options: [
      { id: 'a', text: 'Un document secret réservé aux forces de l\'ordre', isCorrect: false },
      { id: 'b', text: 'Un document public qui répertorie tous les risques naturels et technologiques d\'un département', isCorrect: true },
      { id: 'c', text: 'Un plan d\'évacuation destiné aux pompiers', isCorrect: false },
      { id: 'd', text: 'Un guide de construction parasismique', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Le DDRM est un document public réalisé par le préfet de chaque département. Il recense les risques majeurs (inondations, séismes, risques industriels…) présents sur le territoire et informe les citoyens sur les précautions à prendre.',
    hint: 'Ce document public informe les habitants des risques de leur région.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-014',
    subject: 'histoire_geo',
    title: 'Se préparer aux risques',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un kit de survie (ou « sac de 72 heures ») recommandé pour faire face à une catastrophe ?',
    options: [
      { id: 'a', text: 'Un uniforme de pompier pour aider les secours', isCorrect: false },
      { id: 'b', text: 'Un sac préparé à l\'avance contenant eau, nourriture, médicaments, documents et moyens de communication pour survivre 3 jours', isCorrect: true },
      { id: 'c', text: 'Un équipement professionnel pour mesurer les risques naturels', isCorrect: false },
      { id: 'd', text: 'Un sac de voyage avec vêtements chauds pour partir en montagne', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les autorités recommandent de préparer un kit d\'urgence contenant : eau (1,5 L par personne et par jour), nourriture non périssable, médicaments, lampe de poche, radio à piles et copies de documents importants pour tenir 72 heures.',
    hint: '72 heures = 3 jours d\'autonomie en cas de coupure de tous les services.',
    estimatedMinutes: 2,
    adaptations: A,
  },
  {
    id: 'hg-cm2-geo-rsk-015',
    subject: 'histoire_geo',
    title: 'Risques et aménagement du territoire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'geographie',
    subskill: 'risques majeurs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi certaines populations continuent-elles de vivre dans des zones à risques (volcans, zones inondables) ?',
    options: [
      { id: 'a', text: 'Parce qu\'elles ne savent pas que la zone est dangereuse', isCorrect: false },
      { id: 'b', text: 'Parce que ces zones offrent souvent des terres fertiles, des ressources ou sont leur lieu d\'origine depuis des générations', isCorrect: true },
      { id: 'c', text: 'Parce que les gouvernements les obligent à y rester', isCorrect: false },
      { id: 'd', text: 'Parce que les risques ne sont jamais très dangereux en réalité', isCorrect: false },
    ],
    correctAnswer: 'b',
    explanation: 'Les flancs des volcans ont des sols très fertiles, les plaines inondables sont propices à l\'agriculture, et les habitants ont souvent des liens familiaux et culturels forts avec ces territoires, ce qui explique qu\'ils y restent malgré les risques.',
    hint: 'Un volcan, c\'est dangereux, mais les terres autour sont très fertiles.',
    estimatedMinutes: 2,
    adaptations: A,
  },
];
