import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { HgExercise } from '../hg.types';

const A = cloneDefaultAdaptations();

export const hgCm2HistoireAgeIndustrielExercises: HgExercise[] = [

  {
    id: 'hg-cm2-hist-ind-001',
    subject: 'histoire_geo',
    title: 'La révolution industrielle',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'age_industriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Au XIXe siècle, l\'invention de machines à vapeur a transformé le travail. Comment appelle-t-on cette grande transformation économique ?',
    options: [
      { id: 'a', text: 'La révolution agricole', isCorrect: false },
      { id: 'b', text: 'La révolution industrielle', isCorrect: true },
      { id: 'c', text: 'La révolution numérique', isCorrect: false },
      { id: 'd', text: 'La révolution scientifique', isCorrect: false },
    ],
    correctAnswer: 'La révolution industrielle',
    explanation: 'La révolution industrielle débuta en Angleterre à la fin du XVIIIe siècle. Les machines à vapeur permirent de produire beaucoup plus vite dans des usines.',
    hint: 'Elle a transformé le monde du travail grâce aux machines.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-002',
    subject: 'histoire_geo',
    title: 'Les ouvriers au XIXe siècle',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'histoire',
    subskill: 'age_industriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Au XIXe siècle, les ouvriers travaillaient dans des conditions très difficiles. Quelle journée de travail était courante à cette époque ?',
    options: [
      { id: 'a', text: '4 heures par jour', isCorrect: false },
      { id: 'b', text: '7 heures par jour', isCorrect: false },
      { id: 'c', text: '12 à 14 heures par jour', isCorrect: true },
      { id: 'd', text: '35 heures par semaine', isCorrect: false },
    ],
    correctAnswer: '12 à 14 heures par jour',
    explanation: 'Au XIXe siècle, les ouvriers (y compris des enfants) travaillaient souvent 12 à 14 heures par jour dans des conditions épuisantes.',
    hint: 'C\'est beaucoup plus long qu\'aujourd\'hui !',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-003',
    subject: 'histoire_geo',
    title: 'Le chemin de fer',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'age_industriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'invention du chemin de fer au XIXe siècle a changé les déplacements. Quel avantage principal apportait-il ?',
    options: [
      { id: 'a', text: 'Il permettait de voyager sur la mer', isCorrect: false },
      { id: 'b', text: 'Il permettait de voyager beaucoup plus vite sur de longues distances', isCorrect: true },
      { id: 'c', text: 'Il était moins cher que la marche à pied', isCorrect: false },
      { id: 'd', text: 'Il fonctionnait à l\'électricité', isCorrect: false },
    ],
    correctAnswer: 'Il permettait de voyager beaucoup plus vite sur de longues distances',
    explanation: 'Avant le train, les voyages longues distances se faisaient en diligence et prenaient des jours. Le chemin de fer permettait de traverser la France en quelques heures.',
    hint: 'Il marchait à la vapeur et roulait sur des rails.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-004',
    subject: 'histoire_geo',
    title: 'Louis Pasteur',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'age_industriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Louis Pasteur est un grand scientifique français du XIXe siècle. Quelle découverte majeure lui doit-on ?',
    options: [
      { id: 'a', text: 'L\'électricité', isCorrect: false },
      { id: 'b', text: 'Le vaccin contre la rage et la pasteurisation', isCorrect: true },
      { id: 'c', text: 'L\'imprimerie', isCorrect: false },
      { id: 'd', text: 'La pénicilline', isCorrect: false },
    ],
    correctAnswer: 'Le vaccin contre la rage et la pasteurisation',
    explanation: 'Pasteur a mis au point le vaccin contre la rage en 1885 et la pasteurisation (chauffage pour éliminer les microbes dans les aliments).',
    hint: 'Son nom est donné à un procédé utilisé pour conserver le lait.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-005',
    subject: 'histoire_geo',
    title: 'La tour Eiffel',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'histoire',
    subskill: 'age_industriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La tour Eiffel a été construite pour une exposition universelle. En quelle année a-t-elle été inaugurée ?',
    options: [
      { id: 'a', text: '1850', isCorrect: false },
      { id: 'b', text: '1889', isCorrect: true },
      { id: 'c', text: '1914', isCorrect: false },
      { id: 'd', text: '1920', isCorrect: false },
    ],
    correctAnswer: '1889',
    explanation: 'La tour Eiffel fut construite par Gustave Eiffel pour l\'Exposition universelle de Paris de 1889, qui célébrait le centenaire de la Révolution française.',
    hint: 'C\'est la même année que le centenaire de la Révolution française.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-006',
    subject: 'histoire_geo',
    title: 'Les syndicats',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'age_industriel',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pour défendre leurs droits, les ouvriers du XIXe siècle ont créé des organisations collectives. Lesquelles ?',
    options: [
      { id: 'a', text: 'Des partis royalistes', isCorrect: false },
      { id: 'b', text: 'Des syndicats de travailleurs', isCorrect: true },
      { id: 'c', text: 'Des guildes médiévales', isCorrect: false },
      { id: 'd', text: 'Des compagnies commerciales', isCorrect: false },
    ],
    correctAnswer: 'Des syndicats de travailleurs',
    explanation: 'Les syndicats ont permis aux ouvriers de se réunir pour défendre collectivement leurs droits : salaires, durée du travail, conditions de sécurité.',
    hint: 'Ces organisations existent encore aujourd\'hui pour défendre les employés.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-007',
    subject: 'histoire_geo',
    title: "Première ligne de chemin de fer française",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La première ligne de chemin de fer à usage public en France, ouverte en 1827, reliait deux villes. Lesquelles ?",
    options: [
      { id: 'a', text: "Paris et Versailles", isCorrect: false },
      { id: 'b', text: "Lyon et Saint-Étienne", isCorrect: true },
      { id: 'c', text: "Bordeaux et Toulouse", isCorrect: false },
      { id: 'd', text: "Rouen et Le Havre", isCorrect: false },
    ],
    correctAnswer: "Lyon et Saint-Étienne",
    explanation: "La première ligne de chemin de fer française est inaugurée en 1827 entre Saint-Étienne et Andrézieux (près de Lyon). Elle transportait surtout du charbon. La première ligne de voyageurs suit en 1832.",
    hint: "Lyon-Saint-Étienne 1827 = première ligne de chemin de fer en France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-008',
    subject: 'histoire_geo',
    title: "L'exode rural",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au XIXe siècle, l'industrialisation provoque un exode rural massif. De quoi s'agit-il ?",
    options: [
      { id: 'a', text: "Des paysans qui quittent la ville pour aller à la campagne", isCorrect: false },
      { id: 'b', text: "Des paysans qui quittent la campagne pour aller travailler dans les villes industrielles", isCorrect: true },
      { id: 'c', text: "Des migrations de travailleurs vers des pays étrangers", isCorrect: false },
      { id: 'd', text: "Des déplacements de troupeaux", isCorrect: false },
    ],
    correctAnswer: "Des paysans qui quittent la campagne pour aller travailler dans les villes industrielles",
    explanation: "L'industrialisation attire les paysans vers les villes (mines, usines textiles, métallurgie). Les villes comme Lyon, Lille, Saint-Étienne et Paris grossissent rapidement au XIXe siècle.",
    hint: "Exode rural = rural (campagne) → urban (ville). Au XIXe s. avec l'industrialisation.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-009',
    subject: 'histoire_geo',
    title: "La colonisation française",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'colonisation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au XIXe siècle, la France constitue un vaste empire colonial. Quel était le 2e empire colonial mondial à la fin du XIXe siècle ?",
    options: [
      { id: 'a', text: "La France", isCorrect: true },
      { id: 'b', text: "L'Espagne", isCorrect: false },
      { id: 'c', text: "L'Allemagne", isCorrect: false },
      { id: 'd', text: "La Russie", isCorrect: false },
    ],
    correctAnswer: "La France",
    explanation: "À son apogée (fin XIXe-début XXe s.), l'empire colonial français est le 2e au monde (après l'Empire britannique). Il comprend l'Algérie, le Maroc, la Tunisie, l'Afrique subsaharienne, l'Indochine, Madagascar…",
    hint: "Empire colonial français = 2e mondial au XIXe s., après la Grande-Bretagne.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-010',
    subject: 'histoire_geo',
    title: "La condition ouvrière",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au XIXe siècle, la condition des ouvriers industriels était difficile. Quelle loi de 1841 tenta de les protéger ?",
    options: [
      { id: 'a', text: "La loi instaurant le droit de grève", isCorrect: false },
      { id: 'b', text: "La loi limitant le travail des enfants (interdiction avant 8 ans, 8h max entre 8 et 12 ans)", isCorrect: true },
      { id: 'c', text: "La loi instaurant le SMIC", isCorrect: false },
      { id: 'd', text: "La loi accordant le suffrage universel aux ouvriers", isCorrect: false },
    ],
    correctAnswer: "La loi limitant le travail des enfants (interdiction avant 8 ans, 8h max entre 8 et 12 ans)",
    explanation: "La loi du 22 mars 1841 fut la première à limiter le travail des enfants dans les manufactures : interdit avant 8 ans, limité à 8h/jour entre 8 et 12 ans. Mais son application resta faible.",
    hint: "1841 = première loi limitant le travail des enfants en France.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-011',
    subject: 'histoire_geo',
    title: "La tour Eiffel et l'Exposition universelle",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La tour Eiffel a été construite pour l'Exposition universelle de 1889. Que commémorait cet événement ?",
    options: [
      { id: 'a', text: "La naissance de Napoléon Bonaparte", isCorrect: false },
      { id: 'b', text: "Le centenaire de la Révolution française (1789-1889)", isCorrect: true },
      { id: 'c', text: "L'inauguration du canal de Suez", isCorrect: false },
      { id: 'd', text: "La victoire de la France contre la Prusse", isCorrect: false },
    ],
    correctAnswer: "Le centenaire de la Révolution française (1789-1889)",
    explanation: "L'Exposition universelle de 1889 célèbre le centenaire de la Révolution française. Gustave Eiffel y construisit sa tour (300m), symbole du progrès industriel.",
    hint: "1889 = 100 ans après 1789 → Révolution française → tour Eiffel.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-012',
    subject: 'histoire_geo',
    title: "Haussmann et Paris",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le baron Haussmann transforma Paris sous Napoléon III (1853-1870). En quoi consista cette transformation ?",
    options: [
      { id: 'a', text: "Il construisit la tour Eiffel et les Champs-Élysées", isCorrect: false },
      { id: 'b', text: "Il rasa des quartiers médiévaux et créa de larges boulevards, des parcs et un réseau d'égouts", isCorrect: true },
      { id: 'c', text: "Il construisit le métro parisien", isCorrect: false },
      { id: 'd', text: "Il déplaça la capitale de Paris à Versailles", isCorrect: false },
    ],
    correctAnswer: "Il rasa des quartiers médiévaux et créa de larges boulevards, des parcs et un réseau d'égouts",
    explanation: "Haussmann transforma Paris en une ville moderne : larges boulevards (pour faciliter la circulation et empêcher les barricades), parcs (Bois de Boulogne, Vincennes), eau courante et égouts.",
    hint: "Haussmann = grands boulevards parisiens + parcs + égouts modernes.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-013',
    subject: 'histoire_geo',
    title: "Marie Curie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Marie Curie a reçu deux prix Nobel. Dans quelles disciplines ?",
    options: [
      { id: 'a', text: "Physique et médecine", isCorrect: false },
      { id: 'b', text: "Physique et chimie", isCorrect: true },
      { id: 'c', text: "Chimie et littérature", isCorrect: false },
      { id: 'd', text: "Médecine et physique", isCorrect: false },
    ],
    correctAnswer: "Physique et chimie",
    explanation: "Marie Curie reçut le prix Nobel de physique en 1903 (pour ses recherches sur les radiations) et le prix Nobel de chimie en 1911 (pour la découverte du radium et du polonium).",
    hint: "Marie Curie : physique 1903 + chimie 1911.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-014',
    subject: 'histoire_geo',
    title: "Jules Verne et le progrès",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Jules Verne (1828-1905) est un romancier français célèbre pour ses romans d'anticipation. Lequel est le plus connu ?",
    options: [
      { id: 'a', text: "Les Misérables", isCorrect: false },
      { id: 'b', text: "Le Tour du monde en 80 jours", isCorrect: true },
      { id: 'c', text: "Germinal", isCorrect: false },
      { id: 'd', text: "Notre-Dame de Paris", isCorrect: false },
    ],
    correctAnswer: "Le Tour du monde en 80 jours",
    explanation: "Jules Verne écrivit De la Terre à la Lune, 20 000 lieues sous les mers, Le Tour du monde en 80 jours… Ses romans reflètent la fascination du XIXe s. pour le progrès technique et la science.",
    hint: "Jules Verne = anticipation + progrès technique = XIXe siècle.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-015',
    subject: 'histoire_geo',
    title: "La grève ouvrière",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le droit de grève fut reconnu en France en 1864. Pourquoi les ouvriers faisaient-ils grève au XIXe siècle ?",
    options: [
      { id: 'a', text: "Pour protester contre le prix du pain uniquement", isCorrect: false },
      { id: 'b', text: "Pour obtenir de meilleures conditions de travail, des salaires plus élevés et des horaires réduits", isCorrect: true },
      { id: 'c', text: "Pour soutenir le gouvernement en place", isCorrect: false },
      { id: 'd', text: "Pour exiger la fin du chemin de fer", isCorrect: false },
    ],
    correctAnswer: "Pour obtenir de meilleures conditions de travail, des salaires plus élevés et des horaires réduits",
    explanation: "Les ouvriers du XIXe siècle travaillaient souvent 12 à 14 heures par jour dans des conditions dangereuses pour de faibles salaires. La grève était leur principal moyen de pression.",
    hint: "Grève = arrêt de travail pour obtenir de meilleures conditions.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-016',
    subject: 'histoire_geo',
    title: "La naissance de la photographie",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La photographie est inventée en France dans la première moitié du XIXe siècle. Quel Français est souvent crédité de l'invention du daguerréotype (1839) ?",
    options: [
      { id: 'a', text: "Louis Lumière", isCorrect: false },
      { id: 'b', text: "Louis Daguerre", isCorrect: true },
      { id: 'c', text: "Claude Monet", isCorrect: false },
      { id: 'd', text: "Gustave Eiffel", isCorrect: false },
    ],
    correctAnswer: "Louis Daguerre",
    explanation: "Louis Daguerre inventa le daguerréotype en 1839, un procédé permettant de fixer une image sur une plaque argentée. C'est l'ancêtre de la photographie moderne.",
    hint: "Daguerréotype 1839 → Daguerre → première photographie.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-017',
    subject: 'histoire_geo',
    title: "La bicyclette",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La bicyclette avec pédalier et chaîne (proche du vélo moderne) est perfectionnée dans la 2e moitié du XIXe siècle. Dans quel pays cela se produit-il ?",
    options: [
      { id: 'a', text: "L'Allemagne", isCorrect: false },
      { id: 'b', text: "La France et la Grande-Bretagne", isCorrect: true },
      { id: 'c', text: "Les États-Unis uniquement", isCorrect: false },
      { id: 'd', text: "L'Italie", isCorrect: false },
    ],
    correctAnswer: "La France et la Grande-Bretagne",
    explanation: "La bicyclette fut perfectionnée conjointement en France (vélocipède de Michaux, 1860s) et en Grande-Bretagne (pneus de Dunlop, 1888). Le Tour de France est créé en 1903.",
    hint: "Vélo moderne → France + Grande-Bretagne → fin XIXe s.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-018',
    subject: 'histoire_geo',
    title: "Le télégraphe et le téléphone",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le téléphone est inventé en 1876. Qui en est généralement crédité comme l'inventeur ?",
    options: [
      { id: 'a', text: "Thomas Edison", isCorrect: false },
      { id: 'b', text: "Alexander Graham Bell", isCorrect: true },
      { id: 'c', text: "Guglielmo Marconi", isCorrect: false },
      { id: 'd', text: "Louis Pasteur", isCorrect: false },
    ],
    correctAnswer: "Alexander Graham Bell",
    explanation: "Alexander Graham Bell (Écossais naturalisé américain) breveta le téléphone en 1876. Cette invention révolutionna les communications à distance, permettant de parler en temps réel.",
    hint: "Bell → téléphone → 1876.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-019',
    subject: 'histoire_geo',
    title: "La condition féminine au XIXe siècle",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Au XIXe siècle, quelle restriction légale s'appliquait aux femmes mariées en France (Code civil napoléonien) ?",
    options: [
      { id: 'a', text: "Elles ne pouvaient pas travailler dans les usines", isCorrect: false },
      { id: 'b', text: "Elles étaient sous l'autorité de leur mari pour signer des contrats, ouvrir un compte ou travailler", isCorrect: true },
      { id: 'c', text: "Elles ne pouvaient pas habiter en ville", isCorrect: false },
      { id: 'd', text: "Elles ne pouvaient pas accéder à l'école primaire", isCorrect: false },
    ],
    correctAnswer: "Elles étaient sous l'autorité de leur mari pour signer des contrats, ouvrir un compte ou travailler",
    explanation: "Le Code civil de Napoléon (1804) plaçait la femme mariée sous l'autorité (puissance maritale) de son mari. Elle ne pouvait ni travailler ni ouvrir un compte sans son accord. Ce statut ne changera qu'en 1965.",
    hint: "Code civil 1804 = femme mariée sous tutelle de son mari.",
    estimatedMinutes: 1,
    adaptations: A,
  },

  {
    id: 'hg-cm2-hist-ind-020',
    subject: 'histoire_geo',
    title: "Louis Pasteur",
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'histoire',
    subskill: 'revolution_industrielle',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Louis Pasteur (1822-1895) est l'un des plus grands scientifiques français. Parmi ses découvertes, laquelle est la plus célèbre ?",
    options: [
      { id: 'a', text: "La théorie de la relativité", isCorrect: false },
      { id: 'b', text: "La pasteurisation et le vaccin contre la rage", isCorrect: true },
      { id: 'c', text: "La radioactivité", isCorrect: false },
      { id: 'd', text: "La pénicilline", isCorrect: false },
    ],
    correctAnswer: "La pasteurisation et le vaccin contre la rage",
    explanation: "Louis Pasteur démontra la théorie des germes (les microbes causent les maladies), inventa la pasteurisation (chauffage pour tuer les bactéries) et développa des vaccins (rage, choléra des poules…).",
    hint: "Pasteur → pasteurisation + vaccin contre la rage.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
