import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCe2CorpsExercises: ScienceExercise[] = [
  {
    id: 'sc-ce2-cor-001',
    subject: 'sciences',
    title: 'Squelette : os du bras',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'squelette',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment s\'appelle l\'os du bras qui va du coude au poignet (côté pouce) ?',
    options: [
      { id: 'a', text: 'Le fémur', isCorrect: false },
      { id: 'b', text: 'Le radius', isCorrect: true },
      { id: 'c', text: 'Le tibia', isCorrect: false },
    ],
    correctAnswer: 'Le radius',
    explanation: 'Le radius est l\'os de l\'avant-bras du côté du pouce. L\'autre os de l\'avant-bras s\'appelle le cubitus (ou ulna).',
    hint: 'C\'est l\'os qu\'on fracture souvent lors d\'une chute.',
    tags: ['ce2', 'sciences', 'corps', 'squelette', 'os', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-002',
    subject: 'sciences',
    title: 'Muscles : contraction',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'muscles',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il au niveau du biceps quand on plie le bras ?',
    options: [
      { id: 'a', text: 'Il se relâche', isCorrect: false },
      { id: 'b', text: 'Il se contracte (se raccourcit)', isCorrect: true },
      { id: 'c', text: 'Il n\'est pas utilisé', isCorrect: false },
    ],
    correctAnswer: 'Il se contracte (se raccourcit)',
    explanation: 'Quand on plie le bras, le biceps se contracte (se raccourcit) et le triceps se relâche. Les muscles travaillent en paires.',
    hint: 'Fais le geste et sens ton biceps gonfler.',
    tags: ['ce2', 'sciences', 'corps', 'muscles', 'mouvement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-003',
    subject: 'sciences',
    title: 'Digestion : estomac',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'digestion',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle de l\'estomac dans la digestion ?',
    options: [
      { id: 'a', text: 'Absorber les nutriments dans le sang', isCorrect: false },
      { id: 'b', text: 'Broyer et mélanger les aliments avec des sucs digestifs', isCorrect: true },
      { id: 'c', text: 'Éliminer les déchets', isCorrect: false },
    ],
    correctAnswer: 'Broyer et mélanger les aliments avec des sucs digestifs',
    explanation: 'L\'estomac broie les aliments et les mélange avec des sucs acides. Les aliments y restent 2 à 4 heures.',
    hint: 'C\'est comme un mixeur dans ton ventre.',
    tags: ['ce2', 'sciences', 'corps', 'digestion', 'estomac', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-004',
    subject: 'sciences',
    title: 'Circulation sanguine : cœur',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'circulation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de fois environ le cœur bat-il par minute au repos ?',
    options: [
      { id: 'a', text: '10 fois', isCorrect: false },
      { id: 'b', text: '70 fois', isCorrect: true },
      { id: 'c', text: '200 fois', isCorrect: false },
    ],
    correctAnswer: '70 fois',
    explanation: 'Au repos, le cœur bat environ 60 à 80 fois par minute. À l\'effort, il peut dépasser 180 battements par minute.',
    hint: 'Pose ta main sur ta poitrine et compte les battements.',
    tags: ['ce2', 'sciences', 'corps', 'circulation', 'coeur', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-005',
    subject: 'sciences',
    title: 'Respiration : poumons',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'respiration',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que les poumons font lors de la respiration ?',
    options: [
      { id: 'a', text: 'Ils fabriquent du sang', isCorrect: false },
      { id: 'b', text: 'Ils permettent d\'absorber l\'oxygène et de rejeter le CO₂', isCorrect: true },
      { id: 'c', text: 'Ils digèrent les aliments', isCorrect: false },
    ],
    correctAnswer: 'Ils permettent d\'absorber l\'oxygène et de rejeter le CO₂',
    explanation: 'Les poumons échangent les gaz : ils absorbent l\'oxygène de l\'air et rejettent le dioxyde de carbone (CO₂).',
    hint: 'On inspire de l\'O₂ et on expire du CO₂.',
    tags: ['ce2', 'sciences', 'corps', 'respiration', 'poumons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-006',
    subject: 'sciences',
    title: 'Hygiène : sommeil',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien d\'heures de sommeil environ un enfant de CE2 doit-il dormir chaque nuit ?',
    options: [
      { id: 'a', text: '5 heures', isCorrect: false },
      { id: 'b', text: '9 à 11 heures', isCorrect: true },
      { id: 'c', text: '15 heures', isCorrect: false },
    ],
    correctAnswer: '9 à 11 heures',
    explanation: 'Les enfants de 7-9 ans ont besoin de 9 à 11 heures de sommeil pour grandir, mémoriser et être en forme.',
    hint: 'Plus que les adultes, qui dorment 7 à 8 heures.',
    tags: ['ce2', 'sciences', 'corps', 'hygiene', 'sommeil', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-007',
    subject: 'sciences',
    title: 'Nutrition : glucides',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'nutrition',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel groupe d\'aliments fournit principalement l\'énergie au corps ?',
    options: [
      { id: 'a', text: 'Les légumes verts', isCorrect: false },
      { id: 'b', text: 'Les glucides (pain, pâtes, riz, sucres)', isCorrect: true },
      { id: 'c', text: 'L\'eau', isCorrect: false },
    ],
    correctAnswer: 'Les glucides (pain, pâtes, riz, sucres)',
    explanation: 'Les glucides (sucres lents et rapides) sont le carburant du corps. Le cerveau et les muscles en ont besoin.',
    hint: 'Ce sont les « carburants » de notre corps.',
    tags: ['ce2', 'sciences', 'corps', 'nutrition', 'glucides', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-008',
    subject: 'sciences',
    title: 'Organes des sens : oreille',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie de l\'oreille vibre quand elle reçoit des sons ?',
    options: [
      { id: 'a', text: 'Le nerf optique', isCorrect: false },
      { id: 'b', text: 'Le tympan', isCorrect: true },
      { id: 'c', text: 'La cornée', isCorrect: false },
    ],
    correctAnswer: 'Le tympan',
    explanation: 'Le tympan est une membrane fine qui vibre sous l\'effet des ondes sonores. Ces vibrations sont transmises au cerveau.',
    hint: 'Il ressemble à une peau de tambour tendue.',
    tags: ['ce2', 'sciences', 'corps', 'sens', 'oreille', 'tympan', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-009',
    subject: 'sciences',
    title: 'Système nerveux : cerveau',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'systeme-nerveux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle principal du cerveau ?',
    options: [
      { id: 'a', text: 'Pomper le sang dans le corps', isCorrect: false },
      { id: 'b', text: 'Contrôler et coordonner toutes les fonctions du corps', isCorrect: true },
      { id: 'c', text: 'Filtrer le sang', isCorrect: false },
    ],
    correctAnswer: 'Contrôler et coordonner toutes les fonctions du corps',
    explanation: 'Le cerveau reçoit des informations des sens, les traite et envoie des ordres aux muscles et aux organes.',
    hint: 'C\'est le « chef d\'orchestre » du corps humain.',
    tags: ['ce2', 'sciences', 'corps', 'cerveau', 'systeme-nerveux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-010',
    subject: 'sciences',
    title: 'Squelette : rôle des os',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'squelette',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le principal rôle du squelette ?',
    options: [
      { id: 'a', text: 'Produire de la chaleur', isCorrect: false },
      { id: 'b', text: 'Soutenir le corps, le protéger et permettre les mouvements', isCorrect: true },
      { id: 'c', text: 'Absorber les aliments', isCorrect: false },
    ],
    correctAnswer: 'Soutenir le corps, le protéger et permettre les mouvements',
    explanation: 'Le squelette soutient le corps, protège les organes (le crâne protège le cerveau) et sert d\'attache aux muscles.',
    hint: 'Sans squelette, on serait comme une méduse.',
    tags: ['ce2', 'sciences', 'corps', 'squelette', 'os', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-011',
    subject: 'sciences',
    title: 'Hygiène : dents',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi doit-on se brosser les dents après les repas ?',
    options: [
      { id: 'a', text: 'Pour les blanchir uniquement', isCorrect: false },
      { id: 'b', text: 'Pour éliminer les restes d\'aliments qui causent des caries', isCorrect: true },
      { id: 'c', text: 'Pour mieux goûter les aliments', isCorrect: false },
    ],
    correctAnswer: 'Pour éliminer les restes d\'aliments qui causent des caries',
    explanation: 'Les restes d\'aliments nourrissent des bactéries qui attaquent l\'émail des dents et causent des caries.',
    hint: 'Les bactéries adorent le sucre laissé sur les dents.',
    tags: ['ce2', 'sciences', 'corps', 'hygiene', 'dents', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-012',
    subject: 'sciences',
    title: 'Activité physique : bienfaits',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est l\'un des bienfaits de la pratique régulière du sport ?',
    options: [
      { id: 'a', text: 'Affaiblir le cœur', isCorrect: false },
      { id: 'b', text: 'Renforcer les muscles, le cœur et améliorer l\'humeur', isCorrect: true },
      { id: 'c', text: 'Diminuer la mémoire', isCorrect: false },
    ],
    correctAnswer: 'Renforcer les muscles, le cœur et améliorer l\'humeur',
    explanation: 'Le sport renforce les muscles et le cœur, améliore la respiration, libère des endorphines (hormone du bonheur).',
    hint: 'On se sent toujours mieux après avoir bougé.',
    tags: ['ce2', 'sciences', 'corps', 'sport', 'hygiene', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-013',
    subject: 'sciences',
    title: 'Respiration : fréquence',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'respiration',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de fois environ respire-t-on par minute au repos ?',
    options: [
      { id: 'a', text: '3 à 5 fois', isCorrect: false },
      { id: 'b', text: '15 à 20 fois', isCorrect: true },
      { id: 'c', text: '60 fois', isCorrect: false },
    ],
    correctAnswer: '15 à 20 fois',
    explanation: 'Au repos, un adulte respire 15 à 20 fois par minute. À l\'effort, la respiration s\'accélère pour apporter plus d\'oxygène.',
    hint: 'Essaie de compter tes respirations pendant une minute.',
    tags: ['ce2', 'sciences', 'corps', 'respiration', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-014',
    subject: 'sciences',
    title: 'Digestion : rôle de la bouche',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'digestion',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le premier organe qui digère les aliments ?',
    options: [
      { id: 'a', text: 'L\'estomac', isCorrect: false },
      { id: 'b', text: 'La bouche (dents + salive)', isCorrect: true },
      { id: 'c', text: 'L\'intestin', isCorrect: false },
    ],
    correctAnswer: 'La bouche (dents + salive)',
    explanation: 'La bouche commence la digestion : les dents broient les aliments et la salive les ramollit et commence à les décomposer chimiquement.',
    hint: 'Bien mâcher est la première étape de la digestion.',
    tags: ['ce2', 'sciences', 'corps', 'digestion', 'bouche', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-015',
    subject: 'sciences',
    title: 'Puberté : introduction',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'croissance',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quelle période de la vie le corps de l\'enfant se transforme-t-il en corps d\'adulte ?',
    options: [
      { id: 'a', text: 'À la naissance', isCorrect: false },
      { id: 'b', text: 'À la puberté (entre 8 et 16 ans environ)', isCorrect: true },
      { id: 'c', text: 'À 30 ans', isCorrect: false },
    ],
    correctAnswer: 'À la puberté (entre 8 et 16 ans environ)',
    explanation: 'La puberté est une période de transformation physique et hormonale qui prépare le corps à la reproduction.',
    hint: 'Ça arrive après l\'école primaire pour beaucoup.',
    tags: ['ce2', 'sciences', 'corps', 'puberte', 'croissance', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-016',
    subject: 'sciences',
    title: 'Muscles : paires antagonistes',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'muscles',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand le biceps se contracte pour plier le bras, que fait le triceps ?',
    options: [
      { id: 'a', text: 'Il se contracte aussi', isCorrect: false },
      { id: 'b', text: 'Il se relâche', isCorrect: true },
      { id: 'c', text: 'Il ne fait rien', isCorrect: false },
    ],
    correctAnswer: 'Il se relâche',
    explanation: 'Les muscles travaillent en paires antagonistes : quand l\'un se contracte, l\'autre se relâche. Biceps et triceps sont antagonistes.',
    hint: 'Antagoniste = qui s\'oppose. L\'un contracte, l\'autre étire.',
    tags: ['ce2', 'sciences', 'corps', 'muscles', 'antagonistes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-017',
    subject: 'sciences',
    title: 'Nutrition : lipides et glucides',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'nutrition',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces aliments est principalement riche en glucides (sucres) ?',
    options: [
      { id: 'a', text: 'Le beurre', isCorrect: false },
      { id: 'b', text: 'Le pain', isCorrect: true },
      { id: 'c', text: 'Le steak', isCorrect: false },
    ],
    correctAnswer: 'Le pain',
    explanation: 'Le pain est riche en glucides (amidon). Le beurre contient des lipides (graisses) et le steak des protéines.',
    hint: 'L\'amidon est le glucide principal du pain et des pâtes.',
    tags: ['ce2', 'sciences', 'corps', 'nutrition', 'glucides', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-018',
    subject: 'sciences',
    title: 'Santé : microbes et hygiène',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un microbe (micro-organisme pathogène) ?',
    options: [
      { id: 'a', text: 'Un minuscule animal visible à l\'œil nu', isCorrect: false },
      { id: 'b', text: 'Un être vivant trop petit pour être vu à l\'œil nu qui peut rendre malade', isCorrect: true },
      { id: 'c', text: 'Un champignon géant', isCorrect: false },
    ],
    correctAnswer: 'Un être vivant trop petit pour être vu à l\'œil nu qui peut rendre malade',
    explanation: 'Les microbes (virus, bactéries) sont invisibles à l\'œil nu. On les observe au microscope. Certains causent des maladies.',
    hint: 'On a besoin d\'un microscope pour les voir.',
    tags: ['ce2', 'sciences', 'corps', 'hygiene', 'microbes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-019',
    subject: 'sciences',
    title: 'Squelette : nombre d\'os',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'squelette',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien d\'os compte environ le squelette d\'un adulte humain ?',
    options: [
      { id: 'a', text: '50', isCorrect: false },
      { id: 'b', text: '206', isCorrect: true },
      { id: 'c', text: '500', isCorrect: false },
    ],
    correctAnswer: '206',
    explanation: 'Le squelette adulte compte environ 206 os. Le bébé en a plus (environ 270) car certains os fusionnent en grandissant.',
    hint: 'Plus qu\'on ne le croit : chaque pied compte 26 os.',
    tags: ['ce2', 'sciences', 'corps', 'squelette', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-020',
    subject: 'sciences',
    title: 'Organes : foie et bile',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'digestion',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel liquide le foie produit-il pour aider à digérer les graisses ?',
    options: [
      { id: 'a', text: 'Le suc gastrique', isCorrect: false },
      { id: 'b', text: 'La bile', isCorrect: true },
      { id: 'c', text: 'La salive', isCorrect: false },
    ],
    correctAnswer: 'La bile',
    explanation: 'Le foie produit la bile, stockée dans la vésicule biliaire. La bile est déversée dans l\'intestin pour émulsionner et digérer les graisses.',
    hint: 'La bile rend les graisses solubles dans l\'eau.',
    tags: ['ce2', 'sciences', 'corps', 'digestion', 'foie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-021',
    subject: 'sciences',
    title: 'Circulation : globules rouges',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'circulation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le rôle des globules rouges dans le sang ?',
    options: [
      { id: 'a', text: 'Combattre les microbes', isCorrect: false },
      { id: 'b', text: 'Transporter l\'oxygène des poumons vers les organes', isCorrect: true },
      { id: 'c', text: 'Absorber les nutriments de l\'intestin', isCorrect: false },
    ],
    correctAnswer: 'Transporter l\'oxygène des poumons vers les organes',
    explanation: 'Les globules rouges contiennent l\'hémoglobine, une protéine rouge qui capture l\'O₂ dans les poumons et le libère dans les organes.',
    hint: 'C\'est l\'hémoglobine qui donne au sang sa couleur rouge.',
    tags: ['ce2', 'sciences', 'corps', 'circulation', 'globules-rouges', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-022',
    subject: 'sciences',
    title: 'Santé : vaccination schéma',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'sante',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi certains vaccins nécessitent-ils plusieurs injections (rappels) ?',
    options: [
      { id: 'a', text: 'Parce que le premier vaccin ne fonctionne pas', isCorrect: false },
      { id: 'b', text: 'Pour renforcer et prolonger la protection immunitaire', isCorrect: true },
      { id: 'c', text: 'Parce qu\'on change le type de vaccin à chaque fois', isCorrect: false },
    ],
    correctAnswer: 'Pour renforcer et prolonger la protection immunitaire',
    explanation: 'Un rappel relance la production d\'anticorps, ce qui maintient une protection durable contre la maladie sur de nombreuses années.',
    hint: 'Le rappel "rafraîchit" la mémoire du système immunitaire.',
    tags: ['ce2', 'sciences', 'corps', 'sante', 'vaccination', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-023',
    subject: 'sciences',
    title: 'Sens : proprioception',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment le corps sait-il où se trouvent ses membres sans les regarder (ex : toucher son nez les yeux fermés) ?',
    options: [
      { id: 'a', text: 'Par l\'odorat', isCorrect: false },
      { id: 'b', text: 'Par la proprioception (sens de la position du corps)', isCorrect: true },
      { id: 'c', text: 'Par la mémoire uniquement', isCorrect: false },
    ],
    correctAnswer: 'Par la proprioception (sens de la position du corps)',
    explanation: 'La proprioception est un sixième sens : des capteurs dans les muscles et les articulations informent le cerveau de la position des membres.',
    hint: 'Les sportifs l\'entraînent beaucoup : équilibre, coordination.',
    tags: ['ce2', 'sciences', 'corps', 'sens', 'proprioception', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-024',
    subject: 'sciences',
    title: 'Corps : les reins',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'organes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où sont situés les reins dans le corps ?',
    options: [
      { id: 'a', text: 'Dans la poitrine, de chaque côté du cœur', isCorrect: false },
      { id: 'b', text: 'Dans le dos, de chaque côté de la colonne vertébrale', isCorrect: true },
      { id: 'c', text: 'Dans le ventre, sous l\'estomac', isCorrect: false },
    ],
    correctAnswer: 'Dans le dos, de chaque côté de la colonne vertébrale',
    explanation: 'Les deux reins sont situés dans le bas du dos, de part et d\'autre de la colonne vertébrale. Ils filtrent le sang et produisent l\'urine.',
    hint: 'On les sent parfois quand on les surmène (douleurs lombaires).',
    tags: ['ce2', 'sciences', 'corps', 'organes', 'reins', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-025',
    subject: 'sciences',
    title: 'Corps : peau et sueur',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'thermoregulation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi sue-t-on quand il fait très chaud ou qu\'on fait du sport ?',
    options: [
      { id: 'a', text: 'Pour éliminer les microbes par la peau', isCorrect: false },
      { id: 'b', text: 'Pour refroidir le corps par l\'évaporation de la sueur', isCorrect: true },
      { id: 'c', text: 'Pour nourrir la peau en eau', isCorrect: false },
    ],
    correctAnswer: 'Pour refroidir le corps par l\'évaporation de la sueur',
    explanation: 'En évaporant, la sueur absorbe de la chaleur corporelle et refroidit la peau. C\'est un système de climatisation naturel.',
    hint: 'Souffler sur sa peau mouillée la rafraîchit.',
    tags: ['ce2', 'sciences', 'corps', 'thermoregulation', 'peau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-cor-026',
    subject: 'sciences',
    title: 'Corps : sommeil et mémoire',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'corps',
    subskill: 'cerveau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel rôle joue le sommeil pour le cerveau des enfants ?',
    options: [
      { id: 'a', text: 'Le cerveau s\'arrête complètement de fonctionner', isCorrect: false },
      { id: 'b', text: 'Le cerveau consolide les apprentissages et élimine les déchets', isCorrect: true },
      { id: 'c', text: 'Le cerveau diminue de taille pour se reposer', isCorrect: false },
    ],
    correctAnswer: 'Le cerveau consolide les apprentissages et élimine les déchets',
    explanation: 'Pendant le sommeil, le cerveau trie les informations de la journée, consolide les souvenirs et élimine les déchets métaboliques accumulés.',
    hint: 'On retient mieux une leçon apprise la veille après une bonne nuit.',
    tags: ['ce2', 'sciences', 'corps', 'cerveau', 'sommeil', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
