import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCe2EnvironnementExercises: ScienceExercise[] = [
  {
    id: 'sc-ce2-env-001',
    subject: 'sciences',
    title: 'États de l\'eau',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sous combien de formes différentes l\'eau peut-elle exister ?',
    options: [
      { id: 'a', text: '1 (liquide seulement)', isCorrect: false },
      { id: 'b', text: '3 (liquide, solide, gazeuse)', isCorrect: true },
      { id: 'c', text: '2 (liquide et solide)', isCorrect: false },
    ],
    correctAnswer: '3 (liquide, solide, gazeuse)',
    explanation: 'L\'eau existe sous 3 formes : liquide (rivière), solide (glace) et gazeuse (vapeur).',
    hint: 'Pense à l\'eau du robinet, à la glace et à la vapeur d\'eau.',
    tags: ['ce2', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['L\'eau liquide : rivière.', 'L\'eau solide : glace.', 'L\'eau gazeuse : vapeur. → 3 formes.'] },
    }),
  },

    {
    id: 'sc-ce2-env-002',
    subject: 'sciences',
    title: 'Eau solide',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on l\'eau à l\'état solide ?',
    options: [
      { id: 'a', text: 'La vapeur', isCorrect: false },
      { id: 'b', text: 'La glace', isCorrect: true },
      { id: 'c', text: 'La buée', isCorrect: false },
    ],
    correctAnswer: 'La glace',
    explanation: 'Quand l\'eau gèle (en dessous de 0°C), elle devient de la glace, qui est solide.',
    hint: 'On en met dans les boissons fraîches.',
    tags: ['ce2', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce2-env-003',
    subject: 'sciences',
    title: 'Origine de la pluie',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où vient la pluie ?',
    options: [
      { id: 'a', text: 'Du vent', isCorrect: false },
      { id: 'b', text: 'Des nuages', isCorrect: true },
      { id: 'c', text: 'Des étoiles', isCorrect: false },
    ],
    correctAnswer: 'Des nuages',
    explanation: 'La pluie tombe des nuages. Les nuages sont formés de petites gouttes d\'eau.',
    hint: 'Regarde ce qui est dans le ciel quand il pleut.',
    tags: ['ce2', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce2-env-004',
    subject: 'sciences',
    title: 'Saison après l\'hiver',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle saison vient juste après l\'hiver ?',
    options: [
      { id: 'a', text: 'L\'automne', isCorrect: false },
      { id: 'b', text: 'L\'été', isCorrect: false },
      { id: 'c', text: 'Le printemps', isCorrect: true },
    ],
    correctAnswer: 'Le printemps',
    explanation: 'L\'ordre des saisons est : printemps → été → automne → hiver → printemps…',
    hint: 'C\'est la saison où la nature se réveille.',
    tags: ['ce2', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce2-env-005',
    subject: 'sciences',
    title: 'Hiver : phénomène naturel',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel phénomène naturel peut se produire en hiver ?',
    options: [
      { id: 'a', text: 'Les fleurs éclosent', isCorrect: false },
      { id: 'b', text: 'Il neige', isCorrect: true },
      { id: 'c', text: 'Les feuilles tombent', isCorrect: false },
    ],
    correctAnswer: 'Il neige',
    explanation: 'En hiver, il peut neiger car les températures sont très basses. Les feuilles tombent en automne, les fleurs éclosent au printemps.',
    hint: 'C\'est la saison la plus froide.',
    tags: ['ce2', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce2-env-006',
    subject: 'sciences',
    title: 'Saison la plus chaude',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison fait-il le plus chaud en France ?',
    options: [
      { id: 'a', text: 'Au printemps', isCorrect: false },
      { id: 'b', text: 'En été', isCorrect: true },
      { id: 'c', text: 'En hiver', isCorrect: false },
    ],
    correctAnswer: 'En été',
    explanation: 'En France, l\'été est la saison la plus chaude. Les journées sont longues et ensoleillées.',
    hint: 'C\'est quand on part en vacances à la mer.',
    tags: ['ce2', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce2-env-007',
    subject: 'sciences',
    title: 'Météo : brouillard',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel temps fait-il quand on ne voit pas loin à cause d\'une brume blanche au sol ?',
    options: [
      { id: 'a', text: 'Il y a du vent', isCorrect: false },
      { id: 'b', text: 'Il y a du brouillard', isCorrect: true },
      { id: 'c', text: 'Il fait très beau', isCorrect: false },
    ],
    correctAnswer: 'Il y a du brouillard',
    explanation: 'Le brouillard, c\'est un nuage au ras du sol. Il réduit la visibilité et rend les routes dangereuses.',
    hint: 'On n\'y voit pas loin, comme dans un nuage.',
    tags: ['ce2', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-ce2-env-008',
    subject: 'sciences',
    title: 'Météo : arc-en-ciel',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand voit-on généralement un arc-en-ciel ?',
    options: [
      { id: 'a', text: 'Quand il neige', isCorrect: false },
      { id: 'b', text: 'Après la pluie, quand le soleil revient', isCorrect: true },
      { id: 'c', text: 'La nuit', isCorrect: false },
    ],
    correctAnswer: 'Après la pluie, quand le soleil revient',
    explanation: 'Un arc-en-ciel se forme quand les rayons du soleil traversent les gouttes de pluie encore en suspension dans l\'air.',
    hint: 'Il faut de la pluie ET du soleil en même temps.',
    tags: ['ce2', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-009',
    subject: 'sciences',
    title: 'Cycle de l\'eau complet',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la bonne séquence du cycle de l\'eau ?',
    options: [
      { id: 'a', text: 'Pluie → évaporation → nuages', isCorrect: false },
      { id: 'b', text: 'Évaporation → condensation (nuages) → précipitations (pluie)', isCorrect: true },
      { id: 'c', text: 'Condensation → évaporation → pluie', isCorrect: false },
    ],
    correctAnswer: 'Évaporation → condensation (nuages) → précipitations (pluie)',
    explanation: 'L\'eau s\'évapore, monte, forme des nuages (condensation) et retombe en pluie ou neige (précipitations).',
    hint: 'Commence par ce que le soleil fait à l\'eau.',
    tags: ['ce2', 'sciences', 'eau', 'cycle-eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-010',
    subject: 'sciences',
    title: 'Volcans et séismes',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un volcan ?',
    options: [
      { id: 'a', text: 'Une grande montagne recouverte de neige', isCorrect: false },
      { id: 'b', text: 'Une ouverture dans la croûte terrestre par où sort de la lave', isCorrect: true },
      { id: 'c', text: 'Une île au milieu de la mer', isCorrect: false },
    ],
    correctAnswer: 'Une ouverture dans la croûte terrestre par où sort de la lave',
    explanation: 'Un volcan est une ouverture dans la Terre. Lors d\'une éruption, il projette de la lave, de la cendre et des gaz.',
    hint: 'La lave est de la roche fondue très chaude.',
    tags: ['ce2', 'sciences', 'terre', 'volcan', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-011',
    subject: 'sciences',
    title: 'Pollution de l\'air',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle activité humaine pollue fortement l\'air ?',
    options: [
      { id: 'a', text: 'Planter des arbres', isCorrect: false },
      { id: 'b', text: 'Les voitures à essence et les usines', isCorrect: true },
      { id: 'c', text: 'Faire du vélo', isCorrect: false },
    ],
    correctAnswer: 'Les voitures à essence et les usines',
    explanation: 'Les voitures et les usines dégagent des gaz polluants qui contaminent l\'air que nous respirons.',
    hint: 'Ces activités brûlent du pétrole ou du charbon.',
    tags: ['ce2', 'sciences', 'environnement', 'pollution', 'air', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-012',
    subject: 'sciences',
    title: 'Terre : les pôles',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal vit au pôle Nord ?',
    options: [
      { id: 'a', text: 'Le pingouin', isCorrect: false },
      { id: 'b', text: 'L\'ours polaire', isCorrect: true },
      { id: 'c', text: 'Le kangourou', isCorrect: false },
    ],
    correctAnswer: 'L\'ours polaire',
    explanation: 'L\'ours polaire vit au pôle Nord (Arctique). Le pingouin vit au pôle Sud (Antarctique).',
    hint: 'On le confond souvent avec le pingouin.',
    tags: ['ce2', 'sciences', 'terre', 'poles', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-013',
    subject: 'sciences',
    title: 'Ressources naturelles : forêt',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les forêts sont-elles importantes pour l\'environnement ?',
    options: [
      { id: 'a', text: 'Parce qu\'elles produisent du pétrole', isCorrect: false },
      { id: 'b', text: 'Parce qu\'elles produisent de l\'oxygène et abritent des animaux', isCorrect: true },
      { id: 'c', text: 'Parce qu\'elles empêchent la pluie', isCorrect: false },
    ],
    correctAnswer: 'Parce qu\'elles produisent de l\'oxygène et abritent des animaux',
    explanation: 'Les forêts produisent de l\'oxygène, absorbent du CO₂, régulent le climat et abritent une grande biodiversité.',
    hint: 'Les arbres "respirent" eux aussi.',
    tags: ['ce2', 'sciences', 'environnement', 'foret', 'oxygene', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-014',
    subject: 'sciences',
    title: 'Météo : les saisons et le soleil',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les jours sont-ils plus longs en été qu\'en hiver ?',
    options: [
      { id: 'a', text: 'Parce que la Terre tourne plus vite en été', isCorrect: false },
      { id: 'b', text: 'Parce que la Terre est inclinée et se trouve différemment par rapport au soleil', isCorrect: true },
      { id: 'c', text: 'Parce que le soleil se lève plus tôt depuis toujours', isCorrect: false },
    ],
    correctAnswer: 'Parce que la Terre est inclinée et se trouve différemment par rapport au soleil',
    explanation: 'L\'inclinaison de la Terre cause les saisons. En été, notre hémisphère est plus orienté vers le soleil : les jours sont plus longs.',
    hint: 'La Terre est inclinée par rapport au soleil.',
    tags: ['ce2', 'sciences', 'saisons', 'soleil', 'terre', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-015',
    subject: 'sciences',
    title: 'Eau : eau douce et eau salée',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle proportion de l\'eau sur Terre est douce (non salée) ?',
    options: [
      { id: 'a', text: 'Plus de la moitié', isCorrect: false },
      { id: 'b', text: 'Environ 3 %', isCorrect: true },
      { id: 'c', text: 'Environ 50 %', isCorrect: false },
    ],
    correctAnswer: 'Environ 3 %',
    explanation: 'Seulement 3 % de l\'eau sur Terre est douce. La grande majorité est l\'eau salée des océans.',
    hint: 'L\'eau douce est très rare sur Terre.',
    tags: ['ce2', 'sciences', 'eau', 'eau-douce', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-016',
    subject: 'sciences',
    title: 'Énergie : le soleil',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'energie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que sont les panneaux solaires ?',
    options: [
      { id: 'a', text: 'Des appareils qui chauffent l\'eau uniquement', isCorrect: false },
      { id: 'b', text: 'Des appareils qui transforment la lumière du soleil en électricité', isCorrect: true },
      { id: 'c', text: 'Des miroirs pour faire de la lumière', isCorrect: false },
    ],
    correctAnswer: 'Des appareils qui transforment la lumière du soleil en électricité',
    explanation: 'Les panneaux solaires captent les rayons du soleil et produisent de l\'électricité. C\'est une énergie renouvelable.',
    hint: 'On les voit souvent sur les toits des maisons.',
    tags: ['ce2', 'sciences', 'energie', 'solaire', 'renouvelable', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-017',
    subject: 'sciences',
    title: 'Sol et érosion',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment la pluie et le vent peuvent-ils modifier le paysage ?',
    options: [
      { id: 'a', text: 'Ils n\'ont aucun effet sur la roche', isCorrect: false },
      { id: 'b', text: 'Ils érodent (usent) les roches et déplacent le sol', isCorrect: true },
      { id: 'c', text: 'Ils créent des volcans', isCorrect: false },
    ],
    correctAnswer: 'Ils érodent (usent) les roches et déplacent le sol',
    explanation: 'L\'érosion est le processus par lequel la pluie, le vent et les rivières usent les roches et modifient les paysages.',
    hint: 'L\'eau creuse des canyons au fil du temps.',
    tags: ['ce2', 'sciences', 'terre', 'erosion', 'paysages', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-env-018',
    subject: 'sciences',
    title: 'Dangers naturels : tremblement de terre',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le mouvement brusque du sol causé par des mouvements dans la croûte terrestre ?',
    options: [
      { id: 'a', text: 'Un ouragan', isCorrect: false },
      { id: 'b', text: 'Un tremblement de terre (séisme)', isCorrect: true },
      { id: 'c', text: 'Une éclipse', isCorrect: false },
    ],
    correctAnswer: 'Un tremblement de terre (séisme)',
    explanation: 'Un séisme est provoqué par des mouvements des plaques tectoniques. Il peut causer de graves destructions.',
    hint: 'Le sol se met à vibrer et secouer.',
    tags: ['ce2', 'sciences', 'terre', 'seisme', 'dangers', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
