import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCe2MatiereExercises: ScienceExercise[] = [
  {
    id: 'sc-ce2-mat-001',
    subject: 'sciences',
    title: 'Changements d\'état : évaporation',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'changements-etat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment s\'appelle le passage de l\'eau liquide à l\'état gazeux (vapeur d\'eau) ?',
    options: [
      { id: 'a', text: 'La solidification', isCorrect: false },
      { id: 'b', text: 'L\'évaporation', isCorrect: true },
      { id: 'c', text: 'La condensation', isCorrect: false },
    ],
    correctAnswer: 'L\'évaporation',
    explanation: 'L\'évaporation est le passage du liquide au gaz. L\'eau d\'une flaque s\'évapore sous l\'effet de la chaleur.',
    hint: 'Les flaques disparaissent par temps chaud.',
    tags: ['ce2', 'sciences', 'matiere', 'evaporation', 'changements-etat', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-002',
    subject: 'sciences',
    title: 'Changements d\'état : condensation',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'changements-etat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi y a-t-il de la buée sur un miroir après une douche ?',
    options: [
      { id: 'a', text: 'Parce que le miroir transpire', isCorrect: false },
      { id: 'b', text: 'Parce que la vapeur d\'eau se condense au contact du miroir froid', isCorrect: true },
      { id: 'c', text: 'Parce que le savon a éclaboussé le miroir', isCorrect: false },
    ],
    correctAnswer: 'Parce que la vapeur d\'eau se condense au contact du miroir froid',
    explanation: 'La condensation est le passage du gaz au liquide. La vapeur chaude se transforme en gouttelettes au contact d\'une surface froide.',
    hint: 'On voit aussi ça sur un verre de soda froid en été.',
    tags: ['ce2', 'sciences', 'matiere', 'condensation', 'changements-etat', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-003',
    subject: 'sciences',
    title: 'Mélanges : soluble ou non',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'melanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces solides est insoluble dans l\'eau ?',
    options: [
      { id: 'a', text: 'Le sucre', isCorrect: false },
      { id: 'b', text: 'Le sel', isCorrect: false },
      { id: 'c', text: 'La farine', isCorrect: true },
    ],
    correctAnswer: 'La farine',
    explanation: 'La farine ne se dissout pas dans l\'eau : elle forme un mélange trouble (suspension). Le sucre et le sel, eux, se dissolvent.',
    hint: 'La farine dans l\'eau reste visible.',
    tags: ['ce2', 'sciences', 'matiere', 'melanges', 'solubilite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-004',
    subject: 'sciences',
    title: 'Air : composition',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'air',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel gaz est le plus abondant dans l\'air ?',
    options: [
      { id: 'a', text: 'L\'oxygène (O₂)', isCorrect: false },
      { id: 'b', text: 'L\'azote (N₂)', isCorrect: true },
      { id: 'c', text: 'Le dioxyde de carbone (CO₂)', isCorrect: false },
    ],
    correctAnswer: 'L\'azote (N₂)',
    explanation: 'L\'air est composé d\'environ 78 % d\'azote, 21 % d\'oxygène et 1 % d\'autres gaz. On ne respire donc pas que de l\'oxygène.',
    hint: 'Ce n\'est pas celui qu\'on respire principalement.',
    tags: ['ce2', 'sciences', 'matiere', 'air', 'composition', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-005',
    subject: 'sciences',
    title: 'Matériaux : conducteur électrique',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces matériaux laisse passer le courant électrique ?',
    options: [
      { id: 'a', text: 'Le plastique', isCorrect: false },
      { id: 'b', text: 'Le cuivre', isCorrect: true },
      { id: 'c', text: 'Le caoutchouc', isCorrect: false },
    ],
    correctAnswer: 'Le cuivre',
    explanation: 'Le cuivre est un conducteur électrique. C\'est pour ça que les fils électriques sont en cuivre, entourés de plastique isolant.',
    hint: 'Les fils électriques en sont souvent faits.',
    tags: ['ce2', 'sciences', 'matiere', 'electricite', 'conducteur', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-006',
    subject: 'sciences',
    title: 'Eau : température de fusion',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quelle température l\'eau se transforme-t-elle en glace ?',
    options: [
      { id: 'a', text: 'À -10°C', isCorrect: false },
      { id: 'b', text: 'À 0°C', isCorrect: true },
      { id: 'c', text: 'À 10°C', isCorrect: false },
    ],
    correctAnswer: 'À 0°C',
    explanation: 'L\'eau se solidifie (devient de la glace) à 0°C. En dessous de 0°C, l\'eau est à l\'état solide.',
    hint: 'C\'est le point de congélation de l\'eau.',
    tags: ['ce2', 'sciences', 'matiere', 'eau', 'congelation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-007',
    subject: 'sciences',
    title: 'Eau : ébullition',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quelle température l\'eau bout-elle à pression normale ?',
    options: [
      { id: 'a', text: '50°C', isCorrect: false },
      { id: 'b', text: '100°C', isCorrect: true },
      { id: 'c', text: '200°C', isCorrect: false },
    ],
    correctAnswer: '100°C',
    explanation: 'À 100°C (à pression atmosphérique), l\'eau entre en ébullition et se transforme en vapeur d\'eau.',
    hint: 'C\'est la température de l\'eau des pâtes bouillantes.',
    tags: ['ce2', 'sciences', 'matiere', 'eau', 'ebullition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-008',
    subject: 'sciences',
    title: 'Objets techniques : engrenage',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment fonctionne un engrenage ?',
    options: [
      { id: 'a', text: 'Des aimants font tourner les roues', isCorrect: false },
      { id: 'b', text: 'Des roues dentées s\'emboîtent et se font tourner mutuellement', isCorrect: true },
      { id: 'c', text: 'Un moteur électrique les entraîne toujours', isCorrect: false },
    ],
    correctAnswer: 'Des roues dentées s\'emboîtent et se font tourner mutuellement',
    explanation: 'Un engrenage est un ensemble de roues dentées qui s\'engrènent. Quand l\'une tourne, elle entraîne les autres.',
    hint: 'On en trouve dans les montres et les boîtes de vitesses.',
    tags: ['ce2', 'sciences', 'objets-techniques', 'engrenage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-009',
    subject: 'sciences',
    title: 'Lumière : ombre',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'lumiere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi un objet opaque crée-t-il une ombre derrière lui ?',
    options: [
      { id: 'a', text: 'Parce qu\'il absorbe toute la lumière', isCorrect: false },
      { id: 'b', text: 'Parce qu\'il bloque la lumière qui ne peut pas le traverser', isCorrect: true },
      { id: 'c', text: 'Parce qu\'il reflète la lumière vers le haut', isCorrect: false },
    ],
    correctAnswer: 'Parce qu\'il bloque la lumière qui ne peut pas le traverser',
    explanation: 'Un objet opaque ne laisse pas passer la lumière. La zone dans son dos, privée de lumière, forme une ombre.',
    hint: 'Ta main empêche la lumière de passer.',
    tags: ['ce2', 'sciences', 'matiere', 'lumiere', 'ombre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-010',
    subject: 'sciences',
    title: 'Matériaux : recyclage',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces matériaux ne se recycle PAS facilement ?',
    options: [
      { id: 'a', text: 'Le verre', isCorrect: false },
      { id: 'b', text: 'Le carton', isCorrect: false },
      { id: 'c', text: 'Le polystyrène expansé (mousse blanche)', isCorrect: true },
    ],
    correctAnswer: 'Le polystyrène expansé (mousse blanche)',
    explanation: 'Le polystyrène expansé est difficile à recycler. Le verre, le carton et le métal se recyclent facilement.',
    hint: 'Cette mousse blanche emballe souvent les appareils électroniques.',
    tags: ['ce2', 'sciences', 'matiere', 'materiaux', 'recyclage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-011',
    subject: 'sciences',
    title: 'Force : poussée',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'forces',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi un bouchon en liège flotte-t-il sur l\'eau ?',
    options: [
      { id: 'a', text: 'Parce qu\'il est aimanté', isCorrect: false },
      { id: 'b', text: 'Parce que l\'eau exerce une poussée vers le haut (poussée d\'Archimède)', isCorrect: true },
      { id: 'c', text: 'Parce qu\'il est léger et invisible', isCorrect: false },
    ],
    correctAnswer: 'Parce que l\'eau exerce une poussée vers le haut (poussée d\'Archimède)',
    explanation: 'L\'eau pousse les objets vers le haut. Si cet objet est moins dense que l\'eau, il flotte. Le liège est moins dense que l\'eau.',
    hint: 'Les bateaux flottent pour la même raison.',
    tags: ['ce2', 'sciences', 'matiere', 'forces', 'poussee', 'flottaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-012',
    subject: 'sciences',
    title: 'Objets techniques : levier du 2e genre',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une brouette est un exemple de levier. Où se trouve le point d\'appui (pivot) ?',
    options: [
      { id: 'a', text: 'Au milieu des bras de la brouette', isCorrect: false },
      { id: 'b', text: 'Sous la roue avant', isCorrect: true },
      { id: 'c', text: 'À l\'endroit où on pousse', isCorrect: false },
    ],
    correctAnswer: 'Sous la roue avant',
    explanation: 'La roue avant de la brouette est le point d\'appui. La charge est entre le pivot et l\'endroit où l\'on pousse : c\'est un levier du 2e genre.',
    hint: 'La roue de la brouette est son point de pivot.',
    tags: ['ce2', 'sciences', 'matiere', 'objets-techniques', 'levier', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-013',
    subject: 'sciences',
    title: 'Matière : densité',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'On pose un cube de bois et un cube de fer de même taille sur une balance. Lequel est plus lourd ?',
    options: [
      { id: 'a', text: 'Le cube de bois', isCorrect: false },
      { id: 'b', text: 'Le cube de fer', isCorrect: true },
      { id: 'c', text: 'Ils pèsent pareil', isCorrect: false },
    ],
    correctAnswer: 'Le cube de fer',
    explanation: 'Le fer est plus dense que le bois : à volume égal, il est plus lourd. La densité mesure la masse par volume.',
    hint: 'Un kilo de plumes et un kilo de plomb ont le même poids, mais pas le même volume.',
    tags: ['ce2', 'sciences', 'matiere', 'densite', 'masse', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-014',
    subject: 'sciences',
    title: 'Son : propagation',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'son',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment le son se propage-t-il ?',
    options: [
      { id: 'a', text: 'Il ne voyage que dans l\'air', isCorrect: false },
      { id: 'b', text: 'Il voyage sous forme de vibrations dans des milieux (air, eau, solides)', isCorrect: true },
      { id: 'c', text: 'Il voyage uniquement dans le vide', isCorrect: false },
    ],
    correctAnswer: 'Il voyage sous forme de vibrations dans des milieux (air, eau, solides)',
    explanation: 'Le son est une vibration qui se propage dans les milieux matériels : air, eau, bois, métal. Il ne peut pas voyager dans le vide.',
    hint: 'Colle ton oreille contre un mur : tu entends mieux.',
    tags: ['ce2', 'sciences', 'matiere', 'son', 'vibrations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-015',
    subject: 'sciences',
    title: 'Matière : tension de surface',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'proprietes-eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi un trombone en métal peut-il flotter sur l\'eau si on le pose délicatement ?',
    options: [
      { id: 'a', text: 'Parce que le métal est léger', isCorrect: false },
      { id: 'b', text: 'Grâce à la tension de surface de l\'eau', isCorrect: true },
      { id: 'c', text: 'Parce que l\'eau est froide', isCorrect: false },
    ],
    correctAnswer: 'Grâce à la tension de surface de l\'eau',
    explanation: 'La tension de surface est une force créée par les molécules d\'eau en surface. Elle forme une sorte de "film élastique" qui peut porter de petits objets.',
    hint: 'Les insectes patineurs marchent aussi sur ce "film".',
    tags: ['ce2', 'sciences', 'matiere', 'eau', 'tension-surface', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-016',
    subject: 'sciences',
    title: 'Matière : conducteur thermique',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes-thermiques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi le métal d\'une poêle devient-il brûlant alors que le manche en bois reste tiède ?',
    options: [
      { id: 'a', text: 'Le bois absorbe la chaleur et la retient', isCorrect: false },
      { id: 'b', text: 'Le métal conduit la chaleur bien mieux que le bois', isCorrect: true },
      { id: 'c', text: 'Le bois est plus épais', isCorrect: false },
    ],
    correctAnswer: 'Le métal conduit la chaleur bien mieux que le bois',
    explanation: 'Les métaux sont de bons conducteurs thermiques : ils transmettent rapidement la chaleur. Le bois est un isolant : il transmet mal la chaleur.',
    hint: 'C\'est pour ça que les manches de casseroles sont souvent en plastique ou en bois.',
    tags: ['ce2', 'sciences', 'matiere', 'conduction-thermique', 'metaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-017',
    subject: 'sciences',
    title: 'Matière : miscibilité',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'melanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il quand on mélange de l\'huile et de l\'eau puis qu\'on laisse reposer ?',
    options: [
      { id: 'a', text: 'Ils forment une solution homogène transparente', isCorrect: false },
      { id: 'b', text: 'Ils se séparent : l\'huile monte, l\'eau descend', isCorrect: true },
      { id: 'c', text: 'L\'eau disparaît dans l\'huile', isCorrect: false },
    ],
    correctAnswer: 'Ils se séparent : l\'huile monte, l\'eau descend',
    explanation: 'L\'huile et l\'eau ne se mélangent pas (non miscibles). L\'huile est moins dense que l\'eau, elle monte à la surface. On voit deux couches distinctes.',
    hint: 'La vinaigrette se sépare toujours si on ne l\'agite pas.',
    tags: ['ce2', 'sciences', 'matiere', 'melanges', 'miscibilite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-018',
    subject: 'sciences',
    title: 'Matière : expansion thermique',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'expansion',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les rails de chemin de fer ont-ils de petits espaces entre eux ?',
    options: [
      { id: 'a', text: 'Pour permettre le drainage de l\'eau de pluie', isCorrect: false },
      { id: 'b', text: 'Pour laisser le métal se dilater sous la chaleur sans se tordre', isCorrect: true },
      { id: 'c', text: 'Pour réduire le bruit du train', isCorrect: false },
    ],
    correctAnswer: 'Pour laisser le métal se dilater sous la chaleur sans se tordre',
    explanation: 'Le métal se dilate quand il chauffe. Sans espace, les rails se bosseraient en été. Ces joints de dilatation absorbent l\'expansion thermique.',
    hint: 'C\'est pour ça qu\'on entend "clac-clac" dans les vieux trains.',
    tags: ['ce2', 'sciences', 'matiere', 'dilatation', 'metaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-019',
    subject: 'sciences',
    title: 'Matière : densité',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'densite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un bloc de bois et un bloc de fer de même volume sont posés sur l\'eau. Lequel coule ?',
    options: [
      { id: 'a', text: 'Le bois, car le fer est plus solide', isCorrect: false },
      { id: 'b', text: 'Le fer, car sa densité est supérieure à celle de l\'eau', isCorrect: true },
      { id: 'c', text: 'Ni l\'un ni l\'autre, ils flottent tous les deux', isCorrect: false },
    ],
    correctAnswer: 'Le fer, car sa densité est supérieure à celle de l\'eau',
    explanation: 'Un objet coule si sa densité est supérieure à celle du liquide. La densité du fer (7,8) est bien supérieure à celle de l\'eau (1). Le bois (0,5 à 0,8) flotte.',
    hint: 'Ce qui est plus dense que l\'eau coule ; moins dense, ça flotte.',
    tags: ['ce2', 'sciences', 'matiere', 'densite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-020',
    subject: 'sciences',
    title: 'Matière : combustion',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'reactions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la combustion ?',
    options: [
      { id: 'a', text: 'Un changement d\'état de solide en liquide', isCorrect: false },
      { id: 'b', text: 'Une réaction chimique rapide qui produit de la chaleur et de la lumière', isCorrect: true },
      { id: 'c', text: 'Une dissolution dans l\'eau', isCorrect: false },
    ],
    correctAnswer: 'Une réaction chimique rapide qui produit de la chaleur et de la lumière',
    explanation: 'La combustion est une réaction chimique entre un combustible (bois, gaz) et l\'oxygène. Elle produit de la chaleur, de la lumière, et souvent de la fumée.',
    hint: 'Une bougie qui brûle est une combustion.',
    tags: ['ce2', 'sciences', 'matiere', 'combustion', 'reactions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-021',
    subject: 'sciences',
    title: 'Matière : transparence',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'proprietes-optiques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Parmi ces matériaux, lequel est transparent (laisse passer la lumière et voir à travers) ?',
    options: [
      { id: 'a', text: 'Le bois', isCorrect: false },
      { id: 'b', text: 'Le verre', isCorrect: true },
      { id: 'c', text: 'Le béton', isCorrect: false },
    ],
    correctAnswer: 'Le verre',
    explanation: 'Un matériau transparent laisse passer la lumière et on peut voir à travers. Le verre est transparent. Le bois et le béton sont opaques.',
    hint: 'Les vitres de fenêtre sont en verre, c\'est pour ça qu\'on voit dehors.',
    tags: ['ce2', 'sciences', 'matiere', 'optique', 'transparence', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-022',
    subject: 'sciences',
    title: 'Matière : rouille',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'reactions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi le fer se couvre-t-il de rouille quand il est exposé à l\'air humide ?',
    options: [
      { id: 'a', text: 'Il fond partiellement au contact de l\'eau', isCorrect: false },
      { id: 'b', text: 'Il réagit chimiquement avec l\'oxygène et l\'eau (oxydation)', isCorrect: true },
      { id: 'c', text: 'Il absorbe la couleur marron du sol', isCorrect: false },
    ],
    correctAnswer: 'Il réagit chimiquement avec l\'oxygène et l\'eau (oxydation)',
    explanation: 'La rouille est de l\'oxyde de fer. C\'est le résultat de la réaction chimique entre le fer, l\'oxygène de l\'air et l\'eau : on parle d\'oxydation.',
    hint: 'Les objets en fer laissés dehors sous la pluie rouillent vite.',
    tags: ['ce2', 'sciences', 'matiere', 'rouille', 'oxydation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-023',
    subject: 'sciences',
    title: 'Matière : elasticité',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'proprietes-mecaniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel matériau retrouve sa forme initiale après avoir été déformé (élastique) ?',
    options: [
      { id: 'a', text: 'La pâte à modeler', isCorrect: false },
      { id: 'b', text: 'Le caoutchouc (élastique)', isCorrect: true },
      { id: 'c', text: 'La cire de bougie', isCorrect: false },
    ],
    correctAnswer: 'Le caoutchouc (élastique)',
    explanation: 'Le caoutchouc est élastique : on peut l\'étirer ou le comprimer, il revient à sa forme d\'origine. La pâte à modeler et la cire restent déformées.',
    hint: 'Un élastique de bureau illustre parfaitement ce phénomène.',
    tags: ['ce2', 'sciences', 'matiere', 'elasticite', 'caoutchouc', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-024',
    subject: 'sciences',
    title: 'Matière : aimantation',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes-magnetiques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces matériaux n\'est PAS attiré par un aimant ?',
    options: [
      { id: 'a', text: 'Le fer', isCorrect: false },
      { id: 'b', text: 'Le cuivre', isCorrect: true },
      { id: 'c', text: 'Le nickel', isCorrect: false },
    ],
    correctAnswer: 'Le cuivre',
    explanation: 'Un aimant attire le fer, le nickel et le cobalt (matériaux ferromagnétiques). Le cuivre, l\'aluminium et le plastique ne sont pas attirés.',
    hint: 'Le cuivre est souvent utilisé pour les fils électriques mais il n\'est pas magnétique.',
    tags: ['ce2', 'sciences', 'matiere', 'magnetisme', 'aimant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-025',
    subject: 'sciences',
    title: 'Matière : cycle de l\'eau',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans le cycle de l\'eau, qu\'est-ce que la condensation ?',
    options: [
      { id: 'a', text: 'L\'eau qui s\'évapore dans l\'atmosphère', isCorrect: false },
      { id: 'b', text: 'La vapeur d\'eau qui refroidit et redevient liquide (forme les nuages)', isCorrect: true },
      { id: 'c', text: 'L\'eau qui s\'infiltre dans le sol', isCorrect: false },
    ],
    correctAnswer: 'La vapeur d\'eau qui refroidit et redevient liquide (forme les nuages)',
    explanation: 'La condensation est le passage vapeur → liquide. En altitude, la vapeur d\'eau refroidit et forme de minuscules gouttelettes qui constituent les nuages.',
    hint: 'Les gouttelettes sur un verre froid, c\'est de la condensation.',
    tags: ['ce2', 'sciences', 'matiere', 'eau', 'condensation', 'cycle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-ce2-mat-026',
    subject: 'sciences',
    title: 'Matière : polymères',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le plastique est un polymère. Qu\'est-ce que cela signifie ?',
    options: [
      { id: 'a', text: 'C\'est un matériau minéral extrait des roches', isCorrect: false },
      { id: 'b', text: 'C\'est une longue chaîne de molécules répétées liées entre elles', isCorrect: true },
      { id: 'c', text: 'C\'est un métal mou qui fond à basse température', isCorrect: false },
    ],
    correctAnswer: 'C\'est une longue chaîne de molécules répétées liées entre elles',
    explanation: 'Un polymère (poly = plusieurs, mère = partie) est formé de longues chaînes de molécules répétées. Le plastique, le caoutchouc et la cellulose du bois sont des polymères.',
    hint: 'Poly = beaucoup, mère = unité de base.',
    tags: ['ce2', 'sciences', 'matiere', 'polymeres', 'plastique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
