import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCm1EnvironnementExercises: ScienceExercise[] = [
  {
    id: 'sc-cm1-env-001',
    subject: 'sciences',
    title: 'Habitat : ours polaire',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est l\'habitat naturel d\'un ours polaire ?',
    options: [
      { id: 'a', text: 'La savane africaine', isCorrect: false },
      { id: 'b', text: 'Les régions polaires enneigées', isCorrect: true },
      { id: 'c', text: 'La forêt tropicale', isCorrect: false },
    ],
    correctAnswer: 'Les régions polaires enneigées',
    explanation: 'L\'ours polaire est adapté au froid extrême des régions arctiques, recouvertes de glace et de neige.',
    hint: 'Cet animal est blanc comme la neige.',
    tags: ['cm1', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-002',
    subject: 'sciences',
    title: 'Amphibien',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal peut vivre à la fois dans l\'eau et sur la terre ?',
    options: [
      { id: 'a', text: 'Le lézard', isCorrect: false },
      { id: 'b', text: 'La grenouille', isCorrect: true },
      { id: 'c', text: 'Le dauphin', isCorrect: false },
    ],
    correctAnswer: 'La grenouille',
    explanation: 'La grenouille est un amphibien : elle vit dans l\'eau (têtard) et sur la terre (adulte).',
    hint: 'Cet animal commence sa vie dans l\'eau et la finit sur terre.',
    tags: ['cm1', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-003',
    subject: 'sciences',
    title: 'Hibernation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que font certains animaux comme l\'ours ou la marmotte pendant l\'hiver ?',
    options: [
      { id: 'a', text: 'Ils migrent vers le sud', isCorrect: false },
      { id: 'b', text: 'Ils hibernent', isCorrect: true },
      { id: 'c', text: 'Ils changent de couleur', isCorrect: false },
    ],
    correctAnswer: 'Ils hibernent',
    explanation: 'Certains animaux hibernent en hiver : ils dorment profondément pour économiser leur énergie quand la nourriture est rare.',
    hint: 'Ils passent tout l\'hiver à dormir.',
    tags: ['cm1', 'sciences', 'habitats', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-004',
    subject: 'sciences',
    title: 'Évaporation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le passage de l\'eau liquide à l\'état de vapeur ?',
    options: [
      { id: 'a', text: 'La condensation', isCorrect: false },
      { id: 'b', text: 'L\'évaporation', isCorrect: true },
      { id: 'c', text: 'La congélation', isCorrect: false },
    ],
    correctAnswer: 'L\'évaporation',
    explanation: 'L\'évaporation, c\'est quand l\'eau liquide se transforme en vapeur sous l\'effet de la chaleur.',
    hint: 'C\'est ce qui se passe quand une flaque d\'eau disparaît par temps chaud.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Explique ce que signifie « condensation ».' },
    }),
  },

    {
    id: 'sc-cm1-env-005',
    subject: 'sciences',
    title: 'Eau douce',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où vient l\'eau douce des rivières et des lacs ?',
    options: [
      { id: 'a', text: 'De la mer', isCorrect: false },
      { id: 'b', text: 'Des pluies et de la fonte des neiges', isCorrect: true },
      { id: 'c', text: 'Du sol directement', isCorrect: false },
    ],
    correctAnswer: 'Des pluies et de la fonte des neiges',
    explanation: 'Les rivières sont alimentées par les pluies et par l\'eau des neiges qui fondent en montagne.',
    hint: 'Pense à ce qui tombe du ciel et à ce qui fond au printemps.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-006',
    subject: 'sciences',
    title: 'Eau sur Terre',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle proportion de la surface de la Terre est recouverte par les océans ?',
    options: [
      { id: 'a', text: 'Environ un tiers', isCorrect: false },
      { id: 'b', text: 'Environ deux tiers', isCorrect: true },
      { id: 'c', text: 'Presque tout', isCorrect: false },
    ],
    correctAnswer: 'Environ deux tiers',
    explanation: 'Les océans recouvrent environ 71 % de la Terre, c\'est pourquoi on l\'appelle la « planète bleue ».',
    hint: 'La Terre est surnommée la planète bleue.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-viv-010',
    subject: 'sciences',
    title: 'Habitat : forêt tropicale',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel milieu naturel abrite la plus grande variété d\'êtres vivants ?',
    options: [
      { id: 'a', text: 'Le désert de sable', isCorrect: false },
      { id: 'b', text: 'La forêt tropicale', isCorrect: true },
      { id: 'c', text: 'Un parking en béton', isCorrect: false },
    ],
    correctAnswer: 'La forêt tropicale',
    explanation: 'La forêt tropicale (comme l\'Amazonie) est le milieu le plus riche en espèces animales et végétales de la planète.',
    hint: 'C\'est là qu\'on trouve le plus d\'espèces animales et végétales.',
    tags: ['cm1', 'sciences', 'habitats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-007',
    subject: 'sciences',
    title: 'Météo : rosée',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que la rosée qu\'on voit sur les herbes le matin ?',
    options: [
      { id: 'a', text: 'De la pluie fine', isCorrect: false },
      { id: 'b', text: 'Des gouttes d\'eau déposées pendant la nuit', isCorrect: true },
      { id: 'c', text: 'De la neige fondue', isCorrect: false },
    ],
    correctAnswer: 'Des gouttes d\'eau déposées pendant la nuit',
    explanation: 'La rosée se forme quand la vapeur d\'eau de l\'air se condense sur les surfaces froides (herbe, feuilles) pendant la nuit.',
    hint: 'Le matin, les herbes sont mouillées même s\'il n\'a pas plu.',
    tags: ['cm1', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-008',
    subject: 'sciences',
    title: 'Météo : arc-en-ciel',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de couleurs compte un arc-en-ciel ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '5', isCorrect: false },
      { id: 'c', text: '7', isCorrect: true },
    ],
    correctAnswer: '7',
    explanation: 'Un arc-en-ciel compte 7 couleurs : rouge, orange, jaune, vert, bleu, indigo, violet.',
    hint: 'On dit souvent qu\'il y a les couleurs de l\'arc-en-ciel pour les apprendre.',
    tags: ['cm1', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-009',
    subject: 'sciences',
    title: 'Eau : eau potable',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que l\'eau potable ?',
    options: [
      { id: 'a', text: 'L\'eau de mer', isCorrect: false },
      { id: 'b', text: 'L\'eau qu\'on peut boire sans danger', isCorrect: true },
      { id: 'c', text: 'Toute l\'eau de la nature', isCorrect: false },
    ],
    correctAnswer: 'L\'eau qu\'on peut boire sans danger',
    explanation: 'L\'eau potable est une eau traitée et purifiée qu\'on peut boire sans tomber malade. L\'eau de mer est trop salée pour être bue.',
    hint: 'Elle sort de nos robinets.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cm1-env-010',
    subject: 'sciences',
    title: 'Eau : condensation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le passage de la vapeur d\'eau à l\'état liquide ?',
    options: [
      { id: 'a', text: 'L\'évaporation', isCorrect: false },
      { id: 'b', text: 'La condensation', isCorrect: true },
      { id: 'c', text: 'La congélation', isCorrect: false },
    ],
    correctAnswer: 'La condensation',
    explanation: 'La condensation, c\'est quand la vapeur d\'eau redevient liquide en se refroidissant. C\'est ce qui forme les nuages.',
    hint: 'C\'est le contraire de l\'évaporation.',
    tags: ['cm1', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Explique la différence entre évaporation et condensation.' },
    }),
  },
  {
    id: 'sc-cm1-env-011',
    subject: 'sciences',
    title: 'Énergie : renouvelable vs fossile',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'energie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Laquelle de ces sources d\'énergie est renouvelable ?',
    options: [
      { id: 'a', text: 'Le charbon', isCorrect: false },
      { id: 'b', text: 'L\'énergie éolienne (vent)', isCorrect: true },
      { id: 'c', text: 'Le pétrole', isCorrect: false },
    ],
    correctAnswer: 'L\'énergie éolienne (vent)',
    explanation: 'Le vent est inépuisable : l\'énergie éolienne est renouvelable. Le charbon et le pétrole sont des combustibles fossiles qui s\'épuisent.',
    hint: 'Le vent ne risque pas de manquer.',
    tags: ['cm1', 'sciences', 'energie', 'renouvelable', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-012',
    subject: 'sciences',
    title: 'Atmosphère : effet de serre',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'climat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que l\'effet de serre naturel ?',
    options: [
      { id: 'a', text: 'Un phénomène artificiel créé par les usines', isCorrect: false },
      { id: 'b', text: 'Un phénomène naturel qui retient la chaleur du soleil autour de la Terre', isCorrect: true },
      { id: 'c', text: 'La destruction de la couche d\'ozone', isCorrect: false },
    ],
    correctAnswer: 'Un phénomène naturel qui retient la chaleur du soleil autour de la Terre',
    explanation: 'L\'effet de serre naturel maintient une température habitable sur Terre. Le problème actuel vient de son amplification par les activités humaines.',
    hint: 'Sans cet effet, la Terre serait gelée en permanence.',
    tags: ['cm1', 'sciences', 'environnement', 'climat', 'effet-de-serre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-013',
    subject: 'sciences',
    title: 'Déchets : tri sélectif',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi trie-t-on les déchets ?',
    options: [
      { id: 'a', text: 'Pour embellir les rues', isCorrect: false },
      { id: 'b', text: 'Pour recycler les matières et réduire les déchets', isCorrect: true },
      { id: 'c', text: 'Pour les brûler plus facilement', isCorrect: false },
    ],
    correctAnswer: 'Pour recycler les matières et réduire les déchets',
    explanation: 'Le tri sélectif permet de recycler le verre, le carton, le plastique et les métaux, économisant des ressources naturelles.',
    hint: 'Le recyclage donne une nouvelle vie aux matériaux.',
    tags: ['cm1', 'sciences', 'environnement', 'dechets', 'recyclage', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-014',
    subject: 'sciences',
    title: 'Terre : structure interne',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelles sont les couches principales de la Terre de l\'extérieur vers l\'intérieur ?',
    options: [
      { id: 'a', text: 'Croûte → manteau → noyau', isCorrect: true },
      { id: 'b', text: 'Noyau → croûte → manteau', isCorrect: false },
      { id: 'c', text: 'Manteau → noyau → croûte', isCorrect: false },
    ],
    correctAnswer: 'Croûte → manteau → noyau',
    explanation: 'La Terre est composée de : la croûte (fine couche externe), le manteau (roches chaudes semi-liquides) et le noyau (fer et nickel très chauds).',
    hint: 'Commence par la couche sur laquelle on marche.',
    tags: ['cm1', 'sciences', 'terre', 'structure', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-015',
    subject: 'sciences',
    title: 'Pollution : plastique dans les océans',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'pollution',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le problème principal du plastique jeté dans les océans ?',
    options: [
      { id: 'a', text: 'Il rend l\'eau salée', isCorrect: false },
      { id: 'b', text: 'Il se fragmente en microplastiques ingérés par les animaux marins', isCorrect: true },
      { id: 'c', text: 'Il fait couler les bateaux', isCorrect: false },
    ],
    correctAnswer: 'Il se fragmente en microplastiques ingérés par les animaux marins',
    explanation: 'Le plastique se fragmente en particules minuscules (microplastiques) que les poissons et oiseaux de mer avalent, menaçant les écosystèmes marins.',
    hint: 'Le plastique ne disparaît pas, il se fragmente.',
    tags: ['cm1', 'sciences', 'environnement', 'pollution', 'plastique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-016',
    subject: 'sciences',
    title: 'Météo : nuages',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi sont faits les nuages ?',
    options: [
      { id: 'a', text: 'De vapeur d\'eau pure et invisible', isCorrect: false },
      { id: 'b', text: 'De minuscules gouttelettes d\'eau ou de cristaux de glace en suspension', isCorrect: true },
      { id: 'c', text: 'De fumée et de poussière uniquement', isCorrect: false },
    ],
    correctAnswer: 'De minuscules gouttelettes d\'eau ou de cristaux de glace en suspension',
    explanation: 'Les nuages sont formés de millions de gouttelettes d\'eau très fines ou de cristaux de glace, si légers qu\'ils flottent dans l\'air.',
    hint: 'Le brouillard est un nuage au niveau du sol.',
    tags: ['cm1', 'sciences', 'meteo', 'nuages', 'eau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-017',
    subject: 'sciences',
    title: 'Lithosphère : plaques tectoniques',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une plaque tectonique ?',
    options: [
      { id: 'a', text: 'Un continent entier', isCorrect: false },
      { id: 'b', text: 'Un grand fragment de la croûte terrestre qui se déplace lentement', isCorrect: true },
      { id: 'c', text: 'Une île volcanique', isCorrect: false },
    ],
    correctAnswer: 'Un grand fragment de la croûte terrestre qui se déplace lentement',
    explanation: 'La croûte terrestre est découpée en plaques qui bougent très lentement. Leurs mouvements provoquent séismes et éruptions volcaniques.',
    hint: 'L\'Europe et l\'Amérique s\'éloignent de quelques centimètres par an.',
    tags: ['cm1', 'sciences', 'terre', 'tectonique', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-018',
    subject: 'sciences',
    title: 'Eau : traitement',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où va l\'eau de la douche après qu\'on l\'a utilisée ?',
    options: [
      { id: 'a', text: 'Dans une rivière directement', isCorrect: false },
      { id: 'b', text: 'Dans une station d\'épuration pour être traitée', isCorrect: true },
      { id: 'c', text: 'Elle est recyclée directement dans les canalisations', isCorrect: false },
    ],
    correctAnswer: 'Dans une station d\'épuration pour être traitée',
    explanation: 'Les eaux usées (douche, toilettes) sont acheminées vers une station d\'épuration où elles sont filtrées et dépolluées avant d\'être rejetées.',
    hint: 'Elle ne va pas directement dans la nature.',
    tags: ['cm1', 'sciences', 'eau', 'epuration', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-env-019',
    subject: 'sciences',
    title: 'Risques naturels : inondation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'environnement',
    subskill: 'risques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi déboisement (couper les forêts) augmente-t-il le risque d\'inondation ?',
    options: [
      { id: 'a', text: 'Les arbres produisent de l\'eau', isCorrect: false },
      { id: 'b', text: 'Les racines des arbres retiennent l\'eau de pluie et la font pénétrer dans le sol', isCorrect: true },
      { id: 'c', text: 'Les arbres absorbent les nuages', isCorrect: false },
    ],
    correctAnswer: 'Les racines des arbres retiennent l\'eau de pluie et la font pénétrer dans le sol',
    explanation: 'Sans arbres, l\'eau de pluie ruisselle directement sur le sol sans s\'infiltrer, augmentant le risque d\'inondation.',
    hint: 'Les racines agissent comme des éponges.',
    tags: ['cm1', 'sciences', 'environnement', 'risques', 'inondation', 'foret', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
];
