import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCm1MatiereExercises: ScienceExercise[] = [
  {
    id: 'sc-cm1-mat-001',
    subject: 'sciences',
    title: 'Atome et molécule : définitions',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'structure',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une molécule d\'eau (H₂O) est composée de... ?',
    options: [
      { id: 'a', text: '2 atomes d\'oxygène et 1 atome d\'hydrogène', isCorrect: false },
      { id: 'b', text: '2 atomes d\'hydrogène et 1 atome d\'oxygène', isCorrect: true },
      { id: 'c', text: '3 atomes d\'hydrogène', isCorrect: false },
    ],
    correctAnswer: '2 atomes d\'hydrogène et 1 atome d\'oxygène',
    explanation: 'H₂O signifie : 2 atomes d\'hydrogène (H) et 1 atome d\'oxygène (O). C\'est la formule chimique de l\'eau.',
    hint: 'H = hydrogène, O = oxygène, le chiffre indique la quantité.',
    tags: ['cm1', 'sciences', 'matiere', 'molecule', 'eau', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-002',
    subject: 'sciences',
    title: 'Lumière : vitesse',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'lumiere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la vitesse approximative de la lumière ?',
    options: [
      { id: 'a', text: '300 km/h', isCorrect: false },
      { id: 'b', text: '300 000 km/s', isCorrect: true },
      { id: 'c', text: '1000 m/s', isCorrect: false },
    ],
    correctAnswer: '300 000 km/s',
    explanation: 'La lumière se déplace à environ 300 000 kilomètres par seconde. Elle fait le tour de la Terre environ 7 fois en une seconde.',
    hint: 'Elle va beaucoup plus vite que le son.',
    tags: ['cm1', 'sciences', 'matiere', 'lumiere', 'vitesse', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-003',
    subject: 'sciences',
    title: 'Son : vitesse et tonnerre',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'son',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi voit-on l\'éclair avant d\'entendre le tonnerre ?',
    options: [
      { id: 'a', text: 'Le tonnerre est produit après l\'éclair', isCorrect: false },
      { id: 'b', text: 'La lumière voyage beaucoup plus vite que le son', isCorrect: true },
      { id: 'c', text: 'Le tonnerre se déplace plus lentement car il est plus lourd', isCorrect: false },
    ],
    correctAnswer: 'La lumière voyage beaucoup plus vite que le son',
    explanation: 'La lumière (300 000 km/s) est bien plus rapide que le son (340 m/s). L\'éclair et le tonnerre se produisent en même temps, mais on voit l\'éclair en premier.',
    hint: 'On compte les secondes entre l\'éclair et le tonnerre pour estimer la distance.',
    tags: ['cm1', 'sciences', 'matiere', 'son', 'lumiere', 'vitesse', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-004',
    subject: 'sciences',
    title: 'Électricité : circuit en série',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'electricite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans un circuit en série avec 2 ampoules, si une ampoule grille… ?',
    options: [
      { id: 'a', text: 'L\'autre reste allumée', isCorrect: false },
      { id: 'b', text: 'Les deux s\'éteignent car le circuit est ouvert', isCorrect: true },
      { id: 'c', text: 'Les deux brillent encore plus fort', isCorrect: false },
    ],
    correctAnswer: 'Les deux s\'éteignent car le circuit est ouvert',
    explanation: 'En série, les composants sont sur un seul chemin. Si l\'un est interrompu, tout le courant s\'arrête. C\'est pour ça qu\'on préfère les circuits en parallèle.',
    hint: 'Comme les guirlandes de Noël anciennes : une ampoule grillée éteint tout.',
    tags: ['cm1', 'sciences', 'matiere', 'electricite', 'circuit', 'serie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-005',
    subject: 'sciences',
    title: 'Magnétisme : pôles',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il quand on approche le pôle Nord d\'un aimant du pôle Nord d\'un autre aimant ?',
    options: [
      { id: 'a', text: 'Ils s\'attirent', isCorrect: false },
      { id: 'b', text: 'Ils se repoussent', isCorrect: true },
      { id: 'c', text: 'Il ne se passe rien', isCorrect: false },
    ],
    correctAnswer: 'Ils se repoussent',
    explanation: 'Les pôles identiques se repoussent, les pôles opposés s\'attirent. Nord-Nord = répulsion. Nord-Sud = attraction.',
    hint: 'Les pôles contraires s\'attirent, les pôles identiques se repoussent.',
    tags: ['cm1', 'sciences', 'matiere', 'magnetisme', 'poles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-006',
    subject: 'sciences',
    title: 'Chaleur : conduction',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'thermique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi une cuillère en métal posée dans une tasse de thé chaud devient-elle chaude rapidement ?',
    options: [
      { id: 'a', text: 'Parce qu\'elle absorbe la vapeur du thé', isCorrect: false },
      { id: 'b', text: 'Parce que le métal conduit bien la chaleur par conduction', isCorrect: true },
      { id: 'c', text: 'Parce que le thé teinture le métal', isCorrect: false },
    ],
    correctAnswer: 'Parce que le métal conduit bien la chaleur par conduction',
    explanation: 'La conduction est le transfert de chaleur par contact direct. Le métal est un bon conducteur thermique.',
    hint: 'Ne jamais laisser une cuillère en métal dans une boisson chaude et la porter à la bouche directement.',
    tags: ['cm1', 'sciences', 'matiere', 'thermique', 'conduction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-007',
    subject: 'sciences',
    title: 'Masse et volume : densité',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'proprietes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'On pose un caillou dans l\'eau : il coule. Une bouteille plastique fermée : elle flotte. Pourquoi ?',
    options: [
      { id: 'a', text: 'Le caillou est plus grand', isCorrect: false },
      { id: 'b', text: 'Le caillou est plus dense que l\'eau ; la bouteille (air inclus) est moins dense', isCorrect: true },
      { id: 'c', text: 'La bouteille est aimantée par l\'eau', isCorrect: false },
    ],
    correctAnswer: 'Le caillou est plus dense que l\'eau ; la bouteille (air inclus) est moins dense',
    explanation: 'Un objet flotte si sa densité est inférieure à celle de l\'eau. Le caillou est dense ; la bouteille contient de l\'air léger, donc elle flotte.',
    hint: 'Densité = masse / volume. L\'air est très peu dense.',
    tags: ['cm1', 'sciences', 'matiere', 'densite', 'flottaison', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-008',
    subject: 'sciences',
    title: 'Objets techniques : engrenage et vitesse',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Un grand engrenage (30 dents) entraîne un petit (10 dents). Le petit tourne... ?',
    options: [
      { id: 'a', text: 'Moins vite que le grand', isCorrect: false },
      { id: 'b', text: '3 fois plus vite que le grand', isCorrect: true },
      { id: 'c', text: 'À la même vitesse', isCorrect: false },
    ],
    correctAnswer: '3 fois plus vite que le grand',
    explanation: 'Un petit engrenage entraîné par un grand tourne plus vite. Rapport de transmission = 30 ÷ 10 = 3. C\'est le principe des vitesses d\'un vélo.',
    hint: 'Comme les vitesses d\'un vélo : grande roue → petite roue = vitesse.',
    tags: ['cm1', 'sciences', 'matiere', 'objets-techniques', 'engrenage', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-009',
    subject: 'sciences',
    title: 'Lumière : refraction',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'lumiere',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi une paille dans un verre d\'eau semble-t-elle brisée ?',
    options: [
      { id: 'a', text: 'L\'eau la courbe chimiquement', isCorrect: false },
      { id: 'b', text: 'La lumière change de direction en passant de l\'eau à l\'air (réfraction)', isCorrect: true },
      { id: 'c', text: 'La pression de l\'eau la plie', isCorrect: false },
    ],
    correctAnswer: 'La lumière change de direction en passant de l\'eau à l\'air (réfraction)',
    explanation: 'La réfraction est le changement de direction de la lumière quand elle passe d\'un milieu à un autre (eau vers air). Cela crée une illusion d\'optique.',
    hint: 'L\'arc-en-ciel est aussi dû à une réfraction de la lumière.',
    tags: ['cm1', 'sciences', 'matiere', 'lumiere', 'refraction', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-010',
    subject: 'sciences',
    title: 'Énergie : transformation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'energie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une centrale hydraulique transforme l\'énergie de l\'eau en... ?',
    options: [
      { id: 'a', text: 'Énergie chimique', isCorrect: false },
      { id: 'b', text: 'Énergie électrique', isCorrect: true },
      { id: 'c', text: 'Énergie thermique', isCorrect: false },
    ],
    correctAnswer: 'Énergie électrique',
    explanation: 'Dans une centrale hydraulique, l\'eau en mouvement fait tourner des turbines qui produisent de l\'électricité.',
    hint: 'Les barrages sur les fleuves produisent de l\'électricité.',
    tags: ['cm1', 'sciences', 'matiere', 'energie', 'hydraulique', 'electricite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-011',
    subject: 'sciences',
    title: 'Mélange : filtration',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'melanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment peut-on séparer un mélange sable + eau ?',
    options: [
      { id: 'a', text: 'En le chauffant uniquement', isCorrect: false },
      { id: 'b', text: 'Par filtration (passer dans un filtre)', isCorrect: true },
      { id: 'c', text: 'En ajoutant du sel', isCorrect: false },
    ],
    correctAnswer: 'Par filtration (passer dans un filtre)',
    explanation: 'La filtration retient les solides (sable) et laisse passer le liquide (eau). C\'est ainsi qu\'on purifie l\'eau dans les stations de traitement.',
    hint: 'Un filtre à café fait la même chose avec le café moulu.',
    tags: ['cm1', 'sciences', 'matiere', 'melanges', 'filtration', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-012',
    subject: 'sciences',
    title: 'Matériaux : résistance',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les câbles de suspension d\'un pont sont-ils en acier et non en bois ?',
    options: [
      { id: 'a', text: 'Parce que l\'acier est plus léger', isCorrect: false },
      { id: 'b', text: 'Parce que l\'acier est bien plus résistant à la traction', isCorrect: true },
      { id: 'c', text: 'Parce que l\'acier est moins cher', isCorrect: false },
    ],
    correctAnswer: 'Parce que l\'acier est bien plus résistant à la traction',
    explanation: 'L\'acier résiste très bien aux forces de traction (étirement). Il peut supporter des centaines de tonnes, ce que le bois ne peut pas faire.',
    hint: 'Le choix du matériau dépend des forces qu\'il doit supporter.',
    tags: ['cm1', 'sciences', 'matiere', 'materiaux', 'resistance', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-013',
    subject: 'sciences',
    title: 'Objets techniques : programme',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un programme informatique ?',
    options: [
      { id: 'a', text: 'Un composant électronique physique', isCorrect: false },
      { id: 'b', text: 'Une suite d\'instructions que l\'ordinateur exécute dans l\'ordre', isCorrect: true },
      { id: 'c', text: 'L\'écran d\'un ordinateur', isCorrect: false },
    ],
    correctAnswer: 'Une suite d\'instructions que l\'ordinateur exécute dans l\'ordre',
    explanation: 'Un programme (ou logiciel) est une série d\'instructions écrites par des programmeurs. L\'ordinateur les exécute pour accomplir une tâche.',
    hint: 'Même un simple jeu de téléphone est un programme.',
    tags: ['cm1', 'sciences', 'matiere', 'objets-techniques', 'informatique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-014',
    subject: 'sciences',
    title: 'Forces : gravitation',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'forces',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les objets tombent-ils toujours vers le bas ?',
    options: [
      { id: 'a', text: 'Parce qu\'ils sont lourds', isCorrect: false },
      { id: 'b', text: 'À cause de la gravité, force qui attire les objets vers le centre de la Terre', isCorrect: true },
      { id: 'c', text: 'Parce que l\'air les pousse vers le bas', isCorrect: false },
    ],
    correctAnswer: 'À cause de la gravité, force qui attire les objets vers le centre de la Terre',
    explanation: 'La gravité (ou gravitation) est une force d\'attraction. La Terre attire tous les objets vers son centre. C\'est pour ça qu\'on ne s\'envole pas.',
    hint: 'La pomme de Newton est tombée à cause de la gravité.',
    tags: ['cm1', 'sciences', 'matiere', 'forces', 'gravite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-015',
    subject: 'sciences',
    title: 'Matière : atomes et molécules',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'structure',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une molécule d\'eau (H₂O) ?',
    options: [
      { id: 'a', text: 'Un atome d\'hydrogène entouré d\'eau', isCorrect: false },
      { id: 'b', text: 'Un assemblage de 2 atomes d\'hydrogène et 1 atome d\'oxygène', isCorrect: true },
      { id: 'c', text: 'Un cristal d\'oxygène pur', isCorrect: false },
    ],
    correctAnswer: 'Un assemblage de 2 atomes d\'hydrogène et 1 atome d\'oxygène',
    explanation: 'H₂O signifie : 2 atomes d\'hydrogène (H) et 1 atome d\'oxygène (O) liés entre eux. Une molécule est un groupe d\'atomes unis par des liaisons chimiques.',
    hint: 'H₂O : le 2 indique qu\'il y a 2 atomes de H pour 1 de O.',
    tags: ['cm1', 'sciences', 'matiere', 'molecules', 'atomes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-016',
    subject: 'sciences',
    title: 'Matière : énergie cinétique',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'energie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'énergie cinétique d\'un objet dépend de... ?',
    options: [
      { id: 'a', text: 'Sa couleur et sa température', isCorrect: false },
      { id: 'b', text: 'Sa masse et sa vitesse', isCorrect: true },
      { id: 'c', text: 'Sa hauteur et sa transparence', isCorrect: false },
    ],
    correctAnswer: 'Sa masse et sa vitesse',
    explanation: 'L\'énergie cinétique (énergie du mouvement) est proportionnelle à la masse et au carré de la vitesse. Un camion à 100 km/h a bien plus d\'énergie cinétique qu\'un vélo à la même vitesse.',
    hint: 'Un objet qui bouge vite et qui est lourd a beaucoup d\'énergie cinétique.',
    tags: ['cm1', 'sciences', 'matiere', 'energie-cinetique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-017',
    subject: 'sciences',
    title: 'Matière : allotropes du carbone',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le diamant et le graphite (mine de crayon) sont tous deux faits uniquement de carbone. Pourquoi sont-ils si différents ?',
    options: [
      { id: 'a', text: 'Le graphite contient aussi de l\'azote', isCorrect: false },
      { id: 'b', text: 'Les atomes de carbone sont arrangés différemment (structure cristalline différente)', isCorrect: true },
      { id: 'c', text: 'Le diamant est du carbone pur, le graphite en contient peu', isCorrect: false },
    ],
    correctAnswer: 'Les atomes de carbone sont arrangés différemment (structure cristalline différente)',
    explanation: 'Le diamant : atomes de C en réseau cubique 3D (très dur). Graphite : atomes en feuillets 2D (glissants, noir). Même élément, arrangement différent = propriétés opposées.',
    hint: 'Ce sont des allotropes : même élément, structure différente.',
    tags: ['cm1', 'sciences', 'matiere', 'carbone', 'allotropes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-018',
    subject: 'sciences',
    title: 'Matière : transfert de chaleur',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'thermique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la différence entre conduction, convection et rayonnement thermiques ?',
    options: [
      { id: 'a', text: 'Ce sont trois noms différents pour la même chose', isCorrect: false },
      { id: 'b', text: 'Ce sont trois modes de transfert de chaleur : par contact, par déplacement de fluide, et par ondes', isCorrect: true },
      { id: 'c', text: 'Conduction = liquide, convection = solide, rayonnement = gaz', isCorrect: false },
    ],
    correctAnswer: 'Ce sont trois modes de transfert de chaleur : par contact, par déplacement de fluide, et par ondes',
    explanation: 'Conduction : chaleur via contact solide (poêle). Convection : chaleur via mouvement de fluide (eau qui bout). Rayonnement : chaleur via ondes (soleil → Terre).',
    hint: 'La chaleur d\'un radiateur chauffe par convection (air chaud qui monte).',
    tags: ['cm1', 'sciences', 'matiere', 'thermique', 'conduction', 'convection', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-019',
    subject: 'sciences',
    title: 'Matière : masse volumique de l\'air',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'gaz',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi un ballon rempli d\'air chaud monte-t-il ?',
    options: [
      { id: 'a', text: 'L\'air chaud pèse plus lourd que l\'air froid', isCorrect: false },
      { id: 'b', text: 'L\'air chaud est moins dense que l\'air froid, il monte naturellement', isCorrect: true },
      { id: 'c', text: 'Le feu sous le ballon le propulse vers le haut', isCorrect: false },
    ],
    correctAnswer: 'L\'air chaud est moins dense que l\'air froid, il monte naturellement',
    explanation: 'En se réchauffant, les molécules d\'air s\'écartent : l\'air chaud devient moins dense que l\'air environnant. Il monte (poussée d\'Archimède). C\'est le principe du ballon à air chaud.',
    hint: 'La convection : l\'air chaud monte, l\'air froid descend.',
    tags: ['cm1', 'sciences', 'matiere', 'gaz', 'densite', 'convection', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-020',
    subject: 'sciences',
    title: 'Matière : solubilité et température',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'melanges',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi le sucre se dissout-il plus vite dans l\'eau chaude que dans l\'eau froide ?',
    options: [
      { id: 'a', text: 'L\'eau chaude contient plus d\'eau', isCorrect: false },
      { id: 'b', text: 'La chaleur agite davantage les molécules, accélérant la dissolution', isCorrect: true },
      { id: 'c', text: 'Le sucre fond dans l\'eau chaude', isCorrect: false },
    ],
    correctAnswer: 'La chaleur agite davantage les molécules, accélérant la dissolution',
    explanation: 'La chaleur augmente l\'agitation des molécules d\'eau. Elles entrent plus souvent en contact avec les cristaux de sucre, les dispersent plus vite. Le sucre ne fond pas : il se dissout.',
    hint: 'La dissolution n\'est pas la fusion — le sucre ne change pas d\'état.',
    tags: ['cm1', 'sciences', 'matiere', 'dissolution', 'temperature', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-021',
    subject: 'sciences',
    title: 'Matière : pression atmosphérique',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'pression',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les oreilles se bouchent-elles dans un avion en décollage ou en montagne ?',
    options: [
      { id: 'a', text: 'À cause du bruit des moteurs qui fait vibrer le tympan', isCorrect: false },
      { id: 'b', text: 'La pression atmosphérique diminue, créant un déséquilibre entre l\'intérieur et l\'extérieur de l\'oreille', isCorrect: true },
      { id: 'c', text: 'Le froid en altitude rétrécit le conduit auditif', isCorrect: false },
    ],
    correctAnswer: 'La pression atmosphérique diminue, créant un déséquilibre entre l\'intérieur et l\'extérieur de l\'oreille',
    explanation: 'En altitude, la pression de l\'air diminue. La pression dans l\'oreille interne reste plus élevée, ce qui tend le tympan et le "bouche". Avaler ou se boucher le nez rééquilibre la pression.',
    hint: 'Déglutir (avaler) fait souvent "déboucher" les oreilles.',
    tags: ['cm1', 'sciences', 'matiere', 'pression', 'altitude', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-022',
    subject: 'sciences',
    title: 'Matière : réaction acido-basique',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'reactions',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il quand on mélange du vinaigre (acide) et du bicarbonate de soude (base) ?',
    options: [
      { id: 'a', text: 'Rien de visible', isCorrect: false },
      { id: 'b', text: 'Une effervescence (bulles de CO₂) et une neutralisation partielle', isCorrect: true },
      { id: 'c', text: 'Le mélange devient chaud et explose', isCorrect: false },
    ],
    correctAnswer: 'Une effervescence (bulles de CO₂) et une neutralisation partielle',
    explanation: 'Acide + base = réaction de neutralisation. Le vinaigre et le bicarbonate réagissent en produisant du CO₂ (les bulles) et de l\'eau. Cette réaction est utilisée en cuisine.',
    hint: 'C\'est ce qui fait lever certains gâteaux (levure chimique = bicarbonate + acide).',
    tags: ['cm1', 'sciences', 'matiere', 'reactions', 'acide-base', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-023',
    subject: 'sciences',
    title: 'Matière : électricité statique',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'electricite',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les cheveux se dressent-ils quand on approche un ballon frotté contre un pull ?',
    options: [
      { id: 'a', text: 'Le ballon crée un champ magnétique', isCorrect: false },
      { id: 'b', text: 'Le frottement donne au ballon une charge électrostatique qui attire les cheveux', isCorrect: true },
      { id: 'c', text: 'L\'air comprimé dans le ballon pousse les cheveux', isCorrect: false },
    ],
    correctAnswer: 'Le frottement donne au ballon une charge électrostatique qui attire les cheveux',
    explanation: 'En frottant le ballon, on lui transfère des électrons. Il devient chargé négativement et attire les objets légers chargés positivement (comme les cheveux). C\'est l\'électricité statique.',
    hint: 'Les écrans de téléphone attirent aussi la poussière pour cette raison.',
    tags: ['cm1', 'sciences', 'matiere', 'electricite-statique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-024',
    subject: 'sciences',
    title: 'Matière : nanotechnologies',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un nanomètre (nm) ?',
    options: [
      { id: 'a', text: 'Un millième de mètre (10⁻³ m)', isCorrect: false },
      { id: 'b', text: 'Un milliardième de mètre (10⁻⁹ m)', isCorrect: true },
      { id: 'c', text: 'Un millionième de mètre (10⁻⁶ m)', isCorrect: false },
    ],
    correctAnswer: 'Un milliardième de mètre (10⁻⁹ m)',
    explanation: 'Nano signifie un milliardième. 1 nm = 0,000000001 m. Un cheveu humain mesure environ 80 000 nm de diamètre. Les nanotechnologies travaillent à cette échelle.',
    hint: 'Milli = 10⁻³, micro = 10⁻⁶, nano = 10⁻⁹.',
    tags: ['cm1', 'sciences', 'matiere', 'nanometres', 'echelles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-025',
    subject: 'sciences',
    title: 'Matière : cristaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'structure',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'ont en commun le sel de cuisine, le sucre et le quartz ?',
    options: [
      { id: 'a', text: 'Ils sont tous solubles dans l\'eau', isCorrect: false },
      { id: 'b', text: 'Ce sont tous des cristaux : leurs atomes sont organisés en réseau régulier', isCorrect: true },
      { id: 'c', text: 'Ils contiennent tous du sodium', isCorrect: false },
    ],
    correctAnswer: 'Ce sont tous des cristaux : leurs atomes sont organisés en réseau régulier',
    explanation: 'Un cristal est un solide dont les atomes s\'arrangent en réseau ordonné et répété. Le sel (cubique), le sucre (monoclinique) et le quartz (hexagonal) sont des cristaux aux formes différentes.',
    hint: 'On peut voir la forme cristalline du sel au microscope : des cubes parfaits.',
    tags: ['cm1', 'sciences', 'matiere', 'cristaux', 'structure', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cm1-mat-026',
    subject: 'sciences',
    title: 'Matière : plasticité vs élasticité',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'matiere',
    subskill: 'proprietes-mecaniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la différence entre un matériau élastique et un matériau plastique (au sens mécanique) ?',
    options: [
      { id: 'a', text: 'Le plastique est plus solide, l\'élastique est plus léger', isCorrect: false },
      { id: 'b', text: 'L\'élastique reprend sa forme initiale, le plastique reste déformé', isCorrect: true },
      { id: 'c', text: 'Il n\'y a pas de différence', isCorrect: false },
    ],
    correctAnswer: 'L\'élastique reprend sa forme initiale, le plastique reste déformé',
    explanation: 'Élastique (mécanique) : le matériau reprend sa forme après déformation (caoutchouc, ressort). Plastique : il reste déformé (pâte à modeler, métal tordu).',
    hint: 'Un fil de fer plié reste plié = déformation plastique.',
    tags: ['cm1', 'sciences', 'matiere', 'elasticite', 'plasticite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
