import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCpCorpsExercises: ScienceExercise[] = [
  {
    id: 'sc-cp-cor-001',
    subject: 'sciences',
    title: 'Corps : yeux',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps sert à voir ?',
    options: [
      { id: 'a', text: 'Le nez', isCorrect: false },
      { id: 'b', text: 'Les yeux', isCorrect: true },
      { id: 'c', text: 'Les oreilles', isCorrect: false },
    ],
    correctAnswer: 'Les yeux',
    explanation: 'On utilise les yeux pour voir. Le nez sert à sentir et les oreilles à entendre.',
    hint: 'On les ferme pour dormir.',
    tags: ['cp', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-cor-002',
    subject: 'sciences',
    title: 'Corps : oreilles',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps sert à entendre ?',
    options: [
      { id: 'a', text: 'Les yeux', isCorrect: false },
      { id: 'b', text: 'Les oreilles', isCorrect: true },
      { id: 'c', text: 'Le nez', isCorrect: false },
    ],
    correctAnswer: 'Les oreilles',
    explanation: 'On utilise les oreilles pour entendre les sons et la musique.',
    hint: 'On les utilise pour écouter la musique.',
    tags: ['cp', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-cor-003',
    subject: 'sciences',
    title: 'Corps : nez',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps sert à sentir les odeurs ?',
    options: [
      { id: 'a', text: 'Le nez', isCorrect: true },
      { id: 'b', text: 'La bouche', isCorrect: false },
      { id: 'c', text: 'Les yeux', isCorrect: false },
    ],
    correctAnswer: 'Le nez',
    explanation: 'Le nez permet de sentir les odeurs. On dit qu\'on a un bon odorat.',
    hint: 'On l\'utilise aussi pour respirer.',
    tags: ['cp', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-004',
    subject: 'sciences',
    title: 'Corps : la bouche',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert la bouche ?',
    options: [
      { id: 'a', text: 'À voir', isCorrect: false },
      { id: 'b', text: 'À manger et à parler', isCorrect: true },
      { id: 'c', text: 'À entendre', isCorrect: false },
    ],
    correctAnswer: 'À manger et à parler',
    explanation: 'La bouche sert à manger, à parler et à goûter les aliments.',
    hint: 'On l\'ouvre pour manger.',
    tags: ['cp', 'sciences', 'corps', 'sens', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-005',
    subject: 'sciences',
    title: 'Corps : les dents',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi servent les dents ?',
    options: [
      { id: 'a', text: 'À sentir les odeurs', isCorrect: false },
      { id: 'b', text: 'À couper et mâcher les aliments', isCorrect: true },
      { id: 'c', text: 'À voir les couleurs', isCorrect: false },
    ],
    correctAnswer: 'À couper et mâcher les aliments',
    explanation: 'Les dents coupent et broient les aliments avant de les avaler.',
    hint: 'On les utilise pour croquer une pomme.',
    tags: ['cp', 'sciences', 'corps', 'dents', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-006',
    subject: 'sciences',
    title: 'Hygiène : se laver les mains',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi doit-on se laver les mains avant de manger ?',
    options: [
      { id: 'a', text: 'Pour qu\'elles soient chaudes', isCorrect: false },
      { id: 'b', text: 'Pour enlever les microbes', isCorrect: true },
      { id: 'c', text: 'Pour les rendre belles', isCorrect: false },
    ],
    correctAnswer: 'Pour enlever les microbes',
    explanation: 'Les mains touchent beaucoup d\'objets. Les microbes sur les mains peuvent nous rendre malades.',
    hint: 'Les microbes sont très petits et invisibles.',
    tags: ['cp', 'sciences', 'hygiene', 'sante', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-007',
    subject: 'sciences',
    title: 'Hygiène : se brosser les dents',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de fois par jour doit-on se brosser les dents ?',
    options: [
      { id: 'a', text: 'Une fois par semaine', isCorrect: false },
      { id: 'b', text: 'Deux fois par jour', isCorrect: true },
      { id: 'c', text: 'Jamais', isCorrect: false },
    ],
    correctAnswer: 'Deux fois par jour',
    explanation: 'Il faut se brosser les dents matin et soir pour éviter les caries.',
    hint: 'Le matin et le soir.',
    tags: ['cp', 'sciences', 'hygiene', 'dents', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-008',
    subject: 'sciences',
    title: 'Santé : dormir',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sante',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi les enfants ont-ils besoin de beaucoup dormir ?',
    options: [
      { id: 'a', text: 'Pour s\'ennuyer', isCorrect: false },
      { id: 'b', text: 'Pour grandir et récupérer de l\'énergie', isCorrect: true },
      { id: 'c', text: 'Pour rêver', isCorrect: false },
    ],
    correctAnswer: 'Pour grandir et récupérer de l\'énergie',
    explanation: 'Le corps grandit et se répare pendant le sommeil. Les enfants ont besoin d\'environ 10 heures de sommeil.',
    hint: 'Le corps travaille pendant qu\'on dort.',
    tags: ['cp', 'sciences', 'sante', 'sommeil', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-009',
    subject: 'sciences',
    title: 'Santé : manger des légumes',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sante',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que doit-on manger pour rester en bonne santé ?',
    options: [
      { id: 'a', text: 'Que des bonbons', isCorrect: false },
      { id: 'b', text: 'Des fruits et des légumes', isCorrect: true },
      { id: 'c', text: 'Que des gâteaux', isCorrect: false },
    ],
    correctAnswer: 'Des fruits et des légumes',
    explanation: 'Les fruits et légumes donnent des vitamines et des minéraux utiles pour le corps.',
    hint: 'Ce sont les aliments colorés du jardin.',
    tags: ['cp', 'sciences', 'sante', 'alimentation', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-010',
    subject: 'sciences',
    title: 'Santé : faire du sport',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sante',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi est-il important de bouger et de faire du sport ?',
    options: [
      { id: 'a', text: 'Pour s\'ennuyer dehors', isCorrect: false },
      { id: 'b', text: 'Pour garder un corps fort et en bonne santé', isCorrect: true },
      { id: 'c', text: 'Pour dépenser de l\'argent', isCorrect: false },
    ],
    correctAnswer: 'Pour garder un corps fort et en bonne santé',
    explanation: 'Le sport renforce les muscles, les os et le cœur. Il aide aussi à bien dormir.',
    hint: 'Le sport rend le corps plus fort.',
    tags: ['cp', 'sciences', 'sante', 'sport', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-011',
    subject: 'sciences',
    title: 'Corps : les bras et les jambes',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie du corps utilise-t-on pour marcher et courir ?',
    options: [
      { id: 'a', text: 'Les bras', isCorrect: false },
      { id: 'b', text: 'Les jambes', isCorrect: true },
      { id: 'c', text: 'La tête', isCorrect: false },
    ],
    correctAnswer: 'Les jambes',
    explanation: 'Les jambes et les pieds servent à marcher, courir et sauter.',
    hint: 'Ce sont les membres inférieurs.',
    tags: ['cp', 'sciences', 'corps', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-012',
    subject: 'sciences',
    title: 'Corps : le cœur',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où se trouve le cœur dans notre corps ?',
    options: [
      { id: 'a', text: 'Dans la tête', isCorrect: false },
      { id: 'b', text: 'Dans la poitrine', isCorrect: true },
      { id: 'c', text: 'Dans le ventre', isCorrect: false },
    ],
    correctAnswer: 'Dans la poitrine',
    explanation: 'Le cœur est dans la poitrine, légèrement à gauche. On peut le sentir battre en posant la main dessus.',
    hint: 'On peut sentir ses battements.',
    tags: ['cp', 'sciences', 'corps', 'coeur', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-013',
    subject: 'sciences',
    title: 'Corps : peau et toucher',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Grâce à quoi pouvons-nous sentir si quelque chose est chaud ou froid ?',
    options: [
      { id: 'a', text: 'Nos yeux', isCorrect: false },
      { id: 'b', text: 'Notre peau', isCorrect: true },
      { id: 'c', text: 'Nos oreilles', isCorrect: false },
    ],
    correctAnswer: 'Notre peau',
    explanation: 'La peau est notre organe du toucher. Elle nous permet de sentir le chaud, le froid, le lisse, le rugueux.',
    hint: 'Elle recouvre tout notre corps.',
    tags: ['cp', 'sciences', 'corps', 'sens', 'toucher', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-014',
    subject: 'sciences',
    title: 'Corps : les os',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi servent les os dans notre corps ?',
    options: [
      { id: 'a', text: 'À digérer les aliments', isCorrect: false },
      { id: 'b', text: 'À tenir le corps debout et le protéger', isCorrect: true },
      { id: 'c', text: 'À voir les couleurs', isCorrect: false },
    ],
    correctAnswer: 'À tenir le corps debout et le protéger',
    explanation: 'Les os forment le squelette. Ils tiennent notre corps en position et protègent les organes.',
    hint: 'Ils forment notre squelette.',
    tags: ['cp', 'sciences', 'corps', 'squelette', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-015',
    subject: 'sciences',
    title: 'Corps : les muscles',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que permettent les muscles ?',
    options: [
      { id: 'a', text: 'De voir', isCorrect: false },
      { id: 'b', text: 'De bouger le corps', isCorrect: true },
      { id: 'c', text: 'De digérer', isCorrect: false },
    ],
    correctAnswer: 'De bouger le corps',
    explanation: 'Les muscles se contractent pour faire bouger nos bras, nos jambes et toutes les parties du corps.',
    hint: 'On les fait travailler quand on soulève quelque chose.',
    tags: ['cp', 'sciences', 'corps', 'muscles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-016',
    subject: 'sciences',
    title: 'Corps : les dents',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de fois par jour faut-il se brosser les dents ?',
    options: [
      { id: 'a', text: 'Une fois par semaine', isCorrect: false },
      { id: 'b', text: '2 fois par jour (matin et soir)', isCorrect: true },
      { id: 'c', text: 'Une fois par mois', isCorrect: false },
    ],
    correctAnswer: '2 fois par jour (matin et soir)',
    explanation: 'On se brosse les dents le matin et le soir pour éliminer les restes d\'aliments et éviter les caries.',
    hint: 'Matin et soir, sans oublier !',
    tags: ['cp', 'sciences', 'corps', 'hygiene', 'dents', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-017',
    subject: 'sciences',
    title: 'Corps : vue',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Avec quel organe voit-on ?',
    options: [
      { id: 'a', text: 'Les oreilles', isCorrect: false },
      { id: 'b', text: 'Les yeux', isCorrect: true },
      { id: 'c', text: 'Le nez', isCorrect: false },
    ],
    correctAnswer: 'Les yeux',
    explanation: 'Les yeux sont l\'organe de la vue. Ils envoient des informations au cerveau pour que nous puissions voir.',
    hint: 'On les ferme pour dormir.',
    tags: ['cp', 'sciences', 'corps', 'sens', 'vue', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-018',
    subject: 'sciences',
    title: 'Corps : ouïe',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Avec quel organe entend-on les sons ?',
    options: [
      { id: 'a', text: 'Le nez', isCorrect: false },
      { id: 'b', text: 'Les oreilles', isCorrect: true },
      { id: 'c', text: 'Les yeux', isCorrect: false },
    ],
    correctAnswer: 'Les oreilles',
    explanation: 'Les oreilles captent les sons et les transmettent au cerveau. On a deux oreilles, une de chaque côté de la tête.',
    hint: 'On les protège avec des bouchons quand le bruit est trop fort.',
    tags: ['cp', 'sciences', 'corps', 'sens', 'ouie', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-019',
    subject: 'sciences',
    title: 'Corps : odorat',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Avec quoi sent-on les odeurs ?',
    options: [
      { id: 'a', text: 'La bouche', isCorrect: false },
      { id: 'b', text: 'Le nez', isCorrect: true },
      { id: 'c', text: 'Les mains', isCorrect: false },
    ],
    correctAnswer: 'Le nez',
    explanation: 'Le nez est l\'organe de l\'odorat. Il nous permet de sentir les bonnes et les mauvaises odeurs.',
    hint: 'On le bouche quand ça sent mauvais.',
    tags: ['cp', 'sciences', 'corps', 'sens', 'odorat', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-020',
    subject: 'sciences',
    title: 'Corps : goût',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sens',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Avec quoi goûte-t-on les aliments ?',
    options: [
      { id: 'a', text: 'Les dents', isCorrect: false },
      { id: 'b', text: 'La langue', isCorrect: true },
      { id: 'c', text: 'Le nez uniquement', isCorrect: false },
    ],
    correctAnswer: 'La langue',
    explanation: 'La langue est l\'organe du goût. Elle possède des papilles gustatives qui détectent le sucré, le salé, l\'acide et l\'amer.',
    hint: 'On la sort pour goûter.',
    tags: ['cp', 'sciences', 'corps', 'sens', 'gout', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-021',
    subject: 'sciences',
    title: 'Corps : alimentation',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'nutrition',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi mange-t-on chaque jour ?',
    options: [
      { id: 'a', text: 'Juste parce que c\'est l\'heure', isCorrect: false },
      { id: 'b', text: 'Pour avoir de l\'énergie et grandir', isCorrect: true },
      { id: 'c', text: 'Pour s\'occuper', isCorrect: false },
    ],
    correctAnswer: 'Pour avoir de l\'énergie et grandir',
    explanation: 'La nourriture donne à notre corps l\'énergie pour bouger, réfléchir et grandir. Sans manger, on serait fatigués.',
    hint: 'Après un repas, on se sent mieux et plus fort.',
    tags: ['cp', 'sciences', 'corps', 'nutrition', 'alimentation', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-022',
    subject: 'sciences',
    title: 'Corps : se laver',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'hygiene',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi faut-il se laver les mains avant de manger ?',
    options: [
      { id: 'a', text: 'Pour que les mains sentent bon', isCorrect: false },
      { id: 'b', text: 'Pour enlever les microbes qui pourraient rendre malade', isCorrect: true },
      { id: 'c', text: 'Parce que c\'est joli', isCorrect: false },
    ],
    correctAnswer: 'Pour enlever les microbes qui pourraient rendre malade',
    explanation: 'Les mains touchent beaucoup de choses dans la journée et ramassent des microbes. Se laver les mains évite de les avaler avec les aliments.',
    hint: 'Savon + eau = mains propres.',
    tags: ['cp', 'sciences', 'corps', 'hygiene', 'mains', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-cor-023',
    subject: 'sciences',
    title: 'Corps : lunettes',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'corps',
    subskill: 'sante',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi certains enfants portent-ils des lunettes ?',
    options: [
      { id: 'a', text: 'Pour être plus beaux', isCorrect: false },
      { id: 'b', text: 'Parce que leurs yeux voient flou et les lunettes les aident à mieux voir', isCorrect: true },
      { id: 'c', text: 'Pour protéger leurs yeux du vent uniquement', isCorrect: false },
    ],
    correctAnswer: 'Parce que leurs yeux voient flou et les lunettes les aident à mieux voir',
    explanation: 'Les lunettes corrigent les problèmes de vue. Elles permettent à ceux qui voient mal de voir nettement.',
    hint: 'Un opticien les fabrique et les ajuste.',
    tags: ['cp', 'sciences', 'corps', 'sante', 'vue', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
];
