import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCpEnvironnementExercises: ScienceExercise[] = [
  {
    id: 'sc-cp-env-001',
    subject: 'sciences',
    title: 'Météo : pluie',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand il pleut, quel objet utilise-t-on pour ne pas être mouillé ?',
    options: [
      { id: 'a', text: 'Un ballon', isCorrect: false },
      { id: 'b', text: 'Un parapluie', isCorrect: true },
      { id: 'c', text: 'Un chapeau de soleil', isCorrect: false },
    ],
    correctAnswer: 'Un parapluie',
    explanation: 'On ouvre un parapluie pour se protéger de la pluie.',
    hint: 'On l\'ouvre au-dessus de sa tête.',
    tags: ['cp', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-env-002',
    subject: 'sciences',
    title: 'Météo : orage',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel temps fait-il quand on voit des éclairs dans le ciel ?',
    options: [
      { id: 'a', text: 'Il neige', isCorrect: false },
      { id: 'b', text: 'Il y a un orage', isCorrect: true },
      { id: 'c', text: 'Il fait beau', isCorrect: false },
    ],
    correctAnswer: 'Il y a un orage',
    explanation: 'Les éclairs et le tonnerre apparaissent pendant un orage.',
    hint: 'On entend aussi du tonnerre.',
    tags: ['cp', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-env-003',
    subject: 'sciences',
    title: 'Saison : neige',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison tombe la neige en France ?',
    options: [
      { id: 'a', text: 'En été', isCorrect: false },
      { id: 'b', text: 'En automne', isCorrect: false },
      { id: 'c', text: 'En hiver', isCorrect: true },
    ],
    correctAnswer: 'En hiver',
    explanation: 'En hiver, il fait très froid et il peut neiger. En été il fait chaud.',
    hint: 'C\'est la saison la plus froide.',
    tags: ['cp', 'sciences', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-env-004',
    subject: 'sciences',
    title: 'Météo : ciel nuageux',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel temps fait-il quand le ciel est tout gris et couvert ?',
    options: [
      { id: 'a', text: 'Il fait très soleil', isCorrect: false },
      { id: 'b', text: 'Le ciel est nuageux', isCorrect: true },
      { id: 'c', text: 'Il neige', isCorrect: false },
    ],
    correctAnswer: 'Le ciel est nuageux',
    explanation: 'Quand le ciel est gris et couvert, on dit qu\'il est nuageux. Les nuages cachent le soleil.',
    hint: 'Le ciel est couvert de nuages gris.',
    tags: ['cp', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-env-005',
    subject: 'sciences',
    title: 'Météo : vent',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le vent déplace dans le ciel ?',
    options: [
      { id: 'a', text: 'Les pierres', isCorrect: false },
      { id: 'b', text: 'Les nuages', isCorrect: true },
      { id: 'c', text: 'Les maisons', isCorrect: false },
    ],
    correctAnswer: 'Les nuages',
    explanation: 'Le vent est un mouvement d\'air. Il déplace les nuages dans le ciel et fait bouger les feuilles des arbres.',
    hint: 'Regarde le ciel quand il y a du vent.',
    tags: ['cp', 'sciences', 'meteo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-006',
    subject: 'sciences',
    title: 'Saison : printemps',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Au printemps, que se passe-t-il dans la nature ?',
    options: [
      { id: 'a', text: 'Les feuilles tombent', isCorrect: false },
      { id: 'b', text: 'Les fleurs poussent', isCorrect: true },
      { id: 'c', text: 'Il neige beaucoup', isCorrect: false },
    ],
    correctAnswer: 'Les fleurs poussent',
    explanation: 'Au printemps, la nature se réveille : les fleurs éclosent, les oiseaux chantent, les jours rallongent.',
    hint: 'C\'est la saison qui suit l\'hiver.',
    tags: ['cp', 'sciences', 'saisons', 'printemps', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-007',
    subject: 'sciences',
    title: 'Saison : automne',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En automne, que font les feuilles des arbres ?',
    options: [
      { id: 'a', text: 'Elles poussent', isCorrect: false },
      { id: 'b', text: 'Elles tombent', isCorrect: true },
      { id: 'c', text: 'Elles deviennent bleues', isCorrect: false },
    ],
    correctAnswer: 'Elles tombent',
    explanation: 'En automne, les feuilles jaunissent, rougissent et tombent des arbres.',
    hint: 'On les ramasse sur le sol.',
    tags: ['cp', 'sciences', 'saisons', 'automne', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-008',
    subject: 'sciences',
    title: 'Saison : été',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison fait-il le plus chaud ?',
    options: [
      { id: 'a', text: 'En hiver', isCorrect: false },
      { id: 'b', text: 'En été', isCorrect: true },
      { id: 'c', text: 'Au printemps', isCorrect: false },
    ],
    correctAnswer: 'En été',
    explanation: 'En été, le soleil brille longtemps et il fait très chaud. C\'est la saison des vacances.',
    hint: 'C\'est quand on va à la piscine.',
    tags: ['cp', 'sciences', 'saisons', 'ete', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-009',
    subject: 'sciences',
    title: 'Eau : rivière',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on un cours d\'eau qui coule dans la nature ?',
    options: [
      { id: 'a', text: 'Un désert', isCorrect: false },
      { id: 'b', text: 'Une rivière', isCorrect: true },
      { id: 'c', text: 'Un nuage', isCorrect: false },
    ],
    correctAnswer: 'Une rivière',
    explanation: 'Une rivière est un cours d\'eau qui coule dans la nature. Les poissons y vivent.',
    hint: 'L\'eau y coule en permanence.',
    tags: ['cp', 'sciences', 'eau', 'nature', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-010',
    subject: 'sciences',
    title: 'Eau : à boire',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où vient l\'eau que nous buvons chez nous ?',
    options: [
      { id: 'a', text: 'Des nuages directement', isCorrect: false },
      { id: 'b', text: 'Du robinet', isCorrect: true },
      { id: 'c', text: 'De la mer', isCorrect: false },
    ],
    correctAnswer: 'Du robinet',
    explanation: 'L\'eau du robinet vient des rivières et des nappes souterraines. Elle est traitée pour être potable.',
    hint: 'On l\'ouvre dans la cuisine.',
    tags: ['cp', 'sciences', 'eau', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-011',
    subject: 'sciences',
    title: 'Nature : forêt',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une forêt ?',
    options: [
      { id: 'a', text: 'Un endroit plein de maisons', isCorrect: false },
      { id: 'b', text: 'Un grand espace avec beaucoup d\'arbres', isCorrect: true },
      { id: 'c', text: 'Une plage de sable', isCorrect: false },
    ],
    correctAnswer: 'Un grand espace avec beaucoup d\'arbres',
    explanation: 'Une forêt est un milieu naturel où poussent de nombreux arbres. Des animaux y vivent.',
    hint: 'On peut y trouver des champignons.',
    tags: ['cp', 'sciences', 'nature', 'foret', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-012',
    subject: 'sciences',
    title: 'Nature : le soleil',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que donne le soleil aux plantes ?',
    options: [
      { id: 'a', text: 'De l\'eau', isCorrect: false },
      { id: 'b', text: 'De la lumière et de la chaleur', isCorrect: true },
      { id: 'c', text: 'Du vent', isCorrect: false },
    ],
    correctAnswer: 'De la lumière et de la chaleur',
    explanation: 'Le soleil apporte lumière et chaleur nécessaires aux plantes pour pousser.',
    hint: 'Sans soleil, les plantes ne peuvent pas pousser.',
    tags: ['cp', 'sciences', 'soleil', 'meteo', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-013',
    subject: 'sciences',
    title: 'Météo : il fait froid',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que mets-tu quand il fait très froid dehors ?',
    options: [
      { id: 'a', text: 'Un maillot de bain', isCorrect: false },
      { id: 'b', text: 'Un manteau et une écharpe', isCorrect: true },
      { id: 'c', text: 'Des sandales', isCorrect: false },
    ],
    correctAnswer: 'Un manteau et une écharpe',
    explanation: 'Quand il fait froid, on s\'habille chaudement : manteau, écharpe, gants, bonnet.',
    hint: 'On porte ces vêtements en hiver.',
    tags: ['cp', 'sciences', 'meteo', 'froid', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-014',
    subject: 'sciences',
    title: 'Pollution : protéger la nature',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'environnement',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que faut-il faire pour protéger la nature ?',
    options: [
      { id: 'a', text: 'Jeter ses déchets par terre', isCorrect: false },
      { id: 'b', text: 'Mettre ses déchets à la poubelle', isCorrect: true },
      { id: 'c', text: 'Couper tous les arbres', isCorrect: false },
    ],
    correctAnswer: 'Mettre ses déchets à la poubelle',
    explanation: 'Pour protéger la nature, on jette ses déchets dans les poubelles et on peut les trier.',
    hint: 'On ne jette pas ses papiers par terre.',
    tags: ['cp', 'sciences', 'environnement', 'pollution', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-env-015',
    subject: 'sciences',
    title: 'Nature : la mer',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'habitats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel est le goût de l\'eau de la mer ?',
    options: [
      { id: 'a', text: 'Sucré', isCorrect: false },
      { id: 'b', text: 'Salé', isCorrect: true },
      { id: 'c', text: 'Sans goût', isCorrect: false },
    ],
    correctAnswer: 'Salé',
    explanation: 'L\'eau de la mer est salée. On ne peut pas la boire. L\'eau des rivières et des robinets est douce (pas salée).',
    hint: 'Si tu as déjà avalé de l\'eau de mer en nageant...',
    tags: ['cp', 'sciences', 'eau', 'mer', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
];
