import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCpMatiereExercises: ScienceExercise[] = [
  {
    id: 'sc-cp-mat-001',
    subject: 'sciences',
    title: 'Matière : solide',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'etats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces objets est solide ?',
    options: [
      { id: 'a', text: 'L\'eau dans un verre', isCorrect: false },
      { id: 'b', text: 'Une pierre', isCorrect: true },
      { id: 'c', text: 'La fumée', isCorrect: false },
    ],
    correctAnswer: 'Une pierre',
    explanation: 'Une pierre est solide : elle a une forme fixe qu\'on ne peut pas changer facilement.',
    hint: 'Un solide garde toujours la même forme.',
    tags: ['cp', 'sciences', 'matiere', 'solide', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-002',
    subject: 'sciences',
    title: 'Matière : liquide',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'etats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces éléments est un liquide ?',
    options: [
      { id: 'a', text: 'Le sable', isCorrect: false },
      { id: 'b', text: 'Le lait', isCorrect: true },
      { id: 'c', text: 'La glace', isCorrect: false },
    ],
    correctAnswer: 'Le lait',
    explanation: 'Le lait est un liquide : il coule et prend la forme du récipient où on le verse.',
    hint: 'Un liquide coule et peut être versé.',
    tags: ['cp', 'sciences', 'matiere', 'liquide', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-003',
    subject: 'sciences',
    title: 'Matière : gaz',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'etats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces éléments est un gaz ?',
    options: [
      { id: 'a', text: 'La brique', isCorrect: false },
      { id: 'b', text: 'L\'eau', isCorrect: false },
      { id: 'c', text: 'L\'air', isCorrect: true },
    ],
    correctAnswer: 'L\'air',
    explanation: 'L\'air est un gaz : il est invisible et remplit tout l\'espace disponible.',
    hint: 'On le respire mais on ne le voit pas.',
    tags: ['cp', 'sciences', 'matiere', 'gaz', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-004',
    subject: 'sciences',
    title: 'Glace → eau',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'changements-etat',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il quand un glaçon sort du congélateur et reste à température ambiante ?',
    options: [
      { id: 'a', text: 'Il reste solide', isCorrect: false },
      { id: 'b', text: 'Il fond et devient de l\'eau liquide', isCorrect: true },
      { id: 'c', text: 'Il devient de la vapeur', isCorrect: false },
    ],
    correctAnswer: 'Il fond et devient de l\'eau liquide',
    explanation: 'La glace fond quand elle se réchauffe. La glace (solide) devient de l\'eau (liquide).',
    hint: 'On met des glaçons dans un verre pour refroidir une boisson.',
    tags: ['cp', 'sciences', 'matiere', 'fonte', 'glace', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-005',
    subject: 'sciences',
    title: 'Objets techniques : roue',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert une roue sur un vélo ?',
    options: [
      { id: 'a', text: 'À décorer', isCorrect: false },
      { id: 'b', text: 'À avancer en roulant sur le sol', isCorrect: true },
      { id: 'c', text: 'À faire du bruit', isCorrect: false },
    ],
    correctAnswer: 'À avancer en roulant sur le sol',
    explanation: 'La roue permet de rouler sur le sol et d\'avancer facilement. C\'est une invention très ancienne.',
    hint: 'Les voitures et vélos ont des roues.',
    tags: ['cp', 'sciences', 'objets-techniques', 'roue', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-006',
    subject: 'sciences',
    title: 'Matériaux : bois ou plastique',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une table en bois est faite à partir de... ?',
    options: [
      { id: 'a', text: 'Du pétrole', isCorrect: false },
      { id: 'b', text: 'D\'arbres coupés', isCorrect: true },
      { id: 'c', text: 'De sable', isCorrect: false },
    ],
    correctAnswer: 'D\'arbres coupés',
    explanation: 'Le bois vient des arbres. On le coupe, on le taille et on en fait des meubles.',
    hint: 'Les arbres fournissent le bois.',
    tags: ['cp', 'sciences', 'materiaux', 'bois', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-007',
    subject: 'sciences',
    title: 'Objets techniques : usage',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert un ciseau ?',
    options: [
      { id: 'a', text: 'À coller du papier', isCorrect: false },
      { id: 'b', text: 'À couper du papier ou du tissu', isCorrect: true },
      { id: 'c', text: 'À mesurer', isCorrect: false },
    ],
    correctAnswer: 'À couper du papier ou du tissu',
    explanation: 'Le ciseau est un outil qui coupe. Il a deux lames qui se croisent.',
    hint: 'On l\'utilise pour faire des découpages.',
    tags: ['cp', 'sciences', 'objets-techniques', 'outils', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-008',
    subject: 'sciences',
    title: 'Matière : l\'eau prend la forme',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'etats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Si on verse de l\'eau dans un verre rond, quelle forme a-t-elle ?',
    options: [
      { id: 'a', text: 'Elle garde la forme carrée du robinet', isCorrect: false },
      { id: 'b', text: 'Elle prend la forme ronde du verre', isCorrect: true },
      { id: 'c', text: 'Elle ne rentre pas dans le verre', isCorrect: false },
    ],
    correctAnswer: 'Elle prend la forme ronde du verre',
    explanation: 'L\'eau est un liquide : elle prend toujours la forme du récipient dans lequel on la verse.',
    hint: 'Les liquides coulent et remplissent le contenant.',
    tags: ['cp', 'sciences', 'matiere', 'liquide', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-009',
    subject: 'sciences',
    title: 'Matériaux : métal',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel objet est fabriqué en métal ?',
    options: [
      { id: 'a', text: 'Un livre', isCorrect: false },
      { id: 'b', text: 'Une cuillère en acier', isCorrect: true },
      { id: 'c', text: 'Une écharpe', isCorrect: false },
    ],
    correctAnswer: 'Une cuillère en acier',
    explanation: 'L\'acier est un métal. Les cuillères, les casseroles et les clés sont souvent en métal.',
    hint: 'Les métaux brillent et sont souvent froids au toucher.',
    tags: ['cp', 'sciences', 'materiaux', 'metal', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-010',
    subject: 'sciences',
    title: 'Objets techniques : lumière',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel objet produit de la lumière dans une maison ?',
    options: [
      { id: 'a', text: 'Un livre', isCorrect: false },
      { id: 'b', text: 'Une ampoule', isCorrect: true },
      { id: 'c', text: 'Un tapis', isCorrect: false },
    ],
    correctAnswer: 'Une ampoule',
    explanation: 'Une ampoule électrique produit de la lumière quand on l\'allume.',
    hint: 'On l\'allume et l\'éteint avec un interrupteur.',
    tags: ['cp', 'sciences', 'objets-techniques', 'lumiere', 'electricite', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-011',
    subject: 'sciences',
    title: 'Matière : solide ou liquide ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'etats',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le beurre sorti du réfrigérateur est solide. Que se passe-t-il si on le fait chauffer ?',
    options: [
      { id: 'a', text: 'Il reste solide', isCorrect: false },
      { id: 'b', text: 'Il fond et devient liquide', isCorrect: true },
      { id: 'c', text: 'Il devient gaz', isCorrect: false },
    ],
    correctAnswer: 'Il fond et devient liquide',
    explanation: 'La chaleur fait fondre le beurre. Il passe de l\'état solide à l\'état liquide.',
    hint: 'Le chocolat fait pareil dans tes mains.',
    tags: ['cp', 'sciences', 'matiere', 'changements-etat', 'fonte', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-012',
    subject: 'sciences',
    title: 'Objets techniques : construire',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel outil utilise-t-on pour enfoncer un clou dans le bois ?',
    options: [
      { id: 'a', text: 'Un ciseau', isCorrect: false },
      { id: 'b', text: 'Un marteau', isCorrect: true },
      { id: 'c', text: 'Une règle', isCorrect: false },
    ],
    correctAnswer: 'Un marteau',
    explanation: 'Le marteau sert à frapper les clous pour les enfoncer dans le bois ou le mur.',
    hint: 'Il a une tête lourde en métal.',
    tags: ['cp', 'sciences', 'objets-techniques', 'outils', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-013',
    subject: 'sciences',
    title: 'Matériaux : verre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'materiaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi est fait une vitre de fenêtre ?',
    options: [
      { id: 'a', text: 'De plastique souple', isCorrect: false },
      { id: 'b', text: 'De verre', isCorrect: true },
      { id: 'c', text: 'De tissu', isCorrect: false },
    ],
    correctAnswer: 'De verre',
    explanation: 'Le verre est un matériau transparent, solide mais fragile. Les vitres, les bouteilles et les verres sont en verre.',
    hint: 'On voit à travers, mais il peut se casser.',
    tags: ['cp', 'sciences', 'materiaux', 'verre', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-mat-014',
    subject: 'sciences',
    title: 'Objets techniques : téléphone',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'matiere',
    subskill: 'objets-techniques',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert un téléphone ?',
    options: [
      { id: 'a', text: 'À chauffer la maison', isCorrect: false },
      { id: 'b', text: 'À communiquer avec des personnes éloignées', isCorrect: true },
      { id: 'c', text: 'À couper des légumes', isCorrect: false },
    ],
    correctAnswer: 'À communiquer avec des personnes éloignées',
    explanation: 'Le téléphone permet de parler ou d\'envoyer des messages à des personnes qui sont loin.',
    hint: 'On l\'utilise pour appeler maman ou papa.',
    tags: ['cp', 'sciences', 'objets-techniques', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
];
