import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCpTerreExercises: ScienceExercise[] = [
  {
    id: 'sc-cp-ter-001',
    subject: 'sciences',
    title: 'Ciel : jour et nuit',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi fait-il nuit ?',
    options: [
      { id: 'a', text: 'Le soleil s\'éteint le soir', isCorrect: false },
      { id: 'b', text: 'La Terre tourne et notre côté n\'est plus face au Soleil', isCorrect: true },
      { id: 'c', text: 'La Lune cache le Soleil', isCorrect: false },
    ],
    correctAnswer: 'La Terre tourne et notre côté n\'est plus face au Soleil',
    explanation: 'La Terre tourne sur elle-même. Quand notre côté est face au Soleil, c\'est le jour. Quand il est de l\'autre côté, c\'est la nuit.',
    hint: 'La Terre fait un tour complet en 24 heures.',
    tags: ['cp', 'sciences', 'terre', 'jour-nuit', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-002',
    subject: 'sciences',
    title: 'Saisons : été et hiver',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'En quelle saison fait-il le plus froid en France ?',
    options: [
      { id: 'a', text: 'En été', isCorrect: false },
      { id: 'b', text: 'En hiver', isCorrect: true },
      { id: 'c', text: 'Au printemps', isCorrect: false },
    ],
    correctAnswer: 'En hiver',
    explanation: 'En France, l\'hiver (décembre, janvier, février) est la saison la plus froide. Il peut neiger et les journées sont courtes.',
    hint: 'En hiver, on met un manteau pour sortir.',
    tags: ['cp', 'sciences', 'terre', 'saisons', 'hiver', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-003',
    subject: 'sciences',
    title: 'Soleil : astre du jour',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le Soleil ?',
    options: [
      { id: 'a', text: 'Une planète comme la Terre', isCorrect: false },
      { id: 'b', text: 'Une étoile très grande et très chaude', isCorrect: true },
      { id: 'c', text: 'Une lampe géante dans le ciel', isCorrect: false },
    ],
    correctAnswer: 'Une étoile très grande et très chaude',
    explanation: 'Le Soleil est une étoile : une boule de gaz très chaud qui brille. Il est tellement grand que des millions de Terres rentreraient dedans.',
    hint: 'Le Soleil donne chaud et lumière à toute la Terre.',
    tags: ['cp', 'sciences', 'terre', 'soleil', 'etoile', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-004',
    subject: 'sciences',
    title: 'Lune : la nuit',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Lune produit-elle sa propre lumière ?',
    options: [
      { id: 'a', text: 'Oui, elle brille toute seule', isCorrect: false },
      { id: 'b', text: 'Non, elle reflète la lumière du Soleil', isCorrect: true },
      { id: 'c', text: 'Oui, elle est comme une ampoule géante', isCorrect: false },
    ],
    correctAnswer: 'Non, elle reflète la lumière du Soleil',
    explanation: 'La Lune ne brille pas toute seule. Elle est comme un miroir qui réfléchit la lumière du Soleil. C\'est pour ça qu\'elle éclaire la nuit.',
    hint: 'Pense à un miroir qui réfléchit la lumière.',
    tags: ['cp', 'sciences', 'terre', 'lune', 'lumiere', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-005',
    subject: 'sciences',
    title: 'Météo : la pluie',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'D\'où vient la pluie ?',
    options: [
      { id: 'a', text: 'Des rivières qui débordent', isCorrect: false },
      { id: 'b', text: 'Des nuages dans le ciel', isCorrect: true },
      { id: 'c', text: 'De la mer directement', isCorrect: false },
    ],
    correctAnswer: 'Des nuages dans le ciel',
    explanation: 'Les nuages sont faits de minuscules gouttes d\'eau. Quand les gouttes deviennent trop lourdes, elles tombent sous forme de pluie.',
    hint: 'Regarde le ciel avant qu\'il pleuve : il y a toujours des nuages sombres.',
    tags: ['cp', 'sciences', 'terre', 'meteo', 'pluie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-006',
    subject: 'sciences',
    title: 'Météo : le vent',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que le vent ?',
    options: [
      { id: 'a', text: 'De l\'air chaud qui tombe du ciel', isCorrect: false },
      { id: 'b', text: 'De l\'air qui se déplace d\'un endroit à un autre', isCorrect: true },
      { id: 'c', text: 'Des nuages qui se déplacent très vite', isCorrect: false },
    ],
    correctAnswer: 'De l\'air qui se déplace d\'un endroit à un autre',
    explanation: 'Le vent, c\'est de l\'air en mouvement. Quand l\'air chaud monte, l\'air froid prend sa place et ça crée du vent.',
    hint: 'Le vent fait bouger les feuilles des arbres.',
    tags: ['cp', 'sciences', 'terre', 'meteo', 'vent', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-007',
    subject: 'sciences',
    title: 'Saisons : printemps',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il au printemps ?',
    options: [
      { id: 'a', text: 'Les feuilles tombent des arbres', isCorrect: false },
      { id: 'b', text: 'Les fleurs poussent et les oiseaux font leurs nids', isCorrect: true },
      { id: 'c', text: 'Il neige beaucoup', isCorrect: false },
    ],
    correctAnswer: 'Les fleurs poussent et les oiseaux font leurs nids',
    explanation: 'Au printemps, il fait plus chaud. Les plantes refleurissent et les animaux se réveillent. C\'est une saison de renouveau.',
    hint: 'Au printemps, on voit les premières fleurs et les premières hirondelles.',
    tags: ['cp', 'sciences', 'terre', 'saisons', 'printemps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-008',
    subject: 'sciences',
    title: 'Ciel : les étoiles',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi voit-on les étoiles seulement la nuit ?',
    options: [
      { id: 'a', text: 'Les étoiles disparaissent le jour', isCorrect: false },
      { id: 'b', text: 'La lumière du Soleil est trop forte le jour pour qu\'on les voie', isCorrect: true },
      { id: 'c', text: 'Les étoiles dorment le jour', isCorrect: false },
    ],
    correctAnswer: 'La lumière du Soleil est trop forte le jour pour qu\'on les voie',
    explanation: 'Les étoiles sont là le jour et la nuit. Mais le jour, la lumière du Soleil est tellement forte qu\'on ne peut plus les voir. La nuit, sans le Soleil, elles deviennent visibles.',
    hint: 'Les étoiles ne disparaissent pas — c\'est le Soleil qui les cache.',
    tags: ['cp', 'sciences', 'terre', 'astronomie', 'etoiles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-009',
    subject: 'sciences',
    title: 'Météo : arc-en-ciel',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand voit-on un arc-en-ciel ?',
    options: [
      { id: 'a', text: 'Quand il fait très chaud et sec', isCorrect: false },
      { id: 'b', text: 'Quand il y a à la fois du soleil et des gouttes de pluie', isCorrect: true },
      { id: 'c', text: 'Seulement pendant la nuit', isCorrect: false },
    ],
    correctAnswer: 'Quand il y a à la fois du soleil et des gouttes de pluie',
    explanation: 'Un arc-en-ciel se forme quand la lumière du Soleil traverse des gouttes de pluie. Les gouttes agissent comme des prismes et séparent la lumière en toutes ses couleurs.',
    hint: 'Arc-en-ciel = soleil + pluie en même temps.',
    tags: ['cp', 'sciences', 'terre', 'meteo', 'arc-en-ciel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-010',
    subject: 'sciences',
    title: 'Terre : forme de la Terre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la forme de la Terre ?',
    options: [
      { id: 'a', text: 'Plate comme une crêpe', isCorrect: false },
      { id: 'b', text: 'Ronde comme une balle (sphérique)', isCorrect: true },
      { id: 'c', text: 'En forme de cube', isCorrect: false },
    ],
    correctAnswer: 'Ronde comme une balle (sphérique)',
    explanation: 'La Terre est une sphère (presque ronde). On peut le voir sur les photos prises depuis l\'espace par les astronautes.',
    hint: 'Les astronautes voient la Terre ronde depuis leur fusée.',
    tags: ['cp', 'sciences', 'terre', 'geographie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-011',
    subject: 'sciences',
    title: 'Ciel : lever du soleil',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quel côté le Soleil se lève-t-il chaque matin ?',
    options: [
      { id: 'a', text: 'À l\'ouest', isCorrect: false },
      { id: 'b', text: 'À l\'est', isCorrect: true },
      { id: 'c', text: 'Au nord', isCorrect: false },
    ],
    correctAnswer: 'À l\'est',
    explanation: 'Le Soleil se lève toujours à l\'est et se couche à l\'ouest. C\'est ainsi qu\'on peut s\'orienter dans la nature.',
    hint: 'Est = là où le soleil se lève le matin.',
    tags: ['cp', 'sciences', 'terre', 'astronomie', 'orientation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-012',
    subject: 'sciences',
    title: 'Météo : la neige',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La neige est de l\'eau sous quelle forme ?',
    options: [
      { id: 'a', text: 'De l\'eau liquide', isCorrect: false },
      { id: 'b', text: 'De l\'eau solidifiée en cristaux de glace', isCorrect: true },
      { id: 'c', text: 'De la vapeur d\'eau froide', isCorrect: false },
    ],
    correctAnswer: 'De l\'eau solidifiée en cristaux de glace',
    explanation: 'La neige se forme quand l\'eau dans les nuages gèle. Chaque flocon de neige est un cristal de glace unique avec une forme en étoile à 6 branches.',
    hint: 'La neige fond et redevient de l\'eau quand il fait chaud.',
    tags: ['cp', 'sciences', 'terre', 'meteo', 'neige', 'glace', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-013',
    subject: 'sciences',
    title: 'Eau : états de l\'eau',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sous quelle forme peut-on trouver de l\'eau dans la nature ?',
    options: [
      { id: 'a', text: 'Seulement liquide (rivières, mer)', isCorrect: false },
      { id: 'b', text: 'Liquide (rivière), solide (glace) et gaz (vapeur)', isCorrect: true },
      { id: 'c', text: 'Seulement solide (glace et neige)', isCorrect: false },
    ],
    correctAnswer: 'Liquide (rivière), solide (glace) et gaz (vapeur)',
    explanation: 'L\'eau existe sous trois formes : liquide (mer, rivière), solide (glace, neige) et gaz (vapeur d\'eau dans l\'air). Ces trois états peuvent se transformer l\'un en l\'autre.',
    hint: 'L\'eau dans ton verre = liquide. Un glaçon = solide. La buée = gaz.',
    tags: ['cp', 'sciences', 'terre', 'eau', 'etats', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-014',
    subject: 'sciences',
    title: 'Ciel : la Lune change de forme',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi la Lune semble-t-elle changer de forme chaque nuit ?',
    options: [
      { id: 'a', text: 'La Lune rétrécit puis grandit chaque mois', isCorrect: false },
      { id: 'b', text: 'On voit différentes parties de la Lune éclairées par le Soleil selon sa position', isCorrect: true },
      { id: 'c', text: 'Des nuages cachent une partie de la Lune', isCorrect: false },
    ],
    correctAnswer: 'On voit différentes parties de la Lune éclairées par le Soleil selon sa position',
    explanation: 'La Lune tourne autour de la Terre. Selon sa position, on voit plus ou moins la partie éclairée par le Soleil : c\'est ce qu\'on appelle les phases de la Lune.',
    hint: 'Pleine lune, demi-lune, croissant — ce sont les phases de la Lune.',
    tags: ['cp', 'sciences', 'terre', 'astronomie', 'lune', 'phases', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-015',
    subject: 'sciences',
    title: 'Saisons : automne',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'arrive-t-il aux feuilles en automne ?',
    options: [
      { id: 'a', text: 'Elles poussent et deviennent vertes', isCorrect: false },
      { id: 'b', text: 'Elles changent de couleur (jaune, orange, rouge) et tombent', isCorrect: true },
      { id: 'c', text: 'Elles deviennent bleues à cause du froid', isCorrect: false },
    ],
    correctAnswer: 'Elles changent de couleur (jaune, orange, rouge) et tombent',
    explanation: 'En automne, les jours raccourcissent et il fait plus froid. Les arbres à feuilles caduques perdent leurs feuilles qui deviennent d\'abord jaunes, oranges ou rouges avant de tomber.',
    hint: 'On ramasse les feuilles mortes en automne dans les jardins.',
    tags: ['cp', 'sciences', 'terre', 'saisons', 'automne', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-016',
    subject: 'sciences',
    title: 'Sol : composition',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La terre du jardin est-elle vivante ?',
    options: [
      { id: 'a', text: 'Non, la terre est juste de la poussière', isCorrect: false },
      { id: 'b', text: 'Oui, elle contient des vers, des insectes et des microbes', isCorrect: true },
      { id: 'c', text: 'Non, les animaux vivent à la surface mais pas dans la terre', isCorrect: false },
    ],
    correctAnswer: 'Oui, elle contient des vers, des insectes et des microbes',
    explanation: 'La terre est pleine de vie invisible : des millions de microbes, des vers de terre, des insectes, des champignons. Ils décomposent les feuilles mortes et nourrissent les plantes.',
    hint: 'Si on creuse dans le jardin, on trouve souvent des vers de terre.',
    tags: ['cp', 'sciences', 'terre', 'sol', 'vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-017',
    subject: 'sciences',
    title: 'Météo : l\'orage',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'un éclair ?',
    options: [
      { id: 'a', text: 'Un rayon de lumière réfléchi par la Lune', isCorrect: false },
      { id: 'b', text: 'Une décharge électrique géante dans le ciel', isCorrect: true },
      { id: 'c', text: 'Un morceau de soleil qui tombe', isCorrect: false },
    ],
    correctAnswer: 'Une décharge électrique géante dans le ciel',
    explanation: 'L\'éclair est une énorme décharge électrique. Il peut aller d\'un nuage à un autre ou d\'un nuage vers le sol. Le tonnerre est le bruit produit par cet éclair.',
    hint: 'On entend le tonnerre après l\'éclair car la lumière va plus vite que le son.',
    tags: ['cp', 'sciences', 'terre', 'meteo', 'orage', 'eclair', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-018',
    subject: 'sciences',
    title: 'Planètes : la Terre dans l\'espace',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une planète ?',
    options: [
      { id: 'a', text: 'Une étoile qui brille très fort', isCorrect: false },
      { id: 'b', text: 'Un gros objet rond qui tourne autour d\'une étoile', isCorrect: true },
      { id: 'c', text: 'Un nuage géant dans l\'espace', isCorrect: false },
    ],
    correctAnswer: 'Un gros objet rond qui tourne autour d\'une étoile',
    explanation: 'Une planète est un gros astre sphérique qui tourne autour d\'une étoile. La Terre est une planète qui tourne autour du Soleil. Il y a 8 planètes dans notre système solaire.',
    hint: 'La Terre tourne autour du Soleil en 365 jours = 1 an.',
    tags: ['cp', 'sciences', 'terre', 'astronomie', 'planetes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-019',
    subject: 'sciences',
    title: 'Eau : le cycle simplifié',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'arrive-t-il à l\'eau des flaques après la pluie quand il fait soleil ?',
    options: [
      { id: 'a', text: 'Elle s\'enfonce dans la terre uniquement', isCorrect: false },
      { id: 'b', text: 'Elle s\'évapore et monte dans le ciel pour former des nuages', isCorrect: true },
      { id: 'c', text: 'Elle disparaît pour toujours', isCorrect: false },
    ],
    correctAnswer: 'Elle s\'évapore et monte dans le ciel pour former des nuages',
    explanation: 'Le soleil chauffe l\'eau et la transforme en vapeur d\'eau invisible qui monte dans le ciel. Là, elle refroidit et forme des nuages. Puis il repleut. C\'est le cycle de l\'eau.',
    hint: 'Après la pluie, les flaques disparaissent quand il fait beau : l\'eau s\'évapore.',
    tags: ['cp', 'sciences', 'terre', 'eau', 'evaporation', 'cycle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-020',
    subject: 'sciences',
    title: 'Météo : le brouillard',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'meteo',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le brouillard, c\'est quoi ?',
    options: [
      { id: 'a', text: 'De la fumée provenant des villes', isCorrect: false },
      { id: 'b', text: 'Un nuage très bas qui touche le sol', isCorrect: true },
      { id: 'c', text: 'De la poussière en suspension', isCorrect: false },
    ],
    correctAnswer: 'Un nuage très bas qui touche le sol',
    explanation: 'Le brouillard est en réalité un nuage qui s\'est formé très près du sol. Il est fait de très petites gouttelettes d\'eau flottant dans l\'air.',
    hint: 'Dans le brouillard, on ne voit pas loin, comme dans les nuages.',
    tags: ['cp', 'sciences', 'terre', 'meteo', 'brouillard', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-021',
    subject: 'sciences',
    title: 'Sol : roches',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'terre',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les cailloux et les roches, c\'est naturel ou fabriqué par l\'homme ?',
    options: [
      { id: 'a', text: 'Fabriqué par l\'homme dans des usines', isCorrect: false },
      { id: 'b', text: 'Naturel, formé par la Terre depuis très longtemps', isCorrect: true },
      { id: 'c', text: 'Fabriqué par les animaux', isCorrect: false },
    ],
    correctAnswer: 'Naturel, formé par la Terre depuis très longtemps',
    explanation: 'Les roches sont naturelles. Elles se forment de plusieurs façons : par refroidissement du magma (lave), par compression de sédiments, etc. Certaines ont des millions d\'années.',
    hint: 'On trouve des cailloux dans la nature sans que personne ne les ait fabriqués.',
    tags: ['cp', 'sciences', 'terre', 'roches', 'naturel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-022',
    subject: 'sciences',
    title: 'Ciel : couleur du ciel',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'astronomie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Pourquoi le ciel est-il bleu par beau temps ?',
    options: [
      { id: 'a', text: 'Parce que la mer reflète le bleu dans le ciel', isCorrect: false },
      { id: 'b', text: 'Parce que l\'air diffuse la lumière bleue du Soleil mieux que les autres couleurs', isCorrect: true },
      { id: 'c', text: 'Parce que le Soleil est bleu', isCorrect: false },
    ],
    correctAnswer: 'Parce que l\'air diffuse la lumière bleue du Soleil mieux que les autres couleurs',
    explanation: 'La lumière du Soleil contient toutes les couleurs. En traversant l\'atmosphère, les petites molécules d\'air diffusent la lumière bleue dans toutes les directions. C\'est pour ça que le ciel paraît bleu.',
    hint: 'Au coucher du soleil, le ciel devient rouge/orange car la lumière parcourt plus d\'atmosphère.',
    tags: ['cp', 'sciences', 'terre', 'astronomie', 'ciel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-023',
    subject: 'sciences',
    title: 'Saisons : les 4 saisons',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'saisons',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien y a-t-il de saisons en France ?',
    options: [
      { id: 'a', text: '2 saisons (été et hiver)', isCorrect: false },
      { id: 'b', text: '4 saisons (printemps, été, automne, hiver)', isCorrect: true },
      { id: 'c', text: '6 saisons', isCorrect: false },
    ],
    correctAnswer: '4 saisons (printemps, été, automne, hiver)',
    explanation: 'En France, il y a 4 saisons. Elles se succèdent dans l\'ordre : printemps (mars), été (juin), automne (septembre), hiver (décembre).',
    hint: 'Chaque saison dure environ 3 mois.',
    tags: ['cp', 'sciences', 'terre', 'saisons', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-024',
    subject: 'sciences',
    title: 'Eau : la mer',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'eau',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'eau de la mer est-elle bonne à boire ?',
    options: [
      { id: 'a', text: 'Oui, comme l\'eau du robinet', isCorrect: false },
      { id: 'b', text: 'Non, elle est trop salée pour qu\'on la boive', isCorrect: true },
      { id: 'c', text: 'Oui, si on la chauffe d\'abord', isCorrect: false },
    ],
    correctAnswer: 'Non, elle est trop salée pour qu\'on la boive',
    explanation: 'L\'eau de mer contient beaucoup de sel. Si on boit de l\'eau salée, le corps perd encore plus d\'eau pour éliminer le sel. C\'est dangereux. On boit l\'eau douce des rivières et des lacs.',
    hint: 'Si tu as déjà avalé de l\'eau de mer à la plage, tu sais qu\'elle est très salée !',
    tags: ['cp', 'sciences', 'terre', 'eau', 'mer', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-ter-025',
    subject: 'sciences',
    title: 'Environnement : protéger la nature',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'environnement',
    subskill: 'ecologie',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que peut-on faire pour aider la nature dans son jardin ou au parc ?',
    options: [
      { id: 'a', text: 'Cueillir toutes les fleurs sauvages', isCorrect: false },
      { id: 'b', text: 'Ne pas jeter de déchets et laisser des zones sauvages pour les insectes', isCorrect: true },
      { id: 'c', text: 'Couper les arbres pour faire de la place', isCorrect: false },
    ],
    correctAnswer: 'Ne pas jeter de déchets et laisser des zones sauvages pour les insectes',
    explanation: 'On peut aider la nature en ne jetant pas de déchets, en laissant des coins sauvages pour les insectes, en mettant un nichoir pour les oiseaux et en plantant des fleurs pour les abeilles.',
    hint: 'Chaque geste compte pour protéger les animaux et les plantes.',
    tags: ['cp', 'sciences', 'terre', 'ecologie', 'nature', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
