import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { ScienceExercise } from '../science.types';

export const scienceCpVivantExercises: ScienceExercise[] = [
  {
    id: 'sc-cp-viv-001',
    subject: 'sciences',
    title: 'Animal aquatique',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Parmi ces animaux, lequel vit dans l\'eau ?',
    options: [
      { id: 'a', text: 'Le chien', isCorrect: false },
      { id: 'b', text: 'Le poisson', isCorrect: true },
      { id: 'c', text: 'Le lapin', isCorrect: false },
    ],
    correctAnswer: 'Le poisson',
    explanation: 'Le poisson vit dans l\'eau. Le chien et le lapin vivent sur la terre.',
    hint: 'Pense à l\'animal qu\'on trouve dans un aquarium.',
    tags: ['cp', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-002',
    subject: 'sciences',
    title: 'Animal qui pond des œufs',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal pond des œufs ?',
    options: [
      { id: 'a', text: 'La vache', isCorrect: false },
      { id: 'b', text: 'La poule', isCorrect: true },
      { id: 'c', text: 'La chatte', isCorrect: false },
    ],
    correctAnswer: 'La poule',
    explanation: 'La poule pond des œufs. La vache et la chatte donnent naissance à des petits vivants.',
    hint: 'On trouve ses œufs dans les rayons du supermarché.',
    tags: ['cp', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-003',
    subject: 'sciences',
    title: 'Animal avec des ailes',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal a des ailes et peut voler ?',
    options: [
      { id: 'a', text: 'Le cochon', isCorrect: false },
      { id: 'b', text: 'L\'oiseau', isCorrect: true },
      { id: 'c', text: 'La vache', isCorrect: false },
    ],
    correctAnswer: 'L\'oiseau',
    explanation: 'L\'oiseau a des ailes et peut voler. Les autres animaux cités n\'ont pas d\'ailes.',
    hint: 'Cet animal chante dans les arbres.',
    tags: ['cp', 'sciences', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-004',
    subject: 'sciences',
    title: 'Vivant : arbre',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces objets est vivant ?',
    options: [
      { id: 'a', text: 'Une pierre', isCorrect: false },
      { id: 'b', text: 'Un arbre', isCorrect: true },
      { id: 'c', text: 'Une chaise', isCorrect: false },
    ],
    correctAnswer: 'Un arbre',
    explanation: 'Un arbre est vivant : il grandit, se nourrit et se reproduit. Une pierre et une chaise ne sont pas vivantes.',
    hint: 'Cet être pousse, a des feuilles et peut donner des fruits.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-005',
    subject: 'sciences',
    title: 'Non vivant : table',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel n\'est PAS vivant ?',
    options: [
      { id: 'a', text: 'Un chien', isCorrect: false },
      { id: 'b', text: 'Une fleur', isCorrect: false },
      { id: 'c', text: 'Une table', isCorrect: true },
    ],
    correctAnswer: 'Une table',
    explanation: 'Une table n\'est pas vivante : elle ne grandit pas, ne mange pas, ne respire pas.',
    hint: 'Cet objet a été fabriqué par l\'homme.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-006',
    subject: 'sciences',
    title: 'Vivant : chien',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui est vivant ?',
    options: [
      { id: 'a', text: 'Un caillou', isCorrect: false },
      { id: 'b', text: 'Une voiture', isCorrect: false },
      { id: 'c', text: 'Un chien', isCorrect: true },
    ],
    correctAnswer: 'Un chien',
    explanation: 'Un chien est vivant : il respire, mange, bouge et grandit.',
    hint: 'Cet être a besoin de manger et de boire pour vivre.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-007',
    subject: 'sciences',
    title: 'Vivant : fleur',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces éléments est vivant ?',
    options: [
      { id: 'a', text: 'L\'eau', isCorrect: false },
      { id: 'b', text: 'Une fleur', isCorrect: true },
      { id: 'c', text: 'Une roche', isCorrect: false },
    ],
    correctAnswer: 'Une fleur',
    explanation: 'Une fleur est vivante : elle pousse, a besoin d\'eau et de lumière. L\'eau et une roche ne sont pas des êtres vivants.',
    hint: 'Cet élément pousse et a besoin d\'eau.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-008',
    subject: 'sciences',
    title: 'Non vivant : bougie',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'vivant_non_vivant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel n\'est PAS vivant ?',
    options: [
      { id: 'a', text: 'Un ver de terre', isCorrect: false },
      { id: 'b', text: 'Une bougie', isCorrect: true },
      { id: 'c', text: 'Un moineau', isCorrect: false },
    ],
    correctAnswer: 'Une bougie',
    explanation: 'Une bougie n\'est pas vivante : elle ne grandit pas, ne mange pas et ne se reproduit pas.',
    hint: 'Cet objet a été fabriqué, il ne respire pas.',
    tags: ['cp', 'sciences', 'vivant_non_vivant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

    {
    id: 'sc-cp-viv-009',
    subject: 'sciences',
    title: 'Plante : besoin d\'eau',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qu\'une plante en pot a besoin pour ne pas mourir ?',
    options: [
      { id: 'a', text: 'Du sel', isCorrect: false },
      { id: 'b', text: 'De l\'eau', isCorrect: true },
      { id: 'c', text: 'Du sable', isCorrect: false },
    ],
    correctAnswer: 'De l\'eau',
    explanation: 'Une plante a besoin d\'eau pour vivre et pousser. Sans eau, elle se dessèche et meurt.',
    hint: 'Pense à ce qu\'on fait quand on arrose les fleurs.',
    tags: ['cp', 'sciences', 'plantes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-010',
    subject: 'sciences',
    title: 'Animal herbivore',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal mange uniquement des plantes et de l\'herbe ?',
    options: [
      { id: 'a', text: 'Le loup', isCorrect: false },
      { id: 'b', text: 'La vache', isCorrect: true },
      { id: 'c', text: 'Le renard', isCorrect: false },
    ],
    correctAnswer: 'La vache',
    explanation: 'La vache est herbivore : elle mange de l\'herbe. Le loup et le renard mangent d\'autres animaux.',
    hint: 'Cet animal broute l\'herbe dans les prés.',
    tags: ['cp', 'sciences', 'animaux', 'herbivore', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-011',
    subject: 'sciences',
    title: 'Lumière et plante',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'De quoi une plante a-t-elle aussi besoin, en plus de l\'eau, pour pousser ?',
    options: [
      { id: 'a', text: 'Du chocolat', isCorrect: false },
      { id: 'b', text: 'De la lumière du soleil', isCorrect: true },
      { id: 'c', text: 'De la musique', isCorrect: false },
    ],
    correctAnswer: 'De la lumière du soleil',
    explanation: 'Les plantes ont besoin de lumière pour fabriquer leur nourriture. Sans lumière, elles jaunissent.',
    hint: 'Les plantes tournent vers la fenêtre.',
    tags: ['cp', 'sciences', 'plantes', 'lumiere', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-012',
    subject: 'sciences',
    title: 'Animal insecte',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de pattes a un insecte ?',
    options: [
      { id: 'a', text: '4 pattes', isCorrect: false },
      { id: 'b', text: '6 pattes', isCorrect: true },
      { id: 'c', text: '8 pattes', isCorrect: false },
    ],
    correctAnswer: '6 pattes',
    explanation: 'Tous les insectes ont 6 pattes. L\'araignée en a 8 (ce n\'est pas un insecte).',
    hint: 'Compte les pattes d\'une fourmi.',
    tags: ['cp', 'sciences', 'animaux', 'insectes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-013',
    subject: 'sciences',
    title: 'Bébé animal',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment s\'appelle le bébé du chat ?',
    options: [
      { id: 'a', text: 'Un chaton', isCorrect: true },
      { id: 'b', text: 'Un poulain', isCorrect: false },
      { id: 'c', text: 'Un agneau', isCorrect: false },
    ],
    correctAnswer: 'Un chaton',
    explanation: 'Le bébé chat s\'appelle un chaton. Le bébé cheval est un poulain, le bébé mouton est un agneau.',
    hint: 'C\'est un mini-chat.',
    tags: ['cp', 'sciences', 'animaux', 'bebes', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-014',
    subject: 'sciences',
    title: 'Parties d\'une plante',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle partie de la plante est sous la terre ?',
    options: [
      { id: 'a', text: 'Les feuilles', isCorrect: false },
      { id: 'b', text: 'Les racines', isCorrect: true },
      { id: 'c', text: 'Les fleurs', isCorrect: false },
    ],
    correctAnswer: 'Les racines',
    explanation: 'Les racines sont enfouies dans la terre. Elles servent à boire l\'eau et à tenir la plante.',
    hint: 'On ne les voit pas.',
    tags: ['cp', 'sciences', 'plantes', 'racines', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-015',
    subject: 'sciences',
    title: 'Nid d\'oiseau',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où les oiseaux font-ils leur nid ?',
    options: [
      { id: 'a', text: 'Sous l\'eau', isCorrect: false },
      { id: 'b', text: 'Dans les arbres ou sur les toits', isCorrect: true },
      { id: 'c', text: 'Dans le sable', isCorrect: false },
    ],
    correctAnswer: 'Dans les arbres ou sur les toits',
    explanation: 'Les oiseaux construisent leur nid avec des brindilles, dans les arbres ou sur les rebords des toits.',
    hint: 'Les oiseaux volent pour y arriver.',
    tags: ['cp', 'sciences', 'animaux', 'habitats', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-016',
    subject: 'sciences',
    title: 'Animal mammifère',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal allaite ses petits avec du lait ?',
    options: [
      { id: 'a', text: 'La poule', isCorrect: false },
      { id: 'b', text: 'La chatte', isCorrect: true },
      { id: 'c', text: 'La tortue', isCorrect: false },
    ],
    correctAnswer: 'La chatte',
    explanation: 'La chatte est un mammifère : elle allaite ses chatons avec du lait. La poule et la tortue pondent des œufs.',
    hint: 'Cet animal a des poils et allaite ses petits.',
    tags: ['cp', 'sciences', 'animaux', 'mammiferes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-017',
    subject: 'sciences',
    title: 'Fleur et fruit',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce qui pousse à la place d\'une fleur après sa fécondation ?',
    options: [
      { id: 'a', text: 'Une racine', isCorrect: false },
      { id: 'b', text: 'Un fruit', isCorrect: true },
      { id: 'c', text: 'Une feuille', isCorrect: false },
    ],
    correctAnswer: 'Un fruit',
    explanation: 'Après la fleur vient le fruit, qui contient des graines.',
    hint: 'Les cerisiers font d\'abord des fleurs, puis...',
    tags: ['cp', 'sciences', 'plantes', 'fleurs', 'fruits', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-018',
    subject: 'sciences',
    title: 'Animal carnivore',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal mange d\'autres animaux ?',
    options: [
      { id: 'a', text: 'La girafe', isCorrect: false },
      { id: 'b', text: 'Le lion', isCorrect: true },
      { id: 'c', text: 'L\'éléphant', isCorrect: false },
    ],
    correctAnswer: 'Le lion',
    explanation: 'Le lion est carnivore : il chasse et mange d\'autres animaux. La girafe et l\'éléphant mangent des plantes.',
    hint: 'C\'est le roi de la savane.',
    tags: ['cp', 'sciences', 'animaux', 'carnivore', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-019',
    subject: 'sciences',
    title: 'Cycle de vie : chenille',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que devient une chenille ?',
    options: [
      { id: 'a', text: 'Un oiseau', isCorrect: false },
      { id: 'b', text: 'Un papillon', isCorrect: true },
      { id: 'c', text: 'Un ver de terre', isCorrect: false },
    ],
    correctAnswer: 'Un papillon',
    explanation: 'La chenille se transforme en chrysalide puis en papillon. C\'est une métamorphose.',
    hint: 'Cet animal vole et a de belles ailes colorées.',
    tags: ['cp', 'sciences', 'animaux', 'metamorphose', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-020',
    subject: 'sciences',
    title: 'Graine et germination',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Si on plante une graine dans la terre et qu\'on l\'arrose, que va-t-il se passer ?',
    options: [
      { id: 'a', text: 'La graine va flotter', isCorrect: false },
      { id: 'b', text: 'Une petite plante va pousser', isCorrect: true },
      { id: 'c', text: 'Rien ne va se passer', isCorrect: false },
    ],
    correctAnswer: 'Une petite plante va pousser',
    explanation: 'Avec de l\'eau et de la chaleur, la graine germe et donne naissance à une jeune plante.',
    hint: 'C\'est comme ça que poussent toutes les plantes.',
    tags: ['cp', 'sciences', 'plantes', 'germination', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-021',
    subject: 'sciences',
    title: 'Animal domestique',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces animaux est un animal domestique (qui vit avec les humains) ?',
    options: [
      { id: 'a', text: 'Le loup', isCorrect: false },
      { id: 'b', text: 'Le chien', isCorrect: true },
      { id: 'c', text: 'Le renard', isCorrect: false },
    ],
    correctAnswer: 'Le chien',
    explanation: 'Le chien vit avec les humains depuis très longtemps : c\'est un animal domestique. Le loup et le renard sont des animaux sauvages.',
    hint: 'On peut le caresser et il dort à la maison.',
    tags: ['cp', 'sciences', 'animaux', 'domestique', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-022',
    subject: 'sciences',
    title: 'Animal sauvage',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où vit un animal sauvage ?',
    options: [
      { id: 'a', text: 'Dans une maison avec les humains', isCorrect: false },
      { id: 'b', text: 'Dans la nature, librement', isCorrect: true },
      { id: 'c', text: 'Toujours dans un zoo', isCorrect: false },
    ],
    correctAnswer: 'Dans la nature, librement',
    explanation: 'Un animal sauvage vit dans la nature et trouve lui-même sa nourriture. Il n\'a pas besoin des humains.',
    hint: 'Un renard vit dans la forêt, pas dans un appartement.',
    tags: ['cp', 'sciences', 'animaux', 'sauvage', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-023',
    subject: 'sciences',
    title: 'Animal : araignée',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien de pattes a une araignée ?',
    options: [
      { id: 'a', text: '6 pattes', isCorrect: false },
      { id: 'b', text: '8 pattes', isCorrect: true },
      { id: 'c', text: '10 pattes', isCorrect: false },
    ],
    correctAnswer: '8 pattes',
    explanation: 'L\'araignée a 8 pattes. Ce n\'est pas un insecte (les insectes ont 6 pattes), c\'est une arachnide.',
    hint: 'Plus que les insectes !',
    tags: ['cp', 'sciences', 'animaux', 'araignee', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-024',
    subject: 'sciences',
    title: 'Plante : la tige',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi sert la tige d\'une plante ?',
    options: [
      { id: 'a', text: 'À faire des fruits', isCorrect: false },
      { id: 'b', text: 'À tenir la plante droite et à transporter l\'eau', isCorrect: true },
      { id: 'c', text: 'À capter la lumière', isCorrect: false },
    ],
    correctAnswer: 'À tenir la plante droite et à transporter l\'eau',
    explanation: 'La tige soutient la plante et transporte l\'eau des racines jusqu\'aux feuilles.',
    hint: 'C\'est le "tronc" des petites plantes.',
    tags: ['cp', 'sciences', 'plantes', 'tige', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-025',
    subject: 'sciences',
    title: 'Bébé chien',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment s\'appelle le bébé du chien ?',
    options: [
      { id: 'a', text: 'Un veau', isCorrect: false },
      { id: 'b', text: 'Un chiot', isCorrect: true },
      { id: 'c', text: 'Un poussin', isCorrect: false },
    ],
    correctAnswer: 'Un chiot',
    explanation: 'Le bébé chien s\'appelle un chiot. Le veau est le bébé vache, le poussin est le bébé poule.',
    hint: 'C\'est un tout petit chien.',
    tags: ['cp', 'sciences', 'animaux', 'bebes', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-026',
    subject: 'sciences',
    title: 'Animal : requin',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Où vit un requin ?',
    options: [
      { id: 'a', text: 'Dans les arbres', isCorrect: false },
      { id: 'b', text: 'Dans la mer', isCorrect: true },
      { id: 'c', text: 'Dans le désert', isCorrect: false },
    ],
    correctAnswer: 'Dans la mer',
    explanation: 'Le requin est un poisson de mer. Il respire avec des branchies et se déplace avec ses nageoires.',
    hint: 'Il nage dans l\'eau salée.',
    tags: ['cp', 'sciences', 'animaux', 'poissons', 'mer', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-027',
    subject: 'sciences',
    title: 'Plante : les feuilles',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'À quoi servent les feuilles d\'une plante ?',
    options: [
      { id: 'a', text: 'À boire l\'eau du sol', isCorrect: false },
      { id: 'b', text: 'À capter la lumière du soleil pour faire de la nourriture', isCorrect: true },
      { id: 'c', text: 'À s\'accrocher à la terre', isCorrect: false },
    ],
    correctAnswer: 'À capter la lumière du soleil pour faire de la nourriture',
    explanation: 'Les feuilles sont comme des panneaux solaires. Elles captent la lumière pour que la plante fabrique sa nourriture.',
    hint: 'Elles sont vertes grâce à la chlorophylle.',
    tags: ['cp', 'sciences', 'plantes', 'feuilles', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-028',
    subject: 'sciences',
    title: 'Animal : escargot',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Qu\'est-ce que l\'escargot transporte sur son dos ?',
    options: [
      { id: 'a', text: 'Ses œufs', isCorrect: false },
      { id: 'b', text: 'Sa coquille', isCorrect: true },
      { id: 'c', text: 'Sa nourriture', isCorrect: false },
    ],
    correctAnswer: 'Sa coquille',
    explanation: 'L\'escargot vit dans sa coquille qui le protège des prédateurs et du soleil.',
    hint: 'C\'est sa maison portative.',
    tags: ['cp', 'sciences', 'animaux', 'escargot', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-029',
    subject: 'sciences',
    title: 'Plante : a-t-elle besoin d\'eau ?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que se passe-t-il si on oublie d\'arroser une plante pendant longtemps ?',
    options: [
      { id: 'a', text: 'Elle pousse plus vite', isCorrect: false },
      { id: 'b', text: 'Elle se fane et peut mourir', isCorrect: true },
      { id: 'c', text: 'Elle n\'a pas besoin d\'eau', isCorrect: false },
    ],
    correctAnswer: 'Elle se fane et peut mourir',
    explanation: 'Les plantes ont besoin d\'eau pour vivre. Sans eau, elles se flétrissent et peuvent mourir.',
    hint: 'Comme nous, les plantes ont soif !',
    tags: ['cp', 'sciences', 'plantes', 'eau', 'besoins', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-030',
    subject: 'sciences',
    title: 'Bébé poule',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment naît un poussin ?',
    options: [
      { id: 'a', text: 'Il sort du ventre de la poule', isCorrect: false },
      { id: 'b', text: 'Il sort d\'un œuf', isCorrect: true },
      { id: 'c', text: 'Il tombe des nuages', isCorrect: false },
    ],
    correctAnswer: 'Il sort d\'un œuf',
    explanation: 'La poule pond un œuf, le couve, et le poussin en sort. Les poussins sont des oiseaux.',
    hint: 'Cherche la poule dans la basse-cour.',
    tags: ['cp', 'sciences', 'animaux', 'oiseaux', 'bebes', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-031',
    subject: 'sciences',
    title: 'Animal : fourmi',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les fourmis vivent... ?',
    options: [
      { id: 'a', text: 'Seules dans des trous', isCorrect: false },
      { id: 'b', text: 'En colonies dans des fourmilières', isCorrect: true },
      { id: 'c', text: 'Dans les arbres comme les oiseaux', isCorrect: false },
    ],
    correctAnswer: 'En colonies dans des fourmilières',
    explanation: 'Les fourmis sont des insectes sociaux. Elles vivent en groupe dans des fourmilières, avec une reine, des ouvrières et des soldats.',
    hint: 'On ne voit jamais une fourmi toute seule longtemps.',
    tags: ['cp', 'sciences', 'animaux', 'insectes', 'vie-sociale', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-032',
    subject: 'sciences',
    title: 'Plante : arbres en hiver',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Que font les feuilles de certains arbres en automne ?',
    options: [
      { id: 'a', text: 'Elles poussent davantage', isCorrect: false },
      { id: 'b', text: 'Elles tombent', isCorrect: true },
      { id: 'c', text: 'Elles deviennent bleues', isCorrect: false },
    ],
    correctAnswer: 'Elles tombent',
    explanation: 'En automne, les feuilles des arbres à feuilles caduques (chêne, érable, hêtre) changent de couleur et tombent. Au printemps, de nouvelles feuilles repoussent.',
    hint: 'On ramasse des feuilles mortes en automne.',
    tags: ['cp', 'sciences', 'plantes', 'arbres', 'saisons', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'sc-cp-viv-033',
    subject: 'sciences',
    title: 'Animal : le lait',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quel animal nous donne du lait à boire ?',
    options: [
      { id: 'a', text: 'Le cheval de course', isCorrect: false },
      { id: 'b', text: 'La vache', isCorrect: true },
      { id: 'c', text: 'Le cochon', isCorrect: false },
    ],
    correctAnswer: 'La vache',
    explanation: 'La vache produit du lait. C\'est ce lait qu\'on utilise pour faire du beurre, du fromage et les yaourts.',
    hint: 'Elle vit dans les prés et dit "meuh".',
    tags: ['cp', 'sciences', 'animaux', 'mammiferes', 'alimentation', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
];
