import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCm2LogiqueExercises: MathExercise[] = [
  {
    id: 'ma-cm2-logique-001',
    subject: 'mathematiques',
    title: 'Suite géométrique ×2',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: 'Suite : 3, 6, 12, 24, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '36', isCorrect: false },
      { id: 'b', text: '48', isCorrect: true },
      { id: 'c', text: '60', isCorrect: false },
    ],
    correctAnswer: '48',
    explanation: 'On multiplie par 2 à chaque fois : 24 × 2 = 48.',
    hint: 'Observe le rapport entre chaque nombre et le suivant.',
    tags: ['cm2', 'logique', 'suite', 'géométrique', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-002',
    subject: 'mathematiques',
    title: 'Suite à pas décroissant',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: 'Suite : 100, 90, 81, 73, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '64', isCorrect: false },
      { id: 'b', text: '65', isCorrect: false },
      { id: 'c', text: '66', isCorrect: true },
    ],
    correctAnswer: '66',
    explanation: 'On soustrait 10, 9, 8, 7… Le pas diminue de 1 à chaque fois. 73 − 7 = 66.',
    hint: 'Calcule la différence entre chaque nombre : elle change à chaque étape.',
    tags: ['cm2', 'logique', 'suite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-003',
    subject: 'mathematiques',
    title: 'Suite de Fibonacci',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '1, 1, 2, 3, 5, 8, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '11', isCorrect: false },
      { id: 'b', text: '12', isCorrect: false },
      { id: 'c', text: '13', isCorrect: true },
    ],
    correctAnswer: '13',
    explanation: 'Chaque nombre est la somme des deux précédents : 5 + 8 = 13.',
    hint: 'Additionne les deux derniers nombres de la suite.',
    tags: ['cm2', 'logique', 'suite', 'fibonacci', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Regarde les deux derniers nombres : 5 et 8.', 'Calcule 5 + 8.'] },
      defi_avance: { challengeExtension: 'Trouve le terme suivant après 13.' },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-004',
    subject: 'mathematiques',
    title: 'Suite à pas croissant',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '2, 5, 10, 17, 26, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '33', isCorrect: false },
      { id: 'b', text: '35', isCorrect: false },
      { id: 'c', text: '37', isCorrect: true },
    ],
    correctAnswer: '37',
    explanation: 'Les écarts augmentent de 2 : +3, +5, +7, +9, +11. Donc 26 + 11 = 37.',
    hint: 'Calcule la différence entre chaque terme : elle augmente de 2 à chaque fois.',
    tags: ['cm2', 'logique', 'suite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 5−2, 10−5, 17−10, 26−17.', 'Observe comment les écarts évoluent.', 'Calcule le prochain écart.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-005',
    subject: 'mathematiques',
    title: 'Déduction : deux conditions',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'déduction',
    format: 'qcm',
    instructions: 'Résous l\'énigme.',
    prompt: 'Je suis un nombre entre 20 et 30. Je suis multiple de 7. Qui suis-je ?',
    options: [
      { id: 'a', text: '21', isCorrect: false },
      { id: 'b', text: '28', isCorrect: true },
      { id: 'c', text: '35', isCorrect: false },
    ],
    correctAnswer: '28',
    explanation: 'Les multiples de 7 entre 20 et 30 : 7 × 4 = 28. C\'est 28.',
    hint: 'Liste les multiples de 7 : 7, 14, 21, 28, 35…',
    tags: ['cm2', 'logique', 'déduction', 'multiples', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-006',
    subject: 'mathematiques',
    title: 'Tableau croisé',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'tableau de données',
    format: 'qcm',
    instructions: 'Lis le tableau et réponds.',
    prompt: 'Lundi : 12 garçons, 15 filles. Mardi : 10 garçons, 13 filles. Combien d\'élèves au total sur 2 jours ?',
    options: [
      { id: 'a', text: '48', isCorrect: false },
      { id: 'b', text: '50', isCorrect: true },
      { id: 'c', text: '52', isCorrect: false },
    ],
    correctAnswer: '50',
    explanation: '(12 + 15) + (10 + 13) = 27 + 23 = 50 élèves.',
    hint: 'Additionne tous les effectifs.',
    tags: ['cm2', 'logique', 'tableau', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule le total du lundi.', 'Calcule le total du mardi.', 'Additionne les deux jours.'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-007',
    subject: 'mathematiques',
    title: 'Suite de puissances de 2',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le terme suivant.',
    prompt: '1, 2, 4, 8, 16, 32, ___',
    options: [
      { id: 'a', text: '48', isCorrect: false },
      { id: 'b', text: '64', isCorrect: true },
      { id: 'c', text: '72', isCorrect: false },
    ],
    correctAnswer: '64',
    explanation: 'On multiplie par 2 : 32 × 2 = 64.',
    hint: 'Quel est le rapport entre deux termes consécutifs ?',
    tags: ['cm2', 'logique', 'suite', 'puissances', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-008',
    subject: 'mathematiques',
    title: 'Graphique en barres',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de graphique',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un graphique montre les ventes de glaces : Vanille = 35, Chocolat = 48, Fraise = 27. Quelle parfum se vend le mieux ?',
    options: [
      { id: 'a', text: 'Vanille', isCorrect: false },
      { id: 'b', text: 'Chocolat', isCorrect: true },
      { id: 'c', text: 'Fraise', isCorrect: false },
    ],
    correctAnswer: 'Chocolat',
    explanation: '48 > 35 > 27. Le chocolat est le parfum le plus vendu.',
    hint: 'Compare les trois nombres.',
    tags: ['cm2', 'logique', 'graphique', 'données', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-009',
    subject: 'mathematiques',
    title: 'Raisonnement par l\'absurde',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'raisonnement',
    format: 'qcm',
    instructions: 'Résous l\'énigme.',
    prompt: 'Si tous les chats miaulants sont des chats domestiques, et Félix est un chat domestique, peut-on affirmer que Félix miaule ?',
    options: [
      { id: 'a', text: 'Oui, certainement', isCorrect: false },
      { id: 'b', text: 'Non, pas forcément', isCorrect: true },
      { id: 'c', text: 'Cela dépend du chat', isCorrect: false },
    ],
    correctAnswer: 'Non, pas forcément',
    explanation: 'Que tous les chats miaulants soient domestiques ne signifie pas que tous les chats domestiques miaulentts.',
    hint: 'La logique va dans un seul sens.',
    tags: ['cm2', 'logique', 'raisonnement', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-010',
    subject: 'mathematiques',
    title: 'Suite alternée croissante/décroissante',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le terme suivant.',
    prompt: '2, 8, 5, 11, 8, 14, ___ . Quel est le terme suivant ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '11', isCorrect: true },
      { id: 'c', text: '17', isCorrect: false },
    ],
    correctAnswer: '11',
    explanation: 'La suite alterne +6 et −3 : 2+6=8, 8−3=5, 5+6=11, 11−3=8, 8+6=14, 14−3=11.',
    hint: 'Cherche deux règles qui alternent.',
    tags: ['cm2', 'logique', 'suite', 'alternée', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-011',
    subject: 'mathematiques',
    title: 'Diagramme circulaire',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'données',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans un diagramme de 120 élèves : 1/4 aime les maths, 1/3 aime le sport, le reste aime la lecture. Combien aiment la lecture ?',
    options: [
      { id: 'a', text: '40', isCorrect: false },
      { id: 'b', text: '50', isCorrect: true },
      { id: 'c', text: '60', isCorrect: false },
    ],
    correctAnswer: '50',
    explanation: '1/4 = 30 pour maths. 1/3 = 40 pour sport. Lecture = 120 − 30 − 40 = 50.',
    hint: 'Calcule d\'abord les parts de maths et sport.',
    tags: ['cm2', 'logique', 'données', 'fractions', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-012',
    subject: 'mathematiques',
    title: 'Déduction triple condition',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'déduction',
    format: 'qcm',
    instructions: 'Résous l\'énigme.',
    prompt: 'Je suis un nombre entre 50 et 80. Je suis divisible par 6 et par 9. Qui suis-je ?',
    options: [
      { id: 'a', text: '54', isCorrect: true },
      { id: 'b', text: '60', isCorrect: false },
      { id: 'c', text: '72', isCorrect: false },
    ],
    correctAnswer: '54',
    explanation: '54 est entre 50 et 80, divisible par 6 (54÷6=9) et par 9 (54÷9=6). 72 est aussi valide... en fait 72 convient aussi. Mais 54 est le premier.',
    hint: 'Multiples communs de 6 et 9 = multiples de 18.',
    tags: ['cm2', 'logique', 'déduction', 'multiples', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-013',
    subject: 'mathematiques',
    title: 'Suite de carrés',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le terme suivant.',
    prompt: '1, 4, 9, 16, 25, ___ . Quel est le terme suivant ?',
    options: [
      { id: 'a', text: '34', isCorrect: false },
      { id: 'b', text: '36', isCorrect: true },
      { id: 'c', text: '49', isCorrect: false },
    ],
    correctAnswer: '36',
    explanation: 'Ce sont les carrés successifs : 1²=1, 2²=4, 3²=9, 4²=16, 5²=25, 6²=36.',
    hint: 'Chaque terme est le carré d\'un entier.',
    tags: ['cm2', 'logique', 'suite', 'carrés', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-014',
    subject: 'mathematiques',
    title: 'Tableau de proportionnalité',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'proportionnalité',
    format: 'qcm',
    instructions: 'Complète le tableau.',
    prompt: 'Si 4 cahiers coûtent 12 €, combien coûtent 7 cahiers ?',
    options: [
      { id: 'a', text: '18 €', isCorrect: false },
      { id: 'b', text: '21 €', isCorrect: true },
      { id: 'c', text: '28 €', isCorrect: false },
    ],
    correctAnswer: '21 €',
    explanation: 'Prix unitaire = 12 ÷ 4 = 3 €. 7 × 3 = 21 €.',
    hint: 'Calcule d\'abord le prix d\'un cahier.',
    tags: ['cm2', 'logique', 'proportionnalité', 'tableau', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm2-logique-015',
    subject: 'mathematiques',
    title: 'Probabilité simple',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'probabilités',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'Un sac contient 3 billes rouges et 7 billes bleues. Quelle est la probabilité de tirer une rouge ?',
    options: [
      { id: 'a', text: '1/5', isCorrect: false },
      { id: 'b', text: '3/10', isCorrect: true },
      { id: 'c', text: '7/10', isCorrect: false },
    ],
    correctAnswer: '3/10',
    explanation: '3 rouges sur 10 billes au total = 3/10.',
    hint: 'Probabilité = cas favorables ÷ cas totaux.',
    tags: ['cm2', 'logique', 'probabilités', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
];
