import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCm2ProblemesExercises: MathExercise[] = [
  {
    id: 'ma-cm2-problemes-001',
    subject: 'mathematiques',
    title: 'Prix unitaire',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'division',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Si 3 cahiers coûtent 4,50 €, combien coûte 1 cahier ?',
    options: [
      { id: 'a', text: '1,20 €', isCorrect: false },
      { id: 'b', text: '1,50 €', isCorrect: true },
      { id: 'c', text: '1,80 €', isCorrect: false },
    ],
    correctAnswer: '1,50 €',
    explanation: '4,50 ÷ 3 = 1,50 €.',
    hint: 'Divise le prix total par le nombre de cahiers.',
    tags: ['cm2', 'problemes', 'division', 'décimaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-002',
    subject: 'mathematiques',
    title: 'Aire de la piscine',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'aire',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Une piscine fait 25 m de long et 12 m de large. Quelle est son aire ?',
    options: [
      { id: 'a', text: '280 m²', isCorrect: false },
      { id: 'b', text: '300 m²', isCorrect: true },
      { id: 'c', text: '320 m²', isCorrect: false },
    ],
    correctAnswer: '300 m²',
    explanation: 'Aire = 25 × 12 = 300 m².',
    hint: 'Aire du rectangle = longueur × largeur.',
    tags: ['cm2', 'problemes', 'aire', 'multiplication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-003',
    subject: 'mathematiques',
    title: "Fraction d'un groupe",
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'fractions en contexte',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: "Dans une classe de 32 élèves, 3/8 sont absents. Combien d'élèves sont présents ?",
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '20', isCorrect: true },
      { id: 'c', text: '24', isCorrect: false },
    ],
    correctAnswer: '20',
    explanation: "1/8 de 32 = 32 ÷ 8 = 4. Donc 3/8 = 3 × 4 = 12 absents. Présents : 32 − 12 = 20.",
    hint: "Calcule d'abord 1/8 de 32, puis multiplie par 3, puis soustrait du total.",
    tags: ['cm2', 'problemes', 'fractions', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 1/8 de 32 : 32 ÷ 8.', 'Multiplie par 3 pour avoir 3/8.', 'Soustrait du total : 32 − 12.'] },
      defi_avance: { challengeExtension: 'Si 5/8 avaient une note supérieure à 15/20, combien cela représente-t-il ?' },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-004',
    subject: 'mathematiques',
    title: 'Distance parcourue',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'vitesse et distance',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un bus roule à 60 km/h. En 1 h 30 min, quelle distance parcourt-il ?',
    options: [
      { id: 'a', text: '80 km', isCorrect: false },
      { id: 'b', text: '90 km', isCorrect: true },
      { id: 'c', text: '100 km', isCorrect: false },
    ],
    correctAnswer: '90 km',
    explanation: '1 h 30 min = 1,5 h. Distance = 60 × 1,5 = 90 km.',
    hint: '1 h 30 min = 1,5 heure. Multiplie par 60.',
    tags: ['cm2', 'problemes', 'vitesse', 'distance', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Convertis 1 h 30 min en heures (= 1,5 h).', 'Multiplie par la vitesse : 60 × 1,5.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-005',
    subject: 'mathematiques',
    title: 'Réduction en pourcentage',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'pourcentages',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un article coûte 60 €. Il est soldé à 25 %. Quel est le nouveau prix ?',
    options: [
      { id: 'a', text: '40 €', isCorrect: false },
      { id: 'b', text: '45 €', isCorrect: true },
      { id: 'c', text: '50 €', isCorrect: false },
    ],
    correctAnswer: '45 €',
    explanation: '25 % de 60 = 60 ÷ 4 = 15 €. Prix réduit = 60 − 15 = 45 €.',
    hint: '25 % = 1/4. Calcule le quart de 60, puis soustrais.',
    tags: ['cm2', 'problemes', 'pourcentage', 'monnaie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['25 % = 1/4. Calcule 60 ÷ 4.', 'Soustrais du prix initial.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-006',
    subject: 'mathematiques',
    title: 'Partage de fraction complexe',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un gâteau est partagé entre 5 amis. Chacun reçoit 2/5. Mais 3 parts sont mangées. Quelle fraction reste-t-il ?',
    options: [
      { id: 'a', text: '1/5', isCorrect: false },
      { id: 'b', text: '2/5', isCorrect: true },
      { id: 'c', text: '3/5', isCorrect: false },
    ],
    correctAnswer: '2/5',
    explanation: 'Il y a 5 × (1/5) = 1 gâteau entier. 3/5 mangés. Reste = 1 − 3/5 = 2/5.',
    hint: '5 amis reçoivent chacun 1/5. 3 parts = 3/5. Reste = 1 − 3/5.',
    tags: ['cm2', 'problemes', 'fractions', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['3 parts mangées = 3/5.', 'Reste = 5/5 − 3/5 = ?'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-007',
    subject: 'mathematiques',
    title: 'Problème multi-étapes avec décimaux',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'multi-étapes',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Une salle de cinéma compte 120 places à 7,50 €. 80 places sont vendues. Quelle est la recette ?',
    options: [
      { id: 'a', text: '540 €', isCorrect: false },
      { id: 'b', text: '600 €', isCorrect: true },
      { id: 'c', text: '660 €', isCorrect: false },
    ],
    correctAnswer: '600 €',
    explanation: '80 × 7,50 = 600 €.',
    hint: 'Multiplie le nombre de places vendues par le prix.',
    tags: ['cm2', 'problemes', 'décimaux', 'monnaie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-008',
    subject: 'mathematiques',
    title: 'Problème d\'aire et de coût',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'aire en contexte',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un jardin rectangulaire fait 15 m × 8 m. Le gazon coûte 6 € le m². Quel est le coût total ?',
    options: [
      { id: 'a', text: '680 €', isCorrect: false },
      { id: 'b', text: '720 €', isCorrect: true },
      { id: 'c', text: '760 €', isCorrect: false },
    ],
    correctAnswer: '720 €',
    explanation: 'Aire = 15 × 8 = 120 m². Coût = 120 × 6 = 720 €.',
    hint: 'Calcule d\'abord l\'aire du jardin.',
    tags: ['cm2', 'problemes', 'aire', 'monnaie', 'multi-etapes', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 15 × 8.', 'Multiplie par 6.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-009',
    subject: 'mathematiques',
    title: 'Proportion simple',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'proportionnalité',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: '3 cahiers coûtent 7,50 €. Combien coûtent 5 cahiers au même prix ?',
    options: [
      { id: 'a', text: '11 €', isCorrect: false },
      { id: 'b', text: '12,50 €', isCorrect: true },
      { id: 'c', text: '13 €', isCorrect: false },
    ],
    correctAnswer: '12,50 €',
    explanation: 'Prix unitaire = 7,50 ÷ 3 = 2,50 €. 5 × 2,50 = 12,50 €.',
    hint: 'Calcule d\'abord le prix d\'un cahier.',
    tags: ['cm2', 'problemes', 'proportionnalité', 'décimaux', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 7,50 ÷ 3 pour trouver le prix d\'un cahier.', 'Multiplie par 5.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-010',
    subject: 'mathematiques',
    title: 'Remise en pourcentage',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'pourcentages',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un vélo coûte 200 €. Le magasin fait une remise de 15 %. Quel est le nouveau prix ?',
    options: [
      { id: 'a', text: '160 €', isCorrect: false },
      { id: 'b', text: '170 €', isCorrect: true },
      { id: 'c', text: '185 €', isCorrect: false },
    ],
    correctAnswer: '170 €',
    explanation: '15 % de 200 = 30 €. Prix final = 200 − 30 = 170 €.',
    hint: 'Calcule d\'abord la remise (15 % de 200), puis soustrais.',
    tags: ['cm2', 'problemes', 'pourcentages', 'monnaie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-011',
    subject: 'mathematiques',
    title: 'Partage proportionnel',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'proportionnalité',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Eva et Lucas partagent 60 € dans le rapport 2:3. Quelle part reçoit Lucas ?',
    options: [
      { id: 'a', text: '24 €', isCorrect: false },
      { id: 'b', text: '36 €', isCorrect: true },
      { id: 'c', text: '40 €', isCorrect: false },
    ],
    correctAnswer: '36 €',
    explanation: 'Total parts = 2+3 = 5. Valeur d\'une part = 60÷5 = 12 €. Lucas : 3 × 12 = 36 €.',
    hint: 'Ajoute les parts (2+3), trouve la valeur d\'une part, puis multiplie.',
    tags: ['cm2', 'problemes', 'partage', 'proportionnalité', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-012',
    subject: 'mathematiques',
    title: 'Problème multi-étapes avec fractions',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Tom a 48 billes. Il donne 1/4 à Léa puis 1/3 de ce qui reste à Marc. Combien lui reste-t-il ?',
    options: [
      { id: 'a', text: '20', isCorrect: false },
      { id: 'b', text: '24', isCorrect: true },
      { id: 'c', text: '28', isCorrect: false },
    ],
    correctAnswer: '24',
    explanation: 'Tom donne 48÷4=12 à Léa → reste 36. Il donne 36÷3=12 à Marc → reste 24.',
    hint: 'Résous par étapes : d\'abord le don à Léa, puis le don à Marc.',
    tags: ['cm2', 'problemes', 'fractions', 'multi-etapes', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Tom donne 1/4 de 48 = ? à Léa.', 'Combien reste-t-il ?', 'Il donne 1/3 de ce qui reste à Marc.', 'Combien reste-t-il finalement ?'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-013',
    subject: 'mathematiques',
    title: 'Problème de vitesse',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'vitesse',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Deux villes sont à 280 km. Une voiture part à 9h00 à 70 km/h. À quelle heure arrive-t-elle ?',
    options: [
      { id: 'a', text: '12h00', isCorrect: false },
      { id: 'b', text: '13h00', isCorrect: true },
      { id: 'c', text: '14h00', isCorrect: false },
    ],
    correctAnswer: '13h00',
    explanation: 'Durée = 280 ÷ 70 = 4 heures. 9h + 4h = 13h00.',
    hint: 'Calcule d\'abord la durée (distance ÷ vitesse).',
    tags: ['cm2', 'problemes', 'vitesse', 'durée', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-014',
    subject: 'mathematiques',
    title: 'Problème d\'intérêt simple',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'pourcentages',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Sarah place 500 € à 4 % par an. Combien gagne-t-elle en 1 an ?',
    options: [
      { id: 'a', text: '16 €', isCorrect: false },
      { id: 'b', text: '20 €', isCorrect: true },
      { id: 'c', text: '25 €', isCorrect: false },
    ],
    correctAnswer: '20 €',
    explanation: '4 % de 500 = 500 × 4 ÷ 100 = 20 €.',
    hint: '4 % = 4 ÷ 100 = 0,04. Multiplie 500 × 0,04.',
    tags: ['cm2', 'problemes', 'pourcentages', 'monnaie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm2-problemes-015',
    subject: 'mathematiques',
    title: 'Organisation et dénombrement',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'combinatoire',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Au menu : 3 entrées et 4 plats. Combien de combinaisons entrée + plat peut-on faire ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '12', isCorrect: true },
      { id: 'c', text: '16', isCorrect: false },
    ],
    correctAnswer: '12',
    explanation: '3 entrées × 4 plats = 12 combinaisons possibles.',
    hint: 'Multiplie le nombre d\'entrées par le nombre de plats.',
    tags: ['cm2', 'problemes', 'combinatoire', 'dénombrement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
];
