import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe2VivantExercises: DecouverteExercise[] = [

  {
    id: 'ddm-ce2-vivant-001',
    subject: 'decouverte_du_monde',
    title: 'Le règne des champignons',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les champignons n'appartiennent ni au règne animal ni au règne végétal. À quel règne appartiennent-ils ?",
    options: [
      { id: 'a', text: 'Règne minéral', isCorrect: false },
      { id: 'b', text: 'Règne des Fungi (champignons)', isCorrect: true },
      { id: 'c', text: 'Règne protiste', isCorrect: false },
      { id: 'd', text: 'Règne bactérien', isCorrect: false },
    ],
    correctAnswer: 'Règne des Fungi (champignons)',
    explanation: "Les champignons forment leur propre règne : les Fungi. Ils ne sont pas des plantes (pas de chlorophylle) ni des animaux.",
    hint: 'Les champignons ont leur propre catégorie.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-002',
    subject: 'decouverte_du_monde',
    title: 'Photosynthèse : bilan',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Lors de la photosynthèse, les plantes absorbent du CO₂ et de l'eau, et rejettent…",
    options: [
      { id: 'a', text: 'du CO₂', isCorrect: false },
      { id: 'b', text: "de l'oxygène (O₂)", isCorrect: true },
      { id: 'c', text: "de l'azote", isCorrect: false },
      { id: 'd', text: "de la vapeur d'eau uniquement", isCorrect: false },
    ],
    correctAnswer: "de l'oxygène (O₂)",
    explanation: "La photosynthèse produit du sucre (nourriture) et libère de l'oxygène. C'est pourquoi les plantes sont essentielles à la vie sur Terre.",
    hint: 'Les plantes nous donnent l\'air que nous respirons.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-003',
    subject: 'decouverte_du_monde',
    title: 'Les végétaux sans fleurs',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les fougères et les mousses sont des plantes sans fleurs. Comment se reproduisent-elles ?",
    options: [
      { id: 'a', text: 'Par des graines dans des fruits', isCorrect: false },
      { id: 'b', text: 'Par des spores', isCorrect: true },
      { id: 'c', text: 'Par des oeufs', isCorrect: false },
      { id: 'd', text: 'Par des bulbes uniquement', isCorrect: false },
    ],
    correctAnswer: 'Par des spores',
    explanation: "Les fougères et mousses se reproduisent par des spores (minuscules cellules reproductrices). Elles n'ont pas de fleurs ni de graines.",
    hint: "Les fougères libèrent des spores en poudre depuis leurs feuilles.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-004',
    subject: 'decouverte_du_monde',
    title: 'Les écosystèmes',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un écosystème, c'est…",
    options: [
      { id: 'a', text: 'un animal particulier', isCorrect: false },
      { id: 'b', text: "l'ensemble des êtres vivants et leur milieu qui interagissent", isCorrect: true },
      { id: 'c', text: 'un lac sans animaux', isCorrect: false },
      { id: 'd', text: 'une seule espèce animale dans son habitat', isCorrect: false },
    ],
    correctAnswer: "l'ensemble des êtres vivants et leur milieu qui interagissent",
    explanation: "Un écosystème est un ensemble de plantes, d'animaux et de microorganismes qui vivent dans un même milieu et interagissent entre eux.",
    hint: "C'est tout le réseau du vivant dans un milieu.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-005',
    subject: 'decouverte_du_monde',
    title: 'La forêt comme écosystème',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Si les loups disparaissent d'une forêt, la population de cerfs va probablement…",
    options: [
      { id: 'a', text: 'diminuer aussi', isCorrect: false },
      { id: 'b', text: 'augmenter rapidement (plus de prédateurs)', isCorrect: true },
      { id: 'c', text: 'rester stable', isCorrect: false },
      { id: 'd', text: 'disparaître avec le loup', isCorrect: false },
    ],
    correctAnswer: 'augmenter rapidement (plus de prédateurs)',
    explanation: "Sans prédateur, la proie se multiplie sans contrôle. Si les cerfs deviennent trop nombreux, ils dévorent toute la végétation et fragilisent l'écosystème.",
    hint: 'Sans prédateur, la proie prolifère.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-006',
    subject: 'decouverte_du_monde',
    title: 'Le requin cartilagineux',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le requin est un poisson cartilagineux. Quelle est sa particularité par rapport à d'autres poissons ?",
    options: [
      { id: 'a', text: 'Il a des os comme les mammifères.', isCorrect: false },
      { id: 'b', text: "Son squelette est fait de cartilage (pas d'os).", isCorrect: true },
      { id: 'c', text: "Il vole hors de l'eau.", isCorrect: false },
      { id: 'd', text: "Il pond des oeufs toujours.", isCorrect: false },
    ],
    correctAnswer: "Son squelette est fait de cartilage (pas d'os).",
    explanation: "Le requin (et les raies) ont un squelette de cartilage souple, pas d'os rigides. On les appelle des sélaciens ou chondrichtyens.",
    hint: 'Le cartilage est plus souple que l\'os.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-007',
    subject: 'decouverte_du_monde',
    title: "La transpiration des plantes",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Les plantes participent au cycle de l'eau. Par quoi rejettent-elles de la vapeur d'eau dans l'atmosphère ?",
    options: [
      { id: 'a', text: 'par leurs racines', isCorrect: false },
      { id: 'b', text: 'par leurs feuilles (transpiration)', isCorrect: true },
      { id: 'c', text: 'par leurs fruits', isCorrect: false },
      { id: 'd', text: 'par leurs graines', isCorrect: false },
    ],
    correctAnswer: 'par leurs feuilles (transpiration)',
    explanation: "Les plantes absorbent l'eau par leurs racines et la rejettent sous forme de vapeur par leurs feuilles. Ce phénomène s'appelle la transpiration.",
    hint: "L'eau monte de la racine aux feuilles.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-008',
    subject: 'decouverte_du_monde',
    title: 'La chaîne alimentaire marine',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'alimentation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans la mer : phytoplancton → zooplancton → hareng → thon. Le hareng est à la fois…',
    options: [
      { id: 'a', text: 'producteur et décomposeur', isCorrect: false },
      { id: 'b', text: 'proie du thon et prédateur du zooplancton', isCorrect: true },
      { id: 'c', text: 'uniquement prédateur', isCorrect: false },
      { id: 'd', text: 'décomposeur final', isCorrect: false },
    ],
    correctAnswer: 'proie du thon et prédateur du zooplancton',
    explanation: "Dans une chaîne alimentaire, chaque organisme peut être à la fois proie et prédateur. Le hareng mange le zooplancton et est mangé par le thon.",
    hint: 'Le hareng est au milieu de la chaîne.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-009',
    subject: 'decouverte_du_monde',
    title: 'Le rôle des arbres',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "En plus de produire de l'oxygène, les arbres rendent quels autres services à l'environnement ?",
    options: [
      { id: 'a', text: "Ils chauffent l'atmosphère.", isCorrect: false },
      { id: 'b', text: "Ils fixent le CO₂, maintiennent les sols et abritent la faune.", isCorrect: true },
      { id: 'c', text: "Ils produisent de la pluie uniquement.", isCorrect: false },
      { id: 'd', text: "Ils absorbent la lumière pour que les autres plantes meurent.", isCorrect: false },
    ],
    correctAnswer: "Ils fixent le CO₂, maintiennent les sols et abritent la faune.",
    explanation: "Les arbres absorbent le CO₂ (gaz à effet de serre), stabilisent les sols avec leurs racines et offrent un habitat à des centaines d'espèces.",
    hint: 'Les forêts sont souvent appelées « poumons de la Terre ».',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-010',
    subject: 'decouverte_du_monde',
    title: 'Adaptation au milieu',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le chameau peut survivre longtemps sans eau dans le désert. Cela montre que…",
    options: [
      { id: 'a', text: "Il n'a pas besoin d'eau pour vivre.", isCorrect: false },
      { id: 'b', text: "Il est adapté à son milieu (désert aride).", isCorrect: true },
      { id: 'c', text: "L'eau n'est pas nécessaire dans le désert.", isCorrect: false },
      { id: 'd', text: "Il boit beaucoup la nuit sans qu'on le voie.", isCorrect: false },
    ],
    correctAnswer: "Il est adapté à son milieu (désert aride).",
    explanation: "Le chameau stocke de la graisse dans ses bosses et perd très peu d'eau. Ces adaptations lui permettent de vivre dans les déserts chauds et secs.",
    hint: "Ses bosses contiennent des réserves d'énergie (pas d'eau).",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-011',
    subject: 'decouverte_du_monde',
    title: 'Symbiose',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le lichen est une association entre un champignon et une algue. Les deux bénéficient l'un de l'autre. Cette relation s'appelle…",
    options: [
      { id: 'a', text: 'parasitisme', isCorrect: false },
      { id: 'b', text: 'symbiose', isCorrect: true },
      { id: 'c', text: 'prédation', isCorrect: false },
      { id: 'd', text: 'compétition', isCorrect: false },
    ],
    correctAnswer: 'symbiose',
    explanation: "La symbiose est une relation bénéfique pour les deux espèces. Dans le lichen, l'algue produit la nourriture et le champignon lui fournit eau et protection.",
    hint: 'Symbiose = les deux y gagnent.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-012',
    subject: 'decouverte_du_monde',
    title: 'Le parasite',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "La tique se nourrit du sang des animaux sans les tuer immédiatement. C'est un exemple de…",
    options: [
      { id: 'a', text: 'symbiose', isCorrect: false },
      { id: 'b', text: 'parasitisme', isCorrect: true },
      { id: 'c', text: 'prédation', isCorrect: false },
      { id: 'd', text: 'compétition', isCorrect: false },
    ],
    correctAnswer: 'parasitisme',
    explanation: "Le parasitisme est une relation où un organisme (le parasite) profite d'un autre (l'hôte) en lui causant du tort sans le tuer directement.",
    hint: 'La tique vit aux dépens de son hôte.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-013',
    subject: 'decouverte_du_monde',
    title: 'Les producteurs',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'alimentation',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans un écosystème, les plantes sont appelées « producteurs » parce qu\'elles…',
    options: [
      { id: 'a', text: 'produisent des animaux', isCorrect: false },
      { id: 'b', text: 'fabriquent leur propre nourriture grâce à la photosynthèse', isCorrect: true },
      { id: 'c', text: "produisent de l'eau", isCorrect: false },
      { id: 'd', text: 'produisent de la chaleur', isCorrect: false },
    ],
    correctAnswer: 'fabriquent leur propre nourriture grâce à la photosynthèse',
    explanation: "Les plantes sont à la base de la plupart des chaînes alimentaires : elles produisent leur énergie elles-mêmes et la transmettent aux herbivores.",
    hint: 'Ils sont à la base de toutes les chaînes alimentaires.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-014',
    subject: 'decouverte_du_monde',
    title: 'Le virus : vivant ou non ?',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un virus est-il un être vivant ?",
    options: [
      { id: 'a', text: 'Oui, comme les bactéries.', isCorrect: false },
      { id: 'b', text: "Non, il ne peut pas se reproduire seul — il a besoin d'une cellule hôte.", isCorrect: true },
      { id: 'c', text: 'Oui, il a des cellules comme les animaux.', isCorrect: false },
      { id: 'd', text: 'Oui, il mange et respire.', isCorrect: false },
    ],
    correctAnswer: "Non, il ne peut pas se reproduire seul — il a besoin d'une cellule hôte.",
    explanation: "Les scientifiques ne classifient généralement pas les virus comme des êtres vivants car ils ne peuvent pas se reproduire ni fonctionner seuls.",
    hint: 'Les virus ont besoin de nous pour se multiplier.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-015',
    subject: 'decouverte_du_monde',
    title: "L'adaptation au froid",
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Le manchot empereur vit au pôle Sud à -50°C. Comment résiste-t-il au froid extrême ?",
    options: [
      { id: 'a', text: 'Il hiberne pendant 6 mois.', isCorrect: false },
      { id: 'b', text: "Grâce à une épaisse couche de graisse sous ses plumes imperméables.", isCorrect: true },
      { id: 'c', text: 'Il se réchauffe dans des sources chaudes.', isCorrect: false },
      { id: 'd', text: "Il change de couleur pour absorber la chaleur.", isCorrect: false },
    ],
    correctAnswer: "Grâce à une épaisse couche de graisse sous ses plumes imperméables.",
    explanation: "Le manchot a une couche de graisse épaisse et des plumes serrées imperméables qui le protègent du froid polaire. Les manchots se serrent aussi en groupe.",
    hint: 'La graisse et les plumes imperméables sont ses isolants naturels.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-016',
    subject: 'decouverte_du_monde',
    title: 'La reproduction végétative',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'reproduction',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Certaines plantes (fraisiers, pommes de terre) se reproduisent sans graines. On parle de reproduction…",
    options: [
      { id: 'a', text: 'sexuée par fécondation', isCorrect: false },
      { id: 'b', text: 'végétative (asexuée)', isCorrect: true },
      { id: 'c', text: 'pollinisée par les insectes uniquement', isCorrect: false },
      { id: 'd', text: 'par spores uniquement', isCorrect: false },
    ],
    correctAnswer: 'végétative (asexuée)',
    explanation: "La reproduction végétative produit de nouveaux individus identiques à la plante mère : stolons (fraisiers), tubercules (pommes de terre), boutures…",
    hint: 'Pas de fleur, pas de graine — juste une partie de la plante.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-017',
    subject: 'decouverte_du_monde',
    title: "L'arbre et ses saisons",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vivant',
    subskill: 'plantes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Pourquoi les arbres à feuilles caduques perdent-ils leurs feuilles en automne ?",
    options: [
      { id: 'a', text: 'Parce qu\'ils meurent en automne.', isCorrect: false },
      { id: 'b', text: "Pour économiser l'eau et l'énergie pendant l'hiver froid.", isCorrect: true },
      { id: 'c', text: 'Pour que les insectes puissent les manger.', isCorrect: false },
      { id: 'd', text: 'Parce que le sol devient trop humide.', isCorrect: false },
    ],
    correctAnswer: "Pour économiser l'eau et l'énergie pendant l'hiver froid.",
    explanation: "En perdant ses feuilles, l'arbre réduit ses pertes en eau et en énergie pendant l'hiver. Au printemps, il refait des feuilles pour reprendre la photosynthèse.",
    hint: "L'hiver est une période de repos pour l'arbre.",
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-018',
    subject: 'decouverte_du_monde',
    title: 'Le sol vivant',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Un gramme de terre de jardin contient environ un milliard de bactéries. Cela montre que le sol est…",
    options: [
      { id: 'a', text: 'un milieu mort et inerte', isCorrect: false },
      { id: 'b', text: 'un écosystème vivant essentiel à la vie', isCorrect: true },
      { id: 'c', text: 'dangereux pour toutes les plantes', isCorrect: false },
      { id: 'd', text: 'uniquement composé de minéraux', isCorrect: false },
    ],
    correctAnswer: 'un écosystème vivant essentiel à la vie',
    explanation: "Le sol est un écosystème complexe peuplé de milliards d'êtres vivants (bactéries, vers, champignons) qui le rendent fertile et accueillant pour les plantes.",
    hint: 'La terre est pleine de vie invisible.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-019',
    subject: 'decouverte_du_monde',
    title: 'Pollinisateurs et agriculture',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Sans abeilles ni autres pollinisateurs, de nombreuses plantes cultivées ne produiraient plus de fruits. Pourquoi ?",
    options: [
      { id: 'a', text: 'Parce que les abeilles arrosent les plantes.', isCorrect: false },
      { id: 'b', text: 'Parce que la pollinisation est nécessaire pour que les fleurs deviennent des fruits.', isCorrect: true },
      { id: 'c', text: 'Parce que les abeilles protègent les plantes des maladies.', isCorrect: false },
      { id: 'd', text: 'Parce que les abeilles fabriquent la sève des plantes.', isCorrect: false },
    ],
    correctAnswer: 'Parce que la pollinisation est nécessaire pour que les fleurs deviennent des fruits.',
    explanation: "Les abeilles transportent le pollen d'une fleur à l'autre, permettant la fécondation. Sans pollinisation, pas de fruits (pommes, fraises, cerises…).",
    hint: 'Fleur pollinisée → fruit avec graines.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-vivant-020',
    subject: 'decouverte_du_monde',
    title: 'Espèces invasives',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vivant',
    subskill: 'ecosystemes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Une espèce invasive est une espèce introduite dans un nouveau milieu qui…",
    options: [
      { id: 'a', text: 'protège les espèces locales', isCorrect: false },
      { id: 'b', text: "perturbe l'équilibre de l'écosystème local", isCorrect: true },
      { id: 'c', text: 'améliore la biodiversité locale', isCorrect: false },
      { id: 'd', text: 'disparaît rapidement', isCorrect: false },
    ],
    correctAnswer: "perturbe l'équilibre de l'écosystème local",
    explanation: "Les espèces invasives (comme le frelon asiatique en France) n'ont pas de prédateurs naturels dans leur nouveau milieu et peuvent éliminer des espèces locales.",
    hint: "Sans prédateurs naturels, elles prolifèrent et nuisent aux espèces locales.",
    estimatedMinutes: 1,
    adaptations: A,
  },
];
