import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe2EspaceFranceExercises: DecouverteExercise[] = [

  // CE2 · espace · géographie de la France
  {
    id: 'ddm-ce2-esp-013',
    subject: 'decouverte_du_monde',
    title: 'La Seine',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Seine est le fleuve qui traverse Paris. Elle se jette dans…',
    options: [
      { id: 'a', text: 'la Méditerranée', isCorrect: false },
      { id: 'b', text: 'la Manche (mer)', isCorrect: true },
      { id: 'c', text: 'l\'Atlantique directement', isCorrect: false },
      { id: 'd', text: 'le Rhin', isCorrect: false },
    ],
    correctAnswer: 'la Manche (mer)',
    explanation: 'La Seine prend sa source en Bourgogne et se jette dans la Manche au Havre (Normandie).',
    hint: 'La Seine finit sa course en Normandie, dans la Manche.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-014',
    subject: 'decouverte_du_monde',
    title: 'La Loire',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Loire est le plus long fleuve de France. Elle se jette dans…',
    options: [
      { id: 'a', text: 'la Méditerranée', isCorrect: false },
      { id: 'b', text: 'l\'océan Atlantique', isCorrect: true },
      { id: 'c', text: 'la Manche', isCorrect: false },
      { id: 'd', text: 'la mer du Nord', isCorrect: false },
    ],
    correctAnswer: 'l\'océan Atlantique',
    explanation: 'La Loire (1 013 km) prend sa source dans le Massif central et se jette dans l\'Atlantique à Saint-Nazaire.',
    hint: 'La Loire finit sa course à Saint-Nazaire.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-015',
    subject: 'decouverte_du_monde',
    title: 'Le Rhône',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le Rhône prend sa source en Suisse et se jette dans…',
    options: [
      { id: 'a', text: 'l\'Atlantique', isCorrect: false },
      { id: 'b', text: 'la Méditerranée', isCorrect: true },
      { id: 'c', text: 'la Manche', isCorrect: false },
      { id: 'd', text: 'la mer du Nord', isCorrect: false },
    ],
    correctAnswer: 'la Méditerranée',
    explanation: 'Le Rhône traverse la Suisse, entre en France par Genève et se jette dans la Méditerranée en Camargue (près d\'Arles).',
    hint: 'Le Rhône coule vers le sud et rejoint la Méditerranée.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-016',
    subject: 'decouverte_du_monde',
    title: 'La Garonne',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Garonne est un grand fleuve du sud-ouest. Quelle grande ville traverse-t-elle ?',
    options: [
      { id: 'a', text: 'Marseille', isCorrect: false },
      { id: 'b', text: 'Bordeaux', isCorrect: true },
      { id: 'c', text: 'Lyon', isCorrect: false },
      { id: 'd', text: 'Nantes', isCorrect: false },
    ],
    correctAnswer: 'Bordeaux',
    explanation: 'La Garonne traverse Toulouse et Bordeaux avant de se jeter dans l\'Atlantique. Elle forme l\'estuaire de la Gironde avec la Dordogne.',
    hint: 'La Garonne passe par Toulouse et Bordeaux.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-017',
    subject: 'decouverte_du_monde',
    title: 'Les Alpes',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'massifs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le mont Blanc est le point culminant des Alpes et de l\'Europe occidentale. Il est situé…',
    options: [
      { id: 'a', text: 'dans les Pyrénées', isCorrect: false },
      { id: 'b', text: 'à la frontière franco-italienne en Haute-Savoie', isCorrect: true },
      { id: 'c', text: 'dans le Massif central', isCorrect: false },
      { id: 'd', text: 'au bord de la Méditerranée', isCorrect: false },
    ],
    correctAnswer: 'à la frontière franco-italienne en Haute-Savoie',
    explanation: 'Le mont Blanc (4 808 m) est le plus haut sommet d\'Europe. Il se trouve à la frontière entre la France, l\'Italie et la Suisse.',
    hint: 'Le mont Blanc est à la frontière franco-italienne.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-018',
    subject: 'decouverte_du_monde',
    title: 'Les Pyrénées',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'massifs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les Pyrénées forment la frontière naturelle entre la France et…',
    options: [
      { id: 'a', text: 'l\'Italie', isCorrect: false },
      { id: 'b', text: 'l\'Espagne', isCorrect: true },
      { id: 'c', text: 'l\'Allemagne', isCorrect: false },
      { id: 'd', text: 'la Belgique', isCorrect: false },
    ],
    correctAnswer: 'l\'Espagne',
    explanation: 'Les Pyrénées sont une chaîne de montagnes qui sépare la France de l\'Espagne et d\'Andorre (du golfe de Gascogne à la Méditerranée).',
    hint: 'Les Pyrénées séparent la France de l\'Espagne.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-019',
    subject: 'decouverte_du_monde',
    title: 'Le Massif central',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'massifs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le Massif central est un vieux massif montagneux situé…',
    options: [
      { id: 'a', text: 'au nord de la France', isCorrect: false },
      { id: 'b', text: 'au centre de la France', isCorrect: true },
      { id: 'c', text: 'à l\'est de la France', isCorrect: false },
      { id: 'd', text: 'dans les DOM-TOM', isCorrect: false },
    ],
    correctAnswer: 'au centre de la France',
    explanation: 'Le Massif central est au centre de la France. Il est à l\'origine de nombreux fleuves (Loire, Allier, Dordogne…). Le Puy-de-Dôme est son sommet le plus célèbre.',
    hint: 'Central → au centre. Le Puy-de-Dôme y est.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-020',
    subject: 'decouverte_du_monde',
    title: 'Les Vosges',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'massifs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les Vosges sont un massif montagneux situé…',
    options: [
      { id: 'a', text: 'dans le sud de la France', isCorrect: false },
      { id: 'b', text: 'dans l\'est de la France (Alsace-Lorraine)', isCorrect: true },
      { id: 'c', text: 'dans l\'ouest de la France', isCorrect: false },
      { id: 'd', text: 'en Bretagne', isCorrect: false },
    ],
    correctAnswer: 'dans l\'est de la France (Alsace-Lorraine)',
    explanation: 'Les Vosges sont un massif de l\'est de la France, entre l\'Alsace et la Lorraine. Elles sont moins hautes que les Alpes.',
    hint: 'Les Vosges sont entre l\'Alsace et la Lorraine.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-021',
    subject: 'decouverte_du_monde',
    title: 'La côte méditerranéenne',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'cotes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La côte méditerranéenne de la France se trouve au…',
    options: [
      { id: 'a', text: 'nord', isCorrect: false },
      { id: 'b', text: 'sud', isCorrect: true },
      { id: 'c', text: 'ouest', isCorrect: false },
      { id: 'd', text: 'centre', isCorrect: false },
    ],
    correctAnswer: 'sud',
    explanation: 'La côte méditerranéenne (Côte d\'Azur, Languedoc) se trouve dans le sud de la France, entre l\'Espagne et l\'Italie.',
    hint: 'La Méditerranée borde le sud de la France.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-022',
    subject: 'decouverte_du_monde',
    title: 'Paris, capitale',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'grandes_villes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quelle est la capitale de la France ?',
    options: [
      { id: 'a', text: 'Lyon', isCorrect: false },
      { id: 'b', text: 'Paris', isCorrect: true },
      { id: 'c', text: 'Marseille', isCorrect: false },
      { id: 'd', text: 'Bordeaux', isCorrect: false },
    ],
    correctAnswer: 'Paris',
    explanation: 'Paris est la capitale de la France. C\'est aussi la plus grande ville du pays. Elle est traversée par la Seine.',
    hint: 'La tour Eiffel s\'y trouve.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-023',
    subject: 'decouverte_du_monde',
    title: 'Marseille',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'grandes_villes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Marseille est la 2e ville de France. Elle se trouve…',
    options: [
      { id: 'a', text: 'en Bretagne', isCorrect: false },
      { id: 'b', text: 'dans le sud de la France, sur la Méditerranée', isCorrect: true },
      { id: 'c', text: 'dans le nord, près de la Belgique', isCorrect: false },
      { id: 'd', text: 'dans l\'est, près des Alpes', isCorrect: false },
    ],
    correctAnswer: 'dans le sud de la France, sur la Méditerranée',
    explanation: 'Marseille (environ 900 000 habitants) est le plus grand port de France. Elle est en bord de Méditerranée dans la région PACA.',
    hint: 'Marseille est un grand port sur la Méditerranée.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-024',
    subject: 'decouverte_du_monde',
    title: 'Lyon',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'grandes_villes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lyon est la 3e ville de France. Deux fleuves la traversent : le Rhône et…',
    options: [
      { id: 'a', text: 'la Loire', isCorrect: false },
      { id: 'b', text: 'la Saône', isCorrect: true },
      { id: 'c', text: 'la Garonne', isCorrect: false },
      { id: 'd', text: 'la Seine', isCorrect: false },
    ],
    correctAnswer: 'la Saône',
    explanation: 'Lyon est au confluent du Rhône et de la Saône. C\'est une ville connue pour sa gastronomie et ses lumières.',
    hint: 'Lyon est au confluent (point de rencontre) du Rhône et de la Saône.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-025',
    subject: 'decouverte_du_monde',
    title: 'La côte atlantique',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'cotes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La côte atlantique de la France se trouve à l\'…',
    options: [
      { id: 'a', text: 'est', isCorrect: false },
      { id: 'b', text: 'ouest', isCorrect: true },
      { id: 'c', text: 'nord', isCorrect: false },
      { id: 'd', text: 'centre', isCorrect: false },
    ],
    correctAnswer: 'ouest',
    explanation: 'L\'océan Atlantique borde la France à l\'ouest. Des villes comme Brest, La Rochelle, Nantes et Bordeaux sont sur la côte atlantique.',
    hint: 'L\'Atlantique est à l\'ouest de la France.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-026',
    subject: 'decouverte_du_monde',
    title: 'Les régions de France',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'grandes_villes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Depuis 2016, la France métropolitaine est divisée en combien de régions ?',
    options: [
      { id: 'a', text: '8 régions', isCorrect: false },
      { id: 'b', text: '13 régions', isCorrect: true },
      { id: 'c', text: '22 régions', isCorrect: false },
      { id: 'd', text: '96 régions', isCorrect: false },
    ],
    correctAnswer: '13 régions',
    explanation: 'Depuis la réforme de 2016, la France métropolitaine compte 13 régions (contre 22 auparavant). Plus 5 régions d\'outre-mer.',
    hint: '13 régions en France métropolitaine depuis 2016.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-027',
    subject: 'decouverte_du_monde',
    title: 'La Bretagne sur la carte',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'grandes_villes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Bretagne est une péninsule qui s\'avance dans…',
    options: [
      { id: 'a', text: 'la Méditerranée', isCorrect: false },
      { id: 'b', text: 'l\'océan Atlantique et la Manche', isCorrect: true },
      { id: 'c', text: 'la mer du Nord uniquement', isCorrect: false },
      { id: 'd', text: 'le lac Léman', isCorrect: false },
    ],
    correctAnswer: 'l\'océan Atlantique et la Manche',
    explanation: 'La Bretagne est une péninsule entourée par l\'Atlantique au sud et à l\'ouest, et la Manche au nord.',
    hint: 'La Bretagne est entourée d\'eau sur trois côtés.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-028',
    subject: 'decouverte_du_monde',
    title: 'Fleuves de France : récapitulatif',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces cours d\'eau N\'est PAS un fleuve de France ?',
    options: [
      { id: 'a', text: 'La Loire', isCorrect: false },
      { id: 'b', text: 'La Seine', isCorrect: false },
      { id: 'c', text: 'Le Danube', isCorrect: true },
      { id: 'd', text: 'La Garonne', isCorrect: false },
    ],
    correctAnswer: 'Le Danube',
    explanation: 'Le Danube est un fleuve d\'Europe centrale (Allemagne, Autriche, Roumanie…). Les fleuves de France sont : Loire, Seine, Rhône, Garonne, Rhin.',
    hint: 'Le Danube traverse l\'Europe de l\'est — il ne passe pas par la France.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-029',
    subject: 'decouverte_du_monde',
    title: 'Le relief et les rivières',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les fleuves prennent généralement leur source…',
    options: [
      { id: 'a', text: 'dans la mer', isCorrect: false },
      { id: 'b', text: 'dans les montagnes ou les hauteurs', isCorrect: true },
      { id: 'c', text: 'en ville', isCorrect: false },
      { id: 'd', text: 'à égale distance entre deux villes', isCorrect: false },
    ],
    correctAnswer: 'dans les montagnes ou les hauteurs',
    explanation: 'L\'eau coule de haut en bas. Les fleuves naissent dans les reliefs (montagnes, collines) et descendent vers la mer.',
    hint: 'L\'eau coule toujours de haut en bas.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-030',
    subject: 'decouverte_du_monde',
    title: 'Frontières de la France',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'grandes_villes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Lequel de ces pays ne partage PAS une frontière terrestre avec la France ?',
    options: [
      { id: 'a', text: 'L\'Espagne', isCorrect: false },
      { id: 'b', text: 'La Belgique', isCorrect: false },
      { id: 'c', text: 'Le Portugal', isCorrect: true },
      { id: 'd', text: 'L\'Italie', isCorrect: false },
    ],
    correctAnswer: 'Le Portugal',
    explanation: 'Le Portugal est séparé de la France par l\'Espagne. La France partage ses frontières avec : Belgique, Luxembourg, Allemagne, Suisse, Italie, Monaco, Espagne, Andorre.',
    hint: 'Le Portugal est à l\'ouest de l\'Espagne — entre les deux il y a l\'Espagne.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-031',
    subject: 'decouverte_du_monde',
    title: 'Le Jura',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'massifs',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le massif du Jura est situé à la frontière entre la France et…',
    options: [
      { id: 'a', text: 'l\'Espagne', isCorrect: false },
      { id: 'b', text: 'la Suisse', isCorrect: true },
      { id: 'c', text: 'la Belgique', isCorrect: false },
      { id: 'd', text: 'l\'Allemagne', isCorrect: false },
    ],
    correctAnswer: 'la Suisse',
    explanation: 'Le Jura est un massif calcaire qui forme la frontière entre la France et la Suisse. C\'est aussi le nom d\'un département français.',
    hint: 'Jura → horlogerie suisse. C\'est à la frontière franco-suisse.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-032',
    subject: 'decouverte_du_monde',
    title: 'Strasbourg et le Rhin',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'espace',
    subskill: 'fleuves',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Strasbourg est une grande ville d\'Alsace traversée par un fleuve qui sert de frontière avec l\'Allemagne. Ce fleuve est…',
    options: [
      { id: 'a', text: 'la Moselle', isCorrect: false },
      { id: 'b', text: 'le Rhin', isCorrect: true },
      { id: 'c', text: 'la Seine', isCorrect: false },
      { id: 'd', text: 'le Rhône', isCorrect: false },
    ],
    correctAnswer: 'le Rhin',
    explanation: 'Le Rhin forme la frontière entre l\'Alsace (France) et l\'Allemagne. Strasbourg est sur sa rive ouest.',
    hint: 'Le Rhin est le fleuve frontière entre France et Allemagne à l\'est.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
