import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe2TempsHistoireExercises: DecouverteExercise[] = [

  // CE2 · temps · histoire et frise chronologique
  {
    id: 'ddm-ce2-tem-003',
    subject: 'decouverte_du_monde',
    title: 'La frise chronologique',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Une frise chronologique représente…',
    options: [
      { id: 'a', text: 'une liste de recettes de cuisine dans le temps', isCorrect: false },
      { id: 'b', text: 'le déroulement du temps avec des événements placés dans l\'ordre', isCorrect: true },
      { id: 'c', text: 'une carte géographique en couleurs', isCorrect: false },
      { id: 'd', text: 'un calendrier de la semaine', isCorrect: false },
    ],
    correctAnswer: 'le déroulement du temps avec des événements placés dans l\'ordre',
    explanation: 'Une frise chronologique est une ligne du temps sur laquelle on place les événements historiques dans l\'ordre chronologique.',
    hint: 'Une ligne du temps avec des événements placés dans l\'ordre.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-004',
    subject: 'decouverte_du_monde',
    title: 'Les grandes périodes de l\'histoire',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien y a-t-il de grandes périodes dans l\'histoire enseignée à l\'école ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
      { id: 'd', text: '100', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'L\'histoire se divise en 4 grandes périodes : Préhistoire, Antiquité, Moyen Âge, Époque moderne et contemporaine.',
    hint: 'Préhistoire, Antiquité, Moyen Âge, Époque moderne — 4 périodes.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-005',
    subject: 'decouverte_du_monde',
    title: 'La Préhistoire',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Préhistoire se caractérise par…',
    options: [
      { id: 'a', text: 'l\'existence de l\'écriture et des grandes villes', isCorrect: false },
      { id: 'b', text: 'la période avant l\'invention de l\'écriture', isCorrect: true },
      { id: 'c', text: 'la construction de cathédrales', isCorrect: false },
      { id: 'd', text: 'l\'époque des rois et des chevaliers', isCorrect: false },
    ],
    correctAnswer: 'la période avant l\'invention de l\'écriture',
    explanation: 'La Préhistoire est la très longue période avant l\'invention de l\'écriture (vers -3300 av. J.-C.). Les hommes vivaient en chassant et en cueillant.',
    hint: 'Avant l\'écriture = Préhistoire.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-006',
    subject: 'decouverte_du_monde',
    title: 'Les hommes préhistoriques',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment les hommes préhistoriques obtenaient-ils leur nourriture ?',
    options: [
      { id: 'a', text: 'Dans les supermarchés', isCorrect: false },
      { id: 'b', text: 'En chassant, pêchant et cueillant', isCorrect: true },
      { id: 'c', text: 'En achetant aux agriculteurs', isCorrect: false },
      { id: 'd', text: 'En cultivant dans des serres modernes', isCorrect: false },
    ],
    correctAnswer: 'En chassant, pêchant et cueillant',
    explanation: 'Les premiers humains étaient chasseurs-cueilleurs. Plus tard, ils ont appris l\'agriculture et l\'élevage (néolithique).',
    hint: 'Avant l\'agriculture, on chassait et on cueillait.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-007',
    subject: 'decouverte_du_monde',
    title: 'L\'Antiquité',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'Antiquité commence avec l\'invention de l\'écriture. Quelle grande civilisation de l\'Antiquité est connue pour les pyramides ?',
    options: [
      { id: 'a', text: 'La Grèce', isCorrect: false },
      { id: 'b', text: 'L\'Égypte ancienne', isCorrect: true },
      { id: 'c', text: 'La Rome antique', isCorrect: false },
      { id: 'd', text: 'La Chine médiévale', isCorrect: false },
    ],
    correctAnswer: 'L\'Égypte ancienne',
    explanation: 'L\'Égypte ancienne (Antiquité) est connue pour ses pyramides, ses pharaons et ses hiéroglyphes.',
    hint: 'Les pharaons et les hiéroglyphes.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-008',
    subject: 'decouverte_du_monde',
    title: 'Les Gaulois',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les Gaulois vivaient en France pendant quelle période ?',
    options: [
      { id: 'a', text: 'La Préhistoire', isCorrect: false },
      { id: 'b', text: 'L\'Antiquité', isCorrect: true },
      { id: 'c', text: 'Le Moyen Âge', isCorrect: false },
      { id: 'd', text: 'L\'époque contemporaine', isCorrect: false },
    ],
    correctAnswer: 'L\'Antiquité',
    explanation: 'Les Gaulois (peuple celtique) vivaient en Gaule (l\'actuelle France) pendant l\'Antiquité, avant la conquête romaine de Jules César.',
    hint: 'Astérix et Obélix vivent en Gaule antique.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-009',
    subject: 'decouverte_du_monde',
    title: 'Le Moyen Âge',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le Moyen Âge est la période de l\'histoire où l\'on construisait des…',
    options: [
      { id: 'a', text: 'pyramides', isCorrect: false },
      { id: 'b', text: 'châteaux forts et cathédrales', isCorrect: true },
      { id: 'c', text: 'gratte-ciels', isCorrect: false },
      { id: 'd', text: 'fusées', isCorrect: false },
    ],
    correctAnswer: 'châteaux forts et cathédrales',
    explanation: 'Le Moyen Âge (environ 476–1492) est l\'époque des chevaliers, des châteaux forts, des cathédrales et des seigneurs féodaux.',
    hint: 'L\'époque des chevaliers et des châteaux forts.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-010',
    subject: 'decouverte_du_monde',
    title: 'L\'invention de l\'imprimerie',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'L\'invention de l\'imprimerie par Gutenberg (vers 1450) marque le début de…',
    options: [
      { id: 'a', text: 'la Préhistoire', isCorrect: false },
      { id: 'b', text: 'l\'Époque moderne (fin du Moyen Âge)', isCorrect: true },
      { id: 'c', text: 'l\'Antiquité', isCorrect: false },
      { id: 'd', text: 'l\'ère spatiale', isCorrect: false },
    ],
    correctAnswer: 'l\'Époque moderne (fin du Moyen Âge)',
    explanation: 'L\'imprimerie de Gutenberg (vers 1450) a révolutionné la diffusion des savoirs et marque le passage du Moyen Âge à l\'Époque moderne.',
    hint: 'L\'imprimerie a permis de diffuser les livres à grande échelle.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-011',
    subject: 'decouverte_du_monde',
    title: 'Objets d\'autrefois vs. d\'aujourd\'hui',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'avant_apres',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Avant les téléphones portables, comment communiquait-on à distance ?',
    options: [
      { id: 'a', text: 'par texto', isCorrect: false },
      { id: 'b', text: 'par lettre écrite et téléphone fixe', isCorrect: true },
      { id: 'c', text: 'par email', isCorrect: false },
      { id: 'd', text: 'par message vocal WhatsApp', isCorrect: false },
    ],
    correctAnswer: 'par lettre écrite et téléphone fixe',
    explanation: 'Avant les téléphones portables, on communiquait par lettres (le courrier postal) ou par téléphone fixe à la maison.',
    hint: 'Le courrier postal et le téléphone fixe existaient bien avant le portable.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-012',
    subject: 'decouverte_du_monde',
    title: 'L\'évolution du transport',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'avant_apres',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans l\'ordre chronologique, quel mode de transport est apparu en premier ?',
    options: [
      { id: 'a', text: 'L\'avion', isCorrect: false },
      { id: 'b', text: 'Le bateau à voile', isCorrect: true },
      { id: 'c', text: 'La voiture', isCorrect: false },
      { id: 'd', text: 'Le train', isCorrect: false },
    ],
    correctAnswer: 'Le bateau à voile',
    explanation: 'Les bateaux à voile existent depuis l\'Antiquité. Les trains sont apparus au XIXe siècle, les voitures et avions au XXe siècle.',
    hint: 'Les bateaux à voile existent depuis l\'Antiquité.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-013',
    subject: 'decouverte_du_monde',
    title: 'L\'école autrefois',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'avant_apres',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Au XIXe siècle, les enfants étaient souvent obligés de travailler. Qui a rendu l\'école gratuite et obligatoire en France ?',
    options: [
      { id: 'a', text: 'Napoléon Bonaparte', isCorrect: false },
      { id: 'b', text: 'Jules Ferry', isCorrect: true },
      { id: 'c', text: 'Louis XIV', isCorrect: false },
      { id: 'd', text: 'Victor Hugo', isCorrect: false },
    ],
    correctAnswer: 'Jules Ferry',
    explanation: 'Jules Ferry, ministre de l\'Éducation, a rendu l\'école primaire gratuite (1881) et obligatoire (1882) pour tous les enfants de France.',
    hint: 'Jules Ferry = école gratuite, laïque et obligatoire (lois de 1881-1882).',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-014',
    subject: 'decouverte_du_monde',
    title: 'La Révolution française',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La Révolution française a eu lieu en…',
    options: [
      { id: 'a', text: '1492', isCorrect: false },
      { id: 'b', text: '1789', isCorrect: true },
      { id: 'c', text: '1914', isCorrect: false },
      { id: 'd', text: '1945', isCorrect: false },
    ],
    correctAnswer: '1789',
    explanation: 'La Révolution française a commencé en 1789 avec la prise de la Bastille. Elle a mis fin à la monarchie absolue et proclamé les droits de l\'Homme.',
    hint: 'La Bastille a été prise le 14 juillet 1789.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-015',
    subject: 'decouverte_du_monde',
    title: 'Lire une frise chronologique',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sur une frise chronologique, quel événement est le plus ancien : celui placé à gauche ou à droite ?',
    options: [
      { id: 'a', text: 'Celui placé à droite.', isCorrect: false },
      { id: 'b', text: 'Celui placé à gauche.', isCorrect: true },
      { id: 'c', text: 'L\'ordre n\'a pas d\'importance.', isCorrect: false },
      { id: 'd', text: 'Celui placé en haut.', isCorrect: false },
    ],
    correctAnswer: 'Celui placé à gauche.',
    explanation: 'Sur une frise chronologique horizontale, le temps avance de gauche à droite. L\'événement le plus à gauche est donc le plus ancien.',
    hint: 'Sur une frise, le temps va de gauche (passé) à droite (présent/futur).',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-016',
    subject: 'decouverte_du_monde',
    title: 'Avant Jésus-Christ',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: '« av. J.-C. » signifie avant Jésus-Christ. Un événement en -500 av. J.-C. est-il plus ancien ou plus récent qu\'un en -100 av. J.-C. ?',
    options: [
      { id: 'a', text: 'Plus récent.', isCorrect: false },
      { id: 'b', text: 'Plus ancien.', isCorrect: true },
      { id: 'c', text: 'De la même époque.', isCorrect: false },
      { id: 'd', text: 'On ne peut pas comparer.', isCorrect: false },
    ],
    correctAnswer: 'Plus ancien.',
    explanation: 'Pour les dates av. J.-C., plus le nombre est grand, plus l\'événement est ancien. -500 est avant -100 dans le temps.',
    hint: 'Avant J.-C. : plus le chiffre est grand, plus c\'est ancien.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-017',
    subject: 'decouverte_du_monde',
    title: 'Les siècles',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Combien d\'années y a-t-il dans un siècle ?',
    options: [
      { id: 'a', text: '10 ans', isCorrect: false },
      { id: 'b', text: '100 ans', isCorrect: true },
      { id: 'c', text: '1000 ans', isCorrect: false },
      { id: 'd', text: '50 ans', isCorrect: false },
    ],
    correctAnswer: '100 ans',
    explanation: 'Un siècle = 100 ans. Un millénaire = 1000 ans. Nous sommes au XXIe siècle (années 2000-2099).',
    hint: '« Cent » et « siècle » ont la même racine latine.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-018',
    subject: 'decouverte_du_monde',
    title: 'Le XXe siècle',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Le XXe siècle correspond aux années…',
    options: [
      { id: 'a', text: '1800–1899', isCorrect: false },
      { id: 'b', text: '1900–1999', isCorrect: true },
      { id: 'c', text: '2000–2099', isCorrect: false },
      { id: 'd', text: '1700–1799', isCorrect: false },
    ],
    correctAnswer: '1900–1999',
    explanation: 'Le XXe siècle = de 1900 à 1999. Le XIXe siècle = 1800-1899. Le XXIe siècle (le nôtre) = 2000-2099.',
    hint: 'Le 20e siècle = les années 1900.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-019',
    subject: 'decouverte_du_monde',
    title: 'L\'évolution de l\'école',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'avant_apres',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Dans les écoles d\'autrefois (au début du XXe siècle), avec quoi les élèves écrivaient-ils ?',
    options: [
      { id: 'a', text: 'Des tablettes numériques', isCorrect: false },
      { id: 'b', text: 'Des porte-plume et de l\'encre', isCorrect: true },
      { id: 'c', text: 'Des stylos à bille', isCorrect: false },
      { id: 'd', text: 'Des crayons de couleur', isCorrect: false },
    ],
    correctAnswer: 'Des porte-plume et de l\'encre',
    explanation: 'Au début du XXe siècle, les élèves utilisaient des porte-plume qu\'ils trempaient dans l\'encrier. Les stylos à bille sont arrivés plus tard.',
    hint: 'Les encriers étaient fixés dans les pupitres d\'école.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-020',
    subject: 'decouverte_du_monde',
    title: 'Placer un événement sur une frise',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'temps',
    subskill: 'frise_chronologique',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Sur une frise chronologique avec Préhistoire → Antiquité → Moyen Âge → Époque moderne, les Gaulois se placent…',
    options: [
      { id: 'a', text: 'dans la Préhistoire', isCorrect: false },
      { id: 'b', text: 'dans l\'Antiquité', isCorrect: true },
      { id: 'c', text: 'au Moyen Âge', isCorrect: false },
      { id: 'd', text: 'à l\'Époque moderne', isCorrect: false },
    ],
    correctAnswer: 'dans l\'Antiquité',
    explanation: 'Les Gaulois vivaient à l\'époque de l\'Antiquité (avant et pendant la conquête romaine, Ier siècle av. J.-C.).',
    hint: 'Les Gaulois sont contemporains des Romains (Antiquité).',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-021',
    subject: 'decouverte_du_monde',
    title: 'Les peintures rupestres',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les peintures rupestres (comme à Lascaux) sont des peintures réalisées…',
    options: [
      { id: 'a', text: 'sur des toiles au Moyen Âge', isCorrect: false },
      { id: 'b', text: 'dans des grottes pendant la Préhistoire', isCorrect: true },
      { id: 'c', text: 'sur des murs de cathédrale', isCorrect: false },
      { id: 'd', text: 'dans des musées modernes', isCorrect: false },
    ],
    correctAnswer: 'dans des grottes pendant la Préhistoire',
    explanation: 'Les hommes préhistoriques peignaient sur les parois des grottes (chevaux, bisons, cerfs). La grotte de Lascaux (Dordogne) est très célèbre.',
    hint: 'Lascaux en Dordogne — des peintures vieilles de 17 000 ans.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-tem-022',
    subject: 'decouverte_du_monde',
    title: 'L\'agriculture, une révolution',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'temps',
    subskill: 'grandes_periodes',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Quand les premiers humains ont appris à cultiver la terre et à élever des animaux, cela a permis…',
    options: [
      { id: 'a', text: 'de voyager plus facilement', isCorrect: false },
      { id: 'b', text: 'de se sédentariser et de fonder des villages', isCorrect: true },
      { id: 'c', text: 'de construire des cathédrales', isCorrect: false },
      { id: 'd', text: 'd\'inventer les téléphones', isCorrect: false },
    ],
    correctAnswer: 'de se sédentariser et de fonder des villages',
    explanation: 'La révolution néolithique (agriculture + élevage) a permis aux humains de s\'installer durablement et de créer les premiers villages.',
    hint: 'Cultiver = rester au même endroit = village.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
