import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { DecouverteExercise } from '../decouverte_du_monde.types';

const A = cloneDefaultAdaptations();

export const ddmCe2EspaceExercises: DecouverteExercise[] = [

  // CE2 · espace · paysages
  {
    id: 'ddm-ce2-esp-001',
    subject: 'decouverte_du_monde',
    title: 'La forêt',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis le bon paysage.',
    prompt: 'Dans quel paysage trouve-t-on beaucoup d\'arbres et d\'ombre ?',
    options: [
      { id: 'a', text: 'la mer', isCorrect: false },
      { id: 'b', text: 'la montagne', isCorrect: false },
      { id: 'c', text: 'la forêt', isCorrect: true },
      { id: 'd', text: 'la plaine', isCorrect: false },
    ],
    correctAnswer: 'la forêt',
    explanation: 'La forêt est un espace naturel couvert d\'arbres.',
    hint: 'Les écureuils et les renards y vivent souvent.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-002',
    subject: 'decouverte_du_monde',
    title: 'La mer',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis le bon paysage.',
    prompt: 'Quel paysage est caractérisé par de grandes vagues et du sable ?',
    options: [
      { id: 'a', text: 'la forêt', isCorrect: false },
      { id: 'b', text: 'la rivière', isCorrect: false },
      { id: 'c', text: 'la mer', isCorrect: true },
      { id: 'd', text: 'la montagne', isCorrect: false },
    ],
    correctAnswer: 'la mer',
    explanation: 'La mer est une grande étendue d\'eau salée avec des plages et des vagues.',
    hint: 'On y va souvent en vacances pour se baigner.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-003',
    subject: 'decouverte_du_monde',
    title: 'La rivière',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on un cours d\'eau plus petit qu\'un fleuve ?',
    options: [
      { id: 'a', text: 'un lac', isCorrect: false },
      { id: 'b', text: 'une rivière', isCorrect: true },
      { id: 'c', text: 'une mer', isCorrect: false },
      { id: 'd', text: 'un océan', isCorrect: false },
    ],
    correctAnswer: 'une rivière',
    explanation: 'Une rivière est un cours d\'eau qui se jette dans un fleuve ou dans la mer.',
    hint: 'Elle est plus petite qu\'un fleuve.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-004',
    subject: 'decouverte_du_monde',
    title: 'Les montagnes',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on les hauts reliefs qu\'on voit dans les Alpes ?',
    options: [
      { id: 'a', text: 'des collines', isCorrect: false },
      { id: 'b', text: 'des plaines', isCorrect: false },
      { id: 'c', text: 'des montagnes', isCorrect: true },
      { id: 'd', text: 'des îles', isCorrect: false },
    ],
    correctAnswer: 'des montagnes',
    explanation: 'Les Alpes sont une grande chaîne de montagnes très haute.',
    hint: 'En hiver, il y a souvent de la neige tout en haut.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-012',
    subject: 'decouverte_du_monde',
    title: 'Le lac',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'paysages',
    format: 'qcm',
    instructions: 'Choisis la bonne définition.',
    prompt: 'Comment appelle-t-on une grande étendue d\'eau douce entourée de terres ?',
    options: [
      { id: 'a', text: 'une mer', isCorrect: false },
      { id: 'b', text: 'un lac', isCorrect: true },
      { id: 'c', text: 'un fleuve', isCorrect: false },
      { id: 'd', text: 'un océan', isCorrect: false },
    ],
    correctAnswer: 'un lac',
    explanation: 'Un lac est une étendue d\'eau douce entourée de terre de tous les côtés.',
    hint: 'Il ne coule pas, contrairement à une rivière.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CE2 · espace · ville_campagne
  {
    id: 'ddm-ce2-esp-005',
    subject: 'decouverte_du_monde',
    title: 'À la campagne',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'ville_campagne',
    format: 'qcm',
    instructions: 'Choisis ce qu\'on trouve plutôt à la campagne.',
    prompt: 'Lequel de ces éléments trouve-t-on plutôt à la campagne ?',
    options: [
      { id: 'a', text: 'un métro', isCorrect: false },
      { id: 'b', text: 'un gratte-ciel', isCorrect: false },
      { id: 'c', text: 'un champ de blé', isCorrect: true },
      { id: 'd', text: 'un grand magasin', isCorrect: false },
    ],
    correctAnswer: 'un champ de blé',
    explanation: 'À la campagne, on trouve des champs cultivés, des prés et des forêts.',
    hint: 'C\'est là où poussent les céréales pour faire le pain.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-006',
    subject: 'decouverte_du_monde',
    title: 'Le maire',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'ville_campagne',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on le chef d\'une ville ou d\'un village ?',
    options: [
      { id: 'a', text: 'le président', isCorrect: false },
      { id: 'b', text: 'le maire', isCorrect: true },
      { id: 'c', text: 'le directeur', isCorrect: false },
      { id: 'd', text: 'le gouverneur', isCorrect: false },
    ],
    correctAnswer: 'le maire',
    explanation: 'Le maire est élu par les habitants pour diriger la commune (ville ou village).',
    hint: 'Il travaille à la mairie.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-007',
    subject: 'decouverte_du_monde',
    title: 'Capitale de la France',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'ville_campagne',
    format: 'qcm',
    instructions: 'Choisis la bonne ville.',
    prompt: 'Quelle est la plus grande ville de France ?',
    options: [
      { id: 'a', text: 'Lyon', isCorrect: false },
      { id: 'b', text: 'Marseille', isCorrect: false },
      { id: 'c', text: 'Bordeaux', isCorrect: false },
      { id: 'd', text: 'Paris', isCorrect: true },
    ],
    correctAnswer: 'Paris',
    explanation: 'Paris est la capitale et la plus grande ville de France.',
    hint: 'C\'est là où se trouve la tour Eiffel.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-011',
    subject: 'decouverte_du_monde',
    title: 'Transports en commun',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'ville_campagne',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Les bus et le métro (transports en commun) se trouvent plutôt…',
    options: [
      { id: 'a', text: 'à la campagne', isCorrect: false },
      { id: 'b', text: 'en montagne', isCorrect: false },
      { id: 'c', text: 'en ville', isCorrect: true },
      { id: 'd', text: 'dans les forêts', isCorrect: false },
    ],
    correctAnswer: 'en ville',
    explanation: 'Les transports en commun (bus, métro, tramway) existent surtout en ville où il y a beaucoup d\'habitants.',
    hint: 'Il y a trop de monde en ville pour que tout le monde prenne sa voiture.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CE2 · espace · quartier
  {
    id: 'ddm-ce2-esp-008',
    subject: 'decouverte_du_monde',
    title: 'Le parc du quartier',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'quartier',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on un espace vert avec des bancs et des jeux pour enfants dans un quartier ?',
    options: [
      { id: 'a', text: 'un marché', isCorrect: false },
      { id: 'b', text: 'un parc ou un jardin public', isCorrect: true },
      { id: 'c', text: 'une gare', isCorrect: false },
      { id: 'd', text: 'un parking', isCorrect: false },
    ],
    correctAnswer: 'un parc ou un jardin public',
    explanation: 'Un parc ou jardin public est un espace vert ouvert à tous dans un quartier ou une ville.',
    hint: 'On y joue dehors et on y promène les chiens.',
    estimatedMinutes: 1,
    adaptations: A,
  },
  {
    id: 'ddm-ce2-esp-009',
    subject: 'decouverte_du_monde',
    title: 'La mairie',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'quartier',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'La mairie est le bâtiment où travaille…',
    options: [
      { id: 'a', text: 'le médecin', isCorrect: false },
      { id: 'b', text: 'le boulanger', isCorrect: false },
      { id: 'c', text: 'le maire et ses équipes', isCorrect: true },
      { id: 'd', text: 'le directeur de l\'école', isCorrect: false },
    ],
    correctAnswer: 'le maire et ses équipes',
    explanation: 'La mairie est le bâtiment officiel de la commune, où travaillent le maire et ses collaborateurs.',
    hint: 'On y voit souvent le drapeau tricolore.',
    estimatedMinutes: 1,
    adaptations: A,
  },

  // CE2 · espace · maison_ecole
  {
    id: 'ddm-ce2-esp-010',
    subject: 'decouverte_du_monde',
    title: 'Le directeur de l\'école',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'espace',
    subskill: 'maison_ecole',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: 'Comment appelle-t-on la personne qui dirige une école ?',
    options: [
      { id: 'a', text: 'le maire', isCorrect: false },
      { id: 'b', text: 'le proviseur', isCorrect: false },
      { id: 'c', text: 'le directeur ou la directrice', isCorrect: true },
      { id: 'd', text: 'l\'inspecteur', isCorrect: false },
    ],
    correctAnswer: 'le directeur ou la directrice',
    explanation: 'Le directeur (ou la directrice) est le responsable de l\'école primaire.',
    hint: 'C\'est lui ou elle que l\'on va voir quand il y a un problème important.',
    estimatedMinutes: 1,
    adaptations: A,
  },
];
