import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm1VocVilleExercises: EnglishExercise[] = [
  {
    id: 'en-cm1-voc-029',
    subject: 'anglais',
    title: 'La ville : town centre',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « town centre » en français ?',
    options: [
      { id: 'a', text: 'La banlieue', isCorrect: false },
      { id: 'b', text: 'Le centre-ville', isCorrect: true },
      { id: 'c', text: 'La zone industrielle', isCorrect: false },
    ],
    correctAnswer: 'Le centre-ville',
    explanation: '« Town centre » = centre-ville. En anglais américain on dit « downtown ».',
    hint: 'Le cœur de la ville.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-030',
    subject: 'anglais',
    title: 'La ville : supermarket',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « supermarket » en français ?',
    options: [
      { id: 'a', text: 'Le marché', isCorrect: false },
      { id: 'b', text: 'Le supermarché', isCorrect: true },
      { id: 'c', text: 'La boulangerie', isCorrect: false },
    ],
    correctAnswer: 'Le supermarché',
    explanation: '« Supermarket » = supermarché. Même mot qu\'en français !',
    hint: 'Même mot qu\'en français !',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-031',
    subject: 'anglais',
    title: 'La ville : bank',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « bank » en français (dans le contexte d\'une ville) ?',
    options: [
      { id: 'a', text: 'La banque', isCorrect: true },
      { id: 'b', text: 'La boutique', isCorrect: false },
      { id: 'c', text: 'Le banc (de parc)', isCorrect: false },
    ],
    correctAnswer: 'La banque',
    explanation: '« Bank » = banque (ou rive d\'une rivière, selon le contexte).',
    hint: 'On y garde son argent.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-032',
    subject: 'anglais',
    title: 'La ville : post office',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « post office » en français ?',
    options: [
      { id: 'a', text: 'Le bureau de police', isCorrect: false },
      { id: 'b', text: 'La poste / le bureau de poste', isCorrect: true },
      { id: 'c', text: 'L\'office de tourisme', isCorrect: false },
    ],
    correctAnswer: 'La poste / le bureau de poste',
    explanation: '« Post office » = bureau de poste. « Post » = courrier en anglais.',
    hint: '« Post » = courrier. On y envoie les lettres.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-033',
    subject: 'anglais',
    title: 'La ville : hospital',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « hospital » en français ?',
    options: [
      { id: 'a', text: 'L\'hôtel', isCorrect: false },
      { id: 'b', text: 'L\'hôpital', isCorrect: true },
      { id: 'c', text: 'Le cabinet médical', isCorrect: false },
    ],
    correctAnswer: 'L\'hôpital',
    explanation: '« Hospital » = hôpital. Attention, « hotel » = hôtel (avec un e à la fin).',
    hint: 'On y soigne les malades. Attention : hotel ≠ hospital !',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-034',
    subject: 'anglais',
    title: 'La ville : restaurant',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « restaurant » en français ?',
    options: [
      { id: 'a', text: 'Le restaurant', isCorrect: true },
      { id: 'b', text: 'La boulangerie', isCorrect: false },
      { id: 'c', text: 'La cafétéria', isCorrect: false },
    ],
    correctAnswer: 'Le restaurant',
    explanation: '« Restaurant » = restaurant. Même mot en français et en anglais !',
    hint: 'Même mot qu\'en français !',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-035',
    subject: 'anglais',
    title: 'La ville : museum',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « museum » en français ?',
    options: [
      { id: 'a', text: 'Le cinéma', isCorrect: false },
      { id: 'b', text: 'Le musée', isCorrect: true },
      { id: 'c', text: 'Le théâtre', isCorrect: false },
    ],
    correctAnswer: 'Le musée',
    explanation: '« Museum » = musée. On y voit des œuvres d\'art, des expositions.',
    hint: 'On y voit des tableaux et des objets historiques.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-036',
    subject: 'anglais',
    title: 'La ville : station',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « train station » en français ?',
    options: [
      { id: 'a', text: 'La station de métro', isCorrect: false },
      { id: 'b', text: 'La gare', isCorrect: true },
      { id: 'c', text: 'Le dépôt de bus', isCorrect: false },
    ],
    correctAnswer: 'La gare',
    explanation: '« Train station » = gare. On y prend le train.',
    hint: 'On y prend le train.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-037',
    subject: 'anglais',
    title: 'La ville : bus stop',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « bus stop » en français ?',
    options: [
      { id: 'a', text: 'Le terminus de bus', isCorrect: false },
      { id: 'b', text: 'L\'arrêt de bus', isCorrect: true },
      { id: 'c', text: 'Le dépôt de bus', isCorrect: false },
    ],
    correctAnswer: 'L\'arrêt de bus',
    explanation: '« Bus stop » = arrêt de bus. On y attend le bus.',
    hint: 'On y attend le bus.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-038',
    subject: 'anglais',
    title: 'La ville : pedestrian crossing',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « pedestrian crossing » en français ?',
    options: [
      { id: 'a', text: 'Le passage souterrain', isCorrect: false },
      { id: 'b', text: 'Le passage piéton / le passage clouté', isCorrect: true },
      { id: 'c', text: 'Le carrefour', isCorrect: false },
    ],
    correctAnswer: 'Le passage piéton / le passage clouté',
    explanation: '« Pedestrian » = piéton. « Crossing » = traversée. On traverse la rue ici en sécurité.',
    hint: '« Pedestrian » = piéton. On traverse la route ici.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-039',
    subject: 'anglais',
    title: 'La ville : chemist',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « chemist » en français (dans le contexte d\'une ville) ?',
    options: [
      { id: 'a', text: 'Le chimiste (scientifique)', isCorrect: false },
      { id: 'b', text: 'La pharmacie / le pharmacien', isCorrect: true },
      { id: 'c', text: 'Le laboratoire', isCorrect: false },
    ],
    correctAnswer: 'La pharmacie / le pharmacien',
    explanation: '« Chemist » = pharmacie (anglais britannique). On dit aussi « pharmacy ».',
    hint: 'On y achète des médicaments.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-040',
    subject: 'anglais',
    title: 'La ville : fire station',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « fire station » en français ?',
    options: [
      { id: 'a', text: 'La gare', isCorrect: false },
      { id: 'b', text: 'La caserne de pompiers', isCorrect: true },
      { id: 'c', text: 'La centrale électrique', isCorrect: false },
    ],
    correctAnswer: 'La caserne de pompiers',
    explanation: '« Fire station » = caserne de pompiers. « Fire » = feu, incendie.',
    hint: '« Fire » = feu. C\'est là où travaillent les pompiers.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-041',
    subject: 'anglais',
    title: 'La ville : police station',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « police station » en français ?',
    options: [
      { id: 'a', text: 'Le commissariat de police', isCorrect: true },
      { id: 'b', text: 'L\'hôpital', isCorrect: false },
      { id: 'c', text: 'La mairie', isCorrect: false },
    ],
    correctAnswer: 'Le commissariat de police',
    explanation: '« Police station » = commissariat de police. « Police » = police.',
    hint: '« Police » = police. On y trouve les policiers.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-042',
    subject: 'anglais',
    title: 'La ville : on the high street',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « on the high street » en français ?',
    options: [
      { id: 'a', text: 'Sur l\'autoroute', isCorrect: false },
      { id: 'b', text: 'Dans la rue principale / la grande rue', isCorrect: true },
      { id: 'c', text: 'Au dernier étage', isCorrect: false },
    ],
    correctAnswer: 'Dans la rue principale / la grande rue',
    explanation: '« High street » = rue principale d\'une ville, avec les commerces.',
    hint: '« High » peut vouloir dire principal. C\'est la rue commerçante principale.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-043',
    subject: 'anglais',
    title: 'La ville : near / far from',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « The school is near the park » en français ?',
    options: [
      { id: 'a', text: 'L\'école est loin du parc.', isCorrect: false },
      { id: 'b', text: 'L\'école est près du parc.', isCorrect: true },
      { id: 'c', text: 'L\'école est derrière le parc.', isCorrect: false },
    ],
    correctAnswer: 'L\'école est près du parc.',
    explanation: '« Near » = près de. « Far from » = loin de.',
    hint: '« Near » = proche de. Contraire = « far from ».',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-044',
    subject: 'anglais',
    title: 'La ville : direction globale',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'ville',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « The museum is opposite the library » en français ?',
    options: [
      { id: 'a', text: 'Le musée est à côté de la bibliothèque.', isCorrect: false },
      { id: 'b', text: 'Le musée est en face de la bibliothèque.', isCorrect: true },
      { id: 'c', text: 'Le musée est derrière la bibliothèque.', isCorrect: false },
    ],
    correctAnswer: 'Le musée est en face de la bibliothèque.',
    explanation: '« Opposite » = en face de. « Library » = bibliothèque.',
    hint: '« Opposite » = en face (de l\'autre côté).',
    tags: ['cm1', 'anglais', 'vocabulaire', 'ville', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
