import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm1GramPrepositionsExercises: EnglishExercise[] = [
  {
    id: 'en-cm1-gram-029',
    subject: 'anglais',
    title: 'Prepositions : in',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition.',
    prompt: 'Complète : « The cat is ___ the box. » (le chat est à l\'intérieur de la boîte)',
    options: [
      { id: 'a', text: 'on', isCorrect: false },
      { id: 'b', text: 'in', isCorrect: true },
      { id: 'c', text: 'under', isCorrect: false },
    ],
    correctAnswer: 'in',
    explanation: '« In » = dans / à l\'intérieur de. Le chat est dans la boîte.',
    hint: '« In » = dedans / à l\'intérieur.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-030',
    subject: 'anglais',
    title: 'Prepositions : on',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition.',
    prompt: 'Complète : « The book is ___ the table. » (le livre est posé sur la table)',
    options: [
      { id: 'a', text: 'in', isCorrect: false },
      { id: 'b', text: 'on', isCorrect: true },
      { id: 'c', text: 'next to', isCorrect: false },
    ],
    correctAnswer: 'on',
    explanation: '« On » = sur. Le livre est sur la table.',
    hint: '« On » = sur (surface).',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-031',
    subject: 'anglais',
    title: 'Prepositions : under',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition.',
    prompt: 'Complète : « The dog is ___ the chair. » (le chien est sous la chaise)',
    options: [
      { id: 'a', text: 'on', isCorrect: false },
      { id: 'b', text: 'under', isCorrect: true },
      { id: 'c', text: 'behind', isCorrect: false },
    ],
    correctAnswer: 'under',
    explanation: '« Under » = sous. Le chien est sous la chaise.',
    hint: '« Under » = dessous / sous.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-032',
    subject: 'anglais',
    title: 'Prepositions : next to',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Que veut dire cette préposition ?',
    prompt: 'Que veut dire « next to » dans « The school is next to the park » ?',
    options: [
      { id: 'a', text: 'Loin de', isCorrect: false },
      { id: 'b', text: 'À côté de', isCorrect: true },
      { id: 'c', text: 'En face de', isCorrect: false },
    ],
    correctAnswer: 'À côté de',
    explanation: '« Next to » = à côté de. L\'école est à côté du parc.',
    hint: '« Next » = suivant / à côté → « next to » = à côté de.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-033',
    subject: 'anglais',
    title: 'Prepositions : between',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Que veut dire cette préposition ?',
    prompt: 'Que veut dire « between » dans « The shop is between the bank and the café » ?',
    options: [
      { id: 'a', text: 'À côté de', isCorrect: false },
      { id: 'b', text: 'Entre', isCorrect: true },
      { id: 'c', text: 'En face de', isCorrect: false },
    ],
    correctAnswer: 'Entre',
    explanation: '« Between » = entre (deux choses). La boutique est entre la banque et le café.',
    hint: '« Between » = entre deux points.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-034',
    subject: 'anglais',
    title: 'Prepositions : behind / in front of',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition.',
    prompt: 'Complète : « The teacher is ___ the board. » (devant le tableau)',
    options: [
      { id: 'a', text: 'behind', isCorrect: false },
      { id: 'b', text: 'in front of', isCorrect: true },
      { id: 'c', text: 'under', isCorrect: false },
    ],
    correctAnswer: 'in front of',
    explanation: '« In front of » = devant. « Behind » = derrière.',
    hint: '« In front of » = devant. « Behind » = derrière.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-035',
    subject: 'anglais',
    title: 'Prepositions of time : in / on / at',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition de temps.',
    prompt: 'Complète : « My birthday is ___ July. »',
    options: [
      { id: 'a', text: 'on', isCorrect: false },
      { id: 'b', text: 'in', isCorrect: true },
      { id: 'c', text: 'at', isCorrect: false },
    ],
    correctAnswer: 'in',
    explanation: '« In » + mois/année/saison. « On » + jour/date. « At » + heure.',
    hint: '« In » = dans un mois / une année / une saison.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-036',
    subject: 'anglais',
    title: 'Prepositions of time : on',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition de temps.',
    prompt: 'Complète : « I go to the cinema ___ Saturdays. »',
    options: [
      { id: 'a', text: 'in', isCorrect: false },
      { id: 'b', text: 'on', isCorrect: true },
      { id: 'c', text: 'at', isCorrect: false },
    ],
    correctAnswer: 'on',
    explanation: '« On » + jour de la semaine. « On Saturdays » = le samedi (habitude).',
    hint: '« On » = avec les jours de la semaine.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-037',
    subject: 'anglais',
    title: 'Prepositions of time : at',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition de temps.',
    prompt: 'Complète : « School starts ___ 8 o\'clock. »',
    options: [
      { id: 'a', text: 'in', isCorrect: false },
      { id: 'b', text: 'on', isCorrect: false },
      { id: 'c', text: 'at', isCorrect: true },
    ],
    correctAnswer: 'at',
    explanation: '« At » + heure précise. « At 8 o\'clock » = à 8 heures.',
    hint: '« At » = avec une heure précise.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-038',
    subject: 'anglais',
    title: 'Prepositions : opposite',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'prepositions',
    format: 'qcm',
    instructions: 'Que veut dire cette préposition ?',
    prompt: 'Que veut dire « opposite » dans « The bakery is opposite the school » ?',
    options: [
      { id: 'a', text: 'À côté de', isCorrect: false },
      { id: 'b', text: 'En face de', isCorrect: true },
      { id: 'c', text: 'Loin de', isCorrect: false },
    ],
    correctAnswer: 'En face de',
    explanation: '« Opposite » = en face de. La boulangerie est en face de l\'école.',
    hint: '« Opposite » = de l\'autre côté, en face.',
    tags: ['cm1', 'anglais', 'grammaire', 'prepositions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
