import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm1VocHobbiesExercises: EnglishExercise[] = [
  {
    id: 'en-cm1-voc-014',
    subject: 'anglais',
    title: 'Hobbies : skateboarding',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « skateboarding » en français ?',
    options: [
      { id: 'a', text: 'Le surf', isCorrect: false },
      { id: 'b', text: 'Le skateboard / faire du skate', isCorrect: true },
      { id: 'c', text: 'Le snowboard', isCorrect: false },
    ],
    correctAnswer: 'Le skateboard / faire du skate',
    explanation: '« Skateboarding » = faire du skateboard. Ce sport vient des États-Unis.',
    hint: 'On pratique ce sport sur une planche à roulettes.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-015',
    subject: 'anglais',
    title: 'Hobbies : cycling',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « cycling » en français ?',
    options: [
      { id: 'a', text: 'Faire du roller', isCorrect: false },
      { id: 'b', text: 'Faire du vélo', isCorrect: true },
      { id: 'c', text: 'Faire de la course à pied', isCorrect: false },
    ],
    correctAnswer: 'Faire du vélo',
    explanation: '« Cycling » = faire du vélo. « Cycle » = vélo (en anglais britannique).',
    hint: '« Bicycle » → « cycle » → « cycling ».',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-016',
    subject: 'anglais',
    title: 'Hobbies : photography',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « photography » en français ?',
    options: [
      { id: 'a', text: 'La peinture', isCorrect: false },
      { id: 'b', text: 'La photographie', isCorrect: true },
      { id: 'c', text: 'Le dessin', isCorrect: false },
    ],
    correctAnswer: 'La photographie',
    explanation: '« Photography » = la photographie. Même racine grecque que le français !',
    hint: 'Ce mot ressemble beaucoup au mot français.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-017',
    subject: 'anglais',
    title: 'Hobbies : gardening',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « gardening » en français ?',
    options: [
      { id: 'a', text: 'La cuisine', isCorrect: false },
      { id: 'b', text: 'Le jardinage', isCorrect: true },
      { id: 'c', text: 'La décoration', isCorrect: false },
    ],
    correctAnswer: 'Le jardinage',
    explanation: '« Gardening » = le jardinage. « Garden » = jardin.',
    hint: '« Garden » = jardin → « gardening » = jardinage.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-018',
    subject: 'anglais',
    title: 'Hobbies : playing an instrument',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « I play the guitar » en français ?',
    options: [
      { id: 'a', text: 'J\'écoute de la guitare.', isCorrect: false },
      { id: 'b', text: 'Je joue de la guitare.', isCorrect: true },
      { id: 'c', text: 'J\'achète une guitare.', isCorrect: false },
    ],
    correctAnswer: 'Je joue de la guitare.',
    explanation: '« I play the guitar » = je joue de la guitare. On dit « play the + instrument ».',
    hint: '« Play the piano / guitar / violin » = jouer du piano / de la guitare / du violon.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-019',
    subject: 'anglais',
    title: 'Hobbies : video games',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « I love playing video games » en français ?',
    options: [
      { id: 'a', text: 'J\'aime regarder des vidéos.', isCorrect: false },
      { id: 'b', text: 'J\'adore jouer aux jeux vidéo.', isCorrect: true },
      { id: 'c', text: 'J\'aime faire du sport.', isCorrect: false },
    ],
    correctAnswer: 'J\'adore jouer aux jeux vidéo.',
    explanation: '« Love » = adorer. « Playing video games » = jouer aux jeux vidéo.',
    hint: '« Love » exprime une préférence encore plus forte que « like ».',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-020',
    subject: 'anglais',
    title: 'Hobbies : going to the cinema',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « I like going to the cinema » en français ?',
    options: [
      { id: 'a', text: 'J\'aime regarder la télévision.', isCorrect: false },
      { id: 'b', text: 'J\'aime aller au cinéma.', isCorrect: true },
      { id: 'c', text: 'J\'aime aller au théâtre.', isCorrect: false },
    ],
    correctAnswer: 'J\'aime aller au cinéma.',
    explanation: '« Cinema » = cinéma (même mot !). « Going to the cinema » = aller au cinéma.',
    hint: '« Cinema » est le même mot en français.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-021',
    subject: 'anglais',
    title: 'Hobbies : sport vocabulary',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « basketball » en français ?',
    options: [
      { id: 'a', text: 'Le football', isCorrect: false },
      { id: 'b', text: 'Le basket-ball', isCorrect: true },
      { id: 'c', text: 'Le volleyball', isCorrect: false },
    ],
    correctAnswer: 'Le basket-ball',
    explanation: '« Basketball » = basket-ball. Ce mot est emprunté à l\'américain — même mot en français !',
    hint: '« Basket » + « ball » = panier + balle.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-022',
    subject: 'anglais',
    title: 'Hobbies : hate vs love',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « I hate tidying my room » en français ?',
    options: [
      { id: 'a', text: 'J\'adore ranger ma chambre.', isCorrect: false },
      { id: 'b', text: 'Je déteste ranger ma chambre.', isCorrect: true },
      { id: 'c', text: 'J\'aime ranger ma chambre.', isCorrect: false },
    ],
    correctAnswer: 'Je déteste ranger ma chambre.',
    explanation: '« Hate » = détester (contraire de « love »). « Tidying » = ranger.',
    hint: '« Hate » est le contraire de « love ».',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-023',
    subject: 'anglais',
    title: 'Hobbies : frequency adverbs',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « often » dans « I often play football » ?',
    options: [
      { id: 'a', text: 'Jamais', isCorrect: false },
      { id: 'b', text: 'Souvent', isCorrect: true },
      { id: 'c', text: 'Rarement', isCorrect: false },
    ],
    correctAnswer: 'Souvent',
    explanation: '« Often » = souvent. Ordre : always > usually > often > sometimes > rarely > never.',
    hint: '« Often » = fréquemment / souvent.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-024',
    subject: 'anglais',
    title: 'Hobbies : free time',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « free time » en français ?',
    options: [
      { id: 'a', text: 'L\'heure libre / temps libre', isCorrect: true },
      { id: 'b', text: 'La récréation seulement', isCorrect: false },
      { id: 'c', text: 'Les vacances', isCorrect: false },
    ],
    correctAnswer: 'L\'heure libre / temps libre',
    explanation: '« Free time » = temps libre. « Free » = libre. C\'est le temps sans école ni obligations.',
    hint: '« Free » = libre. « Time » = temps.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-025',
    subject: 'anglais',
    title: 'Hobbies : at the weekend',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « at the weekend » en français ?',
    options: [
      { id: 'a', text: 'En semaine', isCorrect: false },
      { id: 'b', text: 'Le week-end', isCorrect: true },
      { id: 'c', text: 'Pendant les vacances', isCorrect: false },
    ],
    correctAnswer: 'Le week-end',
    explanation: '« At the weekend » = le week-end (samedi et dimanche).',
    hint: '« Weekend » = week + end = fin de semaine.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-026',
    subject: 'anglais',
    title: 'Hobbies : outdoor activities',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « outdoor activities » en français ?',
    options: [
      { id: 'a', text: 'Les activités en salle', isCorrect: false },
      { id: 'b', text: 'Les activités en plein air / dehors', isCorrect: true },
      { id: 'c', text: 'Les activités scolaires', isCorrect: false },
    ],
    correctAnswer: 'Les activités en plein air / dehors',
    explanation: '« Outdoor » = en plein air / extérieur. « Indoor » = à l\'intérieur.',
    hint: '« Out » = dehors. « Door » = porte → outdoor = hors de la porte.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-027',
    subject: 'anglais',
    title: 'Hobbies : board games',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « board games » en français ?',
    options: [
      { id: 'a', text: 'Les jeux vidéo', isCorrect: false },
      { id: 'b', text: 'Les jeux de société', isCorrect: true },
      { id: 'c', text: 'Les sports collectifs', isCorrect: false },
    ],
    correctAnswer: 'Les jeux de société',
    explanation: '« Board games » = jeux de société (échecs, dames, Monopoly…). « Board » = plateau.',
    hint: '« Board » = plateau de jeu.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-028',
    subject: 'anglais',
    title: 'Hobbies : le bon mot',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'hobbies',
    format: 'qcm',
    instructions: 'Choisis le bon mot anglais.',
    prompt: 'Comment dit-on « faire du vélo » en anglais ?',
    options: [
      { id: 'a', text: 'swimming', isCorrect: false },
      { id: 'b', text: 'cycling', isCorrect: true },
      { id: 'c', text: 'skateboarding', isCorrect: false },
    ],
    correctAnswer: 'cycling',
    explanation: '« Cycling » = faire du vélo. « Swimming » = nager. « Skateboarding » = faire du skate.',
    hint: '« Bicycle » → « cycle » → « cycling ».',
    tags: ['cm1', 'anglais', 'vocabulaire', 'hobbies', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
