import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm1CommExercises: EnglishExercise[] = [
  {
    id: 'en-cm1-comp-001',
    subject: 'anglais',
    title: 'Dialogue : asking for directions',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « Excuse me, where is the library? »\n— « Turn left at the traffic lights. »\nQue faut-il faire ?',
    options: [
      { id: 'a', text: 'Tourner à droite aux feux', isCorrect: false },
      { id: 'b', text: 'Tourner à gauche aux feux', isCorrect: true },
      { id: 'c', text: 'Aller tout droit aux feux', isCorrect: false },
    ],
    correctAnswer: 'Tourner à gauche aux feux',
    explanation: '« Turn left » = tourner à gauche. « Traffic lights » = feux de circulation.',
    hint: '« Left » = gauche. « Right » = droite.',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-002',
    subject: 'anglais',
    title: 'Dialogue : giving directions',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Que veut dire « Go straight ahead » en français ?',
    options: [
      { id: 'a', text: 'Tourne à droite', isCorrect: false },
      { id: 'b', text: 'Va tout droit', isCorrect: true },
      { id: 'c', text: 'Arrête-toi', isCorrect: false },
    ],
    correctAnswer: 'Va tout droit',
    explanation: '« Go straight ahead » = va tout droit. « Ahead » = en avant / devant soi.',
    hint: '« Straight » = droit. « Ahead » = devant.',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-003',
    subject: 'anglais',
    title: 'Dialogue : at the school office',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « I\'m sorry, I don\'t know the answer. »\nQue veut dire « I\'m sorry » ?',
    options: [
      { id: 'a', text: 'Je ne suis pas d\'accord.', isCorrect: false },
      { id: 'b', text: 'Je suis désolé(e) / pardon.', isCorrect: true },
      { id: 'c', text: 'Je suis content(e).', isCorrect: false },
    ],
    correctAnswer: 'Je suis désolé(e) / pardon.',
    explanation: '« I\'m sorry » = je suis désolé / pardon. On l\'utilise pour s\'excuser.',
    hint: '« Sorry » = désolé(e). On l\'utilise pour s\'excuser.',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-004',
    subject: 'anglais',
    title: 'Dialogue : expressing ability',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I can speak English and French » en français ?',
    options: [
      { id: 'a', text: 'J\'aime parler anglais et français.', isCorrect: false },
      { id: 'b', text: 'Je sais parler anglais et français.', isCorrect: true },
      { id: 'c', text: 'Je veux parler anglais et français.', isCorrect: false },
    ],
    correctAnswer: 'Je sais parler anglais et français.',
    explanation: '« Can » = pouvoir / savoir. « I can speak » = je sais parler / je peux parler.',
    hint: '« Can » = être capable de.',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-005',
    subject: 'anglais',
    title: 'Dialogue : making suggestions',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « Let\'s go to the park! » en français ?',
    options: [
      { id: 'a', text: 'Est-ce qu\'on peut aller au parc ?', isCorrect: false },
      { id: 'b', text: 'Allons au parc !', isCorrect: true },
      { id: 'c', text: 'Je vais au parc.', isCorrect: false },
    ],
    correctAnswer: 'Allons au parc !',
    explanation: '« Let\'s + verbe » = allons… / si on… ! C\'est une suggestion.',
    hint: '« Let\'s » = let us → allons / si on…',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-006',
    subject: 'anglais',
    title: 'Dialogue : at the shop',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « Can I help you? »\n— « Yes, I\'d like a sandwich, please. »\nQue commande la personne ?',
    options: [
      { id: 'a', text: 'Une pizza', isCorrect: false },
      { id: 'b', text: 'Un sandwich', isCorrect: true },
      { id: 'c', text: 'Un jus d\'orange', isCorrect: false },
    ],
    correctAnswer: 'Un sandwich',
    explanation: '« I\'d like » = je voudrais (forme polie). On commande « a sandwich ».',
    hint: '« I\'d like » = je voudrais (poli).',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-007',
    subject: 'anglais',
    title: 'Dialogue : congratulations',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Ton ami dit « Well done! ». Que veut-il dire ?',
    options: [
      { id: 'a', text: 'C\'est dommage !', isCorrect: false },
      { id: 'b', text: 'Bravo ! Félicitations !', isCorrect: true },
      { id: 'c', text: 'Essaie encore !', isCorrect: false },
    ],
    correctAnswer: 'Bravo ! Félicitations !',
    explanation: '« Well done! » = Bravo ! / Félicitations ! On le dit quand quelqu\'un a bien réussi.',
    hint: '« Well » = bien. « Done » = fait / accompli.',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-008',
    subject: 'anglais',
    title: 'Dialogue : telephone',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce début de dialogue téléphonique.',
    prompt: '— « Hello, can I speak to Tom, please? »\nQue demande la personne ?',
    options: [
      { id: 'a', text: 'Elle demande si Tom est là.', isCorrect: false },
      { id: 'b', text: 'Elle demande à parler à Tom.', isCorrect: true },
      { id: 'c', text: 'Elle demande le numéro de Tom.', isCorrect: false },
    ],
    correctAnswer: 'Elle demande à parler à Tom.',
    explanation: '« Can I speak to… ? » = Est-ce que je peux parler à… ? C\'est la formule pour téléphoner.',
    hint: '« Can I speak to » = formule téléphonique.',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-009',
    subject: 'anglais',
    title: 'Dialogue : what\'s wrong?',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « What\'s wrong? » en français ?',
    options: [
      { id: 'a', text: 'Qu\'est-ce que tu as trouvé ?', isCorrect: false },
      { id: 'b', text: 'Qu\'est-ce qui ne va pas ? / Ça ne va pas ?', isCorrect: true },
      { id: 'c', text: 'Tu as tort ?', isCorrect: false },
    ],
    correctAnswer: 'Qu\'est-ce qui ne va pas ? / Ça ne va pas ?',
    explanation: '« What\'s wrong? » = Qu\'est-ce qui ne va pas ? On le dit quand quelqu\'un semble triste ou blessé.',
    hint: '« Wrong » = incorrect / qui ne va pas.',
    tags: ['cm1', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
