import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm1CompTextesExercises: EnglishExercise[] = [
  {
    id: 'en-cm1-comp-010',
    subject: 'anglais',
    title: 'Compréhension : Tom\'s morning',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte puis réponds.',
    prompt: '« Tom wakes up at half past seven. He has cereal and orange juice for breakfast. Then he walks to school with his sister. »\nA quelle heure Tom se lève-t-il ?',
    options: [
      { id: 'a', text: 'À 7h', isCorrect: false },
      { id: 'b', text: 'À 7h30', isCorrect: true },
      { id: 'c', text: 'À 8h', isCorrect: false },
    ],
    correctAnswer: 'À 7h30',
    explanation: '« Half past seven » = 7h30. « Half past » = et demie.',
    hint: '« Half past seven » = sept heures et demie.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-011',
    subject: 'anglais',
    title: 'Compréhension : Tom\'s morning (2)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Utilise le texte précédent.',
    prompt: '« Tom wakes up at half past seven. He has cereal and orange juice for breakfast. Then he walks to school with his sister. »\nComment Tom va-t-il à l\'école ?',
    options: [
      { id: 'a', text: 'En bus', isCorrect: false },
      { id: 'b', text: 'À pied', isCorrect: true },
      { id: 'c', text: 'En voiture avec ses parents', isCorrect: false },
    ],
    correctAnswer: 'À pied',
    explanation: '« He walks to school » = il marche jusqu\'à l\'école = il y va à pied.',
    hint: '« Walks » = marche.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-012',
    subject: 'anglais',
    title: 'Compréhension : Emma\'s weekend',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte puis réponds.',
    prompt: '« Last Saturday, Emma went to the swimming pool with her dad. She swam for one hour. In the afternoon, she read a book and watched TV. »\nQu\'a fait Emma le matin ?',
    options: [
      { id: 'a', text: 'Elle a regardé la télé.', isCorrect: false },
      { id: 'b', text: 'Elle est allée à la piscine.', isCorrect: true },
      { id: 'c', text: 'Elle a lu un livre.', isCorrect: false },
    ],
    correctAnswer: 'Elle est allée à la piscine.',
    explanation: '« Went to the swimming pool » = est allée à la piscine. « Last Saturday » = samedi dernier.',
    hint: '« Swimming pool » = piscine.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-013',
    subject: 'anglais',
    title: 'Compréhension : Emma\'s weekend (2)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Utilise le texte précédent.',
    prompt: '« Last Saturday, Emma went to the swimming pool with her dad. She swam for one hour. In the afternoon, she read a book and watched TV. »\nQue fait Emma l\'après-midi ?',
    options: [
      { id: 'a', text: 'Elle est retournée à la piscine.', isCorrect: false },
      { id: 'b', text: 'Elle a lu et regardé la télé.', isCorrect: true },
      { id: 'c', text: 'Elle a joué dans le jardin.', isCorrect: false },
    ],
    correctAnswer: 'Elle a lu et regardé la télé.',
    explanation: '« Read a book and watched TV » = a lu un livre et a regardé la télé.',
    hint: '« Read » = lire. « Watched TV » = a regardé la télé.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-014',
    subject: 'anglais',
    title: 'Compréhension : The village',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte puis réponds.',
    prompt: '« My village is small but there are many things to do. There is a park, a library and a small supermarket. There isn\'t a cinema, but there is a community centre. »\nY a-t-il un cinéma dans le village ?',
    options: [
      { id: 'a', text: 'Oui, il y a un cinéma.', isCorrect: false },
      { id: 'b', text: 'Non, il n\'y a pas de cinéma.', isCorrect: true },
      { id: 'c', text: 'Le texte ne le dit pas.', isCorrect: false },
    ],
    correctAnswer: 'Non, il n\'y a pas de cinéma.',
    explanation: '« There isn\'t a cinema » = il n\'y a pas de cinéma.',
    hint: '« There isn\'t » = il n\'y a pas.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-015',
    subject: 'anglais',
    title: 'Compréhension : The village (2)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Utilise le texte précédent sur le village.',
    prompt: 'Quels lieux sont mentionnés dans le village ? (plusieurs bonnes réponses possibles — choisis la liste correcte)',
    options: [
      { id: 'a', text: 'Un parc, une bibliothèque, un cinéma', isCorrect: false },
      { id: 'b', text: 'Un parc, une bibliothèque, un supermarché, un centre communautaire', isCorrect: true },
      { id: 'c', text: 'Un parc, une école, un supermarché', isCorrect: false },
    ],
    correctAnswer: 'Un parc, une bibliothèque, un supermarché, un centre communautaire',
    explanation: 'Park, library, supermarket, community centre = les 4 lieux mentionnés.',
    hint: 'Compte les lieux : there is a park, a library, a supermarket, a community centre.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-016',
    subject: 'anglais',
    title: 'Compréhension : Jack\'s pet',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte puis réponds.',
    prompt: '« Jack has got a dog called Max. Max is big and brown. He loves running in the park. Every morning, Jack takes Max for a walk before school. »\nDe quelle couleur est Max ?',
    options: [
      { id: 'a', text: 'Noir', isCorrect: false },
      { id: 'b', text: 'Marron', isCorrect: true },
      { id: 'c', text: 'Blanc', isCorrect: false },
    ],
    correctAnswer: 'Marron',
    explanation: '« Brown » = marron. « Big and brown » = grand et marron.',
    hint: '« Brown » = marron.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-017',
    subject: 'anglais',
    title: 'Compréhension : Jack\'s pet (2)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Utilise le texte sur Jack et Max.',
    prompt: 'Quand Jack promène-t-il Max ?',
    options: [
      { id: 'a', text: 'Le soir après l\'école', isCorrect: false },
      { id: 'b', text: 'Chaque matin avant l\'école', isCorrect: true },
      { id: 'c', text: 'Le week-end uniquement', isCorrect: false },
    ],
    correctAnswer: 'Chaque matin avant l\'école',
    explanation: '« Every morning before school » = chaque matin avant l\'école.',
    hint: '« Every morning » = chaque matin. « Before school » = avant l\'école.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-018',
    subject: 'anglais',
    title: 'Compréhension : Holiday postcard',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis cette carte postale.',
    prompt: '« Dear Mum, I am in London! The weather is cloudy but I am having a great time. Yesterday I visited the British Museum and we saw Big Ben. Tomorrow we are going shopping. Love, Clara »\nOù est Clara ?',
    options: [
      { id: 'a', text: 'À Paris', isCorrect: false },
      { id: 'b', text: 'À Londres', isCorrect: true },
      { id: 'c', text: 'À New York', isCorrect: false },
    ],
    correctAnswer: 'À Londres',
    explanation: '« I am in London » = je suis à Londres.',
    hint: '« London » = Londres.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-019',
    subject: 'anglais',
    title: 'Compréhension : Holiday postcard (2)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Utilise la carte postale de Clara.',
    prompt: 'Qu\'a fait Clara hier ?',
    options: [
      { id: 'a', text: 'Elle est allée faire du shopping.', isCorrect: false },
      { id: 'b', text: 'Elle a visité le British Museum.', isCorrect: true },
      { id: 'c', text: 'Elle a vu un spectacle.', isCorrect: false },
    ],
    correctAnswer: 'Elle a visité le British Museum.',
    explanation: '« Yesterday I visited the British Museum » = hier j\'ai visité le British Museum.',
    hint: '« Yesterday » = hier.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-020',
    subject: 'anglais',
    title: 'Compréhension : Léa\'s routine',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte.',
    prompt: '« Léa usually gets up at 7 o\'clock. She never eats breakfast at home because she isn\'t hungry in the morning. She always has lunch at school. After school, she often goes to her dance class. »\nOù Léa mange-t-elle le déjeuner ?',
    options: [
      { id: 'a', text: 'À la maison', isCorrect: false },
      { id: 'b', text: 'À l\'école', isCorrect: true },
      { id: 'c', text: 'Chez sa grand-mère', isCorrect: false },
    ],
    correctAnswer: 'À l\'école',
    explanation: '« She always has lunch at school » = elle déjeune toujours à l\'école.',
    hint: '« Has lunch » = déjeune. « At school » = à l\'école.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-021',
    subject: 'anglais',
    title: 'Compréhension : Léa\'s routine (2)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Utilise le texte sur Léa.',
    prompt: 'Pourquoi Léa ne prend-elle pas de petit-déjeuner à la maison ?',
    options: [
      { id: 'a', text: 'Elle n\'a pas le temps.', isCorrect: false },
      { id: 'b', text: 'Elle n\'a pas faim le matin.', isCorrect: true },
      { id: 'c', text: 'Il n\'y a rien à manger chez elle.', isCorrect: false },
    ],
    correctAnswer: 'Elle n\'a pas faim le matin.',
    explanation: '« She isn\'t hungry in the morning » = elle n\'a pas faim le matin.',
    hint: '« Hungry » = qui a faim.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-022',
    subject: 'anglais',
    title: 'Compréhension : The weather',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce bulletin météo.',
    prompt: '« It was cold and rainy on Monday. On Tuesday, the sun came out and it was warm. On Wednesday, it is cloudy but dry. »\nQuel temps faisait-il lundi ?',
    options: [
      { id: 'a', text: 'Chaud et ensoleillé', isCorrect: false },
      { id: 'b', text: 'Froid et pluvieux', isCorrect: true },
      { id: 'c', text: 'Nuageux et sec', isCorrect: false },
    ],
    correctAnswer: 'Froid et pluvieux',
    explanation: '« Cold and rainy » = froid et pluvieux. « On Monday » = lundi.',
    hint: '« Rainy » = pluvieux. « Cold » = froid.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-023',
    subject: 'anglais',
    title: 'Compréhension : Lucas and sport',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte.',
    prompt: '« Lucas loves sport. He plays basketball twice a week with his school team. He also goes swimming on Sundays. His favourite sport is basketball but he is also a good swimmer. »\nCombien de fois par semaine Lucas joue-t-il au basket ?',
    options: [
      { id: 'a', text: 'Une fois par semaine', isCorrect: false },
      { id: 'b', text: 'Deux fois par semaine', isCorrect: true },
      { id: 'c', text: 'Trois fois par semaine', isCorrect: false },
    ],
    correctAnswer: 'Deux fois par semaine',
    explanation: '« Twice a week » = deux fois par semaine.',
    hint: '« Twice » = deux fois.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-024',
    subject: 'anglais',
    title: 'Compréhension : Lucas and sport (2)',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Utilise le texte sur Lucas.',
    prompt: 'Quel est le sport préféré de Lucas ?',
    options: [
      { id: 'a', text: 'La natation', isCorrect: false },
      { id: 'b', text: 'Le basketball', isCorrect: true },
      { id: 'c', text: 'Le football', isCorrect: false },
    ],
    correctAnswer: 'Le basketball',
    explanation: '« His favourite sport is basketball » = son sport préféré est le basketball.',
    hint: '« Favourite » = préféré(e).',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-025',
    subject: 'anglais',
    title: 'Compréhension : The school trip',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte.',
    prompt: '« Our class went on a school trip last Thursday. We visited a farm and saw many animals: cows, horses and chickens. We also made butter! It was a fantastic day. »\nQu\'ont fait les élèves lors de cette sortie ?',
    options: [
      { id: 'a', text: 'Ils ont visité un musée.', isCorrect: false },
      { id: 'b', text: 'Ils ont visité une ferme et fabriqué du beurre.', isCorrect: true },
      { id: 'c', text: 'Ils ont été au zoo.', isCorrect: false },
    ],
    correctAnswer: 'Ils ont visité une ferme et fabriqué du beurre.',
    explanation: '« Visited a farm » = visité une ferme. « Made butter » = fabriqué du beurre.',
    hint: '« Farm » = ferme. « Made butter » = fabriqué du beurre.',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-comp-026',
    subject: 'anglais',
    title: 'Compréhension : vrai ou faux',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'comprehension',
    subskill: 'reading',
    format: 'qcm',
    instructions: 'Lis ce texte et dis si c\'est vrai ou faux.',
    prompt: '« Mia has got two cats and a goldfish. She feeds them every day. Her cats are called Coco and Lola. Her goldfish is called Bubble. »\nVrai ou faux : Mia a trois chats.',
    options: [
      { id: 'a', text: 'Vrai', isCorrect: false },
      { id: 'b', text: 'Faux', isCorrect: true },
      { id: 'c', text: 'Le texte ne le dit pas', isCorrect: false },
    ],
    correctAnswer: 'Faux',
    explanation: 'Mia a deux chats (« two cats »), pas trois. Elle a aussi un poisson rouge.',
    hint: '« Two cats » = deux chats (pas trois).',
    tags: ['cm1', 'anglais', 'comprehension', 'reading', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
  },
];
