import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm1GramPastSimpleIntroExercises: EnglishExercise[] = [
  {
    id: 'en-cm1-gram-039',
    subject: 'anglais',
    title: 'Past simple : yesterday',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « yesterday » en français ?',
    options: [
      { id: 'a', text: 'Aujourd\'hui', isCorrect: false },
      { id: 'b', text: 'Hier', isCorrect: true },
      { id: 'c', text: 'Demain', isCorrect: false },
    ],
    correctAnswer: 'Hier',
    explanation: '« Yesterday » = hier. Marqueur de temps qui accompagne souvent le past simple.',
    hint: 'Le jour avant aujourd\'hui.',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-040',
    subject: 'anglais',
    title: 'Past simple : last week',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « last week » en français ?',
    options: [
      { id: 'a', text: 'La semaine prochaine', isCorrect: false },
      { id: 'b', text: 'La semaine dernière', isCorrect: true },
      { id: 'c', text: 'Cette semaine', isCorrect: false },
    ],
    correctAnswer: 'La semaine dernière',
    explanation: '« Last week » = la semaine dernière. On dit aussi « last Saturday », « last month »…',
    hint: '« Last » + période = la … dernière.',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-041',
    subject: 'anglais',
    title: 'Past simple régulier : -ed',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I played football yesterday » en français ?',
    options: [
      { id: 'a', text: 'Je joue au foot aujourd\'hui.', isCorrect: false },
      { id: 'b', text: 'J\'ai joué au foot hier.', isCorrect: true },
      { id: 'c', text: 'Je vais jouer au foot demain.', isCorrect: false },
    ],
    correctAnswer: 'J\'ai joué au foot hier.',
    explanation: '« Played » = past simple de « play ». On ajoute -ed pour les verbes réguliers.',
    hint: '« Played » = play + -ed = passé de play.',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-042',
    subject: 'anglais',
    title: 'Past simple : She walked',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « She walked to school this morning » en français ?',
    options: [
      { id: 'a', text: 'Elle marche vers l\'école ce matin.', isCorrect: false },
      { id: 'b', text: 'Elle a marché jusqu\'à l\'école ce matin.', isCorrect: true },
      { id: 'c', text: 'Elle va marcher jusqu\'à l\'école.', isCorrect: false },
    ],
    correctAnswer: 'Elle a marché jusqu\'à l\'école ce matin.',
    explanation: '« Walked » = past simple de « walk ». Elle a marché (action terminée).',
    hint: '« Walked » = walk + -ed = a marché.',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-043',
    subject: 'anglais',
    title: 'Past simple : They watched',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « They watched a film last night » en français ?',
    options: [
      { id: 'a', text: 'Ils regardent un film ce soir.', isCorrect: false },
      { id: 'b', text: 'Ils ont regardé un film hier soir.', isCorrect: true },
      { id: 'c', text: 'Ils vont regarder un film demain.', isCorrect: false },
    ],
    correctAnswer: 'Ils ont regardé un film hier soir.',
    explanation: '« Watched » = past simple de « watch ». « Last night » = hier soir.',
    hint: '« Last night » = hier soir. « Watched » = a regardé.',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-044',
    subject: 'anglais',
    title: 'Past simple : didn\'t',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « He didn\'t come to school yesterday » en français ?',
    options: [
      { id: 'a', text: 'Il est venu à l\'école hier.', isCorrect: false },
      { id: 'b', text: 'Il n\'est pas venu à l\'école hier.', isCorrect: true },
      { id: 'c', text: 'Il va venir à l\'école demain.', isCorrect: false },
    ],
    correctAnswer: 'Il n\'est pas venu à l\'école hier.',
    explanation: '« Didn\'t come » = n\'est pas venu. La négation au past simple = didn\'t + verbe base.',
    hint: '« Didn\'t » = did not = négation du passé.',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-045',
    subject: 'anglais',
    title: 'Past simple : Did you...?',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « Did you see the match? » en français ?',
    options: [
      { id: 'a', text: 'Tu vas regarder le match ?', isCorrect: false },
      { id: 'b', text: 'Tu as vu le match ?', isCorrect: true },
      { id: 'c', text: 'Tu regardes le match ?', isCorrect: false },
    ],
    correctAnswer: 'Tu as vu le match ?',
    explanation: '« Did you…? » = est-ce que tu as… ? Question au past simple.',
    hint: '« Did you » = est-ce que tu as (passé) ?',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-046',
    subject: 'anglais',
    title: 'Past simple : I didn\'t like',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I didn\'t like the film » en français ?',
    options: [
      { id: 'a', text: 'J\'ai aimé le film.', isCorrect: false },
      { id: 'b', text: 'Je n\'ai pas aimé le film.', isCorrect: true },
      { id: 'c', text: 'Je n\'ai pas vu le film.', isCorrect: false },
    ],
    correctAnswer: 'Je n\'ai pas aimé le film.',
    explanation: '« Didn\'t like » = n\'ai pas aimé. Négation : didn\'t + verbe infinitif.',
    hint: 'Avec didn\'t, le verbe reste à l\'infinitif (didn\'t like, pas didn\'t liked).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-047',
    subject: 'anglais',
    title: 'Past simple irrégulier : went',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « We went to the cinema last Saturday » en français ?',
    options: [
      { id: 'a', text: 'Nous allons au cinéma samedi.', isCorrect: false },
      { id: 'b', text: 'Nous sommes allés au cinéma samedi dernier.', isCorrect: true },
      { id: 'c', text: 'Nous voudrions aller au cinéma.', isCorrect: false },
    ],
    correctAnswer: 'Nous sommes allés au cinéma samedi dernier.',
    explanation: '« Went » = past simple irrégulier de « go ». Go → went.',
    hint: '« Went » = past simple de « go » (irrégulier).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-048',
    subject: 'anglais',
    title: 'Past simple irrégulier : saw',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « She saw her friend in the park » en français ?',
    options: [
      { id: 'a', text: 'Elle voit son amie dans le parc.', isCorrect: false },
      { id: 'b', text: 'Elle a vu son amie dans le parc.', isCorrect: true },
      { id: 'c', text: 'Elle cherche son amie dans le parc.', isCorrect: false },
    ],
    correctAnswer: 'Elle a vu son amie dans le parc.',
    explanation: '« Saw » = past simple irrégulier de « see ». See → saw.',
    hint: '« Saw » = past simple de « see » (irrégulier).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-049',
    subject: 'anglais',
    title: 'Past simple irrégulier : ate',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « They ate pizza for dinner » en français ?',
    options: [
      { id: 'a', text: 'Ils mangent de la pizza pour dîner.', isCorrect: false },
      { id: 'b', text: 'Ils ont mangé de la pizza pour dîner.', isCorrect: true },
      { id: 'c', text: 'Ils voudraient manger de la pizza.', isCorrect: false },
    ],
    correctAnswer: 'Ils ont mangé de la pizza pour dîner.',
    explanation: '« Ate » = past simple irrégulier de « eat ». Eat → ate.',
    hint: '« Ate » = past simple de « eat » (irrégulier).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-050',
    subject: 'anglais',
    title: 'Past simple : was / were',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I was tired after school » en français ?',
    options: [
      { id: 'a', text: 'Je suis fatigué après l\'école.', isCorrect: false },
      { id: 'b', text: 'J\'étais fatigué après l\'école.', isCorrect: true },
      { id: 'c', text: 'Je serai fatigué après l\'école.', isCorrect: false },
    ],
    correctAnswer: 'J\'étais fatigué après l\'école.',
    explanation: '« Was » = past simple de « be » (I / he / she / it). « Tired » = fatigué.',
    hint: '« Was » = past simple de « am/is ».',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-051',
    subject: 'anglais',
    title: 'Past simple : were',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « We were happy on holiday » en français ?',
    options: [
      { id: 'a', text: 'Nous sommes heureux en vacances.', isCorrect: false },
      { id: 'b', text: 'Nous étions heureux en vacances.', isCorrect: true },
      { id: 'c', text: 'Nous serons heureux en vacances.', isCorrect: false },
    ],
    correctAnswer: 'Nous étions heureux en vacances.',
    explanation: '« Were » = past simple de « are » (you / we / they). « On holiday » = en vacances.',
    hint: '« Were » = past simple de « are ».',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-052',
    subject: 'anglais',
    title: 'Past simple : It was sunny',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « It was sunny last Sunday » en français ?',
    options: [
      { id: 'a', text: 'Il fait beau ce dimanche.', isCorrect: false },
      { id: 'b', text: 'Il faisait beau dimanche dernier.', isCorrect: true },
      { id: 'c', text: 'Il fera beau dimanche.', isCorrect: false },
    ],
    correctAnswer: 'Il faisait beau dimanche dernier.',
    explanation: '« It was sunny » = il faisait beau. « Last Sunday » = dimanche dernier.',
    hint: '« It was » = il faisait (météo passée).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-053',
    subject: 'anglais',
    title: 'Past simple : choisir la bonne forme',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « I ___ my homework last night. » (do)',
    options: [
      { id: 'a', text: 'do', isCorrect: false },
      { id: 'b', text: 'did', isCorrect: true },
      { id: 'c', text: 'done', isCorrect: false },
    ],
    correctAnswer: 'did',
    explanation: '« Last night » → passé → did (past simple de « do »). Do → did.',
    hint: '« Last night » = hier soir → passé. Do → did.',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-054',
    subject: 'anglais',
    title: 'Past simple : irrégulier had',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « He had a great holiday » en français ?',
    options: [
      { id: 'a', text: 'Il a de bonnes vacances.', isCorrect: false },
      { id: 'b', text: 'Il a passé de bonnes vacances.', isCorrect: true },
      { id: 'c', text: 'Il veut de bonnes vacances.', isCorrect: false },
    ],
    correctAnswer: 'Il a passé de bonnes vacances.',
    explanation: '« Had » = past simple irrégulier de « have ». Have → had.',
    hint: '« Had » = past simple de « have » (irrégulier).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-055',
    subject: 'anglais',
    title: 'Past simple : négation avec didn\'t',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne négation.',
    prompt: 'Comment dit-on « Je n\'ai pas joué au foot hier » en anglais ?',
    options: [
      { id: 'a', text: 'I didn\'t played football yesterday.', isCorrect: false },
      { id: 'b', text: 'I didn\'t play football yesterday.', isCorrect: true },
      { id: 'c', text: 'I not played football yesterday.', isCorrect: false },
    ],
    correctAnswer: 'I didn\'t play football yesterday.',
    explanation: 'Négation : didn\'t + verbe base (pas -ed !). « Didn\'t play », pas « didn\'t played ».',
    hint: 'Avec didn\'t : verbe à l\'infinitif (pas de -ed).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-056',
    subject: 'anglais',
    title: 'Past simple : révision globale',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'past-simple',
    format: 'qcm',
    instructions: 'Choisis la phrase correcte.',
    prompt: 'Laquelle de ces phrases est correcte ?',
    options: [
      { id: 'a', text: 'She goed to the park yesterday.', isCorrect: false },
      { id: 'b', text: 'She went to the park yesterday.', isCorrect: true },
      { id: 'c', text: 'She go to the park yesterday.', isCorrect: false },
    ],
    correctAnswer: 'She went to the park yesterday.',
    explanation: '« Go » est irrégulier → « went » (pas « goed »). « Yesterday » confirme le passé.',
    hint: '« Go » est irrégulier → went (pas goed).',
    tags: ['cm1', 'anglais', 'grammaire', 'past-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
