import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCm1GramCanCantExercises: EnglishExercise[] = [
  {
    id: 'en-cm1-gram-001',
    subject: 'anglais',
    title: 'Can : I can swim',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: 'Que veut dire « I can swim » en français ?',
    options: [
      { id: 'a', text: 'Je sais nager.', isCorrect: true },
      { id: 'b', text: 'Je ne sais pas nager.', isCorrect: false },
      { id: 'c', text: "J'aime nager.", isCorrect: false },
    ],
    correctAnswer: 'Je sais nager.',
    explanation: '« Can » = pouvoir / savoir. « I can swim » = Je sais nager.',
    hint: '« Can » exprime la capacité ou la permission.',
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-002',
    subject: 'anglais',
    title: "Can't : She can't fly",
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: "Que veut dire « She can't fly » en français ?",
    options: [
      { id: 'a', text: 'Elle peut voler.', isCorrect: false },
      { id: 'b', text: 'Elle ne peut pas voler.', isCorrect: true },
      { id: 'c', text: 'Elle aime voler.', isCorrect: false },
    ],
    correctAnswer: 'Elle ne peut pas voler.',
    explanation: "« Can't » = ne peut pas. « She can't fly » = Elle ne peut pas voler.",
    hint: "« Can't » est la forme négative de « can ».",
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-003',
    subject: 'anglais',
    title: 'Can : Birds can fly',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Choisis le bon mot pour compléter.',
    prompt: 'Complète : « Birds ___ fly. » (Les oiseaux peuvent voler.)',
    options: [
      { id: 'a', text: 'can', isCorrect: true },
      { id: 'b', text: "can't", isCorrect: false },
      { id: 'c', text: 'is', isCorrect: false },
    ],
    correctAnswer: 'can',
    explanation: 'Les oiseaux peuvent voler → on utilise « can » : Birds can fly.',
    hint: 'Les oiseaux volent → capacité → can.',
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: "Choisis can ou can't.", extraHint: 'Les oiseaux volent → can.' },
    }),
  },
  {
    id: 'en-cm1-gram-004',
    subject: 'anglais',
    title: "Can't : Fish can't climb",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Choisis le bon mot pour compléter.',
    prompt: "Complète : « Fish ___ climb trees. » (Les poissons ne peuvent pas grimper.)",
    options: [
      { id: 'a', text: 'can', isCorrect: false },
      { id: 'b', text: "can't", isCorrect: true },
      { id: 'c', text: 'are', isCorrect: false },
    ],
    correctAnswer: "can't",
    explanation: "Les poissons ne peuvent pas grimper → on utilise « can't ».",
    hint: "Impossible → can't.",
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-008',
    subject: 'anglais',
    title: 'Can : I can run',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: 'Que veut dire « I can run fast » en français ?',
    options: [
      { id: 'a', text: 'Je ne peux pas courir vite.', isCorrect: false },
      { id: 'b', text: 'Je cours souvent.', isCorrect: false },
      { id: 'c', text: 'Je peux courir vite.', isCorrect: true },
    ],
    correctAnswer: 'Je peux courir vite.',
    explanation: '« I can » = je peux. « Run fast » = courir vite.',
    hint: '« Can » = pouvoir.',
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-009',
    subject: 'anglais',
    title: "Can't : He can't speak",
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: "Que veut dire « He can't speak English » en français ?",
    options: [
      { id: 'a', text: 'Il parle anglais.', isCorrect: false },
      { id: 'b', text: 'Il ne parle pas anglais.', isCorrect: true },
      { id: 'c', text: "Il apprend l'anglais.", isCorrect: false },
    ],
    correctAnswer: 'Il ne parle pas anglais.',
    explanation: "« Can't » = ne peut pas. « He can't speak English » = Il ne parle pas anglais.",
    hint: "« Can't » = ne peut pas (forme négative).",
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-010',
    subject: 'anglais',
    title: 'Can : Can she dance?',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette question en français.',
    prompt: 'Que veut dire « Can she dance? » en français ?',
    options: [
      { id: 'a', text: 'Elle danse.', isCorrect: false },
      { id: 'b', text: 'Sait-elle danser ?', isCorrect: true },
      { id: 'c', text: 'Elle aime danser.', isCorrect: false },
    ],
    correctAnswer: 'Sait-elle danser ?',
    explanation: '« Can she... ? » = Sait-elle... ? / Peut-elle... ?',
    hint: '« Can » en question = Peut-elle ? / Sait-elle ?',
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
