import { cloneDefaultAdaptations } from '../../core/exercise-core.adaptations';
import type { EnglishExercise } from './english.types';

export const englishExercises: EnglishExercise[] = [

  // ══════════════════════════════════════════════════════════════════
  // CP — vocabulaire (10 exercices) — reconnaissance mot → traduction
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'en-cp-voc-001',
    subject: 'anglais',
    title: 'Couleur : red',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « red » en français ?',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: true },
      { id: 'b', text: 'Bleu', isCorrect: false },
      { id: 'c', text: 'Vert', isCorrect: false },
    ],
    correctAnswer: 'Rouge',
    explanation: '« Red » veut dire rouge en français.',
    hint: 'Pense à la couleur du feu.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-002',
    subject: 'anglais',
    title: 'Couleur : blue',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « blue » en français ?',
    options: [
      { id: 'a', text: 'Jaune', isCorrect: false },
      { id: 'b', text: 'Bleu', isCorrect: true },
      { id: 'c', text: 'Vert', isCorrect: false },
    ],
    correctAnswer: 'Bleu',
    explanation: '« Blue » veut dire bleu en français.',
    hint: 'Pense à la couleur du ciel.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-003',
    subject: 'anglais',
    title: 'Couleur : yellow',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « yellow » en français ?',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: false },
      { id: 'b', text: 'Orange', isCorrect: false },
      { id: 'c', text: 'Jaune', isCorrect: true },
    ],
    correctAnswer: 'Jaune',
    explanation: '« Yellow » veut dire jaune en français.',
    hint: 'Pense à la couleur du soleil.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-004',
    subject: 'anglais',
    title: 'Animal : cat',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a cat » en français ?',
    options: [
      { id: 'a', text: 'Un chien', isCorrect: false },
      { id: 'b', text: 'Un chat', isCorrect: true },
      { id: 'c', text: 'Un lapin', isCorrect: false },
    ],
    correctAnswer: 'Un chat',
    explanation: '« Cat » veut dire chat en français.',
    hint: 'Cet animal fait « miaou ».',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-005',
    subject: 'anglais',
    title: 'Animal : dog',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a dog » en français ?',
    options: [
      { id: 'a', text: 'Un chat', isCorrect: false },
      { id: 'b', text: 'Un chien', isCorrect: true },
      { id: 'c', text: 'Un oiseau', isCorrect: false },
    ],
    correctAnswer: 'Un chien',
    explanation: '« Dog » veut dire chien en français.',
    hint: 'Cet animal fait « ouaf ».',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-006',
    subject: 'anglais',
    title: 'Animal : fish',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a fish » en français ?',
    options: [
      { id: 'a', text: 'Un poisson', isCorrect: true },
      { id: 'b', text: 'Un cheval', isCorrect: false },
      { id: 'c', text: 'Un lapin', isCorrect: false },
    ],
    correctAnswer: 'Un poisson',
    explanation: '« Fish » veut dire poisson en français.',
    hint: 'Cet animal vit dans l\'eau.',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-007',
    subject: 'anglais',
    title: 'Nombre : five',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'nombres',
    format: 'qcm',
    instructions: 'Quel est ce nombre en chiffres ?',
    prompt: 'Combien vaut « five » en anglais ?',
    options: [
      { id: 'a', text: '3', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '« Five » veut dire 5 en français.',
    hint: 'Compte les doigts d\'une main.',
    tags: ['cp', 'anglais', 'vocabulaire', 'nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-008',
    subject: 'anglais',
    title: 'Nombre : three',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'nombres',
    format: 'qcm',
    instructions: 'Quel est le mot anglais pour ce nombre ?',
    prompt: 'Quel mot anglais correspond au chiffre 3 ?',
    options: [
      { id: 'a', text: 'two', isCorrect: false },
      { id: 'b', text: 'three', isCorrect: true },
      { id: 'c', text: 'four', isCorrect: false },
    ],
    correctAnswer: 'three',
    explanation: 'Le chiffre 3 se dit « three » en anglais.',
    hint: '1 = one, 2 = two, 3 = …',
    tags: ['cp', 'anglais', 'vocabulaire', 'nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-009',
    subject: 'anglais',
    title: 'Salutation : hello',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette salutation ?',
    prompt: 'Que veut dire « Hello » en français ?',
    options: [
      { id: 'a', text: 'Bonjour', isCorrect: true },
      { id: 'b', text: 'Au revoir', isCorrect: false },
      { id: 'c', text: 'Merci', isCorrect: false },
    ],
    correctAnswer: 'Bonjour',
    explanation: '« Hello » veut dire Bonjour en français.',
    hint: 'C\'est ce qu\'on dit en arrivant.',
    tags: ['cp', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-010',
    subject: 'anglais',
    title: 'Salutation : goodbye',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette salutation ?',
    prompt: 'Que veut dire « Goodbye » en français ?',
    options: [
      { id: 'a', text: 'Bonjour', isCorrect: false },
      { id: 'b', text: 'Merci', isCorrect: false },
      { id: 'c', text: 'Au revoir', isCorrect: true },
    ],
    correctAnswer: 'Au revoir',
    explanation: '« Goodbye » veut dire Au revoir en français.',
    hint: 'C\'est ce qu\'on dit en partant.',
    tags: ['cp', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

  // ══════════════════════════════════════════════════════════════════
  // CE1 — vocabulaire (12 exercices)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'en-ce1-voc-001',
    subject: 'anglais',
    title: 'Couleur : green',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « green » en français ?',
    options: [
      { id: 'a', text: 'Vert', isCorrect: true },
      { id: 'b', text: 'Noir', isCorrect: false },
      { id: 'c', text: 'Blanc', isCorrect: false },
    ],
    correctAnswer: 'Vert',
    explanation: '« Green » veut dire vert en français.',
    hint: 'Pense à la couleur de l\'herbe.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-002',
    subject: 'anglais',
    title: 'Couleur : black',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « black » en français ?',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: false },
      { id: 'b', text: 'Blanc', isCorrect: false },
      { id: 'c', text: 'Noir', isCorrect: true },
    ],
    correctAnswer: 'Noir',
    explanation: '« Black » veut dire noir en français.',
    hint: 'Pense à la couleur de la nuit.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-003',
    subject: 'anglais',
    title: 'Animal : horse',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a horse » en français ?',
    options: [
      { id: 'a', text: 'Un cheval', isCorrect: true },
      { id: 'b', text: 'Un mouton', isCorrect: false },
      { id: 'c', text: 'Une vache', isCorrect: false },
    ],
    correctAnswer: 'Un cheval',
    explanation: '« Horse » veut dire cheval en français.',
    hint: 'On peut le monter et il galope.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-004',
    subject: 'anglais',
    title: 'Animal : bird',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a bird » en français ?',
    options: [
      { id: 'a', text: 'Un lapin', isCorrect: false },
      { id: 'b', text: 'Un oiseau', isCorrect: true },
      { id: 'c', text: 'Un cochon', isCorrect: false },
    ],
    correctAnswer: 'Un oiseau',
    explanation: '« Bird » veut dire oiseau en français.',
    hint: 'Cet animal a des ailes et vole.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-005',
    subject: 'anglais',
    title: 'Animal : rabbit',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a rabbit » en français ?',
    options: [
      { id: 'a', text: 'Un lapin', isCorrect: true },
      { id: 'b', text: 'Un chien', isCorrect: false },
      { id: 'c', text: 'Un poisson', isCorrect: false },
    ],
    correctAnswer: 'Un lapin',
    explanation: '« Rabbit » veut dire lapin en français.',
    hint: 'Il a de grandes oreilles et saute.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-006',
    subject: 'anglais',
    title: 'École : pencil',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'ecole',
    format: 'qcm',
    instructions: 'Quel objet est-ce en français ?',
    prompt: 'Que veut dire « a pencil » en français ?',
    options: [
      { id: 'a', text: 'Un crayon', isCorrect: true },
      { id: 'b', text: 'Un stylo', isCorrect: false },
      { id: 'c', text: 'Une règle', isCorrect: false },
    ],
    correctAnswer: 'Un crayon',
    explanation: '« Pencil » veut dire crayon en français.',
    hint: 'On l\'utilise pour écrire et dessiner.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'ecole', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-007',
    subject: 'anglais',
    title: 'École : book',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'ecole',
    format: 'qcm',
    instructions: 'Quel objet est-ce en français ?',
    prompt: 'Que veut dire « a book » en français ?',
    options: [
      { id: 'a', text: 'Un cahier', isCorrect: false },
      { id: 'b', text: 'Un livre', isCorrect: true },
      { id: 'c', text: 'Une gomme', isCorrect: false },
    ],
    correctAnswer: 'Un livre',
    explanation: '« Book » veut dire livre en français.',
    hint: 'On peut lire des histoires dedans.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'ecole', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-008',
    subject: 'anglais',
    title: 'École : ruler',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'ecole',
    format: 'qcm',
    instructions: 'Quel objet est-ce en français ?',
    prompt: 'Que veut dire « a ruler » en français ?',
    options: [
      { id: 'a', text: 'Une règle', isCorrect: true },
      { id: 'b', text: 'Un crayon', isCorrect: false },
      { id: 'c', text: 'Une gomme', isCorrect: false },
    ],
    correctAnswer: 'Une règle',
    explanation: '« Ruler » veut dire règle en français.',
    hint: 'On l\'utilise pour tracer des lignes droites.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'ecole', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-009',
    subject: 'anglais',
    title: 'Corps : head',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « head » en français ?',
    options: [
      { id: 'a', text: 'La tête', isCorrect: true },
      { id: 'b', text: 'Le bras', isCorrect: false },
      { id: 'c', text: 'La jambe', isCorrect: false },
    ],
    correctAnswer: 'La tête',
    explanation: '« Head » veut dire tête en français.',
    hint: 'Elle est tout en haut du corps.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-010',
    subject: 'anglais',
    title: 'Corps : hand',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « hand » en français ?',
    options: [
      { id: 'a', text: 'La main', isCorrect: true },
      { id: 'b', text: 'L\'œil', isCorrect: false },
      { id: 'c', text: 'Le nez', isCorrect: false },
    ],
    correctAnswer: 'La main',
    explanation: '« Hand » veut dire main en français.',
    hint: 'Elle est au bout du bras.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-011',
    subject: 'anglais',
    title: 'Nombre : ten',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'nombres',
    format: 'qcm',
    instructions: 'Quel nombre est-ce ?',
    prompt: 'Quel est le mot anglais pour le nombre 10 ?',
    options: [
      { id: 'a', text: 'eight', isCorrect: false },
      { id: 'b', text: 'nine', isCorrect: false },
      { id: 'c', text: 'ten', isCorrect: true },
    ],
    correctAnswer: 'ten',
    explanation: 'Le nombre 10 se dit « ten » en anglais.',
    hint: '8 = eight, 9 = nine, 10 = …',
    tags: ['ce1', 'anglais', 'vocabulaire', 'nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-012',
    subject: 'anglais',
    title: 'Salutation : please',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire ce mot anglais ?',
    prompt: 'Que veut dire « please » en français ?',
    options: [
      { id: 'a', text: 'Merci', isCorrect: false },
      { id: 'b', text: 'S\'il te plaît', isCorrect: true },
      { id: 'c', text: 'Pardon', isCorrect: false },
    ],
    correctAnswer: 'S\'il te plaît',
    explanation: '« Please » veut dire s\'il te plaît en français.',
    hint: 'On l\'utilise pour faire une demande poliment.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

  // ══════════════════════════════════════════════════════════════════
  // CE2 — vocabulaire + mini phrases (12 exercices)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'en-ce2-voc-001',
    subject: 'anglais',
    title: 'Phrase : How are you?',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « How are you? » en français ?',
    options: [
      { id: 'a', text: 'Comment t\'appelles-tu ?', isCorrect: false },
      { id: 'b', text: 'Comment vas-tu ?', isCorrect: true },
      { id: 'c', text: 'Quel âge as-tu ?', isCorrect: false },
    ],
    correctAnswer: 'Comment vas-tu ?',
    explanation: '« How are you? » veut dire "Comment vas-tu ?" en français.',
    hint: '« How » = comment, « are you » = vas-tu.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-002',
    subject: 'anglais',
    title: "Réponse : I'm fine",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette réponse ?',
    prompt: "Que veut dire « I'm fine » en français ?",
    options: [
      { id: 'a', text: 'Je m\'appelle', isCorrect: false },
      { id: 'b', text: 'Je vais bien', isCorrect: true },
      { id: 'c', text: 'J\'ai faim', isCorrect: false },
    ],
    correctAnswer: 'Je vais bien',
    explanation: "« I'm fine » veut dire « Je vais bien » en français.",
    hint: "« Fine » veut dire bien.",
    tags: ['ce2', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-003',
    subject: 'anglais',
    title: 'Phrase : What is your name?',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « What is your name? » en français ?',
    options: [
      { id: 'a', text: 'Quel âge as-tu ?', isCorrect: false },
      { id: 'b', text: 'Comment t\'appelles-tu ?', isCorrect: true },
      { id: 'c', text: 'Où habites-tu ?', isCorrect: false },
    ],
    correctAnswer: 'Comment t\'appelles-tu ?',
    explanation: '« What is your name? » veut dire "Comment t\'appelles-tu ?" en français.',
    hint: '« Name » veut dire nom.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-004',
    subject: 'anglais',
    title: 'Corps : nose',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « nose » en français ?',
    options: [
      { id: 'a', text: 'Le nez', isCorrect: true },
      { id: 'b', text: 'La bouche', isCorrect: false },
      { id: 'c', text: 'L\'oreille', isCorrect: false },
    ],
    correctAnswer: 'Le nez',
    explanation: '« Nose » veut dire nez en français.',
    hint: 'Il est au milieu du visage.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-005',
    subject: 'anglais',
    title: 'Corps : eye',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « eye » en français ?',
    options: [
      { id: 'a', text: 'Le pied', isCorrect: false },
      { id: 'b', text: 'L\'œil', isCorrect: true },
      { id: 'c', text: 'Le dos', isCorrect: false },
    ],
    correctAnswer: 'L\'œil',
    explanation: '« Eye » veut dire œil en français.',
    hint: 'On s\'en sert pour voir.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-006',
    subject: 'anglais',
    title: 'Corps : leg',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « leg » en français ?',
    options: [
      { id: 'a', text: 'Le bras', isCorrect: false },
      { id: 'b', text: 'La jambe', isCorrect: true },
      { id: 'c', text: 'L\'épaule', isCorrect: false },
    ],
    correctAnswer: 'La jambe',
    explanation: '« Leg » veut dire jambe en français.',
    hint: 'Elle sert à marcher et à courir.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-007',
    subject: 'anglais',
    title: 'École : rubber',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ecole',
    format: 'qcm',
    instructions: 'Quel objet est-ce en français ?',
    prompt: 'Que veut dire « a rubber » en anglais britannique ?',
    options: [
      { id: 'a', text: 'Une règle', isCorrect: false },
      { id: 'b', text: 'Une gomme', isCorrect: true },
      { id: 'c', text: 'Un crayon', isCorrect: false },
    ],
    correctAnswer: 'Une gomme',
    explanation: '« Rubber » (anglais britannique) veut dire gomme en français.',
    hint: 'On l\'utilise pour effacer les erreurs.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'ecole', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-008',
    subject: 'anglais',
    title: 'École : school bag',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'ecole',
    format: 'qcm',
    instructions: 'Quel objet est-ce en français ?',
    prompt: 'Que veut dire « a school bag » en français ?',
    options: [
      { id: 'a', text: 'Une trousse', isCorrect: false },
      { id: 'b', text: 'Un stylo', isCorrect: false },
      { id: 'c', text: 'Un cartable', isCorrect: true },
    ],
    correctAnswer: 'Un cartable',
    explanation: '« School bag » veut dire cartable en français.',
    hint: 'On le porte sur le dos pour aller à l\'école.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'ecole', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-001',
    subject: 'anglais',
    title: 'Verbe être : I am',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'verbe_etre',
    format: 'qcm',
    instructions: 'Choisis le bon mot pour compléter la phrase.',
    prompt: 'Complète : « I ___ happy. »',
    options: [
      { id: 'a', text: 'am', isCorrect: true },
      { id: 'b', text: 'is', isCorrect: false },
      { id: 'c', text: 'are', isCorrect: false },
    ],
    correctAnswer: 'am',
    explanation: 'Avec « I » (je), on utilise toujours « am » : I am happy.',
    hint: 'Avec « I », le verbe être en anglais est « am ».',
    tags: ['ce2', 'anglais', 'grammaire', 'verbe_etre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Complète avec am, is ou are.', extraHint: 'I → am.' },
    }),
  },
  {
    id: 'en-ce2-gram-002',
    subject: 'anglais',
    title: 'Verbe être : She is',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'verbe_etre',
    format: 'qcm',
    instructions: 'Choisis le bon mot pour compléter la phrase.',
    prompt: 'Complète : « She ___ tall. »',
    options: [
      { id: 'a', text: 'am', isCorrect: false },
      { id: 'b', text: 'is', isCorrect: true },
      { id: 'c', text: 'are', isCorrect: false },
    ],
    correctAnswer: 'is',
    explanation: 'Avec « She » (elle) ou « He » (il), on utilise « is » : She is tall.',
    hint: 'He / She / It → is.',
    tags: ['ce2', 'anglais', 'grammaire', 'verbe_etre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Complète avec am, is ou are.', extraHint: 'She / He → is.' },
    }),
  },
  {
    id: 'en-ce2-gram-003',
    subject: 'anglais',
    title: 'Verbe être : They are',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'verbe_etre',
    format: 'qcm',
    instructions: 'Choisis le bon mot pour compléter la phrase.',
    prompt: 'Complète : « They ___ my friends. »',
    options: [
      { id: 'a', text: 'am', isCorrect: false },
      { id: 'b', text: 'is', isCorrect: false },
      { id: 'c', text: 'are', isCorrect: true },
    ],
    correctAnswer: 'are',
    explanation: 'Avec « They » (ils/elles) ou « We » (nous), on utilise « are ».',
    hint: 'We / You / They → are.',
    tags: ['ce2', 'anglais', 'grammaire', 'verbe_etre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Repère le sujet de la phrase.', 'They = ils/elles.', 'Choisis « are ».'] },
    }),
  },
  {
    id: 'en-ce2-gram-004',
    subject: 'anglais',
    title: 'Traduire : I am a student',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'verbe_etre',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: 'Que veut dire « I am a student » en français ?',
    options: [
      { id: 'a', text: 'Je suis un(e) élève.', isCorrect: true },
      { id: 'b', text: 'J\'ai un stylo.', isCorrect: false },
      { id: 'c', text: 'Je joue.', isCorrect: false },
    ],
    correctAnswer: 'Je suis un(e) élève.',
    explanation: '« I am » = je suis, « a student » = un(e) élève.',
    hint: '« I am » veut dire « je suis ».',
    tags: ['ce2', 'anglais', 'grammaire', 'verbe_etre', 'phrases_courtes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },

  // ══════════════════════════════════════════════════════════════════
  // CM1 — vocabulaire + grammaire (13 exercices)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'en-cm1-gram-001',
    subject: 'anglais',
    title: 'Can : I can swim',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: 'Que veut dire « I can swim » en français ?',
    options: [
      { id: 'a', text: 'Je sais nager.', isCorrect: true },
      { id: 'b', text: 'Je ne sais pas nager.', isCorrect: false },
      { id: 'c', text: 'J\'aime nager.', isCorrect: false },
    ],
    correctAnswer: 'Je sais nager.',
    explanation: '« Can » = pouvoir / savoir. « I can swim » = Je sais nager.',
    hint: '« Can » exprime la capacité ou la permission.',
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-002',
    subject: 'anglais',
    title: "Can't : She can't fly",
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase en français.',
    prompt: "Que veut dire « She can't fly » en français ?",
    options: [
      { id: 'a', text: 'Elle peut voler.', isCorrect: false },
      { id: 'b', text: 'Elle ne peut pas voler.', isCorrect: true },
      { id: 'c', text: 'Elle aime voler.', isCorrect: false },
    ],
    correctAnswer: 'Elle ne peut pas voler.',
    explanation: "« Can't » = ne peut pas. « She can't fly » = Elle ne peut pas voler.",
    hint: "« Can't » est la forme négative de « can ».",
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-003',
    subject: 'anglais',
    title: 'Can : Birds can fly',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Choisis le bon mot pour compléter.',
    prompt: 'Complète : « Birds ___ fly. » (Les oiseaux peuvent voler.)',
    options: [
      { id: 'a', text: 'can', isCorrect: true },
      { id: 'b', text: "can't", isCorrect: false },
      { id: 'c', text: 'is', isCorrect: false },
    ],
    correctAnswer: 'can',
    explanation: 'Les oiseaux peuvent voler → on utilise « can » : Birds can fly.',
    hint: 'Les oiseaux volent → capacité → can.',
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis can ou can\'t.', extraHint: 'Les oiseaux volent → can.' },
    }),
  },
  {
    id: 'en-cm1-gram-004',
    subject: 'anglais',
    title: "Can't : Fish can't climb",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Choisis le bon mot pour compléter.',
    prompt: "Complète : « Fish ___ climb trees. » (Les poissons ne peuvent pas grimper.)",
    options: [
      { id: 'a', text: 'can', isCorrect: false },
      { id: 'b', text: "can't", isCorrect: true },
      { id: 'c', text: 'are', isCorrect: false },
    ],
    correctAnswer: "can't",
    explanation: "Les poissons ne peuvent pas grimper → on utilise « can't ».",
    hint: "Impossible → can't.",
    tags: ['cm1', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-005',
    subject: 'anglais',
    title: "Article : a ou an ? (apple)",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'articles',
    format: 'qcm',
    instructions: 'Quel article utilise-t-on devant ce mot ?',
    prompt: 'Quel article utilise-t-on avant « apple » ?',
    options: [
      { id: 'a', text: 'a', isCorrect: false },
      { id: 'b', text: 'an', isCorrect: true },
      { id: 'c', text: 'the', isCorrect: false },
    ],
    correctAnswer: 'an',
    explanation: 'On utilise « an » avant un mot commençant par une voyelle (a, e, i, o, u). Apple → an apple.',
    hint: '« Apple » commence par une voyelle (a).',
    tags: ['cm1', 'anglais', 'grammaire', 'articles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['« Apple » commence par quelle lettre ?', 'A est une voyelle.', 'Voyelle → an.'] },
    }),
  },
  {
    id: 'en-cm1-gram-006',
    subject: 'anglais',
    title: 'Article : a ou an ? (dog)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'articles',
    format: 'qcm',
    instructions: 'Quel article utilise-t-on devant ce mot ?',
    prompt: 'Quel article utilise-t-on avant « dog » ?',
    options: [
      { id: 'a', text: 'a', isCorrect: true },
      { id: 'b', text: 'an', isCorrect: false },
      { id: 'c', text: 'the', isCorrect: false },
    ],
    correctAnswer: 'a',
    explanation: '« Dog » commence par une consonne (d), donc on utilise « a » : a dog.',
    hint: '« Dog » commence par d, une consonne.',
    tags: ['cm1', 'anglais', 'grammaire', 'articles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-gram-007',
    subject: 'anglais',
    title: 'Article : a ou an ? (elephant)',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'articles',
    format: 'qcm',
    instructions: 'Quel article utilise-t-on devant ce mot ?',
    prompt: 'Quel article utilise-t-on avant « elephant » ?',
    options: [
      { id: 'a', text: 'a', isCorrect: false },
      { id: 'b', text: 'an', isCorrect: true },
      { id: 'c', text: 'the', isCorrect: false },
    ],
    correctAnswer: 'an',
    explanation: '« Elephant » commence par une voyelle (e) → an elephant.',
    hint: 'E est une voyelle → an.',
    tags: ['cm1', 'anglais', 'grammaire', 'articles', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Donne 2 autres mots qui prennent « an ».' },
    }),
  },
  {
    id: 'en-cm1-voc-001',
    subject: 'anglais',
    title: 'Phrase : This is a cat',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « This is a cat » en français ?',
    options: [
      { id: 'a', text: 'Voici un chien.', isCorrect: false },
      { id: 'b', text: 'Voici un chat.', isCorrect: true },
      { id: 'c', text: "C'est une maison.", isCorrect: false },
    ],
    correctAnswer: 'Voici un chat.',
    explanation: '« This is » = voici / c\'est. « A cat » = un chat.',
    hint: '« This is » = voici ou c\'est.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'phrases_courtes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-002',
    subject: 'anglais',
    title: 'Phrase : He is my brother',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « He is my brother » en français ?',
    options: [
      { id: 'a', text: 'Il est mon frère.', isCorrect: true },
      { id: 'b', text: 'Elle est ma sœur.', isCorrect: false },
      { id: 'c', text: "C'est mon ami.", isCorrect: false },
    ],
    correctAnswer: 'Il est mon frère.',
    explanation: '« He » = il, « is » = est, « my brother » = mon frère.',
    hint: '« He » = il, « brother » = frère.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'phrases_courtes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-003',
    subject: 'anglais',
    title: 'Couleur : purple',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « purple » en français ?',
    options: [
      { id: 'a', text: 'Rose', isCorrect: false },
      { id: 'b', text: 'Orange', isCorrect: false },
      { id: 'c', text: 'Violet', isCorrect: true },
    ],
    correctAnswer: 'Violet',
    explanation: '« Purple » veut dire violet en français.',
    hint: 'C\'est un mélange de rouge et de bleu.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-004',
    subject: 'anglais',
    title: 'Couleur : orange',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « orange » en anglais ? (même mot en français ?)',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: false },
      { id: 'b', text: 'Orange', isCorrect: true },
      { id: 'c', text: 'Jaune', isCorrect: false },
    ],
    correctAnswer: 'Orange',
    explanation: '« Orange » se dit pareil en anglais et en français !',
    hint: 'Ce mot existe dans les deux langues.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Trouve 2 autres mots identiques en français et en anglais.' },
    }),
  },
  {
    id: 'en-cm1-voc-005',
    subject: 'anglais',
    title: 'Couleur : white',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « white » en français ?',
    options: [
      { id: 'a', text: 'Blanc', isCorrect: true },
      { id: 'b', text: 'Gris', isCorrect: false },
      { id: 'c', text: 'Marron', isCorrect: false },
    ],
    correctAnswer: 'Blanc',
    explanation: '« White » veut dire blanc en français.',
    hint: 'Pense à la neige.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm1-voc-006',
    subject: 'anglais',
    title: 'Phrase : She has blue eyes',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « She has blue eyes » en français ?',
    options: [
      { id: 'a', text: 'Elle a les yeux bleus.', isCorrect: true },
      { id: 'b', text: 'Elle a les cheveux blonds.', isCorrect: false },
      { id: 'c', text: 'Il a les yeux bleus.', isCorrect: false },
    ],
    correctAnswer: 'Elle a les yeux bleus.',
    explanation: '« She » = elle, « has » = a, « blue eyes » = les yeux bleus.',
    hint: '« She » = elle. « Eyes » = les yeux.',
    tags: ['cm1', 'anglais', 'vocabulaire', 'phrases_courtes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Traduis « She » (elle).', 'Traduis « blue eyes ».', 'Assemble la phrase.'] },
    }),
  },

  // ══════════════════════════════════════════════════════════════════
  // CM2 — grammaire + compréhension (13 exercices)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'en-cm2-gram-001',
    subject: 'anglais',
    title: 'Pluriel : cats',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot anglais ?',
    prompt: 'Quel est le pluriel de « cat » ?',
    options: [
      { id: 'a', text: 'cats', isCorrect: true },
      { id: 'b', text: 'cates', isCorrect: false },
      { id: 'c', text: 'caties', isCorrect: false },
    ],
    correctAnswer: 'cats',
    explanation: 'En anglais, on ajoute généralement « s » pour former le pluriel : cat → cats.',
    hint: 'En anglais, le pluriel le plus courant se forme en ajoutant « s ».',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-002',
    subject: 'anglais',
    title: 'Pluriel : boxes',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot anglais ?',
    prompt: 'Quel est le pluriel de « box » ?',
    options: [
      { id: 'a', text: 'boxs', isCorrect: false },
      { id: 'b', text: 'boxes', isCorrect: true },
      { id: 'c', text: 'boxies', isCorrect: false },
    ],
    correctAnswer: 'boxes',
    explanation: 'Les mots finissant par -x, -s, -sh, -ch prennent « es » au pluriel : box → boxes.',
    hint: 'Les mots en -x prennent « es » : box → boxes.',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Choisis le bon pluriel.', extraHint: 'box → boxes (comme "boîtes").' },
    }),
  },
  {
    id: 'en-cm2-gram-003',
    subject: 'anglais',
    title: 'Pluriel irrégulier : children',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'pluriel',
    format: 'qcm',
    instructions: 'Quel est le pluriel de ce mot ?',
    prompt: 'Quel est le pluriel irrégulier de « child » (enfant) ?',
    options: [
      { id: 'a', text: 'childs', isCorrect: false },
      { id: 'b', text: 'childes', isCorrect: false },
      { id: 'c', text: 'children', isCorrect: true },
    ],
    correctAnswer: 'children',
    explanation: '« Child » a un pluriel irrégulier : children (comme "man" → "men").',
    hint: 'Certains pluriels en anglais sont irréguliers.',
    tags: ['cm2', 'anglais', 'grammaire', 'pluriel', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      defi_avance: { challengeExtension: 'Trouve un autre pluriel irrégulier anglais.' },
    }),
  },
  {
    id: 'en-cm2-gram-004',
    subject: 'anglais',
    title: 'Can : Can you speak French?',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « Can you speak French? » en français ?',
    options: [
      { id: 'a', text: 'Parles-tu français ?', isCorrect: true },
      { id: 'b', text: 'Tu aimes le français ?', isCorrect: false },
      { id: 'c', text: 'Tu apprends le français ?', isCorrect: false },
    ],
    correctAnswer: 'Parles-tu français ?',
    explanation: '« Can you » = peux-tu / sais-tu. « Speak French » = parler français.',
    hint: '« Can » en question = peux-tu ? / sais-tu ?',
    tags: ['cm2', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-gram-005',
    subject: 'anglais',
    title: "Can't : contexte",
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse.',
    prompt: "Complète : « I ___ ride a bike, I don't have one. »",
    options: [
      { id: 'a', text: 'can', isCorrect: false },
      { id: 'b', text: "can't", isCorrect: true },
      { id: 'c', text: 'am not', isCorrect: false },
    ],
    correctAnswer: "can't",
    explanation: "La phrase dit qu'il n'a pas de vélo donc il ne peut pas en faire : can't.",
    hint: "Pas de vélo → impossible → can't.",
    tags: ['cm2', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis toute la phrase.', 'A-t-il un vélo ?', 'Non → impossible → can\'t.'] },
    }),
  },
  {
    id: 'en-cm2-gram-006',
    subject: 'anglais',
    title: 'Can : We can play',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'can_cant',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « We can play football » en français ?',
    options: [
      { id: 'a', text: 'Nous voulons jouer au football.', isCorrect: false },
      { id: 'b', text: 'Nous pouvons jouer au football.', isCorrect: true },
      { id: 'c', text: 'Nous jouons au football.', isCorrect: false },
    ],
    correctAnswer: 'Nous pouvons jouer au football.',
    explanation: '« We can » = nous pouvons. « Play football » = jouer au football.',
    hint: '« Can » = pouvoir.',
    tags: ['cm2', 'anglais', 'grammaire', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-001',
    subject: 'anglais',
    title: 'Compréhension : âge',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: "« Tom is 10 years old. He has a dog. » — Quel est l'âge de Tom ?",
    options: [
      { id: 'a', text: '8 ans', isCorrect: false },
      { id: 'b', text: '10 ans', isCorrect: true },
      { id: 'c', text: '12 ans', isCorrect: false },
    ],
    correctAnswer: '10 ans',
    explanation: 'La phrase dit « Tom is 10 years old » : Tom a 10 ans.',
    hint: '« 10 years old » veut dire 10 ans.',
    tags: ['cm2', 'anglais', 'comprehension', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Lis la 1ʳᵉ phrase.', extraHint: '« 10 years old » = 10 ans.' },
    }),
  },
  {
    id: 'en-cm2-comp-002',
    subject: 'anglais',
    title: 'Compréhension : météo',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« It is sunny today. Emma wears a hat. » — Quel temps fait-il ?',
    options: [
      { id: 'a', text: 'Il pleut.', isCorrect: false },
      { id: 'b', text: 'Il fait soleil.', isCorrect: true },
      { id: 'c', text: 'Il neige.', isCorrect: false },
    ],
    correctAnswer: 'Il fait soleil.',
    explanation: '« It is sunny » veut dire il fait soleil.',
    hint: '« Sunny » = ensoleillé.',
    tags: ['cm2', 'anglais', 'comprehension', 'météo', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-comp-003',
    subject: 'anglais',
    title: 'Compréhension : capacités',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Lis et réponds à la question.',
    prompt: '« My name is Lily. I am 9. I can read and write. » — Que peut faire Lily ?',
    options: [
      { id: 'a', text: 'Nager et courir.', isCorrect: false },
      { id: 'b', text: 'Lire et écrire.', isCorrect: true },
      { id: 'c', text: 'Chanter et danser.', isCorrect: false },
    ],
    correctAnswer: 'Lire et écrire.',
    explanation: '« I can read and write » = Je sais lire et écrire.',
    hint: '« Read » = lire, « write » = écrire.',
    tags: ['cm2', 'anglais', 'comprehension', 'can_cant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis la dernière phrase.', 'Repère « can read and write ».', 'Traduis.'] },
    }),
  },
  {
    id: 'en-cm2-comp-004',
    subject: 'anglais',
    title: 'Compréhension : compter',
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'nombres',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: '« I have two cats and one dog. » — Combien d\'animaux en tout ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '« Two cats » = 2 chats + « one dog » = 1 chien = 3 animaux.',
    hint: '« Two » = 2, « one » = 1. Additionne.',
    tags: ['cm2', 'anglais', 'comprehension', 'nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-001',
    subject: 'anglais',
    title: "Phrase : Where are you from?",
    schoolClass: 'CM2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Traduis cette question.',
    prompt: 'Que veut dire « Where are you from? » en français ?',
    options: [
      { id: 'a', text: 'Où vas-tu ?', isCorrect: false },
      { id: 'b', text: "D'où viens-tu ?", isCorrect: true },
      { id: 'c', text: 'Comment t\'appelles-tu ?', isCorrect: false },
    ],
    correctAnswer: "D'où viens-tu ?",
    explanation: '« Where are you from? » = D\'où viens-tu ? / De quel pays es-tu ?',
    hint: '« Where from » = d\'où.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-002',
    subject: 'anglais',
    title: 'Phrase : I like football',
    schoolClass: 'CM2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « I like football » en français ?',
    options: [
      { id: 'a', text: 'Je joue au football.', isCorrect: false },
      { id: 'b', text: "J'aime le football.", isCorrect: true },
      { id: 'c', text: 'Je regarde le football.', isCorrect: false },
    ],
    correctAnswer: "J'aime le football.",
    explanation: '« I like » = j\'aime. « Football » = le football.',
    hint: '« Like » = aimer.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'phrases_courtes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cm2-voc-003',
    subject: 'anglais',
    title: 'Phrase : My favourite colour is red',
    schoolClass: 'CM2',
    generalLevel: 'advanced',
    skill: 'vocabulaire',
    subskill: 'phrases_courtes',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Que veut dire « My favourite colour is red » en français ?',
    options: [
      { id: 'a', text: 'Ma couleur préférée est le rouge.', isCorrect: true },
      { id: 'b', text: "J'ai un stylo rouge.", isCorrect: false },
      { id: 'c', text: 'La voiture est rouge.', isCorrect: false },
    ],
    correctAnswer: 'Ma couleur préférée est le rouge.',
    explanation: '« My favourite » = ma préférée, « colour » = couleur, « is red » = est rouge.',
    hint: '« Favourite » = préféré(e). « Colour » = couleur.',
    tags: ['cm2', 'anglais', 'vocabulaire', 'couleurs', 'phrases_courtes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Traduis « My favourite colour » (ma couleur préférée).', 'Traduis « is red ».', 'Assemble.'] },
      defi_avance: { challengeExtension: "Écris en anglais ta couleur préférée avec « My favourite colour is… »" },
    }),
  },
];
