import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCpCommClassroomExercises: EnglishExercise[] = [
  {
    id: 'en-cp-comp-012',
    subject: 'anglais',
    title: 'Classroom : Open your book',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Open your book. » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu fermes ton livre.', isCorrect: false },
      { id: 'b', text: 'Tu ouvres ton livre.', isCorrect: true },
      { id: 'c', text: 'Tu poses ton livre.', isCorrect: false },
    ],
    correctAnswer: 'Tu ouvres ton livre.',
    explanation: '« Open » = ouvrir. « Your book » = ton livre.',
    hint: '« Open » = ouvrir.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-013',
    subject: 'anglais',
    title: 'Classroom : Close your book',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Close your book. » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu fermes ton livre.', isCorrect: true },
      { id: 'b', text: 'Tu ouvres ton livre.', isCorrect: false },
      { id: 'c', text: 'Tu prends ton stylo.', isCorrect: false },
    ],
    correctAnswer: 'Tu fermes ton livre.',
    explanation: '« Close » = fermer. C\'est le contraire d\'« open ».',
    hint: '« Close » = fermer. Contraire d\'open.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-014',
    subject: 'anglais',
    title: 'Classroom : Be quiet',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Be quiet! » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu lèves la main.', isCorrect: false },
      { id: 'b', text: 'Tu te tais / tu fais du silence.', isCorrect: true },
      { id: 'c', text: 'Tu sors de la classe.', isCorrect: false },
    ],
    correctAnswer: 'Tu te tais / tu fais du silence.',
    explanation: '« Be quiet » = chut ! / taisez-vous ! On doit faire silence.',
    hint: '« Quiet » = calme, silencieux.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-015',
    subject: 'anglais',
    title: 'Classroom : Listen!',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Listen! » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu regardes.', isCorrect: false },
      { id: 'b', text: 'Tu écoutes.', isCorrect: true },
      { id: 'c', text: 'Tu lis.', isCorrect: false },
    ],
    correctAnswer: 'Tu écoutes.',
    explanation: '« Listen » = écouter. Les oreilles sont les plus importantes ici !',
    hint: '« Listen » = utilise tes oreilles.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-016',
    subject: 'anglais',
    title: 'Classroom : Look!',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Look! » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu écoutes.', isCorrect: false },
      { id: 'b', text: 'Tu regardes.', isCorrect: true },
      { id: 'c', text: 'Tu répètes.', isCorrect: false },
    ],
    correctAnswer: 'Tu regardes.',
    explanation: '« Look » = regarder. Les yeux sont les plus importants ici !',
    hint: '« Look » = utilise tes yeux.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-017',
    subject: 'anglais',
    title: 'Classroom : Put your hand up',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Put your hand up! » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu poses ta main sur la table.', isCorrect: false },
      { id: 'b', text: 'Tu lèves la main.', isCorrect: true },
      { id: 'c', text: 'Tu te lèves.', isCorrect: false },
    ],
    correctAnswer: 'Tu lèves la main.',
    explanation: '« Put your hand up » = lève la main (pour répondre à une question).',
    hint: '« Up » = vers le haut. Ta main monte.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-018',
    subject: 'anglais',
    title: 'Classroom : Write your name',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Write your name. » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu lis ton nom à voix haute.', isCorrect: false },
      { id: 'b', text: 'Tu écris ton prénom.', isCorrect: true },
      { id: 'c', text: 'Tu dessines ton visage.', isCorrect: false },
    ],
    correctAnswer: 'Tu écris ton prénom.',
    explanation: '« Write » = écrire. « Your name » = ton prénom / nom.',
    hint: '« Write » = écrire. « Name » = prénom.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-019',
    subject: 'anglais',
    title: 'Classroom : Draw a circle',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Draw a circle. » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu dessines un carré.', isCorrect: false },
      { id: 'b', text: 'Tu dessines un cercle.', isCorrect: true },
      { id: 'c', text: 'Tu colories un triangle.', isCorrect: false },
    ],
    correctAnswer: 'Tu dessines un cercle.',
    explanation: '« Draw » = dessiner. « Circle » = cercle / rond.',
    hint: '« Draw » = dessiner. « Circle » = forme ronde.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-020',
    subject: 'anglais',
    title: 'Classroom : Work in pairs',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Work in pairs. » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu travailles seul(e).', isCorrect: false },
      { id: 'b', text: 'Tu travailles avec un(e) camarade.', isCorrect: true },
      { id: 'c', text: 'Tu travailles en groupe de quatre.', isCorrect: false },
    ],
    correctAnswer: 'Tu travailles avec un(e) camarade.',
    explanation: '« Work in pairs » = travailler en binôme (2 personnes).',
    hint: '« Pairs » = par deux.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-021',
    subject: 'anglais',
    title: 'Classroom : It\'s your turn',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Ton ami dit : « It\'s your turn! » Que veut-il dire ?',
    options: [
      { id: 'a', text: 'C\'est son tour.', isCorrect: false },
      { id: 'b', text: 'C\'est ton tour.', isCorrect: true },
      { id: 'c', text: 'C\'est la fin du jeu.', isCorrect: false },
    ],
    correctAnswer: 'C\'est ton tour.',
    explanation: '« It\'s your turn » = c\'est ton tour. On le dit dans un jeu ou une activité.',
    hint: '« Your » = ton/ta. À qui est le tour ?',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-022',
    subject: 'anglais',
    title: 'Classroom : Can I have a pencil?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « Can I have a pencil, please? » en français ?',
    options: [
      { id: 'a', text: 'Est-ce que j\'ai un crayon ?', isCorrect: false },
      { id: 'b', text: 'Est-ce que je peux avoir un crayon, s\'il te plaît ?', isCorrect: true },
      { id: 'c', text: 'Où est mon crayon ?', isCorrect: false },
    ],
    correctAnswer: 'Est-ce que je peux avoir un crayon, s\'il te plaît ?',
    explanation: '« Can I have… ? » = est-ce que je peux avoir… ? « Pencil » = crayon.',
    hint: '« Can I have » = est-ce que je peux avoir.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-023',
    subject: 'anglais',
    title: 'Classroom : What page is it?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « What page is it? » en français ?',
    options: [
      { id: 'a', text: 'Quel livre c\'est ?', isCorrect: false },
      { id: 'b', text: 'C\'est quelle page ?', isCorrect: true },
      { id: 'c', text: 'C\'est quel exercice ?', isCorrect: false },
    ],
    correctAnswer: 'C\'est quelle page ?',
    explanation: '« What page is it? » = c\'est quelle page ? « Page » = même mot en français.',
    hint: '« Page » = page (même mot !).',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-024',
    subject: 'anglais',
    title: 'Classroom : I\'ve finished!',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Tu entends « I\'ve finished! » Que vient de faire l\'élève ?',
    options: [
      { id: 'a', text: 'Il a commencé son exercice.', isCorrect: false },
      { id: 'b', text: 'Il a terminé son exercice.', isCorrect: true },
      { id: 'c', text: 'Il a besoin d\'aide.', isCorrect: false },
    ],
    correctAnswer: 'Il a terminé son exercice.',
    explanation: '« I\'ve finished » = j\'ai terminé / j\'ai fini.',
    hint: '« Finish » = terminer / finir.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-025',
    subject: 'anglais',
    title: 'Classroom : I don\'t understand',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « I don\'t understand » en français ?',
    options: [
      { id: 'a', text: 'J\'ai compris.', isCorrect: false },
      { id: 'b', text: 'Je ne comprends pas.', isCorrect: true },
      { id: 'c', text: 'J\'ai besoin d\'un stylo.', isCorrect: false },
    ],
    correctAnswer: 'Je ne comprends pas.',
    explanation: '« I don\'t understand » = je ne comprends pas. Très utile en cours !',
    hint: '« Don\'t » = ne…pas. « Understand » = comprendre.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-026',
    subject: 'anglais',
    title: 'Classroom : Can you repeat?',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « Can you repeat, please? » en français ?',
    options: [
      { id: 'a', text: 'Tu peux parler plus fort ?', isCorrect: false },
      { id: 'b', text: 'Tu peux répéter, s\'il te plaît ?', isCorrect: true },
      { id: 'c', text: 'Tu peux m\'aider, s\'il te plaît ?', isCorrect: false },
    ],
    correctAnswer: 'Tu peux répéter, s\'il te plaît ?',
    explanation: '« Repeat » = répéter. Presque le même mot qu\'en français !',
    hint: '« Repeat » ressemble au mot français équivalent.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-027',
    subject: 'anglais',
    title: 'Classroom : Stand up',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette instruction ?',
    prompt: 'Le professeur dit : « Stand up! » Que fais-tu ?',
    options: [
      { id: 'a', text: 'Tu t\'asseois.', isCorrect: false },
      { id: 'b', text: 'Tu te lèves.', isCorrect: true },
      { id: 'c', text: 'Tu sautes.', isCorrect: false },
    ],
    correctAnswer: 'Tu te lèves.',
    explanation: '« Stand up » = lève-toi. Contraire de « Sit down » (assieds-toi).',
    hint: '« Up » = vers le haut. Tu te mets debout.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-comp-028',
    subject: 'anglais',
    title: 'Classroom : That\'s right!',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Tu réponds à une question et ton professeur dit : « That\'s right! » Que veut-il dire ?',
    options: [
      { id: 'a', text: 'Tu as fait une erreur.', isCorrect: false },
      { id: 'b', text: 'C\'est correct / bravo !', isCorrect: true },
      { id: 'c', text: 'Recommence, s\'il te plaît.', isCorrect: false },
    ],
    correctAnswer: 'C\'est correct / bravo !',
    explanation: '« That\'s right! » = c\'est juste ! C\'est une expression d\'encouragement.',
    hint: '« Right » = correct / juste.',
    tags: ['cp', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
];
