import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCpVocFamilleExercises: EnglishExercise[] = [
  {
    id: 'en-cp-voc-026',
    subject: 'anglais',
    title: 'Family : mum',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « mum » en français ?',
    options: [
      { id: 'a', text: 'Papa', isCorrect: false },
      { id: 'b', text: 'Maman', isCorrect: true },
      { id: 'c', text: 'Sœur', isCorrect: false },
    ],
    correctAnswer: 'Maman',
    explanation: '« Mum » veut dire maman en français.',
    hint: 'C\'est le mot affectueux pour la mère.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-027',
    subject: 'anglais',
    title: 'Family : dad',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « dad » en français ?',
    options: [
      { id: 'a', text: 'Papa', isCorrect: true },
      { id: 'b', text: 'Frère', isCorrect: false },
      { id: 'c', text: 'Grand-père', isCorrect: false },
    ],
    correctAnswer: 'Papa',
    explanation: '« Dad » veut dire papa en français.',
    hint: 'C\'est le mot affectueux pour le père.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-028',
    subject: 'anglais',
    title: 'Family : brother',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « brother » en français ?',
    options: [
      { id: 'a', text: 'Sœur', isCorrect: false },
      { id: 'b', text: 'Cousin', isCorrect: false },
      { id: 'c', text: 'Frère', isCorrect: true },
    ],
    correctAnswer: 'Frère',
    explanation: '« Brother » veut dire frère en français.',
    hint: 'C\'est un garçon de la même famille.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-029',
    subject: 'anglais',
    title: 'Family : sister',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « sister » en français ?',
    options: [
      { id: 'a', text: 'Sœur', isCorrect: true },
      { id: 'b', text: 'Cousine', isCorrect: false },
      { id: 'c', text: 'Maman', isCorrect: false },
    ],
    correctAnswer: 'Sœur',
    explanation: '« Sister » veut dire sœur en français.',
    hint: 'C\'est une fille de la même famille.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-030',
    subject: 'anglais',
    title: 'Family : baby',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « baby » en français ?',
    options: [
      { id: 'a', text: 'Un enfant', isCorrect: false },
      { id: 'b', text: 'Un bébé', isCorrect: true },
      { id: 'c', text: 'Un garçon', isCorrect: false },
    ],
    correctAnswer: 'Un bébé',
    explanation: '« Baby » veut dire bébé en français. Ce mot existe aussi en français !',
    hint: 'Ce mot est presque identique en français.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-031',
    subject: 'anglais',
    title: 'Family : grandma',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « grandma » en français ?',
    options: [
      { id: 'a', text: 'Tante', isCorrect: false },
      { id: 'b', text: 'Maman', isCorrect: false },
      { id: 'c', text: 'Grand-mère / mamie', isCorrect: true },
    ],
    correctAnswer: 'Grand-mère / mamie',
    explanation: '« Grandma » veut dire grand-mère (ou mamie) en français.',
    hint: 'C\'est la maman de ton papa ou de ta maman.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-032',
    subject: 'anglais',
    title: 'Family : grandpa',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « grandpa » en français ?',
    options: [
      { id: 'a', text: 'Grand-père / papy', isCorrect: true },
      { id: 'b', text: 'Oncle', isCorrect: false },
      { id: 'c', text: 'Papa', isCorrect: false },
    ],
    correctAnswer: 'Grand-père / papy',
    explanation: '« Grandpa » veut dire grand-père (ou papy) en français.',
    hint: 'C\'est le papa de ton papa ou de ta maman.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-033',
    subject: 'anglais',
    title: 'Family : boy / girl',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « a girl » en français ?',
    options: [
      { id: 'a', text: 'Un garçon', isCorrect: false },
      { id: 'b', text: 'Une fille', isCorrect: true },
      { id: 'c', text: 'Un bébé', isCorrect: false },
    ],
    correctAnswer: 'Une fille',
    explanation: '« Girl » veut dire fille. Le contraire est « boy » (garçon).',
    hint: 'Le contraire est « boy ».',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-034',
    subject: 'anglais',
    title: 'Family : family',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « my family » en français ?',
    options: [
      { id: 'a', text: 'Mon école', isCorrect: false },
      { id: 'b', text: 'Ma famille', isCorrect: true },
      { id: 'c', text: 'Mon ami', isCorrect: false },
    ],
    correctAnswer: 'Ma famille',
    explanation: '« Family » veut dire famille. « My » veut dire mon/ma.',
    hint: '« Family » ressemble beaucoup au mot français !',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-035',
    subject: 'anglais',
    title: 'Family : friend',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot en français ?',
    prompt: 'Que veut dire « my friend » en français ?',
    options: [
      { id: 'a', text: 'Mon frère', isCorrect: false },
      { id: 'b', text: 'Mon ami(e)', isCorrect: true },
      { id: 'c', text: 'Mon chien', isCorrect: false },
    ],
    correctAnswer: 'Mon ami(e)',
    explanation: '« Friend » veut dire ami ou amie en français.',
    hint: 'C\'est quelqu\'un avec qui tu joues à l\'école.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-036',
    subject: 'anglais',
    title: 'Family : le bon mot',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis le bon mot anglais.',
    prompt: 'Comment dit-on « frère » en anglais ?',
    options: [
      { id: 'a', text: 'sister', isCorrect: false },
      { id: 'b', text: 'brother', isCorrect: true },
      { id: 'c', text: 'dad', isCorrect: false },
    ],
    correctAnswer: 'brother',
    explanation: '« Brother » veut dire frère. « Sister » veut dire sœur.',
    hint: 'Ce n\'est pas sister — sister c\'est une fille.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-037',
    subject: 'anglais',
    title: 'Family : le bon mot 2',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis le bon mot anglais.',
    prompt: 'Comment dit-on « grand-mère » en anglais ?',
    options: [
      { id: 'a', text: 'grandpa', isCorrect: false },
      { id: 'b', text: 'mum', isCorrect: false },
      { id: 'c', text: 'grandma', isCorrect: true },
    ],
    correctAnswer: 'grandma',
    explanation: '« Grandma » veut dire grand-mère ou mamie. « Grandpa » veut dire grand-père.',
    hint: '« grandma » et « grandpa » — le « ma » ou « pa » à la fin change le sens.',
    tags: ['cp', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
