import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCpVocCouleursExercises: EnglishExercise[] = [
  {
    id: 'en-cp-voc-001',
    subject: 'anglais',
    title: 'Couleur : red',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « red » en français ?',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: true },
      { id: 'b', text: 'Bleu', isCorrect: false },
      { id: 'c', text: 'Vert', isCorrect: false },
    ],
    correctAnswer: 'Rouge',
    explanation: '« Red » veut dire rouge en français.',
    hint: 'Pense à la couleur du feu.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-002',
    subject: 'anglais',
    title: 'Couleur : blue',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « blue » en français ?',
    options: [
      { id: 'a', text: 'Jaune', isCorrect: false },
      { id: 'b', text: 'Bleu', isCorrect: true },
      { id: 'c', text: 'Vert', isCorrect: false },
    ],
    correctAnswer: 'Bleu',
    explanation: '« Blue » veut dire bleu en français.',
    hint: 'Pense à la couleur du ciel.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-003',
    subject: 'anglais',
    title: 'Couleur : yellow',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « yellow » en français ?',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: false },
      { id: 'b', text: 'Orange', isCorrect: false },
      { id: 'c', text: 'Jaune', isCorrect: true },
    ],
    correctAnswer: 'Jaune',
    explanation: '« Yellow » veut dire jaune en français.',
    hint: 'Pense à la couleur du soleil.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-011',
    subject: 'anglais',
    title: 'Couleur : pink',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « pink » en français ?',
    options: [
      { id: 'a', text: 'Violet', isCorrect: false },
      { id: 'b', text: 'Rose', isCorrect: true },
      { id: 'c', text: 'Orange', isCorrect: false },
    ],
    correctAnswer: 'Rose',
    explanation: '« Pink » veut dire rose en français.',
    hint: 'Pense à la couleur des flamants roses.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-012',
    subject: 'anglais',
    title: 'Couleur : white',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction du mot anglais ?',
    prompt: 'Que veut dire « white » en français ?',
    options: [
      { id: 'a', text: 'Noir', isCorrect: false },
      { id: 'b', text: 'Gris', isCorrect: false },
      { id: 'c', text: 'Blanc', isCorrect: true },
    ],
    correctAnswer: 'Blanc',
    explanation: '« White » veut dire blanc en français.',
    hint: 'Pense à la couleur de la neige.',
    tags: ['cp', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
