import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCpVocSalutationsExercises: EnglishExercise[] = [
  {
    id: 'en-cp-voc-009',
    subject: 'anglais',
    title: 'Salutation : hello',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette salutation ?',
    prompt: 'Que veut dire « Hello » en français ?',
    options: [
      { id: 'a', text: 'Bonjour', isCorrect: true },
      { id: 'b', text: 'Au revoir', isCorrect: false },
      { id: 'c', text: 'Merci', isCorrect: false },
    ],
    correctAnswer: 'Bonjour',
    explanation: '« Hello » veut dire Bonjour en français.',
    hint: "C'est ce qu'on dit en arrivant.",
    tags: ['cp', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-010',
    subject: 'anglais',
    title: 'Salutation : goodbye',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette salutation ?',
    prompt: 'Que veut dire « Goodbye » en français ?',
    options: [
      { id: 'a', text: 'Bonjour', isCorrect: false },
      { id: 'b', text: 'Merci', isCorrect: false },
      { id: 'c', text: 'Au revoir', isCorrect: true },
    ],
    correctAnswer: 'Au revoir',
    explanation: '« Goodbye » veut dire Au revoir en français.',
    hint: "C'est ce qu'on dit en partant.",
    tags: ['cp', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-021',
    subject: 'anglais',
    title: 'Salutation : thank you',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « Thank you » en français ?',
    options: [
      { id: 'a', text: "S'il te plaît", isCorrect: false },
      { id: 'b', text: 'Merci', isCorrect: true },
      { id: 'c', text: 'Pardon', isCorrect: false },
    ],
    correctAnswer: 'Merci',
    explanation: '« Thank you » veut dire merci en français.',
    hint: "C'est ce qu'on dit quand quelqu'un nous aide.",
    tags: ['cp', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
