import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCpVocAnimauxExercises: EnglishExercise[] = [
  {
    id: 'en-cp-voc-004',
    subject: 'anglais',
    title: 'Animal : cat',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a cat » en français ?',
    options: [
      { id: 'a', text: 'Un chien', isCorrect: false },
      { id: 'b', text: 'Un chat', isCorrect: true },
      { id: 'c', text: 'Un lapin', isCorrect: false },
    ],
    correctAnswer: 'Un chat',
    explanation: '« Cat » veut dire chat en français.',
    hint: 'Cet animal fait « miaou ».',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-005',
    subject: 'anglais',
    title: 'Animal : dog',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a dog » en français ?',
    options: [
      { id: 'a', text: 'Un chat', isCorrect: false },
      { id: 'b', text: 'Un chien', isCorrect: true },
      { id: 'c', text: 'Un oiseau', isCorrect: false },
    ],
    correctAnswer: 'Un chien',
    explanation: '« Dog » veut dire chien en français.',
    hint: 'Cet animal fait « ouaf ».',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-006',
    subject: 'anglais',
    title: 'Animal : fish',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a fish » en français ?',
    options: [
      { id: 'a', text: 'Un poisson', isCorrect: true },
      { id: 'b', text: 'Un cheval', isCorrect: false },
      { id: 'c', text: 'Un lapin', isCorrect: false },
    ],
    correctAnswer: 'Un poisson',
    explanation: '« Fish » veut dire poisson en français.',
    hint: "Cet animal vit dans l'eau.",
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-013',
    subject: 'anglais',
    title: 'Animal : bird',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a bird » en français ?',
    options: [
      { id: 'a', text: 'Un chat', isCorrect: false },
      { id: 'b', text: 'Un oiseau', isCorrect: true },
      { id: 'c', text: 'Un cheval', isCorrect: false },
    ],
    correctAnswer: 'Un oiseau',
    explanation: '« Bird » veut dire oiseau en français.',
    hint: 'Cet animal a des ailes et vole.',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-014',
    subject: 'anglais',
    title: 'Animal : rabbit',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a rabbit » en français ?',
    options: [
      { id: 'a', text: 'Un renard', isCorrect: false },
      { id: 'b', text: 'Un cochon', isCorrect: false },
      { id: 'c', text: 'Un lapin', isCorrect: true },
    ],
    correctAnswer: 'Un lapin',
    explanation: '« Rabbit » veut dire lapin en français.',
    hint: 'Cet animal a de grandes oreilles et saute.',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-015',
    subject: 'anglais',
    title: 'Animal : lion',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a lion » en français ?',
    options: [
      { id: 'a', text: 'Un tigre', isCorrect: false },
      { id: 'b', text: 'Un lion', isCorrect: true },
      { id: 'c', text: 'Un éléphant', isCorrect: false },
    ],
    correctAnswer: 'Un lion',
    explanation: '« Lion » se dit pareil en français et en anglais !',
    hint: 'Ce mot ressemble au mot français.',
    tags: ['cp', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
