import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCpVocVetementsExercises: EnglishExercise[] = [
  {
    id: 'en-cp-voc-067',
    subject: 'anglais',
    title: 'Vêtements : shirt',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « shirt » en français ?',
    options: [
      { id: 'a', text: 'La jupe', isCorrect: false },
      { id: 'b', text: 'La chemise', isCorrect: true },
      { id: 'c', text: 'Le pantalon', isCorrect: false },
    ],
    correctAnswer: 'La chemise',
    explanation: '« Shirt » = chemise. On la porte sur le haut du corps.',
    hint: 'On la porte sur le haut du corps (avec des boutons).',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-068',
    subject: 'anglais',
    title: 'Vêtements : trousers',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « trousers » en français ?',
    options: [
      { id: 'a', text: 'Le pantalon', isCorrect: true },
      { id: 'b', text: 'Les chaussures', isCorrect: false },
      { id: 'c', text: 'La veste', isCorrect: false },
    ],
    correctAnswer: 'Le pantalon',
    explanation: '« Trousers » = pantalon. En anglais américain, on dit « pants ».',
    hint: 'On le porte sur les jambes.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-069',
    subject: 'anglais',
    title: 'Vêtements : dress',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « dress » en français ?',
    options: [
      { id: 'a', text: 'Le manteau', isCorrect: false },
      { id: 'b', text: 'La robe', isCorrect: true },
      { id: 'c', text: 'La jupe', isCorrect: false },
    ],
    correctAnswer: 'La robe',
    explanation: '« Dress » = robe. Une robe couvre le haut et le bas du corps.',
    hint: 'Vêtement d\'une seule pièce pour le corps entier.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-070',
    subject: 'anglais',
    title: 'Vêtements : shoes',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « shoes » en français ?',
    options: [
      { id: 'a', text: 'Les chaussettes', isCorrect: false },
      { id: 'b', text: 'Les chaussures', isCorrect: true },
      { id: 'c', text: 'Les bottes', isCorrect: false },
    ],
    correctAnswer: 'Les chaussures',
    explanation: '« Shoes » = chaussures. On les met aux pieds.',
    hint: 'On les met aux pieds pour marcher.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-071',
    subject: 'anglais',
    title: 'Vêtements : socks',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « socks » en français ?',
    options: [
      { id: 'a', text: 'Les gants', isCorrect: false },
      { id: 'b', text: 'Les chaussures', isCorrect: false },
      { id: 'c', text: 'Les chaussettes', isCorrect: true },
    ],
    correctAnswer: 'Les chaussettes',
    explanation: '« Socks » = chaussettes. On les met avant les chaussures.',
    hint: 'On les porte avant de mettre les shoes.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-072',
    subject: 'anglais',
    title: 'Vêtements : hat',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « hat » en français ?',
    options: [
      { id: 'a', text: 'Le chapeau', isCorrect: true },
      { id: 'b', text: 'L\'écharpe', isCorrect: false },
      { id: 'c', text: 'Les gants', isCorrect: false },
    ],
    correctAnswer: 'Le chapeau',
    explanation: '« Hat » = chapeau. On le met sur la tête.',
    hint: 'On le porte sur la tête.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-073',
    subject: 'anglais',
    title: 'Vêtements : coat',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « coat » en français ?',
    options: [
      { id: 'a', text: 'Le pull', isCorrect: false },
      { id: 'b', text: 'Le manteau', isCorrect: true },
      { id: 'c', text: 'La veste', isCorrect: false },
    ],
    correctAnswer: 'Le manteau',
    explanation: '« Coat » = manteau. On le porte quand il fait froid.',
    hint: 'On le met quand il fait froid dehors.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-074',
    subject: 'anglais',
    title: 'Vêtements : skirt',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « skirt » en français ?',
    options: [
      { id: 'a', text: 'La robe', isCorrect: false },
      { id: 'b', text: 'La jupe', isCorrect: true },
      { id: 'c', text: 'Le short', isCorrect: false },
    ],
    correctAnswer: 'La jupe',
    explanation: '« Skirt » = jupe. La jupe couvre la partie basse du corps.',
    hint: 'Vêtement qui couvre seulement la partie basse.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-075',
    subject: 'anglais',
    title: 'Vêtements : T-shirt',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « T-shirt » en français ?',
    options: [
      { id: 'a', text: 'Le T-shirt', isCorrect: true },
      { id: 'b', text: 'La chemise', isCorrect: false },
      { id: 'c', text: 'Le pull', isCorrect: false },
    ],
    correctAnswer: 'Le T-shirt',
    explanation: '« T-shirt » = T-shirt. C\'est le même mot en français !',
    hint: 'Ce mot est identique en français !',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-076',
    subject: 'anglais',
    title: 'Vêtements : boots',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « boots » en français ?',
    options: [
      { id: 'a', text: 'Les sandales', isCorrect: false },
      { id: 'b', text: 'Les bottes', isCorrect: true },
      { id: 'c', text: 'Les chaussures de sport', isCorrect: false },
    ],
    correctAnswer: 'Les bottes',
    explanation: '« Boots » = bottes. On les porte quand il pleut ou qu\'il fait froid.',
    hint: 'On les porte sous la pluie ou dans la neige.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-077',
    subject: 'anglais',
    title: 'Vêtements : scarf',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « scarf » en français ?',
    options: [
      { id: 'a', text: 'Les gants', isCorrect: false },
      { id: 'b', text: 'L\'écharpe', isCorrect: true },
      { id: 'c', text: 'Le chapeau', isCorrect: false },
    ],
    correctAnswer: 'L\'écharpe',
    explanation: '« Scarf » = écharpe. On la porte autour du cou quand il fait froid.',
    hint: 'On la met autour du cou pour avoir chaud.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-078',
    subject: 'anglais',
    title: 'Vêtements : gloves',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « gloves » en français ?',
    options: [
      { id: 'a', text: 'Les gants', isCorrect: true },
      { id: 'b', text: 'L\'écharpe', isCorrect: false },
      { id: 'c', text: 'Les chaussettes', isCorrect: false },
    ],
    correctAnswer: 'Les gants',
    explanation: '« Gloves » = gants. On les met aux mains quand il fait très froid.',
    hint: 'On les met aux mains pour avoir chaud.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-079',
    subject: 'anglais',
    title: 'Vêtements : shorts',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « shorts » en français ?',
    options: [
      { id: 'a', text: 'Le pantalon', isCorrect: false },
      { id: 'b', text: 'Le short', isCorrect: true },
      { id: 'c', text: 'La jupe', isCorrect: false },
    ],
    correctAnswer: 'Le short',
    explanation: '« Shorts » = short. Même mot en français !',
    hint: 'Même mot en français, on le porte quand il fait chaud.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-080',
    subject: 'anglais',
    title: 'Vêtements : jumper',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « jumper » en français ?',
    options: [
      { id: 'a', text: 'Le manteau', isCorrect: false },
      { id: 'b', text: 'Le pull', isCorrect: true },
      { id: 'c', text: 'La veste', isCorrect: false },
    ],
    correctAnswer: 'Le pull',
    explanation: '« Jumper » = pull (en anglais britannique). On dit aussi « sweater » en anglais américain.',
    hint: 'Vêtement chaud qu\'on enfile par la tête.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-081',
    subject: 'anglais',
    title: 'Vêtements : jacket',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « jacket » en français ?',
    options: [
      { id: 'a', text: 'La veste', isCorrect: true },
      { id: 'b', text: 'Le pull', isCorrect: false },
      { id: 'c', text: 'Le manteau', isCorrect: false },
    ],
    correctAnswer: 'La veste',
    explanation: '« Jacket » = veste. Plus courte et légère qu\'un manteau.',
    hint: 'Plus courte qu\'un coat.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-082',
    subject: 'anglais',
    title: 'Vêtements : pyjamas',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « pyjamas » en français ?',
    options: [
      { id: 'a', text: 'Les vêtements de sport', isCorrect: false },
      { id: 'b', text: 'Le pyjama', isCorrect: true },
      { id: 'c', text: 'L\'uniforme scolaire', isCorrect: false },
    ],
    correctAnswer: 'Le pyjama',
    explanation: '« Pyjamas » = pyjama. Même mot en français !',
    hint: 'On le porte pour dormir.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-cp-voc-083',
    subject: 'anglais',
    title: 'Vêtements : phrase complète',
    schoolClass: 'CP',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'vetements',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I wear a hat and a scarf » en français ?',
    options: [
      { id: 'a', text: 'Je porte des gants et des bottes.', isCorrect: false },
      { id: 'b', text: 'Je porte un chapeau et une écharpe.', isCorrect: true },
      { id: 'c', text: 'Je porte un manteau et des chaussures.', isCorrect: false },
    ],
    correctAnswer: 'Je porte un chapeau et une écharpe.',
    explanation: '« Wear » = porter. « Hat » = chapeau. « Scarf » = écharpe.',
    hint: '« Wear » = porter. On identifie hat et scarf.',
    tags: ['cp', 'anglais', 'vocabulaire', 'vetements', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
  },
];
