import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe2LogiqueExercises: MathExercise[] = [
  {
    id: 'ma-ce2-logique-001',
    subject: 'mathematiques',
    title: 'Suite des nombres impairs',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '1, 3, 5, 7, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '9', isCorrect: true },
      { id: 'c', text: '11', isCorrect: false },
    ],
    correctAnswer: '9',
    explanation: 'Ce sont les nombres impairs. On ajoute 2 à chaque fois : 7 + 2 = 9.',
    hint: 'De combien augmente-t-on à chaque fois ?',
    tags: ['ce2', 'logique', 'suite', 'impairs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'ma-ce2-logique-002',
    subject: 'mathematiques',
    title: 'Suite des dizaines',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '10, 20, 30, 40, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '45', isCorrect: false },
      { id: 'b', text: '48', isCorrect: false },
      { id: 'c', text: '50', isCorrect: true },
    ],
    correctAnswer: '50',
    explanation: 'On ajoute 10 à chaque fois : 40 + 10 = 50.',
    hint: "C'est la table de 10.",
    tags: ['ce2', 'logique', 'suite', 'dizaines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'ma-ce2-logique-003',
    subject: 'mathematiques',
    title: 'Suite par 7',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '7, 14, 21, 28, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '33', isCorrect: false },
      { id: 'b', text: '35', isCorrect: true },
      { id: 'c', text: '36', isCorrect: false },
    ],
    correctAnswer: '35',
    explanation: 'On ajoute 7 : 28 + 7 = 35.',
    hint: 'C\'est la table de 7.',
    tags: ['ce2', 'logique', 'suite', 'table_7', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-004',
    subject: 'mathematiques',
    title: 'Intrus de la table',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Trouve l\'intrus.',
    prompt: '12, 18, 24, 29, 36. Quel est l\'intrus ?',
    options: [
      { id: 'a', text: '18', isCorrect: false },
      { id: 'b', text: '24', isCorrect: false },
      { id: 'c', text: '29', isCorrect: true },
    ],
    correctAnswer: '29',
    explanation: '12, 18, 24, 36 sont tous dans la table de 6. 29 n\'y est pas.',
    hint: 'Vérifie lequel n\'est pas divisible par 6.',
    tags: ['ce2', 'logique', 'intrus', 'table_6', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-005',
    subject: 'mathematiques',
    title: 'Lire un tableau croisé',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de données',
    format: 'qcm',
    instructions: 'Lis le tableau et réponds.',
    prompt: 'Dans la classe, 8 filles et 7 garçons ont un animal. Combien d\'élèves en tout ont un animal ?',
    options: [
      { id: 'a', text: '14', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: '16', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: '8 + 7 = 15 élèves.',
    hint: 'Additionne les filles et les garçons.',
    tags: ['ce2', 'logique', 'tableau', 'données', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-006',
    subject: 'mathematiques',
    title: 'Suite des carrés',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '1, 4, 9, 16, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '20', isCorrect: false },
      { id: 'b', text: '25', isCorrect: true },
      { id: 'c', text: '30', isCorrect: false },
    ],
    correctAnswer: '25',
    explanation: 'Ce sont les carrés : 1², 2², 3², 4², 5² = 25.',
    hint: '1×1, 2×2, 3×3, 4×4… et ensuite ?',
    tags: ['ce2', 'logique', 'suite', 'carrés', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-007',
    subject: 'mathematiques',
    title: 'Déduction',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'raisonnement',
    format: 'qcm',
    instructions: 'Raisonne.',
    prompt: 'J\'ai un nombre. Je lui ajoute 6 et j\'obtiens 15. Quel est ce nombre ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '9', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '9',
    explanation: '? + 6 = 15, donc ? = 15 − 6 = 9.',
    hint: 'Si ? + 6 = 15, alors ? = 15 − 6.',
    tags: ['ce2', 'logique', 'raisonnement', 'equation', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-008',
    subject: 'mathematiques',
    title: 'Suite +6',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '6, 12, 18, 24, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '28', isCorrect: false },
      { id: 'b', text: '30', isCorrect: true },
      { id: 'c', text: '32', isCorrect: false },
    ],
    correctAnswer: '30',
    explanation: 'On ajoute 6 à chaque fois : 24 + 6 = 30.',
    hint: 'C\'est la table de multiplication de 6.',
    tags: ['ce2', 'logique', 'suite', 'table-6', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-009',
    subject: 'mathematiques',
    title: 'Diagramme de Venn',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'données',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '10 enfants aiment le foot, 8 aiment le basket, et 3 aiment les deux. Combien aiment au moins un sport ?',
    options: [
      { id: 'a', text: '15', isCorrect: true },
      { id: 'b', text: '18', isCorrect: false },
      { id: 'c', text: '21', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: '10 + 8 − 3 = 15 (on retire les 3 comptés deux fois).',
    hint: 'Évite de compter deux fois ceux qui aiment les deux.',
    tags: ['ce2', 'logique', 'ensembles', 'données', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-010',
    subject: 'mathematiques',
    title: 'Intrus dans les multiples de 3',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'classification',
    format: 'qcm',
    instructions: 'Trouve l\'intrus.',
    prompt: 'Parmi 9, 12, 16, 18, lequel n\'est pas un multiple de 3 ?',
    options: [
      { id: 'a', text: '9', isCorrect: false },
      { id: 'b', text: '16', isCorrect: true },
      { id: 'c', text: '18', isCorrect: false },
    ],
    correctAnswer: '16',
    explanation: '16 ÷ 3 = 5 reste 1. Ce n\'est pas un multiple de 3.',
    hint: 'Un nombre est multiple de 3 si la somme de ses chiffres est divisible par 3.',
    tags: ['ce2', 'logique', 'multiples', 'intrus', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-011',
    subject: 'mathematiques',
    title: 'Suite décroissante −7',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le terme suivant.',
    prompt: '63, 56, 49, 42, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '33', isCorrect: false },
      { id: 'b', text: '35', isCorrect: true },
      { id: 'c', text: '37', isCorrect: false },
    ],
    correctAnswer: '35',
    explanation: 'On enlève 7 à chaque fois : 42 − 7 = 35.',
    hint: 'C\'est la table de 7 à rebours.',
    tags: ['ce2', 'logique', 'suite', 'décroissante', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-012',
    subject: 'mathematiques',
    title: 'Tableau : scores',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de tableau',
    format: 'qcm',
    instructions: 'Lis le tableau.',
    prompt: 'Scores : Alice = 24, Bob = 18, Cléa = 31. Quel est le score total des trois ?',
    options: [
      { id: 'a', text: '71', isCorrect: false },
      { id: 'b', text: '73', isCorrect: true },
      { id: 'c', text: '75', isCorrect: false },
    ],
    correctAnswer: '73',
    explanation: '24 + 18 + 31 = 73.',
    hint: 'Additionne les 3 scores.',
    tags: ['ce2', 'logique', 'tableau', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-ce2-logique-013',
    subject: 'mathematiques',
    title: 'Déduction : quel jour ?',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'déduction',
    format: 'qcm',
    instructions: 'Résous l\'énigme.',
    prompt: 'Aujourd\'hui c\'est mercredi. Dans 5 jours, quel jour sera-t-on ?',
    options: [
      { id: 'a', text: 'Dimanche', isCorrect: false },
      { id: 'b', text: 'Lundi', isCorrect: true },
      { id: 'c', text: 'Mardi', isCorrect: false },
    ],
    correctAnswer: 'Lundi',
    explanation: 'Mercredi + 5 = Jeudi, Vendredi, Samedi, Dimanche, Lundi.',
    hint: 'Compte 5 jours à partir de mercredi.',
    tags: ['ce2', 'logique', 'déduction', 'calendrier', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
];
