import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe2NumerationExercises: MathExercise[] = [
  {
    id: 'ma-ce2-numeration-001',
    subject: 'mathematiques',
    title: 'Chiffre des centaines',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'centaines',
    format: 'qcm',
    instructions: 'Trouve le chiffre des centaines.',
    prompt: 'Quel est le chiffre des centaines dans 347 ?',
    options: [
      { id: 'a', text: '3', isCorrect: true },
      { id: 'b', text: '4', isCorrect: false },
      { id: 'c', text: '7', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: 'Dans 347 : 3 est le chiffre des centaines, 4 des dizaines, 7 des unités.',
    hint: "Les centaines, c'est le premier chiffre à gauche dans un nombre à 3 chiffres.",
    tags: ['ce2', 'numeration', 'centaines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-002',
    subject: 'mathematiques',
    title: 'Décomposition en centaines',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'centaines',
    format: 'qcm',
    instructions: 'Décompose le nombre.',
    prompt: '345 = ___ centaines, ___ dizaines, ___ unités',
    options: [
      { id: 'a', text: '3 centaines, 4 dizaines, 5 unités', isCorrect: true },
      { id: 'b', text: '4 centaines, 3 dizaines, 5 unités', isCorrect: false },
      { id: 'c', text: '3 centaines, 5 dizaines, 4 unités', isCorrect: false },
    ],
    correctAnswer: '3 centaines, 4 dizaines, 5 unités',
    explanation: '345 = 3 centaines + 4 dizaines + 5 unités. De gauche à droite : centaines, dizaines, unités.',
    hint: 'De gauche à droite : centaines, dizaines, unités.',
    tags: ['ce2', 'numeration', 'centaines', 'décomposition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-003',
    subject: 'mathematiques',
    title: 'Comparer des nombres à 3 chiffres',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Quel est le plus grand nombre ?',
    prompt: '489, 498 ou 487 ?',
    options: [
      { id: 'a', text: '489', isCorrect: false },
      { id: 'b', text: '498', isCorrect: true },
      { id: 'c', text: '487', isCorrect: false },
    ],
    correctAnswer: '498',
    explanation: '498 > 489 > 487. Les centaines sont identiques (4), donc on compare les dizaines : 9 > 8.',
    hint: 'Les centaines sont pareilles, compare les dizaines.',
    tags: ['ce2', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-004',
    subject: 'mathematiques',
    title: 'Le double',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'double et moitié',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'Quel est le double de 35 ?',
    options: [
      { id: 'a', text: '60', isCorrect: false },
      { id: 'b', text: '65', isCorrect: false },
      { id: 'c', text: '70', isCorrect: true },
    ],
    correctAnswer: '70',
    explanation: 'Le double de 35 = 35 × 2 = 70.',
    hint: '35 + 35 = ?',
    tags: ['ce2', 'numeration', 'double', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Multiplie 35 par 2.' },
    }),
  },
  {
    id: 'ma-ce2-numeration-005',
    subject: 'mathematiques',
    title: 'La moitié',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'double et moitié',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'Quelle est la moitié de 80 ?',
    options: [
      { id: 'a', text: '35', isCorrect: false },
      { id: 'b', text: '40', isCorrect: true },
      { id: 'c', text: '45', isCorrect: false },
    ],
    correctAnswer: '40',
    explanation: 'La moitié de 80 = 80 ÷ 2 = 40.',
    hint: '80 ÷ 2 = ?',
    tags: ['ce2', 'numeration', 'moitié', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'ma-ce2-numeration-006',
    subject: 'mathematiques',
    title: 'Nombre pair ou impair',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'parité',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '237 est pair ou impair ?',
    options: [
      { id: 'a', text: 'Pair', isCorrect: false },
      { id: 'b', text: 'Impair', isCorrect: true },
      { id: 'c', text: 'Les deux', isCorrect: false },
    ],
    correctAnswer: 'Impair',
    explanation: '237 se termine par 7, qui est impair. Donc 237 est impair.',
    hint: 'Un nombre impair se termine par 1, 3, 5, 7 ou 9.',
    tags: ['ce2', 'numeration', 'pair', 'impair', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-007',
    subject: 'mathematiques',
    title: 'Millier',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'milliers',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de centaines y a-t-il dans 1 000 ?',
    options: [
      { id: 'a', text: '10', isCorrect: true },
      { id: 'b', text: '100', isCorrect: false },
      { id: 'c', text: '1 000', isCorrect: false },
    ],
    correctAnswer: '10',
    explanation: '1 000 = 10 centaines. 10 × 100 = 1 000.',
    hint: '100, 200, 300... jusqu\'à 1000 : combien de centaines ?',
    tags: ['ce2', 'numeration', 'millier', 'centaines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-008',
    subject: 'mathematiques',
    title: 'Ordre décroissant',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'ordre',
    format: 'qcm',
    instructions: 'Range dans l\'ordre décroissant.',
    prompt: '214, 421, 142. Quel est le bon ordre décroissant ?',
    options: [
      { id: 'a', text: '142, 214, 421', isCorrect: false },
      { id: 'b', text: '421, 214, 142', isCorrect: true },
      { id: 'c', text: '421, 142, 214', isCorrect: false },
    ],
    correctAnswer: '421, 214, 142',
    explanation: '421 > 214 > 142. Ordre décroissant : du plus grand au plus petit.',
    hint: 'Commence par le plus grand.',
    tags: ['ce2', 'numeration', 'ordre', 'decroissant', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-009',
    subject: 'mathematiques',
    title: 'Encadrement par centaines',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Encadre le nombre par centaines.',
    prompt: '573 est entre quelles centaines ?',
    options: [
      { id: 'a', text: '400 et 500', isCorrect: false },
      { id: 'b', text: '500 et 600', isCorrect: true },
      { id: 'c', text: '600 et 700', isCorrect: false },
    ],
    correctAnswer: '500 et 600',
    explanation: '500 < 573 < 600.',
    hint: 'Regarde le chiffre des centaines de 573.',
    tags: ['ce2', 'numeration', 'encadrement', 'centaines', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-010',
    subject: 'mathematiques',
    title: 'Arrondi à la dizaine',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'arrondi',
    format: 'qcm',
    instructions: 'Arrondis à la dizaine.',
    prompt: 'Arrondis 347 à la dizaine.',
    options: [
      { id: 'a', text: '340', isCorrect: false },
      { id: 'b', text: '350', isCorrect: true },
      { id: 'c', text: '300', isCorrect: false },
    ],
    correctAnswer: '350',
    explanation: '347 : le chiffre des unités est 7 (≥ 5), donc on arrondit à 350.',
    hint: 'Si les unités ≥ 5, on monte à la dizaine supérieure.',
    tags: ['ce2', 'numeration', 'arrondi', 'dizaine', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-011',
    subject: 'mathematiques',
    title: 'Suite par 100',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Trouve le nombre suivant.',
    prompt: '200, 300, 400, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '450', isCorrect: false },
      { id: 'b', text: '500', isCorrect: true },
      { id: 'c', text: '600', isCorrect: false },
    ],
    correctAnswer: '500',
    explanation: 'On ajoute 100 à chaque fois : 400 + 100 = 500.',
    hint: 'C\'est la table de 100.',
    tags: ['ce2', 'numeration', 'suite', 'centaines', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-012',
    subject: 'mathematiques',
    title: 'Millier',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'milliers',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '4 milliers = ?',
    options: [
      { id: 'a', text: '400', isCorrect: false },
      { id: 'b', text: '4000', isCorrect: true },
      { id: 'c', text: '40000', isCorrect: false },
    ],
    correctAnswer: '4000',
    explanation: '1 millier = 1000. Donc 4 milliers = 4 × 1000 = 4000.',
    hint: '1 millier = 1000.',
    tags: ['ce2', 'numeration', 'milliers', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-013',
    subject: 'mathematiques',
    title: 'Décomposer 3457',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'décomposition',
    format: 'qcm',
    instructions: 'Décompose ce nombre.',
    prompt: '3457 = ___ milliers + ___ centaines + ___ dizaines + ___ unités',
    options: [
      { id: 'a', text: '3 m + 4 c + 5 d + 7 u', isCorrect: true },
      { id: 'b', text: '4 m + 3 c + 5 d + 7 u', isCorrect: false },
      { id: 'c', text: '3 m + 5 c + 4 d + 7 u', isCorrect: false },
    ],
    correctAnswer: '3 m + 4 c + 5 d + 7 u',
    explanation: '3457 = 3000 + 400 + 50 + 7.',
    hint: 'Lis chaque chiffre de gauche à droite.',
    tags: ['ce2', 'numeration', 'décomposition', 'milliers', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-014',
    subject: 'mathematiques',
    title: 'Comparer 2345 et 2435',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'numeration',
    subskill: 'comparaison',
    format: 'qcm',
    instructions: 'Compare.',
    prompt: 'Quel est le plus grand : 2345 ou 2435 ?',
    options: [
      { id: 'a', text: '2345', isCorrect: false },
      { id: 'b', text: '2435', isCorrect: true },
      { id: 'c', text: 'Ils sont égaux', isCorrect: false },
    ],
    correctAnswer: '2435',
    explanation: '2435 > 2345. Les milliers (2) et les unités (5) sont identiques, mais 4 centaines > 3 centaines.',
    hint: 'Compare chiffre par chiffre de gauche à droite.',
    tags: ['ce2', 'numeration', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-015',
    subject: 'mathematiques',
    title: 'Arrondir à la centaine',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'numeration',
    subskill: 'arrondis',
    format: 'qcm',
    instructions: 'Arrondis à la centaine la plus proche.',
    prompt: '1472 arrondi à la centaine la plus proche ?',
    options: [
      { id: 'a', text: '1400', isCorrect: false },
      { id: 'b', text: '1500', isCorrect: true },
      { id: 'c', text: '1600', isCorrect: false },
    ],
    correctAnswer: '1500',
    explanation: '1472 est entre 1400 et 1500. 72 > 50, donc on arrondit à 1500.',
    hint: 'Regarde les dizaines : si ≥ 50, on arrondit au-dessus.',
    tags: ['ce2', 'numeration', 'arrondis', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-016',
    subject: 'mathematiques',
    title: 'Valeur positionnelle de 5678',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'valeur positionnelle',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans 5678, que représente le chiffre 6 ?',
    options: [
      { id: 'a', text: '6 unités', isCorrect: false },
      { id: 'b', text: '6 centaines', isCorrect: true },
      { id: 'c', text: '6 dizaines', isCorrect: false },
    ],
    correctAnswer: '6 centaines',
    explanation: '5678 = 5 m + 6 c + 7 d + 8 u. Le 6 est à la place des centaines.',
    hint: 'Compte les places de droite à gauche : unités, dizaines, centaines, milliers.',
    tags: ['ce2', 'numeration', 'valeur-positionnelle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-ce2-numeration-017',
    subject: 'mathematiques',
    title: 'Suite par milliers',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'suite numérique',
    format: 'qcm',
    instructions: 'Continue la suite.',
    prompt: '1000, 2000, 3000, ___ . Quel est le nombre suivant ?',
    options: [
      { id: 'a', text: '3500', isCorrect: false },
      { id: 'b', text: '4000', isCorrect: true },
      { id: 'c', text: '5000', isCorrect: false },
    ],
    correctAnswer: '4000',
    explanation: 'On ajoute 1000 à chaque fois : 3000 + 1000 = 4000.',
    hint: 'La suite avance de 1000 en 1000.',
    tags: ['ce2', 'numeration', 'suite', 'milliers', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
];
