import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCe2MesuresExercises: MathExercise[] = [
  {
    id: 'ma-ce2-mesures-001',
    subject: 'mathematiques',
    title: 'Mètre et centimètre',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '1 m = ___ cm ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '100', isCorrect: true },
      { id: 'c', text: '1000', isCorrect: false },
    ],
    correctAnswer: '100',
    explanation: '1 mètre = 100 centimètres.',
    hint: 'Cent veut dire 100.',
    tags: ['ce2', 'mesures', 'conversions', 'longueurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-002',
    subject: 'mathematiques',
    title: 'Durée en minutes',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'temps',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: 'Un film dure 1 heure 30 minutes. Combien de minutes cela fait-il ?',
    options: [
      { id: 'a', text: '60', isCorrect: false },
      { id: 'b', text: '90', isCorrect: true },
      { id: 'c', text: '130', isCorrect: false },
    ],
    correctAnswer: '90',
    explanation: '1 heure = 60 minutes. 60 + 30 = 90 minutes. Pas 130 (1 heure ne fait pas 100 min).',
    hint: "Combien de minutes y a-t-il dans 1 heure ?",
    tags: ['ce2', 'mesures', 'temps', 'minutes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-003',
    subject: 'mathematiques',
    title: 'Additionner des masses',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'masses',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '500 g + 300 g = ?',
    options: [
      { id: 'a', text: '700 g', isCorrect: false },
      { id: 'b', text: '800 g', isCorrect: true },
      { id: 'c', text: '900 g', isCorrect: false },
    ],
    correctAnswer: '800 g',
    explanation: '500 + 300 = 800 g.',
    hint: '5 + 3 = 8, donc 500 + 300 = 800.',
    tags: ['ce2', 'mesures', 'masse', 'grammes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'ma-ce2-mesures-004',
    subject: 'mathematiques',
    title: 'Convertir km en m',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'conversions de longueur',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '3 km = ___ m ?',
    options: [
      { id: 'a', text: '30 m', isCorrect: false },
      { id: 'b', text: '300 m', isCorrect: false },
      { id: 'c', text: '3 000 m', isCorrect: true },
    ],
    correctAnswer: '3 000 m',
    explanation: '1 km = 1 000 m, donc 3 km = 3 × 1 000 = 3 000 m.',
    hint: '1 km = 1 000 m.',
    tags: ['ce2', 'mesures', 'longueur', 'km', 'conversion', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { extraHint: '1 km = 1 000 m. Multiplie 3 × 1 000.' },
    }),
  },
  {
    id: 'ma-ce2-mesures-005',
    subject: 'mathematiques',
    title: 'Kg en grammes',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '2 kg = ___ g ?',
    options: [
      { id: 'a', text: '200', isCorrect: false },
      { id: 'b', text: '2 000', isCorrect: true },
      { id: 'c', text: '20 000', isCorrect: false },
    ],
    correctAnswer: '2 000',
    explanation: '1 kg = 1 000 g. 2 kg = 2 × 1 000 = 2 000 g.',
    hint: '1 kg = 1 000 g.',
    tags: ['ce2', 'mesures', 'masse', 'kg', 'grammes', 'conversion', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-006',
    subject: 'mathematiques',
    title: 'Heure et minutes',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'temps',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '90 minutes = ___ heure(s) ___ minutes',
    options: [
      { id: 'a', text: '1 heure 20 minutes', isCorrect: false },
      { id: 'b', text: '1 heure 30 minutes', isCorrect: true },
      { id: 'c', text: '2 heures', isCorrect: false },
    ],
    correctAnswer: '1 heure 30 minutes',
    explanation: '90 min = 60 min + 30 min = 1 heure 30 minutes.',
    hint: '1 heure = 60 minutes. 90 − 60 = 30 minutes.',
    tags: ['ce2', 'mesures', 'temps', 'minutes', 'heures', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-007',
    subject: 'mathematiques',
    title: 'Prix total et monnaie',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'monnaie',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'Une baguette coûte 1,20 €. J\'en achète 4. Combien je paie ?',
    options: [
      { id: 'a', text: '4 €', isCorrect: false },
      { id: 'b', text: '4,60 €', isCorrect: false },
      { id: 'c', text: '4,80 €', isCorrect: true },
    ],
    correctAnswer: '4,80 €',
    explanation: '4 × 1,20 = 4,80 €.',
    hint: '1,20 + 1,20 + 1,20 + 1,20 = ?',
    tags: ['ce2', 'mesures', 'monnaie', 'multiplication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-008',
    subject: 'mathematiques',
    title: 'Longueur d\'un trajet aller-retour',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'longueurs',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'La maison est à 300 m de l\'école. Combien Paul parcourt-il pour faire l\'aller-retour ?',
    options: [
      { id: 'a', text: '300 m', isCorrect: false },
      { id: 'b', text: '600 m', isCorrect: true },
      { id: 'c', text: '900 m', isCorrect: false },
    ],
    correctAnswer: '600 m',
    explanation: 'Aller-retour = 300 × 2 = 600 m.',
    hint: 'Aller + retour = 2 fois la distance.',
    tags: ['ce2', 'mesures', 'longueur', 'aller_retour', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-009',
    subject: 'mathematiques',
    title: 'Litre et millilitre',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '1 litre = ___ millilitres ?',
    options: [
      { id: 'a', text: '10 mL', isCorrect: false },
      { id: 'b', text: '100 mL', isCorrect: false },
      { id: 'c', text: '1 000 mL', isCorrect: true },
    ],
    correctAnswer: '1 000 mL',
    explanation: '1 L = 1 000 mL.',
    hint: 'Milli- veut dire 1/1000.',
    tags: ['ce2', 'mesures', 'contenance', 'litre', 'millilitre', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-010',
    subject: 'mathematiques',
    title: 'Date du calendrier',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'mesures',
    subskill: 'calendrier',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Février a 28 jours (ou 29 en année bissextile). Combien de semaines cela fait-il au minimum ?',
    options: [
      { id: 'a', text: '3 semaines', isCorrect: false },
      { id: 'b', text: '4 semaines', isCorrect: true },
      { id: 'c', text: '5 semaines', isCorrect: false },
    ],
    correctAnswer: '4 semaines',
    explanation: '28 jours ÷ 7 = 4 semaines.',
    hint: '1 semaine = 7 jours. 28 ÷ 7 = ?',
    tags: ['ce2', 'mesures', 'calendrier', 'semaine', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-011',
    subject: 'mathematiques',
    title: '1,5 L en cL',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '1,5 L = ___ cL',
    options: [
      { id: 'a', text: '15 cL', isCorrect: false },
      { id: 'b', text: '150 cL', isCorrect: true },
      { id: 'c', text: '1500 cL', isCorrect: false },
    ],
    correctAnswer: '150 cL',
    explanation: '1 L = 100 cL. Donc 1,5 L = 150 cL.',
    hint: '1 L = 100 cL.',
    tags: ['ce2', 'mesures', 'contenance', 'conversion', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-012',
    subject: 'mathematiques',
    title: 'Vitesse simple',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'mesures',
    subskill: 'vitesse',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un cycliste roule à 20 km/h. En 2 heures, quelle distance parcourt-il ?',
    options: [
      { id: 'a', text: '30 km', isCorrect: false },
      { id: 'b', text: '40 km', isCorrect: true },
      { id: 'c', text: '50 km', isCorrect: false },
    ],
    correctAnswer: '40 km',
    explanation: 'Distance = vitesse × temps = 20 × 2 = 40 km.',
    hint: 'Multiplie la vitesse par le nombre d\'heures.',
    tags: ['ce2', 'mesures', 'vitesse', 'distance', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-013',
    subject: 'mathematiques',
    title: 'Périmètre d\'un jardin',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Calcule le périmètre.',
    prompt: 'Un jardin rectangulaire de 12 m × 8 m. Quel est son périmètre ?',
    options: [
      { id: 'a', text: '36 m', isCorrect: false },
      { id: 'b', text: '40 m', isCorrect: true },
      { id: 'c', text: '44 m', isCorrect: false },
    ],
    correctAnswer: '40 m',
    explanation: 'Périmètre = 2 × (12 + 8) = 2 × 20 = 40 m.',
    hint: 'Périmètre = 2 × (longueur + largeur).',
    tags: ['ce2', 'mesures', 'périmètre', 'rectangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-014',
    subject: 'mathematiques',
    title: 'Durée entre deux heures',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Calcule la durée.',
    prompt: 'Départ à 10h15, arrivée à 12h45. Quelle est la durée du trajet ?',
    options: [
      { id: 'a', text: '2h15', isCorrect: false },
      { id: 'b', text: '2h30', isCorrect: true },
      { id: 'c', text: '2h45', isCorrect: false },
    ],
    correctAnswer: '2h30',
    explanation: 'De 10h15 à 12h15 = 2h. De 12h15 à 12h45 = 30 min. Total = 2h30.',
    hint: 'De 10h15 à 12h45, compte les heures et les minutes séparément.',
    tags: ['ce2', 'mesures', 'durée', 'horaire', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-015',
    subject: 'mathematiques',
    title: 'Aire d\'un carré de 9 cm',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'mesures',
    subskill: 'aire',
    format: 'qcm',
    instructions: 'Calcule l\'aire.',
    prompt: 'Un carré de côté 9 cm. Quelle est son aire ?',
    options: [
      { id: 'a', text: '72 cm²', isCorrect: false },
      { id: 'b', text: '81 cm²', isCorrect: true },
      { id: 'c', text: '90 cm²', isCorrect: false },
    ],
    correctAnswer: '81 cm²',
    explanation: 'Aire = 9 × 9 = 81 cm².',
    hint: 'Aire du carré = côté × côté.',
    tags: ['ce2', 'mesures', 'aire', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:mesures',
  },
  {
    id: 'ma-ce2-mesures-016',
    subject: 'mathematiques',
    title: '3,5 kg en grammes',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'mesures',
    subskill: 'conversions',
    format: 'qcm',
    instructions: 'Convertis.',
    prompt: '3,5 kg = ___ g',
    options: [
      { id: 'a', text: '350 g', isCorrect: false },
      { id: 'b', text: '3500 g', isCorrect: true },
      { id: 'c', text: '35 000 g', isCorrect: false },
    ],
    correctAnswer: '3500 g',
    explanation: '1 kg = 1000 g. Donc 3,5 kg = 3500 g.',
    hint: '1 kg = 1000 g.',
    tags: ['ce2', 'mesures', 'masse', 'conversion', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:mesures',
  },
];
