import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe1VocNombresExercises: EnglishExercise[] = [
  {
    id: 'en-ce1-voc-011',
    subject: 'anglais',
    title: 'Nombre : ten',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'nombres',
    format: 'qcm',
    instructions: 'Quel nombre est-ce ?',
    prompt: 'Quel est le mot anglais pour le nombre 10 ?',
    options: [
      { id: 'a', text: 'eight', isCorrect: false },
      { id: 'b', text: 'nine', isCorrect: false },
      { id: 'c', text: 'ten', isCorrect: true },
    ],
    correctAnswer: 'ten',
    explanation: 'Le nombre 10 se dit « ten » en anglais.',
    hint: '8 = eight, 9 = nine, 10 = …',
    tags: ['ce1', 'anglais', 'vocabulaire', 'nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-019',
    subject: 'anglais',
    title: 'Nombre : seven',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'nombres',
    format: 'qcm',
    instructions: 'Quel est ce nombre en chiffres ?',
    prompt: 'Combien vaut « seven » en anglais ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: '« Seven » veut dire 7 en français.',
    hint: 'Il y a « seven » jours dans une semaine.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-020',
    subject: 'anglais',
    title: 'Nombre : eight',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'nombres',
    format: 'qcm',
    instructions: 'Quel est ce nombre en chiffres ?',
    prompt: 'Combien vaut « eight » en anglais ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '9', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: '« Eight » veut dire 8 en français.',
    hint: 'Une araignée a « eight » pattes.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'nombres', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
