import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe1VocFamilleExercises: EnglishExercise[] = [
  {
    id: 'en-ce1-voc-028',
    subject: 'anglais',
    title: 'Family : this is my mum',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « This is my mum » en français ?',
    options: [
      { id: 'a', text: 'Voici mon père.', isCorrect: false },
      { id: 'b', text: 'Voici ma maman.', isCorrect: true },
      { id: 'c', text: 'Voici ma sœur.', isCorrect: false },
    ],
    correctAnswer: 'Voici ma maman.',
    explanation: '« This is my… » veut dire « Voici mon/ma… ». « Mum » = maman.',
    hint: '« This is » = voici. « My mum » = ma maman.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-029',
    subject: 'anglais',
    title: 'Family : this is my dad',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « This is my dad » en français ?',
    options: [
      { id: 'a', text: 'Voici mon frère.', isCorrect: false },
      { id: 'b', text: 'Voici mon papa.', isCorrect: true },
      { id: 'c', text: 'Voici mon grand-père.', isCorrect: false },
    ],
    correctAnswer: 'Voici mon papa.',
    explanation: '« Dad » veut dire papa. « This is my dad » = Voici mon papa.',
    hint: '« Dad » et « mum » sont les parents.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-030',
    subject: 'anglais',
    title: 'Family : sister / brother',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis la bonne traduction.',
    prompt: 'Comment dit-on « ma sœur » en anglais ?',
    options: [
      { id: 'a', text: 'my brother', isCorrect: false },
      { id: 'b', text: 'my sister', isCorrect: true },
      { id: 'c', text: 'my mum', isCorrect: false },
    ],
    correctAnswer: 'my sister',
    explanation: '« Sister » = sœur. « Brother » = frère. « My » = mon/ma.',
    hint: '« Sister » est une fille, « brother » est un garçon.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-031',
    subject: 'anglais',
    title: 'Family : grandparents',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « my grandparents » en français ?',
    options: [
      { id: 'a', text: 'Mes parents', isCorrect: false },
      { id: 'b', text: 'Mes grands-parents', isCorrect: true },
      { id: 'c', text: 'Mes oncles et tantes', isCorrect: false },
    ],
    correctAnswer: 'Mes grands-parents',
    explanation: '« Grandparents » = grands-parents. « Grandma » = grand-mère, « grandpa » = grand-père.',
    hint: '« Grand- » devant un mot de famille = l\'échelon au-dessus.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-032',
    subject: 'anglais',
    title: 'Family : uncle / aunt',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « my uncle » en français ?',
    options: [
      { id: 'a', text: 'Mon cousin', isCorrect: false },
      { id: 'b', text: 'Mon oncle', isCorrect: true },
      { id: 'c', text: 'Mon frère', isCorrect: false },
    ],
    correctAnswer: 'Mon oncle',
    explanation: '« Uncle » = oncle. « Aunt » = tante. Ce sont les frères et sœurs de tes parents.',
    hint: '« Uncle » ressemble au mot anglais... regarde bien !',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-033',
    subject: 'anglais',
    title: 'Family : cousin',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « my cousin » en français ?',
    options: [
      { id: 'a', text: 'Mon ami', isCorrect: false },
      { id: 'b', text: 'Mon cousin(e)', isCorrect: true },
      { id: 'c', text: 'Mon frère', isCorrect: false },
    ],
    correctAnswer: 'Mon cousin(e)',
    explanation: '« Cousin » veut dire cousin ou cousine — même mot en anglais et en français !',
    hint: 'Ce mot est identique en français.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-034',
    subject: 'anglais',
    title: 'Family : I have…',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I have one brother » en français ?',
    options: [
      { id: 'a', text: 'J\'ai une sœur.', isCorrect: false },
      { id: 'b', text: 'J\'ai un frère.', isCorrect: true },
      { id: 'c', text: 'Je suis un frère.', isCorrect: false },
    ],
    correctAnswer: 'J\'ai un frère.',
    explanation: '« I have » = j\'ai. « One » = un. « Brother » = frère.',
    hint: '« I have » = j\'ai. « One » = un.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-035',
    subject: 'anglais',
    title: 'Family : I have two sisters',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I have two sisters » en français ?',
    options: [
      { id: 'a', text: 'J\'ai deux frères.', isCorrect: false },
      { id: 'b', text: 'J\'ai deux sœurs.', isCorrect: true },
      { id: 'c', text: 'J\'ai deux cousines.', isCorrect: false },
    ],
    correctAnswer: 'J\'ai deux sœurs.',
    explanation: '« Two » = deux. « Sisters » = sœurs (pluriel de sister).',
    hint: '« Two » = 2. « Sisters » = plusieurs sœurs.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-036',
    subject: 'anglais',
    title: 'Family : He / She',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis le bon pronom.',
    prompt: 'Tu parles de ta sœur. Quel pronom anglais utilises-tu ?',
    options: [
      { id: 'a', text: 'He', isCorrect: false },
      { id: 'b', text: 'She', isCorrect: true },
      { id: 'c', text: 'It', isCorrect: false },
    ],
    correctAnswer: 'She',
    explanation: '« She » = elle (féminin). « He » = il (masculin). Ta sœur est une fille → She.',
    hint: '« She » est pour les filles, « he » pour les garçons.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-037',
    subject: 'anglais',
    title: 'Family : He / She (2)',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis le bon pronom.',
    prompt: 'Tu parles de ton frère. Quel pronom anglais utilises-tu ?',
    options: [
      { id: 'a', text: 'She', isCorrect: false },
      { id: 'b', text: 'He', isCorrect: true },
      { id: 'c', text: 'They', isCorrect: false },
    ],
    correctAnswer: 'He',
    explanation: '« He » = il (masculin). Ton frère est un garçon → He.',
    hint: '« He » est pour un garçon.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-038',
    subject: 'anglais',
    title: 'Family : parents',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « my parents » en français ?',
    options: [
      { id: 'a', text: 'Mes amis', isCorrect: false },
      { id: 'b', text: 'Mes parents', isCorrect: true },
      { id: 'c', text: 'Mes grands-parents', isCorrect: false },
    ],
    correctAnswer: 'Mes parents',
    explanation: '« Parents » est le même mot en anglais et en français !',
    hint: 'Ce mot est identique dans les deux langues.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-039',
    subject: 'anglais',
    title: 'Family : le bon mot',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'famille',
    format: 'qcm',
    instructions: 'Choisis le bon mot anglais.',
    prompt: 'Comment dit-on « tante » en anglais ?',
    options: [
      { id: 'a', text: 'uncle', isCorrect: false },
      { id: 'b', text: 'cousin', isCorrect: false },
      { id: 'c', text: 'aunt', isCorrect: true },
    ],
    correctAnswer: 'aunt',
    explanation: '« Aunt » = tante. « Uncle » = oncle. Ne confonds pas les deux !',
    hint: '« Aunt » est pour une femme (la sœur de ton parent).',
    tags: ['ce1', 'anglais', 'vocabulaire', 'famille', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
