import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe1VocAnimauxExercises: EnglishExercise[] = [
  {
    id: 'en-ce1-voc-003',
    subject: 'anglais',
    title: 'Animal : horse',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a horse » en français ?',
    options: [
      { id: 'a', text: 'Un cheval', isCorrect: true },
      { id: 'b', text: 'Un mouton', isCorrect: false },
      { id: 'c', text: 'Une vache', isCorrect: false },
    ],
    correctAnswer: 'Un cheval',
    explanation: '« Horse » veut dire cheval en français.',
    hint: 'On peut le monter et il galope.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-004',
    subject: 'anglais',
    title: 'Animal : bird',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a bird » en français ?',
    options: [
      { id: 'a', text: 'Un lapin', isCorrect: false },
      { id: 'b', text: 'Un oiseau', isCorrect: true },
      { id: 'c', text: 'Un cochon', isCorrect: false },
    ],
    correctAnswer: 'Un oiseau',
    explanation: '« Bird » veut dire oiseau en français.',
    hint: 'Cet animal a des ailes et vole.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-005',
    subject: 'anglais',
    title: 'Animal : rabbit',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a rabbit » en français ?',
    options: [
      { id: 'a', text: 'Un lapin', isCorrect: true },
      { id: 'b', text: 'Un chien', isCorrect: false },
      { id: 'c', text: 'Un poisson', isCorrect: false },
    ],
    correctAnswer: 'Un lapin',
    explanation: '« Rabbit » veut dire lapin en français.',
    hint: 'Il a de grandes oreilles et saute.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-015',
    subject: 'anglais',
    title: 'Animal : cow',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a cow » en français ?',
    options: [
      { id: 'a', text: 'Un cochon', isCorrect: false },
      { id: 'b', text: 'Une vache', isCorrect: true },
      { id: 'c', text: 'Un mouton', isCorrect: false },
    ],
    correctAnswer: 'Une vache',
    explanation: '« Cow » veut dire vache en français.',
    hint: 'Cet animal donne du lait.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-016',
    subject: 'anglais',
    title: 'Animal : pig',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'animaux',
    format: 'qcm',
    instructions: 'Quel est cet animal en français ?',
    prompt: 'Que veut dire « a pig » en français ?',
    options: [
      { id: 'a', text: 'Un canard', isCorrect: false },
      { id: 'b', text: 'Un lapin', isCorrect: false },
      { id: 'c', text: 'Un cochon', isCorrect: true },
    ],
    correctAnswer: 'Un cochon',
    explanation: '« Pig » veut dire cochon en français.',
    hint: 'Cet animal dit « groin groin ».',
    tags: ['ce1', 'anglais', 'vocabulaire', 'animaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
