import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe1VocCouleursExercises: EnglishExercise[] = [
  {
    id: 'en-ce1-voc-001',
    subject: 'anglais',
    title: 'Couleur : green',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « green » en français ?',
    options: [
      { id: 'a', text: 'Vert', isCorrect: true },
      { id: 'b', text: 'Noir', isCorrect: false },
      { id: 'c', text: 'Blanc', isCorrect: false },
    ],
    correctAnswer: 'Vert',
    explanation: '« Green » veut dire vert en français.',
    hint: "Pense à la couleur de l'herbe.",
    tags: ['ce1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-002',
    subject: 'anglais',
    title: 'Couleur : black',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « black » en français ?',
    options: [
      { id: 'a', text: 'Rouge', isCorrect: false },
      { id: 'b', text: 'Blanc', isCorrect: false },
      { id: 'c', text: 'Noir', isCorrect: true },
    ],
    correctAnswer: 'Noir',
    explanation: '« Black » veut dire noir en français.',
    hint: 'Pense à la couleur de la nuit.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-013',
    subject: 'anglais',
    title: 'Couleur : pink',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « pink » en français ?',
    options: [
      { id: 'a', text: 'Violet', isCorrect: false },
      { id: 'b', text: 'Rose', isCorrect: true },
      { id: 'c', text: 'Marron', isCorrect: false },
    ],
    correctAnswer: 'Rose',
    explanation: '« Pink » veut dire rose en français.',
    hint: 'Pense aux flamants roses.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-014',
    subject: 'anglais',
    title: 'Couleur : orange',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'couleurs',
    format: 'qcm',
    instructions: 'Quelle est la traduction ?',
    prompt: 'Que veut dire « orange » en anglais ?',
    options: [
      { id: 'a', text: 'Jaune', isCorrect: false },
      { id: 'b', text: 'Rouge', isCorrect: false },
      { id: 'c', text: 'Orange', isCorrect: true },
    ],
    correctAnswer: 'Orange',
    explanation: '« Orange » se dit pareil en français et en anglais !',
    hint: 'Ce mot existe dans les deux langues.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'couleurs', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
