import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe1VocMaisonExercises: EnglishExercise[] = [
  {
    id: 'en-ce1-voc-053',
    subject: 'anglais',
    title: 'La maison : upstairs / downstairs',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « upstairs » en français ?',
    options: [
      { id: 'a', text: 'En bas / au rez-de-chaussée', isCorrect: false },
      { id: 'b', text: 'En haut / à l\'étage', isCorrect: true },
      { id: 'c', text: 'Dans le jardin', isCorrect: false },
    ],
    correctAnswer: 'En haut / à l\'étage',
    explanation: '« Upstairs » = en haut, à l\'étage. « Downstairs » = en bas, au rez-de-chaussée.',
    hint: '« Up » = vers le haut.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-054',
    subject: 'anglais',
    title: 'La maison : my bedroom is upstairs',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « My bedroom is upstairs » en français ?',
    options: [
      { id: 'a', text: 'Ma chambre est en bas.', isCorrect: false },
      { id: 'b', text: 'Ma chambre est en haut.', isCorrect: true },
      { id: 'c', text: 'Ma chambre est grande.', isCorrect: false },
    ],
    correctAnswer: 'Ma chambre est en haut.',
    explanation: '« My bedroom » = ma chambre. « Upstairs » = en haut (à l\'étage).',
    hint: '« Upstairs » = à l\'étage = en haut.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-055',
    subject: 'anglais',
    title: 'La maison : the kitchen is downstairs',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « The kitchen is downstairs » en français ?',
    options: [
      { id: 'a', text: 'La cuisine est à l\'étage.', isCorrect: false },
      { id: 'b', text: 'La cuisine est en bas.', isCorrect: true },
      { id: 'c', text: 'La cuisine est petite.', isCorrect: false },
    ],
    correctAnswer: 'La cuisine est en bas.',
    explanation: '« Downstairs » = en bas, au rez-de-chaussée. Contraire d\'« upstairs ».',
    hint: '« Down » = vers le bas.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-056',
    subject: 'anglais',
    title: 'La maison : in the kitchen',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « The cat is in the kitchen » en français ?',
    options: [
      { id: 'a', text: 'Le chat est dans le salon.', isCorrect: false },
      { id: 'b', text: 'Le chat est dans la cuisine.', isCorrect: true },
      { id: 'c', text: 'Le chat est dans le jardin.', isCorrect: false },
    ],
    correctAnswer: 'Le chat est dans la cuisine.',
    explanation: '« In the kitchen » = dans la cuisine. « In » = dans.',
    hint: '« In » = dans.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-057',
    subject: 'anglais',
    title: 'La maison : on the table',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « The book is on the table » en français ?',
    options: [
      { id: 'a', text: 'Le livre est sous la table.', isCorrect: false },
      { id: 'b', text: 'Le livre est sur la table.', isCorrect: true },
      { id: 'c', text: 'Le livre est à côté de la table.', isCorrect: false },
    ],
    correctAnswer: 'Le livre est sur la table.',
    explanation: '« On » = sur. « On the table » = sur la table.',
    hint: '« On » = sur (en contact avec la surface).',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-058',
    subject: 'anglais',
    title: 'La maison : under the bed',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « The ball is under the bed » en français ?',
    options: [
      { id: 'a', text: 'La balle est sur le lit.', isCorrect: false },
      { id: 'b', text: 'La balle est sous le lit.', isCorrect: true },
      { id: 'c', text: 'La balle est dans le lit.', isCorrect: false },
    ],
    correctAnswer: 'La balle est sous le lit.',
    explanation: '« Under » = sous. « Under the bed » = sous le lit.',
    hint: '« Under » = sous (en dessous).',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-059',
    subject: 'anglais',
    title: 'La maison : next to the sofa',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « next to the sofa » en français ?',
    options: [
      { id: 'a', text: 'Derrière le canapé', isCorrect: false },
      { id: 'b', text: 'À côté du canapé', isCorrect: true },
      { id: 'c', text: 'Sur le canapé', isCorrect: false },
    ],
    correctAnswer: 'À côté du canapé',
    explanation: '« Next to » = à côté de. « The sofa » = le canapé.',
    hint: '« Next to » = juste à côté.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-060',
    subject: 'anglais',
    title: 'La maison : in front of the TV',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Que veut dire « in front of the TV » en français ?',
    options: [
      { id: 'a', text: 'Derrière la télé', isCorrect: false },
      { id: 'b', text: 'Devant la télé', isCorrect: true },
      { id: 'c', text: 'À côté de la télé', isCorrect: false },
    ],
    correctAnswer: 'Devant la télé',
    explanation: '« In front of » = devant. « In front of the TV » = devant la télé.',
    hint: '« In front of » = devant (face à).',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-061',
    subject: 'anglais',
    title: 'La maison : my house',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « My house has three bedrooms » en français ?',
    options: [
      { id: 'a', text: 'Ma maison est grande.', isCorrect: false },
      { id: 'b', text: 'Ma maison a trois chambres.', isCorrect: true },
      { id: 'c', text: 'Ma maison a trois étages.', isCorrect: false },
    ],
    correctAnswer: 'Ma maison a trois chambres.',
    explanation: '« My house has three bedrooms » = ma maison a trois chambres.',
    hint: '« Bedrooms » = chambres (au pluriel).',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-062',
    subject: 'anglais',
    title: 'La maison : garage',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « garage » en français ?',
    options: [
      { id: 'a', text: 'Le jardin', isCorrect: false },
      { id: 'b', text: 'Le garage', isCorrect: true },
      { id: 'c', text: 'La cave', isCorrect: false },
    ],
    correctAnswer: 'Le garage',
    explanation: '« Garage » = garage. Même mot en français et en anglais !',
    hint: 'On y gare la voiture. Même mot qu\'en français !',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-063',
    subject: 'anglais',
    title: 'La maison : fence',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « fence » en français ?',
    options: [
      { id: 'a', text: 'La porte d\'entrée', isCorrect: false },
      { id: 'b', text: 'La clôture / la barrière', isCorrect: true },
      { id: 'c', text: 'Le mur', isCorrect: false },
    ],
    correctAnswer: 'La clôture / la barrière',
    explanation: '« Fence » = clôture / barrière. Elle entoure le jardin.',
    hint: 'Elle délimite le jardin.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-064',
    subject: 'anglais',
    title: 'La maison : doorbell',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « doorbell » en français ?',
    options: [
      { id: 'a', text: 'La clé de la maison', isCorrect: false },
      { id: 'b', text: 'La sonnette', isCorrect: true },
      { id: 'c', text: 'La boîte aux lettres', isCorrect: false },
    ],
    correctAnswer: 'La sonnette',
    explanation: '« Doorbell » = sonnette. « Door » = porte + « bell » = cloche.',
    hint: '« Bell » = cloche. On appuie dessus pour annoncer sa visite.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-065',
    subject: 'anglais',
    title: 'La maison : letterbox',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « letterbox » en français ?',
    options: [
      { id: 'a', text: 'La sonnette', isCorrect: false },
      { id: 'b', text: 'La boîte aux lettres', isCorrect: true },
      { id: 'c', text: 'La porte d\'entrée', isCorrect: false },
    ],
    correctAnswer: 'La boîte aux lettres',
    explanation: '« Letterbox » = boîte aux lettres. « Letter » = lettre + « box » = boîte.',
    hint: '« Letter » = lettre. Le facteur y dépose le courrier.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-066',
    subject: 'anglais',
    title: 'La maison : neighbour',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « neighbour » en français ?',
    options: [
      { id: 'a', text: 'L\'ami', isCorrect: false },
      { id: 'b', text: 'Le voisin', isCorrect: true },
      { id: 'c', text: 'Le facteur', isCorrect: false },
    ],
    correctAnswer: 'Le voisin',
    explanation: '« Neighbour » = voisin. La personne qui habite à côté de chez toi.',
    hint: 'Personne qui habite près de chez toi.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-067',
    subject: 'anglais',
    title: 'La maison : I live in a flat',
    schoolClass: 'CE1',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I live in a flat » en français ?',
    options: [
      { id: 'a', text: 'J\'habite dans une maison.', isCorrect: false },
      { id: 'b', text: 'J\'habite dans un appartement.', isCorrect: true },
      { id: 'c', text: 'J\'habite dans une ferme.', isCorrect: false },
    ],
    correctAnswer: 'J\'habite dans un appartement.',
    explanation: '« Flat » = appartement (en anglais britannique). On dit aussi « apartment » en anglais américain.',
    hint: '« Flat » = appartement (pas une maison).',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-068',
    subject: 'anglais',
    title: 'La maison : attic',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Que veut dire ce mot ?',
    prompt: 'Que veut dire « attic » en français ?',
    options: [
      { id: 'a', text: 'La cave', isCorrect: false },
      { id: 'b', text: 'Le grenier', isCorrect: true },
      { id: 'c', text: 'Le garage', isCorrect: false },
    ],
    correctAnswer: 'Le grenier',
    explanation: '« Attic » = grenier. C\'est la pièce tout en haut de la maison, sous le toit.',
    hint: 'Pièce tout en haut, sous le toit.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce1-voc-069',
    subject: 'anglais',
    title: 'La maison : choisir la bonne préposition',
    schoolClass: 'CE1',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'maison',
    format: 'qcm',
    instructions: 'Choisis la bonne préposition.',
    prompt: 'Complète : « The dog is ___ the sofa. » (dessous)',
    options: [
      { id: 'a', text: 'on', isCorrect: false },
      { id: 'b', text: 'under', isCorrect: true },
      { id: 'c', text: 'next to', isCorrect: false },
    ],
    correctAnswer: 'under',
    explanation: '« Under » = sous / en dessous. Le chien est sous le canapé.',
    hint: 'Le chien est en dessous du canapé.',
    tags: ['ce1', 'anglais', 'vocabulaire', 'maison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
