import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCm1NumerationExercises: MathExercise[] = [
  {
    id: 'ma-cm1-numeration-001',
    subject: 'mathematiques',
    title: 'Chiffre des dixièmes',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'nombres décimaux',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans le nombre 4,73, quel est le chiffre des dixièmes ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '3', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: 'Dans 4,73 : 4 est la partie entière, 7 est le chiffre des dixièmes, 3 est le chiffre des centièmes.',
    hint: "Le premier chiffre après la virgule, c'est les dixièmes.",
    tags: ['cm1', 'numeration', 'décimaux', 'dixièmes', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Regarde après la virgule.', extraHint: '4 , 7 3 → dixièmes = 7.' },
      progressif: { splitSteps: ['Repère la virgule.', 'Le 1er chiffre après = dixièmes.', 'Quel est-il dans 4,73 ?'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-002',
    subject: 'mathematiques',
    title: 'Comparer des décimaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'nombres décimaux',
    format: 'qcm',
    instructions: 'Quel est le plus grand ?',
    prompt: 'Quel est le plus grand : 3,5 ou 3,48 ?',
    options: [
      { id: 'a', text: '3,48', isCorrect: false },
      { id: 'b', text: '3,5', isCorrect: true },
      { id: 'c', text: 'Ils sont égaux', isCorrect: false },
    ],
    correctAnswer: '3,5',
    explanation: '3,5 = 3,50 > 3,48. Le chiffre des dixièmes de 3,5 est 5, celui de 3,48 est 4.',
    hint: '3,5 = 3,50. Compare les dixièmes : 5 > 4.',
    tags: ['cm1', 'numeration', 'décimaux', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-003',
    subject: 'mathematiques',
    title: 'Placer un décimal sur une droite',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'nombres décimaux',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '2,7 est entre quels entiers consécutifs ?',
    options: [
      { id: 'a', text: 'Entre 1 et 2', isCorrect: false },
      { id: 'b', text: 'Entre 2 et 3', isCorrect: true },
      { id: 'c', text: 'Entre 3 et 4', isCorrect: false },
    ],
    correctAnswer: 'Entre 2 et 3',
    explanation: '2 < 2,7 < 3. La partie entière est 2.',
    hint: 'La partie entière de 2,7 est 2.',
    tags: ['cm1', 'numeration', 'décimaux', 'droite', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-004',
    subject: 'mathematiques',
    title: 'Arrondi à l\'entier',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'arrondi',
    format: 'qcm',
    instructions: 'Arrondis à l\'entier le plus proche.',
    prompt: 'Arrondis 5,3 à l\'entier.',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '5', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '5',
    explanation: '5,3 : les dixièmes sont 3 (< 5), donc on arrondit à 5.',
    hint: 'Si les dixièmes < 5, on arrondit vers le bas.',
    tags: ['cm1', 'numeration', 'décimaux', 'arrondi', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-005',
    subject: 'mathematiques',
    title: 'Décomposer un décimal',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'nombres décimaux',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '5,6 = 5 + ___',
    options: [
      { id: 'a', text: '0,6', isCorrect: true },
      { id: 'b', text: '6', isCorrect: false },
      { id: 'c', text: '0,06', isCorrect: false },
    ],
    correctAnswer: '0,6',
    explanation: '5,6 = 5 + 0,6. La partie décimale est 6 dixièmes = 0,6.',
    hint: '5,6 = 5 entiers + 6 dixièmes = 5 + 0,6.',
    tags: ['cm1', 'numeration', 'décimaux', 'décomposition', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-006',
    subject: 'mathematiques',
    title: 'Ordre de décimaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'ordre',
    format: 'qcm',
    instructions: 'Range dans l\'ordre croissant.',
    prompt: '4,2 ; 4,02 ; 4,22. Quel est l\'ordre croissant ?',
    options: [
      { id: 'a', text: '4,22 ; 4,2 ; 4,02', isCorrect: false },
      { id: 'b', text: '4,02 ; 4,2 ; 4,22', isCorrect: true },
      { id: 'c', text: '4,2 ; 4,02 ; 4,22', isCorrect: false },
    ],
    correctAnswer: '4,02 ; 4,2 ; 4,22',
    explanation: '4,02 < 4,2 < 4,22.',
    hint: 'Compare les dixièmes d\'abord : 0 < 2.',
    tags: ['cm1', 'numeration', 'décimaux', 'ordre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-007',
    subject: 'mathematiques',
    title: 'Encadrement d\'un décimal',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'encadrement',
    format: 'qcm',
    instructions: 'Encadre le décimal au dixième.',
    prompt: '3,47 est entre quels dixièmes ?',
    options: [
      { id: 'a', text: '3,3 et 3,4', isCorrect: false },
      { id: 'b', text: '3,4 et 3,5', isCorrect: true },
      { id: 'c', text: '3,5 et 3,6', isCorrect: false },
    ],
    correctAnswer: '3,4 et 3,5',
    explanation: '3,4 < 3,47 < 3,5.',
    hint: 'Regarde le chiffre des dixièmes : 4. Donc entre 3,4 et 3,5.',
    tags: ['cm1', 'numeration', 'décimaux', 'encadrement', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-008',
    subject: 'mathematiques',
    title: 'Fractions et décimaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'fractions décimales',
    format: 'qcm',
    instructions: 'Convertis cette fraction en décimal.',
    prompt: '3/10 = ?',
    options: [
      { id: 'a', text: '0,03', isCorrect: false },
      { id: 'b', text: '0,3', isCorrect: true },
      { id: 'c', text: '3,0', isCorrect: false },
    ],
    correctAnswer: '0,3',
    explanation: '3/10 = 3 dixièmes = 0,3.',
    hint: 'Les fractions /10 donnent des dixièmes.',
    tags: ['cm1', 'numeration', 'fractions', 'décimaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-009',
    subject: 'mathematiques',
    title: 'Placer 4,35 sur la droite',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'numeration',
    subskill: 'droite numérique',
    format: 'qcm',
    instructions: 'Situe ce nombre.',
    prompt: '4,35 est entre quelles valeurs ?',
    options: [
      { id: 'a', text: 'Entre 4,2 et 4,3', isCorrect: false },
      { id: 'b', text: 'Entre 4,3 et 4,4', isCorrect: true },
      { id: 'c', text: 'Entre 4,4 et 4,5', isCorrect: false },
    ],
    correctAnswer: 'Entre 4,3 et 4,4',
    explanation: '4,3 < 4,35 < 4,4.',
    hint: 'Regarde les dixièmes : 3. Donc entre 4,3 et 4,4.',
    tags: ['cm1', 'numeration', 'décimaux', 'droite', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-010',
    subject: 'mathematiques',
    title: 'Décomposer 8,07',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'décomposition décimale',
    format: 'qcm',
    instructions: 'Décompose ce nombre.',
    prompt: '8,07 = ?',
    options: [
      { id: 'a', text: '8 + 0,7', isCorrect: false },
      { id: 'b', text: '8 + 0,07', isCorrect: true },
      { id: 'c', text: '8 + 0,007', isCorrect: false },
    ],
    correctAnswer: '8 + 0,07',
    explanation: '8,07 = 8 unités + 0 dixièmes + 7 centièmes = 8 + 0,07.',
    hint: 'Le 0 est aux dixièmes, le 7 aux centièmes.',
    tags: ['cm1', 'numeration', 'décimaux', 'décomposition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-011',
    subject: 'mathematiques',
    title: 'Arrondir 6,85 à l\'unité',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'numeration',
    subskill: 'arrondis',
    format: 'qcm',
    instructions: 'Arrondis à l\'unité la plus proche.',
    prompt: '6,85 arrondi à l\'unité ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: '6,85 : la partie décimale (0,85) est ≥ 0,5, donc on arrondit à 7.',
    hint: 'Si la partie décimale ≥ 0,5, on monte.',
    tags: ['cm1', 'numeration', 'arrondis', 'décimaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
  {
    id: 'ma-cm1-numeration-012',
    subject: 'mathematiques',
    title: 'Ranger des décimaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'numeration',
    subskill: 'ordre',
    format: 'qcm',
    instructions: 'Range dans l\'ordre croissant.',
    prompt: '1,2 ; 1,09 ; 1,18 — Quel est l\'ordre croissant ?',
    options: [
      { id: 'a', text: '1,2 ; 1,18 ; 1,09', isCorrect: false },
      { id: 'b', text: '1,09 ; 1,18 ; 1,2', isCorrect: true },
      { id: 'c', text: '1,18 ; 1,09 ; 1,2', isCorrect: false },
    ],
    correctAnswer: '1,09 ; 1,18 ; 1,2',
    explanation: '1,09 < 1,18 < 1,20.',
    hint: 'Aligne les décimaux pour comparer.',
    tags: ['cm1', 'numeration', 'décimaux', 'ordre', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:numeration',
  },
];
