import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCm1ProblemesExercises: MathExercise[] = [
  {
    id: 'ma-cm1-problemes-001',
    subject: 'mathematiques',
    title: "Durée d'un trajet",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'durée',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Un train part à 9h15 et arrive à 11h45. Combien de temps dure le trajet ?',
    options: [
      { id: 'a', text: '2h', isCorrect: false },
      { id: 'b', text: '2h15', isCorrect: false },
      { id: 'c', text: '2h30', isCorrect: true },
    ],
    correctAnswer: '2h30',
    explanation: 'De 9h15 à 11h45 : il y a 2h30 (9h15 + 2h30 = 11h45).',
    hint: 'Calcule de 9h15 à 11h15 (2h), puis de 11h15 à 11h45 (30 min).',
    tags: ['cm1', 'problemes', 'durée', 'temps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-002',
    subject: 'mathematiques',
    title: 'Partage équitable',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'problemes',
    subskill: 'division',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: '5 enfants se partagent 35 billes équitablement. Combien chacun en reçoit ?',
    options: [
      { id: 'a', text: '6', isCorrect: false },
      { id: 'b', text: '7', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '7',
    explanation: '35 ÷ 5 = 7 billes chacun.',
    hint: "Divise le nombre total par le nombre d'enfants.",
    tags: ['cm1', 'problemes', 'division', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-003',
    subject: 'mathematiques',
    title: 'Coût total de stylos',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: 'Un stylo coûte 1,50 €. Marie en achète 4. Combien paie-t-elle ?',
    options: [
      { id: 'a', text: '5 €', isCorrect: false },
      { id: 'b', text: '6 €', isCorrect: true },
      { id: 'c', text: '7 €', isCorrect: false },
    ],
    correctAnswer: '6 €',
    explanation: '4 × 1,50 = 6 €.',
    hint: '1,50 + 1,50 + 1,50 + 1,50 = ?',
    tags: ['cm1', 'problemes', 'multiplication', 'décimaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-004',
    subject: 'mathematiques',
    title: "Fraction d'un groupe",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Lis le problème et trouve la réponse.',
    prompt: "Un tiers d'une classe de 30 élèves part en sortie. Combien d'élèves partent ?",
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '10', isCorrect: true },
      { id: 'c', text: '12', isCorrect: false },
    ],
    correctAnswer: '10',
    explanation: '1/3 de 30 = 30 ÷ 3 = 10 élèves.',
    hint: "Un tiers, c'est diviser par 3.",
    tags: ['cm1', 'problemes', 'fractions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-005',
    subject: 'mathematiques',
    title: "Le tiers d'une quantité",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'fractions en contexte',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un sachet contient 24 bonbons. On mange le tiers. Combien de bonbons reste-t-il ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '12', isCorrect: false },
      { id: 'c', text: '16', isCorrect: true },
    ],
    correctAnswer: '16',
    explanation: 'Le tiers de 24 = 24 ÷ 3 = 8. Il reste 24 − 8 = 16 bonbons.',
    hint: "Calcule d'abord 24 ÷ 3, puis soustrait.",
    tags: ['cm1', 'problemes', 'fractions', 'tiers', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 24 ÷ 3 = le tiers.', 'Soustrait ce tiers de 24.'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-006',
    subject: 'mathematiques',
    title: 'Achat avec décimaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'décimaux en contexte',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un stylo coûte 1,50 € et un cahier coûte 2,70 €. Combien coûtent 2 stylos et 1 cahier ?',
    options: [
      { id: 'a', text: '5,20 €', isCorrect: false },
      { id: 'b', text: '5,70 €', isCorrect: true },
      { id: 'c', text: '6,20 €', isCorrect: false },
    ],
    correctAnswer: '5,70 €',
    explanation: '2 × 1,50 + 2,70 = 3,00 + 2,70 = 5,70 €.',
    hint: 'Calcule d\'abord le prix des 2 stylos.',
    tags: ['cm1', 'problemes', 'décimaux', 'monnaie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 2 × 1,50.', 'Ajoute 2,70.'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-007',
    subject: 'mathematiques',
    title: 'Distance et fractions',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Léa a parcouru les 2/5 d\'un trajet de 20 km. Combien de km lui reste-t-il ?',
    options: [
      { id: 'a', text: '8 km', isCorrect: false },
      { id: 'b', text: '10 km', isCorrect: false },
      { id: 'c', text: '12 km', isCorrect: true },
    ],
    correctAnswer: '12 km',
    explanation: '2/5 de 20 km = 2 × (20 ÷ 5) = 2 × 4 = 8 km parcourus. Reste : 20 − 8 = 12 km.',
    hint: 'Calcule d\'abord 2/5 de 20, puis soustrais.',
    tags: ['cm1', 'problemes', 'fractions', 'distance', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 1/5 de 20 km.', 'Multiplie par 2.', 'Soustrais de 20.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-008',
    subject: 'mathematiques',
    title: 'Économies et achat',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'multi-étapes',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Hugo gagne 2,50 € par semaine. En 4 semaines, il achète un livre à 8 €. Combien lui reste-t-il ?',
    options: [
      { id: 'a', text: '1,50 €', isCorrect: false },
      { id: 'b', text: '2 €', isCorrect: true },
      { id: 'c', text: '2,50 €', isCorrect: false },
    ],
    correctAnswer: '2 €',
    explanation: '4 × 2,50 = 10 €. 10 − 8 = 2 €.',
    hint: 'Calcule d\'abord ses économies totales.',
    tags: ['cm1', 'problemes', 'décimaux', 'monnaie', 'multi-etapes', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 4 × 2,50.', 'Soustrais 8.'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-009',
    subject: 'mathematiques',
    title: 'Partage puis moitié',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'On partage 30 images entre 5 enfants. Chaque enfant donne la moitié de ses images à son voisin. Combien garde-t-il ?',
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '3', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '3',
    explanation: '30 ÷ 5 = 6 images chacun. La moitié de 6 = 3. Il garde 3 images.',
    hint: 'Commence par partager les 30 images.',
    tags: ['cm1', 'problemes', 'fractions', 'partage', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 30 ÷ 5.', 'Calcule la moitié de ce résultat.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-010',
    subject: 'mathematiques',
    title: 'Ruban et fractions',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'mesures en contexte',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un ruban de 3,5 m est coupé en 5 morceaux égaux. Quelle est la longueur d\'un morceau ?',
    options: [
      { id: 'a', text: '0,6 m', isCorrect: false },
      { id: 'b', text: '0,7 m', isCorrect: true },
      { id: 'c', text: '0,8 m', isCorrect: false },
    ],
    correctAnswer: '0,7 m',
    explanation: '3,5 ÷ 5 = 0,7 m.',
    hint: '3,5 ÷ 5 = ?',
    tags: ['cm1', 'problemes', 'mesures', 'décimaux', 'division', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-011',
    subject: 'mathematiques',
    title: 'Prix réduit et quantité',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'multi-étapes',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Un jouet coûte 12 €. Le magasin fait une réduction de 3 €. Emma en achète 3. Combien paie-t-elle ?',
    options: [
      { id: 'a', text: '27 €', isCorrect: true },
      { id: 'b', text: '30 €', isCorrect: false },
      { id: 'c', text: '33 €', isCorrect: false },
    ],
    correctAnswer: '27 €',
    explanation: 'Prix réduit = 12 − 3 = 9 €. Total = 3 × 9 = 27 €.',
    hint: 'Calcule d\'abord le prix réduit, puis multiplie.',
    tags: ['cm1', 'problemes', 'monnaie', 'multi-etapes', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule le prix après réduction.', 'Multiplie par 3.'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-012',
    subject: 'mathematiques',
    title: 'Fraction d\'une distance',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Résous.',
    prompt: 'Une randonnée fait 24 km. Luc a parcouru les 3/4. Combien de km lui reste-t-il ?',
    options: [
      { id: 'a', text: '4 km', isCorrect: false },
      { id: 'b', text: '6 km', isCorrect: true },
      { id: 'c', text: '8 km', isCorrect: false },
    ],
    correctAnswer: '6 km',
    explanation: '3/4 de 24 = 18 km. Reste = 24 − 18 = 6 km.',
    hint: 'Calcule d\'abord 3/4 de 24.',
    tags: ['cm1', 'problemes', 'fractions', 'distance', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-013',
    subject: 'mathematiques',
    title: 'Proportion de prix',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'proportionnalité',
    format: 'qcm',
    instructions: 'Résous.',
    prompt: '4 livres coûtent 36 €. Combien coûtent 6 livres au même prix ?',
    options: [
      { id: 'a', text: '48 €', isCorrect: false },
      { id: 'b', text: '54 €', isCorrect: true },
      { id: 'c', text: '60 €', isCorrect: false },
    ],
    correctAnswer: '54 €',
    explanation: 'Prix unitaire = 36 ÷ 4 = 9 €. 6 × 9 = 54 €.',
    hint: 'Calcule le prix d\'un seul livre, puis multiplie.',
    tags: ['cm1', 'problemes', 'proportionnalité', 'monnaie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-014',
    subject: 'mathematiques',
    title: 'Calcul de pourcentage',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'pourcentages',
    format: 'qcm',
    instructions: 'Résous.',
    prompt: 'Une veste coûte 80 €. Elle est soldée à 20 %. Quel est le nouveau prix ?',
    options: [
      { id: 'a', text: '60 €', isCorrect: false },
      { id: 'b', text: '64 €', isCorrect: true },
      { id: 'c', text: '68 €', isCorrect: false },
    ],
    correctAnswer: '64 €',
    explanation: '20 % de 80 = 80 ÷ 5 = 16 €. Prix soldé = 80 − 16 = 64 €.',
    hint: '20 % = 1/5. Calcule 80 ÷ 5 puis soustrait.',
    tags: ['cm1', 'problemes', 'pourcentage', 'monnaie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-015',
    subject: 'mathematiques',
    title: 'Durée de trajet',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'problemes',
    subskill: 'durées',
    format: 'qcm',
    instructions: 'Résous.',
    prompt: 'Un train part à 8 h 45. Il arrive à 11 h 20. Quelle est la durée du trajet ?',
    options: [
      { id: 'a', text: '2 h 25 min', isCorrect: false },
      { id: 'b', text: '2 h 35 min', isCorrect: true },
      { id: 'c', text: '2 h 45 min', isCorrect: false },
    ],
    correctAnswer: '2 h 35 min',
    explanation: 'De 8 h 45 à 11 h 45 = 3 h. Mais l\'arrivée est 11 h 20, soit 25 min avant. 3 h − 25 min = 2 h 35 min.',
    hint: 'De 8h45 à 11h20 : compte les heures, puis ajuste les minutes.',
    tags: ['cm1', 'problemes', 'durée', 'horaire', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:problemes',
  },
  {
    id: 'ma-cm1-problemes-016',
    subject: 'mathematiques',
    title: 'Partage inégal',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'problemes',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Résous.',
    prompt: 'Léa reçoit 2/5 d\'une somme de 60 €. Marc reçoit le reste. Combien Marc reçoit-il ?',
    options: [
      { id: 'a', text: '32 €', isCorrect: false },
      { id: 'b', text: '36 €', isCorrect: true },
      { id: 'c', text: '40 €', isCorrect: false },
    ],
    correctAnswer: '36 €',
    explanation: 'Léa = 2/5 de 60 = 24 €. Marc = 60 − 24 = 36 €.',
    hint: 'Calcule d\'abord la part de Léa.',
    tags: ['cm1', 'problemes', 'fractions', 'monnaie', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:problemes',
  },
];
