import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCm1GeometrieExercises: MathExercise[] = [
  {
    id: 'ma-cm1-geometrie-001',
    subject: 'mathematiques',
    title: 'Aire du rectangle',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'aire',
    format: 'qcm',
    instructions: "Calcule l'aire.",
    prompt: 'Un rectangle mesure 8 cm de long et 4 cm de large. Quelle est son aire ?',
    options: [
      { id: 'a', text: '24 cm²', isCorrect: false },
      { id: 'b', text: '32 cm²', isCorrect: true },
      { id: 'c', text: '36 cm²', isCorrect: false },
    ],
    correctAnswer: '32 cm²',
    explanation: 'Aire = longueur × largeur = 8 × 4 = 32 cm².',
    hint: 'Aire du rectangle = longueur × largeur.',
    tags: ['cm1', 'geometrie', 'aire', 'rectangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-002',
    subject: 'mathematiques',
    title: 'Périmètre du triangle',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'geometrie',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Calcule le périmètre.',
    prompt: 'Un triangle a des côtés de 5 cm, 7 cm et 3 cm. Quel est son périmètre ?',
    options: [
      { id: 'a', text: '13 cm', isCorrect: false },
      { id: 'b', text: '15 cm', isCorrect: true },
      { id: 'c', text: '17 cm', isCorrect: false },
    ],
    correctAnswer: '15 cm',
    explanation: 'Périmètre = 5 + 7 + 3 = 15 cm.',
    hint: 'Additionne tous les côtés.',
    tags: ['cm1', 'geometrie', 'périmètre', 'triangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-003',
    subject: 'mathematiques',
    title: 'Axes de symétrie du carré',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'geometrie',
    subskill: 'symétrie',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: "Combien d'axes de symétrie a un carré ?",
    options: [
      { id: 'a', text: '2', isCorrect: false },
      { id: 'b', text: '4', isCorrect: true },
      { id: 'c', text: '6', isCorrect: false },
    ],
    correctAnswer: '4',
    explanation: 'Un carré a 4 axes de symétrie : 2 diagonales et 2 médianes.',
    hint: 'Plie le carré dans tous les sens possibles.',
    tags: ['cm1', 'geometrie', 'symétrie', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-004',
    subject: 'mathematiques',
    title: "Aire d'un carré CM1",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'aire',
    format: 'qcm',
    instructions: "Calcule l'aire.",
    prompt: 'Un carré a des côtés de 6 cm. Quelle est son aire ?',
    options: [
      { id: 'a', text: '24 cm²', isCorrect: false },
      { id: 'b', text: '30 cm²', isCorrect: false },
      { id: 'c', text: '36 cm²', isCorrect: true },
    ],
    correctAnswer: '36 cm²',
    explanation: 'Aire = côté × côté = 6 × 6 = 36 cm².',
    hint: 'Multiplie 6 par lui-même.',
    tags: ['cm1', 'geometrie', 'aire', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-005',
    subject: 'mathematiques',
    title: "Périmètre d'un carré CM1",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Calcule le périmètre.',
    prompt: 'Un carré a des côtés de 7 cm. Quel est son périmètre ?',
    options: [
      { id: 'a', text: '21 cm', isCorrect: false },
      { id: 'b', text: '28 cm', isCorrect: true },
      { id: 'c', text: '35 cm', isCorrect: false },
    ],
    correctAnswer: '28 cm',
    explanation: "Périmètre d'un carré = 4 × côté = 4 × 7 = 28 cm.",
    hint: 'Un carré a 4 côtés égaux.',
    tags: ['cm1', 'geometrie', 'périmètre', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { instruction: 'Calcule 4 × 7.' },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-006',
    subject: 'mathematiques',
    title: 'Aire d\'un triangle',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'aire',
    format: 'qcm',
    instructions: "Calcule l'aire.",
    prompt: 'Un triangle a une base de 8 cm et une hauteur de 5 cm. Quelle est son aire ?',
    options: [
      { id: 'a', text: '15 cm²', isCorrect: false },
      { id: 'b', text: '20 cm²', isCorrect: true },
      { id: 'c', text: '40 cm²', isCorrect: false },
    ],
    correctAnswer: '20 cm²',
    explanation: 'Aire = (base × hauteur) ÷ 2 = (8 × 5) ÷ 2 = 40 ÷ 2 = 20 cm².',
    hint: 'Aire du triangle = (base × hauteur) ÷ 2.',
    tags: ['cm1', 'geometrie', 'aire', 'triangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-007',
    subject: 'mathematiques',
    title: 'Angles du triangle',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'angles',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'La somme des angles d\'un triangle est de combien de degrés ?',
    options: [
      { id: 'a', text: '90°', isCorrect: false },
      { id: 'b', text: '180°', isCorrect: true },
      { id: 'c', text: '360°', isCorrect: false },
    ],
    correctAnswer: '180°',
    explanation: 'La somme des 3 angles d\'un triangle est toujours égale à 180°.',
    hint: 'Pour tout triangle, les 3 angles font ensemble 180°.',
    tags: ['cm1', 'geometrie', 'angles', 'triangle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-008',
    subject: 'mathematiques',
    title: 'Solides : cube',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'solides',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Combien de faces a un cube ?',
    options: [
      { id: 'a', text: '4', isCorrect: false },
      { id: 'b', text: '6', isCorrect: true },
      { id: 'c', text: '8', isCorrect: false },
    ],
    correctAnswer: '6',
    explanation: 'Un cube a 6 faces carrées.',
    hint: 'Pense à un dé à jouer.',
    tags: ['cm1', 'geometrie', 'cube', 'solides', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-009',
    subject: 'mathematiques',
    title: 'Côté d\'un carré connaissant le périmètre',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un carré a un périmètre de 24 cm. Quelle est la longueur d\'un côté ?',
    options: [
      { id: 'a', text: '5 cm', isCorrect: false },
      { id: 'b', text: '6 cm', isCorrect: true },
      { id: 'c', text: '8 cm', isCorrect: false },
    ],
    correctAnswer: '6 cm',
    explanation: 'Périmètre = 4 × côté. Côté = 24 ÷ 4 = 6 cm.',
    hint: 'Divise le périmètre par 4.',
    tags: ['cm1', 'geometrie', 'périmètre', 'carré', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-010',
    subject: 'mathematiques',
    title: 'Triangle isocèle',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'triangles',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un triangle isocèle a au moins combien de côtés égaux ?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '2', isCorrect: true },
      { id: 'c', text: '3', isCorrect: false },
    ],
    correctAnswer: '2',
    explanation: 'Un triangle isocèle a exactement 2 côtés égaux (au minimum).',
    hint: 'Iso- vient du grec et signifie égal.',
    tags: ['cm1', 'geometrie', 'triangle', 'isocèle', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-011',
    subject: 'mathematiques',
    title: 'Volume du cube',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'geometrie',
    subskill: 'volume',
    format: 'qcm',
    instructions: 'Calcule le volume.',
    prompt: 'Un cube a un côté de 3 cm. Quel est son volume ?',
    options: [
      { id: 'a', text: '18 cm³', isCorrect: false },
      { id: 'b', text: '27 cm³', isCorrect: true },
      { id: 'c', text: '36 cm³', isCorrect: false },
    ],
    correctAnswer: '27 cm³',
    explanation: 'Volume = côté³ = 3 × 3 × 3 = 27 cm³.',
    hint: 'Volume du cube = arête × arête × arête.',
    tags: ['cm1', 'geometrie', 'volume', 'cube', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-012',
    subject: 'mathematiques',
    title: 'Diagonale du carré',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'geometrie',
    subskill: 'diagonales',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un carré a combien de diagonales ?',
    options: [
      { id: 'a', text: '1', isCorrect: false },
      { id: 'b', text: '2', isCorrect: true },
      { id: 'c', text: '4', isCorrect: false },
    ],
    correctAnswer: '2',
    explanation: 'Un carré a 2 diagonales qui se croisent à angle droit.',
    hint: 'Une diagonale relie deux sommets opposés.',
    tags: ['cm1', 'geometrie', 'diagonale', 'carré', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-013',
    subject: 'mathematiques',
    title: 'Aire du trapèze',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'geometrie',
    subskill: 'aire',
    format: 'qcm',
    instructions: 'Calcule l\'aire.',
    prompt: 'Un trapèze avec bases 8 cm et 4 cm, hauteur 3 cm. Quelle est son aire ?',
    options: [
      { id: 'a', text: '15 cm²', isCorrect: false },
      { id: 'b', text: '18 cm²', isCorrect: true },
      { id: 'c', text: '24 cm²', isCorrect: false },
    ],
    correctAnswer: '18 cm²',
    explanation: 'Aire = (grande base + petite base) × hauteur ÷ 2 = (8 + 4) × 3 ÷ 2 = 18 cm².',
    hint: 'Aire du trapèze = (b₁ + b₂) × h ÷ 2.',
    tags: ['cm1', 'geometrie', 'aire', 'trapèze', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-014',
    subject: 'mathematiques',
    title: 'Cercle : rayon et diamètre',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'geometrie',
    subskill: 'cercle',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un cercle a un rayon de 7 cm. Quel est son diamètre ?',
    options: [
      { id: 'a', text: '7 cm', isCorrect: false },
      { id: 'b', text: '14 cm', isCorrect: true },
      { id: 'c', text: '21 cm', isCorrect: false },
    ],
    correctAnswer: '14 cm',
    explanation: 'Le diamètre = 2 × rayon = 2 × 7 = 14 cm.',
    hint: 'Le diamètre est le double du rayon.',
    tags: ['cm1', 'geometrie', 'cercle', 'rayon', 'diamètre', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:geometrie',
  },
  {
    id: 'ma-cm1-geometrie-015',
    subject: 'mathematiques',
    title: 'Périmètre du cercle',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'geometrie',
    subskill: 'périmètre',
    format: 'qcm',
    instructions: 'Calcule (utilise π ≈ 3,14).',
    prompt: 'Un cercle de rayon 5 cm. Quel est son périmètre (arrondi) ?',
    options: [
      { id: 'a', text: '28,3 cm', isCorrect: false },
      { id: 'b', text: '31,4 cm', isCorrect: true },
      { id: 'c', text: '37,7 cm', isCorrect: false },
    ],
    correctAnswer: '31,4 cm',
    explanation: 'Périmètre = 2 × π × r = 2 × 3,14 × 5 = 31,4 cm.',
    hint: 'Périmètre = 2πr.',
    tags: ['cm1', 'geometrie', 'cercle', 'périmètre', 'pi', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:geometrie',
  },
];
