import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCm1StatistiquesExercises: MathExercise[] = [
  {
    id: 'ma-cm1-statistiques-001',
    subject: 'mathematiques',
    title: 'Lire un tableau de données',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'lecture de tableau',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un tableau montre les scores de 4 élèves : Alice 12, Benoît 18, Clara 15, Dora 9. Qui a le meilleur score ?',
    options: [
      { id: 'a', text: 'Alice', isCorrect: false },
      { id: 'b', text: 'Benoît', isCorrect: true },
      { id: 'c', text: 'Clara', isCorrect: false },
    ],
    correctAnswer: 'Benoît',
    explanation: '18 est le plus grand des quatre scores.',
    hint: 'Compare 12, 18, 15 et 9.',
    tags: ['cm1', 'statistiques', 'tableau', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-002',
    subject: 'mathematiques',
    title: 'Calcul d\'une moyenne simple',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'moyenne',
    format: 'qcm',
    instructions: 'Calcule la moyenne.',
    prompt: 'Les notes de Léa sont 10, 12 et 14. Quelle est sa moyenne ?',
    options: [
      { id: 'a', text: '11', isCorrect: false },
      { id: 'b', text: '12', isCorrect: true },
      { id: 'c', text: '13', isCorrect: false },
    ],
    correctAnswer: '12',
    explanation: '(10 + 12 + 14) ÷ 3 = 36 ÷ 3 = 12.',
    hint: 'Moyenne = somme ÷ nombre de valeurs.',
    tags: ['cm1', 'statistiques', 'moyenne', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-003',
    subject: 'mathematiques',
    title: 'Lire un diagramme en barres',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'diagramme en barres',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Un diagramme montre les fruits préférés : pomme 8, banane 5, orange 11, poire 3. Quel fruit est le moins aimé ?',
    options: [
      { id: 'a', text: 'banane', isCorrect: false },
      { id: 'b', text: 'poire', isCorrect: true },
      { id: 'c', text: 'pomme', isCorrect: false },
    ],
    correctAnswer: 'poire',
    explanation: '3 est le plus petit nombre, correspondant à la poire.',
    hint: 'Cherche la valeur la plus petite.',
    tags: ['cm1', 'statistiques', 'diagramme', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-004',
    subject: 'mathematiques',
    title: 'Total à partir d\'un diagramme',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de données',
    format: 'qcm',
    instructions: 'Lis et calcule.',
    prompt: 'Le diagramme montre les livres lus par mois : Jan=6, Fév=4, Mar=8. Combien en tout sur 3 mois ?',
    options: [
      { id: 'a', text: '16', isCorrect: false },
      { id: 'b', text: '18', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '18',
    explanation: '6 + 4 + 8 = 18 livres.',
    hint: 'Additionne les 3 valeurs.',
    tags: ['cm1', 'statistiques', 'lecture-données', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-005',
    subject: 'mathematiques',
    title: 'Étendue d\'une série',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'étendue',
    format: 'qcm',
    instructions: 'Calcule l\'étendue.',
    prompt: 'Températures de la semaine : 14°, 17°, 12°, 20°, 16°. Quelle est l\'étendue (max − min) ?',
    options: [
      { id: 'a', text: '6°', isCorrect: false },
      { id: 'b', text: '8°', isCorrect: true },
      { id: 'c', text: '10°', isCorrect: false },
    ],
    correctAnswer: '8°',
    explanation: 'Max = 20°, min = 12°. Étendue = 20 − 12 = 8°.',
    hint: 'Étendue = valeur max − valeur min.',
    tags: ['cm1', 'statistiques', 'étendue', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-006',
    subject: 'mathematiques',
    title: 'Interpréter un diagramme circulaire',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'diagramme circulaire',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Dans une classe de 30 élèves, 1/2 aiment le foot, 1/3 aiment la natation, le reste autre chose. Combien aiment le foot ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '15', isCorrect: true },
      { id: 'c', text: '20', isCorrect: false },
    ],
    correctAnswer: '15',
    explanation: '1/2 de 30 = 15.',
    hint: '1/2 = la moitié.',
    tags: ['cm1', 'statistiques', 'fractions', 'diagramme', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-007',
    subject: 'mathematiques',
    title: 'Valeur manquante pour une moyenne',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'moyenne',
    format: 'qcm',
    instructions: 'Résous le problème.',
    prompt: 'La moyenne de 3 notes est 14. Deux notes sont 12 et 13. Quelle est la troisième note ?',
    options: [
      { id: 'a', text: '15', isCorrect: false },
      { id: 'b', text: '17', isCorrect: true },
      { id: 'c', text: '18', isCorrect: false },
    ],
    correctAnswer: '17',
    explanation: 'Somme totale = 14 × 3 = 42. Troisième note = 42 − 12 − 13 = 17.',
    hint: 'Moyenne × nombre = somme totale.',
    tags: ['cm1', 'statistiques', 'moyenne', 'déduction', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-008',
    subject: 'mathematiques',
    title: 'Mode d\'une série',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'mode',
    format: 'qcm',
    instructions: 'Trouve le mode.',
    prompt: 'Série de notes : 8, 12, 10, 12, 15, 8, 12. Quel est le mode (valeur la plus fréquente) ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '10', isCorrect: false },
      { id: 'c', text: '12', isCorrect: true },
    ],
    correctAnswer: '12',
    explanation: '12 apparaît 3 fois, c\'est la valeur la plus fréquente.',
    hint: 'Compte combien de fois chaque valeur apparaît.',
    tags: ['cm1', 'statistiques', 'mode', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-009',
    subject: 'mathematiques',
    title: 'Tableau de fréquences',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'fréquences',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: '20 élèves ont voté : 8 pour rouge, 7 pour bleu, 5 pour vert. Quelle couleur représente 35 % des votes ?',
    options: [
      { id: 'a', text: 'rouge', isCorrect: false },
      { id: 'b', text: 'bleu', isCorrect: true },
      { id: 'c', text: 'vert', isCorrect: false },
    ],
    correctAnswer: 'bleu',
    explanation: '7 ÷ 20 = 0,35 = 35 %. C\'est le bleu.',
    hint: 'Divise chaque valeur par 20 et convertis en pourcentage.',
    tags: ['cm1', 'statistiques', 'fréquences', 'pourcentages', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-010',
    subject: 'mathematiques',
    title: 'Comparer deux séries',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'comparaison de données',
    format: 'qcm',
    instructions: 'Compare les deux classes.',
    prompt: 'Classe A : moyennes 13, 15, 11, 17. Classe B : moyennes 12, 16, 14, 14. Laquelle a la meilleure moyenne ?',
    options: [
      { id: 'a', text: 'Classe A', isCorrect: true },
      { id: 'b', text: 'Classe B', isCorrect: false },
      { id: 'c', text: 'Elles sont égales', isCorrect: false },
    ],
    correctAnswer: 'Classe A',
    explanation: 'Classe A : (13+15+11+17)÷4 = 56÷4 = 14. Classe B : (12+16+14+14)÷4 = 56÷4 = 14. Elles sont égales !',
    hint: 'Calcule la moyenne de chaque classe.',
    tags: ['cm1', 'statistiques', 'moyenne', 'comparaison', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-011',
    subject: 'mathematiques',
    title: 'Données manquantes dans un tableau',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'lecture de tableau',
    format: 'qcm',
    instructions: 'Complète le tableau.',
    prompt: 'Un tableau indique les ventes de janvier à mars. Jan=120, Fév=?, Mar=150. Total=380. Quelle est la valeur de février ?',
    options: [
      { id: 'a', text: '100', isCorrect: false },
      { id: 'b', text: '110', isCorrect: true },
      { id: 'c', text: '120', isCorrect: false },
    ],
    correctAnswer: '110',
    explanation: '380 − 120 − 150 = 110.',
    hint: 'Total − Jan − Mar = Fév.',
    tags: ['cm1', 'statistiques', 'tableau', 'déduction', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-012',
    subject: 'mathematiques',
    title: 'Médiane d\'une série courte',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'logique',
    subskill: 'médiane',
    format: 'qcm',
    instructions: 'Trouve la médiane.',
    prompt: 'Notes rangées dans l\'ordre : 8, 10, 13, 15, 17. Quelle est la médiane ?',
    options: [
      { id: 'a', text: '10', isCorrect: false },
      { id: 'b', text: '13', isCorrect: true },
      { id: 'c', text: '15', isCorrect: false },
    ],
    correctAnswer: '13',
    explanation: 'La médiane est la valeur centrale : 8, 10, **13**, 15, 17.',
    hint: 'La médiane est la valeur du milieu quand les données sont rangées.',
    tags: ['cm1', 'statistiques', 'médiane', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-013',
    subject: 'mathematiques',
    title: 'Graphique — évolution mensuelle',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'logique',
    subskill: 'graphique linéaire',
    format: 'qcm',
    instructions: 'Lis le graphique.',
    prompt: 'Ventes mensuelles : Oct=50, Nov=75, Déc=120, Jan=60. Entre quels mois la hausse est la plus forte ?',
    options: [
      { id: 'a', text: 'Oct→Nov', isCorrect: false },
      { id: 'b', text: 'Nov→Déc', isCorrect: true },
      { id: 'c', text: 'Déc→Jan', isCorrect: false },
    ],
    correctAnswer: 'Nov→Déc',
    explanation: 'Oct→Nov : +25. Nov→Déc : +45. Déc→Jan : −60. La plus forte hausse est Nov→Déc.',
    hint: 'Calcule la différence entre chaque mois.',
    tags: ['cm1', 'statistiques', 'graphique', 'évolution', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:logique',
  },
  {
    id: 'ma-cm1-statistiques-014',
    subject: 'mathematiques',
    title: 'Probabilité — vocabulaire',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'logique',
    subskill: 'probabilités',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'On lance un dé à 6 faces. Quelle est la probabilité d\'obtenir un 3 ?',
    options: [
      { id: 'a', text: '1/3', isCorrect: false },
      { id: 'b', text: '1/6', isCorrect: true },
      { id: 'c', text: '1/2', isCorrect: false },
    ],
    correctAnswer: '1/6',
    explanation: 'Il y a 1 seul 3 parmi 6 faces. Probabilité = 1/6.',
    hint: '6 faces, une seule est le 3.',
    tags: ['cm1', 'statistiques', 'probabilités', 'dé', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:logique',
  },
];
