import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { MathExercise } from '../maths.types';

export const mathsCm1CalculExercises: MathExercise[] = [
  {
    id: 'ma-cm1-calcul-001',
    subject: 'mathematiques',
    title: 'Multiplication à 2 chiffres',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '14 × 3 = ?',
    options: [
      { id: 'a', text: '40', isCorrect: false },
      { id: 'b', text: '42', isCorrect: true },
      { id: 'c', text: '44', isCorrect: false },
    ],
    correctAnswer: '42',
    explanation: '14 × 3 = 42. (10 × 3 = 30, 4 × 3 = 12, 30 + 12 = 42)',
    hint: 'Calcule 10 × 3, puis 4 × 3, puis additionne.',
    tags: ['cm1', 'calcul', 'multiplication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-002',
    subject: 'mathematiques',
    title: 'Division euclidienne',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'division',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '56 ÷ 7 = ?',
    options: [
      { id: 'a', text: '7', isCorrect: false },
      { id: 'b', text: '8', isCorrect: true },
      { id: 'c', text: '9', isCorrect: false },
    ],
    correctAnswer: '8',
    explanation: '56 ÷ 7 = 8, car 7 × 8 = 56.',
    hint: 'Cherche quel nombre × 7 = 56.',
    tags: ['cm1', 'calcul', 'division', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-003',
    subject: 'mathematiques',
    title: "Fraction d'un entier",
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quelle fraction représente une moitié ?',
    options: [
      { id: 'a', text: '1/3', isCorrect: false },
      { id: 'b', text: '1/2', isCorrect: true },
      { id: 'c', text: '1/4', isCorrect: false },
    ],
    correctAnswer: '1/2',
    explanation: 'Une moitié = 1/2 (un sur deux).',
    hint: "La moitié, c'est partager en 2 parties égales et en prendre 1.",
    tags: ['cm1', 'calcul', 'fractions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-004',
    subject: 'mathematiques',
    title: 'Comparer des fractions',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Compare les fractions.',
    prompt: 'Quelle fraction est la plus grande : 1/2 ou 1/4 ?',
    options: [
      { id: 'a', text: '1/4', isCorrect: false },
      { id: 'b', text: '1/2', isCorrect: true },
      { id: 'c', text: 'Elles sont égales', isCorrect: false },
    ],
    correctAnswer: '1/2',
    explanation: '1/2 = 0,5 et 1/4 = 0,25. Donc 1/2 > 1/4.',
    hint: "Imagine une pizza : une moitié c'est plus grand qu'un quart.",
    tags: ['cm1', 'calcul', 'fractions', 'comparaison', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-005',
    subject: 'mathematiques',
    title: 'Multiplication ×25',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication posée',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '25 × 4 = ?',
    options: [
      { id: 'a', text: '90', isCorrect: false },
      { id: 'b', text: '100', isCorrect: true },
      { id: 'c', text: '110', isCorrect: false },
    ],
    correctAnswer: '100',
    explanation: "25 × 4 = 100. On peut penser à 4 pièces de 25 centimes = 1 euro.",
    hint: '25 + 25 = 50, puis 50 + 50 = 100.',
    tags: ['cm1', 'calcul', 'multiplication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      lecture_simplifiee: { extraHint: '25 + 25 = 50. 50 + 50 = ?' },
      defi_avance: { challengeExtension: 'Calcule 25 × 8 en utilisant le même raisonnement.' },
    }),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-006',
    subject: 'mathematiques',
    title: 'Division par 8',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'division',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '72 ÷ 8 = ?',
    options: [
      { id: 'a', text: '8', isCorrect: false },
      { id: 'b', text: '9', isCorrect: true },
      { id: 'c', text: '10', isCorrect: false },
    ],
    correctAnswer: '9',
    explanation: '72 ÷ 8 = 9, car 8 × 9 = 72.',
    hint: 'Quelle table de 8 donne 72 ?',
    tags: ['cm1', 'calcul', 'division', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-007',
    subject: 'mathematiques',
    title: 'Fraction équivalente',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'calcul',
    subskill: 'fractions équivalentes',
    format: 'qcm',
    instructions: 'Trouve la fraction égale.',
    prompt: 'Quelle fraction est égale à 2/4 ?',
    options: [
      { id: 'a', text: '1/3', isCorrect: false },
      { id: 'b', text: '1/2', isCorrect: true },
      { id: 'c', text: '3/4', isCorrect: false },
    ],
    correctAnswer: '1/2',
    explanation: '2/4 = 1/2. On divise le numérateur et le dénominateur par 2.',
    hint: '2 ÷ 2 = 1 et 4 ÷ 2 = 2.',
    tags: ['cm1', 'calcul', 'fractions', 'équivalence', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Lis la fraction 2/4.', 'Divise le haut et le bas par 2.', 'Quelle fraction obtiens-tu ?'] },
    }),
    difficulty_tier: 'advanced',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-008',
    subject: 'mathematiques',
    title: "Fraction d'un entier",
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'calcul',
    subskill: "fractions d'un entier",
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: 'Les 3/4 de 20 = ?',
    options: [
      { id: 'a', text: '12', isCorrect: false },
      { id: 'b', text: '14', isCorrect: false },
      { id: 'c', text: '15', isCorrect: true },
    ],
    correctAnswer: '15',
    explanation: '1/4 de 20 = 20 ÷ 4 = 5. Donc 3/4 = 3 × 5 = 15.',
    hint: "Calcule d'abord 1/4 de 20, puis multiplie par 3.",
    tags: ['cm1', 'calcul', 'fractions', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 20 ÷ 4 pour trouver 1/4.', 'Multiplie par 3.'] },
      defi_avance: { challengeExtension: 'Calcule maintenant les 3/4 de 40.' },
    }),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-009',
    subject: 'mathematiques',
    title: 'Addition de décimaux',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'décimaux',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '2,4 + 1,5 = ?',
    options: [
      { id: 'a', text: '3,7', isCorrect: false },
      { id: 'b', text: '3,9', isCorrect: true },
      { id: 'c', text: '4,1', isCorrect: false },
    ],
    correctAnswer: '3,9',
    explanation: '2,4 + 1,5 = 3,9.',
    hint: '2 + 1 = 3 et 4 + 5 = 9 dixièmes → 3,9.',
    tags: ['cm1', 'calcul', 'décimaux', 'addition', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-010',
    subject: 'mathematiques',
    title: 'Soustraction de décimaux',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'décimaux',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '5,8 − 2,3 = ?',
    options: [
      { id: 'a', text: '3,4', isCorrect: false },
      { id: 'b', text: '3,5', isCorrect: true },
      { id: 'c', text: '3,6', isCorrect: false },
    ],
    correctAnswer: '3,5',
    explanation: '5,8 − 2,3 = 3,5.',
    hint: '5 − 2 = 3 et 8 − 3 = 5 dixièmes → 3,5.',
    tags: ['cm1', 'calcul', 'décimaux', 'soustraction', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-011',
    subject: 'mathematiques',
    title: 'Multiplication posée',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication posée',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '23 × 15 = ?',
    options: [
      { id: 'a', text: '335', isCorrect: false },
      { id: 'b', text: '345', isCorrect: true },
      { id: 'c', text: '355', isCorrect: false },
    ],
    correctAnswer: '345',
    explanation: '23 × 15 = 23 × 10 + 23 × 5 = 230 + 115 = 345.',
    hint: 'Décompose 15 en 10 + 5.',
    tags: ['cm1', 'calcul', 'multiplication', 'posee', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations({
      progressif: { splitSteps: ['Calcule 23 × 10.', 'Calcule 23 × 5.', 'Additionne les deux résultats.'] },
    }),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-012',
    subject: 'mathematiques',
    title: 'Division avec reste',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'division euclidienne',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '47 ÷ 6 = ? reste ?',
    options: [
      { id: 'a', text: '7 reste 4', isCorrect: false },
      { id: 'b', text: '7 reste 5', isCorrect: true },
      { id: 'c', text: '8 reste 0', isCorrect: false },
    ],
    correctAnswer: '7 reste 5',
    explanation: '6 × 7 = 42 et 47 − 42 = 5. Donc 47 ÷ 6 = 7 reste 5.',
    hint: '6 × 7 = 42. 47 − 42 = ?',
    tags: ['cm1', 'calcul', 'division', 'reste', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-013',
    subject: 'mathematiques',
    title: 'Fraction comme résultat de division',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'On partage 1 gâteau entre 4 enfants. Quelle fraction reçoit chacun ?',
    options: [
      { id: 'a', text: '1/3', isCorrect: false },
      { id: 'b', text: '1/4', isCorrect: true },
      { id: 'c', text: '4/1', isCorrect: false },
    ],
    correctAnswer: '1/4',
    explanation: '1 ÷ 4 = 1/4. Chaque enfant reçoit un quart du gâteau.',
    hint: 'Partager par 4, c\'est diviser en 4 parts égales = 1/4.',
    tags: ['cm1', 'calcul', 'fractions', 'partage', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'foundation',
    school_period: 'debut',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-014',
    subject: 'mathematiques',
    title: 'Addition de fractions même dénominateur',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '2/5 + 1/5 = ?',
    options: [
      { id: 'a', text: '3/10', isCorrect: false },
      { id: 'b', text: '3/5', isCorrect: true },
      { id: 'c', text: '2/5', isCorrect: false },
    ],
    correctAnswer: '3/5',
    explanation: '2/5 + 1/5 = 3/5. On additionne les numérateurs : 2 + 1 = 3.',
    hint: 'Même dénominateur : additionne seulement les numérateurs.',
    tags: ['cm1', 'calcul', 'fractions', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-015',
    subject: 'mathematiques',
    title: 'Multiplier un décimal par 10',
    schoolClass: 'CM1',
    generalLevel: 'beginner',
    skill: 'calcul',
    subskill: 'décimaux',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '3,7 × 10 = ?',
    options: [
      { id: 'a', text: '3,70', isCorrect: false },
      { id: 'b', text: '37', isCorrect: true },
      { id: 'c', text: '370', isCorrect: false },
    ],
    correctAnswer: '37',
    explanation: 'Multiplier par 10 déplace la virgule d\'un rang vers la droite : 3,7 → 37.',
    hint: 'Multiplier par 10 = déplacer la virgule d\'une place vers la droite.',
    tags: ['cm1', 'calcul', 'décimaux', 'multiplication', 'qcm'],
    estimatedMinutes: 1,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-016',
    subject: 'mathematiques',
    title: 'PGCD simple',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'calcul',
    subskill: 'diviseurs',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Quels sont les diviseurs communs de 12 et 18 ?',
    options: [
      { id: 'a', text: '1, 2, 3', isCorrect: false },
      { id: 'b', text: '1, 2, 3, 6', isCorrect: true },
      { id: 'c', text: '2, 4, 6', isCorrect: false },
    ],
    correctAnswer: '1, 2, 3, 6',
    explanation: 'Diviseurs de 12 : 1, 2, 3, 4, 6, 12. Diviseurs de 18 : 1, 2, 3, 6, 9, 18. Communs : 1, 2, 3, 6.',
    hint: 'Liste les diviseurs de chaque nombre, puis cherche ceux qu\'ils partagent.',
    tags: ['cm1', 'calcul', 'diviseurs', 'qcm'],
    estimatedMinutes: 3,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-017',
    subject: 'mathematiques',
    title: '4,2 × 3',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiplication',
    format: 'qcm',
    instructions: 'Calcule.',
    prompt: '4,2 × 3 = ?',
    options: [
      { id: 'a', text: '11,6', isCorrect: false },
      { id: 'b', text: '12,6', isCorrect: true },
      { id: 'c', text: '13,6', isCorrect: false },
    ],
    correctAnswer: '12,6',
    explanation: '4,2 × 3 = 12,6.',
    hint: '4 × 3 = 12, 0,2 × 3 = 0,6. Total = 12,6.',
    tags: ['cm1', 'calcul', 'décimaux', 'multiplication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-018',
    subject: 'mathematiques',
    title: '3/4 en décimal',
    schoolClass: 'CM1',
    generalLevel: 'advanced',
    skill: 'calcul',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Convertis cette fraction.',
    prompt: '3/4 = ?',
    options: [
      { id: 'a', text: '0,5', isCorrect: false },
      { id: 'b', text: '0,75', isCorrect: true },
      { id: 'c', text: '1,25', isCorrect: false },
    ],
    correctAnswer: '0,75',
    explanation: '3/4 = 3 ÷ 4 = 0,75.',
    hint: '3 ÷ 4 = ?',
    tags: ['cm1', 'calcul', 'fractions', 'décimaux', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'advanced',
    school_period: 'fin',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-019',
    subject: 'mathematiques',
    title: '3/8 + 2/8',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'fractions',
    format: 'qcm',
    instructions: 'Additionne ces fractions.',
    prompt: '3/8 + 2/8 = ?',
    options: [
      { id: 'a', text: '5/16', isCorrect: false },
      { id: 'b', text: '5/8', isCorrect: true },
      { id: 'c', text: '6/8', isCorrect: false },
    ],
    correctAnswer: '5/8',
    explanation: 'Même dénominateur : on additionne les numérateurs. 3 + 2 = 5. Résultat : 5/8.',
    hint: 'Même dénominateur = additionne les numérateurs.',
    tags: ['cm1', 'calcul', 'fractions', 'addition', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
  {
    id: 'ma-cm1-calcul-020',
    subject: 'mathematiques',
    title: 'Multiples de 6',
    schoolClass: 'CM1',
    generalLevel: 'intermediate',
    skill: 'calcul',
    subskill: 'multiples',
    format: 'qcm',
    instructions: 'Réponds à la question.',
    prompt: 'Lequel est un multiple de 6 ?',
    options: [
      { id: 'a', text: '38', isCorrect: false },
      { id: 'b', text: '42', isCorrect: true },
      { id: 'c', text: '46', isCorrect: false },
    ],
    correctAnswer: '42',
    explanation: '42 = 6 × 7. C\'est un multiple de 6.',
    hint: 'Un multiple de 6 est dans la table de 6.',
    tags: ['cm1', 'calcul', 'multiples', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
    difficulty_tier: 'standard',
    school_period: 'milieu',
    skill_id: 'mathematiques:calcul',
  },
];
