import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe2GramThereIsExercises: EnglishExercise[] = [
  {
    id: 'en-ce2-gram-025',
    subject: 'anglais',
    title: 'There is : sens',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There is a cat on the sofa » en français ?',
    options: [
      { id: 'a', text: 'Un chat est tombé du canapé.', isCorrect: false },
      { id: 'b', text: 'Il y a un chat sur le canapé.', isCorrect: true },
      { id: 'c', text: 'Mon chat est sous le canapé.', isCorrect: false },
    ],
    correctAnswer: 'Il y a un chat sur le canapé.',
    explanation: '« There is » = il y a (singulier). On l\'utilise pour décrire ce qu\'il y a quelque part.',
    hint: '« There is » = il y a (pour un seul objet).',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-026',
    subject: 'anglais',
    title: 'There are : pluriel',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There are two dogs in the garden » en français ?',
    options: [
      { id: 'a', text: 'Il y a un chien dans le jardin.', isCorrect: false },
      { id: 'b', text: 'Il y a deux chiens dans le jardin.', isCorrect: true },
      { id: 'c', text: 'Il n\'y a pas de chiens dans le jardin.', isCorrect: false },
    ],
    correctAnswer: 'Il y a deux chiens dans le jardin.',
    explanation: '« There are » = il y a (pluriel). On l\'utilise quand il y a plusieurs choses.',
    hint: '« There are » = il y a (pour plusieurs objets).',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-027',
    subject: 'anglais',
    title: 'There is / There are : choisir',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « ___ three apples on the table. »',
    options: [
      { id: 'a', text: 'There is', isCorrect: false },
      { id: 'b', text: 'There are', isCorrect: true },
      { id: 'c', text: 'There have', isCorrect: false },
    ],
    correctAnswer: 'There are',
    explanation: 'Three apples = plusieurs → « There are » (pluriel).',
    hint: 'Trois pommes = pluriel → There are.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-028',
    subject: 'anglais',
    title: 'There isn\'t : négation singulier',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There isn\'t any milk in the fridge » en français ?',
    options: [
      { id: 'a', text: 'Il y a du lait dans le frigo.', isCorrect: false },
      { id: 'b', text: 'Il n\'y a pas de lait dans le frigo.', isCorrect: true },
      { id: 'c', text: 'Il y a beaucoup de lait dans le frigo.', isCorrect: false },
    ],
    correctAnswer: 'Il n\'y a pas de lait dans le frigo.',
    explanation: '« There isn\'t any » = il n\'y a pas de. « Fridge » = frigo.',
    hint: '« Isn\'t » = is not = n\'est pas. Il n\'y a pas de…',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-029',
    subject: 'anglais',
    title: 'There aren\'t : négation pluriel',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There aren\'t any eggs » en français ?',
    options: [
      { id: 'a', text: 'Il y a des œufs.', isCorrect: false },
      { id: 'b', text: 'Il n\'y a pas d\'œufs.', isCorrect: true },
      { id: 'c', text: 'Il y a un œuf.', isCorrect: false },
    ],
    correctAnswer: 'Il n\'y a pas d\'œufs.',
    explanation: '« There aren\'t any » = il n\'y a pas de. Forme négative plurielle.',
    hint: '« Aren\'t » = are not → il n\'y a pas de.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-030',
    subject: 'anglais',
    title: 'Is there? : question',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « Is there a park near your house? » en français ?',
    options: [
      { id: 'a', text: 'Tu as un parc près de chez toi ?', isCorrect: false },
      { id: 'b', text: 'Est-ce qu\'il y a un parc près de chez toi ?', isCorrect: true },
      { id: 'c', text: 'Où est le parc près de chez toi ?', isCorrect: false },
    ],
    correctAnswer: 'Est-ce qu\'il y a un parc près de chez toi ?',
    explanation: '« Is there… ? » = est-ce qu\'il y a… ? Question au singulier.',
    hint: '« Is there » = est-ce qu\'il y a (question) ?',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-031',
    subject: 'anglais',
    title: 'Are there? : question plurielle',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « Are there any shops nearby? » en français ?',
    options: [
      { id: 'a', text: 'Où sont les magasins ?', isCorrect: false },
      { id: 'b', text: 'Est-ce qu\'il y a des magasins près d\'ici ?', isCorrect: true },
      { id: 'c', text: 'Il y a des magasins près d\'ici.', isCorrect: false },
    ],
    correctAnswer: 'Est-ce qu\'il y a des magasins près d\'ici ?',
    explanation: '« Are there any…? » = est-ce qu\'il y a des… ? Question au pluriel.',
    hint: '« Are there any » = est-ce qu\'il y a des (question pluriel) ?',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-032',
    subject: 'anglais',
    title: 'There is some : partitif',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There is some bread on the table » en français ?',
    options: [
      { id: 'a', text: 'Il n\'y a pas de pain sur la table.', isCorrect: false },
      { id: 'b', text: 'Il y a du pain sur la table.', isCorrect: true },
      { id: 'c', text: 'Il y a beaucoup de pains sur la table.', isCorrect: false },
    ],
    correctAnswer: 'Il y a du pain sur la table.',
    explanation: '« There is some » = il y a du/de la. « Some » = une certaine quantité.',
    hint: '« Some » devant un indénombrable = du/de la.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-033',
    subject: 'anglais',
    title: 'There are many : quantité',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There are many children in the park » en français ?',
    options: [
      { id: 'a', text: 'Il y a peu d\'enfants dans le parc.', isCorrect: false },
      { id: 'b', text: 'Il y a beaucoup d\'enfants dans le parc.', isCorrect: true },
      { id: 'c', text: 'Il n\'y a pas d\'enfants dans le parc.', isCorrect: false },
    ],
    correctAnswer: 'Il y a beaucoup d\'enfants dans le parc.',
    explanation: '« Many » = beaucoup de (avec les dénombrables au pluriel).',
    hint: '« Many » = beaucoup de.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-034',
    subject: 'anglais',
    title: 'There is : description d\'une chambre',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Lis cette description.',
    prompt: '« In my bedroom, there is a bed, a desk and a lamp. There are also two windows. »\nCombien de fenêtres y a-t-il ?',
    options: [
      { id: 'a', text: 'Une fenêtre', isCorrect: false },
      { id: 'b', text: 'Deux fenêtres', isCorrect: true },
      { id: 'c', text: 'Trois fenêtres', isCorrect: false },
    ],
    correctAnswer: 'Deux fenêtres',
    explanation: '« There are also two windows » = il y a aussi deux fenêtres.',
    hint: '« Two » = deux.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-035',
    subject: 'anglais',
    title: 'There is : a lot of',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There is a lot of noise outside » en français ?',
    options: [
      { id: 'a', text: 'Il y a peu de bruit dehors.', isCorrect: false },
      { id: 'b', text: 'Il y a beaucoup de bruit dehors.', isCorrect: true },
      { id: 'c', text: 'Il n\'y a pas de bruit dehors.', isCorrect: false },
    ],
    correctAnswer: 'Il y a beaucoup de bruit dehors.',
    explanation: '« A lot of » = beaucoup de. « Noise » = bruit. « Outside » = dehors.',
    hint: '« A lot of » = beaucoup de.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-036',
    subject: 'anglais',
    title: 'There is : three bedrooms',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Choisis la bonne phrase.',
    prompt: 'Laquelle est correcte ?',
    options: [
      { id: 'a', text: 'There is three bedrooms in my house.', isCorrect: false },
      { id: 'b', text: 'There are three bedrooms in my house.', isCorrect: true },
      { id: 'c', text: 'There have three bedrooms in my house.', isCorrect: false },
    ],
    correctAnswer: 'There are three bedrooms in my house.',
    explanation: '« Three bedrooms » = pluriel → « there are » (pas « there is »).',
    hint: 'Pluriel → There are.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-037',
    subject: 'anglais',
    title: 'There is : Is there a garden?',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Comment répond-on à cette question ?',
    prompt: '— « Is there a garden? »\nComment réponds-tu oui ?',
    options: [
      { id: 'a', text: 'Yes, there have.', isCorrect: false },
      { id: 'b', text: 'Yes, there is.', isCorrect: true },
      { id: 'c', text: 'Yes, it is.', isCorrect: false },
    ],
    correctAnswer: 'Yes, there is.',
    explanation: 'Réponse courte à « Is there… ? » : « Yes, there is. » ou « No, there isn\'t. »',
    hint: 'Réponse courte : Yes, there is / No, there isn\'t.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-038',
    subject: 'anglais',
    title: 'There is : nothing',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There is nothing in the box » en français ?',
    options: [
      { id: 'a', text: 'Il y a quelque chose dans la boîte.', isCorrect: false },
      { id: 'b', text: 'Il n\'y a rien dans la boîte.', isCorrect: true },
      { id: 'c', text: 'Il y a beaucoup dans la boîte.', isCorrect: false },
    ],
    correctAnswer: 'Il n\'y a rien dans la boîte.',
    explanation: '« There is nothing » = il n\'y a rien. « Nothing » = rien.',
    hint: '« Nothing » = rien.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-039',
    subject: 'anglais',
    title: 'There are : lots of birds',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There are lots of birds in the tree » en français ?',
    options: [
      { id: 'a', text: 'Il y a peu d\'oiseaux dans l\'arbre.', isCorrect: false },
      { id: 'b', text: 'Il y a plein d\'oiseaux dans l\'arbre.', isCorrect: true },
      { id: 'c', text: 'Il n\'y a pas d\'oiseaux dans l\'arbre.', isCorrect: false },
    ],
    correctAnswer: 'Il y a plein d\'oiseaux dans l\'arbre.',
    explanation: '« Lots of » = plein de / beaucoup de. « Birds » = oiseaux. « Tree » = arbre.',
    hint: '« Lots of » = plein de.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-040',
    subject: 'anglais',
    title: 'There is : someone at the door',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « There is someone at the door » en français ?',
    options: [
      { id: 'a', text: 'Il n\'y a personne à la porte.', isCorrect: false },
      { id: 'b', text: 'Il y a quelqu\'un à la porte.', isCorrect: true },
      { id: 'c', text: 'La porte est ouverte.', isCorrect: false },
    ],
    correctAnswer: 'Il y a quelqu\'un à la porte.',
    explanation: '« Someone » = quelqu\'un. « At the door » = à la porte.',
    hint: '« Someone » = quelqu\'un.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-041',
    subject: 'anglais',
    title: 'There is : révision globale',
    schoolClass: 'CE2',
    generalLevel: 'advanced',
    skill: 'grammaire',
    subskill: 'there-is',
    format: 'qcm',
    instructions: 'Traduis cette phrase.',
    prompt: 'Comment dit-on « Il n\'y a pas d\'école le samedi » en anglais ?',
    options: [
      { id: 'a', text: 'There is school on Saturday.', isCorrect: false },
      { id: 'b', text: 'There isn\'t school on Saturday.', isCorrect: true },
      { id: 'c', text: 'There are no school on Saturday.', isCorrect: false },
    ],
    correctAnswer: 'There isn\'t school on Saturday.',
    explanation: '« There isn\'t school » = il n\'y a pas d\'école. « On Saturday » = le samedi.',
    hint: 'Négation singulier → There isn\'t.',
    tags: ['ce2', 'anglais', 'grammaire', 'there-is', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
