import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe2GramPresentSimpleExercises: EnglishExercise[] = [
  {
    id: 'en-ce2-gram-010',
    subject: 'anglais',
    title: 'Present simple : I play',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « I ___ football every day. »',
    options: [
      { id: 'a', text: 'plays', isCorrect: false },
      { id: 'b', text: 'play', isCorrect: true },
      { id: 'c', text: 'playing', isCorrect: false },
    ],
    correctAnswer: 'play',
    explanation: 'Avec « I », on utilise la forme de base du verbe : « I play ».',
    hint: 'Avec « I », pas de -s au verbe.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-011',
    subject: 'anglais',
    title: 'Present simple : He plays',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « He ___ football every day. »',
    options: [
      { id: 'a', text: 'play', isCorrect: false },
      { id: 'b', text: 'plays', isCorrect: true },
      { id: 'c', text: 'playing', isCorrect: false },
    ],
    correctAnswer: 'plays',
    explanation: 'Avec « he », « she » ou « it », on ajoute -s au verbe : « he plays ».',
    hint: 'He/She/It → verbe + -s.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-012',
    subject: 'anglais',
    title: 'Present simple : She likes',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « She ___ cats. »',
    options: [
      { id: 'a', text: 'like', isCorrect: false },
      { id: 'b', text: 'likes', isCorrect: true },
      { id: 'c', text: 'liking', isCorrect: false },
    ],
    correctAnswer: 'likes',
    explanation: 'Avec « she », on ajoute -s : « she likes ». Règle de la 3e personne du singulier.',
    hint: 'She/He/It → verbe + -s.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-013',
    subject: 'anglais',
    title: 'Present simple : Do you…?',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne question.',
    prompt: 'Comment poser la question « Est-ce que tu aimes les chats ? » en anglais ?',
    options: [
      { id: 'a', text: 'You like cats?', isCorrect: false },
      { id: 'b', text: 'Do you like cats?', isCorrect: true },
      { id: 'c', text: 'Does you like cats?', isCorrect: false },
    ],
    correctAnswer: 'Do you like cats?',
    explanation: 'Pour poser une question avec « you », on utilise « Do » : « Do you like… ? »',
    hint: 'Pour « I » et « you » → Do. Pour « he/she » → Does.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-014',
    subject: 'anglais',
    title: 'Present simple : Does she…?',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne question.',
    prompt: 'Comment demander « Est-ce qu\'elle joue au tennis ? » en anglais ?',
    options: [
      { id: 'a', text: 'Do she play tennis?', isCorrect: false },
      { id: 'b', text: 'Does she plays tennis?', isCorrect: false },
      { id: 'c', text: 'Does she play tennis?', isCorrect: true },
    ],
    correctAnswer: 'Does she play tennis?',
    explanation: 'Pour « he/she/it », on utilise « Does » + verbe sans -s : « Does she play? ».',
    hint: 'Does + he/she/it + verbe (sans -s).',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-015',
    subject: 'anglais',
    title: 'Present simple : négation I don\'t',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme négative.',
    prompt: 'Complète : « I ___ like broccoli. »',
    options: [
      { id: 'a', text: 'doesn\'t', isCorrect: false },
      { id: 'b', text: 'don\'t', isCorrect: true },
      { id: 'c', text: 'not', isCorrect: false },
    ],
    correctAnswer: 'don\'t',
    explanation: 'Avec « I », la négation est « don\'t » : « I don\'t like ». Avec he/she → doesn\'t.',
    hint: 'I / you / we / they → don\'t. He / she / it → doesn\'t.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-016',
    subject: 'anglais',
    title: 'Present simple : négation He doesn\'t',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme négative.',
    prompt: 'Complète : « He ___ eat vegetables. »',
    options: [
      { id: 'a', text: 'don\'t', isCorrect: false },
      { id: 'b', text: 'doesn\'t', isCorrect: true },
      { id: 'c', text: 'not', isCorrect: false },
    ],
    correctAnswer: 'doesn\'t',
    explanation: 'Avec « he », la négation est « doesn\'t » + verbe sans -s : « He doesn\'t eat ».',
    hint: 'He / she / it → doesn\'t (+ verbe sans -s).',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-017',
    subject: 'anglais',
    title: 'Present simple : They live',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « They ___ in London. »',
    options: [
      { id: 'a', text: 'lives', isCorrect: false },
      { id: 'b', text: 'live', isCorrect: true },
      { id: 'c', text: 'living', isCorrect: false },
    ],
    correctAnswer: 'live',
    explanation: '« They » (ils/elles) prend la forme de base du verbe sans -s : « They live ».',
    hint: 'We / you / they → verbe sans -s.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-018',
    subject: 'anglais',
    title: 'Present simple : verbe go (3e pers.)',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « She ___ to school by bus. »',
    options: [
      { id: 'a', text: 'go', isCorrect: false },
      { id: 'b', text: 'goes', isCorrect: true },
      { id: 'c', text: 'going', isCorrect: false },
    ],
    correctAnswer: 'goes',
    explanation: 'Le verbe « go » devient « goes » à la 3e personne du singulier (he/she/it).',
    hint: 'Go → goes (verbe irrégulier à la 3e pers. sing.).',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-019',
    subject: 'anglais',
    title: 'Present simple : have got (I)',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « I ___ a dog. »',
    options: [
      { id: 'a', text: 'has got', isCorrect: false },
      { id: 'b', text: 'have got', isCorrect: true },
      { id: 'c', text: 'had got', isCorrect: false },
    ],
    correctAnswer: 'have got',
    explanation: '« Have got » s\'utilise avec I/you/we/they. « Has got » s\'utilise avec he/she/it.',
    hint: 'I → have got. He/She → has got.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-020',
    subject: 'anglais',
    title: 'Present simple : have got (She)',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne forme.',
    prompt: 'Complète : « She ___ a cat and two rabbits. »',
    options: [
      { id: 'a', text: 'have got', isCorrect: false },
      { id: 'b', text: 'has got', isCorrect: true },
      { id: 'c', text: 'is got', isCorrect: false },
    ],
    correctAnswer: 'has got',
    explanation: '« She » → « has got ». « He has got… » / « She has got… ».',
    hint: 'She → has got (pas have got).',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-021',
    subject: 'anglais',
    title: 'Present simple : adverbes de fréquence',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Que veut dire cet adverbe ?',
    prompt: 'Que veut dire « always » dans « I always eat breakfast » ?',
    options: [
      { id: 'a', text: 'Parfois', isCorrect: false },
      { id: 'b', text: 'Toujours', isCorrect: true },
      { id: 'c', text: 'Jamais', isCorrect: false },
    ],
    correctAnswer: 'Toujours',
    explanation: '« Always » = toujours. « Sometimes » = parfois. « Never » = jamais.',
    hint: 'Always → sometimes → never : du plus souvent au moins souvent.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-022',
    subject: 'anglais',
    title: 'Present simple : adverbe never',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Que veut dire cet adverbe ?',
    prompt: 'Que veut dire « never » dans « I never eat fish » ?',
    options: [
      { id: 'a', text: 'Toujours', isCorrect: false },
      { id: 'b', text: 'Souvent', isCorrect: false },
      { id: 'c', text: 'Jamais', isCorrect: true },
    ],
    correctAnswer: 'Jamais',
    explanation: '« Never » = jamais. « I never eat fish » = Je ne mange jamais de poisson.',
    hint: 'Never = jamais (sans « ne » devant le verbe en anglais).',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-023',
    subject: 'anglais',
    title: 'Present simple : question réponse',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Choisis la bonne réponse courte.',
    prompt: '— « Do you play the piano? »\n— « ___, I do. »',
    options: [
      { id: 'a', text: 'No', isCorrect: false },
      { id: 'b', text: 'Yes', isCorrect: true },
      { id: 'c', text: 'Not', isCorrect: false },
    ],
    correctAnswer: 'Yes',
    explanation: 'On répond « Yes, I do. » ou « No, I don\'t. » aux questions avec Do.',
    hint: 'Short answer : Yes, I do. / No, I don\'t.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-gram-024',
    subject: 'anglais',
    title: 'Present simple : routine quotidienne',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'grammaire',
    subskill: 'present-simple',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « She wakes up at 7 o\'clock every morning » en français ?',
    options: [
      { id: 'a', text: 'Elle se couche à 7 heures chaque matin.', isCorrect: false },
      { id: 'b', text: 'Elle se réveille à 7 heures chaque matin.', isCorrect: true },
      { id: 'c', text: 'Elle mange à 7 heures chaque matin.', isCorrect: false },
    ],
    correctAnswer: 'Elle se réveille à 7 heures chaque matin.',
    explanation: '« Wake up » = se réveiller. « Every morning » = chaque matin. « At 7 o\'clock » = à 7 heures.',
    hint: '« Wake up » = se réveiller.',
    tags: ['ce2', 'anglais', 'grammaire', 'present-simple', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
