import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe2VocSalutationsExercises: EnglishExercise[] = [
  {
    id: 'en-ce2-voc-001',
    subject: 'anglais',
    title: 'Phrase : How are you?',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « How are you? » en français ?',
    options: [
      { id: 'a', text: "Comment t'appelles-tu ?", isCorrect: false },
      { id: 'b', text: 'Comment vas-tu ?', isCorrect: true },
      { id: 'c', text: 'Quel âge as-tu ?', isCorrect: false },
    ],
    correctAnswer: 'Comment vas-tu ?',
    explanation: '« How are you? » veut dire "Comment vas-tu ?" en français.',
    hint: '« How » = comment, « are you » = vas-tu.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-002',
    subject: 'anglais',
    title: "Réponse : I'm fine",
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette réponse ?',
    prompt: "Que veut dire « I'm fine » en français ?",
    options: [
      { id: 'a', text: "Je m'appelle", isCorrect: false },
      { id: 'b', text: 'Je vais bien', isCorrect: true },
      { id: 'c', text: "J'ai faim", isCorrect: false },
    ],
    correctAnswer: 'Je vais bien',
    explanation: "« I'm fine » veut dire « Je vais bien » en français.",
    hint: '« Fine » veut dire bien.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-003',
    subject: 'anglais',
    title: 'Phrase : What is your name?',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'salutations',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Que veut dire « What is your name? » en français ?',
    options: [
      { id: 'a', text: 'Quel âge as-tu ?', isCorrect: false },
      { id: 'b', text: "Comment t'appelles-tu ?", isCorrect: true },
      { id: 'c', text: 'Où habites-tu ?', isCorrect: false },
    ],
    correctAnswer: "Comment t'appelles-tu ?",
    explanation: "« What is your name? » veut dire \"Comment t'appelles-tu ?\" en français.",
    hint: '« Name » veut dire nom.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'salutations', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
