import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe2CommExercises: EnglishExercise[] = [
  {
    id: 'en-ce2-comp-001',
    subject: 'anglais',
    title: 'Dialogue : at school',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue et réponds.',
    prompt: '— « What subject do you like? »\n— « I like maths. »\nQue veut dire « subject » ici ?',
    options: [
      { id: 'a', text: 'Un sujet de conversation', isCorrect: false },
      { id: 'b', text: 'Une matière scolaire', isCorrect: true },
      { id: 'c', text: 'Un exercice', isCorrect: false },
    ],
    correctAnswer: 'Une matière scolaire',
    explanation: '« Subject » = matière scolaire (maths, English, science…).',
    hint: '« Maths », « English », « Science » sont des subjects.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-002',
    subject: 'anglais',
    title: 'Dialogue : at home',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue et réponds.',
    prompt: '— « What are you doing? »\n— « I am watching TV. »\nQue fait cette personne ?',
    options: [
      { id: 'a', text: 'Elle lit un livre.', isCorrect: false },
      { id: 'b', text: 'Elle regarde la télévision.', isCorrect: true },
      { id: 'c', text: 'Elle écoute de la musique.', isCorrect: false },
    ],
    correctAnswer: 'Elle regarde la télévision.',
    explanation: '« Watching TV » = regarder la télé. « What are you doing? » = Qu\'est-ce que tu fais ?',
    hint: '« Watching » = regarder. « TV » = télévision.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-003',
    subject: 'anglais',
    title: 'Dialogue : asking for help',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Un élève dit « Can you help me, please? ». Que demande-t-il ?',
    options: [
      { id: 'a', text: 'Il demande à sortir.', isCorrect: false },
      { id: 'b', text: 'Il demande de l\'aide.', isCorrect: true },
      { id: 'c', text: 'Il demande à aller aux toilettes.', isCorrect: false },
    ],
    correctAnswer: 'Il demande de l\'aide.',
    explanation: '« Help me » = aide-moi. « Can you help me? » = Est-ce que tu peux m\'aider ?',
    hint: '« Help » = aider.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-004',
    subject: 'anglais',
    title: 'Mini-dialogue : birthday',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette expression ?',
    prompt: 'Ton ami dit « Happy birthday! ». Que fête-t-il ?',
    options: [
      { id: 'a', text: 'La nouvelle année', isCorrect: false },
      { id: 'b', text: 'Ton anniversaire', isCorrect: true },
      { id: 'c', text: 'La fin de l\'école', isCorrect: false },
    ],
    correctAnswer: 'Ton anniversaire',
    explanation: '« Happy birthday! » = Joyeux anniversaire ! « Birthday » = anniversaire.',
    hint: '« Birth » = naissance. « Day » = jour.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-005',
    subject: 'anglais',
    title: 'Mini-dialogue : weather',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « What\'s the weather like today? »\n— « It\'s sunny! »\nQuel temps fait-il ?',
    options: [
      { id: 'a', text: 'Il pleut.', isCorrect: false },
      { id: 'b', text: 'Il fait beau / il y a du soleil.', isCorrect: true },
      { id: 'c', text: 'Il neige.', isCorrect: false },
    ],
    correctAnswer: 'Il fait beau / il y a du soleil.',
    explanation: '« Sunny » = ensoleillé. « What\'s the weather like? » = Quel temps fait-il ?',
    hint: '« Sunny » vient de « sun » (soleil).',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-006',
    subject: 'anglais',
    title: 'Dialogue : inviting a friend',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « Do you want to come to my house? »\n— « Yes, I\'d love to! »\nQue répond l\'ami ?',
    options: [
      { id: 'a', text: 'Il refuse l\'invitation.', isCorrect: false },
      { id: 'b', text: 'Il accepte l\'invitation avec plaisir.', isCorrect: true },
      { id: 'c', text: 'Il pose une question.', isCorrect: false },
    ],
    correctAnswer: 'Il accepte l\'invitation avec plaisir.',
    explanation: '« I\'d love to! » = J\'adorerais ! / Avec plaisir ! C\'est une façon enthousiaste d\'accepter.',
    hint: '« Love to » = adorer faire quelque chose.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-007',
    subject: 'anglais',
    title: 'Dialogue : my daily routine',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I have breakfast at eight o\'clock » en français ?',
    options: [
      { id: 'a', text: 'Je déjeune à 8 heures.', isCorrect: false },
      { id: 'b', text: 'Je prends mon petit-déjeuner à 8 heures.', isCorrect: true },
      { id: 'c', text: 'Je dîne à 8 heures.', isCorrect: false },
    ],
    correctAnswer: 'Je prends mon petit-déjeuner à 8 heures.',
    explanation: '« Breakfast » = petit-déjeuner. « Have breakfast » = prendre son petit-déjeuner.',
    hint: '« Breakfast » = break + fast = casser le jeûne (le repas qui suit le jeûne de la nuit).',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-008',
    subject: 'anglais',
    title: 'Dialogue : asking the time',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette question ?',
    prompt: 'Quelqu\'un demande « What time is it? ». Que veut-il savoir ?',
    options: [
      { id: 'a', text: 'Quel jour sommes-nous ?', isCorrect: false },
      { id: 'b', text: 'Quelle heure est-il ?', isCorrect: true },
      { id: 'c', text: 'Depuis combien de temps es-tu là ?', isCorrect: false },
    ],
    correctAnswer: 'Quelle heure est-il ?',
    explanation: '« What time is it? » = Quelle heure est-il ? On répond : « It\'s three o\'clock. »',
    hint: '« Time » = temps / heure. « What time » = quelle heure.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-009',
    subject: 'anglais',
    title: 'Dialogue : telling the time',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette réponse ?',
    prompt: '— « What time is it? »\n— « It\'s half past two. »\nQuelle heure est-il ?',
    options: [
      { id: 'a', text: '2 heures', isCorrect: false },
      { id: 'b', text: '2 heures et demie', isCorrect: true },
      { id: 'c', text: '2 heures moins le quart', isCorrect: false },
    ],
    correctAnswer: '2 heures et demie',
    explanation: '« Half past two » = 2 heures et demie (2h30). « Half » = demi. « Past » = passé.',
    hint: '« Half » = moitié / demi.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-010',
    subject: 'anglais',
    title: 'Dialogue : school subjects',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « Do you like PE? »\n— « Yes, it\'s my favourite! »\nQue veut dire « PE » ?',
    options: [
      { id: 'a', text: 'Les maths', isCorrect: false },
      { id: 'b', text: 'L\'éducation physique / sport', isCorrect: true },
      { id: 'c', text: 'L\'anglais', isCorrect: false },
    ],
    correctAnswer: 'L\'éducation physique / sport',
    explanation: '« PE » = Physical Education = éducation physique (la gym / le sport à l\'école).',
    hint: '« Physical » = physique. PE = éducation physique.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-011',
    subject: 'anglais',
    title: 'Dialogue : describing someone',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis cette description.',
    prompt: '« She has got long brown hair and blue eyes. »\nComment est cette personne ?',
    options: [
      { id: 'a', text: 'Elle a les cheveux courts et les yeux verts.', isCorrect: false },
      { id: 'b', text: 'Elle a les cheveux longs bruns et les yeux bleus.', isCorrect: true },
      { id: 'c', text: 'Elle a les cheveux longs blonds et les yeux bleus.', isCorrect: false },
    ],
    correctAnswer: 'Elle a les cheveux longs bruns et les yeux bleus.',
    explanation: '« Long » = long. « Brown hair » = cheveux bruns. « Blue eyes » = yeux bleus.',
    hint: '« Brown » = marron/brun. « Blue » = bleu.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-012',
    subject: 'anglais',
    title: 'Dialogue : talking about pets',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « Have you got a pet? »\n— « Yes, I have a dog. His name is Max. »\nQuel animal a cet enfant ?',
    options: [
      { id: 'a', text: 'Un chat', isCorrect: false },
      { id: 'b', text: 'Un chien', isCorrect: true },
      { id: 'c', text: 'Un lapin', isCorrect: false },
    ],
    correctAnswer: 'Un chien',
    explanation: '« Dog » = chien. « Have you got a pet? » = Est-ce que tu as un animal de compagnie ?',
    hint: '« Pet » = animal de compagnie. « Dog » = chien.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-013',
    subject: 'anglais',
    title: 'Dialogue : expressing feelings',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I am happy today » en français ?',
    options: [
      { id: 'a', text: 'Je suis fatigué aujourd\'hui.', isCorrect: false },
      { id: 'b', text: 'Je suis heureux/heureuse aujourd\'hui.', isCorrect: true },
      { id: 'c', text: 'Je suis triste aujourd\'hui.', isCorrect: false },
    ],
    correctAnswer: 'Je suis heureux/heureuse aujourd\'hui.',
    explanation: '« Happy » = heureux/heureuse. « Today » = aujourd\'hui.',
    hint: '« Happy » = content(e) / heureux.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-014',
    subject: 'anglais',
    title: 'Dialogue : feelings (sad)',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « She is sad because she lost her toy » ?',
    options: [
      { id: 'a', text: 'Elle est contente car elle a trouvé son jouet.', isCorrect: false },
      { id: 'b', text: 'Elle est triste parce qu\'elle a perdu son jouet.', isCorrect: true },
      { id: 'c', text: 'Elle est fatiguée après avoir joué.', isCorrect: false },
    ],
    correctAnswer: 'Elle est triste parce qu\'elle a perdu son jouet.',
    explanation: '« Sad » = triste. « Because » = parce que. « Lost » = perdu. « Toy » = jouet.',
    hint: '« Sad » est le contraire de « happy ». « Because » = parce que.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-015',
    subject: 'anglais',
    title: 'Dialogue : at the shop',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « How much is it? »\n— « It\'s two euros. »\nQue veut dire « How much is it? » ?',
    options: [
      { id: 'a', text: 'C\'est pour qui ?', isCorrect: false },
      { id: 'b', text: 'C\'est combien ?', isCorrect: true },
      { id: 'c', text: 'Tu as combien ?', isCorrect: false },
    ],
    correctAnswer: 'C\'est combien ?',
    explanation: '« How much? » = combien ? C\'est la question pour demander un prix.',
    hint: '« How much? » = combien (pour un prix).',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-016',
    subject: 'anglais',
    title: 'Dialogue : giving opinions',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I think it\'s great! » en français ?',
    options: [
      { id: 'a', text: 'Je pense que c\'est nul.', isCorrect: false },
      { id: 'b', text: 'Je pense que c\'est super !', isCorrect: true },
      { id: 'c', text: 'Je sais que c\'est grand.', isCorrect: false },
    ],
    correctAnswer: 'Je pense que c\'est super !',
    explanation: '« I think » = je pense. « Great » = super / formidable.',
    hint: '« I think » = je pense. « Great » = très bien / super.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-017',
    subject: 'anglais',
    title: 'Dialogue : at home (chores)',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Que veut dire cette phrase ?',
    prompt: 'Que veut dire « I help my mum at home » en français ?',
    options: [
      { id: 'a', text: 'Je joue avec ma maman.', isCorrect: false },
      { id: 'b', text: 'J\'aide ma maman à la maison.', isCorrect: true },
      { id: 'c', text: 'Je regarde ma maman travailler.', isCorrect: false },
    ],
    correctAnswer: 'J\'aide ma maman à la maison.',
    explanation: '« Help » = aider. « At home » = à la maison.',
    hint: '« Help » = aider. « At home » = à la maison.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-comp-018',
    subject: 'anglais',
    title: 'Dialogue : weekend plans',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'comprehension',
    subskill: 'communication',
    format: 'qcm',
    instructions: 'Lis ce dialogue.',
    prompt: '— « What do you do at the weekend? »\n— « I go to the park with my family. »\nQue fait cet enfant le week-end ?',
    options: [
      { id: 'a', text: 'Il reste à la maison.', isCorrect: false },
      { id: 'b', text: 'Il va au parc avec sa famille.', isCorrect: true },
      { id: 'c', text: 'Il va à l\'école le week-end.', isCorrect: false },
    ],
    correctAnswer: 'Il va au parc avec sa famille.',
    explanation: '« Go to the park » = aller au parc. « With my family » = avec ma famille.',
    hint: '« Go to » = aller à. « Park » = parc.',
    tags: ['ce2', 'anglais', 'comprehension', 'communication', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
