import { cloneDefaultAdaptations } from '../../../core/exercise-core.adaptations';
import type { EnglishExercise } from '../english.types';

export const englishCe2VocCorpsExercises: EnglishExercise[] = [
  {
    id: 'en-ce2-voc-004',
    subject: 'anglais',
    title: 'Corps : nose',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « nose » en français ?',
    options: [
      { id: 'a', text: 'Le nez', isCorrect: true },
      { id: 'b', text: 'La bouche', isCorrect: false },
      { id: 'c', text: "L'oreille", isCorrect: false },
    ],
    correctAnswer: 'Le nez',
    explanation: '« Nose » veut dire nez en français.',
    hint: 'Il est au milieu du visage.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-005',
    subject: 'anglais',
    title: 'Corps : eye',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « eye » en français ?',
    options: [
      { id: 'a', text: 'Le pied', isCorrect: false },
      { id: 'b', text: "L'œil", isCorrect: true },
      { id: 'c', text: 'Le dos', isCorrect: false },
    ],
    correctAnswer: "L'œil",
    explanation: '« Eye » veut dire œil en français.',
    hint: "On s'en sert pour voir.",
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-006',
    subject: 'anglais',
    title: 'Corps : leg',
    schoolClass: 'CE2',
    generalLevel: 'intermediate',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « leg » en français ?',
    options: [
      { id: 'a', text: 'Le bras', isCorrect: false },
      { id: 'b', text: 'La jambe', isCorrect: true },
      { id: 'c', text: "L'épaule", isCorrect: false },
    ],
    correctAnswer: 'La jambe',
    explanation: '« Leg » veut dire jambe en français.',
    hint: 'Elle sert à marcher et à courir.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-015',
    subject: 'anglais',
    title: 'Corps : arm',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « arm » en français ?',
    options: [
      { id: 'a', text: 'La jambe', isCorrect: false },
      { id: 'b', text: 'Le bras', isCorrect: true },
      { id: 'c', text: 'Le pied', isCorrect: false },
    ],
    correctAnswer: 'Le bras',
    explanation: '« Arm » veut dire bras en français.',
    hint: "Il relie l'épaule à la main.",
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
  {
    id: 'en-ce2-voc-016',
    subject: 'anglais',
    title: 'Corps : foot',
    schoolClass: 'CE2',
    generalLevel: 'beginner',
    skill: 'vocabulaire',
    subskill: 'corps',
    format: 'qcm',
    instructions: 'Quelle partie du corps est-ce ?',
    prompt: 'Que veut dire « foot » en français ?',
    options: [
      { id: 'a', text: 'Le genou', isCorrect: false },
      { id: 'b', text: 'La main', isCorrect: false },
      { id: 'c', text: 'Le pied', isCorrect: true },
    ],
    correctAnswer: 'Le pied',
    explanation: '« Foot » veut dire pied en français.',
    hint: 'On joue au football avec.',
    tags: ['ce2', 'anglais', 'vocabulaire', 'corps', 'qcm'],
    estimatedMinutes: 2,
    adaptations: cloneDefaultAdaptations(),
  },
];
